### ISSUE TITLE
Failure of logistic regression example

### ISSUE THREAD

**Issue by fonnesbeck** [Theano/Theano#1439]
The logistic regression example at the end of the tutorial examples page for the 0.6rc3 docs fails with a ton of errors resembling this one:

```
ERROR (theano.gof.opt): Optimization failure due to: local_mul_canonizer
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/theano/gof/opt.py", line 1206, in process_node
    replacements = lopt.transform(node)
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 2894, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum))
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 2761, in simplify
    rval = self.simplify_constants(*self.simplify_factors(num, denum))
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 2803, in simplify_constants
    out_type = self.merge_num_denum(orig_num, orig_denum).type
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 2738, in merge_num_denum
    return self.main(*num)
  File "/Library/Python/2.7/site-packages/theano/gof/op.py", line 407, in __call__
    raise ValueError('Cannot compute test value: input %i (%s) of Op %s missing default value' % (i, ins, node))
ValueError: Cannot compute test value: input 1 (Elemwise{add,no_inplace}.0) of Op Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.1}, Elemwise{add,no_inplace}.0) missing default value
```

[Here is the complete output](https://gist.github.com/5889501), which includes the version of Theano that I am using. Running OS X 10.8.4 on a 2011 MacBook Air 11".

**Comment by physhik** [comment]
I saw the same kind of error messages, and deletion of the directory .theano worked for me. Don't know why it does.
