### ISSUE TITLE
Cannot import Theano in python 3.3

### ISSUE THREAD

**Issue by kaizhang** [Theano/Theano#1527]
I got following error when I tried to import theano under python 3.3. Theano version: 0.6rc3

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.3/dist-packages/theano/__init__.py", line 48, in <module>
    from . import gof
  File "/usr/local/lib/python3.3/dist-packages/theano/gof/__init__.py", line 40, in <module>
    from .cc import \
  File "/usr/local/lib/python3.3/dist-packages/theano/gof/cc.py", line 48, in <module>
    from . import link
  File "/usr/local/lib/python3.3/dist-packages/theano/gof/link.py", line 4, in <module>
    from .type import Type
  File "/usr/local/lib/python3.3/dist-packages/theano/gof/type.py", line 12, in <module>
    from theano.gof.op import CLinkerObject
  File "/usr/local/lib/python3.3/dist-packages/theano/gof/op.py", line 25, in <module>
    from . import cc
ImportError: cannot import name cc

**Comment by nouiz** [comment]
As no answer, I close as it work for us.
