### ISSUE TITLE
Trying to call nvcc with an OpenCL context

### ISSUE THREAD

**Issue by marcino239** [Theano/Theano#2190]
I'm not sure what the status of opencl implementation is in theano, but I'm getting the following exception when running example from [deeplearning.net](http://deeplearning.net/tutorial/logreg.html#logreg):
```
(trusty)marcino@localhost:~/work/DeepLearningTutorials/code$ THEANO_FLAGS="device=opencl0:0,floatX=float32" python logistic_sgd.py 
Using device opencl0:0: Mali-T604
... loading data
... building the model
Traceback (most recent call last):
  File "logistic_sgd.py", line 438, in <module>
    sgd_optimization_mnist()
  File "logistic_sgd.py", line 340, in sgd_optimization_mnist
    y: train_set_y[index * batch_size: (index + 1) * batch_size]
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/compile/function.py", line 265, in function
    profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/compile/function_module.py", line 1341, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/compile/function_module.py", line 1207, in create
    _fn, _i, _o = self.linker.make_thunk(input_storage=input_storage_lists)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gof/link.py", line 489, in make_thunk
    output_storage=output_storage)[:3]
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gof/vm.py", line 891, in make_all
    no_recycling))
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gof/op.py", line 724, in make_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gof/cc.py", line 1023, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gof/cc.py", line 965, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gof/cc.py", line 1395, in cthunk_factory
    key = self.cmodule_key()
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gof/cc.py", line 1104, in cmodule_key
    compile_args=self.compile_args(),
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gof/cc.py", line 822, in compile_args
    ret += c_compiler.compile_args()
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/sandbox/gpuarray/comp.py", line 43, in compile_args
    raise Exception, "Trying to call nvcc with an OpenCL context"
Exception: ('The following error happened while compiling the node', GpuCrossentropySoftmaxArgmax1HotWithBias(GpuDot22.0, b, GpuElemwise{Cast{int32}}[]<gpuarray>.0), '\n', 'Trying to call nvcc with an OpenCL context')
```

**Comment by jongwook** [comment]
I still see the same error with Theano 0.7 and https://github.com/Theano/libgpuarray/commit/34967bb8a37bad38227edd46e2b09ed58bfca393.

Any reason or follow-up issue that could explain why this is closed?

**Comment by abergeron** [comment]
This was fixed in the theano master with https://github.com/Theano/Theano/pull/3364

**Comment by nouiz** [comment]
So you need to use the development version: 

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
