### ISSUE TITLE
Random error in Test with python 3

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2402]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/46914094/log.txt

This happen on travis. See the real log.

I restart the failed jobs to have a clean travis history.

**Comment by abergeron** [comment]
I have no idea what error do you mean.  This log seems clean.

**Comment by nouiz** [comment]
I restarted the corresponding travis part and this override the original output. I taught they where keeping all of them...

When there is a new one, I'll copy the error here.

**Comment by abergeron** [comment]
Is it the "Apply() < Apply()" one?  Because I've seen it a couple of times.

**Comment by abergeron** [comment]
This would be an example: https://s3.amazonaws.com/archive.travis-ci.org/jobs/47025241/log.txt, if it is indeed the Apply() problem.

**Comment by nouiz** [comment]
This is what I fixed many times by restart travis and linked to (but got
changed).

**Comment by nouiz** [comment]
New error:

======================================================================

ERROR: theano.compile.tests.test_profiling.test_profiling

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/miniconda/envs/pyenv/lib/python3.3/site-packages/nose/case.py", line 198, in runTest

self.test(*self.arg)

File "/home/travis/miniconda/envs/pyenv/lib/python3.3/site-packages/theano/compile/tests/test_profiling.py", line 44, in test_profiling

f.profile.summary(buf)

File "/home/travis/miniconda/envs/pyenv/lib/python3.3/site-packages/theano/compile/profiling.py", line 1208, in summary

self.summary_class(file, n_ops_to_print)

File "/home/travis/miniconda/envs/pyenv/lib/python3.3/site-packages/theano/compile/profiling.py", line 367, in summary_class

otimes.sort()

TypeError: unorderable types: type() < type()

----------------------------------------------------------------------

**Comment by nouiz** [comment]
fixed.
