### ISSUE TITLE
theano-cache purge error

### ISSUE THREAD

**Issue by JesseLivezey** [Theano/Theano#2428]
When I run ```theano-cache purge```, I get

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/jesse/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/jesse/Development/Theano/theano/gof/cmodule.py", line 1324, in _on_atexit
    self.clear_old()
  File "/home/jesse/Development/Theano/theano/gof/cmodule.py", line 1167, in clear_old
    delete_if_problem=delete_if_problem)
  File "/home/jesse/Development/Theano/theano/gof/cmodule.py", line 852, in refresh
    del root, files, subdirs
UnboundLocalError: local variable 'files' referenced before assignment
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/jesse/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/jesse/Development/Theano/theano/gof/cmodule.py", line 1324, in _on_atexit
    self.clear_old()
  File "/home/jesse/Development/Theano/theano/gof/cmodule.py", line 1167, in clear_old
    delete_if_problem=delete_if_problem)
  File "/home/jesse/Development/Theano/theano/gof/cmodule.py", line 852, in refresh
    del root, files, subdirs
UnboundLocalError: local variable 'files' referenced before assignment
```

from this line
https://github.com/Theano/Theano/blob/f0efd2a729d856bdbf70ad4e5415898833191648/theano/gof/cmodule.py#L852

**Comment by nouiz** [comment]
thanks for the report. I added a fix in this PR:

https://github.com/Theano/Theano/pull/2427
