### ISSUE TITLE
Theano Import Crash

### ISSUE THREAD

**Issue by mshahriarinia** [Theano/Theano#2546]
on OS X Yosemite 10.10 with Canopy EPD python, I installed GCC 4.9.2 according to [here](https://solarianprogrammer.com/2013/06/11/compiling-gcc-mac-os-x/). Then I added  aliases to `~/.bashrc`

```
export PATH="/usr/gcc-4.9.2/bin/:$PATH"
alias gcc='gcc-4.9.2'
alias cc='gcc-4.9.2'
alias g++='g++-4.9.2'
alias c++='c++-4.9.2'
```

```
$ sudo pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
$ python -c "import theano;"
```
Then it prints a file with 01080 lines of code (here I just post the last few lines) and then the following error
```
01070	#else
01071	    m = Py_InitModule3("lazylinker_ext", lazylinker_ext_methods,
01072	                       "Example module that creates an extension type.");
01073	#endif
01074	    Py_INCREF(&lazylinker_ext_CLazyLinkerType);
01075	    PyModule_AddObject(m, "CLazyLinker", (PyObject *)&lazylinker_ext_CLazyLinkerType);
01076	
01077	    return RETVAL;
01078	}
01079	
01080	
===============================
Problem occurred during compilation with the command line below:
/usr/bin/clang++ -dynamiclib -g -march=i686 -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include -I/Applications/Canopy.app/appdata/canopy-1.5.2.2785.macosx-x86_64/Canopy.app/Contents/include/python2.7 -o /Users/morteza/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64/lazylinker_ext/lazylinker_ext.so /Users/morteza/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64/lazylinker_ext/mod.cpp -L/Applications/Canopy.app/appdata/canopy-1.5.2.2785.macosx-x86_64/Canopy.app/Contents/lib
ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/__init__.py", line 55, in <module>
    from theano.compile import \
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/compile/__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/compile/function_module.py", line 18, in <module>
    import theano.compile.mode
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/gof/vm.py", line 568, in <module>
    import lazylinker_c
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/gof/lazylinker_c.py", line 116, in <module>
    preargs=args)
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1992, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture x86_64. clang: error: linker command failed with exit code 1 (use -v to see invocation). 
```
Everything except this works fine and I can import numpy, matplotlib, etc with no problem. Any thoughts on how to fix this?

Or when I set other variables 

```
export CC=/usr/gcc-4.9.2/bin/gcc
export CXX=/usr/gcc-4.9.2/bin/g++
export CPP=/usr/gcc-4.9.2/bin/cpp
export LD=/usr/gcc-4.9.2/bin/gcc
alias c++=/usr/gcc-4.9.2/bin/c++
alias g++=/usr/gcc-4.9.2/bin/g++
alias gcc=/usr/gcc-4.9.2/bin/gcc
alias cpp=/usr/gcc-4.9.2/bin/cpp
alias ld=/usr/gcc-4.9.2/bin/gcc
alias cc=/usr/gcc-4.9.2/bin/gcc
```
I get

```
01044	#endif
01045	    Py_INCREF(&lazylinker_ext_CLazyLinkerType);
01046	    PyModule_AddObject(m, "CLazyLinker", (PyObject *)&lazylinker_ext_CLazyLinkerType);
01047	
01048	    return RETVAL;
01049	}
01050	
01051	
===============================
Problem occurred during compilation with the command line below:
g++ -dynamiclib -g -march=ivybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=ivybridge -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include -I/Applications/Canopy.app/appdata/canopy-1.5.2.2785.macosx-x86_64/Canopy.app/Contents/include/python2.7 -o /Users/morteza/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64/lazylinker_ext/lazylinker_ext.so /Users/morteza/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64/lazylinker_ext/mod.cpp -L/Applications/Canopy.app/appdata/canopy-1.5.2.2785.macosx-x86_64/Canopy.app/Contents/lib

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/__init__.py", line 55, in <module>
    from theano.compile import \
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/compile/__init__.py", line 6, in <module>
    from theano.compile.function_module import *
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/compile/function_module.py", line 18, in <module>
    import theano.compile.mode
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/gof/vm.py", line 516, in <module>
    import lazylinker_c
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/gof/lazylinker_c.py", line 86, in <module>
    preargs=args)
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1971, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): 
```

**Comment by abergeron** [comment]
Tickets are not the appropriate channel for support questions.  You should use the theano-users mailing list.

Theano uses clang by default on OS X and we strongly suggest staying with that default since a lot of weird hangs and crashes have been observed while using gcc.

What you should do to get a working compiler is install XCode from the App Store and run it once (so that it sets up the command line tools).

If you insist on using gcc, then you can set the cxx flag to the full path to whatever version of g++ you want to use and it will use that.  No need to mess around with aliases and such.

**Comment by mshahriarinia** [comment]
The point is that in the [Installing Theano](http://deeplearning.net/software/theano/install.html) webpage or even [here](http://deeplearning.net/software/theano/install.html#macports) there is no talk about CLANG. Right in the MacOS section it strictly says "Then you must install g++." That's why I went for gcc rather than mess with clang++.

**Comment by nouiz** [comment]
It is in our todo list to update the doc. I made a ticket of this:

https://github.com/Theano/Theano/issues/2547

Until then, follow what @abergeron told you.
