### ISSUE TITLE
Weird optimization failure

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#2676]
With floatX=float64:

```
In [1]: import theano

In [2]: a = theano.tensor.fmatrix(); b = theano.tensor.nnet.sigmoid(a); c = theano.tensor.log(theano.tensor.ones(b.shape) - b)

In [3]: f = theano.function([a], c)
ERROR (theano.gof.opt): Optimization failure due to: Elemwise{log,no_inplace}(Elemwise{sub,no_inplace}(y subject to <function _is_1 at 0x105fd00d0>, sigmoid(x))) -> Elemwise{neg,no_inplace}(softplus(x))
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/dwf/miniconda/envs/blocks-dev/lib/python3.4/site-packages/Theano-0.6.0-py3.4.egg/theano/gof/opt.py", line 1524, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/Users/dwf/miniconda/envs/blocks-dev/lib/python3.4/site-packages/Theano-0.6.0-py3.4.egg/theano/gof/toolbox.py", line 258, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/Users/dwf/miniconda/envs/blocks-dev/lib/python3.4/site-packages/Theano-0.6.0-py3.4.egg/theano/gof/fg.py", line 467, in replace
    raise TypeError("The type of the replacement must be the same as the type of the original Variable.", r, new_r, r.type, new_r.type, str(reason))
TypeError: ('The type of the replacement must be the same as the type of the original Variable.', Elemwise{log,no_inplace}.0, Elemwise{neg,no_inplace}.0, TensorType(float64, matrix), TensorType(float32, matrix), 'Elemwise{log,no_inplace}(Elemwise{sub,no_inplace}(y subject to <function _is_1 at 0x105fd00d0>, sigmoid(x))) -> Elemwise{neg,no_inplace}(softplus(x))')
```

I agree that using `fmatrix()` with floatX=float64 is a little weird but I'd expect this optimization to run fine. It's replacing a dtype=float64 output op expression (the log, `c` in my example).

Is this the fault of `nnet.softplus` not respecting `floatX`? (It seems `nnet.sigmoid` doesn't either).

**Comment by dwf** [comment]
The issue seems to be that using ones() instead of "1" up-promotes the argument of `log` to float64.

**Comment by lamblin** [comment]
`floatX` is a default, and sometimes used to avoid some upcasting, but the dtype of inputs is usually what should be respected.
`ones()` will indeed default to `floatX`, here `float64`, forcing the upcast of the argument of `log`, so `c` will be `float64`.
I *think* the right fix would be for the optimization to compute `-softplus(-cast(a, c.dtype))`.
But in that case, there would be no warning sign that you actually may want to define `c = log(ones_like(b) - b)` instead.
