### ISSUE TITLE
Crash for T.concatenate([x, x], axis=-1) grad

### ISSUE THREAD

**Issue by tscohen** [Theano/Theano#2747]
Hi Theano devs, thanks for writing this great tool.

When I use the fast_run optimizer the following code raises an exception. It works when I use fast_compile, or when I replace the axis=-1 with axis=0 (or whatever the last axis of the argument may be). Since this works under one optimizer and not under another, I think its is a bug and not just a missing feature.

```python
import numpy as np
import theano
import theano.tensor as T

theano.config.exception_verbosity = 'high'
theano.config.optimizer = 'fast_run'
#theano.config.optimizer = 'fast_compile'

X = T.dvector()  # or dmatrix, dtensor3, ...
f = T.concatenate([X, X], axis=-1).sum()  # This fails with fast_run but succeeds with fast_compile
#f = T.concatenate([X, X], axis=0).sum()  # This always works
grad = T.grad(f, wrt=[X])
fg = theano.function([X], grad)
fg(np.random.randn(10))
```

The error I get is:
```
python concat_test.py 
Traceback (most recent call last):
  File "concat_test.py", line 15, in <module>
    fg(np.random.randn(10))
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/theano/gof/op.py", line 768, in rval
    r = p(n, [x[0] for x in i], o)
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/theano/tensor/basic.py", line 3205, in perform
    (numpy.sum(splits), len_along_axis))
ValueError: The splits sum to 20, expected 10
Apply node that caused the error: Split{2}(Alloc.0, TensorConstant{-1}, MakeVector.0)
Inputs types: [TensorType(float64, vector), TensorType(int8, scalar), TensorType(int64, vector)]
Inputs shapes: [(10,), (), (2,)]
Inputs strides: [(8,), (), (8,)]
Inputs values: ['not shown', array(-1, dtype=int8), array([10, 10])]

Backtrace when the node is created:
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1089, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)

Debugprint of the apply node: 
Split{2}.0 [@A] <TensorType(float64, vector)> ''   
 |Alloc [@B] <TensorType(float64, vector)> ''   
 | |TensorConstant{(1,) of 1.0} [@C] <TensorType(float64, (True,))>
 | |Shape_i{0} [@D] <TensorType(int64, scalar)> ''   
 |   |<TensorType(float64, vector)> [@E] <TensorType(float64, vector)>
 |TensorConstant{-1} [@F] <TensorType(int8, scalar)>
 |MakeVector [@G] <TensorType(int64, vector)> ''   
   |Shape_i{0} [@D] <TensorType(int64, scalar)> ''   
   |Shape_i{0} [@D] <TensorType(int64, scalar)> ''   
Split{2}.1 [@A] <TensorType(float64, vector)> ''   

Storage map footprint:
 - MakeVector.0, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - TensorConstant{(1,) of 1.0}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{-1}, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - <TensorType(float64, vector)>, Shape: (10,), ElemSize: 8 Byte(s), TotalSize: 80 Byte(s)
 - Alloc.0, Shape: (10,), ElemSize: 8 Byte(s), TotalSize: 80 Byte(s)
```

I'm on a mac, using the anaconda python stack.

**Comment by nouiz** [comment]
This is similar to gh-2613. The problem come from the Split op, not the Join. Split is generated in the grad of Join.

Mostly, we didn't expected negative axis for concatenate. Use 0 or positive axis and it will work for now, until it get fixed.

thanks for the report.

**Comment by dwf** [comment]
@orhanf Any update on this?

**Comment by bouthilx** [comment]
@nouiz I don't think it is much related to #2613. The crash happens when running on CPU (with op ```Join```) while the bug fixed by the PR is only on the GPU (with op ```GpuJoin```). The problem was that Join doesn't need to process negative axis values as ```numpy.concatenate``` and ```PyArray_Concatenate``` are already doing it, but that wasn't the case for ```GpuJoin```, which is not using any of them.

**Comment by orhanf** [comment]
Simplest solutions seems to be fixing the negative axis in the `make_node` of `Join` op.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/issues/2613 did that for GpuJoin.

This is good for constant (so doing the same fix on the CPU is good).

But in the other PR case, this do not fix the problem with the axis is
symbolic. Be sure to test that case after doing the fix in the make_node.
If that isn't enough, you need to add a fix in the perform and/or c_code
too.

**Comment by nouiz** [comment]
Done.
