### ISSUE TITLE
printing.Print inside scan

### ISSUE THREAD

**Issue by AndreasMadsen** [Theano/Theano#2755]
I'm trying to debug a `scan` operation and I'm suspecting that the initial iteration is fine, how the next iterations aren't. As I understand `theano.printing.Print` is the only way for me to print intermediate values in such case. However I get an error when I print inside the _inner function_. Calling `theano.printing.Print` anywhere else works fine.

```python
import numpy as np
import theano
import theano.tensor as T

theano.config.exception_verbosity = 'high'

t = T.iscalar('T')
prints = []

def scanner(t, total):
    prints.append(theano.printing.Print('T')(t))
    return total + t

cumsum, updates = theano.scan(
    fn=scanner,
    sequences=T.arange(0, t),
    outputs_info=[T.zeros(1, dtype='int32')]
)
total = cumsum[-1]

calc = theano.function(
    inputs=[t],
    outputs=[total] + prints,
    updates=updates
)

print('result:', calc(10))
```

The error is:

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    updates=updates
  File "/usr/local/lib/python3.4/site-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/usr/local/lib/python3.4/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/usr/local/lib/python3.4/site-packages/theano/compile/function_module.py", line 1465, in orig_function
    on_unused_input=on_unused_input).create(
  File "/usr/local/lib/python3.4/site-packages/theano/compile/function_module.py", line 1133, in __init__
    fgraph, additional_outputs = std_fgraph(inputs, outputs, accept_inplace)
  File "/usr/local/lib/python3.4/site-packages/theano/compile/function_module.py", line 141, in std_fgraph
    fgraph = gof.fg.FunctionGraph(orig_inputs, orig_outputs)
  File "/usr/local/lib/python3.4/site-packages/theano/gof/fg.py", line 135, in __init__
    self.__import_r__(outputs, reason="init")
  File "/usr/local/lib/python3.4/site-packages/theano/gof/fg.py", line 257, in __import_r__
    self.__import__(apply_node, reason=reason)
  File "/usr/local/lib/python3.4/site-packages/theano/gof/fg.py", line 353, in __import__
    detailed_err_msg)
theano.gof.fg.MissingInputError: A variable that is an input to the graph was neither provided as an input to the function nor given a value. A chain of variables leading from this input to an output is [<TensorType(int32, scalar)>, <theano.printing.Print object at 0x10fde00f0>.0]. This chain may not be unique
Backtrace when the variable is created:
  File "test.py", line 18, in <module>
    outputs_info=[T.zeros(1, dtype='int32')]
```

**Comment by lamblin** [comment]
Having side effects in the `scanner` function is dangerous. In particular, it may be called more than once during the optimization process, adding many variables to `prints`, most of which will not be computable by the final scan.

You could do something like this instead:
```python
def scanner(t, total):
    t = theano.printing.Print('T')(t)
    return total + t
```
This should print the initial `t` at every time step.

**Comment by AndreasMadsen** [comment]
I see, thanks.

Maybe the documentation (http://deeplearning.net/software/theano/library/printing.html) is a bit misleading. However now that I know the answers I'm reading it differently.

**Comment by lamblin** [comment]
If you have a suggestion of how the documentation could be less misleading, a pull request would be welcome :)
For the moment, I'm closing this ticket.

**Comment by rianrajagede** [comment]
I've try to use `printing.Print` like @lamblin suggest, but I don't know why it only print one time if I try to print `non_sequences` variable:
```
import theano
import theano.tensor as T

def geo(pre, t):
    t = theano.printing.Print('T')(t)
    pre = theano.printing.Print('PRE')(pre)
    return pre*t

x = T.iscalar('x')
k = T.iscalar('y')

result, updates = theano.scan(
    fn = geo,
    outputs_info = T.ones_like(x),
    non_sequences = x,
    n_steps = k
)

fun = theano.function([x,k], result, updates=updates)
print(fun(3,5))
```

this give a result:

```
T __str__ = 3
PRE __str__ = 1
PRE __str__ = 3
PRE __str__ = 9
PRE __str__ = 27
PRE __str__ = 81
[  3   9  27  81 243]
```

**Comment by lamblin** [comment]
Since the non-sequences does not change, there is no need to do the computation (here, print) more than once, so theano moves it out of the loop automatically.
If you disable that optimization:
```python
>>> fun = theano.function([x,k], result, updates=updates,
...     mode=theano.compile.get_default_mode().excluding('scanOp_pushout_nonseqs_ops'))
>>> print(fun(3,5))
PRE __str__ = 1
T __str__ = 3
PRE __str__ = 3
T __str__ = 3
PRE __str__ = 9
T __str__ = 3
PRE __str__ = 27
T __str__ = 3
PRE __str__ = 81
T __str__ = 3
[  3   9  27  81 243]
```
