### ISSUE TITLE
pydotprint_variables() fails

### ISSUE THREAD

**Issue by cangermueller** [Theano/Theano#2819]
Hi,

I tried to run `doc/hpcs2011_tutorial/simple_example.py`, using python2.7, pydot 1.0.2, on OSX and get the following error:

```python
/Users/angermue/venv/theano/lib/python2.7/site-packages/theano/printing.py:944: UserWarning: pydotprint_variables() is deprecated. Use pydotprint() instead.
  warnings.warn("pydotprint_variables() is deprecated."
Traceback (most recent call last):
  File "simple_example.py", line 8, in <module>
    theano.printing.pydotprint_variables(b, outfile="pics/f_unoptimized.png", var_with_name_simple=True)
  File "/Users/angermue/venv/theano/lib/python2.7/site-packages/theano/printing.py", line 1077, in pydotprint_variables
    g.write(outfile, prog='dot', format=format)
  File "/Users/angermue/venv/theano/lib/python2.7/site-packages/pydot.py", line 1696, in write
    dot_fd.write(self.create(prog, format))
  File "/Users/angermue/venv/theano/lib/python2.7/site-packages/pydot.py", line 1740, in create
    self.write(tmp_name)
  File "/Users/angermue/venv/theano/lib/python2.7/site-packages/pydot.py", line 1694, in write
    dot_fd.write(self.to_string())
  File "/Users/angermue/venv/theano/lib/python2.7/site-packages/pydot.py", line 1461, in to_string
    graph.append( edge.to_string() + '\n' )
  File "/Users/angermue/venv/theano/lib/python2.7/site-packages/pydot.py", line 900, in to_string
    edge_attr.append( attr + '=' + quote_if_necessary(value) )
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

`pydotprint` works for the same graph. I suspect that this is caused by empty labels in `pydotprint_variables`, as indicated in the source code:
```python
    try:
        g.write(outfile, prog='dot', format=format)
    except pd.InvocationException, e:
        # Some version of pydot are bugged/don't work correctly with
        # empty label. Provide a better user error message.
        if pd.__version__ == "1.0.28" and "label=]" in e.message:
            raise Exception("pydot 1.0.28 is know to be bugged. Use another "
                            "working version of pydot")
        elif "label=]" in e.message:
            raise Exception("Your version of pydot " + pd.__version__ +
                            " returned an error. Version 1.0.28 is known"
                            " to be bugged and 1.0.25 to be working with"
                            " Theano. Using another version of pydot could"
                            " fix this problem. The pydot error is: " +
                            e.message)
```

Do you get the same error? Do you think it's worth fixing this issue, this `pydotprint_variables` is deprecated anyway?

Cheers,
Christof

**Comment by nouiz** [comment]
As it is deprecated and pydotprint() work on it, I think I would just close this. Do you have a need for this? I don't see one.

**Comment by cangermueller** [comment]
I tried to run `doc/hpcs2011_tutorial/simple_example.py` to update the plots in http://deeplearning.net/software/theano/tutorial/symbolic_graphs.html#optimizations (see #2711).
The unoptimized graph was generated with `pydotprint_variables`. Is there a way to generate the unoptimized graph without `pydotprint`?

**Comment by nouiz** [comment]
It work for me. Which version of Theano are you using? Anything after Theano 0.7 should be good.

It could be a problem with your version of pydot. I have 1.0.28 and you?

**Comment by cangermueller** [comment]
Thanks, updating to 1.0.28 solved the issue!
