### ISSUE TITLE
Bug in the Alloc op grad

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#2836]
Here is the code:

```python
import theano
from theano import tensor

x = tensor.vector()
xx = x.dimshuffle('x', 'x', 0)
y = tensor.alloc(xx, 1, 3, x.shape[0])
tensor.grad(y.sum(), x)
```

and here is how it crashes: 

```
Traceback (most recent call last):
  File "alloc.py", line 7, in <module>
    tensor.grad(y.sum(), x)
  File "/home/rizar/Dist/theano/theano/gradient.py", line 545, in grad
    grad_dict, wrt, cost_name)
  File "/home/rizar/Dist/theano/theano/gradient.py", line 1286, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/rizar/Dist/theano/theano/gradient.py", line 1244, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/rizar/Dist/theano/theano/gradient.py", line 951, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/rizar/Dist/theano/theano/gradient.py", line 1244, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/rizar/Dist/theano/theano/gradient.py", line 1091, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/home/rizar/Dist/theano/theano/tensor/basic.py", line 2527, in grad
    gx = gx.dimshuffle(new_order)
  File "/home/rizar/Dist/theano/theano/tensor/var.py", line 340, in dimshuffle
    pattern)
  File "/home/rizar/Dist/theano/theano/tensor/elemwise.py", line 158, in __init__
    (input_broadcastable, new_order))
ValueError: ('You cannot drop a non-broadcastable dimension.', ((True, False), ('x', 'x', 0)))
```

I think I know what the problem is and even tried to fix it, but somehow tests do not pass even in a freshly checked out master making it hard to for me to change anything. I ran `theano-nose theano/tensor/tests/test_basic.py` and got `FAILED (KNOWNFAIL=1, failures=5)` with the following failures:

```
======================================================================
FAIL: test_broadcastable_single_input_broadcastable_dimension (theano.tensor.tests.test_basic.T_Join_and_Split)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rizar/Dist/theano/theano/tensor/tests/test_basic.py", line 3715, in test_broadcastable_single_input_broadcastable_dimension
    if isinstance(node.op, type(self.join_op))]
AssertionError

======================================================================
FAIL: test_infer_shape_join (theano.tensor.tests.test_basic.T_Join_and_Split)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rizar/Dist/theano/theano/tensor/tests/test_basic.py", line 3796, in test_infer_shape_join
    assert not isinstance(node.op, type(self.join_op))
AssertionError

======================================================================
FAIL: test_infer_shape (theano.tensor.tests.test_basic.TestARange)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rizar/Dist/theano/theano/tensor/tests/test_basic.py", line 5216, in test_infer_shape
    assert len(f.maker.fgraph.toposort()) == 9
AssertionError

======================================================================
FAIL: test_alloc_constant_folding (theano.tensor.tests.test_basic.TestAlloc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rizar/Dist/theano/theano/tensor/tests/test_basic.py", line 2151, in test_alloc_constant_folding
    alloc, subtensor, n_alloc, topo_grad)
AssertionError: (<theano.tensor.basic.Alloc object at 0x7f6adce386d0>, Subtensor{:int64:}.0, 2, [Shape(some_vector), DimShuffle{0}(<TensorType(float64, vector)>), DimShuffle{0,x}(<TensorType(float64, vector)>), Reshape{2}(some_vector, TensorConstant{[60 50]}), DimShuffle{x,0}(DimShuffle{0}.0), Subtensor{:int64:}(Reshape{2}.0, Constant{60}), Elemwise{second,no_inplace}(Reshape{2}.0, TensorConstant{(1, 1) of 0.0}), Dot22(Subtensor{:int64:}.0, DimShuffle{0,x}.0), DimShuffle{0}(Dot22.0), Elemwise{second}(DimShuffle{0}.0, TensorConstant{(1,) of 1.0}), DimShuffle{0,x}(Elemwise{second}.0), Dot22(DimShuffle{0,x}.0, DimShuffle{x,0}.0), IncSubtensor{Inc;:int64:}(Elemwise{second,no_inplace}.0, Dot22.0, Constant{60}), Reshape{1}(IncSubtensor{Inc;:int64:}.0, Shape.0)])

======================================================================
FAIL: test_infer_shape (theano.tensor.tests.test_basic.test_broadcast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rizar/Dist/theano/theano/tensor/tests/test_basic.py", line 6166, in test_infer_shape
    assert isinstance(topo[0].op, opt.Shape_i)
AssertionError

----------------------------------------------------------------------
```

**Comment by nouiz** [comment]
thanks for the report. Fixed in gh-2844
