### ISSUE TITLE
Simple? optimization error

### ISSUE THREAD

**Issue by tachim** [Theano/Theano#2975]
Hi all, I'm getting an optimization error with local_add_canonizer. The error is kinda opaque but I'm sure it'll be straightforward for you guys.

```
Traceback (most recent call last):
  File "main6.py", line 519, in <module>
    logZ_mu_list = map(run_constrained_variational, all_args)
  File "main6.py", line 477, in run_constrained_variational
    theano_total = grad_funcs[free_var - m](*list(mu[m:n]))
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0rc1-py2.7.egg/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0rc1-py2.7.egg/theano/compile/debugmode.py", line 2148, in deco
    return f()
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0rc1-py2.7.egg/theano/compile/debugmode.py", line 2076, in f
    r_vals)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0rc1-py2.7.egg/theano/compile/debugmode.py", line 955, in _find_bad_optimizations0
    new_graph=new_graph_str)
theano.compile.debugmode.BadOptimization: BadOptimization Error
  Variable: id 139653347048784 Elemwise{add,no_inplace}.0
  Op Elemwise{add,no_inplace}(TensorConstant{-0.494558968892}, Elemwise{mul,no_inplace}.0, Elemwise{second,no_inplace}.0, Elemwise{mul,no_inplace}.0, Elemwise{true_div,no_inplace}.0, Elemwise{true_div,no_inplace}.0, Elemwise{true_div,no_inplace}.0)
  Value Type: <type 'numpy.ndarray'>
  Old Value shape, dtype, strides: () float64 ()

  Old Value:  -0.311023883434
  New Value shape, dtype, strides: () float64 ()

  New Value:  -0.311022856884
  Max Abs Diff:  1.02655030787e-06
  Mean Abs Diff:  1.02655030787e-06
  Median Abs Diff:  1.02655030787e-06
  Std Abs Diff:  0.0
  Max Rel Diff:  1.65027841372e-06
  Mean Rel Diff:  1.65027841372e-06
  Median Rel Diff:  1.65027841372e-06
  Std Rel Diff:  0.0

  Reason:  local_add_canonizer
  Old Graph:
  Elemwise{add,no_inplace} [@A] ''
   |Elemwise{add,no_inplace} [@B] ''
   | |Elemwise{add,no_inplace} [@C] ''
   | | |Elemwise{add,no_inplace} [@D] ''
   | | | |Elemwise{add,no_inplace} [@E] ''
   | | | | |Elemwise{add,no_inplace} [@F] ''
   | | | | |Elemwise{mul} [@G] ''
   | | | |Elemwise{mul} [@H] ''
   | | |   |Elemwise{mul} [@I] ''
   | | |   |mu_3 [@J]
   | | |Elemwise{mul} [@K] ''
   | |   |Elemwise{mul} [@L] ''
   | |   | |Elemwise{true_div} [@M] ''
   | |   | |Elemwise{add,no_inplace} [@N] ''
   | |   |TensorConstant{-1.88865677912} [@O]
   | |Elemwise{mul} [@P] ''
   |   |Elemwise{mul} [@Q] ''
   |   | |Elemwise{true_div} [@M] ''
   |   | |Elemwise{mul,no_inplace} [@R] ''
   |   |   |TensorConstant{-1.88865677912} [@O]
   |   |   |mu_1 [@S]
   |   |TensorConstant{1.0} [@T]
   |Elemwise{mul} [@U] ''
     |Elemwise{mul} [@V] ''
     | |Elemwise{true_div} [@W] ''
     | | |Elemwise{neg} [@X] ''
     | | | |Elemwise{mul} [@Y] ''
     | | |Elemwise{mul} [@Z] ''
     | |   |Elemwise{add,no_inplace} [@BA] ''
     | |   |Elemwise{add,no_inplace} [@BA] ''
     | |TensorConstant{1.0} [@T]
     |TensorConstant{2} [@BB]

  New Graph:
  Elemwise{add,no_inplace} [@A] ''
   |TensorConstant{-0.494558968892} [@B]
   |Elemwise{mul} [@C] ''
   | |Elemwise{neg} [@D] ''
   | | |DimShuffle{} [@E] ''
   | |   |Elemwise{identity} [@F] ''
   | |     |DimShuffle{x} [@G] ''
   | |TensorConstant{2} [@H]
   |Elemwise{mul} [@I] ''
   | |Elemwise{mul} [@J] ''
   | | |Elemwise{second,no_inplace} [@K] ''
   | | | |Elemwise{add,no_inplace} [@L] ''
   | | | | |Elemwise{add,no_inplace} [@M] ''
   | | | | |TensorConstant{-1.82087995016} [@N]
   | | | |TensorConstant{1.0} [@O]
   | | |TensorConstant{0.0} [@P]
   | |mu_2 [@Q]
   |Elemwise{mul} [@R] ''
   | |Elemwise{mul} [@S] ''
   | | |Elemwise{second,no_inplace} [@K] ''
   | | |TensorConstant{0.829775666218} [@T]
   | |mu_3 [@U]
   |Elemwise{mul} [@V] ''
   | |Elemwise{mul} [@W] ''
   | | |Elemwise{true_div} [@X] ''
   | | | |Elemwise{second,no_inplace} [@K] ''
   | | | |Elemwise{add,no_inplace} [@Y] ''
   | | |   |TensorConstant{1.0} [@Z]
   | | |   |Elemwise{mul,no_inplace} [@BA] ''
   | | |Elemwise{add,no_inplace} [@BB] ''
   | |   |Sum{acc_dtype=float64} [@BC] ''
   | |   | |Elemwise{true_div,no_inplace} [@BD] ''
   | |   |Elemwise{mul,no_inplace} [@BE] ''
   | |     |Elemwise{sub,no_inplace} [@BF] ''
   | |     |TensorConstant{1.0} [@O]
   | |TensorConstant{-1.88865677912} [@BG]
   |Elemwise{mul} [@BH] ''
   | |Elemwise{mul} [@BI] ''
   | | |Elemwise{true_div} [@X] ''
   | | |Elemwise{mul,no_inplace} [@BJ] ''
   | |   |TensorConstant{-1.88865677912} [@BG]
   | |   |mu_1 [@BK]
   | |TensorConstant{1.0} [@O]
   |Elemwise{mul} [@BL] ''
     |Elemwise{mul} [@BM] ''
     | |Elemwise{true_div} [@BN] ''
     | | |Elemwise{neg} [@BO] ''
     | | | |Elemwise{mul} [@BP] ''
     | | |Elemwise{mul} [@BQ] ''
     | |   |Elemwise{add,no_inplace} [@Y] ''
     | |   |Elemwise{add,no_inplace} [@Y] ''
     | |TensorConstant{1.0} [@O]
     |TensorConstant{2} [@H]
```

**Comment by nouiz** [comment]
This seen a case where I think we should have not returned an error. The
difference is to small to be significants. Normally we don't show them.

You seem to use a theano version alder then 0.7. I highly recommend that
you update to 0.7 or the development version.

Why where you using debugmode? This error is probably not what tippy want.

Le 27 mai 2015 17:12, "Tudor Achim" <notifications@github.com> a écrit :
>
> Hi all, I'm getting an optimization error with local_add_canonizer. The
error is kinda opaque but I'm sure it'll be straightforward for you guys.
>
> Traceback (most recent call last):
>   File "main6.py", line 519, in <module>
>     logZ_mu_list = map(run_constrained_variational, all_args)
>   File "main6.py", line 477, in run_constrained_variational
>     theano_total = grad_funcs[free_var - m](*list(mu[m:n]))
>   File
"/usr/local/lib/python2.7/dist-packages/Theano-0.7.0rc1-py2.7.egg/theano/compile/function_module.py",
line 595, in __call__
>     outputs = self.fn()
>   File
"/usr/local/lib/python2.7/dist-packages/Theano-0.7.0rc1-py2.7.egg/theano/compile/debugmode.py",
line 2148, in deco
>     return f()
>   File
"/usr/local/lib/python2.7/dist-packages/Theano-0.7.0rc1-py2.7.egg/theano/compile/debugmode.py",
line 2076, in f
>     r_vals)
>   File
"/usr/local/lib/python2.7/dist-packages/Theano-0.7.0rc1-py2.7.egg/theano/compile/debugmode.py",
line 955, in _find_bad_optimizations0
>     new_graph=new_graph_str)
> theano.compile.debugmode.BadOptimization: BadOptimization Error
>   Variable: id 139653347048784 Elemwise{add,no_inplace}.0
>   Op Elemwise{add,no_inplace}(TensorConstant{-0.494558968892},
Elemwise{mul,no_inplace}.0, Elemwise{second,no_inplace}.0,
Elemwise{mul,no_inplace}.0, Elemwise{true_div,no_inplace}.0,
Elemwise{true_div,no_inplace}.0, Elemwise{true_div,no_inplace}.0)

**Comment by tachim** [comment]
Hmm, but why would there be a difference at all? By default optimizations should probably not be introducing approximations...

**Comment by nouiz** [comment]
Theano do not introduce approximation, but praticly all software use
float/double that are approximation of real numbers.

Changing the order of addtion like a+(b+c) vs (a+b)+c can change the
results. Theano do optimization that change the order of operation.

A good page that talk about this general problem:

http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

Fred

**Comment by nouiz** [comment]
We used a more strict comparison then numpy.allclose for float64. This was the cause of this. I made a PR to use the same tolerance for float64 then numpy.
