### ISSUE TITLE
Bug in cmodule.py, Line 1677

### ISSUE THREAD

**Issue by ghost** [Theano/Theano#2979]
Previous    :   (stdout, stderr) = p.communicate(input=b(''))  
Should be  :   (stdout, stderr) = p.communicate(input='')

**Comment by nouiz** [comment]
Why this is needed? In fact, from memory the current code is needed for
python 3. Which version of python do you use? What problem you have with
the current code?

**Comment by jedi00** [comment]
I'm using Python 3.4, Windows. The current code can not run actually. If you insist the current code is right, can you explain what b('') means? I didn't find any function named as 'b'. According to the code comment, the input should be a blank string, 
I suspect this is a mistake when converting theano from Python 2.x to 3.x

**Comment by nouiz** [comment]
Which version of Theano do you have? The current development version have
this import:

```
from theano.compat.six import b, BytesIO, StringIO

```

b function is used to help support python 2 and 3 with the same code. It
force the string to be in a given encoding in python 3, but do nothing in
python 3.

Updating Theano should solve the problem you have. Can you confirm this?

**Comment by jedi00** [comment]
I'm using Theano 0.7.0, announced as the latest.  According to your direction, I found the b() function, which returns str.encode('latin-1') for Python 3.x environment, which means, the Line 1677 is actually 
                    (stdout, stderr) = p.communicate(input=b'')
According to the comment of .communicate() function, the input should be bytes, so all these seems right. But whereever code snippet involves random generator of theano, it'll break. The following is a complete error log (in which lstm.py is the tutorial code from http://deeplearning.net/tutorial/lstm.html)

Traceback (most recent call last):
  File "F:/DaweiLeng/Code/workspace/Python/TheanoStudy/lstm.py", line 590, in <module>
    test_size=500,
  File "F:/DaweiLeng/Code/workspace/Python/TheanoStudy/lstm.py", line 444, in train_lstm
    y, f_pred_prob, f_pred, cost) = build_model(tparams, model_options)
  File "F:/DaweiLeng/Code/workspace/Python/TheanoStudy/lstm.py", line 325, in build_model
    proj = dropout_layer(proj, use_noise, trng)
  File "F:/DaweiLeng/Code/workspace/Python/TheanoStudy/lstm.py", line 72, in dropout_layer
    a = trng.binomial(state_before.shape, p=0.5, n=1, dtype=state_before.dtype)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\sandbox\rng_mrg.py", line 1245, in binomial
    x = self.uniform(size=size, nstreams=nstreams)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\sandbox\rng_mrg.py", line 1223, in uniform
    node_rstate = shared(self.get_substream_rstates(nstreams))
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\sandbox\rng_mrg.py", line 1113, in get_substream_rstates
    multMatVect(rval[0], A1p72, M1, A2p72, M2)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\sandbox\rng_mrg.py", line 55, in multMatVect
    [A_sym, s_sym, m_sym, A2_sym, s2_sym, m2_sym], o)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\compile\function.py", line 266, in function
    profile=profile)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\compile\pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\compile\function_module.py", line 1466, in orig_function
    defaults)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\compile\function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\vm.py", line 897, in make_all
    no_recycling))
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\cc.py", line 1434, in cthunk_factory
    key = self.cmodule_key()
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\cc.py", line 1154, in cmodule_key
    compile_args=self.compile_args(),
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\cc.py", line 872, in compile_args
    ret += c_compiler.compile_args()
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\cmodule.py", line 1703, in compile_args
    native_lines = get_lines("%s -march=native -E -v -" % theano.config.cxx)
  File "C:\Python34\lib\site-packages\theano-0.7.0-py3.4.egg\theano\gof\cmodule.py", line 1677, in get_lines
    (stdout, stderr) = p.communicate(input=b'')
  File "C:\Python34\lib\subprocess.py", line 959, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python34\lib\subprocess.py", line 1195, in _communicate
    self.stdin.write(bytes(input, 'utf8'))
TypeError: ('The following error happened while compiling the node', <theano.sandbox.rng_mrg.DotModulo object at 0x00000000076267F0>(A, s, m, A2, s2, m2), '\n', 'encoding or errors without a string argument')

**Comment by lamblin** [comment]
How did you install theano? Did you use `pip install ...`, or `python setup.py ...`? Otherwise `2to3` does not run, and the code is not actually ready for python 3 yet.

**Comment by jedi00** [comment]
@lamblin : I downloaded the tar package from pypi and installed by setup.py on a server without internet connection. Do you imply there is any dependency package missing? I have six-1.9.0 installed.

**Comment by lamblin** [comment]
OK, I just wanted to make sure you did not do "git clone ..." or extracted the tar package, and then manually modified the `PYTHONPATH` instead of calling `setup.py`. If you used `setup.py`, then (in theory...) it should be OK.
Theano packages its own version of `six`, so that should not be an issue.

**Comment by lamblin** [comment]
Actually, is it possible that the error does not come from Theano itself, but from a locale/encoding mismatch between Python and your OS, or maybe even gcc?
Can you try to use `communicate` to launch the compilation of a small C program by gcc? Then with a program that has an error?
I have a feeling that gcc spits out an error that has non-ascii characters in them, encoded in something else than utf-8, and that when Python calls `bytes(..., 'utf8')` on it, the `TypeError` is raised. Then Theano catches that error to add some information (happening when compiling this node...).
I'm not sure why `'utf8'` seems to be hardcoded in Python's subprocess.py file, but it may be part of the problem if your locale has a different encoding.

**Comment by nouiz** [comment]
should fixed already, so closing.
