### ISSUE TITLE
Handle broadcastable better in outputs_info of scan

### ISSUE THREAD

**Issue by kyunghyuncho** [Theano/Theano#2985]
Passing a tensor whose shape includes 1 as a part of ``outputs_info`` when calling ``theano.scan`` fails unless those axes of shape 1 are unbroadcasted manually using ``tensor.unbroadcast``. This is due to the different broadcasting pattern between the actual return from the inner function of ``scan`` and the corresponding one passed via ``outputs_info``. It'll make ``theano.scan`` more usable, if ``scan`` can handle this situation automatically.

A sample code reproducing this behaviour
```
import theano
from theano import tensor

def test0(n_samples):
    def _loop(x, y):
        x = x + y
        return x

    rval, updates = theano.scan(_loop, sequences=[],
                                outputs_info=[tensor.alloc(0., n_samples, 10)],
                                non_sequences=[tensor.alloc(1., n_samples, 10)],
                                n_steps=10)

    test_fn = theano.function([], rval[-1])

    print test_fn()

def test1(n_samples):
    def _loop(x, y):
        x = x + y
        return x

    rval, updates = theano.scan(_loop, sequences=[],
                                outputs_info=[tensor.unbroadcast(tensor.alloc(0., n_samples, 10),0)],
                                non_sequences=[tensor.alloc(1., n_samples, 10)],
                                n_steps=10)

    test_fn = theano.function([], rval[-1])

    print test_fn()

if __name__ == '__main__':
    print 'Working case: n_samples > 1'
    test0(2)

    print 'Working with n_samples == 1 if unbroadcasted'
    test1(1)

    print 'Not working with n_samples == 1'
    test0(1)
```

This is the result of running the code above
```
Working case: n_samples > 1
/u/chokyun/work/Theano/build/lib/theano/scan_module/scan_perform_ext.py:133: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
[[ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]
Working with n_samples == 1 if unbroadcasted
[[ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]
Not working with n_samples == 1
Traceback (most recent call last):
  File "./test.py", line 40, in <module>
    test0(1)
  File "./test.py", line 12, in test0
    n_steps=10)
  File "/u/chokyun/work/Theano/build/lib/theano/scan_module/scan.py", line 1045, in scan
    scan_outs = local_op(*scan_inputs)
  File "/u/chokyun/work/Theano/build/lib/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/u/chokyun/work/Theano/build/lib/theano/scan_module/scan_op.py", line 508, in make_node
    outer_sitsot = format(_outer_sitsot, as_var=inner_sitsot)
  File "/u/chokyun/work/Theano/build/lib/theano/scan_module/scan_op.py", line 409, in format
    rval = tmp.filter_variable(rval)
  File "/u/chokyun/work/Theano/build/lib/theano/tensor/type.py", line 217, in filter_variable
    self=self)
TypeError: Cannot convert Type TensorType(float32, 3D) (of Variable IncSubtensor{Set;:int64:}.0) into Type TensorType(float32, (False, True, False)). You can try to manually convert IncSubtensor{Set;:int64:}.0 into a TensorType(float32, (False, True, False)).
```

**Comment by lamblin** [comment]
@kyunghyuncho Can you confirm if #3102 has actually fixed this issue? Thanks.

**Comment by nouiz** [comment]
@kyunghyuncho I tested the code in this issue and it work. So I'll close it. If you still see problems, tell us.can you check

**Comment by franciscovargas** [comment]
I think this issue is associated https://github.com/Theano/Theano/issues/4927
