### ISSUE TITLE
Prevent evaluation of the non-necessary branch of ifelse

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3004]
Currently, even with VM or CVM, when the graph of the branch that is not selected contains a view to a different variable, and that variable is destroyed by a node in the selected branch, we force the execution of all nodes depending on the destroyed variable first.
This means that some part of the unselected branch can be executed, which results in:
- useless computation being performed
- an error if that branch cannot be executed because of the current values being incompatible.

Example code at https://gist.github.com/lamblin/3cc1faaef606a2e65376
Some discussion started at #3001

**Comment by lamblin** [comment]
A partial solution would be to add a Feature to the FunctionGraph that prevents the introduction of an Op if:
- this Op is always executed, and
- the variable it destroys is viewed by an Op that is _not_ always executed.
"Always executed" means that it is executed in all branches of all "ifelse" nodes.

**Comment by lamblin** [comment]
See #3552 and #3793 for examples.

**Comment by nouiz** [comment]
I updated the description to add the work around suggested in one of the closed PR.

**Comment by hlin117** [comment]
`ifelse` is also failing to perform lazy evaluation in my code. However, it's failing before compile time, when I'm using `test_value`s.

**Comment by nouiz** [comment]
Can you give more information? This issue is about runtime problem, so you
probably have another problem. So you probably should open a new issue or
email the mailing list with the full error.

**Comment by hlin117** [comment]
@nouiz I just opened up issue #4474.

**Comment by hlin117** [comment]
@nouiz Do you have any tips on how to avoid the following crash below? Any workaround would be nice.

Ultimately, I need a way to avoid taking the max of an empty Theano vector. The error I have is analogous to the following. We ideally do not want the `else` branch to be executed, but it is anyways.

```
def access_max(array, i):
    0 if len(array) == 0 else np.max(array) 

access_array([], 1)
```

Do you have any suggestions?

<img width="1197" alt="screenshot 2016-05-12 03 56 57" src="https://cloud.githubusercontent.com/assets/1865885/15209249/b065a464-17f5-11e6-81b5-fe050130e78b.png">
The assertion thrown helps verify that the program is executing the wrong branch.

**Comment by nouiz** [comment]
You could just more the max after the ifelse like this:

ifelse(T.eq(antecedents.size, 0), [epsilon], T.max(antecedents)).max()

This way the max will always be executed on something valid and will always
return you the result you want.

**Comment by hlin117** [comment]
Hi @nouiz. Unfortunately, that's the current issue. Regarding your example
```
ifelse(T.eq(antecedents.size, 0), [epsilon], T.max(antecedents)).max()
```
the wrong `ifelse` branch is taken, so even if `antedents` is empty, theano will still try to take the max of an empty array.

Is there a way to append to the `antecedents` array? If we append `epsilon` to the `antecedents` array, there is at least one element, so we could remove the `ifelse` statement entirely.

**Comment by nouiz** [comment]
I made a mistake, try:


ifelse(T.eq(antecedents.size, 0), [epsilon], antecedents).max()


There should be only 1 max call. You can concatenate T.concatenate() would
work. Here is the doc section with the different way to concatenate:

http://deeplearning.net/software/theano/library/tensor/basic.html#theano.tensor.stack

**Comment by hlin117** [comment]
Hi @nouiz. I tried that code, and I received this error:

```
Traceback (most recent call last):
  File "main.py", line 268, in <module>
    main()
  File "main.py", line 245, in main
    actual_mentions_testing)
  File "main.py", line 187, in coref_output
    nn_coreference.fit(X_train_corefs, docs=train_subset)
  File "/Users/hlin117/cs_546/coreference/nn_coreference.py", line 113, in fit
    self._build_mlp()
  File "/Users/hlin117/cs_546/coreference/nn_coreference.py", line 413, in _build_mlp
    T.cast(self._latentloss(x, pairwise_scores, ant_corefs), "float64"))
  File "/Users/hlin117/cs_546/coreference/nn_coreference.py", line 305, in _latentloss
    constant_thing = self._highest_antecedent_score(x, pairwise_scores_ant_corefs)
  File "/Users/hlin117/cs_546/coreference/nn_coreference.py", line 332, in _highest_antecedent_score
    antecedent_scores = ifelse(T.eq(antecedent_scores.size, 0), [epsilon_score], antecedent_scores)
  File "/Users/hlin117/cs_546/venv/src/theano/theano/ifelse.py", line 367, in ifelse
    (then_branch_elem.type, else_branch_elem.type))
TypeError: The two branches should have identical types, but they are TensorType(float64, scalar) and TensorType(float64, vector) respectively. This error could be raised if for example you provided a one element list on the `then` branch but a tensor on the `else` branch.
```
Is this expected behavior? I guess this is the incorrect way to put `epsilon` into a vector.

**Comment by hlin117** [comment]
This is what I did instead
```
proxyarray = T.concatenate([antecedents.flatten(), epsilon.flatten()])  # Hack to turn a scalar into a vector
ifelse(T.eq(antecedents.size, 0), proxyarray, antecedents).max()
```
