### ISSUE TITLE
[BUG IN FGRAPH.REPLACE OR A LISTENER] AssertionError: This substitution would insert a cycle in the graph

### ISSUE THREAD

**Issue by pcyin** [Theano/Theano#3192]
Hi All,

I encountered a strange error under FAST_RUN mode. The theano function fails to compile with the following error, which starts with `<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>>`

The code runs fine without compilation optimization. It seems that the compiled computational graph has a circle, which throws this error.

I am using the latest dev version of theano.

The function dump is [here](http://i.cs.hku.hk/~pcyin/func_dump.bin)

I posted this message on theano-users first, but just realised that it would be better to discuss the issue here, since it could be a bug. Thanks in advance for any suggestion!

```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.AssertionError'> This substitution would insert a cycle in the graph:node: Shape_i{2}(Rebroadcast{0}.0), i: 0, r: Rebroadcast{0}.0, new_r: Rebroadcast{0}.0 MergeOptimizer
Traceback (most recent call last):
  File "main.py", line 532, in <module>
    graph.compile('adadelta', {'output_softmax':'categorical_crossentropy'}, data=None)
  File "models.py", line 602, in compile
    updates=updates, allow_input_downcast=True, mode=theano_mode)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/function.py", line 310, in function
    output_keys=output_keys)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/pfunc.py", line 523, in pfunc
    output_keys=output_keys)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/function_module.py", line 1525, in orig_function
    output_keys=output_keys).create(
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/function_module.py", line 1212, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/opt.py", line 88, in __call__
    return self.optimize(fgraph)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/opt.py", line 79, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/opt.py", line 194, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/opt.py", line 79, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/opt.py", line 1795, in apply
    sub_prof = gopt.apply(fgraph)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/opt.py", line 621, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/toolbox.py", line 258, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/fg.py", line 525, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/fg.py", line 472, in change_input
    r, new_r, reason=reason)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/fg.py", line 601, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/tensor/opt.py", line 1182, in on_change_input
    % (node, i, r, new_r))
AssertionError: This substitution would insert a cycle in the graph:node: Shape_i{2}(Rebroadcast{0}.0), i: 0, r: Rebroadcast{0}.0, new_r: Rebroadcast{0}.0
```

**Comment by nouiz** [comment]
Thanks for the report and the dump. I'm able to reproduce it. A quick work
around that you can do to allow you to continue to work is to use that diff:

```
diff --git a/theano/tensor/opt.py b/theano/tensor/opt.py
index 83bb132..3658377 100644
--- a/theano/tensor/opt.py
+++ b/theano/tensor/opt.py
@@ -1176,7 +1178,7 @@ class ShapeFeature(object):
                     continue

                 if shpnode.outputs[0] in
theano.gof.graph.ancestors([repl]):
-                    raise AssertionError(
+                    raise InconsistencyError(
                         "This substitution would insert a cycle in the
graph:"
                         "node: %s, i: %i, r: %s, new_r: %s"
                         % (node, i, r, new_r))
```

This will with the first line of the error, but remove the stack trace.
Theano will just skip the optimization it was tring to do that cause this
problem. So you can use the return compiled Theano function. It should work
correctly.

This type of problem aren't easy to fix, so not sure how long it will take
to fix it.

**Comment by pcyin** [comment]
Thanks for your advice. I am able to circumvent this issue now.
