### ISSUE TITLE
-m32 compilation error on Raspberry Pi

### ISSUE THREAD

**Issue by davikrehalt** [Theano/Theano#3231]
I tried building theano on the Raspberry Pi 1 B and got the following error 
Problem occurred during compilation with the command line below:
````
/usr/bin/g++ -shared -g -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D NPY_ARRAY_ENSUREARRAY=NPY_ENSUREARRAY -D NPY_ARRAY_ENSURECOPY=NPY_ENSURECOPY -D NPY_ARRAY_ALIGNED=NPY_ALIGNED -D NPY_ARRAY_WRITEABLE=NPY_WRITEABLE -D NPY_ARRAY_UPDATE_ALL=NPY_UPDATE_ALL -D NPY_ARRAY_C_CONTIGUOUS=NPY_C_CONTIGUOUS -D NPY_ARRAY_F_CONTIGUOUS=NPY_F_CONTIGUOUS -m32 -fPIC -I/usr/lib/pymodules/python2.7/numpy/core/include -I/usr/include/python2.7 -I/home/andy/pyjects/Theano/theano/gof -fvisibility=hidden -o /root/.theano/compiledir_Linux-3.18.11+-armv6l-with-debian-7.8--2.7.3-32/lazylinker_ext/lazylinker_ext.so /root/.theano/compiledir_Linux-3.18.11+-armv6l-with-debian-7.8--2.7.3-32/lazylinker_ext/mod.cpp -L/usr/lib -lpython2.7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "theano/__init__.py", line 63, in <module>
    from theano.compile import (
  File "theano/compile/__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "theano/compile/function_module.py", line 19, in <module>
    import theano.compile.mode
  File "theano/compile/mode.py", line 10, in <module>
    import theano.gof.vm
  File "theano/gof/vm.py", line 666, in <module>
    from . import lazylinker_c
  File "theano/gof/lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "theano/gof/cmodule.py", line 2059, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): cc1plus: error: unrecognized command line option ‘-m32’. 
````

**Comment by nouiz** [comment]
In the file theano/gof/cmodule.py, around line 1896, we add the -m32
parameter:

if not any(['arm' in flag for flag in cxxflags]) and platform.machine() !=
'armv7l':
            n_bits = local_bitwidth()
            cxxflags.append('-m%d' % n_bits)

Can you add a print just before that line that print cxxflags and
platform.machine()? With that information that can be fixed easily.

If you know how to fix it and make a PR with the fix, that would be ideal.
If not, give me the output, all make a diff that you can test and I'll make
the PR.

thanks

**Comment by davikrehalt** [comment]
https://github.com/Theano/Theano/pull/3266 I have made a pull request and fixed the issue in this case. The original code only matches for the armv7 whereas now it also matches armv6 which the Raspberry Pi 1 has.

**Comment by nouiz** [comment]
was closed by gh-3266
