### ISSUE TITLE
Bug report when compile function.

### ISSUE THREAD

**Issue by lc82111** [Theano/Theano#3261]
Hi guys:
          I encountered an AssertionError as below, when compile my theano function. I am using the  version 0.7 of theano.  I hope a quick work around is available.  Thanks. The function dump is [here] (http://pan.baidu.com/s/1qWzIGc0).
```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.AssertionError'>  local_shape_to_shape_i
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1527, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/toolbox.py", line 259, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 502, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 442, in change_input
    self.__import_r__([new_r], reason=reason)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 257, in __import_r__
    self.__import__(apply_node, reason=reason)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 365, in __import__
    assert node not in self.apply_nodes
AssertionError
```

**Comment by nouiz** [comment]
We fixed some case in the dev version of Theano update to it. If you still
have the problem, tell us.

Fred

**Comment by nouiz** [comment]
As no reply, I suppose his case is fixed and I close this ticket.
