### ISSUE TITLE
Undefined symbol (though other similar GPU kernels compile)

### ISSUE THREAD

**Issue by iskandr** [Theano/Theano#3262]
I've been using Theano indirectly through the machine learning library Keras. It has previously worked with a GPU target but I'm now getting the following "undefined symbol" compilation error:

```
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 293, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', GpuAlloc{memset_0=True}(CudaNdarrayConstant{[[ 0.]]}, Shape_i{0}.0, Shape_i{1}.0), '\n', '/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.10-64/tmpyppT_h/b8f3852a247133aef7dcde37a608c7e1.so: undefined symbol: _Z17CudaNdarray_SIZEtPK11CudaNdarray', '[GpuAlloc{memset_0=True}(CudaNdarrayConstant{[[ 0.]]}, <TensorType(int64, scalar)>, <TensorType(int64, scalar)>)]')
```

Has anyone else encountered this before and if so is there an obvious fix?

**Comment by lamblin** [comment]
Hi,

Do you have access to the full error message, including the compilation line and code listing? That would be helpful to know exactly what went wrong, and which symbol is undefined.

**Comment by iskandr** [comment]
@lamblin Here's the full stack trace:

```
Traceback (most recent call last):
  File "train-lstm-cross-val.py", line 67, in <module>
    optimizer=RMSprop(clipnorm=10))
  File "/home/ubuntu/kerseq/kerseq/recurrent_network.py", line 174, in build_rnn_graph
    model.compile(optimizer, {"output": loss})
  File "/home/ubuntu/keras/keras/models.py", line 501, in compile
    updates=updates, allow_input_downcast=True, mode=theano_mode)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 259, in make_thunk
    compute_map, no_recycling)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1076, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1354, in compile_cmodule
    preargs=preargs)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py", line 434, in compile_str
    return dlimport(lib_filename)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 293, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', GpuAlloc{memset_0=True}(CudaNdarrayConstant{[[ 0.]]}, Shape_i{0}.0, Shape_i{1}.0), '\n', '/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.10-64/tmpt7gmhh/b8f3852a247133aef7dcde37a608c7e1.so: undefined symbol: _Z17CudaNdarray_SIZEtPK11CudaNdarray', '[GpuAlloc{memset_0=True}(CudaNdarrayConstant{[[ 0.]]}, <TensorType(int64, scalar)>, <TensorType(int64, scalar)>)]')
```

The error arises from this line:

```
    model = build_rnn_graph(
        rnn_class=LSTM,
        sequence_input_names=["peptide", "mhc"],
        n_symbols=n_distinct_symbols,
        embedding_dim=64,
        rnn_output_dim={
            "peptide": PEPTIDE_RNN_OUTPUT_DIM,
            "mhc": MHC_RNN_OUTPUT_DIM
        },
        dense_output_dims=DENSE_OUTPUT_DIMS,
        optimizer=RMSprop(clipnorm=10))
```

...which is calling [kerseq.recurrent_network.build_rnn_graph](https://github.com/hammerlab/kerseq/blob/master/kerseq/recurrent_network.py#L27) 

I have CUDA version `6.5.12`, as well as recent master branches of Theano and Keras.

**Comment by iskandr** [comment]
Pulling the latest Theano seems to have resolved the problem, so I guess I'll close the issue.
