### ISSUE TITLE
Graph contains cycles

### ISSUE THREAD

**Issue by dselsam** [Theano/Theano#3319]
Hi,

When compiling my model, I get `ValueError(graph contains cycles)` during the check in `general_toposort`. The traceback is long, but the beginning is: 

```
ERROR (theano.gof.opt): SeqOptimizer apply 
<theano.gof.opt.EquilibriumOptimizer object at 0x21e49990>
```

My model is a rather complicated recursive neural network, and unfortunately I cannot find a simple example that reproduces the error.

1. Is it correct that no model should be able to trigger this error, and thus that it is a bug in Theano itself?
2. If I sent my model and enough data to trigger the error, would a developer be willing to investigate?
3. If not, are there any potential workarounds, at the user level or involving extra checks and roll-backs during the graph optimization?

Thanks very much.

**Comment by lamblin** [comment]
1. It is possible for user-defined code to explicitly that error, but it would require that the graph contains inconsistent information about which operations should be executed in place, in a destructive fashion. This is why explicitly specifying "inplace" patterns should be avoided.
2. If you provide us with the code and data, we would be interested in having a look and trying to solve the issue. However, we cannot commit on a timeline for that, as we are quite busy at the moment, and some of us are on vacation.
3. There are a couple of things you can try, that could help figuring out where the problem comes from:
  - can you compile a function with "optimizer=None" in the global flags (or passing `mode=theano.Mode(optimizer=None)` to `theano.function`)? If the error is still there, that is probably an issue in the original graph (about inconsistent inplace patterns)
  - can you disable the "inplace" optimizations? For instance `optimizer_excluding=inplace` in `THEANO_FLAGS`.
  - can you disable "ShapeOpt" the same way?
  - also, the full stack trace may be useful.

**Comment by twiecki** [comment]
Related: https://github.com/pymc-devs/pymc3/issues/803

**Comment by basveeling** [comment]
@dselsam I had the same issue, but after reinstalling scipy and numpy (both were already up to date) the error was gone.

**Comment by fvisin** [comment]
I can confirm the same issue on one of the lab's computers, with a code that used to work and I didn't modify in the meanwhile.

**Comment by fvisin** [comment]
I reverted back to https://github.com/Theano/Theano/commit/557fe6fab49262706241f0e774f3269a2ec0275b and it's working again. I wasn't able to determine exactly when it got broken though (time consuming). @lamblin: if you can provide me with the commits you think might trigger this problem, I can run more tests the next week.

**Comment by twiecki** [comment]
I did a git bisect and found that this commit introduced the problem: https://github.com/Theano/Theano/commit/9685f1d1507cdea4df0aa93c46e3e0577af70b3e

**Comment by t13m** [comment]
Hi @twiecki , code in this commit handles different cases of assert node input when applying  `MergeOptimizer`. It check if assert node exists in `node`'s and `candidate`'s input list, and merge the assert nodes with different asserting conditions. 
For now, I have no idea why this problem appears. Can you provide some more information about the problem. And if it is possible to provide the code enough to reproduce the problem, I'd like to do some investigation when I go back to school next week.
Thanks.

**Comment by twiecki** [comment]
My test is to run nosetest on pymc3's https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_plots.py. Not sure if there is a better way but at least it should get you into a debugger.

I think people here have also reported failing unittests, I haven't been able to replicate that however.

**Comment by nouiz** [comment]
I have a PR at https://github.com/Theano/Theano/pull/3344 that disable that
new feature. I think we got enough report that it cause enough trouble to
disable it now. That way it give us more time to fix it.

Thanks for the investigation, it made the tmp fix fast to do.

**Comment by nouiz** [comment]
@t13m, do you have the time to check how to make the real fix? I won't have
time this week, too much stuff accumulated during my vacation.

**Comment by t13m** [comment]
@nouiz Hi, I'd like to make some investigation but I'm not at school until next week, next week will be good for me.

**Comment by nouiz** [comment]
ok. thanks. I work around is merged, so waiting for next week isn't a
problem.

**Comment by nouiz** [comment]
@t13m have you been able to look at this?

**Comment by t13m** [comment]
Hi Fred, I haven't begun yet, and seem having not enough time to do this
recently.

2015-09-23 22:08 GMT+08:00 Frédéric Bastien <notifications@github.com>:

**Comment by nouiz** [comment]
thanks for the update.

**Comment by ysjakking** [comment]
Hi @nouiz, @lamblin , @t13m, 
    I use the Theano-dev and I get the "graph contains cycles " error again  when stacking multi-lstms.  In detail, when I set optimizer=fast_run , it generates this errors. However, when I turn optimizer=fast_compile or None, the error is gone.  
Moreover, I have found the code which causes the error :
this_LSTM_input=prior_LSTM_hidden_out[0:-2] , where "this_LSTM_input"  is  a 3D tensor  (N_steps-2 *  N_batch * dim_hidden_Lstm ) and it is going to be feed into the next LSTM layer implemented using "scan". While  the  “ prior_LSTM_hidden_out“  is the output 3D tensor  (N_steps *  N_batch * dim_hidden_Lstm ) of the prior LSTM.

However, when I replace the error line with "this_LSTM_input=prior_LSTM_hidden_out" the error is gone again. I can not figure out why.   

Please, help me~, Thanks in advance.

The Code:

    this_LSTM_input=prior_LSTM_hidden_out[0:-2]       ###this line causes the error
    #this_LSTM_input=prior_LSTM_hidden_out             ###this line does not cause the error
  
    def recurrence_dis_localsum(Word_t_local,Mask_t_local,h_t_prior_local,c_t_prior_local): 

        lstm_t = T.dot(h_t_prior_local, W_LSTM_hidden_dis_local) + T.dot(Word_t_local, W_LSTM_in_dis_local) + b_LSTM_dis_local
        i_t_enc = T.nnet.sigmoid(lstm_t[:, 0*n_LSTM:1*n_LSTM])
        f_t_enc = T.nnet.sigmoid(lstm_t[:, 1*n_LSTM:2*n_LSTM])

        cell_t_enc = f_t_enc * c_t_prior_local + i_t_enc * T.tanh(lstm_t[:, 2*n_LSTM:3*n_LSTM])
        cell_t_enc = Mask_t_local.dimshuffle([0, 'x']) * cell_t_enc + (1. - Mask_t_local.dimshuffle([0, 'x'])) * c_t_prior_local
       o_t_enc = T.nnet.sigmoid(lstm_t[:, 3*n_LSTM:4*n_LSTM])
        h_t = o_t_enc * T.tanh(cell_t_enc)
        h_t = Mask_t_local.dimshuffle([0, 'x']) * h_t + (1. - Mask_t_local.dimshuffle([0, 'x'])) * h_t_prior_local

        return h_t.astype(theano.config.floatX) ,cell_t_enc.astype(theano.config.floatX)

    LSTM_h0_local = (T.extra_ops.repeat(LSTM_h0_dis_local, repeats=Word_list.shape[1], axis=0)).astype(theano.config.floatX)
    cell0_LSTM_local = T.zeros((Word_list.shape[1],n_LSTM),dtype=theano.config.floatX)

    (h_list_local , cell_list_local), updates_LSTM_local = theano.scan(lambda Word_t_local,Mask_t_local,h_t_prior_local,c_t_prior_local : recurrence_dis_localsum(Word_t_local,Mask_t_local,h_t_prior_local,c_t_prior_local),
                                                    sequences=[this_LSTM_input,local_mask.dimshuffle([1, 0])],
                                                    outputs_info=[LSTM_h0_local,cell0_LSTM_local],
                                                    n_steps=this_LSTM_input.shape[0])

**Comment by lamblin** [comment]
Would it be possible that #5223 addresses the issue?
Could you try out that branch and see if you still have that error?
Thanks.

**Comment by ysjakking** [comment]
@lamblin  Ok! I will try, thanks!

**Comment by nouiz** [comment]
If it don't fix the issue, we will need a way to reproduce the error.

thanks for the report.

**Comment by ysjakking** [comment]
Hi @nouiz,
                    I tried the branch #5223 ,but it did not work fine for my problem.  Note that it is complicated to give all the codes, I give the information as below:

COMPILING...

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f670190f6d0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2357, in apply
    sub_prof = gopt.apply(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2011, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply local_dot_to_dot22
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2011, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.blas.GemmOptimizer object at 0x7f67b2121490>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/tensor/blas.py", line 1434, in apply
    nodelist = theano.gof.graph.io_toposort(fgraph.inputs, fgraph.outputs)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply local_dot22_to_dot22scalar
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2011, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f67b2121610>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2380, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <TopoOptimizer instance>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2011, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply use_scipy_ger
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2011, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f670190f550>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2357, in apply
    sub_prof = gopt.apply(fgraph)
  File "/home/shijie.yang/Theano-master/theano/tensor/nnet/nnet.py", line 1498, in crossentropy_to_crossentropy_with_softmax_with_bias
    while search_make_one_sub():
  File "/home/shijie.yang/Theano-master/theano/tensor/nnet/nnet.py", line 1483, in search_make_one_sub
    for node in fgraph.toposort():
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 633, in toposort
    order = graph.io_toposort(fg.inputs, fg.outputs, ords)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply crossentropy_to_crossentropy_with_softmax
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/tensor/nnet/nnet.py", line 1545, in crossentropy_to_crossentropy_with_softmax
    while search_make_one_sub():
  File "/home/shijie.yang/Theano-master/theano/tensor/nnet/nnet.py", line 1522, in search_make_one_sub
    for node in fgraph.toposort():
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 633, in toposort
    order = graph.io_toposort(fg.inputs, fg.outputs, ords)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f670190f590>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2380, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.NameError'> free variable 'node' referenced before assignment in enclosing scope InputToGpuOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply <theano.sandbox.cuda.opt.InputToGpuOptimizer object at 0x7f67a5988d50>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/sandbox/cuda/opt.py", line 205, in apply
    "InputToGpuOptimizer")
  File "/home/shijie.yang/Theano-master/theano/gof/toolbox.py", line 328, in replace_validate
    self.replace_all_validate(fgraph, [(r, new_r)], reason=reason)
  File "/home/shijie.yang/Theano-master/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 508, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 450, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 351, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 414, in __import__
    self.execute_callbacks('on_import', node, reason)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 588, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 1744, in on_import
    self.importer(node)
  File "/home/shijie.yang/Theano-master/theano/tensor/blas.py", line 1425, in on_import
    if new_node is not node:
NameError: free variable 'node' referenced before assignment in enclosing scope

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f670190f790>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 83, in optimize
    self.add_requirements(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2283, in add_requirements
    opt.add_requirements(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 1195, in add_requirements
    req(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 1228, in <lambda>
    fgraph.attach_feature(dh_handler()),)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 540, in attach_feature
    attach(self)
  File "/home/shijie.yang/Theano-master/theano/gof/destroyhandler.py", line 744, in on_attach
    toolbox.Bookkeeper.on_attach(self, fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/toolbox.py", line 124, in on_attach
    for node in graph.io_toposort(fgraph.inputs, fgraph.outputs):
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f670190f850>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2380, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f670190f5d0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2380, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply AbstractConvCheck
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 2011, in apply
    q = deque(graph.io_toposort(fgraph.inputs, start_from))
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f67b2165e90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/tensor/opt.py", line 7215, in apply
    nodelist = list(fgraph.toposort())
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 633, in toposort
    order = graph.io_toposort(fg.inputs, fg.outputs, ords)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f67b2165f50>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/tensor/opt.py", line 7215, in apply
    nodelist = list(fgraph.toposort())
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 633, in toposort
    order = graph.io_toposort(fg.inputs, fg.outputs, ords)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f67a593d050>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/tensor/opt.py", line 7215, in apply
    nodelist = list(fgraph.toposort())
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 633, in toposort
    order = graph.io_toposort(fg.inputs, fg.outputs, ords)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f677c596a90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/tensor/opt.py", line 7215, in apply
    nodelist = list(fgraph.toposort())
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 633, in toposort
    order = graph.io_toposort(fg.inputs, fg.outputs, ords)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 1030, in io_toposort
    deps_cache=deps_cache, clients=clients)
  File "/home/shijie.yang/Theano-master/theano/gof/graph.py", line 960, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: graph contains cycles

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.NameError'> free variable 'node' referenced before assignment in enclosing scope MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply MergeOptimizer
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 855, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "/home/shijie.yang/Theano-master/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 508, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 450, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 351, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 414, in __import__
    self.execute_callbacks('on_import', node, reason)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 588, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 1744, in on_import
    self.importer(node)
  File "/home/shijie.yang/Theano-master/theano/tensor/blas.py", line 1425, in on_import
    if new_node is not node:
NameError: free variable 'node' referenced before assignment in enclosing scope

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.AssertionError'>  InputToGpuOptimizer
Traceback (most recent call last):
  File "/home/shijie.yang/Theano/captionGAN/mCaptionGAN_single_disRNN_mask_discrim_last_localsum_lstm.py", line 397, in <module>
    updates=d_updates)
  File "/home/shijie.yang/Theano-master/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/shijie.yang/Theano-master/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/shijie.yang/Theano-master/theano/compile/function_module.py", line 1783, in orig_function
    output_keys=output_keys).create(
  File "/home/shijie.yang/Theano-master/theano/compile/function_module.py", line 1465, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/shijie.yang/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/shijie.yang/Theano-master/theano/sandbox/cuda/opt.py", line 205, in apply
    "InputToGpuOptimizer")
  File "/home/shijie.yang/Theano-master/theano/gof/toolbox.py", line 328, in replace_validate
    self.replace_all_validate(fgraph, [(r, new_r)], reason=reason)
  File "/home/shijie.yang/Theano-master/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/shijie.yang/Theano-master/theano/gof/fg.py", line 507, in replace
    assert (node == 'output' and self.outputs[i] is r) or (node.inputs[i] is r)
AssertionError

Process finished with exit code 1

**Comment by lamblin** [comment]
That stack trace does not give us enough information to reproduce the issue, unfortunately.
Could you try to call [`function_dump`](http://deeplearning.net/software/theano/tutorial/debug_faq.html#dumping-a-function-to-help-debug) and make the file available? That way we would not need all your code or data.

**Comment by ysjakking** [comment]
This is my dumped function file. There are two functions totally and I do not know which causes the error. Perhaps both of them...
I have renamed the files to txt format just for uploading.




[function_d_dump.txt](https://github.com/Theano/Theano/files/615241/function_d_dump.txt)
[function_g_dump.txt](https://github.com/Theano/Theano/files/615242/function_g_dump.txt)
