### ISSUE TITLE
[BUG IN FGRAPH.REPLACE OR A LISTENER] maximum recursion depth exceeded

### ISSUE THREAD

**Issue by pcyin** [Theano/Theano#3341]
Hi,

My theano function fails to compile with the following error, which starts with <<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>>. The function compiles fine in `FAST_COMPILE` mode.

I tried to increase maximum recursion depth using `sys.setrecursionlimit(100000)`, then the compilation never ends and memory usage explodes (I don't think my model is such complex).

The function dump is [here](http://i.cs.hku.hk/~pcyin/func.bin). Reminiscent of #3192 (UPDATE: this is different cause), is it possible to circumvent this issue using similar trick?

Thanks in advance!

```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.RuntimeError'> maximum recursion depth exceeded in __instancecheck__ local_fill_to_alloc
ERROR: clients intersect!
  RCLIENTS of Elemwise{second,no_inplace}.0 [(Elemwise{second,no_inplace}(Elemwise{second,no_inplace}.0, Elemwise{second,no_inplace}.0), 0, <class 'theano.gof.graph.Apply'>, 39491230672)]
  NCLIENTS of Elemwise{second,no_inplace}.0 [(Elemwise{second,no_inplace}(Elemwise{second,no_inplace}.0, Elemwise{second,no_inplace}.0), 0, <class 'theano.gof.graph.Apply'>, 39491230672)]
ERROR (theano.gof.opt): Optimization failure due to: local_fill_to_alloc
08/29/2015 10:06:04 [ERROR] opt: Optimization failure due to: local_fill_to_alloc
ERROR (theano.gof.opt): TRACEBACK:
08/29/2015 10:06:04 [ERROR] opt: TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 1771, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.revert(chk)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/toolbox.py", line 192, in revert
    f()
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/toolbox.py", line 146, in __call__
    reason=("Revert", self.reason))
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/fg.py", line 516, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/fg.py", line 290, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/fg.py", line 417, in __import__
    self.__add_clients__(input, [(node, i)])
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/fg.py", line 251, in __add_clients__
    assert not set(r.clients).intersection(set(new_clients))
AssertionError

08/29/2015 10:06:04 [ERROR] opt: Traceback (most recent call last):
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 1771, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/toolbox.py", line 306, in replace_all_validate
    fgraph.revert(chk)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/toolbox.py", line 192, in revert
    f()
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/toolbox.py", line 146, in __call__
    reason=("Revert", self.reason))
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/fg.py", line 516, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/fg.py", line 290, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/fg.py", line 417, in __import__
    self.__add_clients__(input, [(node, i)])
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/fg.py", line 251, in __add_clients__
    assert not set(r.clients).intersection(set(new_clients))
AssertionError

Traceback (most recent call last):
  File "main.py", line 162, in <module>
    data=None,
  File "/Users/yinpengcheng/Research/DeepLearning/keras_qa/keras/models.py", line 637, in compile
    updates=updates, allow_input_downcast=True, mode=theano_mode)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/compile/function.py", line 309, in function
    output_keys=output_keys)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/compile/pfunc.py", line 511, in pfunc
    output_keys=output_keys)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/compile/function_module.py", line 1760, in orig_function
    output_keys=output_keys).create(
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/compile/function_module.py", line 1444, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 2106, in apply
    lopt_change = self.process_node(fgraph, node, lopt)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 1779, in process_node
    self.failure_callback(e, self, repl_pairs, lopt)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 1637, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt)
  File "/Users/yinpengcheng/Research/DeepLearning/Theano/theano/gof/opt.py", line 1625, in warn
    raise exc
AssertionError

```

**Comment by pcyin** [comment]
update: the theano function finished compilation after ~7 hours, but then crashed with the error `segmentation fault (core dumped)`. Is it possible to further debug the issue? Thanks!

**Comment by nouiz** [comment]
Part of the error message is:

 maximum recursion depth 

raise python recursion limit to help work around that. see https://docs.python.org/2/library/sys.html#sys.setrecursionlimit. I used 40000 and 50000 in the past. 50000 caused segfault in some cases, so 40k is safer.

This alone could also cause the long execution time at the same time.

**Comment by nouiz** [comment]
I tested gh-3192 again and it is still fixed. This is a different problem that I started to explain above. Mostly the graph is very big with 49446 nodes.

The way Theano currently work, this cause a us to bust the python recursion limit.
I'm able to reproduce it. I'm triing to change python limit to see if it really work around the problem:

sys.setrecursionlimit(int(sys.argv[2]))

**Comment by pcyin** [comment]
Thanks! I used Keras to build the model, and I believe this large-graph issue is partially related to how Keras build the computational graph, as explained in [this Keras issue](https://github.com/fchollet/keras/issues/666) I opened. In short, the way Keras builds the computational graph may introduce redundant nodes, and could make Theano hard to reduce the redundancy during optimization. 

Currently I rewrote my code to build the computational graph directly based on Theano, and the compilation time reduced to a few seconds and problem solved.

**Comment by nouiz** [comment]
I just made a PR https://github.com/Theano/Theano/pull/3604 that should triple Theano graph size before having this problem.

This fix the problem for the duplicate case gh-3600. I'm still running the slower use case from this issue.

**Comment by nouiz** [comment]
gh-6403 fix this completly. It transform triple recursion to simple recursion. This mean we will have the same limit as the one at the start of compilation of a Theano function.

**Comment by nouiz** [comment]
I made a follow up ticket: https://github.com/Theano/Theano/issues/3607
