### ISSUE TITLE
Theano should provide easy interface to merge_optimizer

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#3393]
This could be used in Blocks after `ComputationGraph.replace` to prevent duplicate parts in back-prop graph.

Below is a small script with which we tried (but failed) to reproduce duplication in back-prop graph. @lamblin asked to put it here as the starting point.

```python
import theano
from theano import tensor
from theano.printing import pydotprint
from theano.gof import FunctionGraph
from theano.gof.opt import merge_optimizer
from blocks.graph import ComputationGraph



# Common part
x = tensor.matrix('x')
y = x + 1

# Branch 1
y1 = y * 2
y2 = y1 - 3

# Branch 2
y3 = y * 4
y4 = y3 - 5

outputs = [y1, y2, y3, y4]
pydotprint(outputs, outfile='outputs.png')

cg = ComputationGraph(outputs)
cg_replaced = cg.replace({y2: y1 + 7})
f_replaced = theano.function(
    cg_replaced.inputs,
    theano.grad(sum(cg_replaced.outputs).sum(), x))
pydotprint(f_replaced, outfile='outputs_replaced.png')

def theano_merge(cg):
    fg = FunctionGraph(cg.inputs, cg.outputs)
    merge_optimizer.optimize(fg)
    return ComputationGraph(fg.outputs)

cg_merged = theano_merge(cg_replaced)
pydotprint(cg_merged.outputs, outfile='outputs_merged.png')
f_merged = theano.function(cg_merged.inputs, cg_merged.outputs)
```

**Comment by rizar** [comment]
I hit the problem of duplicate nodes in the gradient graph again. I am trying to manually apply `MergeOptimizer` to my graph before I compute the gradients. When I build the `FunctionGraph`, I get the following error message: 

```
Traceback (most recent call last):
  File "/u/bahdanau/Dist/dict_based_learning/bin/train_extractive_qa.py", line 8, in <module>
    main(qa_config_registry, train_extractive_qa)
  File "/u/bahdanau/Dist/dict_based_learning/dictlearn/main.py", line 74, in main
    call_training_func)()
  File "/u/bahdanau/Dist/dict_based_learning/dictlearn/util.py", line 231, in func_wrapper
    func(*args, **kwargs)
  File "/u/bahdanau/Dist/dict_based_learning/dictlearn/main.py", line 70, in call_training_func
    **training_func_kwargs)
  File "/u/bahdanau/Dist/dict_based_learning/dictlearn/extractive_qa_training.py", line 320, in train_extractive_qa
    fg = FunctionGraph(regularized_cg.inputs + regularized_cg.shared_variables, regularized_cg.outputs)
  File "/u/bahdanau/Dist/theano/theano/gof/fg.py", line 175, in __init__
    self.__import_r__(output, reason="init")
  File "/u/bahdanau/Dist/theano/theano/gof/fg.py", line 346, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/u/bahdanau/Dist/theano/theano/gof/fg.py", line 391, in __import__
    raise MissingInputError(error_msg, variable=r)
theano.gof.fg.MissingInputError: Input 0 of the graph (indices start from 0), used to compute HostFromGpu(gpuarray)(<GpuArrayType<None>(int32, matrix)>), was not provided and not given a value. Use the Theano flag exception_verbosity='high', for more information on this error.
```

I tried providing all shared variables as inputs to `FunctionGraph`, but it didn't help. Can you please help?

**Comment by nouiz** [comment]
Try with those THeano flags:

traceback.compile_limit=20
traceback.limit=20

it could add to the error msg the stack trace when the missing variable was
created.

**Comment by lamblin** [comment]
Could it be a shared random state? I'm not sure if you count them as shared variables.

**Comment by rizar** [comment]
Actually, it was. Thanks, Pascal!

BTW, it seems like I finally learnt to use MergeOptimizer, but I had to
hack Theano a bit. More updates coming.
