### ISSUE TITLE
Cannot use theano in Windows7 64bit and Anaconda

### ISSUE THREAD

**Issue by auroralinan** [Theano/Theano#3408]
It's my first time to use theano. And when I tested these code [import theano   theano.test()] I got a problem. I'm using Windows7 64bit and Anaconda environment with python 2.7.9. And the theano is cloned from Git and I did the "python setup.py develop". My g++ is the MinGW64 installed with DEV-Cpp. It seems like a compile problem but I'm not familiar with compiling C and C++ code. I'm wondering what can I do to solve this.

Error codes are as follow,  (Sorry for my poor English. )

```
Problem occurred during compilation with the command line below:
C:\Program Files (x86)\Dev-Cpp\MinGW64\bin\g++.exe -shared -g -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Anaconda\lib\site-packages\numpy\core\include -IC:\Anaconda\include -Ie:\downloads\theano-master\theano-master\theano\gof -o C:\Users\Administrator\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Administrator\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp -LC:\Anaconda\libs -LC:\Anaconda -lpython27
===============================
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o: In function `unpack_list_of_ssize_t':
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:48: undefined reference to `__imp_PyExc_TypeError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:58: undefined reference to `__imp_PyExc_IndexError'
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o: In function `CLazyLinker_init':
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:331: undefined reference to `__imp_PyCObject_Type'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:352: undefined reference to `__imp_PyExc_IndexError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:370: undefined reference to `__imp_PyExc_IndexError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:385: undefined reference to `__imp_PyExc_IndexError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:389: undefined reference to `__imp_PyExc_IndexError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:393: undefined reference to `__imp_PyExc_IndexError'
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o:C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:397: more undefined references to `__imp_PyExc_IndexError' follow
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o: In function `CLazyLinker_init':
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:405: undefined reference to `__imp_PyExc_TypeError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:420: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:426: undefined reference to `__imp_PyExc_IndexError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:444: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:440: undefined reference to `__imp_PyExc_TypeError'
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o: In function `c_call':
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:545: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:545: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:545: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:546: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:546: undefined reference to `__imp__Py_NoneStruct'
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o:C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:546: more undefined references to `__imp__Py_NoneStruct' follow
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o: In function `lazy_rec_eval':
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:618: undefined reference to `__imp_PyExc_IndexError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:641: undefined reference to `__imp_PyExc_TypeError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:649: undefined reference to `__imp_PyExc_ValueError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:657: undefined reference to `__imp_PyExc_IndexError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:708: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:715: undefined reference to `__imp_PyExc_TypeError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:721: undefined reference to `__imp_PyExc_TypeError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:771: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:771: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:772: undefined reference to `__imp__Py_NoneStruct'
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o: In function `CLazyLinker_call':
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:807: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:807: undefined reference to `__imp__Py_NoneStruct'
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o:C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:808: more undefined references to `__imp__Py_NoneStruct' follow
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o: In function `CLazyLinker_call':
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:857: undefined reference to `__imp_PyExc_AssertionError'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:900: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:900: undefined reference to `__imp__Py_NoneStruct'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:901: undefined reference to `__imp__Py_NoneStruct'
C:\Users\ADMINI~1\AppData\Local\Temp\cclEEOw9.o: In function `CLazyLinker_set_allow_gc':
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:933: undefined reference to `__imp_PyBool_Type'
C:/Users/Administrator/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-64/lazylinker_ext/mod.cpp:936: undefined reference to `__imp__Py_TrueStruct'
collect2.exe: error: ld returned 1 exit status

Traceback (most recent call last):
  File "E:/OneDrive/safeProject/signature/test.py", line 14, in <module>
    import theano
  File "e:\downloads\theano-master\theano-master\theano\__init__.py", line 63, in <module>
    from theano.compile import (
  File "e:\downloads\theano-master\theano-master\theano\compile\__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "e:\downloads\theano-master\theano-master\theano\compile\function_module.py", line 22, in <module>
    import theano.compile.mode
  File "e:\downloads\theano-master\theano-master\theano\compile\mode.py", line 12, in <module>
    import theano.gof.vm
  File "e:\downloads\theano-master\theano-master\theano\gof\vm.py", line 672, in <module>
    from . import lazylinker_c
  File "e:\downloads\theano-master\theano-master\theano\gof\lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "e:\downloads\theano-master\theano-master\theano\gof\cmodule.py", line 2176, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
. 

Process finished with exit code 1
```

**Comment by beingria** [comment]
Simply run 
conda install mingw libpython 
and give the necessary permissions when prompted.

**Comment by nouiz** [comment]
We are going to a new installation system with conda, so I'm going to close this, but if you still want the old back-end the previous comment could fix this error.
