### ISSUE TITLE
Extremely slow compilation / crash

### ISSUE THREAD

**Issue by ebenolson** [Theano/Theano#3412]
This issue has been discussed previously here: https://groups.google.com/forum/#!topic/lasagne-users/XR-jmU1pMWc

A test case is here: https://gist.github.com/ebenolson/4b2fe40ff677db7ca496

The problem seems to be related to inference of constant bounds for the lines

    input = conved[:, :, shift:input.shape[2] + shift]

When using `device=cpu`, the function compiles correctly, but each additional layer takes a far longer time to complete. Putting `None` into the `image_shape` removes the problem.

When using `device=gpu` and cuDNN, compilation fails after several minutes with an error:

    <<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.AssertionError'> ('Rebroadcast needs bool for new broadcast pattern. Got ', False) LocalOptGroup(local_dnn_conv_inplace,local_dnn_convgw_inplace,local_dnn_convgi_inplace)
    ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_dnn_conv_inplace,local_dnn_convgw_inplace,local_dnn_convgi_inplace)
    ERROR:theano.gof.opt:Optimization failure due to: LocalOptGroup(local_dnn_conv_inplace,local_dnn_convgw_inplace,local_dnn_convgi_inplace)
    ERROR (theano.gof.opt): TRACEBACK:
    ERROR:theano.gof.opt:TRACEBACK:
    ERROR (theano.gof.opt): Traceback (most recent call last):
      File "/home/eben/projects/Theano/theano/gof/opt.py", line 1797, in process_node
        fgraph.replace_all_validate(repl_pairs, reason=lopt)
      File "/home/eben/projects/Theano/theano/gof/toolbox.py", line 295, in replace_all_validate
        fgraph.replace(r, new_r, reason=reason, verbose=False)
      File "/home/eben/projects/Theano/theano/gof/fg.py", line 545, in replace
        new_r2 = r.type.convert_variable(new_r)
      File "/home/eben/projects/Theano/theano/sandbox/cuda/type.py", line 268, in convert_variable
        return theano.tensor.patternbroadcast(var, self.broadcastable)
      File "/home/eben/projects/Theano/theano/tensor/basic.py", line 3598, in patternbroadcast
        for i in xrange(len(broadcastable))])(x)
      File "/home/eben/projects/Theano/theano/compile/ops.py", line 664, in __init__
        broad)
    AssertionError: ('Rebroadcast needs bool for new broadcast pattern. Got ', False)

    ERROR:theano.gof.opt:Traceback (most recent call last):
      File "/home/eben/projects/Theano/theano/gof/opt.py", line 1797, in process_node
        fgraph.replace_all_validate(repl_pairs, reason=lopt)
      File "/home/eben/projects/Theano/theano/gof/toolbox.py", line 295, in replace_all_validate
        fgraph.replace(r, new_r, reason=reason, verbose=False)
      File "/home/eben/projects/Theano/theano/gof/fg.py", line 545, in replace
        new_r2 = r.type.convert_variable(new_r)
      File "/home/eben/projects/Theano/theano/sandbox/cuda/type.py", line 268, in convert_variable
        return theano.tensor.patternbroadcast(var, self.broadcastable)
      File "/home/eben/projects/Theano/theano/tensor/basic.py", line 3598, in patternbroadcast
        for i in xrange(len(broadcastable))])(x)
      File "/home/eben/projects/Theano/theano/compile/ops.py", line 664, in __init__
        broad)
    AssertionError: ('Rebroadcast needs bool for new broadcast pattern. Got ', False)

**Comment by nouiz** [comment]
Just to let know that I have a PR with a fix for the crash and the slowdown. The use case here is 300x faster to optimizer.

**Comment by nouiz** [comment]
By the way, thanks for the good simple way to reproduce it. It made the fix much easier.

**Comment by ebenolson** [comment]
Glad it was helpful, thank you for finding a fix.

**Comment by nouiz** [comment]
I closed to fast, the PR isn't merged yet.

**Comment by nouiz** [comment]
We merged the fix. thanks.
