### ISSUE TITLE
Better error when python-dev isn't installed (was constant_folding failure & ImportError during compile (Ubuntu, CPU))

### ISSUE THREAD

**Issue by gophercg** [Theano/Theano#3454]
TODO from this thread:
- [ ] Make Theano tell to install python-dev/python-devel when there is error to help

Setup:

```
Machine: Xeon CPUs, nvidia GPU, no root, no internet.

Versions:
*Ubuntu 12.04.1 LTS 64bit
*Theano-0.7.0
*pip-7.1.2
*python-2.7.3
*numpy-1.8.1
*scipy-0.12.0

Some theano.config auto found by Theano:
cxx (<type 'str'>) 
    Doc:  The C++ compiler to use. Currently only g++ is supported, but supporting additional compilers should not be too difficult. If it is empty, no C++ code is compiled.
    Value:  /usr/bin/g++#version: g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
blas.ldflags (<type 'str'>) 
    Doc:  lib[s] to include for [Fortran] level-3 blas implementation
    Value:  -L/usr/lib64 -lf77blas -lcblas -latlas #probably copy from numpy.
```

Got Theano package from PYPI tar.gz. Installed ok:

```
pip install --install-option="--prefix=$USERVOLPYTHON" --no-index --find-links="$THEANO_PACKAGE_DIR"
$USERVOLPYTHON: user dir of python modules.
```

.theanorc located in same dir as the compiledir folder:

```
base_compiledir = $USERVOLPYTHON/lib/python2.7/site-packages/theano/config__base_compiledir
```

Doc add example:

```
import theano.tensor as T
from theano import function
x=T.dscalar('x')
y=T.dscalar('y')
z=x+y
f=function([x,y],z)
```

Import theano twice works (Same issue as https://github.com/Theano/Theano/issues/2253, first time builds cutils_ext in compiledir & ImportErrors, then 2nd time import works. But this is not my current question). But last line function() compiling errors (Elemwise):

```
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2019, in compile_str
    return dlimport(lib_filename)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cmodule.py", line 293, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y), '\n', 'No module named tmpE6hIBV.2e70502e0c54f693d2d4f0bfd86b46ae', '[Elemwise{add,no_inplace}(x, y)]')
```

Blas example:

```
python `python -c "import os, theano; print os.path.dirname(theano.__file__)"`/misc/check_blas.py
```

Lots of errors with constant_folding & importError Dimshuffle, and last is Gemm. Adding optimizer_excluding=constant_folding in .theanorc doesn’t change output.

```
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/opt.py", line 1493, in process_node
    replacements = lopt.transform(node)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/tensor/opt.py", line 4684, in constant_folding
    no_recycling=[])
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1076, in module_from_key
    module = lnk.compile_cmodule(location)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cc.py", line 1354, in compile_cmodule
    preargs=preargs)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2019, in compile_str
    return dlimport(lib_filename)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cmodule.py", line 293, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('No module named tmpYW7QX9.18d5a8a6a9092d5ba63e47774ced3130', '[DimShuffle{x,x}(TensorConstant{0.4})]')
Traceback (most recent call last):
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/misc/check_blas.py", line 248, in <module>
    iters=options.iter, order=options.order)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/misc/check_blas.py", line 75, in execute
    f = theano.function([], updates=[(c, 0.4 * c + .8 * T.dot(a, b))])
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1076, in module_from_key
    module = lnk.compile_cmodule(location)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cc.py", line 1354, in compile_cmodule
    preargs=preargs)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2019, in compile_str
    return dlimport(lib_filename)
  File "$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof/cmodule.py", line 293, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', Gemm{inplace}(<TensorType(float64, matrix)>, TensorConstant{0.8}, <TensorType(float64, matrix)>, <TensorType(float64, matrix)>, TensorConstant{0.4}), '\n', 'No module named tmpjY6zly.f9
```

Most googling ImportError yields CUDA issues, but I haven’t tried GPU setup yet, just getting CPU compiling to work now. http://stackoverflow.com/questions/24402213/theano-test-optimization-failure-due-to-constant-folding-on-ubuntu

Trying theano.test() will ImportError on every theano function used, like above examples.

**Comment by nouiz** [comment]
There is a problem related to the compilation.

You told that you use the last release of Theano. Can you remove it and do
that multiple time (in case you have multiple version installed)

then install the development version:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by gophercg** [comment]
pip uninstall theano #OK
Restore old easy_install theano folder name so pip finds it:
pip uninstall theano #OK

On an internet pc get the zip, then copy to non-internet pc (confirmed folder contents a bit different from PYPI’s):
```
pip install --download="DOWNLOAD_DIR" --no-deps git+git://github.com/Theano/Theano.git
```

Tried severall install commands that either had numpy not found error or put files in wrong dir. This one worked:
```
pip install --install-option="--prefix=$USERVOLPYTHON" --no-index --find-links="/vol/weta/src/jyang/code/Puppeteer/lib/Python/PACKAGES/" theano
```

Import works:
```
{495} > python
Python 2.7.3 (default, Aug 20 2013, 15:31:56) 
[GCC 4.1.3 20080704 (prerelease) (Ubuntu 4.1.2-27ubuntu1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano #1st builds library dynamically & errors
ImportError: No module named cutils_ext.cutils_ext
>>> import theano #2nd different error
ImportError: cannot import name gof
Exit python. Reenter python.
>>> import theano #Ok works.
```

theano.version.version
```
0.7.0.dev-lotsofstuff
```

But add example & check_blas still yield same errors (as previous post).

**Comment by gophercg** [comment]
I set these flags that might get more details.
```
nocleanup = True
remove_gxx_opt = True
compilation_warning = True
cxxflags = -v -Wall
```

I’m comparing folders from this target PC1 (described previously) to a PC2 (linux virtual machine, has internet, no root, Ubuntu 14.04, all dependencies local installed including gcc, unknown hardware, probably on a central server). PC2 can compile & run Theano functions, version 0.7.0 (from PYPI, not dev).
In compiledir, PC2 generates 4 files each in the 2 folders, and one `__init__.py` outside. PC1 only has 3 files each, missing `__init__.pyc`. In each folder generated during function compile, PC2 has 2 extra files: key.pkl & `__init__.pyc`. Is there a way to see gcc errors? I’m assuming compilation failed, but a .so file is always generated.

Here’s the verbose gcc output of PC1, when running the add example:
```
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
COLLECT_GCC_OPTIONS='-shared' '-g' '-fno-math-errno' '-Wno-unused-label' '-Wno-unused-variable' '-Wno-write-strings' '-v' '-Wall' '-march=core2' '-mcx16' '-msahf' '-mno-movbe' '-mno-aes' '-mno-pclmul' '-mno-popcnt' '-mno-abm' '-mno-lwp' '-mno-fma' '-mno-fma4' '-mno-xop' '-mno-bmi' '-mno-tbm' '-mno-avx' '-mno-sse4.2' '-msse4.1' '--param' 'l1-cache-size=32' '--param' 'l1-cache-line-size=64' '--param' 'l2-cache-size=6144' '-mtune=core2' '-D' ' NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-m64' '-fPIC' '-I' '/vol/apps/python/2.7/ext_modules/pynumpy/1.8.1/numpy/core/include' '-I' '/vol/apps/python-2.7.3_cache1_64/include/python2.7' '-I' '$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof' '-fvisibility=hidden' '-o' '$USERVOLPYTHON/lib/python2.7/site-packages/theano/config__base_compiledir/compiledir_Linux-3.12-monkey-20140806-x86_64-with-debian-wheezy-sid-x86_64-2.7.3-64/tmpnA8jRK/8145af3f7b27a99c49078359c926b1d9.so' '-L/vol/apps/python-2.7.3_cache1_64/lib' '-shared-libgcc'
 /usr/lib/gcc/x86_64-linux-gnu/4.6/cc1plus -quiet -v -I /vol/apps/python/2.7/ext_modules/pynumpy/1.8.1/numpy/core/include -I /vol/apps/python-2.7.3_cache1_64/include/python2.7 -I $USERVOLPYTHON/lib/python2.7/site-packages/theano/gof -imultilib . -imultiarch x86_64-linux-gnu -D_GNU_SOURCE -D  NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION $USERVOLPYTHON/lib/python2.7/site-packages/theano/config__base_compiledir/compiledir_Linux-3.12-monkey-20140806-x86_64-with-debian-wheezy-sid-x86_64-2.7.3-64/tmpnA8jRK/mod.cpp -quiet -dumpbase mod.cpp -march=core2 -mcx16 -msahf -mno-movbe -mno-aes -mno-pclmul -mno-popcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-tbm -mno-avx -mno-sse4.2 -msse4.1 -mtune=core2 -m64 -auxbase mod -g -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wall -version -fno-math-errno -fPIC -fvisibility=hidden --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -fstack-protector -o /tmp/jyang/ccYj6P2E.s
GNU C++ (Ubuntu/Linaro 4.6.3-1ubuntu5) version 4.6.3 (x86_64-linux-gnu)
        compiled by GNU C version 4.6.3, GMP version 5.0.2, MPFR version 3.1.0-p3, MPC version 0.9
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /vol/apps/python/2.7/ext_modules/pynumpy/1.8.1/numpy/core/include
 /vol/apps/python-2.7.3_cache1_64/include/python2.7
 $USERVOLPYTHON/lib/python2.7/site-packages/theano/gof
 /usr/include/c++/4.6
 /usr/include/c++/4.6/x86_64-linux-gnu/.
 /usr/include/c++/4.6/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.6/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU C++ (Ubuntu/Linaro 4.6.3-1ubuntu5) version 4.6.3 (x86_64-linux-gnu)
        compiled by GNU C version 4.6.3, GMP version 5.0.2, MPFR version 3.1.0-p3, MPC version 0.9
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 65b5171ac1bd7b3f07dbea6bdb24be3d
COLLECT_GCC_OPTIONS='-shared' '-g' '-fno-math-errno' '-Wno-unused-label' '-Wno-unused-variable' '-Wno-write-strings' '-v' '-Wall' '-march=core2' '-mcx16' '-msahf' '-mno-movbe' '-mno-aes' '-mno-pclmul' '-mno-popcnt' '-mno-abm' '-mno-lwp' '-mno-fma' '-mno-fma4' '-mno-xop' '-mno-bmi' '-mno-tbm' '-mno-avx' '-mno-sse4.2' '-msse4.1' '--param' 'l1-cache-size=32' '--param' 'l1-cache-line-size=64' '--param' 'l2-cache-size=6144' '-mtune=core2' '-D' ' NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-m64' '-fPIC' '-I' '/vol/apps/python/2.7/ext_modules/pynumpy/1.8.1/numpy/core/include' '-I' '/vol/apps/python-2.7.3_cache1_64/include/python2.7' '-I' '$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof' '-fvisibility=hidden' '-o' '$USERVOLPYTHON/lib/python2.7/site-packages/theano/config__base_compiledir/compiledir_Linux-3.12-monkey-20140806-x86_64-with-debian-wheezy-sid-x86_64-2.7.3-64/tmpnA8jRK/8145af3f7b27a99c49078359c926b1d9.so' '-L/vol/apps/python-2.7.3_cache1_64/lib' '-shared-libgcc'
 as --64 -o /tmp/jyang/ccbcrt7C.o /tmp/jyang/ccYj6P2E.s
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.6/:/usr/lib/gcc/x86_64-linux-gnu/4.6/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.6/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.6/:/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-shared' '-g' '-fno-math-errno' '-Wno-unused-label' '-Wno-unused-variable' '-Wno-write-strings' '-v' '-Wall' '-march=core2' '-mcx16' '-msahf' '-mno-movbe' '-mno-aes' '-mno-pclmul' '-mno-popcnt' '-mno-abm' '-mno-lwp' '-mno-fma' '-mno-fma4' '-mno-xop' '-mno-bmi' '-mno-tbm' '-mno-avx' '-mno-sse4.2' '-msse4.1' '--param' 'l1-cache-size=32' '--param' 'l1-cache-line-size=64' '--param' 'l2-cache-size=6144' '-mtune=core2' '-D' ' NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-m64' '-fPIC' '-I' '/vol/apps/python/2.7/ext_modules/pynumpy/1.8.1/numpy/core/include' '-I' '/vol/apps/python-2.7.3_cache1_64/include/python2.7' '-I' '$USERVOLPYTHON/lib/python2.7/site-packages/theano/gof' '-fvisibility=hidden' '-o' '$USERVOLPYTHON/lib/python2.7/site-packages/theano/config__base_compiledir/compiledir_Linux-3.12-monkey-20140806-x86_64-with-debian-wheezy-sid-x86_64-2.7.3-64/tmpnA8jRK/8145af3f7b27a99c49078359c926b1d9.so' '-L/vol/apps/python-2.7.3_cache1_64/lib' '-shared-libgcc'
 /usr/lib/gcc/x86_64-linux-gnu/4.6/collect2 --sysroot=/ --build-id --no-add-needed --as-needed --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -shared -z relro -o $USERVOLPYTHON/lib/python2.7/site-packages/theano/config__base_compiledir/compiledir_Linux-3.12-monkey-20140806-x86_64-with-debian-wheezy-sid-x86_64-2.7.3-64/tmpnA8jRK/8145af3f7b27a99c49078359c926b1d9.so /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.6/crtbeginS.o -L/vol/apps/python-2.7.3_cache1_64/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../.. /tmp/jyang/ccbcrt7C.o -lpython2.7 -lstdc++ -lm -lgcc_s -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/4.6/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crtn.o

Traceback (most recent call last): same error
ImportError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y), '\n', 'No module named tmpnA8jRK.8145af3f7b27a99c49078359c926b1d9', '[Elemwise{add,no_inplace}(x, y)]')
```

PC2 has a very different environment, and this VM runs extremely slowly, so the comparison might be a bit far. Since PC1 has a lot of restrictions, I’m not sure if any environment variables need certain values, or might be overridden by the admin software management (most dependencies are from this management system, including scipy, numpy, gcc, & atlasblas). I can also post the gcc output from PC2 if you want.

**Comment by gophercg** [comment]
After comparing PC1 & PC2 environment, I managed to guess which files were referenced from which paths (which isn’t obvious from the path or debug messages). Solution was to add all the envvars to locate what I think are relevant files.

As future reference for folks to fix the cutils_ext & other errors in above posts, I added these environment variables:
```
setenv PYTHONUSERBASE $USERVOLPYTHON

setenv PATH $USERVOLPYTHON/bin:$PATH
#Optional, for running locally installed pip & theano-cache etc.

setenv LIBRARY_PATH /usr/lib
#Find libpython2.7.so in this folder.

setenv LD_LIBRARY_PATH /usr/lib:$LD_LIBRARY_PATH
#liblapack.so

setenv C_INCLUDE_PATH /usr/include/python2.7:/usr/include/x86_64-linux-gnu
#Python.h

setenv CPLUS_INCLUDE_PATH /usr/include/python2.7:/usr/include/x86_64-linux-gnu
#Python.h

setenv PYTHONPATH $USERVOLPYTHON/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg-info:$USERVOLPYTHON/lib/python2.7:$USERVOLPYTHON/lib/python2.7/site-packages:$PYTHONPATH
#Might be optional. I tried various paths during setup & import/compile.
```

It would be very helpful if Theano messages could include which files are not found, besides the functions/symbols that have error during compile. Or during install, print warnings that say libpython2.7.so etc is not in the paths required for gcc to compile correctly.

**Comment by nouiz** [comment]
done by gh-5672
