### ISSUE TITLE
NaN Values on simple Convolution operation

### ISSUE THREAD

**Issue by botev** [Theano/Theano#3484]
So I managed to short up the code for reproducing this issue and described as well here: https://github.com/Lasagne/Lasagne/issues/450#issuecomment-144984449 now with pure Theano so people can easily reproduce. Note that I'm using the bleeding edge Theano, meaning the current master branch. I do not know when it was introduced/ or maybe I'm doing something wrong, but please do help me resolve it if you know how. The issue was reproduced both on Nvidia K80 as well as on my laptop CPU. The only caveat is that it does not necessarily happen from the first iteration. The Theano code:
```
import numpy as np
import theano.tensor as T
import theano
import time
from theano.compile.nanguardmode import NanGuardMode

DIM_N = 256
N = 128
BS = 32


def main():
    # Input vars
    var_in = theano.tensor.tensor4(name="images")
    var_t = theano.tensor.tensor3(name="targets")

    # 32 filters, 3x3
    W_conv_1 = theano.shared(np.random.randn(32, 9, 3, 3).astype(theano.config.floatX), name="W_1")
    b_conv_1 = theano.shared(np.random.randn(32,).astype(theano.config.floatX),name="b_1")

    # Convolution simulating 'same' by cropping
    conved = T.nnet.conv2d(var_in, W_conv_1, image_shape=(None, 9, DIM_N, DIM_N),
                           filter_shape=(32, 9, 3, 3),
                           border_mode='full')
    s1 = var_in.shape[2]
    s2 = var_in.shape[3]
    conved = conved[:, :, 1:s1+1, 1:s2+1] + b_conv_1.dimshuffle('x', 0, 'x', 'x')

    # Apply relu
    conved = T.nnet.relu(conved)

    # 1 filter, 5x5
    W_conv_2 = theano.shared(np.random.randn(1, 32, 5, 5).astype(theano.config.floatX),name="W_2")
    b_conv_2 = theano.shared(np.random.randn(1,).astype(theano.config.floatX),name="b_2")

    # Second convolution with same by cropping
    conved_2 = T.nnet.conv2d(conved, W_conv_2, image_shape=(None, 32, DIM_N, DIM_N),
                           filter_shape=(1, 32, 5, 5),
                           border_mode='full')
    s1 = conved.shape[2]
    s2 = conved.shape[3];
    conved_2 = conved_2[:, :, 1:s1+1, 1:s2+1] + b_conv_2.dimshuffle('x', 0, 'x', 'x')

    # Sigmoid
    output = theano.tensor.nnet.sigmoid(conved_2)
    # Condition
    cond = T.clip(output, 1e-5, 1-1e-5)
    # Reshape
    reshaped = cond.reshape((-1, DIM_N, DIM_N))

    # Loss
    loss = T.nnet.binary_crossentropy(reshaped, var_t).mean()

    # Gradients
    grads = theano.grad(loss, [W_conv_1, W_conv_2, b_conv_1, b_conv_2])
    updates = [(W_conv_1, W_conv_1 - 0.001*grads[0]),
               (W_conv_2, W_conv_2 - 0.001*grads[1]),
               (b_conv_1, b_conv_1 - 0.001*grads[2]),
               (b_conv_2, b_conv_2 - 0.001*grads[3])]

    # Function
    loss_f = theano.function([var_in, var_t], loss, updates=updates,
                            mode=NanGuardMode(nan_is_error=True, inf_is_error=True, big_is_error=True))

    # Uncomment for priting tree
    # theano.printing.debugprint(loss_f, print_type=True)

    for epoch in range(10):
        train_data = [np.random.randn(N, 9, DIM_N, DIM_N).astype(theano.config.floatX),
                      np.random.randint(2, size=(N, DIM_N, DIM_N)).astype(theano.config.floatX)]
        start_time = time.time()
        # Iterate over mini batches
        loss = 0
        for i in range(0, N, BS):
            data = [var[i:i+BS] for var in train_data]
            loss += loss_f(*data)
        # Normalize the loss, and print it
        error = loss * BS / N
        timing = time.time() - start_time
        print "Epoch{}[{.0f}s]: {.3f}".format(epoch+1, timing, error)

if __name__ == '__main__':
    main()
```
The NaN gurad gives the following message:
```
AssertionError: NaN detected
NanGuardMode found an error in the output of a node in this variable:
Elemwise{true_div} [@A] ''   
 |Elemwise{mul} [@B] ''   
 | |Elemwise{mul} [@C] ''   
 | | |ConvOp{('imshp', (1, 260, 260)),('kshp', (5, 5)),('nkern', 32),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (1, 260, 260)),('kshp_logical', (5, 5)),('kshp_logical_top_aligned', True)} [@D] ''   
 | | | |IncSubtensor{Inc;::, ::, int64:int64:, int64:int64:} [@E] ''   
 | | | | |Elemwise{second,no_inplace} [@F] ''   
 | | | | | |ConvOp{('imshp', (32, 256, 256)),('kshp', (5, 5)),('nkern', 1),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'full'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (32, 256, 256)),('kshp_logical', (5, 5)),('kshp_logical_top_aligned', True)} [@G] ''   
 | | | | | | |Elemwise{mul,no_inplace} [@H] ''   
 | | | | | | | |DimShuffle{x,x,x,x} [@I] ''   
 | | | | | | | | |TensorConstant{0.5} [@J]
 | | | | | | | |Elemwise{add,no_inplace} [@K] ''   
 | | | | | | |   |Elemwise{add,no_inplace} [@L] ''   
 | | | | | | |   | |Subtensor{::, ::, int64:int64:, int64:int64:} [@M] ''   
 | | | | | | |   | | |ConvOp{('imshp', (9, 256, 256)),('kshp', (3, 3)),('nkern', 32),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'full'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (9, 256, 256)),('kshp_logical', (3, 3)),('kshp_logical_top_aligned', True)} [@N] ''   
 | | | | | | |   | | | |images [@O]
 | | | | | | |   | | | |W_1 [@P]
 | | | | | | |   | | |Constant{1} [@Q]
 | | | | | | |   | | |ScalarFromTensor [@R] ''   
 | | | | | | |   | | | |Elemwise{add,no_inplace} [@S] ''   
 | | | | | | |   | | |   |Subtensor{int64} [@T] ''   
 | | | | | | |   | | |   | |Shape [@U] ''   
 | | | | | | |   | | |   | | |images [@O]
 | | | | | | |   | | |   | |Constant{2} [@V]
 | | | | | | |   | | |   |TensorConstant{1} [@W]
 | | | | | | |   | | |Constant{1} [@X]
 | | | | | | |   | | |ScalarFromTensor [@Y] ''   
 | | | | | | |   | |   |Elemwise{add,no_inplace} [@Z] ''   
 | | | | | | |   | |     |Subtensor{int64} [@BA] ''   
 | | | | | | |   | |     | |Shape [@BB] ''   
 | | | | | | |   | |     | | |images [@O]
 | | | | | | |   | |     | |Constant{3} [@BC]
 | | | | | | |   | |     |TensorConstant{1} [@W]
 | | | | | | |   | |DimShuffle{x,0,x,x} [@BD] ''   
 | | | | | | |   |   |b_1 [@BE]
 | | | | | | |   |Elemwise{abs_,no_inplace} [@BF] ''   
 | | | | | | |     |Elemwise{add,no_inplace} [@L] ''   
 | | | | | | |W_2 [@BG]
 | | | | | |DimShuffle{x,x,x,x} [@BH] ''   
 | | | | |   |TensorConstant{0.0} [@BI]
 | | | | |Elemwise{mul} [@BJ] ''   
 | | | | | |Elemwise{mul} [@BK] ''   
 | | | | | | |Elemwise{mul} [@BL] ''   
 | | | | | | | |Elemwise{AND} [@BM] ''   
 | | | | | | | | |Elemwise{GE} [@BN] ''   
 | | | | | | | | | |sigmoid [@BO] ''   
 | | | | | | | | | | |Elemwise{add,no_inplace} [@BP] ''   
 | | | | | | | | | |   |Subtensor{::, ::, int64:int64:, int64:int64:} [@BQ] ''   
 | | | | | | | | | |   | |ConvOp{('imshp', (32, 256, 256)),('kshp', (5, 5)),('nkern', 1),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'full'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (32, 256, 256)),('kshp_logical', (5, 5)),('kshp_logical_top_aligned', True)} [@G] ''   
 | | | | | | | | | |   | |Constant{1} [@BR]
 | | | | | | | | | |   | |ScalarFromTensor [@BS] ''   
 | | | | | | | | | |   | | |Elemwise{add,no_inplace} [@BT] ''   
 | | | | | | | | | |   | |   |Subtensor{int64} [@BU] ''   
 | | | | | | | | | |   | |   | |Shape [@BV] ''   
 | | | | | | | | | |   | |   | | |Elemwise{mul,no_inplace} [@H] ''   
 | | | | | | | | | |   | |   | |Constant{2} [@BW]
 | | | | | | | | | |   | |   |TensorConstant{1} [@W]
 | | | | | | | | | |   | |Constant{1} [@BX]
 | | | | | | | | | |   | |ScalarFromTensor [@BY] ''   
 | | | | | | | | | |   |   |Elemwise{add,no_inplace} [@BZ] ''   
 | | | | | | | | | |   |     |Subtensor{int64} [@CA] ''   
 | | | | | | | | | |   |     | |Shape [@CB] ''   
 | | | | | | | | | |   |     | | |Elemwise{mul,no_inplace} [@H] ''   
 | | | | | | | | | |   |     | |Constant{3} [@CC]
 | | | | | | | | | |   |     |TensorConstant{1} [@W]
 | | | | | | | | | |   |DimShuffle{x,0,x,x} [@CD] ''   
 | | | | | | | | | |     |b_2 [@CE]
 | | | | | | | | | |DimShuffle{x,x,x,x} [@CF] ''   
 | | | | | | | | |   |TensorConstant{9.99999974738e-06} [@CG]
 | | | | | | | | |Elemwise{LE} [@CH] ''   
 | | | | | | | |   |sigmoid [@BO] ''   
 | | | | | | | |   |DimShuffle{x,x,x,x} [@CI] ''   
 | | | | | | | |     |TensorConstant{0.99998998642} [@CJ]
 | | | | | | | |Reshape{4} [@CK] ''   
 | | | | | | |   |Elemwise{add,no_inplace} [@CL] ''   
 | | | | | | |   | |Elemwise{true_div} [@CM] ''   
 | | | | | | |   | | |Elemwise{mul} [@CN] ''   
 | | | | | | |   | | | |Elemwise{neg} [@CO] ''   
 | | | | | | |   | | | | |Elemwise{second} [@CP] ''   
 | | | | | | |   | | | |   |Elemwise{neg,no_inplace} [@CQ] ''   
 | | | | | | |   | | | |   | |Elemwise{add,no_inplace} [@CR] ''   
 | | | | | | |   | | | |   |   |Elemwise{mul,no_inplace} [@CS] ''   
 | | | | | | |   | | | |   |   | |targets [@CT]
 | | | | | | |   | | | |   |   | |Elemwise{log,no_inplace} [@CU] ''   
 | | | | | | |   | | | |   |   |   |Reshape{3} [@CV] ''   
 | | | | | | |   | | | |   |   |     |Elemwise{clip,no_inplace} [@CW] ''   
 | | | | | | |   | | | |   |   |     | |sigmoid [@BO] ''   
 | | | | | | |   | | | |   |   |     | |DimShuffle{x,x,x,x} [@CF] ''   
 | | | | | | |   | | | |   |   |     | |DimShuffle{x,x,x,x} [@CI] ''   
 | | | | | | |   | | | |   |   |     |TensorConstant{[ -1 256 256]} [@CX]
 | | | | | | |   | | | |   |   |Elemwise{mul,no_inplace} [@CY] ''   
 | | | | | | |   | | | |   |     |Elemwise{sub,no_inplace} [@CZ] ''   
 | | | | | | |   | | | |   |     | |DimShuffle{x,x,x} [@DA] ''   
 | | | | | | |   | | | |   |     | | |TensorConstant{1.0} [@DB]
 | | | | | | |   | | | |   |     | |targets [@CT]
 | | | | | | |   | | | |   |     |Elemwise{log,no_inplace} [@DC] ''   
 | | | | | | |   | | | |   |       |Elemwise{sub,no_inplace} [@DD] ''   
 | | | | | | |   | | | |   |         |DimShuffle{x,x,x} [@DE] ''   
 | | | | | | |   | | | |   |         | |TensorConstant{1.0} [@DB]
 | | | | | | |   | | | |   |         |Reshape{3} [@CV] ''   
 | | | | | | |   | | | |   |DimShuffle{x,x,x} [@DF] ''   
 | | | | | | |   | | | |     |Elemwise{true_div} [@DG] ''   
 | | | | | | |   | | | |       |Elemwise{true_div} [@DH] ''   
 | | | | | | |   | | | |       | |Elemwise{true_div} [@DI] ''   
 | | | | | | |   | | | |       | | |Elemwise{second,no_inplace} [@DJ] ''   
 | | | | | | |   | | | |       | | | |Elemwise{true_div,no_inplace} [@DK] 'mean'   
 | | | | | | |   | | | |       | | | | |Elemwise{true_div,no_inplace} [@DL] ''   
 | | | | | | |   | | | |       | | | | | |Elemwise{true_div,no_inplace} [@DM] ''   
 | | | | | | |   | | | |       | | | | | | |Sum{acc_dtype=float64} [@DN] ''   
 | | | | | | |   | | | |       | | | | | | | |Elemwise{neg,no_inplace} [@CQ] ''   
 | | | | | | |   | | | |       | | | | | | |Subtensor{int64} [@DO] ''   
 | | | | | | |   | | | |       | | | | | |   |Elemwise{Cast{float32}} [@DP] ''   
 | | | | | | |   | | | |       | | | | | |   | |Shape [@DQ] ''   
 | | | | | | |   | | | |       | | | | | |   |   |Elemwise{neg,no_inplace} [@CQ] ''   
 | | | | | | |   | | | |       | | | | | |   |Constant{0} [@DR]
 | | | | | | |   | | | |       | | | | | |Subtensor{int64} [@DS] ''   
 | | | | | | |   | | | |       | | | | |   |Elemwise{Cast{float32}} [@DP] ''   
 | | | | | | |   | | | |       | | | | |   |Constant{1} [@DT]
 | | | | | | |   | | | |       | | | | |Subtensor{int64} [@DU] ''   
 | | | | | | |   | | | |       | | | |   |Elemwise{Cast{float32}} [@DP] ''   
 | | | | | | |   | | | |       | | | |   |Constant{2} [@DV]
 | | | | | | |   | | | |       | | | |TensorConstant{1.0} [@DB]
 | | | | | | |   | | | |       | | |Subtensor{int64} [@DU] ''   
 | | | | | | |   | | | |       | |Subtensor{int64} [@DS] ''   
 | | | | | | |   | | | |       |Subtensor{int64} [@DO] ''   
 | | | | | | |   | | | |targets [@CT]
 | | | | | | |   | | |Reshape{3} [@CV] ''   
 | | | | | | |   | |Elemwise{neg} [@DW] ''   
 | | | | | | |   |   |Elemwise{true_div} [@DX] ''   
 | | | | | | |   |     |Elemwise{mul} [@DY] ''   
 | | | | | | |   |     | |Elemwise{neg} [@CO] ''   
 | | | | | | |   |     | |Elemwise{sub,no_inplace} [@CZ] ''   
 | | | | | | |   |     |Elemwise{sub,no_inplace} [@DD] ''   
 | | | | | | |   |Shape [@DZ] ''   
 | | | | | | |     |Elemwise{clip,no_inplace} [@CW] ''   
 | | | | | | |Elemwise{scalar_sigmoid} [@EA] ''   
 | | | | | |   |Elemwise{add,no_inplace} [@BP] ''   
 | | | | | |Elemwise{sub} [@EB] ''   
 | | | | |   |DimShuffle{x,x,x,x} [@EC] ''   
 | | | | |   | |TensorConstant{1.0} [@DB]
 | | | | |   |Elemwise{scalar_sigmoid} [@ED] ''   
 | | | | |     |Elemwise{add,no_inplace} [@BP] ''   
 | | | | |Constant{1} [@BR]
 | | | | |ScalarFromTensor [@BS] ''   
 | | | | |Constant{1} [@BX]
 | | | | |ScalarFromTensor [@BY] ''   
 | | | |Subtensor{::, ::, ::int64, ::int64} [@EE] ''   
 | | |   |DimShuffle{1,0,2,3} [@EF] ''   
 | | |   | |W_2 [@BG]
 | | |   |Constant{-1} [@EG]
 | | |   |Constant{-1} [@EH]
 | | |DimShuffle{x,x,x,x} [@I] ''   
 | |Elemwise{add,no_inplace} [@L] ''   
 |Elemwise{Abs} [@EI] ''   
   |Elemwise{add,no_inplace} [@L] ''   


Apply node that caused the error: Elemwise{true_div}(Elemwise{mul}.0, Elemwise{Abs}.0)
Toposort index: 105
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(32, 32, 256, 256), (32, 32, 256, 256)]
Inputs strides: [(8388608, 262144, 1024, 4), (8388608, 262144, 1024, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{add,no_inplace}(Elemwise{mul}.0, Elemwise{true_div}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
alex@botev-ThinkPad-T440:~/work/python/Toppings$ python toppings/test_theano.py 
Traceback (most recent call last):
  File "toppings/test_theano.py", line 83, in <module>
    main()
  File "toppings/test_theano.py", line 76, in main
    loss += loss_f(*data)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/compile/function_module.py", line 852, in __call__
    outputs = self.fn()
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/link.py", line 1014, in f
    raise_with_op(node, *thunks)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/link.py", line 1012, in f
    wrapper(i, node, *thunks)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/compile/nanguardmode.py", line 326, in nan_check
    do_check_on(x[0], node, fn, False)
  File "/home/alex/.local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/compile/nanguardmode.py", line 293, in do_check_on
    raise AssertionError(msg)
AssertionError: NaN detected
NanGuardMode found an error in the output of a node in this variable:
Elemwise{true_div} [@A] ''   
 |Elemwise{mul} [@B] ''   
 | |Elemwise{mul} [@C] ''   
 | | |ConvOp{('imshp', (1, 260, 260)),('kshp', (5, 5)),('nkern', 32),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (1, 260, 260)),('kshp_logical', (5, 5)),('kshp_logical_top_aligned', True)} [@D] ''   
 | | | |IncSubtensor{Inc;::, ::, int64:int64:, int64:int64:} [@E] ''   
 | | | | |Elemwise{second,no_inplace} [@F] ''   
 | | | | | |ConvOp{('imshp', (32, 256, 256)),('kshp', (5, 5)),('nkern', 1),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'full'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (32, 256, 256)),('kshp_logical', (5, 5)),('kshp_logical_top_aligned', True)} [@G] ''   
 | | | | | | |Elemwise{mul,no_inplace} [@H] ''   
 | | | | | | | |DimShuffle{x,x,x,x} [@I] ''   
 | | | | | | | | |TensorConstant{0.5} [@J]
 | | | | | | | |Elemwise{add,no_inplace} [@K] ''   
 | | | | | | |   |Elemwise{add,no_inplace} [@L] ''   
 | | | | | | |   | |Subtensor{::, ::, int64:int64:, int64:int64:} [@M] ''   
 | | | | | | |   | | |ConvOp{('imshp', (9, 256, 256)),('kshp', (3, 3)),('nkern', 32),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'full'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (9, 256, 256)),('kshp_logical', (3, 3)),('kshp_logical_top_aligned', True)} [@N] ''   
 | | | | | | |   | | | |images [@O]
 | | | | | | |   | | | |W_1 [@P]
 | | | | | | |   | | |Constant{1} [@Q]
 | | | | | | |   | | |ScalarFromTensor [@R] ''   
 | | | | | | |   | | | |Elemwise{add,no_inplace} [@S] ''   
 | | | | | | |   | | |   |Subtensor{int64} [@T] ''   
 | | | | | | |   | | |   | |Shape [@U] ''   
 | | | | | | |   | | |   | | |images [@O]
 | | | | | | |   | | |   | |Constant{2} [@V]
 | | | | | | |   | | |   |TensorConstant{1} [@W]
 | | | | | | |   | | |Constant{1} [@X]
 | | | | | | |   | | |ScalarFromTensor [@Y] ''   
 | | | | | | |   | |   |Elemwise{add,no_inplace} [@Z] ''   
 | | | | | | |   | |     |Subtensor{int64} [@BA] ''   
 | | | | | | |   | |     | |Shape [@BB] ''   
 | | | | | | |   | |     | | |images [@O]
 | | | | | | |   | |     | |Constant{3} [@BC]
 | | | | | | |   | |     |TensorConstant{1} [@W]
 | | | | | | |   | |DimShuffle{x,0,x,x} [@BD] ''   
 | | | | | | |   |   |b_1 [@BE]
 | | | | | | |   |Elemwise{abs_,no_inplace} [@BF] ''   
 | | | | | | |     |Elemwise{add,no_inplace} [@L] ''   
 | | | | | | |W_2 [@BG]
 | | | | | |DimShuffle{x,x,x,x} [@BH] ''   
 | | | | |   |TensorConstant{0.0} [@BI]
 | | | | |Elemwise{mul} [@BJ] ''   
 | | | | | |Elemwise{mul} [@BK] ''   
 | | | | | | |Elemwise{mul} [@BL] ''   
 | | | | | | | |Elemwise{AND} [@BM] ''   
 | | | | | | | | |Elemwise{GE} [@BN] ''   
 | | | | | | | | | |sigmoid [@BO] ''   
 | | | | | | | | | | |Elemwise{add,no_inplace} [@BP] ''   
 | | | | | | | | | |   |Subtensor{::, ::, int64:int64:, int64:int64:} [@BQ] ''   
 | | | | | | | | | |   | |ConvOp{('imshp', (32, 256, 256)),('kshp', (5, 5)),('nkern', 1),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'full'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (32, 256, 256)),('kshp_logical', (5, 5)),('kshp_logical_top_aligned', True)} [@G] ''   
 | | | | | | | | | |   | |Constant{1} [@BR]
 | | | | | | | | | |   | |ScalarFromTensor [@BS] ''   
 | | | | | | | | | |   | | |Elemwise{add,no_inplace} [@BT] ''   
 | | | | | | | | | |   | |   |Subtensor{int64} [@BU] ''   
 | | | | | | | | | |   | |   | |Shape [@BV] ''   
 | | | | | | | | | |   | |   | | |Elemwise{mul,no_inplace} [@H] ''   
 | | | | | | | | | |   | |   | |Constant{2} [@BW]
 | | | | | | | | | |   | |   |TensorConstant{1} [@W]
 | | | | | | | | | |   | |Constant{1} [@BX]
 | | | | | | | | | |   | |ScalarFromTensor [@BY] ''   
 | | | | | | | | | |   |   |Elemwise{add,no_inplace} [@BZ] ''   
 | | | | | | | | | |   |     |Subtensor{int64} [@CA] ''   
 | | | | | | | | | |   |     | |Shape [@CB] ''   
 | | | | | | | | | |   |     | | |Elemwise{mul,no_inplace} [@H] ''   
 | | | | | | | | | |   |     | |Constant{3} [@CC]
 | | | | | | | | | |   |     |TensorConstant{1} [@W]
 | | | | | | | | | |   |DimShuffle{x,0,x,x} [@CD] ''   
 | | | | | | | | | |     |b_2 [@CE]
 | | | | | | | | | |DimShuffle{x,x,x,x} [@CF] ''   
 | | | | | | | | |   |TensorConstant{9.99999974738e-06} [@CG]
 | | | | | | | | |Elemwise{LE} [@CH] ''   
 | | | | | | | |   |sigmoid [@BO] ''   
 | | | | | | | |   |DimShuffle{x,x,x,x} [@CI] ''   
 | | | | | | | |     |TensorConstant{0.99998998642} [@CJ]
 | | | | | | | |Reshape{4} [@CK] ''   
 | | | | | | |   |Elemwise{add,no_inplace} [@CL] ''   
 | | | | | | |   | |Elemwise{true_div} [@CM] ''   
 | | | | | | |   | | |Elemwise{mul} [@CN] ''   
 | | | | | | |   | | | |Elemwise{neg} [@CO] ''   
 | | | | | | |   | | | | |Elemwise{second} [@CP] ''   
 | | | | | | |   | | | |   |Elemwise{neg,no_inplace} [@CQ] ''   
 | | | | | | |   | | | |   | |Elemwise{add,no_inplace} [@CR] ''   
 | | | | | | |   | | | |   |   |Elemwise{mul,no_inplace} [@CS] ''   
 | | | | | | |   | | | |   |   | |targets [@CT]
 | | | | | | |   | | | |   |   | |Elemwise{log,no_inplace} [@CU] ''   
 | | | | | | |   | | | |   |   |   |Reshape{3} [@CV] ''   
 | | | | | | |   | | | |   |   |     |Elemwise{clip,no_inplace} [@CW] ''   
 | | | | | | |   | | | |   |   |     | |sigmoid [@BO] ''   
 | | | | | | |   | | | |   |   |     | |DimShuffle{x,x,x,x} [@CF] ''   
 | | | | | | |   | | | |   |   |     | |DimShuffle{x,x,x,x} [@CI] ''   
 | | | | | | |   | | | |   |   |     |TensorConstant{[ -1 256 256]} [@CX]
 | | | | | | |   | | | |   |   |Elemwise{mul,no_inplace} [@CY] ''   
 | | | | | | |   | | | |   |     |Elemwise{sub,no_inplace} [@CZ] ''   
 | | | | | | |   | | | |   |     | |DimShuffle{x,x,x} [@DA] ''   
 | | | | | | |   | | | |   |     | | |TensorConstant{1.0} [@DB]
 | | | | | | |   | | | |   |     | |targets [@CT]
 | | | | | | |   | | | |   |     |Elemwise{log,no_inplace} [@DC] ''   
 | | | | | | |   | | | |   |       |Elemwise{sub,no_inplace} [@DD] ''   
 | | | | | | |   | | | |   |         |DimShuffle{x,x,x} [@DE] ''   
 | | | | | | |   | | | |   |         | |TensorConstant{1.0} [@DB]
 | | | | | | |   | | | |   |         |Reshape{3} [@CV] ''   
 | | | | | | |   | | | |   |DimShuffle{x,x,x} [@DF] ''   
 | | | | | | |   | | | |     |Elemwise{true_div} [@DG] ''   
 | | | | | | |   | | | |       |Elemwise{true_div} [@DH] ''   
 | | | | | | |   | | | |       | |Elemwise{true_div} [@DI] ''   
 | | | | | | |   | | | |       | | |Elemwise{second,no_inplace} [@DJ] ''   
 | | | | | | |   | | | |       | | | |Elemwise{true_div,no_inplace} [@DK] 'mean'   
 | | | | | | |   | | | |       | | | | |Elemwise{true_div,no_inplace} [@DL] ''   
 | | | | | | |   | | | |       | | | | | |Elemwise{true_div,no_inplace} [@DM] ''   
 | | | | | | |   | | | |       | | | | | | |Sum{acc_dtype=float64} [@DN] ''   
 | | | | | | |   | | | |       | | | | | | | |Elemwise{neg,no_inplace} [@CQ] ''   
 | | | | | | |   | | | |       | | | | | | |Subtensor{int64} [@DO] ''   
 | | | | | | |   | | | |       | | | | | |   |Elemwise{Cast{float32}} [@DP] ''   
 | | | | | | |   | | | |       | | | | | |   | |Shape [@DQ] ''   
 | | | | | | |   | | | |       | | | | | |   |   |Elemwise{neg,no_inplace} [@CQ] ''   
 | | | | | | |   | | | |       | | | | | |   |Constant{0} [@DR]
 | | | | | | |   | | | |       | | | | | |Subtensor{int64} [@DS] ''   
 | | | | | | |   | | | |       | | | | |   |Elemwise{Cast{float32}} [@DP] ''   
 | | | | | | |   | | | |       | | | | |   |Constant{1} [@DT]
 | | | | | | |   | | | |       | | | | |Subtensor{int64} [@DU] ''   
 | | | | | | |   | | | |       | | | |   |Elemwise{Cast{float32}} [@DP] ''   
 | | | | | | |   | | | |       | | | |   |Constant{2} [@DV]
 | | | | | | |   | | | |       | | | |TensorConstant{1.0} [@DB]
 | | | | | | |   | | | |       | | |Subtensor{int64} [@DU] ''   
 | | | | | | |   | | | |       | |Subtensor{int64} [@DS] ''   
 | | | | | | |   | | | |       |Subtensor{int64} [@DO] ''   
 | | | | | | |   | | | |targets [@CT]
 | | | | | | |   | | |Reshape{3} [@CV] ''   
 | | | | | | |   | |Elemwise{neg} [@DW] ''   
 | | | | | | |   |   |Elemwise{true_div} [@DX] ''   
 | | | | | | |   |     |Elemwise{mul} [@DY] ''   
 | | | | | | |   |     | |Elemwise{neg} [@CO] ''   
 | | | | | | |   |     | |Elemwise{sub,no_inplace} [@CZ] ''   
 | | | | | | |   |     |Elemwise{sub,no_inplace} [@DD] ''   
 | | | | | | |   |Shape [@DZ] ''   
 | | | | | | |     |Elemwise{clip,no_inplace} [@CW] ''   
 | | | | | | |Elemwise{scalar_sigmoid} [@EA] ''   
 | | | | | |   |Elemwise{add,no_inplace} [@BP] ''   
 | | | | | |Elemwise{sub} [@EB] ''   
 | | | | |   |DimShuffle{x,x,x,x} [@EC] ''   
 | | | | |   | |TensorConstant{1.0} [@DB]
 | | | | |   |Elemwise{scalar_sigmoid} [@ED] ''   
 | | | | |     |Elemwise{add,no_inplace} [@BP] ''   
 | | | | |Constant{1} [@BR]
 | | | | |ScalarFromTensor [@BS] ''   
 | | | | |Constant{1} [@BX]
 | | | | |ScalarFromTensor [@BY] ''   
 | | | |Subtensor{::, ::, ::int64, ::int64} [@EE] ''   
 | | |   |DimShuffle{1,0,2,3} [@EF] ''   
 | | |   | |W_2 [@BG]
 | | |   |Constant{-1} [@EG]
 | | |   |Constant{-1} [@EH]
 | | |DimShuffle{x,x,x,x} [@I] ''   
 | |Elemwise{add,no_inplace} [@L] ''   
 |Elemwise{Abs} [@EI] ''   
   |Elemwise{add,no_inplace} [@L] ''   


Apply node that caused the error: Elemwise{true_div}(Elemwise{mul}.0, Elemwise{Abs}.0)
Toposort index: 105
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(32, 32, 256, 256), (32, 32, 256, 256)]
Inputs strides: [(8388608, 262144, 1024, 4), (8388608, 262144, 1024, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{add,no_inplace}(Elemwise{mul}.0, Elemwise{true_div}.0)]]
```
I do not understand where does this `Abs` operator comes from and why it is dividing by it. Additionally I attach the graph image below. For easy navigating the `Abs` operator I'm talking about is located in the center about 3/4 of the image going up to down. It comes from an Elementwise addition of of `b_1` and the `SubTensor` of the gradient (I think) Convolution of the `W_1` with `images`. Why do we take take there an `Abs` and divide by it? 

The picture: https://www.dropbox.com/s/04bl3vurkzyvrlu/theano.svg?dl=0

**Comment by rudhbaskaran** [comment]
Is there any resolution or this yet? I am having a similar problem with the bleeding edge version. I did a pull on Oct 14th, but it didn't help.

**Comment by harpone** [comment]
Also getting weird NanGuardMode NaN errors whie training a model... basically the model trains just fine, but sometimes I get mysterious NaNs (I have a deep RNN and an RBM layer at the top... I think RBMs have previously had some nan problems) and that's why I tried the NanGuardMode... but NanGuardMode complains about NaNs right at the beginning of training!

So is NanGuardMode actually working right at the moment?

**Comment by nouiz** [comment]
NanGuardMode is currently too strict. This PR should help on that. You can
try it now:

https://github.com/Theano/Theano/pull/3768

**Comment by harpone** [comment]
Ah OK, thanks! I'll give it a try ASAP.

- Heikki

**Comment by nouiz** [comment]
Closing as no news. if you still have problems, reopen this issue.
