### ISSUE TITLE
Reshaping with slice of symbolic shape contining negative number causing compiler failure

### ISSUE THREAD

**Issue by danielrenshaw** [Theano/Theano#3555]
Executing the following program fails with the following exception on the `theano.function` line.

```
import numpy
import theano
import theano.tensor as tt

x = tt.ltensor3()
f = theano.function([x], outputs=x.reshape(x.shape[:-1]))
f(numpy.arange(6).reshape((3, 2, 1)))
```

Generates this output:

```
===============================
00001   #include <Python.h>
<SNIP>
00312   
Problem occurred during compilation with the command line below:
C:\TDM-GCC-64\bin\g++.exe -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=sandybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=sandybridge -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Anaconda\lib\site-packages\numpy\core\include -IC:\Anaconda\include -I<snip>\theano\gof -o <snip>\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.10-64\tmpvpvp9m\beeb5fb0ecc8fea1a8829c4ca9589a25.pyd <snip>\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.10-64\tmpvpvp9m\mod.cpp -LC:\Anaconda\libs -LC:\Anaconda -lpython27
===============================
<snip>\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.10-64\tmpvpvp9m\mod.cpp: In member function 'int {anonymous}::__struct_compiled_op_beeb5fb0ecc8fea1a8829c4ca9589a25::run()':
<snip>\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.10-64\tmpvpvp9m\mod.cpp:113:33: error: size of array 'new_dims' is negative
             npy_intp new_dims[-1];
                                 ^

Traceback (most recent call last):
  File "<snip>/reshape_bug.py", line 6, in <module>
    f = theano.function([x], outputs=x.reshape(x.shape[:-1]))
  File "<snip>\theano\compile\function.py", line 308, in function
    output_keys=output_keys)
  File "<snip>\theano\compile\pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "<snip>\theano\compile\function_module.py", line 1778, in orig_function
    defaults)
  File "<snip>\theano\compile\function_module.py", line 1642, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "<snip>\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "<snip>\theano\gof\vm.py", line 1037, in make_all
    no_recycling))
  File "<snip>\theano\gof\op.py", line 918, in make_thunk
    no_recycling)
  File "<snip>\theano\gof\op.py", line 836, in make_c_thunk
    output_storage=node_output_storage)
  File "<snip>\theano\gof\cc.py", line 1198, in make_thunk
    keep_lock=keep_lock)
  File "<snip>\theano\gof\cc.py", line 1136, in __compile__
    keep_lock=keep_lock)
  File "<snip>\theano\gof\cc.py", line 1593, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "<snip>\theano\gof\cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "<snip>\theano\gof\cc.py", line 1504, in compile_cmodule
    preargs=preargs)
  File "<snip>\theano\gof\cmodule.py", line 2185, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Reshape{-1}(<TensorType(int64, 3D)>, MakeVector{dtype='int64'}.0), '\n', "Compilation failed (return status=1): <snip>\\Theano\\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.10-64\\tmpvpvp9m\\mod.cpp: In member function 'int {anonymous}::__struct_compiled_op_beeb5fb0ecc8fea1a8829c4ca9589a25::run()':\r. <snip>\\Theano\\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.10-64\\tmpvpvp9m\\mod.cpp:113:33: error: size of array 'new_dims' is negative\r.              npy_intp new_dims[-1];\r.                                  ^\r. ", '[Reshape{-1}(<TensorType(int64, 3D)>, <TensorType(int64, vector)>)]')

Process finished with exit code 1
```

Running on Windows 10 with latest Theano version from Github.

For comparison, the following alternate line works fine

```
f = theano.function([x], outputs=x.reshape(x.shape[:2]))
```

**Comment by lamblin** [comment]
It seems to have been fixed somehow, it works in the current master.
```python
array([[0, 1],
       [2, 3],
       [4, 5]])
```
