### ISSUE TITLE
GPU-Test theano.sandbox.cuda.tests.test_blas:test_downsample fails with other config flags than 'optimizer=None'

### ISSUE THREAD

**Issue by pkainz** [Theano/Theano#3578]
Hi, 
my system config:
- numpy 1.9.2
- scipy 0.16.1
- theano bleeding-edge 
- GPU: GeForce GTX TITAN BLACK
- CUDA 7.5
- cuDNN 3.0.07
- Nvidia driver version 352.21
- empyt/no `.theanorc` file 

a GPU test fails with the following output (I ran it separately again):
```bash
$ THEANO_FLAGS=device=cpu,exception_verbosity=high theano-nose theano.sandbox.cuda.tests.test_blas:test_downsample
```
```
Using gpu device 0: GeForce GTX TITAN Black (CNMeM is disabled)
F
======================================================================
FAIL: theano.sandbox.cuda.tests.test_blas.test_downsample
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/phil/theano/theano/sandbox/cuda/tests/test_blas.py", line 404, in test_downsample
    assert numpy.allclose(gg(), gg2()), shp
  File "/home/phil/theano/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/phil/theano/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/phil/theano/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
AssertionError: Theano Assert failed!
Apply node that caused the error: Assert{msg='Theano Assert failed!'}(GpuDownsampleFactorMaxGradGrad{ds=(2, 2), ignore_border=True}.0, Elemwise{eq,no_inplace}.0, Elemwise{eq,no_inplace}.0)
Toposort index: 15
Inputs types: [CudaNdarrayType(float32, 4D), TensorType(int8, scalar), TensorType(int8, scalar)]
Inputs shapes: [(10, 10, 5, 5), (), ()]
Inputs strides: [(250, 25, 5, 1), (), ()]
Inputs values: ['not shown', array(0, dtype=int8), array(0, dtype=int8)]
Outputs clients: [[GpuElemwise{Mul}[(0, 1)](CudaNdarrayConstant{[[[[ 2.]]]]}, Assert{msg='Theano Assert failed!'}.0)]]

Debugprint of the apply node: 
Assert{msg='Theano Assert failed!'} [@A] <CudaNdarrayType(float32, 4D)> ''   
 |GpuDownsampleFactorMaxGradGrad{ds=(2, 2), ignore_border=True} [@B] <CudaNdarrayType(float32, 4D)> ''   
 | |a [@C] <CudaNdarrayType(float32, 4D)>
 | |GpuDnnPool [@D] <CudaNdarrayType(float32, 4D)> ''   
 | | |GpuContiguous [@E] <CudaNdarrayType(float32, 4D)> ''   
 | | | |a [@C] <CudaNdarrayType(float32, 4D)>
 | | |GpuDnnPoolDesc{ws=(2, 2), stride=(2, 2), mode='max', pad=(0, 0)} [@F] <CDataType{cudnnPoolingDescriptor_t}> ''   
 | |a [@C] <CudaNdarrayType(float32, 4D)>
 |Elemwise{eq,no_inplace} [@G] <TensorType(int8, scalar)> ''   
 | |Elemwise{Composite{maximum((i0 + ((i1 + i2) // i3)), i4)}} [@H] <TensorType(int64, scalar)> ''   
 | | |TensorConstant{1} [@I] <TensorType(int64, scalar)>
 | | |TensorConstant{-2} [@J] <TensorType(int64, scalar)>
 | | |Shape_i{2} [@K] <TensorType(int64, scalar)> ''   
 | | | |a [@C] <CudaNdarrayType(float32, 4D)>
 | | |TensorConstant{2} [@L] <TensorType(int64, scalar)>
 | | |TensorConstant{0} [@M] <TensorType(int64, scalar)>
 | |Shape_i{2} [@K] <TensorType(int64, scalar)> ''   
 |Elemwise{eq,no_inplace} [@N] <TensorType(int8, scalar)> ''   
   |Elemwise{Composite{maximum((i0 + ((i1 + i2) // i3)), i4)}} [@O] <TensorType(int64, scalar)> ''   
   | |TensorConstant{1} [@I] <TensorType(int64, scalar)>
   | |TensorConstant{-2} [@J] <TensorType(int64, scalar)>
   | |Shape_i{3} [@P] <TensorType(int64, scalar)> ''   
   | | |a [@C] <CudaNdarrayType(float32, 4D)>
   | |TensorConstant{2} [@L] <TensorType(int64, scalar)>
   | |TensorConstant{0} [@M] <TensorType(int64, scalar)>
   |Shape_i{3} [@P] <TensorType(int64, scalar)> ''   

Storage map footprint:
 - GpuDnnPoolGrad.0, Shape: (10, 10, 10, 11), ElemSize: 4 Byte(s), TotalSize: 44000 Byte(s)
 - a, Shared Input, Shape: (10, 10, 10, 11), ElemSize: 4 Byte(s), TotalSize: 44000 Byte(s)
 - GpuContiguous.0, Shape: (10, 10, 10, 11), ElemSize: 4 Byte(s), TotalSize: 44000 Byte(s)
 - GpuDownsampleFactorMaxGradGrad{ds=(2, 2), ignore_border=True}.0, Shape: (10, 10, 5, 5), ElemSize: 4 Byte(s), TotalSize: 10000 Byte(s)
 - GpuContiguous.0, Shape: (10, 10, 5, 5), ElemSize: 4 Byte(s), TotalSize: 10000 Byte(s)
 - TensorConstant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{-2}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{2}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - CudaNdarrayConstant{[[[[ 2.]]]]}, Shape: (1, 1, 1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[[[[ 0.]]]]}, Shape: (1, 1, 1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - Elemwise{eq,no_inplace}.0, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - Elemwise{eq,no_inplace}.0, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 TotalSize: 108042.0 Byte(s) 0.000 GB
 TotalSize inputs: 44040.0 Byte(s) 0.000 GB

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.

----------------------------------------------------------------------
Ran 1 test in 10.533s

FAILED (failures=1)

```

However, if I manually disable the optimizer
```bash
$ THEANO_FLAGS=device=cpu,exception_verbosity=high,optimizer=None theano-nose theano.sandbox.cuda.tests.test_blas:test_downsample
```
the test passes:
```
Using gpu device 0: GeForce GTX TITAN Black (CNMeM is disabled)
.
----------------------------------------------------------------------
Ran 1 test in 29.018s

OK
```

Is this a serious issue with the cuDNN/gemm optimizers?
How should I interpret the failing test?

Thanks for your support, best regards.

**Comment by pkainz** [comment]
Follow up: using the option `optimizer=fast_compile` also works.

**Comment by nouiz** [comment]
I know about this, I just didn't got the time to fix it.

As this is an assert raised when it shouldn't in a test, if you don't have
assert with your own code, you can ignore this error.

**Comment by nouiz** [comment]
I have a fix in this PR: https://github.com/Theano/Theano/pull/3728

**Comment by pkainz** [comment]
Great, thanks!
