### ISSUE TITLE
Pip install on top of current anaconda + mkl not linking correctly

### ISSUE THREAD

**Issue by kungfujam** [Theano/Theano#3630]
Following installation instructions [here](http://deeplearning.net/software/theano/install.html), it's implied that theano should work 'out of the box' alongside anaconda with mkl:

> If you install their MKL Optimizations product (free for academic, ~30$ otherwise) Theano will also be optimized as we will reuse the faster BLAS version automatically.

I tried to run the deeplearning.net logistic regression code [here](http://deeplearning.net/tutorial/logreg.html#putting-it-all-together) and got an error about `mkl`. If I install on top of an anaconda environment without `mkl`, everything works fine.
### System details

Mac OS 10.10.5.
conda version : 3.18.4
conda-build version : 1.18.1
python version : 2.7.10.final.0
### Instructions
- Install conda with default packages
- [Obtain an mkl licence](http://docs.continuum.io/mkl-optimizations/index) [(Free for students)](https://www.continuum.io/anaconda-academic-subscriptions-available)
- Install mkl

``` bash
conda install mkl
```
- Install Theano

``` bash
pip install Theano
```
- Run the [logistic regression example](http://deeplearning.net/tutorial/logreg.html#putting-it-all-together)

``` bash
python logistic_sgd.py
```
## Stacktrace

``` bash
$ python logistic_sgd.py 
... loading data
... building the model
INFO (theano.gof.compilelock): Waiting for existing lock by process '20107' (I am process '21069')
INFO (theano.gof.compilelock): To manually release the lock, delete /Users/kungfujam/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/lock_dir
Traceback (most recent call last):
  File "logistic_sgd.py", line 470, in <module>
    sgd_optimization_mnist()
  File "logistic_sgd.py", line 311, in sgd_optimization_mnist
    y: test_set_y[index * batch_size: (index + 1) * batch_size]
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1076, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1354, in compile_cmodule
    preargs=preargs)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2019, in compile_str
    return dlimport(lib_filename)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 293, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', Dot22(Subtensor{int64:int64:}.0, W), '\n', 'dlopen(/Users/kungfujam/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/tmpohGdUI/eb163660e6e45b373cd7909e14efd44a.so, 2): Library not loaded: libmkl_intel_lp64.dylib\n  Referenced from: /Users/kungfujam/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/tmpohGdUI/eb163660e6e45b373cd7909e14efd44a.so\n  Reason: image not found', '[Dot22(<TensorType(float64, matrix)>, W)]')
```

**Comment by nouiz** [comment]
A temp work around is to use this Theano flag:

blas.ldflags=

**Comment by nouiz** [comment]
Also, youneed to use Theano development version:

pip uninstall Theano

then see:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

That will probably fix it, if not tell us.

**Comment by kungfujam** [comment]
So I need to install the dev version and set blas.ldflags to be nothing (i.e. empty string)?

**Comment by nouiz** [comment]
First try the development version. Maybe that alone will make it work.

If not, try the change to the flag.

Keep us updated.

**Comment by kungfujam** [comment]
Dev version install alone did not work (dev install building from cloned github). Where exactly do I need to change the flag?

**Comment by kungfujam** [comment]
Ok, used `THEANO_FLAGS='blas.ldflags='  python setup.py develop` and got the same error.

Code
-------
```bash
c106183:git kungfujam$ git clone git://github.com/Theano/Theano.git
Cloning into 'Theano'...
remote: Counting objects: 120889, done.
remote: Compressing objects: 100% (96/96), done.
oReceiving objects:  14% (16925/120889), 3.07 MiB | 724.00 KiB/s    
remote: Total 120889 (delta 48), reused 0 (delta 0), pack-reused 120793
Receiving objects: 100% (120889/120889), 43.86 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (95514/95514), done.
Checking connectivity... done.
c106183:git kungfujam$ cd Theano
c106183:Theano kungfujam$ THEANO_FLAGS='blas.ldflags='  python setup.py develop
running develop
running egg_info
creating Theano.egg-info
writing requirements to Theano.egg-info/requires.txt
writing Theano.egg-info/PKG-INFO
writing top-level names to Theano.egg-info/top_level.txt
writing dependency_links to Theano.egg-info/dependency_links.txt
writing pbr to Theano.egg-info/pbr.json
writing manifest file 'Theano.egg-info/SOURCES.txt'
reading manifest file 'Theano.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 9: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'Theano.egg-info/SOURCES.txt'
running build_ext
Creating /Users/kungfujam/anaconda/lib/python2.7/site-packages/Theano.egg-link (link to .)
Adding Theano 0.7.0 to easy-install.pth file
Installing theano-cache script to /Users/kungfujam/anaconda/bin
Installing theano-nose script to /Users/kungfujam/anaconda/bin
Installing theano-test script to /Users/kungfujam/anaconda/bin

Installed /Users/kungfujam/git/Theano
Processing dependencies for Theano==0.7.0
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /Users/kungfujam/anaconda/lib/python2.7/site-packages
Searching for scipy==0.16.0
Best match: scipy 0.16.0
Adding scipy 0.16.0 to easy-install.pth file

Using /Users/kungfujam/anaconda/lib/python2.7/site-packages
Searching for numpy==1.9.3
Best match: numpy 1.9.3
Adding numpy 1.9.3 to easy-install.pth file

Using /Users/kungfujam/anaconda/lib/python2.7/site-packages
Finished processing dependencies for Theano==0.7.0
c106183:Theano kungfujam$ cd ../DDS/code
c106183:Theano kungfujam$ python logistic_sgd.py 
... loading data
... building the model
Traceback (most recent call last):
  File "logistic_sgd.py", line 470, in <module>
    sgd_optimization_mnist()
  File "logistic_sgd.py", line 311, in sgd_optimization_mnist
    y: test_set_y[index * batch_size: (index + 1) * batch_size]
  File "/Users/kungfujam/git/Theano/theano/compile/function.py", line 308, in function
    output_keys=output_keys)
  File "/Users/kungfujam/git/Theano/theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "/Users/kungfujam/git/Theano/theano/compile/function_module.py", line 1778, in orig_function
    defaults)
  File "/Users/kungfujam/git/Theano/theano/compile/function_module.py", line 1642, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/Users/kungfujam/git/Theano/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/Users/kungfujam/git/Theano/theano/gof/vm.py", line 1037, in make_all
    no_recycling))
  File "/Users/kungfujam/git/Theano/theano/gof/op.py", line 918, in make_thunk
    no_recycling)
  File "/Users/kungfujam/git/Theano/theano/gof/op.py", line 836, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/kungfujam/git/Theano/theano/gof/cc.py", line 1209, in make_thunk
    keep_lock=keep_lock)
  File "/Users/kungfujam/git/Theano/theano/gof/cc.py", line 1147, in __compile__
    keep_lock=keep_lock)
  File "/Users/kungfujam/git/Theano/theano/gof/cc.py", line 1604, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/Users/kungfujam/git/Theano/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/Users/kungfujam/git/Theano/theano/gof/cc.py", line 1515, in compile_cmodule
    preargs=preargs)
  File "/Users/kungfujam/git/Theano/theano/gof/cmodule.py", line 2195, in compile_str
    return dlimport(lib_filename)
  File "/Users/kungfujam/git/Theano/theano/gof/cmodule.py", line 331, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', Dot22(Subtensor{int64:int64:}.0, W), '\n', 'dlopen(/Users/kungfujam/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/tmpouynW6/5b8e0e3c738e8a98be19af2f610d232c.so, 2): Library not loaded: libmkl_intel_lp64.dylib\n  Referenced from: /Users/kungfujam/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/tmpouynW6/5b8e0e3c738e8a98be19af2f610d232c.so\n  Reason: image not found', '[Dot22(<TensorType(float64, matrix)>, W)]')
```

**Comment by nouiz** [comment]
Theano flags aren't set during installation, but are used each time a
new python process is started:

use:


THEANO_FLAGS='blas.ldflags='  python ...

**Comment by kungfujam** [comment]
`THEANO_FLAGS='blas.ldflags='  python logistic_sgd.py` works like a charm.

**Comment by integeruser** [comment]
As written in the stack trace, this happens because library `libmkl_intel_lp64.dylib` can't be found.
Try this workaround:
```
~ ➤ find / -name "libmkl_intel_lp64.dylib" 2>/dev/null                                                            15:59
/Users/fcagnin/miniconda2/lib/libmkl_intel_lp64.dylib
/Users/fcagnin/miniconda2/pkgs/mkl-rt-11.1-p0/lib/libmkl_intel_lp64.dylib
~ ➤ cd /Users/fcagnin/miniconda2/lib/                                                                             16:00
lib ➤ python ...
```
This works for me, without setting any `THEANO_FLAGS`.

**Comment by kungfujam** [comment]
That workaround also works for me...however, not a hugely convenient solution!

**Comment by abergeron** [comment]
The real problem is that all the the dylibs for mkl don't have the right install_name.  This is either to discourage reuse or just a packaging error.

Because of that we either need to set DYLD_FALLBACK_LIBRARY_PATH=/path/to/mkl/dylibs (but before the python process which imports Theano starts otherwise it's ignored) or try to patch up the library path in each module that depends on it after compilation using install_name_tool (and even that would require some special option to the compiler to pad the install names otherwise the new ones won't fit).

So not much has been done because it's a relatively large amount of work.

**Comment by abergeron** [comment]
Since I don't have time to work on this, one thing that could help is if you report this issue to Continuum (maybe with a link to this issue).  If they fix the install_name of the dylibs then the problem should resolve itself :)

**Comment by kungfujam** [comment]
Cheers, will do.

**Comment by nouiz** [comment]
we have new conda packages that work on Mac, so should be fixed
