### ISSUE TITLE
Cannot construct a ufunc with more than 32 operands

### ISSUE THREAD

**Issue by ignatenkobrain** [Theano/Theano#3635]
```python
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7fd405826ed0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/gof/opt.py", line 194, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/gof/opt.py", line 79, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/tensor/opt.py", line 5892, in apply
    new_outputs = self.optimizer(node)
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/tensor/opt.py", line 5839, in local_fuse
    ret = local_fuse(n)
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/tensor/opt.py", line 5839, in local_fuse
    ret = local_fuse(n)
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/tensor/opt.py", line 5839, in local_fuse
    ret = local_fuse(n)
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/tensor/opt.py", line 5827, in local_fuse
    n = maker(node, C)(*inputs).owner
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/tensor/opt.py", line 5640, in maker
    return OP(scalar_op)
  File "/home/brain/git/neurofedora/python-theano/Theano-rel-0.7.1a1/theano/tensor/elemwise.py", line 503, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 33 and outputs = 1)
```

**Comment by ignatenkobrain** [comment]
duplicate of #3052

**Comment by nouiz** [comment]
To be sure, this is fixed, update to the development version.
