### ISSUE TITLE
Gradient on dnn.GpuDnnConv3d parameter raises an error that the input tensor should be 4D

### ISSUE THREAD

**Issue by jgwak** [Theano/Theano#3659]
I'm facing a strange issue regarding gradient on convolutional layer parameter using `GpuDnnConv3d`.

I took gradient of parameters using `T.grad(cost, W)` where `W` is a parameter of `GpuDnnConv3d`.
I expect theano to use `GpuDnnConv3dGradW` as defined in here:
https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L638
I also expect the input to be 5D: (b, c, 0, 1, 2)

However, I get the following error:

```
ERROR (theano.gof.opt): Optimization failure due to: local_dnn_convw_output_merge
ERROR (theano.gof.opt): node: GpuElemwise{add,no_inplace}(GpuDnnConv3dGradW{algo='none', inplace=False}.0, GpuElemwise{mul,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/jgwak/.pyv/theano/local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 1787, in process_node
    replacements = lopt.transform(node)
  File "/home/jgwak/.pyv/theano/local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/opt_util.py", line 121, in opt
    return maker(targ, *inputs)
  File "/home/jgwak/.pyv/theano/local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/dnn.py", line 2266, in local_dnn_convw_output_merge
    return [GpuDnnConvGradW()(*inputs)]
  File "/home/jgwak/.pyv/theano/local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/op.py", line 600, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/jgwak/.pyv/theano/local/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/dnn.py", line 801, in make_node
    raise TypeError('img must be 4D tensor')
TypeError: img must be 4D tensor
```

As you can see in the error message, It did use `GpuDnnConv3dGradW` as expected.

However, it raises an error complaining that the input should be 4D. Actually, the code that raises the error above is in `GpuDnnConvGradW` class, which is a class for 2D convolution, which seems to be the reason why it is complaining that the image shape doesn't match.

I expect the code not to raise error by the following check in `GpuDnnConv3dGradW`:
https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L869

FYI, the version of my theano is HEAD of this github repository.

**Comment by nouiz** [comment]
You build the graph on the CPU and is it the optimization that move them to the GPU that cause this. You can ignore it. Thanks for the report. I know how to fix it.

**Comment by nouiz** [comment]
I have a PR, thanks.
