### ISSUE TITLE
Broken compilation following recent commit

### ISSUE THREAD

**Issue by jonhoo** [Theano/Theano#3692]
The merge of 79745f4334c257ec783c73bff5c38f4fd007ac9a in 09605e7cae876e15c5502c4edaba6a9644c50c11 breaks compilation for me on [this network](https://github.com/jonhoo/periscope/blob/ce5b82c5a810ee8aadc35161262f3b07d42510d0/main.py#L67), giving the error below. If I revert that commit, compilation works fine.

```
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    prediction = lasagne.layers.get_output(network)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/lasagne/layers/helper.py", line 185, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/lasagne/layers/dnn.py", line 308, in get_output_for
    conv_mode=conv_mode
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/sandbox/cuda/dnn.py", line 1153, in dnn_conv
    desc_op.subsample)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/sandbox/cuda/dnn.py", line 557, in get_out_shape
    subsample)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/tensor/nnet/abstract_conv2d.py", line 51, in get_conv_output_shape
    for i in range(len(subsample)))
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/tensor/nnet/abstract_conv2d.py", line 51, in <genexpr>
    for i in range(len(subsample)))
IndexError: list index out of range
```

**Comment by skaae** [comment]
I gets the same error 

commit: 79745f4334c257ec783c73bff5c38f4fd007ac9a

```
dnn_conv(X, w, subsample=(2, 2), border_mode=(2, 2))
```
gives the error

X is a 4d tensor
W is a (128, 3, 5, 5) shared

**Comment by jhallard** [comment]
anyone found how to fix this?

**Comment by nouiz** [comment]
fixed by: https://github.com/Theano/Theano/pull/3700

thanks for the report. You can just update Theano to get the fix.
