### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by jonhoo** [Theano/Theano#3762]
91f084979cc63f6ad7dedb050c9012f5f1d73efe breaks Theano for me. I get the following error when trying to build the models:

```
Traceback (most recent call last):
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/cc.py", line 1058, in header_dirs
    ret += x.c_header_dirs(c_compiler)
TypeError: c_header_dirs() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import experiment
  File "/home/ubuntu/periscope/experiment.py", line 1, in <module>
    import lasagne
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/lasagne/__init__.py", line 12, in <module>
    import theano
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 31, in test_nvidia_driver1
    profile=False)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/compile/function_module.py", line 1778, in orig_function
    defaults)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/compile/function_module.py", line 1642, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/vm.py", line 1037, in make_all
    no_recycling))
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/sandbox/cuda/__init__.py", line 287, in make_thunk
    compute_map, no_recycling)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/op.py", line 929, in make_thunk
    no_recycling)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/op.py", line 847, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/cc.py", line 1207, in make_thunk
    keep_lock=keep_lock)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/cc.py", line 1152, in __compile__
    keep_lock=keep_lock)
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/cc.py", line 1594, in cthunk_factory
    key = self.cmodule_key()
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/cc.py", line 1291, in cmodule_key
    header_dirs=self.header_dirs(),
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/gof/cc.py", line 1060, in header_dirs
    ret += x.c_header_dirs()
  File "/home/ubuntu/periscope/env/lib/python3.4/site-packages/theano/sandbox/cuda/type.py", line 478, in c_header_dirs
    ret = [os.path.dirname(cuda_ndarray.__file__)]
AttributeError: ('The following error happened while compiling the node', GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>), '\n', "'module' object has no attribute '__file__'")
```

**Comment by nouiz** [comment]
Can you delete your theano compiledir? This is a strange error. Which
version of python do you use?

**Comment by jonhoo** [comment]
Curious. Can no longer replicate this issue. I got the error above when compiling after having removed `~/.theano` if I remember correctly. This was python 3.4.

**Comment by realzoberg** [comment]
Got the same issue on Windows x32 with cuda 6.5. Can someone help me?

**Comment by nouiz** [comment]
Be sure to use Theano development version. Be sure to detele your Theano
compilation cache completly.

If that don't fix it, my guess is that you have mixed Theano version. So
uninstall all your version. uninstall it many times, in case some version
hides others one, then reinstall Theano.

**Comment by lucasb-eyer** [comment]
Just adding for future reference that I had this error, and clearing the (very) old theano cache, i.e. `rm -rf ~/.theano`, indeed fixed this.

**Comment by imk1** [comment]
I am having the same problem.  I tried clearing everything in my theano cash as well as uninstalling theano until I could do it anymore, deleting everything theano-related from my computer, and then re-installing theano.  Does anyone have any other suggestions?  Thanks so much!

**Comment by IsaacGuan** [comment]
Hi @imk1,
Maybe you could try to downgrade your NumPy to 1.15.4 (at least this version works for me), and then clean the cache. Theano is too old to be compatible with the latest packages...

**Comment by imk1** [comment]
Downgrading numpy to version 1.15.4 seems to have solved the problem.  Thanks!
