### ISSUE TITLE
nvcc compilation problem

### ISSUE THREAD

**Issue by fayeshine** [Theano/Theano#3771]
In file included from /home/wenjian/anaconda2/include/python2.7/Python.h:8:0,
                 from mod.cu:1:
/home/wenjian/anaconda2/include/python2.7/pyconfig.h:1194:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/local/cuda/bin/..//include/host_config.h:161:0,
                 from /usr/local/cuda/bin/..//include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:228:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /home/wenjian/anaconda2/include/python2.7/Python.h:8:0,
                 from mod.cu:1:
/home/wenjian/anaconda2/include/python2.7/pyconfig.h:1216:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/local/cuda/bin/..//include/host_config.h:161:0,
                 from /usr/local/cuda/bin/..//include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:169:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
mod.cu(305): warning: subscript out of range
mod.cu(314): error: too few arguments in function call
1 error detected in the compilation of "/tmp/tmpxft_00000a04_00000000-9_mod.cpp1.ii".

['nvcc', '-shared', '-O3', '-arch=sm_52', '-m64', '-Xcompiler', '-fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/wenjian/.theano/compiledir_Linux-4.2--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.11-64/cuda_ndarray', '-I/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda', '-I/home/wenjian/anaconda2/lib/python2.7/site-packages/numpy/core/include', '-I/home/wenjian/anaconda2/include/python2.7', '-I/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof', '-o', '/home/wenjian/.theano/compiledir_Linux-4.2--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.11-64/tmp2Tt_iv/7af9a02d0c906ccfd3747d633455c63a.so', 'mod.cu', '-L/home/wenjian/anaconda2/lib', '-lpython2.7', '-lcudnn', '-lcudart']
Traceback (most recent call last):
  File "cnn.py", line 67, in <module>
    model.compile(loss='categorical_crossentropy', optimizer=sgd)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/keras/models.py", line 423, in compile
    self._train = K.function(train_ins, [train_loss], updates=updates)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 361, in function
    return Function(inputs, outputs, updates=updates)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 354, in __init__
    allow_input_downcast=True, **kwargs)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1778, in orig_function
    defaults)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1642, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py", line 1037, in make_all
    no_recycling))
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 287, in make_thunk
    compute_map, no_recycling)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 929, in make_thunk
    no_recycling)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 847, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1207, in make_thunk
    keep_lock=keep_lock)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1152, in __compile__
    keep_lock=keep_lock)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1602, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1513, in compile_cmodule
    preargs=preargs)
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py", line 382, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuDnnConvDesc{border_mode=(1, 1), subsample=(1, 1), conv_mode='conv'}(MakeVector{dtype='int64'}.0, MakeVector{dtype='int64'}.0), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -arch=sm_52 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/wenjian/.theano/compiledir_Linux-4.2--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.11-64/cuda_ndarray -I/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda -I/home/wenjian/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/wenjian/anaconda2/include/python2.7 -I/home/wenjian/anaconda2/lib/python2.7/site-packages/theano/gof -o /home/wenjian/.theano/compiledir_Linux-4.2--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.11-64/tmp2Tt_iv/7af9a02d0c906ccfd3747d633455c63a.so mod.cu -L/home/wenjian/anaconda2/lib -lpython2.7 -lcudnn -lcudart', "[GpuDnnConvDesc{border_mode=(1, 1), subsample=(1, 1), conv_mode='conv'}(<TensorType(int64, vector)>, <TensorType(int64, vector)>)]")

**Comment by fayeshine** [comment]
besides, it's cuDNN 4

**Comment by fayeshine** [comment]
moved to cudnn 3 and bug fixed, however it means should try to fix cudnn 4 compatbility

**Comment by nouiz** [comment]
We have a PR for it:

https://github.com/Theano/Theano/pulls/carriepl

**Comment by fayeshine** [comment]
@nouiz ,glad to see it to be merged ASAP!

**Comment by nouiz** [comment]
cudnn v4 is merged
