### ISSUE TITLE
no such instruction: `vfnmadd312sd .LC15(%rip),%xmm0,%xmm1'.

### ISSUE THREAD

**Issue by twiecki** [Theano/Theano#3780]
```
======================================================================
ERROR: Failure: Exception (("Compilation failed (return status=1): /tmp/ccBcGK8x.s: Assembler messages:. /tmp/ccBcGK8x.s:1528: Error: no such instruction: `vfnmadd312sd .LC15(%rip),%xmm0,%xmm1'. /tmp/ccBcGK8x.s:1852: Error: no such instruction: `vfnmadd312sd .LC15(%rip),%xmm0,%xmm1'. /tmp/ccBcGK8x.s:2134: Error: no such instruction: `vfnmadd312sd .LC14(%rip),%xmm4,%xmm0'. /tmp/ccBcGK8x.s:2135: Error: no such instruction: `vfnmadd312sd .LC15(%rip),%xmm4,%xmm0'. ", '[psi(x)]'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_special_functions.py", line 21, in test_functions
    psi = function([x], ps.psi(x))
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/op.py", line 647, in __call__
    no_recycling=[])
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 815, in make_thunk
    compute_map, no_recycling)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/op.py", line 1168, in make_thunk
    compute_map, no_recycling)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/op.py", line 932, in make_thunk
    no_recycling)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/op.py", line 850, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/cc.py", line 1207, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/cc.py", line 1152, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/cc.py", line 1602, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/cc.py", line 1513, in compile_cmodule
    preargs=preargs)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2187, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ("Compilation failed (return status=1): /tmp/ccBcGK8x.s: Assembler messages:. /tmp/ccBcGK8x.s:1528: Error: no such instruction: `vfnmadd312sd .LC15(%rip),%xmm0,%xmm1'. /tmp/ccBcGK8x.s:1852: Error: no such instruction: `vfnmadd312sd .LC15(%rip),%xmm0,%xmm1'. /tmp/ccBcGK8x.s:2134: Error: no such instruction: `vfnmadd312sd .LC14(%rip),%xmm4,%xmm0'. /tmp/ccBcGK8x.s:2135: Error: no such instruction: `vfnmadd312sd .LC15(%rip),%xmm4,%xmm0'. ", '[psi(x)]')
```

This is from various pymc3 tests that are failing on travis:
https://travis-ci.org/pymc-devs/pymc3/jobs/96825763

**Comment by nouiz** [comment]
I have renamed this issue and I think I'll keep it as a permanent issue to help people find work around. This can happen due to many problems outside of Theano like gcc bugs or installation problems.

Be sure to use Theano development version. We fix sometimes this problems.

A quick work around is to use a Theano flag like: 
- gcc.cxxflags='-march=core2" 
- gcc.cxxflags='-march=corei7" 
- gcc.cxxflags='-march=corei7-avx" 

Try from the top to the bottom. The first is more generic, the laster use newer GPU. Use the latest that work.

Can you confirm this fix it for you? Can you tell which version of g++ that you use and which processor do you have?

**Comment by twiecki** [comment]
Thanks @nouiz, that fixed it: https://github.com/pymc-devs/pymc3/commit/8f4ca56142cda23930e9161608013182a4996892

**Comment by xiongxiaochu** [comment]
there is an error occured when I am compling my theano project:
Exception: ('The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}(Shape_i{0}.0, InplaceDimShuffle{0,x,1}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Wo0123, Poi_vector0123, Uo0123, Wf0123, Uf0123, Wi0123, Ui0123, Wc0123, Uc0123, ScalarFromTensor.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, Subtensor{::, int32}.0, Alloc.0, Alloc.0), '\n', 'The following error happened while compiling the node', Elemwise{Composite{(i0 - sqr(i1))}}[(0, 1)](TensorConstant{(1,) of 1.0}, InplaceDimShuffle{x}.0), '\n', "Compilation failed (return status=1): /tmp/ccTb8sm4.s: Assembler messages:. /tmp/ccTb8sm4.s:1416: Error: no such instruction: `vfnmadd312sd (%rcx),%xmm0,%xmm0'. ", '[Elemwise{Composite{(i0 - sqr(i1))}}[(0, 1)](TensorConstant{(1,) of 1.0}, <TensorType(float64, (True,))>)]')

I have tried the solutions above, and this problem is not solved. How could I solve it?

**Comment by nouiz** [comment]
You mean you set the Theano flag: 

    gcc.cxxflags='-march=core2'

And that this don't solve your problem? Can you print theano.config.gcc.cxxflags to be sure you set it correctly? Be sure to use Theano  0.8rc1 or Theano dev version: http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by xiongxiaochu** [comment]
I used this command to set the Theano flag:
THEANO_FLAGS='config.gcc.cxxflags=-march=core2'  python my_model.py
and the output for "print theano.config.gcc.cxxflags" is nothing. So I'm not sure whether it has been set correctly. Additionally, I am using the Theano dev version.
This time, I got the same error message...

**Comment by nouiz** [comment]
Use:


THEANO_FLAGS='gcc.cxxflags=-march=core2' python my_model.py

**Comment by ehosseiniasl** [comment]
I have tried all gcc flags in theanorc, but the error remains. I can import theano in ipython (Mac OS X), but 'illegal instruction: 4' appears when running django test which loads theano model. below is the related line in .theanorc:
[gcc]
cxxflags=-march=core2

**Comment by ehosseiniasl** [comment]
I also run this:
THEANO_FLAGS=cxx='' theano-nose -v theano/compile/tests/test_builders.py:T_OpFromGraph.test_grad

got this error:
ERROR: Failure: ImportError (No module named nose_parameterized)

**Comment by nouiz** [comment]
This is a new dependency of Theano tests. You can install it like this:

pip install --user nose_parameterized

**Comment by ehosseiniasl** [comment]
ok, I solved that issue. Now I got below one when 'import theano'

Exception: Compilation failed (return status=1): clang: error: unsupported option '-b mi2'. clang: error: unsupported option '-b mi'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sse4a'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-tbm'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-fma4'. clang: error: unknown argument: '-target-feature'
