### ISSUE TITLE
Optimization error with typed_list

### ISSUE THREAD

**Issue by mirandaconrado** [Theano/Theano#3808]
When using typed_list (MWE provided below), the following error appears:
```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> 'NoneType' object has no attribute '__getitem__' constant_folding
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 1527, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/usr/lib64/python2.7/site-packages/theano/gof/toolbox.py", line 259, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/lib64/python2.7/site-packages/theano/gof/fg.py", line 502, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/usr/lib64/python2.7/site-packages/theano/gof/fg.py", line 449, in change_input
    r, new_r, reason=reason)
  File "/usr/lib64/python2.7/site-packages/theano/gof/fg.py", line 577, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/theano/tensor/opt.py", line 1124, in on_change_input
    self.update_shape(new_r, r)
  File "/usr/lib64/python2.7/site-packages/theano/tensor/opt.py", line 937, in update_shape
    merged_shape.append(r_shape[i])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Based on the error, I investigated opt.py and found that the line 910 (r_shape = self.shape_of[r]) returns None when r prints "Constant{[array([1]...y}"¹ on the MWE below and r's type is "\<class 'theano.gof.graph.Constant'\>".

MWE:
```
import theano
import theano.tensor as T
import theano.typed_list

m = T.ones((1,), dtype='int8')
l = theano.typed_list.make_list([m, m])
f = theano.function(
        [],
        l
)
print f()
```

¹ Bonus bug: line 458 of gof/graph.py should be "name = name[:10] + '...' + name[-10:]" instead of using "name[-10]".

**Comment by nouiz** [comment]
What is Tone? Can you make an example that work by itself? It will help
debugging this.

At worst, this will cause a less optimized graph, but it should give good
answer.

**Comment by mirandaconrado** [comment]
For some reason the e-mail system stripped some dots. "Tones" is supposed to be "T (dot) ones". The example includes only theano and default python things.

**Comment by nouiz** [comment]
Thanks. Fixed here: https://github.com/Theano/Theano/pull/3811
