### ISSUE TITLE
"Delete your Theano cache. The automatic recompilation did not work."

### ISSUE THREAD

**Issue by citihome** [Theano/Theano#3818]
When I use Lasagne's pool.py, I need to update my theano from version 0.7.0 to 0.8.0 which provide mean_pooling function through theano.tensor.signal.downsample.max_pool_2d(there is mode param).
As I'm the Anaconda user, then I update this through the following command,

conda install -c https://conda.anaconda.org/trung theano
it seems upgrade is success, but when I import theano lib, it returns exception like this
hutch@hutch-ubuntu:~$ conda install -c https://conda.anaconda.org/trung theano
Fetching package metadata: ........
Solving package specifications: ...................
Package plan for installation in environment /usr/local/anaconda:

The following NEW packages will be INSTALLED:

    theano: 0.8-py27_0

Proceed ([y]/n)? y

Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
hutch@hutch-ubuntu:~$ python
Python 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda/lib/python2.7/site-packages/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/usr/local/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 549, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/usr/local/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 435, in use
    "Delete your Theano cache. The automatic"
Exception: Delete your Theano cache. The automatic recompilation did not work.
>>> 

========
can anyone show me how to fixed the problem?(I had also tried to upgrade theano by pip install github project package, failed too, It shows 
command /usr/local/pypy-2.6.1-linux 64/bin/pypy - c "import setuptools, tokenize; __file__ = '/tmp/pip-build-7z14uQ/scipy/setup'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n','\n'), __file__, 'exec'); install --record /tmp/pip-ilqubE-record/install_record.txt --single-version-externally-managed -compile failed with error code in /tmp/pip-build-7zI4uQ/scipy
I guess there is something wrong with scipy, but scipy works well in my environment.

**Comment by nouiz** [comment]
You can delete your theano cache with the command:

"theano-cache purge"

If that do not work do this in python to know the path of the cache and
delete this directory:

python
import theano
print theano.config.compiledir

**Comment by nouiz** [comment]
As no activity, I close.

**Comment by xgenvn** [comment]
AFAIK, from the source code it's under ***C:\Users\<username>\AppData\Local\Theano***. I met same errors, import theano produced same errors over and over, I couldn't even access to the config class.

**Comment by nouiz** [comment]
Can you delete manually the compiledir? If that don't fix it, give your
full error message.

**Comment by xgenvn** [comment]
Hi, to fix the issue I had to delete compiledir manually. I guess there's an issue with windows file system, when number of files is huge, deleting those folders might fail.

**Comment by Hazarapet** [comment]
Guys I've got the same error and can't fix it
the "theano-cache clear" gives the following

WARNING (theano.gof.cmodule): Ignoring init arguments for module cache because it was created prior to this call

and "theano-cache purge" gives 

Using cuDNN version 5110 on context None
Mapped name None to device cuda0: GeForce GTX 1070 (0000:01:00.0)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1488, in _on_atexit
    self.clear_old()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1292, in clear_old
    cleanup=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 746, in refresh
    subdirs = sorted(os.listdir(self.dirname))
OSError: [Errno 2] No such file or directory: '/home/user/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.12-64'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1488, in _on_atexit
    self.clear_old()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1292, in clear_old
    cleanup=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 746, in refresh
    subdirs = sorted(os.listdir(self.dirname))
OSError: [Errno 2] No such file or directory: '/home/user/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.12-64'

I've also removed the cache dir but it didn't help. is there any idea how I can fix it.?

**Comment by nouiz** [comment]
I don't know what is going on, but can you manually delete this directory:

/home/user/.theano/

**Comment by Hazarapet** [comment]
I'm doing it. but theano-cache purge gives the same thing.

**Comment by nouiz** [comment]
By manually delete, I mean "rm -rf dir". Not using theano-cache.

**Comment by Hazarapet** [comment]
I know. "rm -rf" is always effective

**Comment by nouiz** [comment]
I don't have this problem here, so I can't test my fix. I have in this PR a
fix for that exact case, but another crash could be after that. Can you try
it?

https://github.com/Theano/Theano/pull/6068

thanks

**Comment by paulorenanmelo** [comment]
I tried cleaning the theano cache, changing reference folders (which I don't fully understand yet). It works fine under CPU, but when I use the .theanorc.txt I get the following error with stack trace:

> Problem occurred during compilation with the command line below:
> "C:\ProgramData\Anaconda3\Library\mingw-w64\bin\g++.exe" -shared -g C:\ProgramData\Anaconda3\MinGW\x86_64-w64-mingw32\include -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include" -I"C:\ProgramData\Anaconda3\include" -I"C:\ProgramData\Anaconda3\lib\site-packages\theano\gof" -L"C:\ProgramData\Anaconda3\libs" -L"C:\ProgramData\Anaconda3" -o C:\ProgramData\Anaconda3\pkgs\theano-0.9.0-py36_0\Lib\site-packages\theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-3.6.1-64\lazylinker_ext\lazylinker_ext.pyd C:\ProgramData\Anaconda3\pkgs\theano-0.9.0-py36_0\Lib\site-packages\theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-3.6.1-64\lazylinker_ext\mod.cpp -lpython36
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-3397704bd624>", line 1, in <module>
>     import theano
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\__init__.py", line 66, in <module>
>     from theano.compile import (
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\__init__.py", line 10, in <module>
>     from theano.compile.function_module import *
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 21, in <module>
>     import theano.compile.mode
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\mode.py", line 10, in <module>
>     import theano.gof.vm
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\vm.py", line 662, in <module>
>     from . import lazylinker_c
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
>     preargs=args)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2316, in compile_str
>     (status, compile_stderr.replace('\n', '. ')))
> 
> . collect2.exe: error: ld returned 1 exit status C:/ProgramData/Anaconda3/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\ProgramData\Anaconda3\MinGW\x86_64-w64-mingw32\include: Permission denied

Could someone enlighten me?

Here's my .theanorc.txt

> [global]
> floatX=float32
> device=cuda
> base_compiledir=C:\ProgramData\Anaconda3\pkgs\theano-0.9.0-py36_0\Lib\site-packages\theano
> 
> [lib]
> cnmem=1
> 
> [nvcc]
> fastmath=True
> 
> [gcc]
> cxxflags=C:\ProgramData\Anaconda3\MinGW\x86_64-w64-mingw32\include
> 
> [cuda]
> root=CUDAToolkit_8.0.{00D3C40F-BDD2-44CA-B8D6-36119DF9D909}
> 
> [dnn]
> include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
> library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

I currently have the dnn lines commented, just another failed attempt

Thanks

**Comment by nouiz** [comment]
Check the permission on that directory:

C:\ProgramData\Anaconda3\MinGW\x86_64-w64-mingw32\include

The error tell you don't have the permission to it.

**Comment by paulorenanmelo** [comment]
Thanks nouiz.
I tried changing attributes of the folder applying to subfolders and files to remove the option "read-only" which apears as a square, rather than a tick (meaning there might be some files or folders read-only)
That made the stack trace a bit more simple, but still I can't have access to the folder and I have no idea why.
I also tried using the downloads folder in my user location (maybe ProgramData has restrictions because of being a system folder?) and it still doesn't give me access. I am obviously running the console as an admin.

Stack trace update:
> Problem occurred during compilation with the command line below:
> "C:\ProgramData\Anaconda3\Library\mingw-w64\bin\g++.exe" -shared -g C:\Users\Root\Downloads\Theano-0.9.0\MinGW\lib\gcc\x86_64-w64-mingw32\4.7.0\include -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include" -I"C:\ProgramData\Anaconda3\include" -I"C:\ProgramData\Anaconda3\lib\site-packages\theano\gof" -L"C:\ProgramData\Anaconda3\libs" -L"C:\ProgramData\Anaconda3" -o C:\Users\Root\Downloads\Theano-0.9.0\Theano-0.9.0\theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-3.6.1-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Root\Downloads\Theano-0.9.0\Theano-0.9.0\theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-3.6.1-64\lazylinker_ext\mod.cpp -lpython36
> C:/ProgramData/Anaconda3/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Root\Downloads\Theano-0.9.0\MinGW\lib\gcc\x86_64-w64-mingw32\4.7.0\include: Permission denied
> collect2.exe: error: ld returned 1 exit status
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 75, in <module>
>     raise ImportError()
> ImportError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 92, in <module>
>     raise ImportError()
> ImportError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\__init__.py", line 66, in <module>
>     from theano.compile import (
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\__init__.py", line 10, in <module>
>     from theano.compile.function_module import *
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 21, in <module>
>     import theano.compile.mode
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\mode.py", line 10, in <module>
>     import theano.gof.vm
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\vm.py", line 662, in <module>
>     from . import lazylinker_c
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
>     preargs=args)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2316, in compile_str
>     (status, compile_stderr.replace('\n', '. ')))
> Exception: Compilation failed (return status=1): C:/ProgramData/Anaconda3/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Root\Downloads\Theano-0.9.0\MinGW\lib\. collect2.exe: error: ld returned 1 exit status denied

**Comment by philipperemy** [comment]
This error happened to me when I downgraded theano from the latest to 0.7.
I could not make it work again.
I had to upgrade again!

**Comment by nouiz** [comment]
Thanks for the idea about the cause and fix.

Do not use Theano 0.7. It is way too old.
