### ISSUE TITLE
print_profile failed with profile_optimizer=True

### ISSUE THREAD

**Issue by rubenvereecken** [Theano/Theano#3833]
I tried compiling my Theano graphs today to see if I could do better somewhere. I stumbled upon an error, and managed to reproduce it only when `theano.config.profile_optimizer=True`. The other relevant configs are:

    theano.config.profile = True
    theano.config.profile_memory = True
    theano.config.profiling.debugprint = True

The error I get occurs in `atexit.print_profile`:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "~/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "~/.local/lib/python2.7/site-packages/theano/compile/profiling.py", line 141, in _atexit_print_fn
    n_apply_to_print=config.profiling.n_apply)
  File "~/.local/lib/python2.7/site-packages/theano/compile/profiling.py", line 1304, in summary
    self.optimizer_profile[1])
  File "~/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 318, in print_profile
    level=level + 1)
  File "~/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 2392, in print_profile
    o.print_profile(stream, prof, level + 2)
  File "~/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 867, in print_profile
    nb_fail, nb_merged, nb_constant), file=stream)
TypeError: %d format: a number is required, not TopoOptimizer
Error in sys.exitfunc:
Traceback (most recent call last):
  File "~/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "~/.local/lib/python2.7/site-packages/theano/compile/profiling.py", line 141, in _atexit_print_fn
    n_apply_to_print=config.profiling.n_apply)
  File "~/.local/lib/python2.7/site-packages/theano/compile/profiling.py", line 1304, in summary
    self.optimizer_profile[1])
  File "~/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 318, in print_profile
    level=level + 1)
  File "~/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 2392, in print_profile
    o.print_profile(stream, prof, level + 2)
  File "~/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 867, in print_profile
    nb_fail, nb_merged, nb_constant), file=stream)
TypeError: %d format: a number is required, not TopoOptimizer
```

 I checked the source code but I hope someone else can make more sense of it. I don't absolutely need to profile the optimizer (more interested in the rest), but it seemed interesting to look into.

**Comment by nouiz** [comment]
I suppose that you use the development version of Theano. If not update to
it.

If you use it, can you give a function_dump to allow me to investigate?

http://www.deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

I'm not sure when I'll have the time to look.

**Comment by rubenvereecken** [comment]
Alright, that wasn't too difficult. Here you go, the [network in question].(https://github.com/Theano/Theano/files/78854/network.zip)

I'll also add I got this bit when the program starts up:
```
theano/gof/vm.py:852: UserWarning: CVM does not support memory profile, using Stack VM.
  'CVM does not support memory profile, using Stack VM.')
```

**Comment by nouiz** [comment]
You can ignore the warning.

I'm not able to reproduce it with this dump. You didn't dumped the function that cause problems, but the lasagne object. It is the call to theano.function that must be changed to theano.function_dump().

If you don't know how to do that, can you give me the files that reproduce this?

**Comment by nouiz** [comment]
As not activity, I'll close.
