### ISSUE TITLE
Gradient throws AssertionError when using transposed sparse matrix inside scan

### ISSUE THREAD

**Issue by dcferreira** [Theano/Theano#3866]
Hi,

I'm getting a weird error when asking for the gradient of a product of a sparse transposed matrix by a dense matrix (with respect to the dense matrix).
As an example, take this starting piece of code (just setting some variables for later use):
```
import numpy as np
from scipy.sparse import *
from theano import sparse
import theano
import theano.tensor as T

X = eye(4, dtype='float32', format='csr')
A = np.identity(4, dtype='float32')

_X = sparse.csr_matrix(name='X', dtype='float32')
_A = theano.shared(value = A)
```
When I run the following, it works fine:
```
P = sparse.basic.dot(_X, _A)
PR, _ = theano.reduce(
    fn = lambda idx, prev : P.sum(),
    sequences = [T.arange(_X.shape[0])],
    outputs_info = T.as_tensor_variable(np.asarray(0, 'float32'))
)
gP = T.grad(PR, wrt=_A)
```
However, I get an AssertionError if I try to run the following piece of code:
```
P2 = sparse.basic.dot(_X.T, _A)
PR2, _ = theano.reduce(
    fn = lambda idx, prev : P2.sum(),
    sequences = [T.arange(_X.shape[0])],
    outputs_info = T.as_tensor_variable(np.asarray(0, 'float32'))
)
gP2 = T.grad(PR2, wrt=_A)
```

This last piece of code is exactly the same as the previous, except that `_X` is transposed (note that I picked squared matrices so the code could stay the same, but I get the same error with rectangular matrices).
The error I get comes from `assert _is_sparse_variable(x) and _is_sparse_variable(gz)`,  in `sparse/basic.py`.

I've reproduced this in two different machines (windows and linux), so it doesn't appear to be an installation error. I'm using the CPU, if it makes any difference. Is this expected behaviour?
I would be grateful for suggestions of workarounds, if anyone has them :)

**Comment by lamblin** [comment]
Sparse matrices are not as well-supported as dense CPU and GPU tensors, unfortunately.
In this case, I guess it comes down to the format of your matrices: `_X` is csr, so `dot(_X, _A)` is sparse in csr format as well (empty rows of `_X` will give empty rows in `P`). However, `_X.T` will be csc, and `dot(_X.T, _A)` will be dense in general (no empty lines in `_X.T`, and no empty columns in `_A`, so `P2` is dense).
I'm not sure what the right fix should be, though, and it is unlikely that a core developer will have time to look more into it. If you want to explore more, though, we would be happy to help.

**Comment by eduardo4jesus** [comment]
I am getting the same error, but with a different piece of code. But I am not using a explicit transpose.

```

import numpy as np
import scipy.sparse as sp

import theano
import theano.tensor as T
import theano.sparse as sparse


#   Test case variables
in_x_dense = np.array(
    [[2, 3, 2],
     [4, 8, 4],
     [3, 8, 9]], dtype='float32')

in_x = sp.csr_matrix(in_x_dense)

in_ul = np.array([1, 0, 1], dtype='float32')

in_w = np.array(
    [[2, 0],
     [4, 2],
     [4, 7]], dtype='float32')

# Testing Gradient
x = sparse.csr_matrix('x', dtype='float32')
ul = T.fvector('ul')
w = T.fmatrix('w')

o = sparse.dot(sparse.col_scale(x, ul), w)
fo = theano.function([x, ul, w], o)
print('fo\n', fo(in_x, in_ul, in_w))

do_dx = theano.grad(T.sum(o), x)
dfo_dx = theano.function([x, ul, w], do_dx)
print('dfo_dx\n', dfo_dx(in_x, in_ul, in_w))

```

Call stack:
```
Using gpu device 3: GeForce GTX TITAN X (CNMeM is disabled)
fo
 [[ 12.  14.]
 [ 24.  28.]
 [ 42.  63.]]
Traceback (most recent call last):
  File "theano-lab.py", line 75, in <module>
    do_dx = theano.grad(T.sum(o), x)
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 561, in grad
    grad_dict, wrt, cost_name)
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1324, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1324, in <listcomp>
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 973, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 973, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1113, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/sparse/basic.py", line 1553, in grad
    assert _is_sparse_variable(x) and _is_sparse_variable(gz)
AssertionError
``
