### ISSUE TITLE
Gradient implementation for Basic Arithmetic Sparse Operations

### ISSUE THREAD

**Issue by eduardo4jesus** [Theano/Theano#3941]
Hello everyone, 

Is there any chances of future extension regarding a Grad implementation for the following comparisons?

[**Basic Arithmetic**](http://www.deeplearning.net/software/theano/library/sparse/)
eq.
neq.
gt.
ge.
lt.
le.

**Comment by lamblin** [comment]
Extending the `sparse` module, or even fixing its existing problems, is not really in our list of priorities, unfortunately.
Also, arithmetic comparisons have a discrete output, and are locally constant, so they do not make any contribution to the gradient at all. An easy workaround would be to explicitly consider them constant during the backpropagation.

**Comment by eduardo4jesus** [comment]
Thank you for the feed back. That was fast!

I am start to explore sparsity for my MSc thesis project. The gradient for those operations seemed to be really useful for my very specific application. I will try to adapt some of it myself then. In case those operations' gradient work good on my project I would be really excited to contribute.

**Comment by lamblin** [comment]
On Wed, Jan 27, 2016, Eduardo de Jesus Coelho Reis wrote:
> I am start to explore sparsity for my MSc thesis project. The gradient for those operations seemed to be really useful for my very specific application. I will try to adapt some of it myself then. In case those operations' gradient work good on my project I would be really excited to contribute.
> 

It's great that you are eager to contribute :)

For these specific operations, though, the right implementation for the
gradients (at least, the one consistent with what we do everywhere else
in theano) would be to return 0. In fact, these operations are like the
"step" function: flat almost everywhere, with a discontinuity at one
point, so there is no "slope" or gradient anywhere. Therefore I'm not
really sure how useful that would be for you.

-- 
Pascal

**Comment by eduardo4jesus** [comment]
I'm still really fresh in Machine Learning. So, I am might be just confused about its utility.

But I guess it would be useful, for example, in implementing _Sparse Perceptron_. It has a regularization for feature selection like this:

**[ ( U > l ) * X ] * W**

Lets say the input **X** is a sparse vector, the SPerc contains an accumulator vector **U** having same size of **X**. Then, instead doing the parsing the usual **X * W** for the activation function, it operates the inner product only considering only the indices of **X** ( x_i ) with correspondent **U** ( u_i ) greater then a threshold **l**.

**Comment by lamblin** [comment]
Sure, computing gradients using that expression can be useful. But what would happen in that case usually, is that you would compute the gradient of the cost wrt `W` (and `X` if you are back-propagating to a previous layer), considering `(U > l)` to be constant. And you could not really backpropagate the cost through `U`.

**Comment by eduardo4jesus** [comment]
I imagined ** [ ( U > l ) * X ] ** as a function of **X**. So, lets say **X** = _[x0, x1, x2]_. And **U** has a configuration so that **( U > l )** = [0, 1, 0].

Then, for the cases where I have other previous layers, I am willing to back-propagate the cost wrt **X**  only through _x1_.

**Comment by eduardo4jesus** [comment]
I am happy to realize I was so mistaken! 

I thought that in order to compute the gradient wrt **x** of the function **y** defined as...
**t = gt(u, l)
y = x t**
...I would have to implement the grad for the **gt** function, even it not receiving **x** as input.

Then I started checking a tiny modification in order to compute the **dt_du**. I tried to get it returning zeros.This is the code snippet I used:

```
import scipy.sparse as sp
import theano
import theano.sparse as sparse

def my_grad(self, inputs, gout):
    (x, y) = inputs
    return sparse.basic.sp_zeros_like(x), sparse.basic.sp_zeros_like(y)

sparse.basic.__ComparisonOpSS.grad = my_grad

u = sparse.csr_matrix(name='u', dtype='float32')
l = sparse.csr_matrix(name='l', dtype='float32')

t = sparse.basic.gt(u, l)
ft = theano.function([u,l], t)

tdu = theano.grad(sparse.basic.sp_sum(t), u)
dftdu = theano.function([u, l], tdu)

in_u = sp.csr_matrix([[4,5,6]], dtype='float32')
in_l = sp.csr_matrix([[1,5,5]], dtype='float32')

print('ft = [U > L]')
print(ft(in_u, in_l).toarray())
print('dft/du')
print(dftdu(in_u, in_l).toarray())

```


 but when the execution reached the line:
`ft = theano.function([u,l], t)`

I was getting the following error:
>   File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1113, in access_te
rm_cache                                                                                               
    input_grads = node.op.grad(inputs, new_output_grads)                                               
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/sparse/basic.py", line 1819, in grad 
    return [x.zeros_like(dtype=theano.config.floatX)]                                                  

I had no success trying to get **dftdu** working.

It took a while until I realize that Theano's awesomeness doesn't need even to check **gt** to compute **dy_dx**, since **y** hasn't **x** as input. What makes a lot of sense.

Perfect, I definitely should had tried it before. But now, what I found funny is that, before throwing my code snippet out, I tried just for fun to compute **dy_du**. It indeed returned zeros as I adapted.

So, somehow it is able to use **my_grad** when computing **dy_du**, but when I directly compute **dt_du** it crashes.

I would appreciate any clue about why this happen :)

**Comment by nouiz** [comment]
When you talk about an error you have, show us the error. It contain the
answer most of the time (but it isn't always easy to understand, we try to
make it the most clear we can). This really help give back good answer.

I suppose that if you try to compute dt_du, you mean to execute
theano.grad(t, u). theano.grad need the cost to be a scalar, t isn,t a
scalar. You can use grad(t.sum(), u)

**Comment by eduardo4jesus** [comment]
> I suppose that if you try to compute dt_du, you mean to execute theano.grad(t, u). theano.grad need the cost to be a scalar, t isn,t a scalar. You can use grad(t.sum(), u)

Since `t` is sparse, I used `sparse.basic.sp_sum` in the gradient computation: 
`tdu = theano.grad(sparse.basic.sp_sum(t), u)`

Here is the complete callstack. :) 
```
Traceback (most recent call last):                                                                                
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/pudb/__init__.py", line 77, in runscript               
    dbg._runscript(mainpyfile)                                                                                    
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/pudb/debugger.py", line 419, in _runscript             
    self.run(statement, globals=globals_, locals=locals_)                                                         
  File "/usr/lib/python3.4/bdb.py", line 431, in run                                                              
    exec(cmd, globals, locals)                                                                                    
  File "<string>", line 1, in <module>                                                                            
  File "lab-theano-old.py", line 18, in <module>                                                                  
    tdu = theano.grad(sparse.basic.sp_sum(t), u)                                                                  
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 561, in grad                 
    grad_dict, wrt, cost_name)                                                                                    
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1324, in _populate_grad_dict 
    rval = [access_grad_cache(elem) for elem in wrt]                                                              
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1324, in <listcomp>          
    rval = [access_grad_cache(elem) for elem in wrt]                                                              
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1279, in access_grad_cache   
    term = access_term_cache(node)[idx]                                                                           
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 973, in access_term_cache    
    output_grads = [access_grad_cache(var) for var in node.outputs]                                               
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 973, in <listcomp>           
    output_grads = [access_grad_cache(var) for var in node.outputs]                                               
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1279, in access_grad_cache   
    term = access_term_cache(node)[idx]                                                                           
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/gradient.py", line 1113, in access_term_cache   
    input_grads = node.op.grad(inputs, new_output_grads)                                                          
  File "/data/eduardoj/MSc-env/lib/python3.4/site-packages/theano/sparse/basic.py", line 1819, in grad            
    return [x.zeros_like(dtype=theano.config.floatX)]                                                             
TypeError: zeros_like() got an unexpected keyword argument 'dtype'       
```

**Comment by lamblin** [comment]
OK, thanks.
The issue here is that [`SparseVariable.zeros_like()`](https://github.com/Theano/Theano/blob/5c31ea6beeadabda13a347762cc0b6b54a65b78b/theano/sparse/basic.py#L383) does not accept the `dtype` argument, like [`TensorVariable.zeros_like()`](https://github.com/Theano/Theano/blob/149d008d528277988867089cb607105e706910c4/theano/tensor/var.py#L677) does.
Do you think you could add it, and port the `dtype` logic from [`theano.tensor.basic.zeros_like`](https://github.com/Theano/Theano/blob/149d008d528277988867089cb607105e706910c4/theano/tensor/basic.py#L2260) to [`theano.sparse.basic.sp_zeros_like`](https://github.com/Theano/Theano/blob/5c31ea6beeadabda13a347762cc0b6b54a65b78b/theano/sparse/basic.py#L285)?
