### ISSUE TITLE
Theano not running in Debug Mode: StochasticOrder Error

### ISSUE THREAD

**Issue by prateekpg2455** [Theano/Theano#3981]
Hi,

I have been trying to run the code in debug mode as explained here: http://deeplearning.net/software/theano/tutorial/modes.html#using-debugmode

It is giving me this error:
```
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '57702' (I am process '28538')
ERROR (theano.gof.opt): SeqOptimizer apply <theano.compile.mode.AddDestroyHandler object at 0x31271d0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/mode.py", line 145, in apply
    fgraph.replace_validate(o, _output_guard(o),
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 525, in __call__
    raise ValueError('Cannot compute test value: input %i (%s) of Op %s missing default value' % (i, ins, node))
ValueError: Cannot compute test value: input 0 (Elemwise{mul,no_inplace}.0) of Op OutputGuard(Elemwise{mul,no_inplace}.0) missing default value

---------------------------------------------------------------------------
StochasticOrder                           Traceback (most recent call last)
<ipython-input-7-69c8908bb634> in <module>()
----> 1 f = theano.function([x], 10*x, mode ="DebugMode")

/usr/local/lib/python2.7/dist-packages/theano/compile/function.pyc in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    264                 allow_input_downcast=allow_input_downcast,
    265                 on_unused_input=on_unused_input,
--> 266                 profile=profile)
    267     # We need to add the flag check_aliased inputs if we have any mutable or
    268     # borrowed used defined inputs

/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.pyc in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    509     return orig_function(inputs, cloned_outputs, mode,
    510             accept_inplace=accept_inplace, name=name, profile=profile,
--> 511             on_unused_input=on_unused_input)
    512
    513

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input)
   1463                    accept_inplace=accept_inplace,
   1464                    profile=profile,
-> 1465                    on_unused_input=on_unused_input).create(
   1466                        defaults)
   1467

/usr/local/lib/python2.7/dist-packages/theano/compile/debugmode.pyc in function_maker(self, i, o, m, *args, **kwargs)
   2518         """
   2519         assert m is self
-> 2520         return _Maker(i, o, self.optimizer, self, *args, **kwargs)
   2521
   2522     def __init__(self,

/usr/local/lib/python2.7/dist-packages/theano/compile/debugmode.pyc in __init__(self, inputs, outputs, optimizer, mode, accept_inplace, function_builder, profile, on_unused_input)
   2277                         else:
   2278                             pass
-> 2279                     raise StochasticOrder(infolog.getvalue())
   2280                 else:
   2281                     if self.verbose:

StochasticOrder: WARNING: Optimization process is unstable...
  (HINT: Ops that the nodes point to must compare equal)
(event index)  (one event trace)  (other event trace)
-----------------------------------------------------
trailing event in optimization 1 : 18
    {'node': OutputGuard(Elemwise{mul,no_inplace}.0), 'kind': 'import', 'reason': 'output_guard', 'idx': None, 'op': <theano.compile.ops.OutputGuard object at 0x31014d0>}
trailing event in optimization 1 : 19
    change output_guard output 0
trailing event in optimization 1 : 20
    change ('Revert', 'output_guard') output 0
trailing event in optimization 1 : 21
    {'node': OutputGuard(Elemwise{mul,no_inplace}.0), 'kind': 'prune', 'reason': ('Revert', 'output_guard'), 'idx': None, 'op': <theano.compile.ops.OutputGuard object at 0x31014d0>}

```

What is going wrong?

**Comment by nouiz** [comment]
Can you make a function_dump of the function you are compiling? This will
help debug this:

http://deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

There isn't very bad, just that if you compile the same Theano function
many times, you could end up with optimized function that are equivalent,
but not exactly the same. So it make the exact reproducibility harder.

I don't know when we can look at this. But if you just want DebugMode to
continue passed this, you can do so with this Theano flags:
DebugMode.patience=1

**Comment by prateekpg2455** [comment]
So I created the fucntion_dump of the function I was trying to compile. PFA. 
[debug.pkl.gz](https://github.com/Theano/Theano/files/116469/debug.pkl.gz)
