### ISSUE TITLE
Assembly level instructions for debugging are not helping

### ISSUE THREAD

**Issue by prateekpg2455** [Theano/Theano#4001]
I am running PyMC3 examples which is highly dependent on Theano. Unfortunately, there are some compiling issues and the output it is generating are assembly level. I am not familiar with assembly level language so i am posting the error log here. 

It will be really helpful if you can tell me what is going wrong in it. I have tried reinstalling Numpy, Scipy and Theano. Numpy and Scipy are properly linked to OpenBLAS libraries. 

I am running this example :-  https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/normal.py

```
INFO (theano.gof.compilelock): Waiting for existing lock by process '52735' (I am process '53368')
INFO (theano.gof.compilelock): To manually release the lock, delete /home/pgupta/.theano/compiledir_Linux-3.2--virtual-x86_64-with-Ubuntu-12.04-precise-x86_64-2.7.3-64/lock_dir
===============================
00001	#include <Python.h>
00002	#include <iostream>
00003	#include <math.h>
00004	#include <numpy/arrayobject.h>
00005	#include <numpy/arrayscalars.h>
00006	#include <vector>
00007	#include <algorithm>
00008	//////////////////////
00009	////  Support Code
00010	//////////////////////
00011
00012
00013	    namespace {
00014	    struct __struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163 {
00015	        PyObject* __ERROR;
00016
00017	        PyObject* storage_V3;
00018	PyObject* storage_V5;
00019	PyObject* storage_V1;
00020
00021
00022	        __struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163() {}
00023	        ~__struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163(void) {
00024	            cleanup();
00025	        }
00026
00027	        int init(PyObject* __ERROR, PyObject* storage_V3, PyObject* storage_V5, PyObject* storage_V1) {
00028	            Py_XINCREF(storage_V3);
00029	Py_XINCREF(storage_V5);
00030	Py_XINCREF(storage_V1);
00031	            this->storage_V3 = storage_V3;
00032	this->storage_V5 = storage_V5;
00033	this->storage_V1 = storage_V1;
00034
00035
00036
00037
00038
00039	            this->__ERROR = __ERROR;
00040	            return 0;
00041	        }
00042	        void cleanup(void) {
00043	            __label_1:
00044
00045	double __DUMMY_1;
00046	__label_3:
00047
00048	double __DUMMY_3;
00049	__label_5:
00050
00051	double __DUMMY_5;
00052	__label_8:
00053
00054	double __DUMMY_8;
00055
00056	            Py_XDECREF(this->storage_V3);
00057	Py_XDECREF(this->storage_V5);
00058	Py_XDECREF(this->storage_V1);
00059	        }
00060	        int run(void) {
00061	            int __failure = 0;
00062
00063	    PyObject* py_V1;
00064
00065	        PyArrayObject* V1;
00066
00067	            typedef npy_float64 dtype_V1;
00068
00069	    PyObject* py_V3;
00070
00071	        PyArrayObject* V3;
00072
00073	            typedef npy_float64 dtype_V3;
00074
00075	    PyObject* py_V5;
00076
00077	        PyArrayObject* V5;
00078
00079	            typedef npy_float64 dtype_V5;
00080
00081	{
00082
00083	    py_V1 = PyList_GET_ITEM(storage_V1, 0);
00084	    {Py_XINCREF(py_V1);}
00085
00086	        if (py_V1 == Py_None)
00087	        {
00088
00089	        V1 = NULL;
00090
00091	        }
00092	        else
00093	        {
00094
00095	            V1 = NULL;
00096	            if (py_V1 == Py_None) {
00097	                // We can either fail here or set V1 to NULL and rely on Ops
00098	                // using tensors to handle the NULL case, but if they fail to do so
00099	                // they'll end up with nasty segfaults, so this is public service.
00100	                PyErr_SetString(PyExc_ValueError, "expected an ndarray, not None");
00101	                {
00102	        __failure = 2;
00103	        if (!PyErr_Occurred()) {
00104	            PyErr_SetString(PyExc_RuntimeError,
00105	                "Unexpected error in an Op's C code. "
00106	                "No Python exception was set.");
00107	            }
00108	        goto __label_2;}
00109	            }
00110	            if (!PyArray_Check(py_V1)) {
00111	                PyErr_SetString(PyExc_ValueError, "expected an ndarray");
00112	                {
00113	        __failure = 2;
00114	        if (!PyErr_Occurred()) {
00115	            PyErr_SetString(PyExc_RuntimeError,
00116	                "Unexpected error in an Op's C code. "
00117	                "No Python exception was set.");
00118	            }
00119	        goto __label_2;}
00120	            }
00121	            // We expect NPY_FLOAT64
00122	            if (!PyArray_ISALIGNED((PyArrayObject*) py_V1)) {
00123	                PyArrayObject * tmp = (PyArrayObject*) py_V1;
00124	                PyErr_Format(PyExc_NotImplementedError,
00125	                             "expected an aligned array of type %ld "
00126	                             "(NPY_FLOAT64), got non-aligned array of type %ld"
00127	                             " with %ld dimensions, with 3 last dims "
00128	                             "%ld, %ld, %ld"
00129	                             " and 3 last strides %ld %ld, %ld.",
00130	                             (long int) NPY_FLOAT64,
00131	                             (long int) PyArray_TYPE((PyArrayObject*) py_V1),
00132	                             (long int) PyArray_NDIM(tmp),
00133	                             (long int) PyArray_NDIM(tmp) >= 3 ?
00134	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-3] : -1,
00135	                             (long int) PyArray_NDIM(tmp) >= 2 ?
00136	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-2] : -1,
00137	                             (long int) PyArray_NDIM(tmp) >= 1 ?
00138	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-1] : -1,
00139	                             (long int) PyArray_NDIM(tmp) >= 3 ?
00140	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-3] : -1,
00141	                             (long int) PyArray_NDIM(tmp) >= 2 ?
00142	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-2] : -1,
00143	                             (long int) PyArray_NDIM(tmp) >= 1 ?
00144	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-1] : -1
00145	            );
00146	                {
00147	        __failure = 2;
00148	        if (!PyErr_Occurred()) {
00149	            PyErr_SetString(PyExc_RuntimeError,
00150	                "Unexpected error in an Op's C code. "
00151	                "No Python exception was set.");
00152	            }
00153	        goto __label_2;}
00154	            }
00155	            // This is a TypeError to be consistent with DEBUG_MODE
00156	            // Note: DEBUG_MODE also tells the name of the container
00157	            if (PyArray_TYPE((PyArrayObject*) py_V1) != NPY_FLOAT64) {
00158	                PyErr_Format(PyExc_TypeError,
00159	                             "expected type_num %d (NPY_FLOAT64) got %d",
00160	                             NPY_FLOAT64, PyArray_TYPE((PyArrayObject*) py_V1));
00161	                {
00162	        __failure = 2;
00163	        if (!PyErr_Occurred()) {
00164	            PyErr_SetString(PyExc_RuntimeError,
00165	                "Unexpected error in an Op's C code. "
00166	                "No Python exception was set.");
00167	            }
00168	        goto __label_2;}
00169	            }
00170
00171	        V1 = (PyArrayObject*)(py_V1);
00172	        Py_XINCREF(V1);
00173
00174	        }
00175
00176	{
00177
00178	    py_V3 = PyList_GET_ITEM(storage_V3, 0);
00179	    {Py_XINCREF(py_V3);}
00180
00181	            V3 = NULL;
00182	            if (py_V3 == Py_None) {
00183	                // We can either fail here or set V3 to NULL and rely on Ops
00184	                // using tensors to handle the NULL case, but if they fail to do so
00185	                // they'll end up with nasty segfaults, so this is public service.
00186	                PyErr_SetString(PyExc_ValueError, "expected an ndarray, not None");
00187	                {
00188	        __failure = 4;
00189	        if (!PyErr_Occurred()) {
00190	            PyErr_SetString(PyExc_RuntimeError,
00191	                "Unexpected error in an Op's C code. "
00192	                "No Python exception was set.");
00193	            }
00194	        goto __label_4;}
00195	            }
00196	            if (!PyArray_Check(py_V3)) {
00197	                PyErr_SetString(PyExc_ValueError, "expected an ndarray");
00198	                {
00199	        __failure = 4;
00200	        if (!PyErr_Occurred()) {
00201	            PyErr_SetString(PyExc_RuntimeError,
00202	                "Unexpected error in an Op's C code. "
00203	                "No Python exception was set.");
00204	            }
00205	        goto __label_4;}
00206	            }
00207	            // We expect NPY_FLOAT64
00208	            if (!PyArray_ISALIGNED((PyArrayObject*) py_V3)) {
00209	                PyArrayObject * tmp = (PyArrayObject*) py_V3;
00210	                PyErr_Format(PyExc_NotImplementedError,
00211	                             "expected an aligned array of type %ld "
00212	                             "(NPY_FLOAT64), got non-aligned array of type %ld"
00213	                             " with %ld dimensions, with 3 last dims "
00214	                             "%ld, %ld, %ld"
00215	                             " and 3 last strides %ld %ld, %ld.",
00216	                             (long int) NPY_FLOAT64,
00217	                             (long int) PyArray_TYPE((PyArrayObject*) py_V3),
00218	                             (long int) PyArray_NDIM(tmp),
00219	                             (long int) PyArray_NDIM(tmp) >= 3 ?
00220	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-3] : -1,
00221	                             (long int) PyArray_NDIM(tmp) >= 2 ?
00222	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-2] : -1,
00223	                             (long int) PyArray_NDIM(tmp) >= 1 ?
00224	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-1] : -1,
00225	                             (long int) PyArray_NDIM(tmp) >= 3 ?
00226	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-3] : -1,
00227	                             (long int) PyArray_NDIM(tmp) >= 2 ?
00228	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-2] : -1,
00229	                             (long int) PyArray_NDIM(tmp) >= 1 ?
00230	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-1] : -1
00231	            );
00232	                {
00233	        __failure = 4;
00234	        if (!PyErr_Occurred()) {
00235	            PyErr_SetString(PyExc_RuntimeError,
00236	                "Unexpected error in an Op's C code. "
00237	                "No Python exception was set.");
00238	            }
00239	        goto __label_4;}
00240	            }
00241	            // This is a TypeError to be consistent with DEBUG_MODE
00242	            // Note: DEBUG_MODE also tells the name of the container
00243	            if (PyArray_TYPE((PyArrayObject*) py_V3) != NPY_FLOAT64) {
00244	                PyErr_Format(PyExc_TypeError,
00245	                             "expected type_num %d (NPY_FLOAT64) got %d",
00246	                             NPY_FLOAT64, PyArray_TYPE((PyArrayObject*) py_V3));
00247	                {
00248	        __failure = 4;
00249	        if (!PyErr_Occurred()) {
00250	            PyErr_SetString(PyExc_RuntimeError,
00251	                "Unexpected error in an Op's C code. "
00252	                "No Python exception was set.");
00253	            }
00254	        goto __label_4;}
00255	            }
00256
00257	        V3 = (PyArrayObject*)(py_V3);
00258	        Py_XINCREF(V3);
00259
00260	{
00261
00262	    py_V5 = PyList_GET_ITEM(storage_V5, 0);
00263	    {Py_XINCREF(py_V5);}
00264
00265	            V5 = NULL;
00266	            if (py_V5 == Py_None) {
00267	                // We can either fail here or set V5 to NULL and rely on Ops
00268	                // using tensors to handle the NULL case, but if they fail to do so
00269	                // they'll end up with nasty segfaults, so this is public service.
00270	                PyErr_SetString(PyExc_ValueError, "expected an ndarray, not None");
00271	                {
00272	        __failure = 6;
00273	        if (!PyErr_Occurred()) {
00274	            PyErr_SetString(PyExc_RuntimeError,
00275	                "Unexpected error in an Op's C code. "
00276	                "No Python exception was set.");
00277	            }
00278	        goto __label_6;}
00279	            }
00280	            if (!PyArray_Check(py_V5)) {
00281	                PyErr_SetString(PyExc_ValueError, "expected an ndarray");
00282	                {
00283	        __failure = 6;
00284	        if (!PyErr_Occurred()) {
00285	            PyErr_SetString(PyExc_RuntimeError,
00286	                "Unexpected error in an Op's C code. "
00287	                "No Python exception was set.");
00288	            }
00289	        goto __label_6;}
00290	            }
00291	            // We expect NPY_FLOAT64
00292	            if (!PyArray_ISALIGNED((PyArrayObject*) py_V5)) {
00293	                PyArrayObject * tmp = (PyArrayObject*) py_V5;
00294	                PyErr_Format(PyExc_NotImplementedError,
00295	                             "expected an aligned array of type %ld "
00296	                             "(NPY_FLOAT64), got non-aligned array of type %ld"
00297	                             " with %ld dimensions, with 3 last dims "
00298	                             "%ld, %ld, %ld"
00299	                             " and 3 last strides %ld %ld, %ld.",
00300	                             (long int) NPY_FLOAT64,
00301	                             (long int) PyArray_TYPE((PyArrayObject*) py_V5),
00302	                             (long int) PyArray_NDIM(tmp),
00303	                             (long int) PyArray_NDIM(tmp) >= 3 ?
00304	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-3] : -1,
00305	                             (long int) PyArray_NDIM(tmp) >= 2 ?
00306	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-2] : -1,
00307	                             (long int) PyArray_NDIM(tmp) >= 1 ?
00308	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-1] : -1,
00309	                             (long int) PyArray_NDIM(tmp) >= 3 ?
00310	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-3] : -1,
00311	                             (long int) PyArray_NDIM(tmp) >= 2 ?
00312	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-2] : -1,
00313	                             (long int) PyArray_NDIM(tmp) >= 1 ?
00314	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-1] : -1
00315	            );
00316	                {
00317	        __failure = 6;
00318	        if (!PyErr_Occurred()) {
00319	            PyErr_SetString(PyExc_RuntimeError,
00320	                "Unexpected error in an Op's C code. "
00321	                "No Python exception was set.");
00322	            }
00323	        goto __label_6;}
00324	            }
00325	            // This is a TypeError to be consistent with DEBUG_MODE
00326	            // Note: DEBUG_MODE also tells the name of the container
00327	            if (PyArray_TYPE((PyArrayObject*) py_V5) != NPY_FLOAT64) {
00328	                PyErr_Format(PyExc_TypeError,
00329	                             "expected type_num %d (NPY_FLOAT64) got %d",
00330	                             NPY_FLOAT64, PyArray_TYPE((PyArrayObject*) py_V5));
00331	                {
00332	        __failure = 6;
00333	        if (!PyErr_Occurred()) {
00334	            PyErr_SetString(PyExc_RuntimeError,
00335	                "Unexpected error in an Op's C code. "
00336	                "No Python exception was set.");
00337	            }
00338	        goto __label_6;}
00339	            }
00340
00341	        V5 = (PyArrayObject*)(py_V5);
00342	        Py_XINCREF(V5);
00343
00344	{
00345	// Op class Elemwise
00346
00347	        npy_float64* V3_iter;
00348
00349	                int V3_jumpx_0;
00350
00351	        npy_float64* V5_iter;
00352
00353	                npy_intp V5_n0;
00354	                ssize_t V5_stride0;
00355	                int V5_jump0_0;
00356
00357
00358	                V3_jumpx_0 = -(0);
00359	                //printf("V3_jumpx_0 is:");
00360	                //std::cout << V3_jumpx_0 << std::endl;
00361
00362	            if (PyArray_NDIM(V5) < 1) {
00363	                PyErr_SetString(PyExc_ValueError, "Not enough dimensions on input.");
00364	                {
00365	        __failure = 7;
00366	        if (!PyErr_Occurred()) {
00367	            PyErr_SetString(PyExc_RuntimeError,
00368	                "Unexpected error in an Op's C code. "
00369	                "No Python exception was set.");
00370	            }
00371	        goto __label_7;}
00372	            }
00373
00374	                V5_n0 = PyArray_DIMS(V5)[0];
00375	                V5_stride0 = PyArray_STRIDES(V5)[0] / sizeof(npy_float64);
00376	                V5_jump0_0 = (V5_stride0) - (0);
00377	                //printf("V5_jump0_0 is:");
00378	                //std::cout << V5_jump0_0 << std::endl;
00379
00380
00381	        npy_float64* V1_iter;
00382
00383	                npy_intp V1_n0;
00384	                ssize_t V1_stride0;
00385	                int V1_jump0_0;
00386
00387	    {
00388	        npy_intp dims[1];
00389	        //npy_intp* dims = (npy_intp*)malloc(1 * sizeof(npy_intp));
00390	        dims[0] = V5_n0;
00391
00392	        if (!V1) {
00393	            V1 = (PyArrayObject*)PyArray_EMPTY(1, dims,
00394	                                                    NPY_FLOAT64,
00395	                                                    PyArray_ISFORTRAN(V5));
00396	        }
00397	        else {
00398	            PyArray_Dims new_dims;
00399	            new_dims.len = 1;
00400	            new_dims.ptr = dims;
00401	            PyObject* success = PyArray_Resize(V1, &new_dims, 0, NPY_CORDER);
00402	            if (!success) {
00403	                // If we can't resize the ndarray we have we can allocate a new one.
00404	                PyErr_Clear();
00405	                Py_XDECREF(V1);
00406	                V1 = (PyArrayObject*)PyArray_EMPTY(1, dims, NPY_FLOAT64, 0);
00407	            }
00408	        }
00409	        if (!V1) {
00410	            {
00411	        __failure = 7;
00412	        if (!PyErr_Occurred()) {
00413	            PyErr_SetString(PyExc_RuntimeError,
00414	                "Unexpected error in an Op's C code. "
00415	                "No Python exception was set.");
00416	            }
00417	        goto __label_7;}
00418	        }
00419	    }
00420
00421	            if (PyArray_NDIM(V1) < 1) {
00422	                PyErr_SetString(PyExc_ValueError, "Not enough dimensions on input.");
00423	                {
00424	        __failure = 7;
00425	        if (!PyErr_Occurred()) {
00426	            PyErr_SetString(PyExc_RuntimeError,
00427	                "Unexpected error in an Op's C code. "
00428	                "No Python exception was set.");
00429	            }
00430	        goto __label_7;}
00431	            }
00432
00433	                V1_n0 = PyArray_DIMS(V1)[0];
00434	                V1_stride0 = PyArray_STRIDES(V1)[0] / sizeof(npy_float64);
00435	                V1_jump0_0 = (V1_stride0) - (0);
00436	                //printf("V1_jump0_0 is:");
00437	                //std::cout << V1_jump0_0 << std::endl;
00438
00439
00440	            if((PyArray_ISCONTIGUOUS(V5) && PyArray_ISCONTIGUOUS(V1)) || (PyArray_ISFORTRAN(V5) && PyArray_ISFORTRAN(V1))){
00441
00442	                    // All output have the same size
00443	                    npy_intp n = PyArray_SIZE(V1);
00444
00445	            dtype_V3& V3_i = ((dtype_V3*) PyArray_DATA(V3))[0];
00446
00447	            dtype_V5 * V5_ptr = (dtype_V5*) PyArray_DATA(V5);
00448
00449	            dtype_V1 * V1_ptr = (dtype_V1*) PyArray_DATA(V1);
00450
00451	                    for(int i=0; i<n; i++){
00452
00453	            dtype_V5& V5_i = V5_ptr[i];
00454
00455	            dtype_V1& V1_i = V1_ptr[i];
00456
00457	                        {
00458	npy_float64 V7_tmp1;
00459	V7_tmp1 = V5_i * V5_i;
00460	npy_float64 V7_tmp2;
00461	V7_tmp2 = -V7_tmp1;
00462	V1_i = V3_i + V7_tmp2;
00463	}
00464	;
00465	                    }
00466
00467	            }else{
00468	                {
00469	        V3_iter = (npy_float64*)(PyArray_DATA(V3));
00470	V5_iter = (npy_float64*)(PyArray_DATA(V5));
00471	V1_iter = (npy_float64*)(PyArray_DATA(V1));
00472
00473	        for (int ITER_0 = 0; ITER_0<V1_n0; ITER_0++) {
00474	            npy_float64 &V3_i = * ( V3_iter + ITER_0 * V3_jumpx_0 );
00475	npy_float64 &V5_i = * ( V5_iter + ITER_0 * V5_jump0_0 );
00476	npy_float64 &V1_i = * ( V1_iter + ITER_0 * V1_jump0_0 );
00477
00478
00479	        {
00480
00481	            {
00482	npy_float64 V7_tmp1;
00483	V7_tmp1 = V5_i * V5_i;
00484	npy_float64 V7_tmp2;
00485	V7_tmp2 = -V7_tmp1;
00486	V1_i = V3_i + V7_tmp2;
00487	}
00488
00489
00490	        }
00491
00492	        }
00493	        }
00494	            }
00495	            __label_7:
00496
00497	double __DUMMY_7;
00498
00499	}
00500	__label_6:
00501
00502	        if (V5) {
00503	            Py_XDECREF(V5);
00504	        }
00505
00506	    {Py_XDECREF(py_V5);}
00507
00508	double __DUMMY_6;
00509
00510	}
00511	__label_4:
00512
00513	        if (V3) {
00514	            Py_XDECREF(V3);
00515	        }
00516
00517	    {Py_XDECREF(py_V3);}
00518
00519	double __DUMMY_4;
00520
00521	}
00522	__label_2:
00523
00524	    if (!__failure) {
00525
00526	        {Py_XDECREF(py_V1);}
00527	        if (!V1) {
00528	            Py_INCREF(Py_None);
00529	            py_V1 = Py_None;
00530	        }
00531	        else if ((void*)py_V1 != (void*)V1) {
00532	            py_V1 = (PyObject*)V1;
00533	        }
00534
00535	        {Py_XINCREF(py_V1);}
00536
00537	        if (V1 && !PyArray_ISALIGNED((PyArrayObject*) py_V1)) {
00538	            PyErr_Format(PyExc_NotImplementedError,
00539	                         "c_sync: expected an aligned array, got non-aligned array of type %ld"
00540	                         " with %ld dimensions, with 3 last dims "
00541	                         "%ld, %ld, %ld"
00542	                         " and 3 last strides %ld %ld, %ld.",
00543	                         (long int) PyArray_TYPE((PyArrayObject*) py_V1),
00544	                         (long int) PyArray_NDIM(V1),
00545	                         (long int) PyArray_NDIM(V1) >= 3 ?
00546	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-3] : -1,
00547	                         (long int) PyArray_NDIM(V1) >= 2 ?
00548	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-2] : -1,
00549	                         (long int) PyArray_NDIM(V1) >= 1 ?
00550	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-1] : -1,
00551	                         (long int) PyArray_NDIM(V1) >= 3 ?
00552	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-3] : -1,
00553	                         (long int) PyArray_NDIM(V1) >= 2 ?
00554	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-2] : -1,
00555	                         (long int) PyArray_NDIM(V1) >= 1 ?
00556	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-1] : -1
00557	        );
00558	            {
00559	        __failure = 2;
00560	        if (!PyErr_Occurred()) {
00561	            PyErr_SetString(PyExc_RuntimeError,
00562	                "Unexpected error in an Op's C code. "
00563	                "No Python exception was set.");
00564	            }
00565	        goto __label_2;}
00566	        }
00567
00568	      PyObject* old = PyList_GET_ITEM(storage_V1, 0);
00569	      {Py_XINCREF(py_V1);}
00570	      PyList_SET_ITEM(storage_V1, 0, py_V1);
00571	      {Py_XDECREF(old);}
00572	    }
00573
00574	        if (V1) {
00575	            Py_XDECREF(V1);
00576	        }
00577
00578	    {Py_XDECREF(py_V1);}
00579
00580	double __DUMMY_2;
00581
00582	}
00583
00584
00585	        if (__failure) {
00586	            // When there is a failure, this code puts the exception
00587	            // in __ERROR.
00588	            PyObject* err_type = NULL;
00589	            PyObject* err_msg = NULL;
00590	            PyObject* err_traceback = NULL;
00591	            PyErr_Fetch(&err_type, &err_msg, &err_traceback);
00592	            if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}
00593	            if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}
00594	            if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}
00595	            PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);
00596	            PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);
00597	            PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);
00598	            PyList_SET_ITEM(__ERROR, 0, err_type);
00599	            PyList_SET_ITEM(__ERROR, 1, err_msg);
00600	            PyList_SET_ITEM(__ERROR, 2, err_traceback);
00601	            {Py_XDECREF(old_err_type);}
00602	            {Py_XDECREF(old_err_msg);}
00603	            {Py_XDECREF(old_err_traceback);}
00604	        }
00605	        // The failure code is returned to index what code block failed.
00606	        return __failure;
00607
00608	        }
00609	    };
00610	    }
00611
00612
00613	        static int __struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163_executor(__struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163* self) {
00614	            return self->run();
00615	        }
00616
00617	        static void __struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163_destructor(void* executor, void* self) {
00618	            delete ((__struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163*)self);
00619	        }
00620
00621	//////////////////////
00622	////  Functions
00623	//////////////////////
00624	static PyObject * instantiate(PyObject * self, PyObject *argtuple) {
00625	  assert(PyTuple_Check(argtuple));
00626	  if (4 != PyTuple_Size(argtuple)){
00627	     PyErr_Format(PyExc_TypeError, "Wrong number of arguments, expected 4, got %i", (int)PyTuple_Size(argtuple));
00628	     return NULL;
00629	  }
00630	  __struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163* struct_ptr = new __struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163();
00631	  if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1),PyTuple_GET_ITEM(argtuple, 2),PyTuple_GET_ITEM(argtuple, 3) ) != 0) {
00632	    delete struct_ptr;
00633	    return NULL;
00634	  }
00635	  PyObject* thunk = PyCObject_FromVoidPtrAndDesc((void*)(&__struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163_executor), struct_ptr, __struct_compiled_op_d56db4aca7d1d5b51427fe9c71787163_destructor);
00636	  return thunk; }
00637
00638	//////////////////////
00639	////  Module init
00640	//////////////////////
00641	static PyMethodDef MyMethods[] = {
00642		{"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
00643		{NULL, NULL, 0, NULL}
00644	};
00645	PyMODINIT_FUNC initd56db4aca7d1d5b51427fe9c71787163(void){
00646	   import_array();
00647	   (void) Py_InitModule("d56db4aca7d1d5b51427fe9c71787163", MyMethods);
00648	}
00649
===============================
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=corei7-avx -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mno-tbm -mavx -msse4.2 -msse4.1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=25600 -mtune=generic -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy-1.12.0.dev0+1436ec3-py2.7-linux-x86_64.egg/numpy/core/include -I/usr/include/python2.7 -o /home/pgupta/.theano/compiledir_Linux-3.2--virtual-x86_64-with-Ubuntu-12.04-precise-x86_64-2.7.3-64/tmps6ZX_o/d56db4aca7d1d5b51427fe9c71787163.so /home/pgupta/.theano/compiledir_Linux-3.2--virtual-x86_64-with-Ubuntu-12.04-precise-x86_64-2.7.3-64/tmps6ZX_o/mod.cpp -L/usr/lib -lpython2.7
/tmp/ccmvN69j.s: Assembler messages:
/tmp/ccmvN69j.s:1565: Error: no such instruction: `vfnmadd312sd (%rsi),%xmm0,%xmm0'
/tmp/ccmvN69j.s:1742: Error: no such instruction: `vfnmadd312sd (%rcx),%xmm0,%xmm0'

Traceback (most recent call last):
  File "normal.py", line 16, in <module>
    start = find_MAP()
  File "/usr/local/lib/python2.7/dist-packages/pymc3/tuning/starting.py", line 69, in find_MAP
    logp = bij.mapf(model.fastlogp)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/model.py", line 145, in fastlogp
    return self.model.fastfn(self.logpt)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/model.py", line 311, in fastfn
    f = self.makefn(outs, mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/model.py", line 283, in makefn
    mode=mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 1002, in make_thunk
    compute_map, no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1076, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1354, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2010, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Elemwise{Composite{(i0 + (-sqr(i1)))}}(TensorConstant{(1,) of -1..3787706641}, x), '\n', "Compilation failed (return status=1): /tmp/ccmvN69j.s: Assembler messages:. /tmp/ccmvN69j.s:1565: Error: no such instruction: `vfnmadd312sd (%rsi),%xmm0,%xmm0'. /tmp/ccmvN69j.s:1742: Error: no such instruction: `vfnmadd312sd (%rcx),%xmm0,%xmm0'. ", '[Elemwise{Composite{(i0 + (-sqr(i1)))}}(TensorConstant{(1,) of -1..3787706641}, x)]')
```

**Comment by nouiz** [comment]
This isn't a bug in Theano, but a bug in g++ or the linker that is triggered by Theano. Theano don't generate assembly. The code you see is C code. The error have assembly code, but it come from the g++ or the linker.

There is already an issue about this(https://github.com/Theano/Theano/issues/3780). So I'll close this issue. You can work around this by using tring those Theano flags:

A quick work around is to use a Theano flag like:

    gcc.cxxflags='-march=core2"
    gcc.cxxflags='-march=corei7"
    gcc.cxxflags='-march=corei7-avx"

Take the last one that work. If it don't work, you can reply here.

**Comment by prateekpg2455** [comment]
Atleast it changed the error. Thanks!

**Comment by prateekpg2455** [comment]
By the way it is very unstable. I ran it again with same flags and gave me the above error. Bad thing is that error instructions are not helping.
