### ISSUE TITLE
argmax error when unpickling and running theano models in parallel

### ISSUE THREAD

**Issue by carterk** [Theano/Theano#4023]
Here's what I'm doing:
- create a model
- broadcast pickled model to multiple machines with Spark
- unpickle model for each core on each machine
- train model

```
Traceback (most recent call last):
  File "/var/lib/hadoop-hdfs/data01/spark/python/lib/pyspark.zip/pyspark/worker.py", line 98, in main
    command = pickleSer._read_with_length(infile)
  File "/var/lib/hadoop-hdfs/data01/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 164, in _read_with_length
    return self.loads(obj)
  File "/var/lib/hadoop-hdfs/data01/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 422, in loads
    return pickle.loads(obj)
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 1018, in _constructor_Function
    f = maker.create(input_storage, trustme=True)
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 1636, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/lib/python2.7/site-packages/theano/gof/vm.py", line 1037, in make_all
    no_recycling))
  File "/usr/lib/python2.7/site-packages/theano/gof/op.py", line 965, in make_thunk
    no_recycling)
  File "/usr/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/lib/python2.7/site-packages/theano/gof/cc.py", line 1207, in make_thunk
    keep_lock=keep_lock)
  File "/usr/lib/python2.7/site-packages/theano/gof/cc.py", line 1152, in __compile__
    keep_lock=keep_lock)
  File "/usr/lib/python2.7/site-packages/theano/gof/cc.py", line 1602, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1137, in module_from_key
    src_code = lnk.get_src_code()
  File "/usr/lib/python2.7/site-packages/theano/gof/cc.py", line 1486, in get_src_code
    mod = self.get_dynamic_module()
  File "/usr/lib/python2.7/site-packages/theano/gof/cc.py", line 1530, in get_dynamic_module
    self.code_gen()
  File "/usr/lib/python2.7/site-packages/theano/gof/cc.py", line 832, in code_gen
    behavior = op.c_code(node, name, isyms, osyms, sub)
  File "/usr/lib/python2.7/site-packages/theano/tensor/basic.py", line 1380, in c_code
    assert node.inputs[1].ndim == 1
AssertionError: (AssertionError('The following error happened while compiling the node', MaxAndArgmax(Softmax.0, TensorConstant{1}), '\n'), <function _constructor_Function at 0x68c0d70>, (<theano.compile.function_module.FunctionMaker object at 0x5cf1710>, [<None>, <None>, <array([[ 0.03729132, -0.11013737, -0.15326254, ...,  0.03427935,
```

The only issue is a call to `argmax`. Everything else works fine (the model runs fine when the call to `argmax` is commented out).

I'm running this version of Theano: `0.8.0.dev0.dev-unknown-git`
With this version of Lasagne: `0.2.dev1`

Could this be related to https://github.com/Theano/Theano/issues/3972?

**Comment by nouiz** [comment]
Can you go in pdb and print node.inputs on the line that cause error? Or
you can modify this line:


    assert node.inputs[1].ndim == 1

to

    assert node.inputs[1].ndim == 1, node.inputs
