### ISSUE TITLE
Can anyone help on the following error msg?

### ISSUE THREAD

**Issue by shampool** [Theano/Theano#4031]
Thanks,

  File "c:\downloads\theano\theano\tensor\type.py", line 194, in filter
    " dimension.", data.shape, self.broadcastable)

TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn}(Elemwise{maximum,no_inplace}.0, InplaceDimShuffle{0,x,1,2,3}.0, Alloc.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Elemwise{Add}[(0, 0)].0, Subtensor{int64:int64:int64}.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, <TensorType(float32, matrix)>, <TensorType(float32, vector)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, ARange{dtype='int64'}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0), '\n', 'The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn}(Shape_i{0}.0, InplaceDimShuffle{0,2,1}.0, Elemwise{neq,no_inplace}.0, Alloc.0, Alloc.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{::int64}.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Elemwise{Composite{minimum(minimum(i0, i1), i2)}}.0, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0), '\n', 'Non-unit value on shape on a broadcastable dimension.', (0L, 0L, 0L), (False, False, True), 'Container name "None"')

**Comment by nouiz** [comment]
We need the full error message.

**Comment by shampool** [comment]
@nouiz   Thanks for your reply, here is the complete error msg.  
PS: I got this error on windows.  But on ubuntu, updating the theano version to 0.8 fixes the problem.

\downloads\theano\theano\tensor\signal\downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Traceback (most recent call last):

  File "<ipython-input-1-a61150b21f86>", line 1, in <module>
    runfile('D:/Workstation/KingDrive/WorkStation/MICCAI_RNNseg/Code_python/utils/lab/multiDimInputRNN.py', wdir='D:/Workstation/KingDrive/WorkStation/MICCAI_RNNseg/Code_python/utils/lab')

  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/Workstation/KingDrive/WorkStation/MICCAI_RNNseg/Code_python/utils/lab/multiDimInputRNN.py", line 192, in <module>
    strumodel = buildmodel(patchsize, patchsize,img_channels, labelpatchsize*labelpatchsize)

  File "D:/Workstation/KingDrive/WorkStation/MICCAI_RNNseg/Code_python/utils/lab/multiDimInputRNN.py", line 76, in buildmodel
    model.compile(loss={'output_mask': 'awmse','output_boundary': 'wmse' }, optimizer=opt)

  File "..\..\..\..\..\Code\keras\keras\models.py", line 1063, in compile
    self._train = K.function(train_ins, [train_loss], updates=updates)

  File "..\..\..\..\..\Code\keras\keras\backend\theano_backend.py", line 394, in function
    return Function(inputs, outputs, updates=updates)

  File "..\..\..\..\..\Code\keras\keras\backend\theano_backend.py", line 386, in __init__
    allow_input_downcast=True, **kwargs)

  File "c:\downloads\theano\theano\compile\function.py", line 317, in function
    output_keys=output_keys)

  File "c:\downloads\theano\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)

  File "c:\downloads\theano\theano\compile\function_module.py", line 1777, in orig_function
    defaults)

  File "c:\downloads\theano\theano\compile\function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)

  File "c:\downloads\theano\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]

  File "c:\downloads\theano\theano\gof\vm.py", line 1037, in make_all
    no_recycling))

  File "c:\downloads\theano\theano\scan_module\scan_op.py", line 868, in make_thunk
    on_unused_input='ignore')

  File "c:\downloads\theano\theano\compile\function.py", line 317, in function
    output_keys=output_keys)

  File "c:\downloads\theano\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)

  File "c:\downloads\theano\theano\compile\function_module.py", line 1777, in orig_function
    defaults)

  File "c:\downloads\theano\theano\compile\function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)

  File "c:\downloads\theano\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]

  File "c:\downloads\theano\theano\gof\vm.py", line 1037, in make_all
    no_recycling))

  File "c:\downloads\theano\theano\scan_module\scan_op.py", line 868, in make_thunk
    on_unused_input='ignore')

  File "c:\downloads\theano\theano\compile\function.py", line 317, in function
    output_keys=output_keys)

  File "c:\downloads\theano\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)

  File "c:\downloads\theano\theano\compile\function_module.py", line 1777, in orig_function
    defaults)

  File "c:\downloads\theano\theano\compile\function_module.py", line 1657, in create
    self.return_none, self.output_keys, self)

  File "c:\downloads\theano\theano\compile\function_module.py", line 417, in __init__
    c.value = value

  File "c:\downloads\theano\theano\gof\link.py", line 468, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)

  File "c:\downloads\theano\theano\tensor\type.py", line 194, in filter
    " dimension.", data.shape, self.broadcastable)

TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn}(Elemwise{maximum,no_inplace}.0, InplaceDimShuffle{0,x,1,2,3}.0, Alloc.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Elemwise{Add}[(0, 0)].0, Subtensor{int64:int64:int64}.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, <TensorType(float32, matrix)>, <TensorType(float32, vector)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, ARange{dtype='int64'}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0), '\n', 'The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn}(Shape_i{0}.0, InplaceDimShuffle{0,2,1}.0, Elemwise{neq,no_inplace}.0, Alloc.0, Alloc.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{::int64}.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Elemwise{Composite{minimum(minimum(i0, i1), i2)}}.0, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0), '\n', 'Non-unit value on shape on a broadcastable dimension.', (0L, 0L, 0L), (False, False, True), 'Container name "None"')


In [2]:

**Comment by nouiz** [comment]
There should be more then that, like a file dump with stuff just after.
This is the part I need.

Be sure to use the same version of Theano on windows, the last release 0.7
don't work well with update to windows.

**Comment by shampool** [comment]
@nouiz  Thanks for your comments.
That is all the information I can get from the python interpreter. 
I am not sure how to get the file with dumped information. Could you give me a link? Thank you.

I updated my theano to 0.8 as well, that is the error message I got with theano 0.8 on windows.

**Comment by nouiz** [comment]
Did you fix it? I don't remember how to get a better error message on windows, but if you give me script to reproduce it, I can try to reproduce it here. That way, I can get the information I need to investigate.

**Comment by shampool** [comment]
Thanks, It's been fixed, I switched to ubuntu 14.04, and the problem disappeared.
