### ISSUE TITLE
Import Error: No Module Named <hexstring>

### ISSUE THREAD

**Issue by jonathanasdf** [Theano/Theano#4052]
I just installed Theano on cygwin, and can import it fine, but whenever I try anything with it I get this error.

```
$ theano-nose
E
======================================================================
ERROR: Failure: ImportError (('The following error happened while compiling the node', Dot22(X, Y), '\n', 'No module named de61f4c333d06430fc7dc014bf04eb25', '[Dot22(X, Y)]'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/cygdrive/z/documents/CMU/10-401/test.py", line 10, in <module>
    mf = theano.function([X,Y],X.dot(Y))
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/vm.py", line 1037, in make_all
    no_recycling))
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/op.py", line 965, in make_thunk
    no_recycling)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1207, in make_thunk
    keep_lock=keep_lock)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1152, in __compile__
    keep_lock=keep_lock)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1602, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1513, in compile_cmodule
    preargs=preargs)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2235, in compile_str
    return dlimport(lib_filename)
  File "/home/jonathanasdf/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 331, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', Dot22(X, Y), '\n', 'No module named de61f4c333d06430fc7dc014bf04eb25', '[Dot22(X, Y)]')

----------------------------------------------------------------------
Ran 1 test in 1.635s

FAILED (errors=1)
```

I couldn't find any relevant information from a quick Google search. Does anyone know how I can debug this?

I am running with ldflags = -lblas in .theanorc. Without it, Theano complains that it cannot find blas.

**Comment by lamblin** [comment]
Could you try to run `theano-cache purge` first, and try again?
For some reason, the module appeared to be compiled correctly, but cannot be imported.
You could try to put a breakpoint (or use `theano-nose --pdb --pdb-failures`), and check what the value of `lib_filename` is, see if it is present on the filesystem, also check if its parent directory is in `sys.path` in python.

**Comment by jonathanasdf** [comment]
Sorry, I decided to give up and install Theano through Anaconda, so I won't be able to debug this issue any further.
