### ISSUE TITLE
Aggressive optimization in 3.x when handling matrices generated by T.ones()

### ISSUE THREAD

**Issue by Bonnevie** [Theano/Theano#4106]
Running the following MWE I get some peculiar behaviour in Python 3.x

```
import theano
import theano.tensor as T
from theano.tensor.shared_randomstreams import RandomStreams

srng = RandomStreams()

#we set up two ones-matrices with different dimensions
A = T.ones((10,2))
B = T.ones((5,2))
C = A-B

#we set up random matrices with the same dimensions as above
Ar = srng.normal((10,2))
Br = srng.normal((5,2))
Cr = Ar-Br

#we expect both of the C's to be incalculable due to dimension mismatch 
#the random matrices behave as desired
try: 
    Cr.eval()
    print('Random matrices can be substracted')
except:
    print('Subtraction of random matrices failed')

#but C can be calculated for the ones-matrices! 
try: 
    C.eval()
    print('Ones can be substracted')
except:
    print('Subtraction of ones failed')


# we can also try to use compiled versions
Cf = theano.function([],C)
Crf = theano.function([],Cr)

#the random matrices behave as desired
try: 
    Crf()
    print('Random matrices can be substracted (compiled)')
except:
    print('Subtraction of random matrices failed (compiled)')

#but C can be calculated for the ones-matrices! 
try: 
    Cf()
    print('Ones can be substracted (compiled)')
except:
    print('Subtraction of ones failed (compiled)')

```

It seemingly ignores that the ones-matrices are of different dimensionality. I had some colleagues confirm that it's also a bit wonky in 2.7, although less so: in 2.7 compiled functions work as desired (reporting an error), but .eval() reports an error *and* returns an output.

**Comment by nouiz** [comment]
For me, it fail in both python 2.7 and 3.4. Which version of Theano do you use? Can you update Theano to 0.8rc1 or the development version:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

```
>>> import theano
>>> import theano.tensor as T
>>> from theano.tensor.shared_randomstreams import RandomStreams
>>> 
>>> srng = RandomStreams()
>>> 
>>> #we set up two ones-matrices with different dimensions
... A = T.ones((10,2))
>>> B = T.ones((5,2))
>>> C = A-B
>>> 
>>> #we set up random matrices with the same dimensions as above
... Ar = srng.normal((10,2))
>>> Br = srng.normal((5,2))
>>> Cr = Ar-Br
>>> 
>>> #we expect both of the C's to be incalculable due to dimension mismatch 
... #the random matrices behave as desired
... try: 
...     Cr.eval()
...     print('Random matrices can be substracted')
... except:
...     print('Subtraction of random matrices failed')
... 
Subtraction of random matrices failed
>>> #but C can be calculated for the ones-matrices! 
... try: 
...     C.eval()
...     print('Ones can be substracted')
... except:
...     print('Subtraction of ones failed')
... 
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: Elemwise{sub,no_inplace}(TensorConstant{(10, 2) of 1.0}, TensorConstant{(5, 2) of 1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/u/bastienf/repos/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/u/bastienf/repos/theano/tensor/opt.py", line 5829, in constant_folding
    required = thunk()
  File "/u/bastienf/repos/theano/gof/op.py", line 883, in rval
    fill_storage()
  File "/u/bastienf/repos/theano/gof/cc.py", line 1707, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "/Tmp/lisa/os_v5/anaconda/envs/py3k/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
ValueError: Input dimension mis-match. (input[0].shape[0] = 10, input[1].shape[0] = 5)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f323b9851d0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/u/bastienf/repos/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/u/bastienf/repos/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/u/bastienf/repos/theano/gof/opt.py", line 2223, in apply
    sub_prof = gopt.apply(fgraph)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1879, in apply
    nb += self.process_node(fgraph, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1777, in process_node
    lopt, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1673, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1659, in warn
    raise exc
  File "/u/bastienf/repos/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/u/bastienf/repos/theano/tensor/opt.py", line 5829, in constant_folding
    required = thunk()
  File "/u/bastienf/repos/theano/gof/op.py", line 883, in rval
    fill_storage()
  File "/u/bastienf/repos/theano/gof/cc.py", line 1707, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "/Tmp/lisa/os_v5/anaconda/envs/py3k/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
ValueError: Input dimension mis-match. (input[0].shape[0] = 10, input[1].shape[0] = 5)

Subtraction of ones failed
>>> 
>>> # we can also try to use compiled versions
... Cf = theano.function([],C)
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: Elemwise{sub,no_inplace}(TensorConstant{(10, 2) of 1.0}, TensorConstant{(5, 2) of 1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/u/bastienf/repos/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/u/bastienf/repos/theano/tensor/opt.py", line 5829, in constant_folding
    required = thunk()
  File "/u/bastienf/repos/theano/gof/op.py", line 883, in rval
    fill_storage()
  File "/u/bastienf/repos/theano/gof/cc.py", line 1707, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "/Tmp/lisa/os_v5/anaconda/envs/py3k/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
ValueError: Input dimension mis-match. (input[0].shape[0] = 10, input[1].shape[0] = 5)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f323b6ea400>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/u/bastienf/repos/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/u/bastienf/repos/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/u/bastienf/repos/theano/gof/opt.py", line 2223, in apply
    sub_prof = gopt.apply(fgraph)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1879, in apply
    nb += self.process_node(fgraph, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1777, in process_node
    lopt, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1673, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1659, in warn
    raise exc
  File "/u/bastienf/repos/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/u/bastienf/repos/theano/tensor/opt.py", line 5829, in constant_folding
    required = thunk()
  File "/u/bastienf/repos/theano/gof/op.py", line 883, in rval
    fill_storage()
  File "/u/bastienf/repos/theano/gof/cc.py", line 1707, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "/Tmp/lisa/os_v5/anaconda/envs/py3k/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
ValueError: Input dimension mis-match. (input[0].shape[0] = 10, input[1].shape[0] = 5)

log_thunk_trace: There was a problem executing an Op.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/u/bastienf/repos/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/u/bastienf/repos/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/u/bastienf/repos/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "/u/bastienf/repos/theano/compile/function_module.py", line 1456, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/u/bastienf/repos/theano/gof/opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "/u/bastienf/repos/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/u/bastienf/repos/theano/gof/opt.py", line 240, in apply
    self.failure_callback(e, self, optimizer)
  File "/u/bastienf/repos/theano/gof/opt.py", line 197, in warn
    raise exc
  File "/u/bastienf/repos/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/u/bastienf/repos/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/u/bastienf/repos/theano/gof/opt.py", line 2223, in apply
    sub_prof = gopt.apply(fgraph)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1879, in apply
    nb += self.process_node(fgraph, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1777, in process_node
    lopt, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1673, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/u/bastienf/repos/theano/gof/opt.py", line 1659, in warn
    raise exc
  File "/u/bastienf/repos/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/u/bastienf/repos/theano/tensor/opt.py", line 5829, in constant_folding
    required = thunk()
  File "/u/bastienf/repos/theano/gof/op.py", line 883, in rval
    fill_storage()
  File "/u/bastienf/repos/theano/gof/cc.py", line 1707, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "/Tmp/lisa/os_v5/anaconda/envs/py3k/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
ValueError: Input dimension mis-match. (input[0].shape[0] = 10, input[1].shape[0] = 5)
>>> Crf = theano.function([],Cr)
>>> 
>>> #the random matrices behave as desired
... try: 
...     Crf()
...     print('Random matrices can be substracted (compiled)')
... except:
...     print('Subtraction of random matrices failed (compiled)')
... 
Subtraction of random matrices failed (compiled)
>>> #but C can be calculated for the ones-matrices! 
... try: 
...     Cf()
...     print('Ones can be substracted (compiled)')
... except:
...     print('Subtraction of ones failed (compiled)')
... 
Subtraction of ones failed (compiled)
```

**Comment by nouiz** [comment]
closing as no news and it was working correctly for me.
