### ISSUE TITLE
EquilibriumOptimizer is misbehaving

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#4123]
See the error message below. I don't have a ready small example, but if this error message alone is not informative enough, I can try to localize the bug. 

```
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f99fe5bdf90>
2016-02-25 15:36:08,514: theano.gof.opt: ERROR: SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f99fe5bdf90>
ERROR (theano.gof.opt): Traceback:
2016-02-25 15:36:08,514: theano.gof.opt: ERROR: Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/u/bahdanau/Dist/theano/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/u/bahdanau/Dist/theano/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/u/bahdanau/Dist/theano/theano/gof/opt.py", line 2151, in apply
    sub_prof = gopt.apply(fgraph)
  File "/u/bahdanau/Dist/theano/theano/scan_module/scan_opt.py", line 1713, in apply
    self.process_node(fgraph, node)
  File "/u/bahdanau/Dist/theano/theano/scan_module/scan_opt.py", line 1637, in process_node
    nw_pos = inv_compress_map[idx]
KeyError: 3

2016-02-25 15:36:08,545: theano.gof.opt: ERROR: Traceback (most recent call last):
  File "/u/bahdanau/Dist/theano/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/u/bahdanau/Dist/theano/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/u/bahdanau/Dist/theano/theano/gof/opt.py", line 2151, in apply
    sub_prof = gopt.apply(fgraph)
  File "/u/bahdanau/Dist/theano/theano/scan_module/scan_opt.py", line 1713, in apply
    self.process_node(fgraph, node)
  File "/u/bahdanau/Dist/theano/theano/scan_module/scan_opt.py", line 1637, in process_node
    nw_pos = inv_compress_map[idx]
KeyError: 3
```

**Comment by nouiz** [comment]
I just need a function_dump to be able to regenerate it:

http://www.deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

If you use blocks, you need to add an extra parameter *extra_tag_to_remove*

**Comment by rizar** [comment]
Can you access the [link](https://www.dropbox.com/s/1crmnh7pvjq28x6/dump.pkl?dl=0)?

**Comment by nouiz** [comment]
I get this error:

ImportError: No module named reverse_words.edit_distance

Where I can get this?

**Comment by rizar** [comment]
Actually, it has been a while since I saw this error message last time. Maybe it was somehow fixed. I will close the issue until I see it again.
