### ISSUE TITLE
GPU tests fail on current master

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#4131]
When i ran the nose tests on theano/gof/tests, the tests failed with the following traceback:
Full traceback : 

```
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Dot22.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Dot22.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Dot22.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Dot22.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Dot22.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_flatten
ERROR (theano.gof.opt): node: Flatten{1}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 1026, in local_gpu_flatten
    x, shp= node.inputs
ValueError: need more than 1 value to unpack

.............................ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): node: if{}(HostFromGpu.0, <theano.gof.tests.test_lazy.NotImplementedOp object at 0x10f32bed0>.0, <Generic>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 546, in local_gpu_lazy_ifelse
    for o in outs]):
AttributeError: 'Variable' object has no attribute 'dtype'

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): node: if{}(HostFromGpu.0, <theano.gof.tests.test_lazy.NotImplementedOp object at 0x10f32bed0>.0, <Generic>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 546, in local_gpu_lazy_ifelse
    for o in outs]):
AttributeError: 'Variable' object has no attribute 'dtype'

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): node: if{}(HostFromGpu.0, <theano.gof.tests.test_lazy.NotImplementedOp object at 0x10f32bed0>.0, <Generic>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 546, in local_gpu_lazy_ifelse
    for o in outs]):
AttributeError: 'Variable' object has no attribute 'dtype'

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): node: if{}(HostFromGpu.0, <theano.gof.tests.test_lazy.NotImplementedOp object at 0x10f32bed0>.0, <Generic>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 546, in local_gpu_lazy_ifelse
    for o in outs]):
AttributeError: 'Variable' object has no attribute 'dtype'

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): node: if{}(HostFromGpu.0, <theano.gof.tests.test_lazy.NotImplementedOp object at 0x10f32bed0>.0, <Generic>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 546, in local_gpu_lazy_ifelse
    for o in outs]):
AttributeError: 'Variable' object has no attribute 'dtype'

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): node: if{}(HostFromGpu.0, <theano.gof.tests.test_lazy.NotImplementedOp object at 0x10f32bed0>.0, <Generic>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 546, in local_gpu_lazy_ifelse
    for o in outs]):
AttributeError: 'Variable' object has no attribute 'dtype'

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): node: if{}(HostFromGpu.0, <theano.gof.tests.test_lazy.NotImplementedOp object at 0x10f32bed0>.0, <Generic>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 546, in local_gpu_lazy_ifelse
    for o in outs]):
AttributeError: 'Variable' object has no attribute 'dtype'

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): node: if{}(HostFromGpu.0, <theano.gof.tests.test_lazy.NotImplementedOp object at 0x10f32bed0>.0, <Generic>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/opt.py", line 546, in local_gpu_lazy_ifelse
    for o in outs]):
AttributeError: 'Variable' object has no attribute 'type'

..................................................................................F
======================================================================
FAIL: theano.gof.tests.test_vm.test_reallocation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/tests/test_vm.py", line 396, in test_reallocation
    assert check_storage(storage_map)[0]
AssertionError

----------------------------------------------------------------------
Ran 169 tests in 7.458s

FAILED (failures=1)
```

**Comment by Sentient07** [comment]
And this, on ```theano/tensor/tests/*.py``` https://gist.github.com/Sentient07/1a75c41caa64b46521b8

**Comment by Sentient07** [comment]
Sorry, I had by mistakenly set ```device=gpu``` instead of ```init_gpu_device=gpu0```.

**Comment by nouiz** [comment]
I don't know why you get this and we don't, but here is a PR that some some of the warning:

https://github.com/Theano/Theano/pull/4161

what is the value of Theano flag device? Normally, tests  should not run with device=gpu, but with device=cpu.

**Comment by nouiz** [comment]
It seem I didn't see all the comments before replying. This can make tests fail, but it should not make optimization crash. I fixed them.
