### ISSUE TITLE
error in mvcc_compiler.py

### ISSUE THREAD

**Issue by attardi** [Theano/Theano#4137]
A program that works fine on CPUs,  get this error when run on a NVIDIA GPU with SDK cuda-7.5:

Traceback (most recent call last):
  File "./conv_net_sentence.py", line 194, in <module>
    sqr_norm_lim=sqr_norm_lim)
  File "/home/attardi/experiments/Twitter/CNN_sentence/conv_net_classes.py", line 563, in train
    allow_input_downcast = True)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 259, in make_thunk
    compute_map, no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1076, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1354, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/nvcc_compiler.py", line 423, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuDnnConvGradI{inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAlloc{memset_0=True}.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='cross'}.0, Constant{1.0}, Constant{0.0}), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -arch=sm_37 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=11b90075e2397c684f9dc0f7276eab8f,-D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC -Xlinker -rpath,/home/attardi/.theano/compiledir_Linux-4.2--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -I/home/attardi/.theano/compiledir_Linux-4.2--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -I/usr/local/cuda-7.5/include -I/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -o /home/attardi/.theano/compiledir_Linux-4.2--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpk8npH6/9feb83af6867d846f4cb67ce81b7848b.so mod.cu -L/home/attardi/.theano/compiledir_Linux-4.2--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -L/usr/lib -lpython2.7 -lcudart -lcublas -lcuda_ndarray -lcudnn', '[GpuDnnConvGradI{inplace=True}(<CudaNdarrayType(float32, 4D)>, <CudaNdarrayType(float32, (False, False, False, True))>, <CudaNdarrayType(float32, 4D)>, <CDataType{cudnnConvolutionDescriptor_t}>, Constant{1.0}, Constant{0.0})]')

**Comment by attardi** [comment]
Looks like there is an extra space in:
    -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION

**Comment by attardi** [comment]
The fix is to line 165 in nvcc_compiler.py:

        flags.append("-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION")

**Comment by attardi** [comment]
nvcc signals three errors, compiling mod.cu:

    141   err = cudnnConvolutionBackwardData(
    142     _handle,
    143     (void *)&alpha,
    144     APPLY_SPECIFIC(kerns), CudaNdarray_DEV_DATA(kerns),
    145     APPLY_SPECIFIC(output), CudaNdarray_DEV_DATA(output),
    146     desc,
    147     (void *)&beta,
    148     APPLY_SPECIFIC(input), CudaNdarray_DEV_DATA(*input));

    mod.cu(147): error: argument of type "void *" is incompatible with parameter of type "cudnnConvolutionBwdDataAlgo_t"
    mod.cu(148): error: argument of type "float *" is incompatible with parameter of type "size_t"
    mod.cu(148): error: too few arguments in function call
    3 errors detected in the compilation of "/tmp/tmpxft_0000d1e6_00000000-9_mod.cpp1.ii".

**Comment by attardi** [comment]
Indeed /usr/local/cuda-7.5/include/cudnn.h defines:

    cudnnStatus_t CUDNNWINAPI cudnnConvolutionBackwardData(
                                cudnnHandle_t                       handle,
                                const void                         *alpha,
                                const cudnnFilterDescriptor_t       wDesc,
                                const void                         *w,
                                const cudnnTensorDescriptor_t       dyDesc,
                                const void                         *dy,
                                const cudnnConvolutionDescriptor_t  convDesc,
                                cudnnConvolutionBwdDataAlgo_t       algo,
                                void                               *workSpace,
                                size_t                              workSpaceSizeInBytes,
                                const void                         *beta,
                                const cudnnTensorDescriptor_t       dxDesc,
                                void                               *dx );

**Comment by attardi** [comment]
Fixed by upgrading to the bleeding edge release:

    pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
