### ISSUE TITLE
Can't do "import theano" using Linux / theano 0.8rc1

### ISSUE THREAD

**Issue by lcauchon** [Theano/Theano#4166]
Hi,
I got this error when I try to import theano in a linux environment.
This is also true for 0.7 but not 0.6.

Thanks,

Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/automountdir/gpfsFS1/projets/gc014/software/GIT/Theano-rel-0.8.0rc1/theano/__init__.py", line 42, in <module>
    from theano.configdefaults import config
  File "/gpfs/automountdir/gpfsFS1/projets/gc014/software/GIT/Theano-rel-0.8.0rc1/theano/configdefaults.py", line 1420, in <module>
    in_c_key=False)
  File "/gpfs/automountdir/gpfsFS1/projets/gc014/software/GIT/Theano-rel-0.8.0rc1/theano/configparser.py", line 265, in AddConfigVar
    root=newroot, in_c_key=in_c_key)
  File "/gpfs/automountdir/gpfsFS1/projets/gc014/software/GIT/Theano-rel-0.8.0rc1/theano/configparser.py", line 275, in AddConfigVar
    configparam.__get__(root, type(root), delete_key=True)
  File "/gpfs/automountdir/gpfsFS1/projets/gc014/software/GIT/Theano-rel-0.8.0rc1/theano/configparser.py", line 323, in __get__
    self.__set__(cls, val_str)
  File "/gpfs/automountdir/gpfsFS1/projets/gc014/software/GIT/Theano-rel-0.8.0rc1/theano/configparser.py", line 334, in __set__
    self.val = self.filter(val)
  File "/gpfs/automountdir/gpfsFS1/projets/gc014/software/GIT/Theano-rel-0.8.0rc1/theano/configparser.py", line 374, in filter
    cast_val = mytype(val)
ValueError: could not convert string to float: 'True'
>>>

**Comment by lamblin** [comment]
Please ask that question on StackOverflow or [theano-users](https://groups.google.com/forum/#!forum/theano-users), and provide the content of your THEANORC environment variable and `.theanorc` file if they exist.
My guess is that you used `lib.cnmem=True` instead of providing a number (size in MB or % of GPU memory) like the documentation indicates.
