### ISSUE TITLE
Got a 'import theano error' after update 0.7 to 0.8

### ISSUE THREAD

**Issue by chengzhanzhan** [Theano/Theano#4170]
When I updated the theano from 0.7 version to 0.8, I got a import error:

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 42, in <module>
    from theano.configdefaults import config
  File "/usr/local/lib/python2.7/dist-packages/theano/configdefaults.py", line 1420, in <module>
    in_c_key=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 265, in AddConfigVar
    root=newroot, in_c_key=in_c_key)
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 275, in AddConfigVar
    configparam.__get__(root, type(root), delete_key=True)
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 323, in __get__
    self.__set__(cls, val_str)
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 334, in __set__
    self.val = self.filter(val)
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 374, in filter
    cast_val = mytype(val)
ValueError: could not convert string to float: True

Then I attempt to update the numpy and scipy to the latest version:
>>> numpy.version.version
'1.8.2'
'>>> scipy.version.version
'0.13.3'

But the error is still there.

Then I reinstall the theano. It doesn't work.

**Comment by chengzhanzhan** [comment]
I reinstall the theano0.7, then upgrade numpy to 1.9.2; then the it's ok

**Comment by nouiz** [comment]
The problem is the Theano flags lib.cnmem. You give him a value of True. This isn't allowed. It must be a float. Try the value 1.

It work with Theano 0.7, as we just don't have that flag, so it end-up being ignored.

Can you update Theano to 0.8rc1 again and change the flag to make sure it work?

thanks

**Comment by chengzhanzhan** [comment]
@nouiz You are right!

Now I update the theano version to 0.8.0rc1.dev-e563c53c1c74d84b727ddeb9e3a53eb558e0944b
 by using "sudo python setup.py develop".

Then I set cnmem a value between 0 and 1, I got another error:
`$ python -c "import theano"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zzcheng/Theano/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/home/zzcheng/Theano/theano/sandbox/cuda/__init__.py", line 694, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/home/zzcheng/Theano/theano/sandbox/cuda/__init__.py", line 573, in use
    cnmem = min(config.lib.cnmem, 0.98) * 100
TypeError: function takes at most 1 argument (2 given)`

I found the corresponding code:
'568             if config.print_active_device:
569                 if config.lib.cnmem:
570                     if config.lib.cnmem > 1:
571                         cnmem_enabled = "enabled with initial size: %d MB" % config.lib.cnmem
572                     else:
573                         cnmem = min(config.lib.cnmem, 0.98) * 100
574                         cnmem_enabled = "enabled with initial size: %.1f%% of memory" % cnmem   '

I attempted to set cnmem > 1, such as 600, and it return:
'Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 600 MB, CuDNN 3007)'.

Why can't I set cnmem < 1.

Bellow is my .theanorc file:
'  1 [cuda]      
  2 root=/usr/local/cuda-7.5/bin/
  3             
  4 [global]    
  5 device=gpu0 
  6 force_device=True
  7 floatX=float32
  8             
  9 optimizer=fast_run
 10             
 11 allow_gc=False
 12             
 13 openmp=True 
 14             
 15 [nvcc]      
 16 fastmath = True
 17             
 18 [lib]       
 19 cnmem = 1000                                                                                                                             
 20             
 21 [scan]      
 22 allow_gc=False'

Thanks!

**Comment by nouiz** [comment]
This is strange.

The min() python command seem to only take 1 parameter.

Can you add this "import pdb;pdb.set_trace()" juste before the call to min.
This will get you in python debugger. then excute just "min" and give me
this output?

Here it work well. I have this output: "<built-in function min>"

Have you modified this file?

**Comment by JunjieHu** [comment]
Hi @nouiz  

I also have the same problem for the min.  I add "import pdb" at the beginning of "theano/sandbox/cuda/__init__.py" and add "pdb.set_trace()" just before calling "min". And I get the following error message.

`Using Theano backend.
Traceback (most recent call last):
  File "/home/jjhu/Research/lstm/lstm_text_generation.py", line 14, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 5, in <module>
    from . import backend as K
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 51, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 699, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 576, in use
    pdb.set_trace()
  File "/usr/lib/python2.7/pdb.py", line 1251, in set_trace
    Pdb().set_trace(sys._getframe().f_back)
  File "/usr/lib/python2.7/pdb.py", line 63, in __init__
    cmd.Cmd.__init__(self, completekey, stdin, stdout)
  File "/usr/lib/python2.7/cmd.py", line 90, in __init__
    import sys
TypeError: function takes at most 1 argument (2 given)`

**Comment by nouiz** [comment]
Uninstall Theano. Do this many times and try to import to be sure there
isn't many version installed. After that, install Theano 0.8.1. It is
probably mixed Theano version.
