### ISSUE TITLE
Saving and Loading theano variables

### ISSUE THREAD

**Issue by jpiabrantes** [Theano/Theano#4173]
I am using a theano variable to define a function. Then I save the variable. When I load the variable theano does not recognize it as being the same variable used before.

This code:
```python
import theano
import theano.tensor as T
from theano.misc.pkl_utils import dump,load
x = T.scalar('x')
y = x**2

f = file('temp','wb')
dump(x,f)
f.close()
del x

f = file('temp','rb')
x=load(f)
f.close()

F=theano.function([x],y)
print F(2)
```

Generates the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/jpiabrantes/Desktop/untitled6.py", line 28, in <module>
    F=theano.function([x],y)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1415, in __init__
    self._check_unused_inputs(inputs, outputs, on_unused_input)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1553, in _check_unused_inputs
    i.variable, err_msg))
theano.compile.function_module.UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 0 is not part of the computational graph needed to compute the outputs: x.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.
```

I also tried to Save/Load using cPickle with the same results.

**Comment by lamblin** [comment]
Pickled objects cannot keep pointers to objects still in memory, that cannot work when they can be saved and loaded in different processes, on different machines. pickling and unpickling is equivalent to a deep copy.

You can always pickle both x and y, then when you load the variables, the new x will be the input to the new y.

**Comment by jpiabrantes** [comment]
Pickling x and y it's also not working (actually it is what I am doing on my real script). The following code gives the same error as before:

```python
import theano
import theano.tensor as T
from theano.misc.pkl_utils import dump,load
x = T.scalar('x')
y = x**2

f = file('temp','wb')
dump(x,f)
dump(y,f)
f.close()
del x
del y

f = file('temp','rb')
x=load(f)
y=load(f)
f.close()

F=theano.function([x],y)
print F(2)
```

**Comment by lamblin** [comment]
If you call `dump` twice, even on the same file, a new deep copy will be done twice, so that does not really help. If you dump a data structure (a pair or a list for instance) containing both `x` and `y` at the same time, it should work.

```python
dump((x, y), f)
...
x, y = load(f)
````
This is not related to Theano, btw, you can try it with lists of lists in Python, for instance
```python
l = [1, 2]
ll = [l, l]
# try to pickle and unpickle l and then ll, or (l, ll)
l[0] = 0
print(ll)
```

**Comment by jpiabrantes** [comment]
Thank you @lamblin  that solved my problem.
