### ISSUE TITLE
Gradient method (float32 to float64)

### ISSUE THREAD

**Issue by Sylvus** [Theano/Theano#4197]
Hi,
when I try to run my network on the GPU I need to specify floatX=float32. Unfortunately this breaks my program with the following error:

> Traceback (most recent call last):
>  [...] File "Neural-Network.py", line 145, in compute_updates
>     updates = lasagne.updates.adagrad(cost, params, learning_rate=options.learning_rate,  epsilon=options.epsilon)
>   File "/usr/local/lib/python3.4/dist-packages/lasagne/updates.py", line 385, in adagrad
>     grads = get_or_compute_grads(loss_or_grads, params)
>   File "/usr/local/lib/python3.4/dist-packages/lasagne/updates.py", line 123, in get_or_compute_grads
>     return theano.grad(loss_or_grads, params)
>   File "/usr/local/lib/python3.4/dist-packages/theano/gradient.py", line 561, in grad
>     grad_dict, wrt, cost_name)
>   File "/usr/local/lib/python3.4/dist-packages/theano/gradient.py", line 1324, in _populate_grad_dict
>     rval = [access_grad_cache(elem) for elem in wrt]
>   File "/usr/local/lib/python3.4/dist-packages/theano/gradient.py", line 1324, in <listcomp>
>     rval = [access_grad_cache(elem) for elem in wrt]
>   File "/usr/local/lib/python3.4/dist-packages/theano/gradient.py", line 1279, in access_grad_cache
>     term = access_term_cache(node)[idx]
>   File "/usr/local/lib/python3.4/dist-packages/theano/gradient.py", line 973, in access_term_cache
>     output_grads = [access_grad_cache(var) for var in node.outputs]
>   File "/usr/local/lib/python3.4/dist-packages/theano/gradient.py", line 973, in <listcomp>
>     output_grads = [access_grad_cache(var) for var in node.outputs]
>   File "/usr/local/lib/python3.4/dist-packages/theano/gradient.py", line 1279, in access_grad_cache
>     term = access_term_cache(node)[idx]
>   File "/usr/local/lib/python3.4/dist-packages/theano/gradient.py", line 1113, in access_term_cache
>     input_grads = node.op.grad(inputs, new_output_grads)
>   File "/usr/local/lib/python3.4/dist-packages/theano/tensor/nnet/abstract_conv.py", line 573, in grad
>     d_bottom = bottom.type.filter_variable(d_bottom)
>   File "/usr/local/lib/python3.4/dist-packages/theano/tensor/type.py", line 233, in filter_variable
>     self=self))
> TypeError: Cannot convert Type TensorType(float32, (False, True, False, False)) (of Variable Rebroadcast{?,1}.0) into Type TensorType(float64, (False, True, False, False)). You can try to manually convert Rebroadcast{?,1}.0 into a TensorType(float64, (False, True, False, False)).
> 

For me this seems like an issue where Theano is expecting a float64 but I am passing a float32. Is this correct? And if this is intended, how do I need to adapt my program? 

Thank you very much!

Some additional information: I compute the cost myself so I could use T.cast(...) but that does not help. The params are given to me by the Lasagne Framework (params for the neural network I'm training). So maybe I need to ask there instead? Also this code works fine when running it on the CPU.

**Comment by Sylvus** [comment]
I found my problem, at some point in my code I was giving Lasagne a dtensor which, correctly gave me 64 bit floats. Sorry for the issue.
