### ISSUE TITLE
GPU pickling error

### ISSUE THREAD

**Issue by bartvm** [Theano/Theano#4238]
This was encountered by @yiulau. When unpickling a model on GPU (built using Blocks) the following error occurs:

```pytb
Traceback (most recent call last):
  File "/home/vanmerb/anaconda2/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/home/vanmerb/anaconda2/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/home/vanmerb/anaconda2/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "generate_error.py", line 1, in <module>
    from theano import tensor
  File "/home/vanmerb/blocks/blocks/serialization.py", line 261, in load
    return p.load()
  File "/home/vanmerb/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/vanmerb/anaconda2/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/home/vanmerb/Theano/theano/compile/function_module.py", line 1028, in _constructor_Function
    (container.data == x)
AssertionError
```
It turns out that `container.data` and `x` are different `CudaNdarray` objects seemingly referring to different memory locations on the GPU, but with the exact same data:

```python
(Pdb) p x.gpudata == container.data.gpudata
False
(Pdb) p np.all(np.array(container.data) == np.array(x))
True
```

The following code reproduces the error (requires Blocks and Fuel with MNIST downloaded): https://gist.github.com/f875ad0b47ed4c22e902

**Comment by bartvm** [comment]
Seems to be a Blocks issue.
