### ISSUE TITLE
BadOptimization error for local_gpua_careduce with acc_dtype

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4264]
The following test fails in DebugMode:

```
$ THEANO_FLAGS=mode=DEBUG_MODE theano-nose -sv theano/sandbox/gpuarray/tests/test_elemwise.py:T_gpureduce_dtype.test_reduce_custom_dtype

Mapped name None to device cuda: GeForce GTX 750 (CuDNN version 4007)
Test the ability to provide your own output dtype for a reduce. ... ERROR

======================================================================
ERROR: Test the ability to provide your own output dtype for a reduce.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/lamblinp/code/Theano_git/theano/tensor/tests/test_elemwise.py", line 856, in test_reduce_custom_dtype
    f(data)
  File "/u/lamblinp/code/Theano_git/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/u/lamblinp/code/Theano_git/theano/compile/debugmode.py", line 2279, in deco
    return f()
  File "/u/lamblinp/code/Theano_git/theano/compile/debugmode.py", line 2204, in f
    r_vals)
  File "/u/lamblinp/code/Theano_git/theano/compile/debugmode.py", line 1055, in _find_bad_optimizations0
    new_graph=new_graph_str)
BadOptimization: BadOptimization Error
  Variable: id 140512852752336 HostFromGpu(gpuarray).0
  Op HostFromGpu(gpuarray)(GpuCAReduceCuda{mul}.0)
  Value Type: <type 'numpy.ndarray'>
  Old Value shape, dtype, strides: () int16 ()

  Old Value:  -30210
  New Value shape, dtype, strides: () int16 ()

  New Value:  32767
  Reason:  local_gpua_careduce
  Old Graph:
  Prod{acc_dtype=float64} [id A] ''
   |HostFromGpu(gpuarray) [id B] ''
     |GpuFromHost<None> [id C] ''
       |<TensorType(float32, matrix)> [id D]

  New Graph:
  HostFromGpu(gpuarray) [id E] ''
   |GpuCAReduceCuda{mul} [id F] ''
     |GpuFromHost<None> [id C] ''


Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
```

**Comment by lamblin** [comment]
It may not be that bad, actually.
The data it is trying to reduce is the following:
```
(Pdb) p data
array([[ 7.35458231,  7.3439002 ,  3.14275408,  0.38952541],
       [ 4.22320604,  0.11452938,  0.99039823,  3.42300701],
       [ 4.34597301,  6.58151579,  1.75168395,  6.50324011]], dtype=float32)
(Pdb) p data.prod(dtype='d')
35326.961634572697
```

So the result does not fit in an `int16`. The casting from the `float64` accumulator to `int16` in that case seems to be done in a different way:
- the CPU implementation wraps around, and gives `-30210`, which is `35326 - 2**16`;
- the GPU implementation returns the max `int16` possible, `32767`, or `2**15 - 1`.

**Comment by lamblin** [comment]
This works now, maybe due to smaller inputs in that case.
