### ISSUE TITLE
CudaNdarray errors in nosetests

### ISSUE THREAD

**Issue by gokul-uf** [Theano/Theano#4328]
While running tests on the bleeding edge, I get the following errors

```
Ran 21758 tests in 12174.397s
FAILED (SKIP=72, errors=7)

======================================================================
ERROR: test_set_value (theano.sandbox.cuda.tests.test_basic_ops.test_shared_options)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gokul/Theano/theano/tensor/tests/test_sharedvar.py", line 256, in test_set_value
    get_x /= values_to_div
TypeError: unsupported operand type(s) for /=: 'CudaNdarray' and 'CudaNdarray'

======================================================================
ERROR: test_shared_do_alias (theano.sandbox.cuda.tests.test_basic_ops.test_shared_options)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gokul/Theano/theano/tensor/tests/test_sharedvar.py", line 303, in test_shared_do_alias
    x /= values_to_div
TypeError: unsupported operand type(s) for /=: 'CudaNdarray' and 'CudaNdarray'

======================================================================
ERROR: test_shared_dont_alias (theano.sandbox.cuda.tests.test_basic_ops.test_shared_options)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gokul/Theano/theano/tensor/tests/test_sharedvar.py", line 103, in test_shared_dont_alias
    x /= values_to_div
TypeError: unsupported operand type(s) for /=: 'CudaNdarray' and 'CudaNdarray'

======================================================================
ERROR: test_return_internal_type (theano.sandbox.cuda.tests.test_basic_ops.test_shared_options)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gokul/Theano/theano/tensor/tests/test_sharedvar.py", line 197, in test_return_internal_type
    x /= values_to_div  # supported by ndarray and CudaNdarray
TypeError: unsupported operand type(s) for /=: 'CudaNdarray' and 'CudaNdarray'

======================================================================
ERROR: test_set_value (theano.sandbox.cuda.tests.test_basic_ops.test_shared_options)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gokul/Theano/theano/tensor/tests/test_sharedvar.py", line 270, in test_set_value
    get_x /= values_to_div  # supported by ndarray and CudaNdarray
TypeError: unsupported operand type(s) for /=: 'CudaNdarray' and 'CudaNdarray'

======================================================================
ERROR: theano.sandbox.cuda.tests.test_cuda_ndarray.test_add_iadd_idiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gokul/Envs/theano_install/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/gokul/Theano/theano/sandbox/cuda/tests/test_cuda_ndarray.py", line 157, in test_add_iadd_idiv
    b0 /= b1
TypeError: unsupported operand type(s) for /=: 'CudaNdarray' and 'CudaNdarray'

----------------------------------------------------------------------
```
I am running the tests in `cpu` mode. @nouiz had mentioned that this is indeed an error in the tests.
REF: https://groups.google.com/forum/#!topic/theano-dev/Nsw2GyxLcps

@lamblin I'd like to work on this if you could tell me how I should go about it

**Comment by nouiz** [comment]
This is the commit that cause an error:

$ git bisect bad
7a97cfe85a2163839c0a08c9b35377f3057f5fa7 is the first bad commit
commit 7a97cfe85a2163839c0a08c9b35377f3057f5fa7
Author: Ramana.S <vxrram95@gmail.com>
Date:   Wed Feb 3 05:29:02 2016 +0530

    Added required __future__ imports

:040000 040000 8a290d5444cb9092381e8561366bf965d1499b1f
b01695926015fff39dfd245d0b6092bc13a7849e M      benchmark
:040000 040000 ab570039c60337d7d33cfc432f376a2b1690dcdd
100cede50dd92d373b2b453bb320056f42fef919 M      doc
:100755 100755 6188a9ccfae879273fa589a22318c92b6d7070ca
489ba7b2bfa43858b916b480d019ed75be4d675f M      setup.py
:040000 040000 00177e5343bea2af691a8db2bdae40274b38c175
43adb17f335df8a183cf98dab165d6c3c9aa3906 M      theano

**Comment by nouiz** [comment]
thanks, here is the fix:

https://github.com/Theano/Theano/pull/4330

On Sun, Apr 3, 2016 at 5:15 PM, Frédéric Bastien <frederic.bastien@gmail.com

**Comment by gokul-uf** [comment]
Will close as soon as PR is accepted
