### ISSUE TITLE
Some problems about sparse.basic.structured_dot

### ISSUE THREAD

**Issue by Glexin** [Theano/Theano#4348]
I write a script to get familiar with the sparse dot operations. I try structured_dot, dot, true_dot, and found some problems in structured_dot.
Environment : numpy 1.10.2, scipy 0.16.1, theano 0.7.0, CentOS 6.2
Problems in theano sparse dot:
1. structured_dot doesn't return sparse mat when one of the operands is dense, this doesn't match the doc.
2. If sturctured_dot(A, B). Calculate sturctured_dot's gradient of A will yield a exception. It's raise by code located in theano/sparse/basic.py(line 3506) StructuredDotGradCSR.perform(...), maybe caused by that numpy.dot doesn't support sparse matrix in my numpy version. Exception:
```
  Traceback (most recent call last):
  File "av/test.py", line 220, in <module>
    test_theano_sparse_dot()
  File "av/test.py", line 209, in test_theano_sparse_dot
    _C = f(sA, sB)
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
  File "/usr/lib/python2.7/site-packages/theano/gof/op.py", line 772, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/lib/python2.7/site-packages/theano/sparse/basic.py", line 3510, in perform
    dot_val = numpy.dot(g_ab[i], b[j].T)
ValueError: Cannot find a common data type.
Apply node that caused the error: StructuredDotGradCSR(CSMProperties{None}.1, CSMProperties{None}.2, SparseVariable{csr,float32}, SparseVariable{csr,float32})
Inputs types: [TensorType(int32, vector), TensorType(int32, vector), Sparse[float32, csr], Sparse[float32, csr]]
Inputs shapes: [(3,), (2,), (5, 1), (1, 1)]
Inputs strides: [(4,), (4,), 'No strides', 'No strides']
Inputs values: [array([0, 1, 4], dtype=int32), array([0, 3], dtype=int32), <5x1 sparse matrix of type '<type 'numpy.float32'>'
    with 3 stored elements in Compressed Sparse Row format>, <1x1 sparse matrix of type '<type 'numpy.float32'>'
    with 1 stored elements in Compressed Sparse Row format>]
```
When I modify replace the line 3506 '''dot_val = numpy.dot(g_ab[i], b[j].T)''' with '''dot_val = g_ab[i] * b[j].T''', it works fine. The * between numpy sparse matrix act as dot product.
3.The structured_dot's gradient for A and B are not symemtric, gradient_of_A is structured, but gradient_of_B is not structured, if A is dense matrix, and B is structured, do you guys implement in that way on purpose?
Script:

[test.py.txt](https://github.com/Theano/Theano/files/210111/test.py.txt)
Log:
[test.log.txt](https://github.com/Theano/Theano/files/210088/test.log.txt)

**Comment by Glexin** [comment]
I found that the the uploaded file is not found. Here is the script:
```
def test_theano_sparse_dot():
    import numpy as np
    import theano
    from theano import tensor as T
    from theano import sparse as tsp
    from scipy import sparse as sp
    def show_matrix(mat, name):
        print "%s %s :" % (name, type(mat))
        if not isinstance(mat, np.ndarray):
            mat = mat.toarray()
        print mat
    # data
    A = np.asarray([1,3,0,0,4], dtype=np.float32)
    A.shape = (1, 5)
    B = np.asarray([2,0,7,0,1], dtype=np.float32)
    B.shape = (5, 1)
    show_matrix(A, "Input mat A")
    show_matrix(B, "Input mat B")
    sA = sp.csr_matrix(A)
    sB = sp.csr_matrix(B)
    # theano variables
    spmatA = tsp.csr_matrix('A', dtype=theano.config.floatX)
    spmatB = tsp.csr_matrix('B', dtype=theano.config.floatX)
    matA = T.matrix('A')
    matB = T.matrix('B')

    print ""
    print "#### structrued_dot test ####"
    print "SparseMat dot SparseMat"
    product = tsp.basic.structured_dot(spmatA, spmatB)
    target = tsp.basic.sp_sum(product, sparse_grad=True)
    gA = T.grad(target, spmatA)
    gB = T.grad(target, spmatB)
    f = theano.function(
            inputs = [spmatA, spmatB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(sA, sB)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

    print ""
    print "SparseMat dot DenseMat"
    product = tsp.basic.structured_dot(spmatA, matB)
    target = product.sum()
    # If you replace the line above with the line below, it
    # will raise exception. Because the product is not sparse.
    #target = tsp.basic.sp_sum(product, sparse_grad=True)
    gA = T.grad(target, spmatA)
    gB = T.grad(target, matB)
    f = theano.function(
            inputs = [spmatA, matB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(sA, B)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

    print ""
    print "DenseMat dot SparseMat"
    product = tsp.basic.structured_dot(matA, spmatB)
    target = product.sum()
    # If you replace the line above with the line below, it
    # will raise exception. Because the product is not sparse.
    #target = tsp.basic.sp_sum(product, sparse_grad=True)
    gA = T.grad(target, matA)
    gB = T.grad(target, spmatB)
    f = theano.function(
            inputs = [matA, spmatB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(A, sB)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

    print ""
    print "#### theano.sparse.basic.dot test ####"
    print "SparseMat dot SparseMat"
    product = tsp.basic.dot(spmatA, spmatB)
    target = product.sum()
    gA = T.grad(target, spmatA)
    gB = T.grad(target, spmatB)
    f = theano.function(
            inputs = [spmatA, spmatB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(sA, sB)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

    print ""
    print "SparseMat dot DenseMat"
    product = tsp.basic.dot(spmatA, matB)
    target = product.sum()
    gA = T.grad(target, spmatA)
    gB = T.grad(target, matB)
    f = theano.function(
            inputs = [spmatA, matB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(sA, B)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

    print ""
    print "DenseMat dot SparseMat"
    product = tsp.basic.dot(matA, spmatB)
    target = product.sum()
    gA = T.grad(target, matA)
    gB = T.grad(target, spmatB)
    f = theano.function(
            inputs = [matA, spmatB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(A, sB)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

    print ""
    print "#### theano.sparse.basic.true_dot test ####"
    print "SparseMat dot SparseMat"
    product = tsp.basic.true_dot(spmatA, spmatB)
    target = tsp.basic.sp_sum(product, sparse_grad=True)
    gA = T.grad(target, spmatA)
    gB = T.grad(target, spmatB)
    f = theano.function(
            inputs = [spmatA, spmatB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(sA, sB)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

    print ""
    print "SparseMat dot DenseMat"
    product = tsp.basic.true_dot(spmatA, matB)
    target = tsp.basic.sp_sum(product, sparse_grad=True)
    gA = T.grad(target, spmatA)
    gB = T.grad(target, matB)
    f = theano.function(
            inputs = [spmatA, matB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(sA, B)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

    print ""
    print "DenseMat dot SparseMat"
    product = tsp.basic.true_dot(matA, spmatB)
    target = tsp.basic.sp_sum(product, sparse_grad=True)
    gA = T.grad(target, matA)
    gB = T.grad(target, spmatB)
    f = theano.function(
            inputs = [matA, spmatB],
            outputs = [product, gA, gB])
    _product, _gA, _gB = f(A, sB)
    show_matrix(_product, "_product")
    show_matrix(_gA, "_gA")
    show_matrix(_gB, "_gB")

if __name__ == '__main__':
    test_theano_sparse_dot()
```
