### ISSUE TITLE
ValueError: CudaNdarray_CopyFromCudaNdarray: need same dimensions for dim 0, destination=2, source=4

### ISSUE THREAD

**Issue by jdc08161063** [Theano/Theano#4354]
I'm running the code with scan:
```python
def step_nei_test(table_n,keys_n,filled_n,capacity_n,key_size_n,position):
    key = theano.shared(np.asarray(np.random.uniform(0,200,3),dtype=theano.config.floatX)) 
    findk = _find(table_n,keys_n,filled_n,capacity_n,key_size_n,key,theano.shared(np.asarray(1,dtype=theano.config.floatX)))
    table_n = findk[0]
    keys_n = findk[1]
    filled_n = findk[2]
    capacity_n = findk[3]
    key_size_n = findk[4]
    position = findk[5]
    return (table_n,keys_n,filled_n,capacity_n,key_size_n,position)
position = theano.shared(np.asarray(-2,dtype=theano.config.floatX))
results0, updates0 = theano.scan(fn=step_nei_test,
                                 outputs_info=[h.table_,h.keys_,h.filled_,h.capacity_,h.key_size_,position],
                                 n_steps=5)
```
it has an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\scisoft\theano-master\theano\gof\graph.py", line 523, in eval
    rval = self._fn_cache[inputs](*args)
  File "c:\scisoft\theano-master\theano\compile\function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "c:\scisoft\theano-master\theano\gof\link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "c:\scisoft\theano-master\theano\compile\function_module.py", line 859, in __call__
    outputs = self.fn()
  File "c:\scisoft\theano-master\theano\scan_module\scan_op.py", line 951, in rval
    r = p(n, [x[0] for x in i], o)
  File "c:\scisoft\theano-master\theano\scan_module\scan_op.py", line 940, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 505, in theano.scan_module.scan_perform.perform (C:\Users\Administrator\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.10-64\scan_perform\mod.cpp:5551)
    outs[j][0][pos[j]] = \
ValueError: CudaNdarray_CopyFromCudaNdarray: need same dimensions for dim 0, destination=2, source=4
Apply node that caused the error: forall_inplace,gpu,scan_fn}(TensorConstant{5}, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, scalar)>, <CudaNdarrayType(float32, vector)>, Rebroadcast{0}.0, Rebroadcast{0}.0, Subtensor{int64}.0, Subtensor{int64}.0, ScalarFromTensor.0, ScalarFromTensor.0)
Toposort index: 61
Inputs types: [TensorType(int64, scalar), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, row), CudaNdarrayType(float32, (True,)), CudaNdarrayType(float32, (True,)), CudaNdarrayType(float32, (True,)), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, scalar), CudaNdarrayType(float32, vector), CudaNdarrayType(float32, vector), CudaNdarrayType(float32, vector), TensorType(int64, scalar), TensorType(int64, scalar), Scalar(int64), Scalar(int64)]
Inputs shapes: [(), (2, 2), (1, 36), (1,), (1,), (1,), (), (), (), (), (), (), (), (), (), (3,), (1,), (1,), (), (), (), ()]
Inputs strides: [(), (2, 1), (0, 1), (0,), (0,), (0,), (), (), (), (), (), (), (), (), (), (1,), (0,), (0,), (), (), (), ()]
Inputs values: [array(5L, dtype=int64), CudaNdarray([[-1. -1.]
 [ 0. -1.]]), 'not shown', CudaNdarray([ 1.]), CudaNdarray([ 2.]), CudaNdarray([ 3.]), CudaNdarray(0.0), CudaNdarray(1664525.0), CudaNdarray(1664525.0), CudaNdarray(1.0), CudaNdarray(-1.0), CudaNdarray(1.0), CudaNdarray(0.0), CudaNdarray(-2.0), CudaNdarray(0.0), CudaNdarray([ 52.32150269  99.56606293  43.38441086]), CudaNdarray([ 0.]), CudaNdarray([-2.]), array(1L, dtype=int64), array(1L, dtype=int64), 1, 1]
Outputs clients: [[GpuSubtensor{int64}(forall_inplace,gpu,scan_fn}.0, Constant{1})], [], [], [], []]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

But when i run it step by step, the code is correct, and the error disappear. Does anyone else has the same problem?

**Comment by jdc08161063** [comment]
moreover, when i run it use for, it's correct.
for i in np.arange(5):
    te = step_nei_test(table_,keys_,filled_,capacity_,key_size_,position)
    table_ = te[0]
    keys_ = te[1]
    filled_ = te[2]
    capacity_ = te[3]
    key_size_ = te[4]
    position = te[5]

does anyone knows why? and how to do it with scan

**Comment by lamblin** [comment]
Can you run that code in DebugMode?

**Comment by jdc08161063** [comment]
@lamblin I tested the instructions in DebugMode and am still encountering the error. In the scan operation, can I change the length of table_? In the _find function, i will double the length of table_. Did it cause the error?

**Comment by lamblin** [comment]
When you say you are encountering the error, do you mean that you have the same exact error message and stack trace? Or does it fail with a different error?

You cannot change the shape of a recurrent state between timesteps, no. That would indeed cause errors like this one. You can use a larger tensor and only use a subset of it in earlier steps to circumvent that. If you have questions with that, please use `theano-users` or StackOverflow.

**Comment by nouiz** [comment]
This request that the state/output must be the same shape at each time
already come, so I made an issue to document it:

https://github.com/Theano/Theano/issues/4359

**Comment by jdc08161063** [comment]
@lamblin @nouiz thanks, i fixed the code.
