### ISSUE TITLE
Test failining theano.sandbox.gpuarray on master (7943ab3)

### ISSUE THREAD

**Issue by mgermain** [Theano/Theano#4361]
I ran the theano.sandbox.gpuarray tests on the last master(7943ab37580fc4f1436d93bb455ff7731be3c28d) with floatX=float32 and nothing else in my .thenaorc and I got some errors. This all works in float64.

```
======================================================================
ERROR: test_all (theano.sandbox.gpuarray.tests.test_blas.GpuGemmTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/germaima/Theano_BASE/theano/sandbox/gpuarray/tests/test_basic_ops.py", line 92, in test_all
    self.run_case(testname, inputs)
  File "/u/germaima/Theano_BASE/theano/sandbox/gpuarray/tests/test_basic_ops.py", line 99, in run_case
    node_ref = safe_make_node(self.op, *inputs_ref)
  File "/u/germaima/Theano_BASE/theano/tensor/tests/test_basic.py", line 195, in safe_make_node
    node = op(*inputs)
  File "/u/germaima/Theano_BASE/theano/gof/op.py", line 613, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/u/germaima/Theano_BASE/theano/tensor/blas.py", line 894, in make_node
    (z.dtype, a.dtype, x.dtype, y.dtype, b.dtype))
TypeError: ('gemm requires matching dtypes', ('float32', 'float64', 'float32', 'float32', 'float64'), 'Test GpuGemm{inplace=True}::test1: Error occured while making a node with inputs [array([[ 0.92534935, -0.60589957,  0.42917994, -0.67615211],\n       [ 0.73250955,  0.24764049,  0.91891026,  0.04828408],\n       [-0.92713422,  0.45374316, -0.99218029, -0.89941198]], dtype=float32), 1.0, array([[ 0.98398465, -0.57548499,  0.89474136, -0.0969189 ,  0.99758935],\n       [ 0.29500297,  0.40448141, -0.14083646, -0.66445047, -0.7637338 ],\n       [ 0.87576526,  0.8219949 , -0.20401293,  0.85060656,  0.49099845]], dtype=float32), array([[ 0.57965273,  0.27541703,  0.98548275, -0.04778893],\n       [-0.7957716 ,  0.74512666,  0.51225406, -0.40160233],\n       [-0.62748694, -0.01129297, -0.91820902, -0.04329544],\n       [-0.38201961,  0.84116054,  0.83589137, -0.06302214],\n       [-0.53137386, -0.82035011,  0.35880715,  0.31185666]], dtype=float32), 0.0]')

======================================================================
FAIL: test_c_inplace (theano.sandbox.gpuarray.tests.test_elemwise.test_gpu_Broadcast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/germaima/Theano_BASE/theano/sandbox/gpuarray/tests/test_elemwise.py", line 46, in test_c_inplace
    super(test_gpu_Broadcast, self).test_c_inplace()
  File "/u/germaima/Theano_BASE/theano/tensor/tests/test_elemwise.py", line 265, in test_c_inplace
    self.rand_cval)
  File "/u/germaima/Theano_BASE/theano/tensor/tests/test_elemwise.py", line 231, in with_linker_inplace
    self.assertTrue((xv == zv).all())
AssertionError: <pygpu.gpuarray.GpuArray object at 0x7f929da5e958> is not true

======================================================================
FAIL: test_fill (theano.sandbox.gpuarray.tests.test_elemwise.test_gpu_Broadcast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/germaima/Theano_BASE/theano/tensor/tests/test_elemwise.py", line 278, in test_fill
    assert (xv == yv).all()
AssertionError

======================================================================
FAIL: test_perform_inplace (theano.sandbox.gpuarray.tests.test_elemwise.test_gpu_Broadcast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/germaima/Theano_BASE/theano/tensor/tests/test_elemwise.py", line 259, in test_perform_inplace
    self.rand_val)
  File "/u/germaima/Theano_BASE/theano/tensor/tests/test_elemwise.py", line 231, in with_linker_inplace
    self.assertTrue((xv == zv).all())
AssertionError: <pygpu.gpuarray.GpuArray object at 0x7f929da5e8d0> is not true

======================================================================
FAIL: test_weird_strides (theano.sandbox.gpuarray.tests.test_elemwise.test_gpu_Broadcast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/germaima/Theano_BASE/theano/tensor/tests/test_elemwise.py", line 303, in test_weird_strides
    assert (f(xv, yv) == zv).all()
AssertionError

----------------------------------------------------------------------
Ran 324 tests in 699.508s
```

**Comment by nouiz** [comment]
This was fixed some times ago.
