### ISSUE TITLE
Indecipherable traceback error when using GPU

### ISSUE THREAD

**Issue by jpiabrantes** [Theano/Theano#4364]
I get a Traceback error when I import theano.

Here's the command line output with the Traceback in the end:
```sh
>>> import theano
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN not available)
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '14196' (I am process '16304')
1 #include <Python.h>
2 #include <iostream>
3 #include "theano_mod_helper.h"
4 #include "cuda_ndarray.cuh"
5 //////////////////////
6 ////  Support Code
7 //////////////////////
8
9
10             static __global__ void kernel_reduce_ccontig_node_97496c4d3cf9a06dc4082cc141f918d2_0(
11                     const unsigned int d0,
12                     const float *A,
13                     float * Z)
14             {
15                 const int threadCount = blockDim.x;
16                 const int threadNum = threadIdx.x;
17                 extern __shared__ float buf[];
18                 float myresult = 0;
19
20                 if (warpSize != 32)
21                 {
22                     return;  //TODO: set error code
23                 }
24
25                 for (int i0 = threadIdx.x; i0 < d0; i0 += blockDim.x)
26                 {
27                     myresult = myresult + A[i0];
28                 }
29
30         __syncthreads(); // some kernel do multiple reduction.
31         buf[threadNum] = myresult;
32         __syncthreads();
33
34         // rest of function is handled by one warp
35         if (threadNum < warpSize)
36         {
37             //round up all the partial sums into the first `warpSize` elements
38             for (int i = threadNum + warpSize; i < threadCount; i += warpSize)
39             {
40                 myresult = myresult + buf[i];
41             }
42             buf[threadNum] = myresult;
43         /*Comment this optimization as it don't work on Fermi GPU.
44         TODO: find why it don't work or put the GPU compute capability into the version
45             // no sync because only one warp is running
46             if(threadCount >32)
47             {buf[threadNum] = buf[threadNum] + buf[threadNum+16];buf[threadNum] = buf[threadNum] + buf[threadNum+8];buf[threadNum] = buf[threadNum] + buf[threadNum+4];buf[threadNum] = buf[threadNum] + buf[threadNum+2];buf[threadNum] = buf[threadNum] + buf[threadNum+1];
48                 if (threadNum == 0)
49                 {
50                     Z[0] = buf[0];
51                 }
52
53             }
54             else */
55             if (threadNum < 16)
56             {
57                 //reduce so that threadNum 0 has the reduction of everything
58                 if (threadNum + 16 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+16];if (threadNum + 8 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+8];if (threadNum + 4 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+4];if (threadNum + 2 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+2];if (threadNum + 1 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+1];
59                 if (threadNum == 0)
60                 {
61                     Z[0] = buf[0];
62                 }
63             }
64         }
65
66             }
67
68
69             static __global__ void kernel_reduce_1_node_97496c4d3cf9a06dc4082cc141f918d2_0(
70                     const unsigned int d0,
71                     const float *A, const int sA0,
72                     float * Z)
73             {
74                 const int threadCount = blockDim.x;
75                 const int threadNum = threadIdx.x;
76                 extern __shared__ float buf[];
77                 float myresult = 0;
78
79                 if (warpSize != 32)
80                 {
81                     return;  //TODO: set error code
82                 }
83
84                 for (int i0 = threadIdx.x; i0 < d0; i0 += blockDim.x)
85                 {
86                     myresult = myresult + A[i0 * sA0];
87                 }
88
89         __syncthreads(); // some kernel do multiple reduction.
90         buf[threadNum] = myresult;
91         __syncthreads();
92
93         // rest of function is handled by one warp
94         if (threadNum < warpSize)
95         {
96             //round up all the partial sums into the first `warpSize` elements
97             for (int i = threadNum + warpSize; i < threadCount; i += warpSize)
98             {
99                 myresult = myresult + buf[i];
100             }
101             buf[threadNum] = myresult;
102         /*Comment this optimization as it don't work on Fermi GPU.
103         TODO: find why it don't work or put the GPU compute capability into the version
104             // no sync because only one warp is running
105             if(threadCount >32)
106             {buf[threadNum] = buf[threadNum] + buf[threadNum+16];buf[threadNum] = buf[threadNum] + buf[threadNum+8];buf[threadNum] = buf[threadNum] + buf[threadNum+4];buf[threadNum] = buf[threadNum] + buf[threadNum+2];buf[threadNum] = buf[threadNum] + buf[threadNum+1];
107                 if (threadNum == 0)
108                 {
109                     Z[0] = buf[0];
110                 }
111
112             }
113             else */
114             if (threadNum < 16)
115             {
116                 //reduce so that threadNum 0 has the reduction of everything
117                 if (threadNum + 16 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+16];if (threadNum + 8 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+8];if (threadNum + 4 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+4];if (threadNum + 2 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+2];if (threadNum + 1 < threadCount) buf[threadNum] = buf[threadNum] + buf[threadNum+1];
118                 if (threadNum == 0)
119                 {
120                     Z[0] = buf[0];
121                 }
122             }
123         }
124
125             }
126
127
128
129     namespace {
130     struct __struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2 {
131         PyObject* __ERROR;
132
133         PyObject* storage_V3;
134 PyObject* storage_V1;
135
136
137         __struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2() {
138             // This is only somewhat safe because we:
139             //  1) Are not a virtual class
140             //  2) Do not use any virtual classes in the members
141             //  3) Deal with mostly POD and pointers
142
143             // If this changes, we would have to revise this, but for
144             // now I am tired of chasing segfaults because
145             // initialization code had an error and some pointer has
146             // a junk value.
147             memset(this, 0, sizeof(*this));
148         }
149         ~__struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2(void) {
150             cleanup();
151         }
152
153         int init(PyObject* __ERROR, PyObject* storage_V3, PyObject* storage_V1) {
154             Py_XINCREF(storage_V3);
155 Py_XINCREF(storage_V1);
156             this->storage_V3 = storage_V3;
157 this->storage_V1 = storage_V1;
158
159
160
161
162             this->__ERROR = __ERROR;
163             return 0;
164         }
165         void cleanup(void) {
166             __label_1:
167
168 double __DUMMY_1;
169 __label_3:
170
171 double __DUMMY_3;
172 __label_6:
173
174 double __DUMMY_6;
175
176             Py_XDECREF(this->storage_V3);
177 Py_XDECREF(this->storage_V1);
178         }
179         int run(void) {
180             int __failure = 0;
181
182     PyObject* py_V1;
183      CudaNdarray * V1;
184     PyObject* py_V3;
185      CudaNdarray * V3;
186 {
187
188     py_V1 = PyList_GET_ITEM(storage_V1, 0);
189     {Py_XINCREF(py_V1);}
190
191         if (py_V1 == Py_None)
192         {
193             V1 = NULL;
194         }
195         else
196         {
197
198         assert(py_V1->ob_refcnt >= 2); // There should be at least one ref from the container object,
199         // and one ref from the local scope.
200
201         if (CudaNdarray_Check(py_V1))
202         {
203             //fprintf(stderr, "c_extract CNDA object w refcnt %p %i\n", py_V1, (py_V1->ob_refcnt));
204             V1 = (CudaNdarray*)py_V1;
205             //std::cerr << "c_extract " << V1 << '\n';
206
207
208                 if (V1->nd != 0)
209                 {
210                     PyErr_Format(PyExc_RuntimeError,
211                                  "c_extract: Some CudaNdarray has rank %i, it was supposed to have rank 0",
212                                  V1->nd);
213                     V1 = NULL;
214                     {
215         __failure = 2;
216         if (!PyErr_Occurred()) {
217             PyErr_SetString(PyExc_RuntimeError,
218                 "Unexpected error in an Op's C code. "
219                 "No Python exception was set.");
220             }
221         goto __label_2;};
222                 }
223                 //std::cerr << "c_extract " << V1 << " nd check passed\n";
224
225
226                 assert(V1);
227                 Py_INCREF(py_V1);
228             }
229             else if (py_V1 == Py_None)
230             {
231                 PyErr_SetString(PyExc_TypeError,
232                                 "expected a CudaNdarray, not None");
233                 V1 = NULL;
234                 {
235         __failure = 2;
236         if (!PyErr_Occurred()) {
237             PyErr_SetString(PyExc_RuntimeError,
238                 "Unexpected error in an Op's C code. "
239                 "No Python exception was set.");
240             }
241         goto __label_2;};
242             }
243             else
244             {
245                 //fprintf(stderr, "FAILING c_extract CNDA object w refcnt %p %i\n", py_V1, (py_V1->ob_refcnt));
246                 PyErr_SetString(PyExc_TypeError, "Argument not a CudaNdarray");
247                 V1 = NULL;
248                 {
249         __failure = 2;
250         if (!PyErr_Occurred()) {
251             PyErr_SetString(PyExc_RuntimeError,
252                 "Unexpected error in an Op's C code. "
253                 "No Python exception was set.");
254             }
255         goto __label_2;};
256             }
257             //std::cerr << "c_extract done " << V1 << '\n';
258
259
260         }
261
262 {
263
264     py_V3 = PyList_GET_ITEM(storage_V3, 0);
265     {Py_XINCREF(py_V3);}
266
267         assert(py_V3->ob_refcnt >= 2); // There should be at least one ref from the container object,
268         // and one ref from the local scope.
269
270         if (CudaNdarray_Check(py_V3))
271         {
272             //fprintf(stderr, "c_extract CNDA object w refcnt %p %i\n", py_V3, (py_V3->ob_refcnt));
273             V3 = (CudaNdarray*)py_V3;
274             //std::cerr << "c_extract " << V3 << '\n';
275
276
277                 if (V3->nd != 1)
278                 {
279                     PyErr_Format(PyExc_RuntimeError,
280                                  "c_extract: Some CudaNdarray has rank %i, it was supposed to have rank 1",
281                                  V3->nd);
282                     V3 = NULL;
283                     {
284         __failure = 4;
285         if (!PyErr_Occurred()) {
286             PyErr_SetString(PyExc_RuntimeError,
287                 "Unexpected error in an Op's C code. "
288                 "No Python exception was set.");
289             }
290         goto __label_4;};
291                 }
292                 //std::cerr << "c_extract " << V3 << " nd check passed\n";
293
294
295                 assert(V3);
296                 Py_INCREF(py_V3);
297             }
298             else if (py_V3 == Py_None)
299             {
300                 PyErr_SetString(PyExc_TypeError,
301                                 "expected a CudaNdarray, not None");
302                 V3 = NULL;
303                 {
304         __failure = 4;
305         if (!PyErr_Occurred()) {
306             PyErr_SetString(PyExc_RuntimeError,
307                 "Unexpected error in an Op's C code. "
308                 "No Python exception was set.");
309             }
310         goto __label_4;};
311             }
312             else
313             {
314                 //fprintf(stderr, "FAILING c_extract CNDA object w refcnt %p %i\n", py_V3, (py_V3->ob_refcnt));
315                 PyErr_SetString(PyExc_TypeError, "Argument not a CudaNdarray");
316                 V3 = NULL;
317                 {
318         __failure = 4;
319         if (!PyErr_Occurred()) {
320             PyErr_SetString(PyExc_RuntimeError,
321                 "Unexpected error in an Op's C code. "
322                 "No Python exception was set.");
323             }
324         goto __label_4;};
325             }
326             //std::cerr << "c_extract done " << V3 << '\n';
327
328
329 {
330 // Op class GpuCAReduce
331
332         if (V3->nd != 1)
333         {
334             PyErr_Format(PyExc_TypeError,
335                          "required nd=1, got nd=%i", V3->nd);
336             {
337         __failure = 5;
338         if (!PyErr_Occurred()) {
339             PyErr_SetString(PyExc_RuntimeError,
340                 "Unexpected error in an Op's C code. "
341                 "No Python exception was set.");
342             }
343         goto __label_5;};
344         }
345
346
347         if (  !V1
348            || (V1->nd != 0)
349
350
351            )
352         {
353
354 int *new_dims=NULL;
355
356             Py_XDECREF(V1);
357             V1 = (CudaNdarray*) CudaNdarray_NewDims(0, new_dims);
358             if (NULL == V1)
359             {
360                 {
361         __failure = 5;
362         if (!PyErr_Occurred()) {
363             PyErr_SetString(PyExc_RuntimeError,
364                 "Unexpected error in an Op's C code. "
365                 "No Python exception was set.");
366             }
367         goto __label_5;};
368             }
369         }
370
371
372         if (CudaNdarray_SIZE(V1) && ! CudaNdarray_SIZE(V3)){
373             cudaMemset(V1->devdata, 0, CudaNdarray_SIZE(V1) * sizeof(float));
374         }
375         else if (CudaNdarray_SIZE(V1))
376         {
377
378 if(CudaNdarray_is_c_contiguous(V3)){
379
380         {
381           if(CudaNdarray_SIZE(V3)==0){
382             cudaMemset(V1->devdata, 0, CudaNdarray_SIZE(V1) * sizeof(float));
383           }else{
384             int verbose = 0;
385             dim3 n_threads(
386                     std::min(CudaNdarray_SIZE(V3),
387                              (size_t) NUM_VECTOR_OP_THREADS_PER_BLOCK));
388             dim3 n_blocks(1);
389             if (verbose) printf("running kernel_reduce_ccontig_node_97496c4d3cf9a06dc4082cc141f918d2_0"
390                                 " n_threads.x=%d, size=%d, ndim=%d\n",
391                                 n_threads.x,CudaNdarray_SIZE(V3),V3->nd);
392             int n_shared = sizeof(float) * n_threads.x;
393             kernel_reduce_ccontig_node_97496c4d3cf9a06dc4082cc141f918d2_0<<<n_blocks, n_threads, n_shared>>>(
394                     CudaNdarray_SIZE(V3),
395                     CudaNdarray_DEV_DATA(V3),
396                     CudaNdarray_DEV_DATA(V1));
397             CNDA_THREAD_SYNC;
398             cudaError_t sts = cudaGetLastError();
399             if (cudaSuccess != sts)
400             {
401                 PyErr_Format(PyExc_RuntimeError,
402                              "Cuda error: %s: %s."
403                              " (grid: %i x %i; block: %i x %i x %i)\n",
404                     "kernel_reduce_ccontig_node_97496c4d3cf9a06dc4082cc141f918d2_0",
405                     cudaGetErrorString(sts),
406                     n_blocks.x,
407                     n_blocks.y,
408                     n_threads.x,
409                     n_threads.y,
410                     n_threads.z);
411                 {
412         __failure = 5;
413         if (!PyErr_Occurred()) {
414             PyErr_SetString(PyExc_RuntimeError,
415                 "Unexpected error in an Op's C code. "
416                 "No Python exception was set.");
417             }
418         goto __label_5;};
419             }
420          }
421         }
422
423 }else{
424
425         {
426             int verbose = 0;
427             dim3 n_threads(
428                     std::min(CudaNdarray_HOST_DIMS(V3)[0],
429                             NUM_VECTOR_OP_THREADS_PER_BLOCK));
430             dim3 n_blocks(1);
431
432             if (verbose)
433                 printf("running kernel_reduce_1_node_97496c4d3cf9a06dc4082cc141f918d2_0\n");
434             int n_shared = sizeof(float) * n_threads.x * n_threads.y * n_threads.z;
435             if (verbose>1)
436                 printf("n_threads.x=%d, n_threads.y=%d, n_threads.z=%d,"
437                        " nb_threads=%d, n_blocks.x=%d, n_blocks.y=%d,"
438                        " nb_block=%d, n_shared=%d, shape=(%d)\n",
439                                   n_threads.x,n_threads.y,n_threads.z,
440                                   n_threads.x*n_threads.y*n_threads.z,
441                                   n_blocks.x,n_blocks.y,
442                                   n_blocks.x*n_blocks.y, n_shared, CudaNdarray_HOST_DIMS(V3)[0]);
443             kernel_reduce_1_node_97496c4d3cf9a06dc4082cc141f918d2_0<<<n_blocks, n_threads, n_shared>>>(
444
445
446                     CudaNdarray_HOST_DIMS(V3)[0],
447
448
449                     CudaNdarray_DEV_DATA(V3)
450
451
452                     ,CudaNdarray_HOST_STRIDES(V3)[0]
453
454
455                     ,CudaNdarray_DEV_DATA(V1)
456
457
458                     );
459             CNDA_THREAD_SYNC;
460             cudaError_t sts = cudaGetLastError();
461             if (cudaSuccess != sts)
462             {
463                 PyErr_Format(PyExc_RuntimeError,
464                     "Cuda error: %s: %s."
465                     " (grid: %i x %i; block: %i x %i x %i)"
466                     " shape=(%d) \n",
467                     "kernel_reduce_1_node_97496c4d3cf9a06dc4082cc141f918d2_0",
468                     cudaGetErrorString(sts),
469                     n_blocks.x,
470                     n_blocks.y,
471                     n_threads.x,
472                     n_threads.y,
473                     n_threads.z,
474                     CudaNdarray_HOST_DIMS(V3)[0]);
475                 {
476         __failure = 5;
477         if (!PyErr_Occurred()) {
478             PyErr_SetString(PyExc_RuntimeError,
479                 "Unexpected error in an Op's C code. "
480                 "No Python exception was set.");
481             }
482         goto __label_5;};
483             }
484
485
486         }
487
488 }
489
490         }
491
492 __label_5:
493
494 double __DUMMY_5;
495
496 }
497 __label_4:
498
499         //std::cerr << "cleanup " << py_V3 << " " << V3 << "\n";
500         //fprintf(stderr, "c_cleanup CNDA py_object w refcnt %p %i\n", py_V3, (py_V3->ob_refcnt));
501         if (V3)
502         {
503             //fprintf(stderr, "c_cleanup CNDA cn_object w refcnt %p %i\n", V3, (V3->ob_refcnt));
504             Py_XDECREF(V3);
505         }
506         //std::cerr << "cleanup done" << py_V3 << "\n";
507
508     {Py_XDECREF(py_V3);}
509
510 double __DUMMY_4;
511
512 }
513 __label_2:
514
515     if (!__failure) {
516
517         //std::cerr << "sync\n";
518         if (NULL == V1) {
519             // failure: sync None to storage
520             Py_XDECREF(py_V1);
521             py_V1 = Py_None;
522             Py_INCREF(py_V1);
523         }
524         else
525         {
526             if (py_V1 != (PyObject*)V1)
527             {
528                 Py_XDECREF(py_V1);
529                 py_V1 = (PyObject*)V1;
530                 Py_INCREF(py_V1);
531             }
532             assert(py_V1->ob_refcnt);
533         }
534
535       PyObject* old = PyList_GET_ITEM(storage_V1, 0);
536       {Py_XINCREF(py_V1);}
537       PyList_SET_ITEM(storage_V1, 0, py_V1);
538       {Py_XDECREF(old);}
539     }
540
541         //std::cerr << "cleanup " << py_V1 << " " << V1 << "\n";
542         //fprintf(stderr, "c_cleanup CNDA py_object w refcnt %p %i\n", py_V1, (py_V1->ob_refcnt));
543         if (V1)
544         {
545             //fprintf(stderr, "c_cleanup CNDA cn_object w refcnt %p %i\n", V1, (V1->ob_refcnt));
546             Py_XDECREF(V1);
547         }
548         //std::cerr << "cleanup done" << py_V1 << "\n";
549
550     {Py_XDECREF(py_V1);}
551
552 double __DUMMY_2;
553
554 }
555
556
557         if (__failure) {
558             // When there is a failure, this code puts the exception
559             // in __ERROR.
560             PyObject* err_type = NULL;
561             PyObject* err_msg = NULL;
562             PyObject* err_traceback = NULL;
563             PyErr_Fetch(&err_type, &err_msg, &err_traceback);
564             if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}
565             if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}
566             if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}
567             PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);
568             PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);
569             PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);
570             PyList_SET_ITEM(__ERROR, 0, err_type);
571             PyList_SET_ITEM(__ERROR, 1, err_msg);
572             PyList_SET_ITEM(__ERROR, 2, err_traceback);
573             {Py_XDECREF(old_err_type);}
574             {Py_XDECREF(old_err_msg);}
575             {Py_XDECREF(old_err_traceback);}
576         }
577         // The failure code is returned to index what code block failed.
578         return __failure;
579
580         }
581     };
582     }
583
584
585         static int __struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2_executor(__struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2* self) {
586             return self->run();
587         }
588
589         static void __struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2_destructor(void* executor, void* self) {
590             delete ((__struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2*)self);
591         }
592
593 //////////////////////
594 ////  Functions
595 //////////////////////
596 static PyObject * instantiate(PyObject * self, PyObject *argtuple) {
597   assert(PyTuple_Check(argtuple));
598   if (3 != PyTuple_Size(argtuple)){
599      PyErr_Format(PyExc_TypeError, "Wrong number of arguments, expected 3, got %i", (int)PyTuple_Size(argtuple));
600      return NULL;
601   }
602   __struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2* struct_ptr = new __struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2();
603   if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1),PyTuple_GET_ITEM(argtuple, 2) ) != 0) {
604     delete struct_ptr;
605     return NULL;
606   }
607   PyObject* thunk = PyCObject_FromVoidPtrAndDesc((void*)(&__struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2_executor), struct_ptr, __struct_compiled_op_97496c4d3cf9a06dc4082cc141f918d2_destructor);
608   return thunk; }
609
610 //////////////////////
611 ////  Module init
612 //////////////////////
613 static PyMethodDef MyMethods[] = {
614     {"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
615     {NULL, NULL, 0, NULL}
616 };
617 PyMODINIT_FUNC init97496c4d3cf9a06dc4082cc141f918d2(void){
618    (void) Py_InitModule("97496c4d3cf9a06dc4082cc141f918d2", MyMethods);
619 }
620
===============================
nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2010, 2012, and 2013 are supported

['nvcc', '-shared', '-O3', '-LC:\\Anaconda2\\libs', '-arch=sm_50', '--compiler-bindir', 'C:\\Anaconda2\\MinGW\\bin', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-IC:\\Users\\jpiabrantes\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64\\cuda_ndarray', '-IC:\\Anaconda2\\lib\\site-packages\\numpy\\core\\include', '-IC:\\Anaconda2\\include', '-IC:\\Anaconda2\\lib\\site-packages\\theano\\gof', '-IC:\\Anaconda2\\lib\\site-packages\\theano\\sandbox\\cuda', '-o', 'C:\\Users\\jpiabrantes\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64\\tmp66dzfd\\97496c4d3cf9a06dc4082cc141f918d2.pyd', 'mod.cu', '-LC:\\Users\\jpiabrantes\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64\\cuda_ndarray', '-LC:\\Anaconda2\\libs', '-LC:\\Anaconda2', '-lcudart', '-lcublas', '-lcuda_ndarray', '-lpython27']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\theano\__init__.py", line 112, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "C:\Anaconda2\lib\site-packages\theano\sandbox\cuda\tests\test_driver.py", line 32, in test_nvidia_driver1
    profile=False)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function.py", line 322, in function
    output_keys=output_keys)
  File "C:\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 480, in pfunc
    output_keys=output_keys)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1779, in orig_function
    defaults)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1643, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Anaconda2\lib\site-packages\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Anaconda2\lib\site-packages\theano\gof\vm.py", line 1005, in make_all
    no_recycling))
  File "C:\Anaconda2\lib\site-packages\theano\sandbox\cuda\__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 972, in make_thunk
    no_recycling)
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 881, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "C:\Anaconda2\lib\site-packages\theano\sandbox\cuda\nvcc_compiler.py", line 403, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>), '\n', 'nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -LC:\\Anaconda2\\libs -arch=sm_50 --compiler-bindir C:\\Anaconda2\\MinGW\\bin -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -IC:\\Users\\jpiabrantes\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64\\cuda_ndarray -IC:\\Anaconda2\\lib\\site-packages\\numpy\\core\\include -IC:\\Anaconda2\\include -IC:\\Anaconda2\\lib\\site-packages\\theano\\gof -IC:\\Anaconda2\\lib\\site-packages\\theano\\sandbox\\cuda -o C:\\Users\\jpiabrantes\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64\\tmp66dzfd\\97496c4d3cf9a06dc4082cc141f918d2.pyd mod.cu -LC:\\Users\\jpiabrantes\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64\\cuda_ndarray -LC:\\Anaconda2\\libs -LC:\\Anaconda2 -lcudart -lcublas -lcuda_ndarray -lpython27', '[GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>)]')
```

Do you guys understand what's going on? I'm using windows 10

**Comment by jpiabrantes** [comment]
My .theanorc was pointing to anacondas compiler instead of visual studio. Had to change the line:

`compiler_bindir=C:\Anaconda2\MinGW\bin`

to:

`compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin`
