### ISSUE TITLE
Multi thread returns error on theano/compile

### ISSUE THREAD

**Issue by sjhddh** [Theano/Theano#4405]
Hello,

I've just written a multi threading program using `concurrent.futures.ThreadPoolExecutor` in Python3.5

I think it should be the similar as other multi-threading built-in functions before.

The program is working when I simple run them one by one.

But when I use concurrent, it returns:

```
Traceback (most recent call last):
  File "/Users/AaronSun/Git/.virtualenvs/ts/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: expected an ndarray, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/AaronSun/Git/test_scripts/test_scripts/free_test/test_concurrent_cv_pipe.py", line 67, in <module>
    cpipe = ConcorrentCVPipe(nlp_algo, ml_algo, [set1, set2, set3])
  File "/Users/AaronSun/Git/ts_eval/ts_eval/concurrent_cv_pipe.py", line 18, in __init__
    self.cocurrent_cv_pipe()
  File "/Users/AaronSun/Git/ts_eval/ts_eval/concurrent_cv_pipe.py", line 83, in cocurrent_cv_pipe
    print(i.result())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/AaronSun/Git/ts_eval/ts_eval/concurrent_cv_pipe.py", line 45, in pipe_wrapper
    custom_data=data)
  File "/Users/AaronSun/Git/ts_eval/ts_eval/pipe.py", line 82, in pipe
    eva.train(train_tectors, train_targets)
  File "/Users/AaronSun/Git/ts_eval/ts_eval/evalu.py", line 44, in train
    self.ml.fit(vectors, labels)
  File "/Users/AaronSun/Git/ts_ml/ts_ml/modules/ann/ann.py", line 82, in fit
    batch_size=self.batch, validation_split=self.validation_split, validation_data=self.validation_data)
  File "/Users/AaronSun/Git/.virtualenvs/ts/lib/python3.5/site-packages/keras/models.py", line 701, in fit
    shuffle=shuffle, metrics=metrics)
  File "/Users/AaronSun/Git/.virtualenvs/ts/lib/python3.5/site-packages/keras/models.py", line 317, in _fit
    outs = f(ins_batch)
  File "/Users/AaronSun/Git/.virtualenvs/ts/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 446, in __call__
    return self.function(*inputs)
  File "/Users/AaronSun/Git/.virtualenvs/ts/lib/python3.5/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Users/AaronSun/Git/.virtualenvs/ts/lib/python3.5/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/AaronSun/Git/.virtualenvs/ts/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: expected an ndarray, not None
Apply node that caused the error: Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)](Dot22.0, InplaceDimShuffle{x,0}.0)
Toposort index: 72
Inputs types: [TensorType(float32, matrix), TensorType(float32, row)]
Inputs shapes: [(500, 64), 'No shapes']
Inputs strides: [(256, 4), 'No strides']
Inputs values: ['not shown', None]
Outputs clients: [[Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 1.33333}, Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)].0, Elemwise{Composite{Cast{float32}(LT(i0, i1))}}[(0, 0)].0), Elemwise{Composite{(i0 * i1 * (i2 - sqr(i3)))}}[(0, 0)](Dot22Scalar.0, Elemwise{Composite{Cast{float32}(LT(i0, i1))}}[(0, 0)].0, TensorConstant{(1, 1) of 1.0}, Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)].0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

Is there any settings that I need to do for Theano before I use threading (calculating the different set of data using the same Theano-base ML function)?

Need help,
Cheers

**Comment by nouiz** [comment]
You can't have multiple threads call the same Theano function. There is global structure that should not be shared like this.

So you need one Theano function per thread. You can copy Theano function very easily, just by calling copy() on it. For this case, no parameter are needed.

http://deeplearning.net/software/theano/library/compile/function.html#theano.compile.function_module.Function.copy
