### ISSUE TITLE
Creating a step-function: Optimization failure due to: local_subtensor_merge

### ISSUE THREAD

**Issue by gnhm** [Theano/Theano#4417]
I'm trying to create a function which, when given an int64 vector, returns a 1d array of length N incremented by 1 after each element in the vector, and going to zero after the last element. This is possibly confusing, so perhaps the code is clearer:

```python
L = 20
steps = T.vector(dtype = 'int64')
mu = scan( fn = lambda s: T.eq( (s <= np.arange(L)) , ((steps[-1] > np.arange(L))) ), sequences = steps )[0].sum(axis = 0)
f = function([steps], mu)

print f([1,2, 7, 40]) #For example...
```

This returns `[0 1 2 2 2 2 2 3 3 3 3 3 3 3 3 0 0 0 0 0]`, which is the desired output. However, it also gives me a long list of errors, which I've appended to the end. Perhaps I'm doing something wrong, and if so, I'd appreciate suggestions.

```
ERROR (theano.gof.opt): Optimization failure due to: local_subtensor_merge
ERROR (theano.gof.opt): node: Subtensor{:int64:}(Subtensor{int64::}.0, ScalarFromTensor.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 2814, in local_subtensor_merge
    ushape[pos_2]))
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 2760, in merge_two_slices
    stop = pre_greedy_local_optimizer(list_opt, stop)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 2569, in pre_greedy_local_optimizer
    list_optimizations, out, {}, 0)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 2541, in local_recursive_function
    depth + 1)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 2541, in local_recursive_function
    depth + 1)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 2553, in local_recursive_function
    ret = opt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 2280, in local_upcast_elemwise_constant_inputs
    rval = [node.op(*new_inputs)]
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Elemwise{switch,no_inplace}.0) of Op Elemwise{sub,no_inplace}(Elemwise{switch,no_inplace}.0, DimShuffle{}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: local_dimshuffle_lift
ERROR (theano.gof.opt): node: DimShuffle{x,0}(Elemwise{gt,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 584, in local_dimshuffle_lift
    op.inplace)(inp)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (DimShuffle{x}.0) of Op DimShuffle{x,0}(DimShuffle{x}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(Subtensor{int64::}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1765, in local_shape_to_shape_i
    ret = shape_feature.make_vector_shape(node.inputs[0])
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1238, in make_vector_shape
    return make_vector(*self.shape_of[r])
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Elemwise{sub,no_inplace}.0) of Op MakeVector{dtype='int64'}(Elemwise{sub,no_inplace}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: local_dimshuffle_lift
ERROR (theano.gof.opt): node: DimShuffle{x,0}(Elemwise{gt,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 584, in local_dimshuffle_lift
    op.inplace)(inp)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (DimShuffle{x}.0) of Op DimShuffle{x,0}(DimShuffle{x}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(<TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1765, in local_shape_to_shape_i
    ret = shape_feature.make_vector_shape(node.inputs[0])
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1238, in make_vector_shape
    return make_vector(*self.shape_of[r])
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Shape_i{0}.0) of Op MakeVector{dtype='int64'}(Shape_i{0}.0) missing default value

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x10fbc8350>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 2196, in apply
    lopt_change = self.process_node(fgraph, node, lopt)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 584, in local_dimshuffle_lift
    op.inplace)(inp)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (DimShuffle{x}.0) of Op DimShuffle{x,0}(DimShuffle{x}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: local_dimshuffle_lift
ERROR (theano.gof.opt): node: DimShuffle{x,0}(Elemwise{gt,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 584, in local_dimshuffle_lift
    op.inplace)(inp)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (DimShuffle{x}.0) of Op DimShuffle{x,0}(DimShuffle{x}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): node: Shape(<TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1765, in local_shape_to_shape_i
    ret = shape_feature.make_vector_shape(node.inputs[0])
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1238, in make_vector_shape
    return make_vector(*self.shape_of[r])
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Shape_i{0}.0) of Op MakeVector{dtype='int64'}(Shape_i{0}.0) missing default value

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x10fb9f550>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 6707, in apply
    new_outputs = self.optimizer(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 6551, in local_fuse
    return_list=True)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (<int64>) of Op LE(<int64>, <int64>) missing default value

ERROR (theano.gof.opt): SeqOptimizer apply <theano.compile.mode.AddDestroyHandler object at 0x10e1fc290>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
Press ENTER or type command to continue
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/mode.py", line 134, in apply
    fgraph.replace_validate(o, _output_guard(o),
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Sum{axis=[0], acc_dtype=int64}.0) of Op OutputGuard(Sum{axis=[0], acc_dtype=int64}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: dimshuffle_as_view
ERROR (theano.gof.opt): node: DimShuffle{x}(Subtensor{int64}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 644, in dimshuffle_as_view
    v = new_op(*node.inputs)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Subtensor{int64}.0) of Op InplaceDimShuffle{x}(Subtensor{int64}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: dimshuffle_as_view
ERROR (theano.gof.opt): node: DimShuffle{x,0}(Elemwise{gt,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 644, in dimshuffle_as_view
    v = new_op(*node.inputs)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Elemwise{gt,no_inplace}.0) of Op InplaceDimShuffle{x,0}(Elemwise{gt,no_inplace}.0) missing default value

ERROR (theano.gof.opt): Optimization failure due to: dimshuffle_as_view
ERROR (theano.gof.opt): node: DimShuffle{0,x}(Subtensor{:int64:}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 644, in dimshuffle_as_view
    v = new_op(*node.inputs)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 635, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Subtensor{:int64:}.0) of Op InplaceDimShuffle{0,x}(Subtensor{:int64:}.0) missing default value
```

**Comment by nouiz** [comment]
Did you set the Theano flag compute_test_value? If so, remove it. It will
remove this problem.

If you didn't set it, it could be set by pymc3. Sometimes it get imported
when we load the Theano cache. You can delete Theano cache with this shell
command:

theano-cache purge

**Comment by gnhm** [comment]
I didn't set it, but I am using pymc3. Since I am trying to use this with pymc3, is there any way to get around this problem without changing compute_test_value?

**Comment by nouiz** [comment]
Use test value when you create a new Theano variable:

http://deeplearning.net/software/theano/tutorial/debug_faq.html#using-test-values

**Comment by nouiz** [comment]
No news, so closing.
