### ISSUE TITLE
Optimization failure due to: constant_folding

### ISSUE THREAD

**Issue by jdc08161063** [Theano/Theano#4431]
Hi,
    I'm running theano code on a 64-bit window computer, and i got the following error:

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: Alloc(TensorConstant{nan}, TensorConstant{-111})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "c:\scisoft\theano-master\theano\gof\opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "c:\scisoft\theano-master\theano\tensor\opt.py", line 5865, in constant_folding
    required = thunk()
  File "c:\scisoft\theano-master\theano\gof\op.py", line 885, in rval
    fill_storage()
  File "c:\scisoft\theano-master\theano\gof\cc.py", line 1707, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "<string>", line 2, in reraise
MemoryError: alloc failed

Does anyone know why?

**Comment by nouiz** [comment]
You are missing memory. This happen during the compilation of a Theano
function where we pre-compute everything that only depend on constant.

Do you have big constant in your graph?

**Comment by lamblin** [comment]
That question has been answered on theano-users.
