### ISSUE TITLE
Cuda unavailable after latest pull

### ISSUE THREAD

**Issue by sergeyf** [Theano/Theano#4458]
Hello,

I'm on Windows 8.1 with a GTX 870m GPU. Theano has been working for me with no issues until I did `git pull` + `python setup.py install` a few seconds ago. Now, `import theano` results in:

```EnvironmentError: You forced the use of gpu device gpu, but CUDA initialization failed with error:
cuda unavailable```

I have CUDA 7.5 installed, and have successfully rebuilt `Samples_vs2013.sln` with no errors.

Here is the full error log:

```
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 --compiler-bindir D:\\VS12\\VC\\bin\\amd64 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -ID:\\Anaconda2\\lib\\site-packages\\theano-0.9.0.dev0-py2.7.egg\\theano\\sandbox\\cuda -ID:\\Anaconda2\\lib\\site-packages\\numpy\\core\\include -ID:\\Anaconda2\\include -ID:\\Anaconda2\\lib\\site-packages\\theano-0.9.0.dev0-py2.7.egg\\theano\\gof -o C:\\Users\\S\\AppData\\Local\\Theano\\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -LD:\\Anaconda2\\libs -LD:\\Anaconda2 -lcublas -lpython27 -lcudart')
mod.cu
LINK : fatal error LNK1104: cannot open file 'C:/Users/S/AppData/Local/Theano/compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64/cuda_ndarray/cuda_ndarray.pyd'

['nvcc', '-shared', '-O3', '--compiler-bindir', 'D:\\VS12\\VC\\bin\\amd64', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-ID:\\Anaconda2\\lib\\site-packages\\theano-0.9.0.dev0-py2.7.egg\\theano\\sandbox\\cuda', '-ID:\\Anaconda2\\lib\\site-packages\\numpy\\core\\include', '-ID:\\Anaconda2\\include', '-ID:\\Anaconda2\\lib\\site-packages\\theano-0.9.0.dev0-py2.7.egg\\theano\\gof', '-o', 'C:\\Users\\S\\AppData\\Local\\Theano\\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64\\cuda_ndarray\\cuda_ndarray.pyd', 'mod.cu', '-LD:\\Anaconda2\\libs', '-LD:\\Anaconda2', '-lcublas', '-lpython27', '-lcudart']
Traceback (most recent call last):

  File "<ipython-input-1-fbeba985c8a6>", line 1, in <module>
    runfile('D:/Code/AI2/recreate_nan.py', wdir='D:/Code/AI2')

  File "D:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/Code/AI2/recreate_nan.py", line 4, in <module>
    from keras.layers import Input, Dense, merge

  File "D:\Anaconda2\lib\site-packages\keras-1.0.2-py2.7.egg\keras\__init__.py", line 3, in <module>
    from . import backend

  File "D:\Anaconda2\lib\site-packages\keras-1.0.2-py2.7.egg\keras\backend\__init__.py", line 51, in <module>
    from .theano_backend import *

  File "D:\Anaconda2\lib\site-packages\keras-1.0.2-py2.7.egg\keras\backend\theano_backend.py", line 1, in <module>
    import theano

  File "D:\Anaconda2\lib\site-packages\theano-0.9.0.dev0-py2.7.egg\theano\__init__.py", line 104, in <module>
    import theano.sandbox.cuda

  File "D:\Anaconda2\lib\site-packages\theano-0.9.0.dev0-py2.7.egg\theano\sandbox\cuda\__init__.py", line 696, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)

  File "D:\Anaconda2\lib\site-packages\theano-0.9.0.dev0-py2.7.egg\theano\sandbox\cuda\__init__.py", line 495, in use
    device, cuda_initialization_error_message))

EnvironmentError: You forced the use of gpu device gpu, but CUDA initialization failed with error:
cuda unavailable
```

Thanks for the wonderful package and all your help!

**Comment by nouiz** [comment]
Can you try to delete your Theano cache?

**Comment by sergeyf** [comment]
That did it, thanks so much!
