### ISSUE TITLE
NanGuard is flagging rng.binomial as "Big value"

### ISSUE THREAD

**Issue by braingineer** [Theano/Theano#4459]
Hi all,

Usually I can push through all Theano issues, but I can't figure this one out.  Any idea what it is or how to debug?   I can't recreate because I have no idea why it's happening.. 

print out when ran with `THEANO_FLAGS='optimizer=None,exception_verbosity=high'` and 

``` python
mode=NanGuardMode(nan_is_error=True, 
                  inf_is_error=True, 
                  big_is_error=True)
```

```
Traceback (most recent call last):
  File "/home/cogniton/anaconda/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/home/cogniton/anaconda/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/home/cogniton/anaconda/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "driver.py", line 18, in <module>
    """
  File "model.py", line 215, in train
    batch_size=self.igor.batch_size)
  File "/home/cogniton/research/code/keras/keras/engine/training.py", line 1399, in fit_generator
    raise e
AssertionError: Big value detected
NanGuardMode found an error in an input of this node.
Node:
GPU_mrg_uniform{CudaNdarrayType(float32, vector),no_inplace}(<CudaNdarrayType(float32, vector)>, TensorConstant{(1,) of 5})
The input variable that cause problem:
GPU_mrg_uniform{CudaNdarrayType(float32, vector),no_inplace}.0 [id A] ''   
 |<CudaNdarrayType(float32, vector)> [id B]
 |TensorConstant{(1,) of 5} [id C]
GPU_mrg_uniform{CudaNdarrayType(float32, vector),no_inplace}.1 [id A] ''   


Apply node that caused the error: GPU_mrg_uniform{CudaNdarrayType(float32, vector),no_inplace}(<CudaNdarrayType(float32, vector)>, TensorConstant{(1,) of 5})
Toposort index: 1599
Inputs types: [CudaNdarrayType(float32, vector), TensorType(int64, (True,))]
Inputs shapes: [(30,), (1,)]
Inputs strides: [(1,), (8,)]
Inputs values: ['not shown', array([5])]
Outputs clients: [['output'], [HostFromGpu(GPU_mrg_uniform{CudaNdarrayType(float32, vector),no_inplace}.1)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "model.py", line 125, in make
    igor.tree_spinetypeseq_in]),
  File "/home/cogniton/research/code/ikelos/ikelos/utils.py", line 25, in func
    out = layer(out)
  File "model.py", line 114, in <lambda>
    lambda x: [F_embedpos(x[0]), F_embedtype(x[1])])
  File "/home/cogniton/research/code/keras/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/cogniton/research/code/keras/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/cogniton/research/code/keras/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/cogniton/research/code/keras/keras/layers/embeddings.py", line 131, in call
    B = K.random_binomial((self.input_dim,), p=retain_p) * (1. / retain_p)
  File "/home/cogniton/research/code/keras/keras/backend/theano_backend.py", line 1137, in random_binomial
    return rng.binomial(shape, p=p, dtype=dtype)

Debugprint of the apply node: 
GPU_mrg_uniform{CudaNdarrayType(float32, vector),no_inplace}.0 [id A] <CudaNdarrayType(float32, vector)> ''   
 |<CudaNdarrayType(float32, vector)> [id B] <CudaNdarrayType(float32, vector)>
 |TensorConstant{(1,) of 5} [id C] <TensorType(int64, (True,))>
GPU_mrg_uniform{CudaNdarrayType(float32, vector),no_inplace}.1 [id A] <CudaNdarrayType(float32, vector)> ''   

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
```

I'm using Keras.  The code triggering  this bit:

``` python
    def call(self, x, mask=None):
        if 0. < self.dropout < 1.:
            retain_p = 1. - self.dropout
            B = K.random_binomial((self.input_dim,), p=retain_p) * (1. / retain_p)
            B = K.expand_dims(B)
            W = K.in_train_phase(self.W * B, self.W)
        else:
            W = self.W
        out = K.gather(W, x)
        return out
```

where `K.random_binomial` goes to

``` python
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams

# . . . 

def random_binomial(shape, p=0.0, dtype=_FLOATX, seed=None):
    if seed is None:
        seed = np.random.randint(10e6)
    rng = RandomStreams(seed=seed)
    return rng.binomial(shape, p=p, dtype=dtype)
```

The shape being used is `(5,)` and i tried `p`s between 0.05 and 0.95.

**Comment by braingineer** [comment]
modifying to avoid; issue is moot.

**Comment by nouiz** [comment]
Which version of Theano do you use? We fixed some issue like this before
the 0.8 release.

If you use Theano 0.8 or more recent, then can you give a full example that
reproduce that?

I understand that you have found a work around, but if this is a real
problem in Theano, I would like to fix it.

**Comment by braingineer** [comment]
Hi @nouiz , 

I am using 0.8, but I haven't pulled in a week or two.  

I tried to make it reproducible, but I couldn't find a quick way. I thought maybe it was [this one](https://github.com/Theano/Theano/issues/2076), so I tried creating a ton of them, thinking maybe that was it.  It wasn't.   I am working towards a Sunday deadline but I'll try to recreate after that.

**Comment by nouiz** [comment]
thanks. Good luck with your deadline.

If you can't reproduce it, they it could be just a random stuff. Always
hard to investigate!

**Comment by lamblin** [comment]
This should not be an issue any more with the new GPU back-end.
