### ISSUE TITLE
Bug in slicing

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#4469]
Please see an example and an error below.

```
╰─$ cat bug.py                                                                            
from theano import tensor

x = tensor.matrix('x')
y = tensor.tensor3('y')
x[:y.shape[0], None, :]
╭─rizar@nika-vostro  ~/temp  
╰─$  PYTHONPATH=$HOME/dist/Theano python bug.py
Traceback (most recent call last):
  File "bug.py", line 5, in <module>
    x[:y.shape[0], None, :]
  File "/home/rizar/dist/Theano/theano/tensor/var.py", line 527, in __getitem__
    check_rval = [arg == slice(None, None, None) for arg in new_args]
  File "/home/rizar/dist/Theano/theano/tensor/var.py", line 53, in __lt__
    rval = theano.tensor.basic.lt(self, other)
  File "/home/rizar/dist/Theano/theano/gof/op.py", line 602, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/rizar/dist/Theano/theano/tensor/elemwise.py", line 553, in make_node
    inputs = list(map(as_tensor_variable, inputs))
  File "/home/rizar/dist/Theano/theano/tensor/basic.py", line 210, in as_tensor_variable
    raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
theano.tensor.var.AsTensorError: ('Cannot convert None to TensorType', <type 'NoneType'>)
```

**Comment by nouiz** [comment]
I have a fix here:

**Comment by lamblin** [comment]
It seems to be working on the current master.
