### ISSUE TITLE
Cannot unpickle scan op that involves a shared variable

### ISSUE THREAD

**Issue by davidbau** [Theano/Theano#4574]
I am unable to pickle an object that happens to include a theano graph that uses a jacobian with a function involving a shared variable. It is failing because scan_op's validate_inner_graph complains about a CudaNdarray output.

I don't really understand what is going on in this case - is validate_inner_graph's assertion incorrect?  Here is a very minimal repro. (Run with THEANO_FLAGS=floatX=float32,device=gpu0.)

```
import theano, numpy, pickle

x = theano.shared(numpy.zeros(5, dtype=theano.config.floatX))
y = x ** 2

J = theano.gradient.jacobian(y, x)

s = pickle.dumps(J)
J2 = pickle.loads(s)
```

The exception traceback is as follows:

```
Traceback (most recent call last):
  File "jacobianbug.py", line 19, in <module>
    J2 = pickle.loads(s)
  File "/home/davidbau/git/ni/env/lib/python3.4/site-packages/theano/scan_module/scan_op.py", line 322, in __setstate__
    self.validate_inner_graph()
  File "/home/davidbau/git/ni/env/lib/python3.4/site-packages/theano/scan_module/scan_op.py", line 266, in validate_inner_graph
    raise TypeError("Inconsistency in the inner graph of "
TypeError: Inconsistency in the inner graph of scan '%s' : one of the outputs to the inner graph is of type CudaNdarray but the attributes of the scan op indicate that it shouldn't be the case
```

**Comment by davidbau** [comment]
@carriepl - looks like the checks were added in 7a63d84df924a71460c15feb2d7d58b216913691 - any insight on why they are necessary?  At least in this case, when I remove those checks, things work fine.

**Comment by davidbau** [comment]
The underlying problem is described in #4583 - closing.
