### ISSUE TITLE
Error while trying to profile

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#4610]
I get this error occasionally when i try profiling(at the end of profiling result). I am not able to produce this consistently. 

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/compile/profiling.py", line 101, in _atexit_print_fn
    n_apply_to_print=config.profiling.n_apply)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/compile/profiling.py", line 1250, in summary
    self.optimizer_profile[1])
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/gof/opt.py", line 291, in print_profile
    nb_nodes, callbacks_time) = prof
ValueError: need more than 9 values to unpack
```

**Comment by nouiz** [comment]
I included the fix in this PR: https://github.com/Theano/Theano/pull/4614
