### ISSUE TITLE
Windows issue with `pygpu`

### ISSUE THREAD

**Issue by m0nhawk** [Theano/Theano#4705]
Windows 10, Visual Studio 2013, Anaconda 4.1.0 with Python 2.7.

I've install the Theano via:

    pip install git+git://github.com/Theano/Theano.git

And `.theanorc.txt`:

```
[global]
device = cuda
floatX = float32

[nvcc]
flags=-LC:\Anaconda2\libs
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe
```

But it's impossible to load the Theano:

```
(C:\Anaconda2) C:\Users\Tapabrata>python -c "import theano"
ERROR (theano.gpuarray): pygpu was configured but could not be imported
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 21, in <module>
    import pygpu
ImportError: No module named pygpu
```

Manual install of `libgpuarray` yield on `setup.py`:

```
(C:\Anaconda2) C:\Users\Tapabrata\Downloads\libgpuarray-master>python setup.py build
running build
running build_py
running build_ext
building 'pygpu.gpuarray' extension
C:\Anaconda2\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -DGPUARRAY_SHARED -IC:\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\Tapabrata\Downloads\libgpuarray-master\src -IC:\Anaconda2\include -IC:\Anaconda2\PC -c pygpu/gpuarray.c -o build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o
In file included from C:\Anaconda2\lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:1777:0,
                 from C:\Anaconda2\lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:18,
                 from C:\Anaconda2\lib\site-packages\numpy\core\include/numpy/arrayobject.h:4,
                 from pygpu/gpuarray.c:300:
C:\Anaconda2\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h:12:9: note: #pragma message: C:\Anaconda2\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
pygpu/gpuarray.c: In function '__pyx_pf_5pygpu_8gpuarray_10GpuContext_4__cinit__':
pygpu/gpuarray.c:12322:17: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
pygpu/gpuarray.c: In function '__Pyx_RaiseNeedMoreValuesError':
pygpu/gpuarray.c:32086:18: warning: unknown conversion type character 'z' in format [-Wformat]
pygpu/gpuarray.c:32086:18: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'Py_ssize_t' [-Wformat]
pygpu/gpuarray.c:32086:18: warning: too many arguments for format [-Wformat-extra-args]
pygpu/gpuarray.c: In function '__Pyx_RaiseTooManyValuesError':
pygpu/gpuarray.c:32092:18: warning: unknown conversion type character 'z' in format [-Wformat]
pygpu/gpuarray.c:32092:18: warning: too many arguments for format [-Wformat-extra-args]
pygpu/gpuarray.c: In function '__Pyx_RaiseArgtupleInvalid':
pygpu/gpuarray.c:32489:18: warning: unknown conversion type character 'z' in format [-Wformat]
pygpu/gpuarray.c:32489:18: warning: format '%s' expects argument of type 'char *', but argument 5 has type 'Py_ssize_t' [-Wformat]
pygpu/gpuarray.c:32489:18: warning: unknown conversion type character 'z' in format [-Wformat]
pygpu/gpuarray.c:32489:18: warning: too many arguments for format [-Wformat-extra-args]
pygpu/gpuarray.c: In function '__Pyx_ImportType':
pygpu/gpuarray.c:36826:13: warning: unknown conversion type character 'z' in format [-Wformat]
pygpu/gpuarray.c:36826:13: warning: unknown conversion type character 'z' in format [-Wformat]
pygpu/gpuarray.c:36826:13: warning: too many arguments for format [-Wformat-extra-args]
pygpu/gpuarray.c:36832:13: warning: unknown conversion type character 'z' in format [-Wformat]
pygpu/gpuarray.c:36832:13: warning: unknown conversion type character 'z' in format [-Wformat]
pygpu/gpuarray.c:36832:13: warning: too many arguments for format [-Wformat-extra-args]
writing build\temp.win-amd64-2.7\Release\pygpu\gpuarray.def
C:\Anaconda2\Scripts\gcc.bat -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o build\temp.win-amd64-2.7\Release\pygpu\gpuarray.def -LC:\Users\Tapabrata\Downloads\libgpuarray-master\lib\Release -LC:\Anaconda2\libs -LC:\Anaconda2\PCbuild\amd64 -LC:\Anaconda2\PC\VS9.0\amd64 -lgpuarray -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\pygpu\gpuarray.pyd
build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o:gpuarray.c:(.text+0x376f): undefined reference to `__imp_gpuarray_api_major'
build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o:gpuarray.c:(.text+0x37ad): undefined reference to `__imp_gpuarray_api_minor'
build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o:gpuarray.c:(.text+0x248c7): undefined reference to `__imp_gpuarray_api_major'
build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o:gpuarray.c:(.text+0x248d8): undefined reference to `__imp_gpuarray_api_minor'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\Anaconda2\\Scripts\\gcc.bat' failed with exit status 1
```

How should I adjust installation steps to make it work?

**Comment by dog56ui78** [comment]
I had this problem a few days ago but I cant really remember what I did to fix it because getting theano to work for the gpu on windows has been terrible (And I currently have an open issue with getting the bleeding edge version to work). But try typing "conda update conda" then "conda update --all" and then "conda install mingw libpython" in the command prompt. And then reinstall theano. If that doesn't work then try reinstalling anaconda (set it as your default python). I believe thats what I did and it worked. And then retype the three commands and the one that installs theano.

**Comment by m0nhawk** [comment]
@dog56ui78 Thanks for the suggestion, but it didn't help. From a start it was a clean Windows 10 installation with Visual Studio 2013 and Anaconda 4.1.0 (Python 2.7).

I've already install the `mingw` and `libpython` to the environment.

Also, I'm using CUDA, so switching to OpenCL won't help.

**Comment by nouiz** [comment]
installing libgpuarray take 2 steps:

1) install the c package libgpuarray
2) install the python binding pygpu.

From the error message, I would think you didn't do 1. Can you confirm? This is done with cmake.

**Comment by m0nhawk** [comment]
@nouiz I have compile and installed the `libgpuarray`:

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="C:/Users/Tapabrata/Downloads/libgpuarray" -G"Visual Studio 12 2013 Win64" ..`

Build and install via Visual Studio is OK. And `python setup.py build` yields the mentioned error.

**Comment by nouiz** [comment]
I checked and have no idea. @abergeron come back Monday, he will probably have an idea.

**Comment by m0nhawk** [comment]
Any update on this?

I was using latest available versions: Theano/libgpuarray@f357aa9 & Theano/Theano@2644596

Same error as initially.

**Comment by abergeron** [comment]
It seems that Cython generates c99 code for printf and msvc2013 doesn't have support for those.

I made some hacks to avoid the affected format specifiers in the rest of the libgpuarray code but I can't change the output of Cython.  Maybe a different version will produce coda that is compilable with MSVC.  Otherwise you can try to build the extension with gcc or clang.

**Comment by nouiz** [comment]
I think I heard that msvc2015 support C99. So maybe updating it will help you.

**Comment by adler-j** [comment]
I managed to solve this in libgpuarray by doing:

``` 
python setup.py build_ext --compiler=msvc
python setup.py install
```

**Comment by masakinakada** [comment]
I am getting the same problem and cannot build libgpuarray on visual studio 2013. getting lots of errors. what is the best solution for this?? Anyvody figure it out?

**Comment by adler-j** [comment]
> I am getting the same problem and cannot build libgpuarray on visual studio 2013. getting lots of errors. what is the best solution for this?? Anyvody figure it out?

Did you try my solution?

Also what errors are you getting?

**Comment by masakinakada** [comment]
Hi Adler, thank you so much for your kind help. 
After Cmake, I cannot build the project with visual studio 2013, and I do not think I can try your solution. 
"python setup.py build_ext --compiler=msvc
python setup.py install"

Is there anyway I can jump into your solution? 
Thank you so much for your support! I have been struggling a week. ..

**Comment by adler-j** [comment]
> Just a note, we are doing conda packages to help install pygpu. This will
make this much easier to install on windows.

This is totally excellent and would make using pygpu so much easier. Great initiative. If you need any help with testing etc, please ask.

**Comment by masakinakada** [comment]
Thanks @nouiz !! 
Super helpful.

Masaki

**Comment by ddharmawan** [comment]
That's a great news @nouiz 
Will it be ready anytime soon by any chance?

**Comment by nouiz** [comment]
Can you try it?


conda install -c rdonnelly theano

We tested it and it worked for us, but having confirmation from other
people would be great.

**Comment by masakinakada** [comment]
Thank you so much @nouiz 

I tried and got following error. Do you know how to fix it? 

Using Theano backend.
Mapped name None to device cuda: GeForce GTX 1060 6GB
PCI Bus ID: 0000:01:00.0
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{(1L, 1L) of 1e-08})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1922, in process_node
    replacements = lopt.transform(node)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\tensor\opt.py", line 6387, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\op.py", line 924, in make_thunk
    no_recycling)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1578, in cthunk_factory
    key = self.cmodule_key()
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1270, in cmodule_key
    header_dirs=self.header_dirs(),
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1043, in header_dirs
    ret += x.c_header_dirs()
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gpuarray\type.py", line 494, in c_header_dirs
    return [pygpu.get_include(), numpy.get_include()]
  File "C:\Libs\Anaconda2\lib\site-packages\pygpu\__init__.py", line 4, in get_include
    assert os.path.exists(os.path.join(p, 'gpuarray_api.h'))
AssertionError

Traceback (most recent call last):
  File "testGPU.py", line 20, in <module>
    model.fit(data, labels, nb_epoch=10, batch_size=32)
  File "C:\Libs\Anaconda2\lib\site-packages\keras\models.py", line 671, in fit
    initial_epoch=initial_epoch)
  File "C:\Libs\Anaconda2\lib\site-packages\keras\engine\training.py", line 1116, in fit
    self._make_train_function()
  File "C:\Libs\Anaconda2\lib\site-packages\keras\engine\training.py", line 720, in _make_train_function
    **self._function_kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 963, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 949, in __init__
    **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1783, in orig_function
    output_keys=output_keys).create(
  File "C:\Libs\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1465, in __init__
    optimizer_profile = optimizer(fgraph)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 2415, in apply
    lopt_change = self.process_node(fgraph, node, lopt)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1927, in process_node
    lopt, node)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1821, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1807, in warn
    raise exc
AssertionError

**Comment by mingwandroid** [comment]
@masakinakada, can you please show the output from:

`conda info`

and

`conda list --show-channel-urls`

**Comment by abergeron** [comment]
This has been a problem in the past, that the headers would not be installed in the right place.

This PR *should* help with that issue: https://github.com/Theano/libgpuarray/pull/332

**Comment by masakinakada** [comment]
Thank you so much for the fix! 

However, I am still getting this error when I run 
python setup.py build_ext -L "C:/Program Files (x86)/libgpuarray/lib" -I "C:/Program Files (x86)/libgpuarray/include"

Could anyone help me?

pygpu/gpuarray.c:21333:12: warning: '__pyx_pw_5pygpu_8gpuarray_8GpuArray_17__bool__' defined but not used [-Wunused-function]
 static int __pyx_pw_5pygpu_8gpuarray_8GpuArray_17__bool__(PyObject *__pyx_v_self) {
            ^
writing build\temp.win-amd64-2.7\Release\pygpu\gpuarray.def
C:\TDM-GCC-64\bin\gcc.exe -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o build\temp.win-amd64-2.7\Release\pygpu\gpuarray.def -LC:\Libs\libgpuarray\lib\Release "-LC:/Program Files (x86)/libgpuarray/lib" -LC:\Libs\Anaconda2\libs -LC:\Libs\Anaconda2\PCbuild\amd64 -LC:\Libs\Anaconda2\PC\VS9.0\amd64 -lgpuarray -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\pygpu\gpuarray.pyd
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release/gpuarray.dll when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release/gpuarray.dll when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release\gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib\gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgpuarray
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\TDM-GCC-64\\bin\\gcc.exe' failed with exit status 1

**Comment by nouiz** [comment]
Did you call cmake becofe calling "python setup.py ..."? It seem the cmake
failed or didn't install in a path "python setup.py ..." find.

We have alpha conda packages. Do you want to try it?


conda install -c rdonnelly theano`

**Comment by masakinakada** [comment]
@nouiz 
Yes, I did the cmake before calling python setup.py....

And yes, I tried your alpha, but still got the same error like this
This is something to do with Theano version? 

I am so sorry for taking this much time.... Hope you can still help me with this...
Thank you so much!

ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1922, in process_node
    replacements = lopt.transform(node)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\tensor\opt.py", line 6387, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\op.py", line 924, in make_thunk
    no_recycling)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1578, in cthunk_factory
    key = self.cmodule_key()
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1270, in cmodule_key
    header_dirs=self.header_dirs(),
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1043, in header_dirs
    ret += x.c_header_dirs()
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gpuarray\type.py", line 494, in c_header_dirs
    return [pygpu.get_include(), numpy.get_include()]
  File "C:\Libs\Anaconda2\lib\site-packages\pygpu\__init__.py", line 4, in get_include
    assert os.path.exists(os.path.join(p, 'gpuarray_api.h'))
AssertionError

Traceback (most recent call last):
  File "testArms.py", line 188, in <module>
    history=model.fit(train_data, label,shuffle=True, validation_split=0.1,nb_epoch=100, batch_size=128, verbose=1,callbacks=callbacks_list)
  File "C:\Libs\Anaconda2\lib\site-packages\keras\models.py", line 671, in fit
    initial_epoch=initial_epoch)
  File "C:\Libs\Anaconda2\lib\site-packages\keras\engine\training.py", line 1100, in fit
    self._make_test_function()
  File "C:\Libs\Anaconda2\lib\site-packages\keras\engine\training.py", line 735, in _make_test_function
    **self._function_kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 963, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 949, in __init__
    **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1783, in orig_function
    output_keys=output_keys).create(
  File "C:\Libs\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1465, in __init__
    optimizer_profile = optimizer(fgraph)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 2415, in apply
    lopt_change = self.process_node(fgraph, node, lopt)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1927, in process_node
    lopt, node)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1821, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "C:\Libs\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1807, in warn
    raise exc
AssertionError

**Comment by abergeron** [comment]
The alpha packges have this problem.  There was a PR that was recently merged that should help with this so you can try a current checkout.

**Comment by masakinakada** [comment]
Thank you very much.
I upgraded Theano to newer version with following and running better!
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

One last erorror is
"
File "C:\Libs\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py",
line 23, in <module>
import pygpu.version
ImportError: No module named version"

Do you know if the conda install -c rdonnelly theano is missing the version

**Comment by nouiz** [comment]
Don't mix the conda packages and theano dev version. If you use Theano dev
version, remove all conda packages of Theano and libgpuarray and use
libgpuarray version.

The fix Arnaud was refering was in libgpuarray. Update this one too, delete
temporary compilation and recompile everything in it.

**Comment by masakinakada** [comment]
Oh, I see.
I was supposed to upgrade pygpu version....
Let me try it!

Thanks
