### ISSUE TITLE
pd.find_graphviz() was removed in pydot 1.2.x (released on 2016-07-01), causing `import theano` to fail

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [Theano/Theano#4759]
`pd.find_graphviz()` was removed in pydot 1.2.x (released on 2016-07-01). This causes `import theano` to fail:

```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 74, in <module>
    from theano.printing import pprint, pp
  File "/usr/local/lib/python2.7/dist-packages/theano/printing.py", line 35, in <module>
    if pd.find_graphviz():
AttributeError: 'module' object has no attribute 'find_graphviz'
```

(tested with Theano 0.8.2 and current master branch)

**Comment by nouiz** [comment]
There is already a fix in the PR: https://github.com/Theano/Theano/pull/4747
