### ISSUE TITLE
gpuarray/tests/test_dnn.py fails with CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by gokul-uf** [Theano/Theano#4784]
I am running `nosetest theano/gpuarray/tests/test_dnn.py`. 
I get the following output.

```
======================================================================
ERROR: theano.gpuarray.tests.test_dnn.test_dnn_batchnorm_train
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/gokul/Theano/theano/gpuarray/tests/test_dnn.py", line 1019, in test_dnn_batchnorm_train
    outputs = f(X, Scale, Bias, Dy)
  File "/home/gokul/Theano/theano/compile/function_module.py", line 875, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/gokul/Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/gokul/Theano/theano/compile/function_module.py", line 862, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Error during batchnorm: CUDNN_STATUS_BAD_PARAM

Apply node that caused the error: GpuDnnBatchNorm{mode='per-activation', epsilon=0.005}(GpuContiguous.0, GpuContiguous.0, GpuContiguous.0)
Toposort index: 24
Inputs types: [GpuArrayType<None>(float32, (False, False, False, True)), GpuArrayType<None>(float32, (False, False, False, True)), GpuArrayType<None>(float32, (False, False, False, True))]
Inputs shapes: [(4, 3, 1, 1), (1, 3, 1, 1), (1, 3, 1, 1)]
Inputs strides: [(12, 4, 4, 4), (4, 4, 12, 12), (4, 4, 12, 12)]
Inputs values: ['not shown', gpuarray.array([[[[-0.15183933]],

        [[-1.86331975]],

        [[-0.41337317]]]], dtype=float32), gpuarray.array([[[[ 0.49706259]],

        [[-0.08146131]],

        [[ 1.36952996]]]], dtype=float32)]
Outputs clients: [[GpuReshape{3}(GpuDnnBatchNorm{mode='per-activation', epsilon=0.005}.0, MakeVector{dtype='int64'}.0)], [GpuReshape{3}(GpuDnnBatchNorm{mode='per-activation', epsilon=0.005}.1, MakeVector{dtype='int64'}.0), GpuDnnBatchNormGrad{mode='per-activation', epsilon=0.005}(GpuContiguous.0, GpuReshape{4}.0, GpuContiguous.0, GpuDnnBatchNorm{mode='per-activation', epsilon=0.005}.1, GpuDnnBatchNorm{mode='per-activation', epsilon=0.005}.2)], [GpuReshape{3}(GpuDnnBatchNorm{mode='per-activation', epsilon=0.005}.2, MakeVector{dtype='int64'}.0), GpuDnnBatchNormGrad{mode='per-activation', epsilon=0.005}(GpuContiguous.0, GpuReshape{4}.0, GpuContiguous.0, GpuDnnBatchNorm{mode='per-activation', epsilon=0.005}.1, GpuDnnBatchNorm{mode='per-activation', epsilon=0.005}.2)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/gokul/Theano/theano/gradient.py", line 1267, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/gokul/Theano/theano/gradient.py", line 961, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/gokul/Theano/theano/gradient.py", line 1267, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/gokul/Theano/theano/gradient.py", line 961, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/gokul/Theano/theano/gradient.py", line 1267, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/gokul/Theano/theano/gradient.py", line 1101, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/home/gokul/Theano/theano/gpuarray/dnn.py", line 1427, in grad
    _, x_mean, x_invstd = self.make_node(x, scale, bias).outputs
  File "/home/gokul/Theano/theano/gpuarray/dnn.py", line 1422, in make_node
    return Apply(self, [x, scale, bias], [x.type(), scale.type(), scale.type()])

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

======================================================================
ERROR: theano.gpuarray.tests.test_dnn.test_batchnorm_inference
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/gokul/Theano/theano/gpuarray/tests/test_dnn.py", line 1075, in test_batchnorm_inference
    outputs = f(X, Scale, Bias, Mean, Var, Dy)
  File "/home/gokul/Theano/theano/compile/function_module.py", line 875, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/gokul/Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/gokul/Theano/theano/compile/function_module.py", line 862, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Error during batchnorm: CUDNN_STATUS_BAD_PARAM

Apply node that caused the error: GpuDnnBatchNormInference{mode='per-activation', epsilon=0.005}(GpuContiguous.0, GpuContiguous.0, GpuContiguous.0, GpuContiguous.0, GpuContiguous.0)
Toposort index: 28
Inputs types: [GpuArrayType<None>(float32, (False, False, False, True)), GpuArrayType<None>(float32, (False, False, False, True)), GpuArrayType<None>(float32, (False, False, False, True)), GpuArrayType<None>(float32, (False, False, False, True)), GpuArrayType<None>(float32, (False, False, False, True))]
Inputs shapes: [(4, 3, 1, 1), (1, 3, 1, 1), (1, 3, 1, 1), (1, 3, 1, 1), (1, 3, 1, 1)]
Inputs strides: [(12, 4, 4, 4), (4, 4, 12, 12), (4, 4, 12, 12), (4, 4, 12, 12), (4, 4, 12, 12)]
Inputs values: ['not shown', gpuarray.array([[[[ 0.98027265]],

        [[ 2.16591239]],

        [[-1.6757735 ]]]], dtype=float32), gpuarray.array([[[[ 0.33340845]],

        [[ 0.97332394]],

        [[-0.87594336]]]], dtype=float32), gpuarray.array([[[[ 2.36045694]],

        [[ 1.41262603]],

        [[-0.25679791]]]], dtype=float32), gpuarray.array([[[[ 0.12699968]],

        [[ 0.4482913 ]],

        [[ 0.6851173 ]]]], dtype=float32)]
Outputs clients: [[GpuReshape{3}(GpuDnnBatchNormInference{mode='per-activation', epsilon=0.005}.0, MakeVector{dtype='int64'}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 395, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/gokul/Theano/theano/gpuarray/tests/test_dnn.py", line 1047, in test_batchnorm_inference
    var, mode, eps)
  File "/home/gokul/Theano/theano/gpuarray/dnn.py", line 1687, in dnn_batch_normalization_test
    gpu_contiguous(var))
  File "/home/gokul/Theano/theano/gof/op.py", line 602, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/gokul/Theano/theano/gpuarray/dnn.py", line 1486, in make_node
    return Apply(self, [x, scale, bias, estimated_mean, estimated_variance], [x.type()])

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

----------------------------------------------------------------------
```

These tests were introduced in commit #18885126
I have mentioned this error in the discussion for that commit as well. 
Filing this bug to bring it to notice of others.
@nouiz @abergeron

**Comment by lamblin** [comment]
I vaguely remember that this had been solved by making sure `epsilon` was big enough.
Please re-open if the issue is still there.
