### ISSUE TITLE
Theano runs without gcc, but fails when gcc in path

### ISSUE THREAD

**Issue by dave07747** [Theano/Theano#4811]
Hi,

I'm on a windows 10 platform and when I run theano without gcc in the path, it runs fine, just complains about g++ not being available. However, when I add mingw into the path it throws an error. 

```
Problem occurred during compilation with the command line below:
C:\Program Files\mingw-w64\x86_64-6.1.0-posix-seh-rt_v5-rev0\mingw64\bin\g++.exe -shared -g -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Python34\lib\site-packages\numpy\core\include -IC:\Python34\include -IC:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\gof -o C:\Users\David\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_23_Stepping_10_GenuineIntel-3.4.3-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\David\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_23_Stepping_10_GenuineIntel-3.4.3-64\lazylinker_ext\mod.cpp -LC:\Python34\libs -LC:\Python34 -lpython34
In file included from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/math.h:36:0,

                 from C:\Python34\include/pyport.h:328,

                 from C:\Python34\include/Python.h:50,

                 from C:\Users\David\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_23_Stepping_10_GenuineIntel-3.4.3-64\lazylinker_ext\mod.cpp:1:

C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cmath:1133:11: error: '::hypot' has not been declared

   using ::hypot;

           ^~~~~


Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\gof\lazylinker_c.py", line 75, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\gof\lazylinker_c.py", line 92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David\Desktop\Neural Net\Theano\test.py", line 3, in <module>
    import theano
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\__init__.py", line 70, in <module>
    from theano.compile import (
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\compile\__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\compile\function_module.py", line 21, in <module>
    import theano.compile.mode
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\compile\mode.py", line 12, in <module>
    import theano.gof.vm
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\gof\vm.py", line 659, in <module>
    from . import lazylinker_c
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\Python34\lib\site-packages\theano-0.9.0.dev2-py3.4.egg\theano\gof\cmodule.py", line 2299, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): In file included from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/math.h:36:0,
.                  from C:\Python34\include/pyport.h:328,
.                  from C:\Python34\include/Python.h:50,
.                  from C:\Users\David\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_23_Stepping_10_GenuineIntel-3.4.3-64\lazylinker_ext\mod.cpp:1:
. C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cmath:1133:11: error: '::hypot' has not been declared
.    using ::hypot;
.            ^~~~~
. 
```

Any suggestion would be highly appreciated!

**Comment by ruslanagit** [comment]
Follow the following steps:
1. Install TDM-GCC (if not yet installed)
2, In  .theanorc file add 
 _[gcc] 
 cxxflags = -shared -I"[TDM-GCC path]\include" -I"[TDM-GCC path]\x86_64-w64-mingw32\include"_ 
Update paths to TDM-GCC according to your system, of course.
3. Verify that bin directory of mingw is added to PATH, but TDM-GCC path is not there.

These should work.

**Comment by riteish4141** [comment]
Hello,
I installed TDM-GCC, but I am unable to find this .theanorc file in my system. Can you tell me where can I locate this ?

**Comment by erfannoury** [comment]
There is no such a file. You have to create it.
Create it in user's directory, e.g. `C:\Users\<username>`

**Comment by dave07747** [comment]
You have to create a .theanorc or .theanorc.txt in your accounts user
directory

**Comment by ruslanagit** [comment]
The .theanorc file should be located in %USERPROFILE% directory.
Usually it maps into C:\Users\\\<username\> for Windows.
If the file does not already exist, you can create it manually with any text editor. 
And yes, you can also add .txt extension so the file name is .theanorc.txt

**Comment by nouiz** [comment]
As no news, I'll suppose the user fixed it. So closing.
