### ISSUE TITLE
Error with linking theano to g++

### ISSUE THREAD

**Issue by andrejzg** [Theano/Theano#4878]
I'm having a problem getting theano to work on my system. It works without g++, but ever since I installed g++ it's been throwing me these error messages. Thanks in advance for any help :).

```
C:\developer\workspaces\PythonBuildTools\venv\Scripts\pythonw.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2\helpers\pydev\pydevconsole.py" 51751 51752
PyDev console: starting.

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\developer\\workspaces\\PythonBuildTools'])

Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32

> import theano

00001	#include <Python.h>
===============================
00002	#include "theano_mod_helper.h"
00003	#include "structmember.h"
00004	#include <sys/time.h>
00005	
00006	#if PY_VERSION_HEX >= 0x03000000
00007	#include "numpy/npy_3kcompat.h"

**<lots more code printed here>**

Problem occurred during compilation with the command line below:
C:\MinGW\bin\g++.exe -shared -g -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=35840 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\numpy\core\include -IC:\Users\mallory\AppData\Roaming\company\python\3.4.3\include -IC:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\gof -o C:\Users\mallory\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_63_Stepping_2_GenuineIntel-3.4.3-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\mallory\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_63_Stepping_2_GenuineIntel-3.4.3-64\lazylinker_ext\mod.cpp -LC:\Users\mallory\AppData\Roaming\company\python\3.4.3\libs -LC:\Users\mallory\AppData\Roaming\company\python\3.4.3 -lpython34
===============================
C:\Users\mallory\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_63_Stepping_2_GenuineIntel-3.4.3-64\lazylinker_ext\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include <Python.h>
 ^

Traceback (most recent call last):
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\gof\lazylinker_c.py", line 74, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\gof\lazylinker_c.py", line 91, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mallory\AppData\Roaming\company\python\3.4.3\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\__init__.py", line 63, in <module>
    from theano.compile import (
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\compile\__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\compile\function_module.py", line 22, in <module>
    import theano.compile.mode
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\compile\mode.py", line 12, in <module>
    import theano.gof.vm
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\gof\vm.py", line 638, in <module>
    from . import lazylinker_c
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\gof\lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "C:\developer\workspaces\PythonBuildTools\venv\lib\site-packages\theano\gof\cmodule.py", line 2204, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): C:\Users\mallory\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_63_Stepping_2_GenuineIntel-3.4.3-64\lazylinker_ext\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
.  #include <Python.h>
.  ^
. 

```

**Comment by lamblin** [comment]
It looks like you installed a version of g++ that is 32-bit only, which is why it complains about "sorry, unimplemented: 64-bit mode not compiled in".
In the future, please use StackOverflow or the theano-users mailing list for such requests for support, we try to keep GitHub issues for bug reports and feature requests.
