### ISSUE TITLE
Error while printing profile

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#4892]
This is the error that I'm getting at the end of printing profile over the current master.

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/compile/profiling.py", line 103, in _atexit_print_fn
    n_apply_to_print=config.profiling.n_apply)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/compile/profiling.py", line 1256, in summary
    self.optimizer_profile[1])
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/gof/opt.py", line 339, in print_profile
    level=level + 1)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/gof/opt.py", line 2446, in print_profile
    o.print_profile(stream, prof, level + 2)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/gof/opt.py", line 899, in print_profile
    nb_fail, nb_merged, nb_constant), file=stream)
TypeError: %d format: a number is required, not TopoOptimizer
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/compile/profiling.py", line 103, in _atexit_print_fn
    n_apply_to_print=config.profiling.n_apply)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/compile/profiling.py", line 1256, in summary
    self.optimizer_profile[1])
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/gof/opt.py", line 339, in print_profile
    level=level + 1)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/gof/opt.py", line 2446, in print_profile
    o.print_profile(stream, prof, level + 2)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/theano/gof/opt.py", line 899, in print_profile
    nb_fail, nb_merged, nb_constant), file=stream)
TypeError: %d format: a number is required, not TopoOptimizer
Segmentation fault: 11
```
I started observing this error post the update of the master I did on 18th August.

**Comment by nouiz** [comment]
fixed in https://github.com/Theano/Theano/pull/4894
