### ISSUE TITLE
Theano Hanging

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#4921]
My fit is hanging. Attaching with gdb and dumping the backtrace I see:
```
#0  0x00002b96a4a85680 in sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:92
#1  0x00000000004faa68 in PyThread_acquire_lock (lock=lock@entry=0x2737490, waitflag=waitflag@entry=1) at Python/thread_pthread.h:324
#2  0x00000000004b0816 in PyEval_RestoreThread (tstate=0x23620a0) at Python/ceval.c:359
#3  0x00002b96d9a0dbb8 in CudaNdarray_CopyFromArray(CudaNdarray*, tagPyArrayObject*) ()
   from /home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.11-64/cuda_ndarray/cuda_ndarray.so
#4  0x00002b9788ffc25d in __struct_compiled_op_da6ac6908198a9d83223e8a2be6b76b9_executor((anonymous namespace)::__struct_compiled_op_da6ac6908198a9d83223e8a2be6b76b9*) ()
   from /home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.11-64/tmpHTVCuK/da6ac6908198a9d83223e8a2be6b76b9.so
```

I have `Theano==0.8.2` and am using cudnn 4.

**Comment by lamblin** [comment]
Are you using multithreading and GPU at the same time?
If so, you have to be careful because it is not safe in general.
Also, can you try with the development version from GitHub and the new GPU back-end (based on libgpuarray)?

**Comment by nouiz** [comment]
The first step is to try with the dev version of Theano.

**Comment by nouiz** [comment]
No news, so closing. If you fixed it, it would be great that you confirm it.
