### ISSUE TITLE
Can't import Theano: 'nvcc' already exists error

### ISSUE THREAD

**Issue by stepseazy** [Theano/Theano#5072]
Hello Sir or Madam,

Python won't let me import theano. Here is the error I get:

>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rik/anaconda3/lib/python3.5/site-packages/theano/__init__.py", line 39, in <module>
    from theano.configdefaults import config
  File "/home/rik/anaconda3/lib/python3.5/site-packages/theano/configdefaults.py", line 6, in <module>
    from theano.configparser import (AddConfigVar, BoolParam, ConfigParam, EnumStr,
  File "/home/rik/anaconda3/lib/python3.5/site-packages/theano/configparser.py", line 83, in <module>
    theano_cfg.read(config_files)
  File "/home/rik/anaconda3/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/home/rik/anaconda3/lib/python3.5/configparser.py", line 1063, in _read
    lineno)
configparser.DuplicateSectionError: While reading from '/home/rik/.theanorc' [line  6]: section 'nvcc' already exists

I think it has to do with tensorflow being installed since nvcc is a CUDA thing I believe. not sure what to do to fix this. PLEASE HELP!!!

-Rik

**Comment by JesseLivezey** [comment]
Started an answer here:
https://groups.google.com/forum/#!topic/theano-users/i7LDDp5Gbn8
