### ISSUE TITLE
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.AssertionError'>  local_subtensor_merge

### ISSUE THREAD

**Issue by around1991** [Theano/Theano#5107]
Running a theano function in Keras, and I get the following error with optimizer=fast_run. I've just updated to the dev version of Theano (using pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git). The function compiles fine with optimizer=fast_compile.

```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.AssertionError'>  local_subtensor_merge
ERROR (theano.gof.opt): Optimization failure due to: local_subtensor_merge
ERROR (theano.gof.opt): node: Subtensor{:int64:}(Subtensor{::int64}.0, ScalarFromTensor.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1962, in process_node
    remove=remove)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/fg.py", line 508, in replace
    self.change_input(node, i, new_r, reason=reason)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/fg.py", line 450, in change_input
    self.__import_r__(new_r, reason=reason)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/fg.py", line 351, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/fg.py", line 414, in __import__
    self.execute_callbacks('on_import', node, reason)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/fg.py", line 588, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1300, in on_import
    assert r in self.shape_of
AssertionError

Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "seq2seq_vae.py", line 1, in <module>
    import os
  File "seq2seq_vae.py", line 366, in main
    model.train(iter(data_iterator), len(data_iterator), 5, None, None, None)
  File "seq2seq_vae.py", line 346, in train
    nb_val_samples=val_samples_per_epoch)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/src/keras/keras/engine/training.py", line 1313, in fit_generator
    self._make_train_function()
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/src/keras/keras/engine/training.py", line 679, in _make_train_function
    **self._function_kwargs)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/src/keras/keras/backend/theano_backend.py", line 545, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/src/keras/keras/backend/theano_backend.py", line 531, in __init__
    **kwargs)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1458, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 2415, in apply
    lopt_change = self.process_node(fgraph, node, lopt)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1970, in process_node
    self.failure_callback(e, self, repl_pairs, lopt, node)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1821, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/auto/homes/kc391/NNCG_narrative/nn-plots/env/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1807, in warn
    raise exc
AssertionError
```

I can email a function dump if needed.

Thanks
Kris

**Comment by around1991** [comment]
I've done a git bisect: the offending commit seems to be 

```
29e67107e0558ec979be1834df47bf50fb948284 is the first bad commit
commit 29e67107e0558ec979be1834df47bf50fb948284
Author: Frederic Bastien <nouiz@nouiz.org>
Date:   Wed Oct 12 15:27:57 2016 -0400

    Make sure fgraph attribute are always removed from apply node and variables when they aren't in an fgraph anymore.

:040000 040000 52a4c90079cadee7e4ff16f9e77baf440506b659 66272aeab9251fb8dd53628038ad7c51a5c8cc64 M      theano
```

**Comment by nouiz** [comment]
Thanks for the report and investigation.

The change in this PR is related indirectly to the error. Having the
function dump or a way to reproduce the error would really help. Can you
provide that?

**Comment by lamblin** [comment]
@nouiz Considering that `local_subtensor_merge` tries to manually apply some optimizations by calling `pre_constant_merge` and `pre_greedy_local_optimizer`, could it be possible that removing `fgraph` somehow interferes with that?

**Comment by around1991** [comment]
Hi @nouiz 

I've tried calling function_dump, but I get an error, saying that lambda functions can't be pickled. Is there a way around this?

Thanks

**Comment by nouiz** [comment]
We can probably fix it. Do you have the full error message? Most of the
time it don't help. Can you give us a way to reproduce it? It will allow me
to debug both problem.

If it is hard, change the import from cProfile to profile. It is a Python
version, so it will help get better error information. But most of the
time, I need a break point there to find the problem and fix it.

**Comment by nouiz** [comment]
I manually reverted that commit. Can you test to make sure this fix the problem? I'm not sure this is the part of the PR that cause the problem. This will give us more time to investigate a full fix:

https://github.com/Theano/Theano/pull/5126

**Comment by carlthome** [comment]
Same issue here.

**Comment by carlthome** [comment]
And installing the latest Theano on master (e.g. `pip install git+git://github.com/theano/theano --upgrade`) made the error go away. The revert is possibly related as the Theano build I was running that had the bug was only about a week old.

**Comment by nouiz** [comment]
As the regression is fixed, I'll close this issue, but I'll make a new one to implement the original.

As told, we need a way to reproduce the problem.

**Comment by nouiz** [comment]
Thanks to confirm the master for the problem. We still need a way to
reproduce it. The current fix isn't a long term solution.
