### ISSUE TITLE
local_opt_alloc fails to cast its replacement to the original type

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#5140]
There is a bug in `local_opt_alloc`.
According to @lamblin's analysis the op is applying this replacement:

```
sum(alloc(x, *shape)) => prod(shape) * x
```

followed by a cast to the same type as the _input_. It is not immediately clear which cast would be appropriate here though.

Here is the full error:

``` python
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{acc_dtype=int64}.0, Elemwise{mul,n
o_inplace}.0, TensorType(int64, scalar), TensorType(int32, scalar), 'local_opt_alloc') local_opt_alloc
ERROR (theano.gof.opt): Optimization failure due to: local_opt_alloc
ERROR (theano.gof.opt): node: Sum{acc_dtype=int64}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/francesco/exp/theano/theano/gof/opt.py", line 1962, in process_node
    remove=remove)
  File "/home/francesco/exp/theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/francesco/exp/theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/francesco/exp/theano/theano/gof/fg.py", line 480, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{acc_dtype=int64}.0, Elemwise{mul,no_inplace}.0, TensorType(int64, scalar), TensorType(int32, scalar), 'local_opt_alloc')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{acc_dtype=int64}.0, Elemwise{mul,no_inplace}.0, TensorType(int64, scalar), TensorType(int32, scalar), 'local_opt_alloc') local_opt_alloc
ERROR (theano.gof.opt): Optimization failure due to: local_opt_alloc
ERROR (theano.gof.opt): node: Sum{acc_dtype=int64}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/francesco/exp/theano/theano/gof/opt.py", line 1962, in process_node
    remove=remove)
  File "/home/francesco/exp/theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/francesco/exp/theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/francesco/exp/theano/theano/gof/fg.py", line 480, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{acc_dtype=int64}.0, Elemwise{mul,no_inplace}.0, TensorType(int64, scalar), TensorType(int32, scalar
), 'local_opt_alloc')
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{acc_dtype=int64}.0, Elemwise{mul,no_inplace}.0, TensorType(int64, scalar), TensorType(int32, scalar), 'local_opt_alloc') local_opt_alloc
ERROR (theano.gof.opt): Optimization failure due to: local_opt_alloc
ERROR (theano.gof.opt): node: Sum{acc_dtype=int64}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/francesco/exp/theano/theano/gof/opt.py", line 1962, in process_node
    remove=remove)
  File "/home/francesco/exp/theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/francesco/exp/theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/francesco/exp/theano/theano/gof/fg.py", line 480, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{acc_dtype=int64}.0, Elemwise{mul,no_inplace}.0, TensorType(int64, scalar), TensorType(int32, scalar), 'local_opt_alloc')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Sum{acc_dtype=int64}.0, Elemwise{mul,no_inplace}.0, TensorType(int64, scalar), TensorType(int32, scalar), 'local_opt_alloc') local_opt_alloc
ERROR (theano.gof.opt): Optimization failure due to: local_opt_alloc
ERROR (theano.gof.opt): node: Sum{acc_dtype=int64}(Alloc.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/francesco/exp/theano/theano/gof/opt.py", line 1962, in process_node
    remove=remove)
  File "/home/francesco/exp/theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/francesco/exp/theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/francesco/exp/theano/theano/gof/fg.py", line 480, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Sum{acc_dtype=int64}.0, Elemwise{mul,no_inplace}.0, TensorType(int64, scalar), TensorType(int32, scalar), 'local_opt_alloc')
```

**Comment by lamblin** [comment]
I guess that the closest behaviour would be to cast `x` and `prod(shape)` as the `acc_dtype` of the reduction, and then cast the output as the `out_dtype` of the reduction.

**Comment by nouiz** [comment]
There was fix to that opt related to dtype, so it should be fixed.
