### ISSUE TITLE
what is the problems, please.

### ISSUE THREAD

**Issue by gzliuyun** [Theano/Theano#5150]
01102  
D:\Python27\libs/libpython27.a: error adding symbols: File format not recognized
01103       return RETVAL;
collect2.exe: error: ld returned 1 exit status
01104   }

01105  
Problem occurred during compilation with the command line below:
"C:\MinGW\bin\g++.exe" -shared -g -march=ivybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=ivybridge -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m32 -I"D:\Python27\lib\site-packages\numpy\core\include" -I"D:\Python27\include" -I"D:\Python27\lib\site-packages\theano\gof" -L"D:\Python27\libs" -L"D:\Python27" -o C:\Users\Administrator\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.10-32\lazylinker_ext\lazylinker_ext.pyd C:\Users\Administrator\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.10-32\lazylinker_ext\mod.cpp -lpython27
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Predict-linux-interface/aa.py", line 3, in <module>
    import theano
  File "D:\Python27\lib\site-packages\theano__init__.py", line 70, in <module>
    from theano.compile import (
  File "D:\Python27\lib\site-packages\theano\compile__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "D:\Python27\lib\site-packages\theano\compile\function_module.py", line 21, in <module>
    import theano.compile.mode
  File "D:\Python27\lib\site-packages\theano\compile\mode.py", line 10, in <module>
    import theano.gof.vm
  File "D:\Python27\lib\site-packages\theano\gof\vm.py", line 659, in <module>
    from . import lazylinker_c
  File "D:\Python27\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "D:\Python27\lib\site-packages\theano\gof\cmodule.py", line 2323, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
.

**Comment by nouiz** [comment]
Hard to tell for me as I'm not a Windows expert. But it seam you compiled
Python without a shared library. Install anaconda instead. It have a Python
well compiled.
