### ISSUE TITLE
Problem with float16 since #5077

### ISSUE THREAD

**Issue by danielS91** [Theano/Theano#5180]
I just updated to the latest dev version of theano.
Starting with #5077, I can not add Dropout layers to a keras network model when using float16. FloatX is correctly set for both keras and theano.
The version of keras doesn't matter, I tested 1.1.0 and the latest git version.

Code to reproduce the problem:
```python
import theano

from keras.models import Sequential
from keras.layers import Dense, Dropout

model = Sequential()
model.add(Dense(10, activation='linear', input_shape=(5,)))
model.add(Dropout(0.45))
model.add(Dense(2, activation='softmax'))

# print unoptimized graph
theano.printing.debugprint(model.outputs, print_type=True)

model._make_predict_function()


```

Output and error log:
```
Softmax [id A] <TensorType(float16, matrix)> ''   
 |Elemwise{add,no_inplace} [id B] <TensorType(float16, matrix)> ''   
   |dot [id C] <TensorType(float16, matrix)> ''   
   | |Elemwise{switch,no_inplace} [id D] <TensorType(float16, matrix)> ''   
   | | |InplaceDimShuffle{x,x} [id E] <TensorType(uint8, (True, True))> ''   
   | | | |keras_learning_phase [id F] <TensorType(uint8, scalar)>
   | | |Elemwise{true_div,no_inplace} [id G] <TensorType(float16, matrix)> ''   
   | | | |Elemwise{mul,no_inplace} [id H] <TensorType(float16, matrix)> ''   
   | | | | |Elemwise{add,no_inplace} [id I] <TensorType(float16, matrix)> ''   
   | | | | | |dot [id J] <TensorType(float16, matrix)> ''   
   | | | | | | |dense_input_1 [id K] <TensorType(float16, matrix)>
   | | | | | | |HostFromGpu(gpuarray) [id L] <TensorType(float16, matrix)> ''   
   | | | | | |   |dense_1_W [id M] <GpuArrayType<None>(float16, (False, False))>
   | | | | | |InplaceDimShuffle{x,0} [id N] <TensorType(float16, row)> ''   
   | | | | |   |HostFromGpu(gpuarray) [id O] <TensorType(float16, vector)> ''   
   | | | | |     |dense_1_b [id P] <GpuArrayType<None>(float16, (False,))>
   | | | | |Elemwise{Cast{float16}} [id Q] <TensorType(float16, matrix)> ''   
   | | | |   |Elemwise{lt,no_inplace} [id R] <TensorType(bool, matrix)> ''   
   | | | |     |Elemwise{add,no_inplace} [id S] <TensorType(float16, matrix)> ''   
   | | | |     | |Elemwise{mul,no_inplace} [id T] <TensorType(float16, matrix)> ''   
   | | | |     | | |mrg_uniform{TensorType(float16, matrix),no_inplace}.1 [id U] <TensorType(float16, matrix)> ''   
   | | | |     | | | |<GpuArrayType<None>(int32, (False, False))> [id V] <GpuArrayType<None>(int32, (False, False))>
   | | | |     | | | |Shape [id W] <TensorType(int64, vector)> ''   
   | | | |     | | |   |Elemwise{add,no_inplace} [id I] <TensorType(float16, matrix)> ''   
   | | | |     | | |InplaceDimShuffle{x,x} [id X] <TensorType(float16, (True, True))> ''   
   | | | |     | |   |Elemwise{sub,no_inplace} [id Y] <TensorType(float16, scalar)> ''   
   | | | |     | |     |TensorConstant{1.0} [id Z] <TensorType(float16, scalar)>
   | | | |     | |     |TensorConstant{0.0} [id BA] <TensorType(float16, scalar)>
   | | | |     | |InplaceDimShuffle{x,x} [id BB] <TensorType(float16, (True, True))> ''   
   | | | |     |   |TensorConstant{0.0} [id BA] <TensorType(float16, scalar)>
   | | | |     |InplaceDimShuffle{x,x} [id BC] <TensorType(float16, (True, True))> ''   
   | | | |       |TensorConstant{0.5498046875} [id BD] <TensorType(float16, scalar)>
   | | | |InplaceDimShuffle{x,x} [id BE] <TensorType(float16, (True, True))> ''   
   | | |   |TensorConstant{0.5498046875} [id BF] <TensorType(float16, scalar)>
   | | |Elemwise{add,no_inplace} [id I] <TensorType(float16, matrix)> ''   
   | |HostFromGpu(gpuarray) [id BG] <TensorType(float16, matrix)> ''   
   |   |dense_2_W [id BH] <GpuArrayType<None>(float16, (False, False))>
   |InplaceDimShuffle{x,0} [id BI] <TensorType(float16, row)> ''   
     |HostFromGpu(gpuarray) [id BJ] <TensorType(float16, vector)> ''   
       |dense_2_b [id BK] <GpuArrayType<None>(float16, (False,))>
Traceback (most recent call last):
  File "test_model", line 20, in <module>
    model._make_predict_function()
  File "/home/daniel/.local/lib/python2.7/site-packages/keras/engine/training.py", line 734, in _make_predict_function
    **kwargs)
  File "/home/daniel/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 727, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/daniel/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 713, in __init__
    **kwargs)
  File "/home/daniel/.local/Theano/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/daniel/.local/Theano/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/daniel/.local/Theano/theano/compile/function_module.py", line 1783, in orig_function
    output_keys=output_keys).create(
  File "/home/daniel/.local/Theano/theano/compile/function_module.py", line 1465, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/home/daniel/.local/Theano/theano/gof/opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "/home/daniel/.local/Theano/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/daniel/.local/Theano/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/daniel/.local/Theano/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/daniel/.local/Theano/theano/tensor/opt.py", line 7192, in apply
    new_outputs = self.optimizer(node)
  File "/home/daniel/.local/Theano/theano/tensor/opt.py", line 7139, in local_fuse
    ret = local_fuse(n)
  File "/home/daniel/.local/Theano/theano/tensor/opt.py", line 7129, in local_fuse
    assert node.outputs[0].dtype == n.outputs[0].dtype
AssertionError
```
So it's "float16 == float32"

The problem is somehow related to the FusionOptimizer. I will try to further investigate the problem...

**Comment by nouiz** [comment]
Thanks for the report and the small code to reproduce it. I'm able to
reproduce it and I'll continue to look at it today.

**Comment by nouiz** [comment]
I think I have a fix in this PR:

https://github.com/Theano/Theano/pull/5181

**Comment by danielS91** [comment]
#5181 solves the problem. THANKS
