### ISSUE TITLE
Theano crashes when Variable 'owner' attribute is not defined

### ISSUE THREAD

**Issue by andresgottlieb** [Theano/Theano#5195]
I'm using Theano through [PyMC3](https://github.com/pymc-devs/pymc3) and, when working with parallelization, I sometimes get this error:

```
File "/Python/lib/python3.5/site-packages/theano/gof/graph.py", line 670, in expand
   if r.owner and (not blockers or r not in blockers):
AttributeError: 'FreeRV' object has no attribute 'owner'
```

This is apparently because the code in [graph.py line 670](https://github.com/Theano/Theano/blob/master/theano/gof/graph.py#L670):

```python
if r.owner and (not blockers or r not in blockers):
```

crashes when r.owner is not defined.

Should this be corrected to:

```python
if hasattr(r, 'owner') and (not blockers or r not in blockers):
```

Or is it by design that r.owner should always be defined and PyMC3 is doing something wrong?

Thank you,

**Comment by nouiz** [comment]
Normally, all Theano variable should have an owner.

Can you give the fulls stack trace?

**Comment by andresgottlieb** [comment]
Thank you @nouiz, here's the full stack trace:

```
Exception in thread Thread-3:
Traceback (most recent call last):
 File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
   self.run()
 File "/usr/lib/python3.5/threading.py", line 862, in run
   self._target(*self._args, **self._kwargs)
 File "/usr/lib/python3.5/multiprocessing/pool.py", line 429, in _handle_results
   task = get()
 File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
   return ForkingPickler.loads(buf.getbuffer())
 File "/Python/lib/python3.5/site-packages/theano/compile/function_module.py", line 1690, in _constructor_FunctionMaker
   return FunctionMaker(**kwargs)
 File "/Python/lib/python3.5/site-packages/theano/compile/function_module.py", line 1422, in __init__
   [i.update for i in inputs
 File "/Python/lib/python3.5/site-packages/theano/gof/graph.py", line 693, in inputs
   vlist = ancestors(variable_list, blockers)
 File "/Python/lib/python3.5/site-packages/theano/gof/graph.py", line 672, in ancestors
   dfs_variables = stack_search(deque(variable_list), expand, 'dfs')
 File "/Python/lib/python3.5/site-packages/theano/gof/graph.py", line 640, in stack_search
   expand_l = expand(l)
 File "/Python/lib/python3.5/site-packages/theano/gof/graph.py", line 670, in expand
   if r.owner and (not blockers or r not in blockers):
AttributeError: 'FreeRV' object has no attribute 'owner'
```

**Comment by nouiz** [comment]
I don't undertand how this could happen that the object don't have an owner
field.

Do you have this in a deterministic way or not? Is it easy to reproduce?

Do you use multiple different computer? Can you make sure they use the same
Theano version?

**Comment by andresgottlieb** [comment]
After deeper debugging, I'm quite convinced the problem has nothing to do with a problem with Theano, so I'm closing this issue. Thank you!
