### ISSUE TITLE
tensor conj() execute error on GPU

### ISSUE THREAD

**Issue by shiretzet** [Theano/Theano#5233]
Hi,

I'm using conj() inside scan "loop".
Running tensor conj() on CPU works fine.
Running on GPU throws the following error:
``` python
Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 4008)
1 #include <Python.h>
2 #include <iostream>
3 #include "theano_mod_helper.h"
4 #include "cuda_ndarray.cuh"
5 //////////////////////
6 ////  Support Code
7 //////////////////////
8 
9 
10     namespace {
11     struct __struct_compiled_op_meb173dd48882f5afc4154fb0624ff299 {
12         PyObject* __ERROR;
13 
14         PyObject* storage_V3;
15 PyObject* storage_V1;
16         
17 
18         __struct_compiled_op_meb173dd48882f5afc4154fb0624ff299() {
19             // This is only somewhat safe because we:
20             //  1) Are not a virtual class
21             //  2) Do not use any virtual classes in the members
22             //  3) Deal with mostly POD and pointers
23 
24             // If this changes, we would have to revise this, but for
25             // now I am tired of chasing segfaults because
26             // initialization code had an error and some pointer has
27             // a junk value.
28             memset(this, 0, sizeof(*this));
29         }
30         ~__struct_compiled_op_meb173dd48882f5afc4154fb0624ff299(void) {
31             cleanup();
32         }
33 
34         int init(PyObject* __ERROR, PyObject* storage_V3, PyObject* storage_V1) {
35             Py_XINCREF(storage_V3);
36 Py_XINCREF(storage_V1);
37             this->storage_V3 = storage_V3;
38 this->storage_V1 = storage_V1;
39             
40 
41 
42 
43             this->__ERROR = __ERROR;
44             return 0;
45         }
46         void cleanup(void) {
47             __label_1:
48 
49 double __DUMMY_1;
50 __label_3:
51 
52 double __DUMMY_3;
53 __label_6:
54 
55 double __DUMMY_6;
56 
57             Py_XDECREF(this->storage_V3);
58 Py_XDECREF(this->storage_V1);
59         }
60         int run(void) {
61             int __failure = 0;
62             
63     PyObject* py_V1;
64      CudaNdarray * V1;
65     PyObject* py_V3;
66      CudaNdarray * V3;
67 {
68 
69     py_V1 = PyList_GET_ITEM(storage_V1, 0);
70     {Py_XINCREF(py_V1);}
71     
72         if (py_V1 == Py_None)
73         {
74             V1 = NULL;
75         }
76         else
77         {
78             
79         assert(py_V1->ob_refcnt >= 2); // There should be at least one ref from the container object,
80         // and one ref from the local scope.
81 
82         if (CudaNdarray_Check(py_V1))
83         {
84             //fprintf(stderr, "c_extract CNDA object w refcnt %p %i\n", py_V1, (py_V1->ob_refcnt));
85             V1 = (CudaNdarray*)py_V1;
86             //std::cerr << "c_extract " << V1 << '\n';
87         
88 
89                 if (V1->nd != 2)
90                 {
91                     PyErr_Format(PyExc_RuntimeError,
92                                  "c_extract: Some CudaNdarray has rank %i, it was supposed to have rank 2",
93                                  V1->nd);
94                     V1 = NULL;
95                     {
96         __failure = 2;
97         if (!PyErr_Occurred()) {
98             PyErr_SetString(PyExc_RuntimeError,
99                 "Unexpected error in an Op's C code. "
100                 "No Python exception was set.");
101             }
102         goto __label_2;};
103                 }
104                 //std::cerr << "c_extract " << V1 << " nd check passed\n";
105             
106 
107                 assert(V1);
108                 Py_INCREF(py_V1);
109             }
110             else if (py_V1 == Py_None)
111             {
112                 PyErr_SetString(PyExc_TypeError,
113                                 "expected a CudaNdarray, not None");
114                 V1 = NULL;
115                 {
116         __failure = 2;
117         if (!PyErr_Occurred()) {
118             PyErr_SetString(PyExc_RuntimeError,
119                 "Unexpected error in an Op's C code. "
120                 "No Python exception was set.");
121             }
122         goto __label_2;};
123             }
124             else
125             {
126                 //fprintf(stderr, "FAILING c_extract CNDA object w refcnt %p %i\n", py_V1, (py_V1->ob_refcnt));
127                 PyErr_SetString(PyExc_TypeError, "Argument not a CudaNdarray");
128                 V1 = NULL;
129                 {
130         __failure = 2;
131         if (!PyErr_Occurred()) {
132             PyErr_SetString(PyExc_RuntimeError,
133                 "Unexpected error in an Op's C code. "
134                 "No Python exception was set.");
135             }
136         goto __label_2;};
137             }
138             //std::cerr << "c_extract done " << V1 << '\n';
139             
140 
141         }
142         
143 {
144 
145     py_V3 = PyList_GET_ITEM(storage_V3, 0);
146     {Py_XINCREF(py_V3);}
147     
148         assert(py_V3->ob_refcnt >= 2); // There should be at least one ref from the container object,
149         // and one ref from the local scope.
150 
151         if (CudaNdarray_Check(py_V3))
152         {
153             //fprintf(stderr, "c_extract CNDA object w refcnt %p %i\n", py_V3, (py_V3->ob_refcnt));
154             V3 = (CudaNdarray*)py_V3;
155             //std::cerr << "c_extract " << V3 << '\n';
156         
157 
158                 if (V3->nd != 2)
159                 {
160                     PyErr_Format(PyExc_RuntimeError,
161                                  "c_extract: Some CudaNdarray has rank %i, it was supposed to have rank 2",
162                                  V3->nd);
163                     V3 = NULL;
164                     {
165         __failure = 4;
166         if (!PyErr_Occurred()) {
167             PyErr_SetString(PyExc_RuntimeError,
168                 "Unexpected error in an Op's C code. "
169                 "No Python exception was set.");
170             }
171         goto __label_4;};
172                 }
173                 //std::cerr << "c_extract " << V3 << " nd check passed\n";
174             
175 
176                 assert(V3);
177                 Py_INCREF(py_V3);
178             }
179             else if (py_V3 == Py_None)
180             {
181                 PyErr_SetString(PyExc_TypeError,
182                                 "expected a CudaNdarray, not None");
183                 V3 = NULL;
184                 {
185         __failure = 4;
186         if (!PyErr_Occurred()) {
187             PyErr_SetString(PyExc_RuntimeError,
188                 "Unexpected error in an Op's C code. "
189                 "No Python exception was set.");
190             }
191         goto __label_4;};
192             }
193             else
194             {
195                 //fprintf(stderr, "FAILING c_extract CNDA object w refcnt %p %i\n", py_V3, (py_V3->ob_refcnt));
196                 PyErr_SetString(PyExc_TypeError, "Argument not a CudaNdarray");
197                 V3 = NULL;
198                 {
199         __failure = 4;
200         if (!PyErr_Occurred()) {
201             PyErr_SetString(PyExc_RuntimeError,
202                 "Unexpected error in an Op's C code. "
203                 "No Python exception was set.");
204             }
205         goto __label_4;};
206             }
207             //std::cerr << "c_extract done " << V3 << '\n';
208             
209 
210 {
211 // Op class GpuElemwise
212 
213         //std::cerr << "C_CODE conj START\n";
214         //standard elemwise size checks
215             
216 
217             int dims[2] = {1,1};
218             
219 
220                 int broadcasts_V3[2] = {0, 0};
221                 
222 
223         //std::cerr << "C_CODE conj checking input V3\n";
224         if (2 != V3->nd)
225         {
226             PyErr_Format(PyExc_TypeError,
227                          "need 2 dims, not %i", V3->nd);
228             {
229         __failure = 5;
230         if (!PyErr_Occurred()) {
231             PyErr_SetString(PyExc_RuntimeError,
232                 "Unexpected error in an Op's C code. "
233                 "No Python exception was set.");
234             }
235         goto __label_5;};
236         }
237         for (int i = 0; i< 2; ++i)
238         {
239             dims[i] = (dims[i] == 1) ? CudaNdarray_HOST_DIMS(V3)[i] : dims[i];
240             if ((!(broadcasts_V3[i] &&
241                  CudaNdarray_HOST_DIMS(V3)[i] == 1)) &&
242                 (dims[i] != CudaNdarray_HOST_DIMS(V3)[i]))
243             {
244                 //std::cerr << "C_CODE conj checking input V3 failed\n";
245                 PyErr_Format(PyExc_ValueError,
246                              "GpuElemwise. Input dimension mis-match. Input"
247                              " 0 (indices start at 0) has shape[%i] == %i"
248                              ", but the output's size on that axis is %i.",
249                              i,
250                              CudaNdarray_HOST_DIMS(V3)[i],
251                              dims[i]
252                             );
253                 {
254         __failure = 5;
255         if (!PyErr_Occurred()) {
256             PyErr_SetString(PyExc_RuntimeError,
257                 "Unexpected error in an Op's C code. "
258                 "No Python exception was set.");
259             }
260         goto __label_5;};
261             }
262         }
263             
264 
265         for (int i = 0; (i< 2) && (V1); ++i) {
266             if (dims[i] != CudaNdarray_HOST_DIMS(V1)[i])
267             {
268                 Py_DECREF(V1);
269                 V1 = NULL;
270             }
271         }
272         if (V1 && !CudaNdarray_is_c_contiguous(V1))
273         {
274             Py_XDECREF(V1);
275             V1 = NULL;
276         }
277         if (NULL == V1)
278         {
279             V1 = (CudaNdarray*)CudaNdarray_New();
280             if (!V1)
281             {
282                 //error string already set
283                 {
284         __failure = 5;
285         if (!PyErr_Occurred()) {
286             PyErr_SetString(PyExc_RuntimeError,
287                 "Unexpected error in an Op's C code. "
288                 "No Python exception was set.");
289             }
290         goto __label_5;};
291             }
292             if (CudaNdarray_alloc_contiguous(V1, 2, dims))
293             {
294                 //error string already set
295                 Py_DECREF(V1);
296                 V1 = NULL;
297                 {
298         __failure = 5;
299         if (!PyErr_Occurred()) {
300             PyErr_SetString(PyExc_RuntimeError,
301                 "Unexpected error in an Op's C code. "
302                 "No Python exception was set.");
303             }
304         goto __label_5;};
305             }
306         }
307         //std::cerr << "ELEMWISE NEW V1 nd" << V1->nd << "\n";
308         //std::cerr << "ELEMWISE NEW V1 data" << V1->devdata << "\n";
309         
310 
311         {
312             //new block so that failure gotos don't skip over variable initialization
313             //std::cerr << "calling callkernel\n";
314             if (callkernel_node_meb173dd48882f5afc4154fb0624ff299_0(1, 0, dims
315             
316 
317                         , CudaNdarray_DEV_DATA(V3), CudaNdarray_HOST_STRIDES(V3)
318             
319 
320                         , CudaNdarray_DEV_DATA(V1), CudaNdarray_HOST_STRIDES(V1)
321             
322 
323                         ))
324             {
325                  // error
326             
327 
328                 Py_DECREF(V1);
329                 V1 = NULL;
330                 
331 
332                 {
333         __failure = 5;
334         if (!PyErr_Occurred()) {
335             PyErr_SetString(PyExc_RuntimeError,
336                 "Unexpected error in an Op's C code. "
337                 "No Python exception was set.");
338             }
339         goto __label_5;};
340             }
341             else // no error
342             {
343             }
344         }
345         //std::cerr << "C_CODE conj END\n";
346         
347 __label_5:
348 
349 double __DUMMY_5;
350 
351 }
352 __label_4:
353 
354         //std::cerr << "cleanup " << py_V3 << " " << V3 << "\n";
355         //fprintf(stderr, "c_cleanup CNDA py_object w refcnt %p %i\n", py_V3, (py_V3->ob_refcnt));
356         if (V3)
357         {
358             //fprintf(stderr, "c_cleanup CNDA cn_object w refcnt %p %i\n", V3, (V3->ob_refcnt));
359             Py_XDECREF(V3);
360         }
361         //std::cerr << "cleanup done" << py_V3 << "\n";
362         
363     {Py_XDECREF(py_V3);}
364     
365 double __DUMMY_4;
366 
367 }
368 __label_2:
369 
370     if (!__failure) {
371       
372         //std::cerr << "sync\n";
373         if (NULL == V1) {
374             // failure: sync None to storage
375             Py_XDECREF(py_V1);
376             py_V1 = Py_None;
377             Py_INCREF(py_V1);
378         }
379         else
380         {
381             if (py_V1 != (PyObject*)V1)
382             {
383                 Py_XDECREF(py_V1);
384                 py_V1 = (PyObject*)V1;
385                 Py_INCREF(py_V1);
386             }
387             assert(py_V1->ob_refcnt);
388         }
389         
390       PyObject* old = PyList_GET_ITEM(storage_V1, 0);
391       {Py_XINCREF(py_V1);}
392       PyList_SET_ITEM(storage_V1, 0, py_V1);
393       {Py_XDECREF(old);}
394     }
395     
396         //std::cerr << "cleanup " << py_V1 << " " << V1 << "\n";
397         //fprintf(stderr, "c_cleanup CNDA py_object w refcnt %p %i\n", py_V1, (py_V1->ob_refcnt));
398         if (V1)
399         {
400             //fprintf(stderr, "c_cleanup CNDA cn_object w refcnt %p %i\n", V1, (V1->ob_refcnt));
401             Py_XDECREF(V1);
402         }
403         //std::cerr << "cleanup done" << py_V1 << "\n";
404         
405     {Py_XDECREF(py_V1);}
406     
407 double __DUMMY_2;
408 
409 }
410 
411             
412         if (__failure) {
413             // When there is a failure, this code puts the exception
414             // in __ERROR.
415             PyObject* err_type = NULL;
416             PyObject* err_msg = NULL;
417             PyObject* err_traceback = NULL;
418             PyErr_Fetch(&err_type, &err_msg, &err_traceback);
419             if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}
420             if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}
421             if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}
422             PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);
423             PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);
424             PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);
425             PyList_SET_ITEM(__ERROR, 0, err_type);
426             PyList_SET_ITEM(__ERROR, 1, err_msg);
427             PyList_SET_ITEM(__ERROR, 2, err_traceback);
428             {Py_XDECREF(old_err_type);}
429             {Py_XDECREF(old_err_msg);}
430             {Py_XDECREF(old_err_traceback);}
431         }
432         // The failure code is returned to index what code block failed.
433         return __failure;
434         
435         }
436     };
437     }
438     
439 
440         static int __struct_compiled_op_meb173dd48882f5afc4154fb0624ff299_executor(__struct_compiled_op_meb173dd48882f5afc4154fb0624ff299 *self) {
441             return self->run();
442         }
443 
444         static void __struct_compiled_op_meb173dd48882f5afc4154fb0624ff299_destructor(PyObject *capsule) {
445             __struct_compiled_op_meb173dd48882f5afc4154fb0624ff299 *self = (__struct_compiled_op_meb173dd48882f5afc4154fb0624ff299 *)PyCapsule_GetContext(capsule);
446             delete self;
447         }
448         
449 //////////////////////
450 ////  Functions
451 //////////////////////
452 static PyObject * instantiate(PyObject * self, PyObject *argtuple) {
453   assert(PyTuple_Check(argtuple));
454   if (3 != PyTuple_Size(argtuple)){ 
455      PyErr_Format(PyExc_TypeError, "Wrong number of arguments, expected 3, got %i", (int)PyTuple_Size(argtuple));
456      return NULL;
457   }
458   __struct_compiled_op_meb173dd48882f5afc4154fb0624ff299* struct_ptr = new __struct_compiled_op_meb173dd48882f5afc4154fb0624ff299();
459   if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1),PyTuple_GET_ITEM(argtuple, 2) ) != 0) {
460     delete struct_ptr;
461     return NULL;
462   }
463     PyObject* thunk = PyCapsule_New((void*)(&__struct_compiled_op_meb173dd48882f5afc4154fb0624ff299_executor), NULL, __struct_compiled_op_meb173dd48882f5afc4154fb0624ff299_destructor);
464     if (thunk != NULL && PyCapsule_SetContext(thunk, struct_ptr) != 0) {
465         PyErr_Clear();
466         Py_DECREF(thunk);
467         thunk = NULL;
468     }
469 
470   return thunk; }
471 
472 //////////////////////
473 ////  Module init
474 //////////////////////
475 static PyMethodDef MyMethods[] = {
476 	{"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
477 	{NULL, NULL, 0, NULL}
478 };
479 static struct PyModuleDef moduledef = {
480       PyModuleDef_HEAD_INIT,
481       "meb173dd48882f5afc4154fb0624ff299",
482       NULL,
483       -1,
484       MyMethods,
485 };
486 
487 PyMODINIT_FUNC PyInit_meb173dd48882f5afc4154fb0624ff299(void) {
488     PyObject *m = PyModule_Create(&moduledef);
489     return m;
490 }
491 
===============================
In file included from mod.cu:4:0:
/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:17:0: warning: "PyString_Check" redefined [enabled by default]
 #define PyString_Check PyUnicode_Check
 ^
In file included from /usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                 from mod.cu:4:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:63:0: note: this is the location of the previous definition
 #define PyString_Check PyBytes_Check
 ^
In file included from mod.cu:4:0:
/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:18:0: warning: "PyString_FromString" redefined [enabled by default]
 #define PyString_FromString PyUnicode_FromString
 ^
In file included from /usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                 from mod.cu:4:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:65:0: note: this is the location of the previous definition
 #define PyString_FromString PyBytes_FromString
 ^
In file included from mod.cu:4:0:
/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:19:0: warning: "PyString_AsString" redefined [enabled by default]
 #define PyString_AsString PyUnicode_AsUTF8
 ^
In file included from /usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                 from mod.cu:4:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:72:0: note: this is the location of the previous definition
 #define PyString_AsString PyBytes_AsString
 ^
In file included from mod.cu:4:0:
/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:20:0: warning: "PyString_FromStringAndSize" redefined [enabled by default]
 #define PyString_FromStringAndSize PyUnicode_FromStringAndSize
 ^
In file included from /usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                 from mod.cu:4:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:66:0: note: this is the location of the previous definition
 #define PyString_FromStringAndSize PyBytes_FromStringAndSize
 ^
In file included from mod.cu:4:0:
/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:21:0: warning: "PyString_Size" redefined [enabled by default]
 #define PyString_Size PyUnicode_GET_SIZE
 ^
In file included from /usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                 from mod.cu:4:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:74:0: note: this is the location of the previous definition
 #define PyString_Size PyBytes_Size
 ^
mod.cu(314): error: identifier "callkernel_node_meb173dd48882f5afc4154fb0624ff299_0" is undefined
1 error detected in the compilation of "/tmp/tmpxft_000008dc_00000000-9_mod.cpp1.ii".

['nvcc', '-shared', '-O3', '--maxrregcount=32', '-use_fast_math', '-arch=sm_52', '-m64', '-Xcompiler', '-fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.3-64/cuda_ndarray', '-I/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.3-64/cuda_ndarray', '-I/usr/local/cuda/include', '-I/usr/local/lib/python3.4/dist-packages/numpy/core/include', '-I/usr/include/python3.4m', '-I/usr/local/lib/python3.4/dist-packages/theano/gof', '-I/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda', '-o', '/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.3-64/tmp0ng77wu1/meb173dd48882f5afc4154fb0624ff299.so', 'mod.cu', '-L/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.3-64/cuda_ndarray', '-L/usr/lib', '-lcudart', '-lcublas', '-lcuda_ndarray', '-lpython3.4m']
Traceback (most recent call last):
  File "theano_corr.py", line 147, in <module>
    my_pca = theano.function(inputs=[part1, part2, mins1, maxs1], outputs=pca_out)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/usr/local/lib/python3.4/dist-packages/theano/scan_module/scan_op.py", line 856, in make_thunk
    on_unused_input='ignore')
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/nvcc_compiler.py", line 399, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', for{gpu,scan_fn}(Elemwise{Cast{int64}}.0, Elemwise{add,no_inplace}.0, Elemwise{lt,no_inplace}.0, Elemwise{sub,no_inplace}.0, Elemwise{sub,no_inplace}.0, Elemwise{Sub}[(0, 1)].0, Elemwise{Composite{AND(GE(i0, i1), LT(i0, i2))}}.0, Elemwise{Composite{OR(LT(i0, i1), GT(i0, i2))}}.0, Elemwise{Cast{int64}}.0, GpuFromHost.0, GpuFromHost.0, ScalarFromTensor.0, ScalarFromTensor.0), '\n', 'The following error happened while compiling the node', GpuElemwise{conj,no_inplace}(GpuDimShuffle{1,0}.0), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 --maxrregcount=32 -use_fast_math -arch=sm_52 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.3-64/cuda_ndarray -I/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.3-64/cuda_ndarray -I/usr/local/cuda/include -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -I/usr/local/lib/python3.4/dist-packages/theano/gof -I/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda -o /root/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.3-64/tmp0ng77wu1/meb173dd48882f5afc4154fb0624ff299.so mod.cu -L/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.3-64/cuda_ndarray -L/usr/lib -lcudart -lcublas -lcuda_ndarray -lpython3.4m', '[GpuElemwise{conj,no_inplace}(<CudaNdarrayType(float32, matrix)>)]')
```

**Comment by Sentient07** [comment]
Let @nouiz confirm this, but while creating a new OP, you shouldn't do it in the old backend. We'd be dropping the support soon. You should have it in the new backend ( inside `gpuarray/`). You can refer here : http://deeplearning.net/software/theano_versions/dev/extending/extending_theano_gpu.html

**Comment by shiretzet** [comment]
well the only thing i did was ```T.conj()```

nothing more

**Comment by Sentient07** [comment]
Oh, my bad. I thought the C code that was in your comment was the Op's GPU version's C code. Do you have a PR/ could share the code somewhere ?

**Comment by shiretzet** [comment]
Sure, as simple as that:
``` python
import theano.tensor as T
import theano.sandbox.cuda
theano.sandbox.cuda.use("gpu0")

m = T.fmatrix('m')

def test_conj(idx,matrix):
    return T.conj(matrix)

out, _ =theano.scan(fn=test_conj,sequences=T.arange(1,10,1), non_sequences=[m])

func = theano.function(inputs=[m], outputs=[out])
```

if i comment-out ```#theano.sandbox.cuda.use("gpu0")``` it works (i.e. CPU)

(Needless to say that everything else works fine on GPU)

**Comment by nouiz** [comment]
Thanks for the report.

Note, conj on non-complex is the identity. But I still fixed it in this PR:

https://github.com/Theano/Theano/pull/5244

In the mean time, you can just don't call conj on non-complex or use this
pR.
