### ISSUE TITLE
Error while testing `test_printing` 

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#5236]
On current master, I see this error while i'm testing the `printing` module. 
```
F..........
======================================================================
FAIL: This is a REALLY PARTIAL TEST.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/Ramana/projects/theano/Theano/theano/tests/test_printing.py", line 86, in test_pydotprint_variables
    theano.printing.pydotprint_variables(x * 2)
  File "/Users/Ramana/projects/theano/Theano/theano/printing.py", line 1232, in pydotprint_variables
    g.write(outfile, prog='dot', format=format)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/pydot.py", line 1774, in write
    s = self.create(prog, format)
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/pydot.py", line 1900, in create
    assert p.returncode == 0, p.returncode
AssertionError: 1
-------------------- >> begin captured stdout << ---------------------
The output file is available at /Users/Ramana/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.10-64/theano.pydotprint.cpu.png
['dot', '-Tpng', '/var/folders/x1/c4s7h8yx2x1dddqrdxjlbfvh0000gn/T/tmpilUH_P'] return code: 1

stdout, stderr:
 
Error: /var/folders/x1/c4s7h8yx2x1dddqrdxjlbfvh0000gn/T/tmpilUH_P: syntax error in line 8 near ']'



--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 13 tests in 21.305s

FAILED (failures=1)
```

**Comment by Sentient07** [comment]
Not sure how travis skipped this. I fixed this by myself. https://github.com/Theano/Theano/pull/5237

**Comment by nouiz** [comment]
Ok, as told in the PR, this is only with old code that is deprecated. I would remove that.

**Comment by Sentient07** [comment]
Fixed in https://github.com/Theano/Theano/pull/5237
