### ISSUE TITLE
tensor.diag for gpuarray backend

### ISSUE THREAD

**Issue by trungnt13** [Theano/Theano#5260]
I think there is no implementation for _T.diag_ in new _gpuarray_ backend
```python
from __future__ import print_function, division, absolute_import

import os
os.environ['THEANO_FLAGS'] = 'device=cuda,floatX=float32,exception_verbosity=high'

import numpy as np

import theano
from theano import tensor as T


X = theano.shared(np.random.rand(8, 12).astype('float32'), name='X')
y = T.diag(X)
print(y.eval())
```

And the log:

```
Mapped name None to device cuda: GeForce GTX TITAN X
Using cuDNN version 5105 on context None
Traceback (most recent call last):
  File "tmp5.py", line 14, in <module>
    print(y.eval())
  File "/home/trung/miniconda2/envs/ai/lib/python2.7/site-packages/theano/gof/graph.py", line 519, in eval
    rval = self._fn_cache[inputs](*args)
  File "/home/trung/miniconda2/envs/ai/lib/python2.7/site-packages/theano/compile/function_module.py", line 886, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/trung/miniconda2/envs/ai/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/trung/miniconda2/envs/ai/lib/python2.7/site-packages/theano/compile/function_module.py", line 873, in __call__
    self.fn() if output_subset is None else\
  File "/home/trung/miniconda2/envs/ai/lib/python2.7/site-packages/theano/gof/op.py", line 861, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/trung/miniconda2/envs/ai/lib/python2.7/site-packages/theano/tensor/nlinalg.py", line 212, in perform
    rval.strides = (x.strides[0] + x.strides[1],)
AttributeError: attribute 'strides' of 'pygpu.gpuarray.GpuArray' objects is not writable
Apply node that caused the error: ExtractDiag{view=False}(X)
Toposort index: 0
Inputs types: [GpuArrayType<None>(float32, (False, False))]
Inputs shapes: [(8, 12)]
Inputs strides: [(48, 4)]
Inputs values: ['not shown']
Inputs type_num: [11]
Outputs clients: [['output']]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "tmp5.py", line 13, in <module>
    y = T.diag(X)

Debugprint of the apply node: 
ExtractDiag{view=False} [id A] <GpuArrayType<None>(float32, (False,))> ''   
 |X [id B] <GpuArrayType<None>(float32, (False, False))>

Storage map footprint:
 - X, Shared Input, Shape: (8, 12), ElemSize: 4 Byte(s), TotalSize: 384 Byte(s)
 TotalSize: 384 Byte(s) 0.000 GB
 TotalSize inputs: 384 Byte(s) 0.000 GB
```

**Comment by Sentient07** [comment]
Yes, this is a known error and you have reported this previously.  https://github.com/Theano/Theano/issues/4679

**Comment by nouiz** [comment]
closing as duplicate. Note, we have a PR in libgpuarray that will allow to fix this. So it should work "shortly": https://github.com/Theano/libgpuarray/pull/291
