### ISSUE TITLE
commit 7455188 causes ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, True, False), (0, 'x', 1, 'x')))

### ISSUE THREAD

**Issue by Spaak** [Theano/Theano#5273]
On commit 810e4c8, my PyMC3-based code (using variational inference) still worked fine, but on commit 7455188, this breaks with the stack trace pasted below. As far as I can check this is not a PyMC3 error, since simply reverting to 810e4c8 solves the issue.

```
    params = mc.variational.advi(n=1000, learning_rate=1, start=model.test_point)
  File "/home/eelke/repos/pymc3/pymc3/variational/advi.py", line 139, in advi
    updates = optimizer(loss=-1 * elbo, param=[uw_shared])
  File "/home/eelke/repos/pymc3/pymc3/variational/advi.py", line 257, in optimizer
    grad = tt.grad(loss, param_)
  File "/home/eelke/repos/Theano/theano/gradient.py", line 553, in grad
    grad_dict, wrt, cost_name)
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1317, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1317, in <listcomp>
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1106, in access_term_cache
    new_output_grads)
  File "/home/eelke/repos/Theano/theano/gof/op.py", line 700, in L_op
    return self.grad(inputs, output_grads)
  File "/home/eelke/repos/Theano/theano/tensor/elemwise.py", line 717, in grad
    sr = sr.dimshuffle(shuffle)
  File "/home/eelke/repos/Theano/theano/tensor/var.py", line 363, in dimshuffle
    pattern)
  File "/home/eelke/repos/Theano/theano/tensor/elemwise.py", line 175, in __init__
    (input_broadcastable, new_order))
ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, True, False), (0, 'x', 1, 'x')))
```

**Comment by nouiz** [comment]
Thanks for the report and finding the commit that introduced this.

Can you easily share code that reproduce this? I wasn't able to easily reproduce this.

**Comment by nouiz** [comment]
I think this diff would fix the problem, but being able to make a test of this would be great:

```
diff --git a/theano/tensor/elemwise.py b/theano/tensor/elemwise.py
index a96fe7c..96e6436 100755
--- a/theano/tensor/elemwise.py
+++ b/theano/tensor/elemwise.py
@@ -703,19 +703,8 @@ second dimension
                       if bcast and not outs[0].broadcastable[j]]
 
             if to_sum:
-                shuffle = []
-                j = 0
-                for bcast in ipt.type.broadcastable:
-                    if bcast == 1:
-                        shuffle.append('x')
-                    else:
-                        shuffle.append(j)
-                        j += 1
-                    # close if
-                # close for
-                sr = Sum(axis=to_sum)(rval[i])
-                sr = sr.dimshuffle(shuffle)
-                # sr = DimShuffle(sr.type.broadcastable, shuffle)(sr)
+                sr = theano.tensor.basic.sum(
+                    rval[i], axis=to_sum, keepdims=True)
                 rval[i] = sr
             # close if
         # close for
```
if sharing the code is hard, can you try this diff?

**Comment by nouiz** [comment]
We merged my cleanup/try to fix this issue. But we still don't have a test
for it, so if you help us make one, it would be great.

To make it easy for you to give us the information we need to reproduce the
problem, I made a diff that if you apply manually, would the extra
information we need. Can you update Theano to a version that have the
problem, manually apply the diff bellow and send us the new full error
message with the extra printing? With this, I'll be able to make a test.

```
diff --git a/theano/gradient.py b/theano/gradient.py
index 7d21be4..5fc1171 100644
--- a/theano/gradient.py
+++ b/theano/gradient.py
@@ -1101,9 +1101,16 @@ def _populate_grad_dict(var_to_app_to_idx,
                                 "Got a gradient of shape " +
                                 str(o_shape) + " on an output of shape " +
                                 str(g_shape))
-
-                input_grads = node.op.L_op(inputs, node.outputs,
-                                           new_output_grads)
+                try:
+                    input_grads = node.op.L_op(inputs, node.outputs,
+                                               new_output_grads)
+                except ValueError:
+                    print(inputs)
+                    print(node.outputs)
+                    print(new_output_grads)
+                    print([i.type for i in inputs])
+                    print([i.type for i in node.outputs])
+                    print([i.type for i in new_output_grads])

                 if input_grads is None:
                     raise TypeError("%s.grad returned NoneType, "
```

thanks

**Comment by Spaak** [comment]
OK I applied the diff and ran the code, giving:

```
[Elemwise{add,no_inplace}.0, Elemwise{mul,no_inplace}.0]
[Elemwise{add,no_inplace}.0]
[Elemwise{add,no_inplace}.0]
[TensorType(float64, (True, False, False, False)), TensorType(float64, (True, True, False, False))]
[TensorType(float64, (True, False, False, False))]
[TensorType(float64, (True, False, False, False))]
Traceback (most recent call last):
...
run_delay_fixation_pooled_advi
    params = mc.variational.advi(n=1000, learning_rate=1, start=model.test_point)
  File "/home/eelke/repos/pymc3/pymc3/variational/advi.py", line 139, in advi
    updates = optimizer(loss=-1 * elbo, param=[uw_shared])
  File "/home/eelke/repos/pymc3/pymc3/variational/advi.py", line 257, in optimizer
    grad = tt.grad(loss, param_)
  File "/home/eelke/repos/Theano/theano/gradient.py", line 553, in grad
    grad_dict, wrt, cost_name)
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1324, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1324, in <listcomp>
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 965, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/eelke/repos/Theano/theano/gradient.py", line 1115, in access_term_cache
    if input_grads is None:
UnboundLocalError: local variable 'input_grads' referenced before assignment
```

**Comment by Sentient07** [comment]
@Spaak Could you please empty initialize the `input_grads` list before the `try` block and try that diff?

**Comment by Spaak** [comment]
@Sentient07, yes I will, but currently running a probably very long computation so this will not be until tomorrow. Meanwhile, I assumed it didn't really matter for this particular diff, since all the `print` calls in the `except` block don't depend on `input_grads` and were executed anyway (the output of which is above the stack trace).

**Comment by nouiz** [comment]
Thanks. I was able to reproduce the error. The PR we merged fix the
problem, so if you update Theano the error won't be there anymore.

I'll add a test for this case in a futur PR.
