### ISSUE TITLE
Weird compile error on isnan

### ISSUE THREAD

**Issue by twiecki** [Theano/Theano#5280]
```
======================================================================
ERROR: test_poisson_mixture (pymc3.tests.test_mixture.TestMixture)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wiecki/working/projects/pymc/pymc3/tests/test_mixture.py", line 84, in test_poisson_mixture
    x_obs = Mixture('x_obs', w, Poisson.dist(mu), observed=self.pois_x)
  File "/home/wiecki/working/projects/pymc/pymc3/distributions/distribution.py", line 26, in __new__
    dist = cls.dist(*args, **kwargs)
  File "/home/wiecki/working/projects/pymc/pymc3/distributions/distribution.py", line 39, in dist
    dist.__init__(*args, **kwargs)
  File "/home/wiecki/working/projects/pymc/pymc3/distributions/mixture.py", line 64, in __init__
    comp_mode_logps = self.logp(comp_modes)
  File "/home/wiecki/working/projects/pymc/pymc3/distributions/mixture.py", line 113, in logp
    w >= 0, w <= 1, tt.allclose(w.sum(axis=-1), 1))
  File "/home/wiecki/tools/theano/theano/tensor/basic.py", line 1865, in allclose
    return all(isclose(a, b, rtol, atol, equal_nan))
  File "/home/wiecki/tools/theano/theano/tensor/basic.py", line 1943, in isclose
    b_nan = isnan(b)
  File "/home/wiecki/tools/theano/theano/gof/op.py", line 659, in __call__
    no_recycling=[])
  File "/home/wiecki/tools/theano/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/home/wiecki/tools/theano/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/wiecki/tools/theano/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/wiecki/tools/theano/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/wiecki/tools/theano/theano/gof/cc.py", line 1589, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/wiecki/tools/theano/theano/gof/cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/wiecki/tools/theano/theano/gof/cc.py", line 1492, in compile_cmodule
    preargs=preargs)
  File "/home/wiecki/tools/theano/theano/gof/cmodule.py", line 2323, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): In file included from /home/wiecki/miniconda3/include/python3.5m/pyport.h:328:0,.                  from /home/wiecki/miniconda3/include/python3.5m/Python.h:50,.                  from /home/wiecki/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmphjy_f0a9/mod.cpp:1:. /home/wiecki/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmphjy_f0a9/mod.cpp: In member function ‘int {anonymous}::__struct_compiled_op_ma603dd4b312cefd3d55365bd3cfb46da::run()’:. /home/wiecki/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmphjy_f0a9/mod.cpp:309:30: error: non-floating-point argument in call to function ‘__builtin_isnan’.                    V1_i = abs(isnan(V3_i));.                               ^. ', '[Elemwise{isnan,no_inplace}(TensorConstant{1})]')
-------------------- >> begin captured stdout << ---------------------
===============================
===============================
In file included from /home/wiecki/miniconda3/include/python3.5m/pyport.h:328:0,
                 from /home/wiecki/miniconda3/include/python3.5m/Python.h:50,
                 from /home/wiecki/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmphjy_f0a9/mod.cpp:1:
/home/wiecki/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmphjy_f0a9/mod.cpp: In member function ‘int {anonymous}::__struct_compiled_op_ma603dd4b312cefd3d55365bd3cfb46da::run()’:
/home/wiecki/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmphjy_f0a9/mod.cpp:309:30: error: non-floating-point argument in call to function ‘__builtin_isnan’
                   V1_i = abs(isnan(V3_i));
                              ^


--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
pymc3: DEBUG: Applied stickbreaking-transform to w and added transformed w_stickbreaking_ to model.
pymc3: DEBUG: Applied log-transform to mu and added transformed mu_log_ to model.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 4 tests in 2.976s

FAILED (errors=4)
```

This does not occur on travis so it's probably a local problem but it's puzzling to me.

Reproduce: run tests/test_mixture.py in pymc3.

**Comment by nouiz** [comment]
You seem to call isnan, on a non float value. Theano don't raise an error
in that cases, but the c compiler does.

Can you check this is what is happening, that you call isnan with non float
value?

**Comment by lamblin** [comment]
It seems to be a new behaviour of glibc 2.23.
I think the fix would be to change the `c_code` of `scalar.IsNan` when the input dtype is not a floating point dtype.
Another option would be not to insert IsNan at all in the computation graph when the input is not a float.

**Comment by nouiz** [comment]
I did a PR: https://github.com/Theano/Theano/pull/5289
