### ISSUE TITLE
Theano Cudnn enable Issue in Windows 10 64bit

### ISSUE THREAD

**Issue by pimier15** [Theano/Theano#5327]
When i import theano , i got this error

-------------------------------------------------------------------------------------------------------------
Using Theano backend.
Using gpu device 0: GeForce GTX 1060 3GB (CNMeM is enabled with initial size: 81.0% of memory, cuDNN Can not compile with cuDNN. We got this error:
)
ERROR (theano.gof.opt): SeqOptimizer apply <theano.sandbox.cuda.dnn.NoCuDNNRaise object at 0x0000000009004240>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio 12.0\vc\theano\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "c:\program files (x86)\microsoft visual studio 12.0\vc\theano\theano\gof\opt.py", line 90, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio 12.0\vc\theano\theano\sandbox\cuda\dnn.py", line 3092, in apply
    if not dnn_available():
  File "c:\program files (x86)\microsoft visual studio 12.0\vc\theano\theano\sandbox\cuda\__init__.py", line 345, in dnn_available
    dnn_available.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: Can not compile with cuDNN. We got this error:

ERROR (theano.gof.opt): SeqOptimizer apply <theano.sandbox.cuda.dnn.NoCuDNNRaise object at 0x0000000009004240>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio 12.0\vc\theano\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "c:\program files (x86)\microsoft visual studio 12.0\vc\theano\theano\gof\opt.py", line 90, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio 12.0\vc\theano\theano\sandbox\cuda\dnn.py", line 3092, in apply
    if not dnn_available():
  File "c:\program files (x86)\microsoft visual studio 12.0\vc\theano\theano\sandbox\cuda\__init__.py", line 345, in dnn_available
    dnn_available.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: Can not compile with cuDNN. We got this error:
-------------------------------------------------------------------------------------------------------------

This is my sysenv Flag 

floatX=float32,device=gpu,optimizer_including=cudnn,lib.cnmem=0.8,dnn.conv.algo_bwd_filter=deterministic,dnn.conv.algo_bwd_data=deterministic,blas.ldflags=-LC:/toolkits/openblas-0.2.14-int32/bin -lopenblas

and This is .theanorx.txt

[global]
floatX = float32
device = gpu
optimizer_including = cudnn
cuda.disable_gcc_cudnn_check=True <- tried with and without this

[nvcc]
flags=-LC:\Apps\Anaconda2
fastmath = True
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

[dnn]
enabled = True

[lib]
cnmem=0.81
#cudnn=1.0

[blas]
ldflags=-LC:\openblas -lopenblas

**Comment by nouiz** [comment]
This is a problem with your environment. Please use Theano mailing list for that. We keep issue for feature request and for problems in Theano.

You probably miss one step in the installation of cudnn. Adding it to your PATH can help with that type of error.
