### ISSUE TITLE
BUG IN FGRAPH.REPLACE OR A LISTENER

### ISSUE THREAD

**Issue by pcyin** [Theano/Theano#5334]
Hi,

I am using the dev version, and encountered the following error message when compiling a graph, which seems to be a bug.

```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', InplaceDimShuffle{1}.0, Subtensor{int64}.0, TensorType(float32, vector), TensorType(float32, row), 'local_dimshuffle_subtensor') local_dimshuffle_subtensor
ERROR (theano.gof.opt): Optimization failure due to: local_dimshuffle_subtensor
ERROR:theano.gof.opt:Optimization failure due to: local_dimshuffle_subtensor
ERROR (theano.gof.opt): node: InplaceDimShuffle{1}(Subtensor{int64}.0)
ERROR:theano.gof.opt:node: InplaceDimShuffle{1}(Subtensor{int64}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR:theano.gof.opt:TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "Theano/theano/gof/opt.py", line 2004, in process_node
    remove=remove)
  File "Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', InplaceDimShuffle{1}.0, Subtensor{int64}.0, TensorType(float32, vector), TensorType(float32, row), 'local_dimshuffle_subtensor')

ERROR:theano.gof.opt:Traceback (most recent call last):
  File "Theano/theano/gof/opt.py", line 2004, in process_node
    remove=remove)
  File "Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', InplaceDimShuffle{1}.0, Subtensor{int64}.0, TensorType(float32, vector), TensorType(float32, row), 'local_dimshuffle_subtensor')
``` 
The function dump is [here](http://pcyin.me/func.bin). It takes in a simple `ivector` like `func(np.array([0,1,4,1,3,4], dtype='int32'))`.

Btw, the function seems to give me correct results, though I got this error message.

**Comment by nouiz** [comment]
I'm able to reproduce the problems thanks.

You can safely ignore the warning. The execution is valid. I'll try to
remove the warning.

**Comment by nouiz** [comment]
Thanks I did a PR: https://github.com/Theano/Theano/pull/5350
