### ISSUE TITLE
Optimization failure due to: local_gpu_softmax_with_bias

### ISSUE THREAD

**Issue by aeloyq** [Theano/Theano#5364]
i got these imfo when compile the theano.function :

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_softmax_with_bias
ERROR (theano.gof.opt): node: SoftmaxWithBias(dot.0, HostFromGpu.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):

this is my code:

`if Wt is None:
            Wt_values=np.array(Rng.randn(N_hl,N_out),dtype=theano.config.floatX)
            Wt=theano.shared(value=Wt_values,name='Wt',borrow=True)
        if Bi is None:
            Bi_values=np.zeros((N_out), dtype=theano.config.floatX)
            Bi = theano.shared(value=Bi_values, name='Bi', borrow=True)
        self.Wt,self.Bi=Wt,Bi
        self.outputs=T.nnet.nnet.softmax(T.dot(self.hidden.outputs,self.Wt)+self.Bi)`

**Comment by aeloyq** [comment]
i forgot something :
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None

**Comment by nouiz** [comment]
In the current/old gpu back-end, a few optimizations complain instead of being skipped when the graph have float64.

I suppose you don't want a graph with float64, so the solution is to change your code. I don't plan to change the old back-end, as we are deprecating it. So I close this issue.

thanks for the report.

**Comment by aeloyq** [comment]
actually i simplize the error:

>>> for p in a.params:
...     print p.eval()
... 

CudaNdarray([[-0.32195094 -2.57921886]
 [-0.80003369 -1.17916536]])
CudaNdarray([ 0.  0.])
CudaNdarray([[ 0.17618603 -2.1899929 ]
 [ 0.65234697  0.29998466]])
CudaNdarray([ 0.  0.])
>>> >>> for p in a.params:
...     print p.eval().dtype
... 
float32
float32
float32
float32
>>> 
>>> b=a[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'MLP_Softmax' object does not support indexing
>>> b=a.params[0]
>>> c=a.params[1]
>>> d=a.params[2]
>>> e=a.params[3]
>>> f=[[1,0],[0,0],[1,0],[0,1],[1,1]]
>>> g= theano.tensor.dot(f,b)+c
>>> h= theano.tensor.dot(g,d)+e
>>> h
Elemwise{add,no_inplace}.0
>>> i= theano.tensor.nnet.softmax(h)
>>> i.eval()
array([[ 0.15834246,  0.84165754],
       [ 0.5       ,  0.5       ],
       [ 0.15834246,  0.84165754],
       [ 0.0904201 ,  0.9095799 ],
       [ 0.01835858,  0.98164142]])
ERROR (theano.gof.opt): Optimization failure due to: local_gpu_softmax_with_bias
ERROR (theano.gof.opt): node: SoftmaxWithBias(dot.0, HostFromGpu.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\opt.py", line 1922, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\opt.py", line 1422, in local_gpu_softmax_with_bias
    gpu_sm = GpuSoftmaxWithBias()(as_cuda_ndarray_variable(x),
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\basic_ops.py", line 46, in as_cuda_ndarray_variable
    return gpu_from_host(tensor_x)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\op.py", line 602, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\basic_ops.py", line 139, in make_node
    dtype=x.dtype)()])
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\type.py", line 95, in __init__
    (self.__class__.__name__, dtype, name))
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_softmax_with_bias
ERROR (theano.gof.opt): node: SoftmaxWithBias(dot.0, HostFromGpu.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\opt.py", line 1922, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\opt.py", line 1422, in local_gpu_softmax_with_bias
    gpu_sm = GpuSoftmaxWithBias()(as_cuda_ndarray_variable(x),
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\basic_ops.py", line 46, in as_cuda_ndarray_variable
    return gpu_from_host(tensor_x)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\op.py", line 602, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\basic_ops.py", line 139, in make_node
    dtype=x.dtype)()])
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\type.py", line 95, in __init__
    (self.__class__.__name__, dtype, name))
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None

ERROR (theano.gof.opt): Optimization failure due to: local_gpu_softmax_with_bias
ERROR (theano.gof.opt): node: SoftmaxWithBias(dot.0, HostFromGpu.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\opt.py", line 1922, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\opt.py", line 1422, in local_gpu_softmax_with_bias
    gpu_sm = GpuSoftmaxWithBias()(as_cuda_ndarray_variable(x),
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\basic_ops.py", line 46, in as_cuda_ndarray_variable
    return gpu_from_host(tensor_x)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\op.py", line 602, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\basic_ops.py", line 139, in make_node
    dtype=x.dtype)()])
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\sandbox\cuda\type.py", line 95, in __init__
    (self.__class__.__name__, dtype, name))
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None

**Comment by nouiz** [comment]
use the Theano flag:

warn_float64=raise

to find where the upcast to float64 happen

**Comment by aeloyq** [comment]
Thank you very much. it works.

i found that my inputs X is a type of tensor.imatrix
when i change it into tensor.matrix errors fixed

so,the tensorvariable of dtype int32 will be upcast to float64 when compute with other data with float type?
Can i set configs like theano flags to keep converting data into float32 instead of float64 when necessary
sorry for my poor english...i'm chinese

**Comment by aeloyq** [comment]
by the way 
which part of theano documentation may i look for related issues
for example  where can i get information like : use the Theano flag : warn_float64=raise

**Comment by nouiz** [comment]
The doc for all Theano flags:

http://deeplearning.net/software/theano/library/config.html

int32 x float32 always upcast to float64. This is the normal upcasting
rules from C and NumPy. This is normal, as the max value of int32 can't be
represented exactly as float32.

int16 x float32 give float32. So using that could help you prevent upcast.

**Comment by aeloyq** [comment]
i see... what a stupid question.. hh

**Comment by nouiz** [comment]
This isn't a stupid question. Also, it isn't the first time it get asked!
