### ISSUE TITLE
test_dnn_rnn_gru() from test_dnn(theano/gpuarray/test/test_dnn.py) failed

### ISSUE THREAD

**Issue by xht13** [Theano/Theano#5371]
THEANO_FLAGS=mode=FAST_RUN,device=cuda0,floatX=float32,optimizer_including=cudnn python test_cudnn_rnn.py 

  error info:
  Mapped name None to device cuda0: GeForce GTX 1080
Using cuDNN version 5105 on context None
Traceback (most recent call last):
  File "test_cudnn_rnn.py", line 182, in <module>
    test_dnn_rnn_gru()
  File "test_cudnn_rnn.py", line 22, in test_dnn_rnn_gru
    rnnb = dnn.RNNBlock(theano.config.floatX, hidden_dim, depth, 'gru', context_name=None)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gpuarray/dnn.py", line 2382, in __init__
    ddesc, states = _make_dropout_desc(0, 4242, context_name)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gpuarray/dnn.py", line 1869, in _make_dropout_desc
    profile=False)()
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/compile/function_module.py", line 1784, in orig_function
    defaults)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/compile/function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/vm.py", line 1055, in make_all
    impl=impl))
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/op.py", line 824, in make_c_thunk
    no_recycling=e_no_recycling)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/cc.py", line 563, in accept
    self.fetch_variables()
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/cc.py", line 589, in fetch_variables
    params = node.run_params()
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/graph.py", line 129, in run_params
    return self.op.get_params(self)
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gpuarray/dnn.py", line 215, in get_params
    ptr = get_prop(self.dnn_context(node), 'cudnn_handle').value
  File "/usr/lib/python2.7/site-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gpuarray/type.py", line 114, in get_prop
    return _get_props(name)[k]
KeyError: ('The following error happened while compiling the node', _DropoutDescriptor{context_name=None}(Cast{float32}.0, Cast{uint64}.0, Constant{<pygpu.gpu...0x3a50cd0>}), '\n', 'cudnn_handle')

centos 7.0, gcc 4.8.5, theano 0.9-dev ,cudnn 5.1.0.5, cuda 8.0, gtx 1080, pygpu.test() is successful. I really don't know how to fix it

**Comment by xht13** [comment]
original code from theano/gpuarray/test/test_dnn.py to test rnn and lstm

**Comment by khaotik** [comment]
@xht13 Look similar to #5123, try adding cuDNN directory path to `LIBRARY_PATH` or adding symlink to cuDNN libs at `/usr/lib`

**Comment by yyht** [comment]
thanks, this works for me

**Comment by nouiz** [comment]
Was this the full error message? If so, we should make it better. If it was
not the full error message, so you still have it?

**Comment by yyht** [comment]
yes, this is full error message. adding cuDNN directory path to LIBRARY_PATH solves my problem.
