### ISSUE TITLE
I had'nt used the linux system for a month,and got error when Importing Theano

### ISSUE THREAD

**Issue by QuantumLiu** [Theano/Theano#5386]
Theano had worked well ,but no it got error.This is really strange,I hadn't used this system for a month!
`Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Using gpu device 0: GeForce GTX 1060 6GB (CNMeM is enabled with initial size: 80.0% of memory, cuDNN None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/tests/test_driver.py", line 31, in test_nvidia_driver1
    profile=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1594, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 48, in get_module_cache
    return cmodule.get_module_cache(config.compiledir, init_args=init_args)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1516, in get_module_cache
    _module_cache = ModuleCache(dirname, **init_args)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 657, in __init__
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 741, in refresh
    files = os.listdir(root)
OSError: [Errno 13] Permission denied: '/home/quantumliu/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmp0kscz7'
`

**Comment by Sentient07** [comment]
Did you try clearing and purging the cache? I had the same problem before (Caused by shifting between two versions) and it solved the problem for me

**Comment by QuantumLiu** [comment]
Sowould you please tell me how didi you clean the cache?

**Comment by QuantumLiu** [comment]
thank you so much!i fixed it by
sudo theano-cache clear

**Comment by Sentient07** [comment]
Welcome, also please ask debugging questions on StackOverflow or theano mailing list henceforth.
