### ISSUE TITLE
SeqOptimizer error with scan under contexts flag

### ISSUE THREAD

**Issue by HosangYoon** [Theano/Theano#5401]
Hello,

I'm getting some optimizer errors while trying to change my RNN code to work with the `contexts` flag. It works without problems currently with libgpuarray using the `device=cuda0` flag. 

Following simplified code reproduces the problem on my machine (using the latest developer builds (cloned today) of Theano, libgpuarray, & pygpu on Ubuntu 16.04, numpy 1.11.0, scipy 0.17.0, cuda 8.0.44, nvidia driver 375.26, cuDNN 5105):
```
import os

#os.environ['THEANO_FLAGS'] = 'device=cuda0,floatX=float32'
os.environ['THEANO_FLAGS'] = 'contexts=dev0->cuda0,floatX=float32,exception_verbosity=high'

import numpy as np
import theano as th
import theano.tensor as tt

x = tt.matrix()
y = th.shared(np.array([0., 0., 0.]).astype('float32'), target='dev0')

def step(x_i, prev_h_i, y):
    return x_i + prev_h_i + y

ret, upd = th.scan(step, sequences=[x],
                    outputs_info=[tt.zeros_like(x[0])],
                    non_sequences=[y], n_steps=x.shape[0])

a=np.ones((5,3)).astype('float32')
inputs = {x:a}

print ret.eval(inputs)
```

Which generates the following output:

```
Using cuDNN version 5105 on context dev0
Mapped name dev0 to device cuda0: GeForce GTX TITAN X (0000:02:00.0)
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gpuarray.opt.GraphToGPU object at 0x7fe265a70290>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/yuno/Theano/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/yuno/Theano/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/yuno/Theano/theano/gpuarray/opt.py", line 388, in apply
    outputs = new_ops(*[mapping[i] for i in node.inputs], return_list=True)
  File "/home/yuno/Theano/theano/tensor/basic.py", line 2935, in __call__
    ret = super(Alloc, self).__call__(val, *shapes, **kwargs)
  File "/home/yuno/Theano/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/yuno/Theano/theano/gpuarray/basic_ops.py", line 825, in make_node
    value = as_gpuarray_variable(value, context_name=self.context_name)
  File "/home/yuno/Theano/theano/gpuarray/basic_ops.py", line 74, in as_gpuarray_variable
    return gpu_from_host(context_name)(x)
  File "/home/yuno/Theano/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/yuno/Theano/theano/gpuarray/basic_ops.py", line 651, in make_node
    dtype=x.dtype)()])
  File "/home/yuno/Theano/theano/gpuarray/type.py", line 170, in __init__
    get_context(self.context_name)
  File "/home/yuno/Theano/theano/gpuarray/type.py", line 88, in get_context
    raise ContextNotDefined("context name %s not defined" % (name,))
ContextNotDefined: context name None not defined

[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]
 [ 4.  4.  4.]
 [ 5.  5.  5.]]
```
Using `device=cuda0` flag instead and removing the `target = 'dev0'` part, the code runs without any errors.

Using both `device` and `contexts` flags (so that context name None is defined) gives even more strange errors.

Using just the `contexts` flag but giving `optimizer=None` flag makes the errors go away, which leads me to believe it might be a bug.

Is this reproducible?

Thanks.

**Comment by HosangYoon** [comment]
Noticed my Theano & libgpuarray builds were producing lots of errors in test suites. They have been fixed by:
- Installing NCCL (lack of which I think was the reason for the errors above)
- Reverting Nvidia driver 375.26 -> 367.48 (the version that comes with the CUDA toolkit 8.0.44)
- Using Theano (c0b2476) & libgpuarray (61fe479) versions

Strangely, I was getting numerical errors in Theano's test suite with Nvidia driver 375.26 which got fixed by reverting to an older version. In any case, the problem above seems to have been specific to my case, so closing this issue.

**Comment by abergeron** [comment]
The multi-context support was an experiement that was somewhat abandoned since we found out that it doesn't lead to any speed ups (and even introduces major slowdowns in some cases) due to the GIL.

Because of that we probably will not fix anything related to that in the short term.  I encourage you to try using multiple processes to split your model across GPUs instead.

**Comment by dianaloren** [comment]
Hello,
I have Theano 0.9.0rc2.dev-76cfd7e8473024c6a5009df4a85ac4aea4dd14f4 installed and all the tests have worked so far.
However, running a nn training algorithm, I am having the exact same issue as @junosan. Reading the answers, should I understand that this is a issue to be solved in Theano and you won't be supporting this  (http://deeplearning.net/software/theano/tutorial/using_multi_gpu.html) "anymore" (?) 

Thanks.
