### ISSUE TITLE
Can't compile in virtualenv

### ISSUE THREAD

**Issue by nazandr** [Theano/Theano#5416]
```
Traceback (most recent call last):
  File "ownNewsParser/bot.py", line 4, in <module>
    from keras.preprocessing import text
  File "/home/andrey/keras2/lib/python3.5/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/home/andrey/keras2/lib/python3.5/site-packages/keras/backend/__init__.py", line 64, in <module>
    from .theano_backend import *
  File "/home/andrey/keras2/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/home/andrey/keras2/lib/python3.5/site-packages/theano/__init__.py", line 66, in <module>
    from theano.compile import (
  File "/home/andrey/keras2/lib/python3.5/site-packages/theano/compile/__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "/home/andrey/keras2/lib/python3.5/site-packages/theano/compile/function_module.py", line 21, in <module>
    import theano.compile.mode
  File "/home/andrey/keras2/lib/python3.5/site-packages/theano/compile/mode.py", line 10, in <module>
    import theano.gof.vm
  File "/home/andrey/keras2/lib/python3.5/site-packages/theano/gof/vm.py", line 659, in <module>
    from . import lazylinker_c
  File "/home/andrey/keras2/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "/home/andrey/keras2/lib/python3.5/site-packages/theano/gof/cmodule.py", line 2309, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): /home/andrey/.theano/compiledir_Linux-4.4--generic-i686-athlon-with-Ubuntu-16.04-xenial-athlon-3.5.2-32/lazylinker_ext/mod.cpp:1:20: fatal error: Python.h: Нет такого файла или каталога. compilation terminated.. 

```

**Comment by nouiz** [comment]
Can you translate the error? If it mean the file Python.h don't exist, it
mean you didn't installed python-dev inside the virtual environment. This
is a dependency of Theano.
