### ISSUE TITLE
"Could not initialize elemwise support" with OpenCL on amdgpu drivers

### ISSUE THREAD

**Issue by gcarq** [Theano/Theano#5418]
Hi, I'm using Theano with Keras for a very naive time series prediction. It works fine on the CPU, but I get following error if I try it on a Radeon r9 280x with amdgpu drivers on Arch Linux: 

```
$ /usr/bin/python /home/random/workspace/theano_test/time_series_prediction.py
Using Theano backend.
Mapped name None to device opencl0:0: AMD TAHITI (DRM 3.8.0 / 4.9.0-2-slk, LLVM 3.9.1) 
train_dataset: 100, test_dataset: 58
fitting model:   0%|          | 0/250 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/random/workspace/theano_test/time_series_prediction.py", line 191, in <module>
    main()
  File "/home/random/workspace/theano_test/time_series_prediction.py", line 164, in main
    model.fit(train_x, train_y, nb_epoch=1, batch_size=batch_size, verbose=0, shuffle=False)
  File "/usr/lib/python3.6/site-packages/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/usr/lib/python3.6/site-packages/keras/engine/training.py", line 1125, in fit
    self._make_train_function()
  File "/usr/lib/python3.6/site-packages/keras/engine/training.py", line 729, in _make_train_function
    **self._function_kwargs)
  File "/usr/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 969, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 955, in __init__
    **kwargs)
  File "/usr/lib/python3.6/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/lib/python3.6/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/lib/python3.6/site-packages/theano/compile/function_module.py", line 1784, in orig_function
    defaults)
  File "/usr/lib/python3.6/site-packages/theano/compile/function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/lib/python3.6/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/lib/python3.6/site-packages/theano/gof/vm.py", line 1059, in make_all
    impl=impl))
  File "/usr/lib/python3.6/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/usr/lib/python3.6/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/lib/python3.6/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/usr/lib/python3.6/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/usr/lib/python3.6/site-packages/theano/gof/cc.py", line 1606, in cthunk_factory
    *(in_storage + out_storage + orphd))
RuntimeError: ('The following error happened while compiling the node', GpuElemwise{sub,no_inplace}(GpuArrayConstant{1.0}, <GpuArrayType<None>(float32, ())>), '\n', 'Could not initialize elemwise support')
```

Keras model:
```
model = Sequential()
model.add(LSTM(128, activation='tanh',
                             batch_input_shape=(batch_size, look_back, 1),
                             stateful=True,
                             return_sequences=False))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')
```

Theano config:
```
$ cat ~/.theanorc 
[global]
mode = FAST_RUN
device = opencl0:0
#device = cpu
floatX = float32
allow_gc = False
```

Versions:
theano master branch, commit `1ef44cc`.
libgpuarray master branch, commit `61fe479`.
Python 3.6.0
opencl-mesa 13.0.3-1
Linux 3.9.0

Here is also a link to a very similar github issue: http://stackoverflow.com/questions/38487510/python-theano-runtimeerror-could-not-initialize-elemwise-support

Is there a way to get this running with opencl, and if not was is necessary to do so?

**Comment by nouiz** [comment]
The OpenCL back-end isn't in a useful state. There is ops are missing OpenCL support and others problems. We don't have time to work on it now. So I tag this issue for OpenCL and we will check it when we have time for OpenCL.

Unless you have time to help us heavily to make this work, I would recommand you to use CUDA or the CPU.

Sorry for this sad news.
