### ISSUE TITLE
unable to install theano when behind proxy !!

### ISSUE THREAD

**Issue by abidmanu** [Theano/Theano#5438]
I was trying to install theano using sudo pip install theano on my ubuntu machine but failed in doing so, may be because i was behind the proxy. so i tried to install without proxy (using mobile wifi) but still was not able to import theano and when i again tried to install using sudo pip install theano it shows following.
Requirement already satisfied (use --upgrade to upgrade): Theano in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/lib/python2.7/dist-packages (from Theano)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.11 in /usr/lib/python2.7/dist-packages (from Theano)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from Theano)
Cleaning up...
can some one help me please ?

**Comment by himanshubabal** [comment]
Log shows that Theano is already installed on your system.

You can try to uninstall Theano and re-install it
`pip uninstall theano`

And then re-install it
`pip install theano`

That should solve your problem.
Also, you can use pip behind a network proxy
`pip install --proxy user:password@proxyserver:port theano`

Also, make sure Python and Pip are using same directory
run   `which python`   and   'which pip'
and make sure their base directories are same

For example, I am using miniconda distribution
```
$which python
/Users/himanshubabal/miniconda3/bin/python
~ $which pip
/Users/himanshubabal/miniconda3/bin/pip
```
So you see, both python and pip will be storing libraries in same directories.
Make sure it is this way in your system.

You can also see all libraries installed by pip using following
`pip freeze`

That should solve your problem

**Comment by abidmanu** [comment]
after uninstalling theano, i tried to install using proxy ( sudo pip install --proxy edcguest:edcguest@172.31.103.29:3128 theano ) but shows following error:
Downloading/unpacking theano
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 670, in get_page
    resp = session.get(url, headers={"Accept": "text/html"})
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/adapters.py", line 305, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/adapters.py", line 215, in get_connection
    block=self._pool_block)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/poolmanager.py", line 259, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/poolmanager.py", line 214, in __init__
    'Not supported proxy scheme %s' % self.proxy.scheme
AssertionError: Not supported proxy scheme None

Storing debug log for failure in /home/apple/.pip/pip.log

**Comment by Sentient07** [comment]
This is a problem with pip and not with theano. You can adjust the environment variable `http_proxy` to configure with your proxy settings and then use `pip install`.

**Comment by nouiz** [comment]
Download Theano from by it and install that copy. It will bypass the proxy
problem you have.

**Comment by abidmanu** [comment]
i did not get your point

**Comment by nouiz** [comment]
I mean download from git, not by pip.
