### ISSUE TITLE
Theano crash when using "time_once" optimization value

### ISSUE THREAD

**Issue by pec72** [Theano/Theano#5517]
Theano version : <= rel-0.9.0beta1

Theano crash when using gpuarray as the GPU backend due to problem with cudnn

when using:

 THEANO_FLAGS='device=cuda,floatX=float32,lib.cnmem=0.20,optimizer_including=cudnn,dnn.conv.algo_bwd_data=time_once,dnn.conv.algo_bwd_filter=time_once' 

Then, the following methods are used, but with the wrong parameters

- cudnnFindConvolutionBackwardFilterAlgorithmEx(...)
- cudnnFindConvolutionBackwardDataAlgorithmEx(...)

Output error:
```
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wl,-rpath,/usr/local/cuda-8.0/targets/x86_64-linux/lib -std=c++11 -march=ivybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=10240 -mtune=ivybridge -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/opt/conda/lib/python3.5/site-packages/pygpu -I/opt/conda/lib/python3.5/site-packages/numpy/core/include -I/usr/local/cuda-8.0/targets/x86_64-linux/include -I/opt/conda/lib/python3.5/site-packages/theano/gpuarray -I/opt/conda/lib/python3.5/site-packages/numpy/core/include -I/opt/conda/include/python3.5m -I/opt/conda/lib/python3.5/site-packages/theano/gof -L/usr/local/cuda-8.0/targets/x86_64-linux/lib -L/opt/conda/lib -fvisibility=hidden -o /root/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmptezj2csp/m7283a1e68eabbf98670cc2c87ae15cb1.so /root/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmptezj2csp/mod.cpp -lgpuarray -lcudnn -lpython3.5m
/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmptezj2csp/mod.cpp: In member function ‘int {anonymous}::__struct_compiled_op_m7283a1e68eabbf98670cc2c87ae15cb1::conv_gi_node_m7283a1e68eabbf98670cc2c87ae15cb1_0(PyGpuArrayObject*, PyGpuArrayObject*, PyGpuArrayObject*, cudnnConvolutionDescriptor_t, double, double, PyGpuArrayObject**, cudnnHandle_t)’:
/root/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmptezj2csp/mod.cpp:382:72: error: cannot convert ‘cudnnConvolutionDescriptor_t {aka cudnnConvolutionStruct*}’ to ‘cudnnTensorDescriptor_t {aka cudnnTensorStruct*}’ for argument ‘4’ to ‘cudnnStatus_t cudnnFindConvolutionBackwardDataAlgorithmEx(cudnnHandle_t, cudnnFilterDescriptor_t, const void*, cudnnTensorDescriptor_t, const void*, cudnnConvolutionDescriptor_t, cudnnTensorDescriptor_t, void*, int, int*, cudnnConvolutionBwdDataAlgoPerf_t*, void*, size_t)’
       APPLY_SPECIFIC(input), 1, &count, &choice, *(void **)tmpmem, free);
                                                                        ^
In file included from /root/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmptezj2csp/mod.cpp:13:0:
/usr/local/cuda-8.0/targets/x86_64-linux/include/cudnn.h:112:16: note: class type ‘cudnnConvolutionStruct’ is incomplete
 typedef struct cudnnConvolutionStruct*     cudnnConvolutionDescriptor_t;
                ^

Traceback (most recent call last):
  File "training-streaming.py", line 478, in <module>
    shuffle=True
  File "/opt/conda/lib/python3.5/site-packages/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/opt/conda/lib/python3.5/site-packages/keras/engine/training.py", line 1164, in fit
    self._make_train_function()
  File "/opt/conda/lib/python3.5/site-packages/keras/engine/training.py", line 768, in _make_train_function
    **self._function_kwargs)
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 969, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 955, in __init__
    **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/opt/conda/lib/python3.5/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/opt/conda/lib/python3.5/site-packages/theano/compile/function_module.py", line 1784, in orig_function
    defaults)
  File "/opt/conda/lib/python3.5/site-packages/theano/compile/function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/vm.py", line 1063, in make_all
    impl=impl))
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/cc.py", line 1589, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/cc.py", line 1492, in compile_cmodule
    preargs=preargs)
  File "/opt/conda/lib/python3.5/site-packages/theano/gof/cmodule.py", line 2309, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', GpuDnnConvGradI{algo='time_on_shape_change', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', 'Compilation failed (return status=1): /root/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmptezj2csp/mod.cpp: In member function ‘int {anonymous}::__struct_compiled_op_m7283a1e68eabbf98670cc2c87ae15cb1::conv_gi_node_m7283a1e68eabbf98670cc2c87ae15cb1_0(PyGpuArrayObject*, PyGpuArrayObject*, PyGpuArrayObject*, cudnnConvolutionDescriptor_t, double, double, PyGpuArrayObject**, cudnnHandle_t)’:. /root/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmptezj2csp/mod.cpp:382:72: error: cannot convert ‘cudnnConvolutionDescriptor_t {aka cudnnConvolutionStruct*}’ to ‘cudnnTensorDescriptor_t {aka cudnnTensorStruct*}’ for argument ‘4’ to ‘cudnnStatus_t cudnnFindConvolutionBackwardDataAlgorithmEx(cudnnHandle_t, cudnnFilterDescriptor_t, const void*, cudnnTensorDescriptor_t, const void*, cudnnConvolutionDescriptor_t, cudnnTensorDescriptor_t, void*, int, int*, cudnnConvolutionBwdDataAlgoPerf_t*, void*, size_t)’.        APPLY_SPECIFIC(input), 1, &count, &choice, *(void **)tmpmem, free);.                                                                         ^. In file included from /root/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/tmptezj2csp/mod.cpp:13:0:. /usr/local/cuda-8.0/targets/x86_64-linux/include/cudnn.h:112:16: note: class type ‘cudnnConvolutionStruct’ is incomplete.  typedef struct cudnnConvolutionStruct*     cudnnConvolutionDescriptor_t;.                 ^. ', "[GpuDnnConvGradI{algo='time_on_shape_change', inplace=True}(<GpuArrayType<None>(float32, (False, False, False, False))>, <GpuArrayType<None>(float32, (False, False, False, False))>, <GpuArrayType<None>(float32, (False, False, False, False))>, <CDataType{cudnnConvolutionDescriptor_t}>, Constant{1.0}, Constant{0.0})]")

```

**Comment by nouiz** [comment]
which cudnn version do you use? The new back-end currently support only v5 and v5.1.

**Comment by pec72** [comment]
Here is the ouput:

Using Theano backend.
Using cuDNN version 5105 on context None
Mapped name None to device cuda0: GeForce GTX 1070 (0000:02:00.0)

**Comment by nouiz** [comment]
I'm able to reproduce the error. I'm looking into it.

thanks for the report.

Fred

**Comment by nouiz** [comment]
here is a PR that fix this:

https://github.com/Theano/Theano/pull/5558
