### ISSUE TITLE
theano-nose broken on linux

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5531]
Since the change to make it work on Windows, it is broken on linux:

$ theano-nose 
Traceback (most recent call last):
  File "/home/nouiz/miniconda/bin/theano-nose", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/nouiz/repos/Theano/bin/theano-nose", line 2, in <module>
    import theano_nose
ImportError: No module named theano_nose

I tried to use a relative import, but it gave this error: 

Traceback (most recent call last):
  File "/home/nouiz/miniconda/bin/theano-nose", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/nouiz/repos/Theano/bin/theano-nose", line 2, in <module>
    from .theano_nose import main
ValueError: Attempted relative import in non-package

**Comment by nouiz** [comment]
If I run:

python setup.py develop

it fix the problem, so closing.

**Comment by notoraptor** [comment]
Indeed, as the changes modified the installation script, it was necessary to reinstall Theano after updating it.

Running `pip install -e .` may be sufficient also !
