### ISSUE TITLE
import error when importing gpuarray

### ISSUE THREAD

**Issue by kobecsb** [Theano/Theano#5540]
Hi,
I installed libgpuarray according to the docs. (linux)
But when I test like ```python -c "import theano.gpuarray"```,  an error encountered,
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, nerv, extra_ops, multinomial, reduction
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/opt.py", line 57, in <module>
    from .blocksparse import (GpuSparseBlockGemv, GpuSparseBlockOuter,
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 91, in <module>
    gpu_sparse_block_gemv = GpuSparseBlockGemv(False)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 31, in __init__
    COp.__init__(self, "blockgemv.c", "APPLY_SPECIFIC(blockgemv)")
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1277, in __init__
    self.load_c_code(func_files)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1357, in load_c_code
    "%s" % func_files[i])
ValueError: No valid section marker was found in file /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blockgemv.c
```
I looked into the code in op.py and change the section_re from
```
section_re = re.compile(r'^#section ([a-zA-Z0-9_]+)$', re.MULTILINE)
```
to
```
section_re = re.compile(r'^#section ([a-zA-Z0-9_\r]+)$', re.MULTILINE)
```
to match the '\r' character in c code but got another error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, nerv, extra_ops, multinomial, reduction
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/opt.py", line 57, in <module>
    from .blocksparse import (GpuSparseBlockGemv, GpuSparseBlockOuter,
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 145, in <module>
    gpu_sparse_block_outer = GpuSparseBlockOuter(False)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 108, in __init__
    COp.__init__(self, ["blockger.c"], "APPLY_SPECIFIC(blockger)")
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1275, in __init__
    self.load_c_code(func_files)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1346, in load_c_code
    (func_files[i], split[n]))
ValueError: Unknown section type (in file /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blockger.c): support_code_apply
```
So I read the op.py and change the first line in blockgemv.c to
```
THEANO_APPLY_CODE_SECTION
```
and change the 
```
backward_re = re.compile(
         r'^THEANO_(APPLY|SUPPORT)_CODE_SECTION$',
         re.MULTILINE)
```
to
```
backward_re = re.compile(
         r'^THEANO_(APPLY|SUPPORT)_CODE_SECTION\r$',
         re.MULTILINE)
```

And ```python -c "import theano.gpuarray"```, then it works.

So I'm wondering if it's a bug or some specific design?
Thank you.

**Comment by nouiz** [comment]
THe problem is that the file  /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blockgemv.c

is in dos mode. So the end of line isn't the same as on windows. The easy fix as you are on linux is to run the command line "dos2unix file". To fix this file. This fix could be needed for different file.

But we should do something about this in Theano. This isn't the first report. I'm not sure what we should do. I see a few options:
1) detect file with end of line as dos format and automatically convert them. For files inside Theano, it is fine, but it isn't for user doing extension of Theano that code on windows.
2) Make all the compilation pipeline support both end of line.
3) detect in dos format. In memory convert it before parsing it.

I would have a tendency to prefer 3.

**Comment by nouiz** [comment]
I have a PR that fix this:

https://github.com/Theano/Theano/pull/5542

Mostly, when reading the file, we ask python to convert the end of line to unix format when it isn't the case.

thanks for the report.
