### ISSUE TITLE
GpuCAReduceCuda RuntimeError: 'Could not initialize elemwise support'

### ISSUE THREAD

**Issue by jc-Rosichini** [Theano/Theano#5541]
Hi ,
I'm running into a runtime error that seems related to GpuCAReduceCuda
This happens only when using cuda0 mode (it's ok in cpu and gpu modes)

(1) my config:
Windows 10
Python Anaconda 3.5
Theano 0.9.0beta1dev
Lasagne 0.2dev1
pygpy 0.6.0 and latest libgpuarray

(2) the crash:     

The code compiles ok both in cpu and/or gpu and cuda (new libgpuarray) modes

Then at runtime in cuda mode:
```
 train_fn = theano.function([net.input_var, net.target_var], [loss, I, U, acc], updates=updates
 
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1795, in orig_function
    defaults)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\vm.py", line 1063, in make_all
    impl=impl))
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 924, in make_thunk
    no_recycling)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1603, in cthunk_factory
    *(in_storage + out_storage + orphd))
	
RuntimeError: ('The following error happened while compiling the node', GpuElemwise{add,no_inplace}(GpuCAReduceCuda{pre=sqr,red=add}.0, 
GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, 
GpuCAReduceCuda{pre=sqr,red=add}.0, .... 
...
...  GpuCAReduceCuda{pre=sqr,red=add}.0), '\n', 'Could not initialize elemwise support')
```

(3) Code

The theano sub functions :

```
import theano.tensor as T

def crossentropy_weighted(y_pred, y_true, void_labels, weighted_labels):
    # Flatten y_true
    y_true_tmp = T.flatten(y_true)   # b,0,1 -> b01
    # Create mask
    mask = T.ones_like(y_true_tmp)
    
    # create weights mask
    weights = T.zeros_like(y_true_tmp)
    for l in range(len(weighted_labels)):
        weights = T.switch(T.eq(y_true_tmp, l), weighted_labels[l], weights)
      
    mask = T.switch(T.eq(y_true_tmp, void_labels[0]), np.int32(0), mask)

    # Modify y_true temporarily
    y_true_tmp = y_true_tmp * mask
    
    # Clip predictions                       
    y_clip = (1e-20)*T.ones_like(y_pred)
    y_pred_tmp = T.maximum(y_pred, y_clip)

    # Compute cross-entropy (per pixel)   
    loss = T.nnet.categorical_crossentropy(y_pred_tmp, y_true_tmp)
    
    # apply weights balancing
    loss *= weights 

    # Compute masked mean loss
    loss *= mask
    loss = T.sum(loss) / (T.sum(mask).astype(T.config.floatX) + 0.001) 

    return loss

def the_metrics(y_pred, y_true, n_classes, void_labels):  
    not_void = T.ones_like(y_true, dtype='int32')
    not_void = T.switch(T.eq(y_true, void_labels[0]), np.int32(0), not_void)

    I = T.zeros(n_classes)
    U = T.zeros(n_classes)

    for i in range(n_classes):
        y_true_i = T.eq(y_true,  i)
        y_pred_i = T.eq(y_predN, i)
        I = T.set_subtensor(I[i], T.sum(y_true_i * y_pred_i))
        U = T.set_subtensor(U[i], T.sum(T.or_(y_true_i, y_pred_i) * not_void))

    accuracy = T.sum(I) / (T.sum(not_void) + 0.01) # avoid 0 divide
    return I, U, accuracy

loss      = crossentropy_weighted(pred, net.target_var, void_labels, balanced_weights)
weightsl2 = regularize_network_params(net.output_layer, lasagne.regularization.l2)
loss     += weight_decay_shared * weightsl2

train_fn = theano.function([net.input_var, net.target_var], [loss, I, U, acc], updates=updates)
```
------

Any hints greatly appreciated, thanks

**Comment by nouiz** [comment]
Thanks for the report. I'm not sure what is going on. I updated the description so that the code is more readable and added one missing import, but this isn't enough to make it work. Can you update the example so that I can reproduce the problem?

**Comment by jc-Rosichini** [comment]
Here is a zip with a source example 'bug_test.py' and a dump of what happens.
Note that I updated to the very latest dev Theano / Lasagne and recompiled LibgpuArray.
[bug_test.zip](https://github.com/Theano/Theano/files/775566/bug_test.zip)

**Comment by jc-Rosichini** [comment]
btw. the original issue is still alive     

train_fn = theano.function([net.input_var, net.target_var], [loss, I, U, acc], updates=updates
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1795, in orig_function
    defaults)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\vm.py", line 1063, in make_all
    impl=impl))
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 924, in make_thunk
    no_recycling)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1603, in cthunk_factory
    *(in_storage + out_storage + orphd))
RuntimeError: ('The following error happened while compiling the node', GpuElemwise{add,no_inplace}(GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0,
... _and so on_ 
...
GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, 
GpuCAReduceCuda{pre=sqr,red=add}.0), '\n', 'Could not initialize elemwise support')

**Comment by jc-Rosichini** [comment]
sorry the correct dump file is : 
[dump_test_theano.txt](https://github.com/Theano/Theano/files/775616/dump_test_theano.txt)

**Comment by abergeron** [comment]
Can you try with with #5547?  It has fixed a very similar problem for someone else.

**Comment by jc-Rosichini** [comment]
Tried #5547 patch on op.py
Still getting:
  File "train.py", line 466, in initiate_training
    train(cf)
  File "train.py", line 230, in train
    train_fn = theano.function([net.input_var, net.target_var], [loss, I, U, acc], updates=updates
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1795, in orig_function
    defaults)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\vm.py", line 1063, in make_all
    impl=impl))
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 924, in make_thunk
    no_recycling)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1603, in cthunk_factory
    *(in_storage + out_storage + orphd))
RuntimeError: ('The following error happened while compiling the node', GpuElemwise{add,no_inplace}(GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0,
 ....
GpuCAReduceCuda{pre=sqr,red=add}.0), '\n', 'Could not initialize elemwise support')


GpuCAReduceCuda{pre=sqr,red=add}.0,

**Comment by jc-Rosichini** [comment]
Having said so, it does seem that it fixes the issue for this toy example:
[bug_test_2.zip](https://github.com/Theano/Theano/files/776798/bug_test_2.zip)

**Comment by abergeron** [comment]
Which version of the cuda driver do you have?

**Comment by jc-Rosichini** [comment]
Cuda8.0 + cuDNN5
NVidia driver 378.66-notebook-win10-64bit-international-whql (the latest)
GeForce GTX 980M (CNMeM is enabled with initial size: 81.0% of memory, cuDNN 5105)
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]

**Comment by nouiz** [comment]
I have a fix PR here:

https://github.com/Theano/Theano/pull/5559

It fix some error like yours, but I'm not sure if it fix your case.

Can you test it?

thanks

Fred

**Comment by jc-Rosichini** [comment]
Sure, will do in a few minutes and let you know!
Jean-Claude

**Comment by jc-Rosichini** [comment]
ok two things:

**(1) after  latest upgrade thru: pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git**

Nothing better:

......
mod.cu(3074): warning: statement is unreachable

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
mod.cu
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(668): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(668): note: consider using '%zu' in the format string
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): warning C4477: 'fprintf' : format string '%016lx' requires an argument of type 'unsigned long', but variadic argument 1 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): note: consider using '%zx' in the format string
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): warning C4477: 'fprintf' : format string '%016lx' requires an argument of type 'unsigned long', but variadic argument 2 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): note: consider using '%zx' in the format string
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 3 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): note: consider using '%zu' in the format string
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): warning C4477: 'fprintf' : format string '%016lx' requires an argument of type 'unsigned long', but variadic argument 4 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): note: consider using '%zx' in the format string
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): warning C4477: 'fprintf' : format string '%2lu' requires an argument of type 'unsigned long', but variadic argument 5 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(670): note: consider using '%zu' in the format string
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(690): warning C4477: 'fprintf' : format string '%016lx' requires an argument of type 'unsigned long', but variadic argument 3 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(690): note: consider using '%zx' in the format string
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(690): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 4 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(690): note: consider using '%zu' in the format string
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(690): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 5 has type 'std::size_t'
C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\sandbox\cuda\cnmem.cpp(690): note: consider using '%zu' in the format string
mod.cu(802): warning C4311: 'type cast': pointer truncation from 'CudaNdarray *' to 'long'
mod.cu(3372): warning C4312: 'type cast': conversion from 'long' to 'float *' of greater size

LINK : fatal error LNK1104: cannot open file 'E:/theano_compiledirx/compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64/cuda_ndarray/cuda_ndarray.pyd'

_and then_
....
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1603, in cthunk_factory
    *(in_storage + out_storage + orphd))
RuntimeError: ('The following error happened while compiling the node', GpuElemwise{add,no_inplace}(GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, 

GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, 
GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0, 
..............................
............................., 
 GpuCAReduceCuda{pre=sqr,red=add}.0, GpuCAReduceCuda{pre=sqr,red=add}.0), '\n', 'Could not initialize elemwise support')




**(2) then after changing the 4 py files as per #5559** 
Something is broken at compile time ... gof  ???

python gfilter.py
Using cuDNN version 5105 on context None
Mapped name None to device cuda0: GeForce GTX 980M (0000:01:00.0)
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gpuarray.opt.GraphToGPU object at 0x000001954041B9E8>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gpuarray\opt.py", line 391, in apply
    outputs = new_ops(*[mapping[i] for i in node.inputs], return_list=True)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gpuarray\elemwise.py", line 96, in make_node
    if len(inputs) > max_inputs_to_GpuElemwise(outputs):
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gpuarray\elemwise.py", line 45, in max_inputs_to_GpuElemwise
    if isinstance(node_or_outputs, gof.Apply):
NameError: name 'gof' is not defined

**Comment by jc-Rosichini** [comment]
ERROR (theano.gof.opt): Optimization failure due to: local_gpua_elemwise
ERROR (theano.gof.opt): node: Elemwise{sqr,no_inplace}(HostFromGpu(gpuarray).0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1973, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gpuarray\opt.py", line 234, in local_opt
    new_op(*node.inputs, return_list=True)]
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gpuarray\elemwise.py", line 96, in make_node
    if len(inputs) > max_inputs_to_GpuElemwise(outputs):
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gpuarray\elemwise.py", line 45, in max_inputs_to_GpuElemwise
    if isinstance(node_or_outputs, gof.Apply):
NameError: name 'gof' is not defined

**Comment by nouiz** [comment]
My PR was with an older version of my local branch. When I pushed the
updated version, it got refused as I rebased it and I missed the
rejection...

I updated it again. Try with the PR. It is not yet merged.

thanks

**Comment by jc-Rosichini** [comment]
Hi, done it: so far so good, seems ok!
Thank you
Jean-Claude
