### ISSUE TITLE
ImportError: cannot import name inplace_increment

### ISSUE THREAD

**Issue by 9thDimension** [Theano/Theano#5564]
Just got the latest Theano 0.9.0b1 using `sudo pip install git+git://github.com/Theano/Theano.git`
```
>>> import theano
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/theano/__init__.py", line 80, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/lib/python2.7/site-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
  File "/usr/lib/python2.7/site-packages/theano/tensor/__init__.py", line 9, in <module>
    from theano.tensor.subtensor import *
  File "/usr/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 27, in <module>
    from cutils_ext.cutils_ext import inplace_increment
ImportError: cannot import name inplace_increment
```

This is on Centos 7.

**Comment by nouiz** [comment]
I'm pretty sure this is related to having an old Theano cache.

Can you delete it? "theano-cache purge". If that don't work, by default it is under ~/.theano

**Comment by wangtingc** [comment]
@nouiz hi, I want to know where I should input the command  "theano-cache purge". 
My problem is 
NotImplementedError: Could not import inplace_increment, so some
advanced indexing features are disabled. They will be available if you
update NumPy to version 1.8 or later, or to the latest development version.
You may need to clear the cache (theano-cache clear) afterwards.

but my numpy is 1.11.3, why I still get the problem?

**Comment by nouiz** [comment]
delete the cache manually if theano-cache don't work:

rm -rf ~/.theano

and update Theano:

sudo pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
