### ISSUE TITLE
Theano 0.8.0 / 0.8.2 crash when training Keras model on GPU

### ISSUE THREAD

**Issue by 9thDimension** [Theano/Theano#5565]
I did try using a more recent Theano, but I also had problems with that.
```
<above is my Keras model definition>...
____________________________________________________________________________________________________
activation_61 (Activation)       (None, 64, 160, 160)  0           merge_22[0][0]                   
____________________________________________________________________________________________________
segment (Convolution2D)          (None, 1, 160, 160)   1601        activation_61[0][0]              
====================================================================================================
Total params: 5,023,809
Trainable params: 3,559,361
Non-trainable params: 1,464,448
____________________________________________________________________________________________________
[2017-02-17 13:07:26,528][train_val_mask][INFO]:    Training network...


1 #include <Python.h>
2 #include <iostream>
3 #include "theano_mod_helper.h"
4 #include <math.h>
5 #include <numpy/arrayobject.h>
6 #include <numpy/arrayscalars.h>
7 #include "cudnn.h"
8 #include "cudnn_helper.h"
9 //////////////////////
10 ////  Support Code
11 //////////////////////
12 
13 
14     namespace {
15     struct __struct_compiled_op_3a87097b49a747ff917f4cb202458172 {
16         PyObject* __ERROR;
17 
18         PyObject* storage_V3;
19 PyObject* storage_V5;
20 PyObject* storage_V1;
21         
22 
23         __struct_compiled_op_3a87097b49a747ff917f4cb202458172() {
24             // This is only somewhat safe because we:
25             //  1) Are not a virtual class
26             //  2) Do not use any virtual classes in the members
27             //  3) Deal with mostly POD and pointers
28 
29             // If this changes, we would have to revise this, but for
30             // now I am tired of chasing segfaults because
31             // initialization code had an error and some pointer has
32             // a junk value.
33             memset(this, 0, sizeof(*this));
34         }
35         ~__struct_compiled_op_3a87097b49a747ff917f4cb202458172(void) {
36             cleanup();
37         }
38 
39         int init(PyObject* __ERROR, PyObject* storage_V3, PyObject* storage_V5, PyObject* storage_V1) {
40             Py_XINCREF(storage_V3);
41 Py_XINCREF(storage_V5);
42 Py_XINCREF(storage_V1);
43             this->storage_V3 = storage_V3;
44 this->storage_V5 = storage_V5;
45 this->storage_V1 = storage_V1;
46             
47 
48 
49 
50 
51             this->__ERROR = __ERROR;
52             return 0;
53         }
54         void cleanup(void) {
55             __label_1:
56 
57 double __DUMMY_1;
58 __label_3:
59 
60 double __DUMMY_3;
61 __label_5:
62 
63 double __DUMMY_5;
64 __label_8:
65 
66 double __DUMMY_8;
67 
68             Py_XDECREF(this->storage_V3);
69 Py_XDECREF(this->storage_V5);
70 Py_XDECREF(this->storage_V1);
71         }
72         int run(void) {
73             int __failure = 0;
74             
75     PyObject* py_V1;
76     
77         cudnnConvolutionDescriptor_t V1;
78         
79     PyObject* py_V3;
80     
81         PyArrayObject* V3;
82         
83             typedef npy_int64 dtype_V3;
84             
85     PyObject* py_V5;
86     
87         PyArrayObject* V5;
88         
89             typedef npy_int64 dtype_V5;
90             
91 {
92 
93     py_V1 = PyList_GET_ITEM(storage_V1, 0);
94     {Py_XINCREF(py_V1);}
95     
96         if (py_V1 == Py_None)
97         {
98             V1 = NULL;
99         }
100         else
101         {
102             
103   V1 = (cudnnConvolutionDescriptor_t)PyCObject_AsVoidPtr(py_V1);
104 
105         }
106         
107 {
108 
109     py_V3 = PyList_GET_ITEM(storage_V3, 0);
110     {Py_XINCREF(py_V3);}
111     
112             V3 = NULL;
113             if (py_V3 == Py_None) {
114                 // We can either fail here or set V3 to NULL and rely on Ops
115                 // using tensors to handle the NULL case, but if they fail to do so
116                 // they'll end up with nasty segfaults, so this is public service.
117                 PyErr_SetString(PyExc_ValueError, "expected an ndarray, not None");
118                 {
119         __failure = 4;
120         if (!PyErr_Occurred()) {
121             PyErr_SetString(PyExc_RuntimeError,
122                 "Unexpected error in an Op's C code. "
123                 "No Python exception was set.");
124             }
125         goto __label_4;}
126             }
127             if (!PyArray_Check(py_V3)) {
128                 PyErr_SetString(PyExc_ValueError, "expected an ndarray");
129                 {
130         __failure = 4;
131         if (!PyErr_Occurred()) {
132             PyErr_SetString(PyExc_RuntimeError,
133                 "Unexpected error in an Op's C code. "
134                 "No Python exception was set.");
135             }
136         goto __label_4;}
137             }
138             // We expect NPY_INT64
139             if (!PyArray_ISALIGNED((PyArrayObject*) py_V3)) {
140                 PyArrayObject * tmp = (PyArrayObject*) py_V3;
141                 PyErr_Format(PyExc_NotImplementedError,
142                              "expected an aligned array of type %ld "
143                              "(NPY_INT64), got non-aligned array of type %ld"
144                              " with %ld dimensions, with 3 last dims "
145                              "%ld, %ld, %ld"
146                              " and 3 last strides %ld %ld, %ld.",
147                              (long int) NPY_INT64,
148                              (long int) PyArray_TYPE((PyArrayObject*) py_V3),
149                              (long int) PyArray_NDIM(tmp),
150                              (long int) PyArray_NDIM(tmp) >= 3 ?
151             PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-3] : -1,
152                              (long int) PyArray_NDIM(tmp) >= 2 ?
153             PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-2] : -1,
154                              (long int) PyArray_NDIM(tmp) >= 1 ?
155             PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-1] : -1,
156                              (long int) PyArray_NDIM(tmp) >= 3 ?
157             PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-3] : -1,
158                              (long int) PyArray_NDIM(tmp) >= 2 ?
159             PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-2] : -1,
160                              (long int) PyArray_NDIM(tmp) >= 1 ?
161             PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-1] : -1
162             );
163                 {
164         __failure = 4;
165         if (!PyErr_Occurred()) {
166             PyErr_SetString(PyExc_RuntimeError,
167                 "Unexpected error in an Op's C code. "
168                 "No Python exception was set.");
169             }
170         goto __label_4;}
171             }
172             // This is a TypeError to be consistent with DEBUG_MODE
173             // Note: DEBUG_MODE also tells the name of the container
174             if (PyArray_TYPE((PyArrayObject*) py_V3) != NPY_INT64) {
175                 PyErr_Format(PyExc_TypeError,
176                              "expected type_num %d (NPY_INT64) got %d",
177                              NPY_INT64, PyArray_TYPE((PyArrayObject*) py_V3));
178                 {
179         __failure = 4;
180         if (!PyErr_Occurred()) {
181             PyErr_SetString(PyExc_RuntimeError,
182                 "Unexpected error in an Op's C code. "
183                 "No Python exception was set.");
184             }
185         goto __label_4;}
186             }
187             
188         V3 = (PyArrayObject*)(py_V3);
189         Py_XINCREF(V3);
190         
191 {
192 
193     py_V5 = PyList_GET_ITEM(storage_V5, 0);
194     {Py_XINCREF(py_V5);}
195     
196             V5 = NULL;
197             if (py_V5 == Py_None) {
198                 // We can either fail here or set V5 to NULL and rely on Ops
199                 // using tensors to handle the NULL case, but if they fail to do so
200                 // they'll end up with nasty segfaults, so this is public service.
201                 PyErr_SetString(PyExc_ValueError, "expected an ndarray, not None");
202                 {
203         __failure = 6;
204         if (!PyErr_Occurred()) {
205             PyErr_SetString(PyExc_RuntimeError,
206                 "Unexpected error in an Op's C code. "
207                 "No Python exception was set.");
208             }
209         goto __label_6;}
210             }
211             if (!PyArray_Check(py_V5)) {
212                 PyErr_SetString(PyExc_ValueError, "expected an ndarray");
213                 {
214         __failure = 6;
215         if (!PyErr_Occurred()) {
216             PyErr_SetString(PyExc_RuntimeError,
217                 "Unexpected error in an Op's C code. "
218                 "No Python exception was set.");
219             }
220         goto __label_6;}
221             }
222             // We expect NPY_INT64
223             if (!PyArray_ISALIGNED((PyArrayObject*) py_V5)) {
224                 PyArrayObject * tmp = (PyArrayObject*) py_V5;
225                 PyErr_Format(PyExc_NotImplementedError,
226                              "expected an aligned array of type %ld "
227                              "(NPY_INT64), got non-aligned array of type %ld"
228                              " with %ld dimensions, with 3 last dims "
229                              "%ld, %ld, %ld"
230                              " and 3 last strides %ld %ld, %ld.",
231                              (long int) NPY_INT64,
232                              (long int) PyArray_TYPE((PyArrayObject*) py_V5),
233                              (long int) PyArray_NDIM(tmp),
234                              (long int) PyArray_NDIM(tmp) >= 3 ?
235             PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-3] : -1,
236                              (long int) PyArray_NDIM(tmp) >= 2 ?
237             PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-2] : -1,
238                              (long int) PyArray_NDIM(tmp) >= 1 ?
239             PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-1] : -1,
240                              (long int) PyArray_NDIM(tmp) >= 3 ?
241             PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-3] : -1,
242                              (long int) PyArray_NDIM(tmp) >= 2 ?
243             PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-2] : -1,
244                              (long int) PyArray_NDIM(tmp) >= 1 ?
245             PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-1] : -1
246             );
247                 {
248         __failure = 6;
249         if (!PyErr_Occurred()) {
250             PyErr_SetString(PyExc_RuntimeError,
251                 "Unexpected error in an Op's C code. "
252                 "No Python exception was set.");
253             }
254         goto __label_6;}
255             }
256             // This is a TypeError to be consistent with DEBUG_MODE
257             // Note: DEBUG_MODE also tells the name of the container
258             if (PyArray_TYPE((PyArrayObject*) py_V5) != NPY_INT64) {
259                 PyErr_Format(PyExc_TypeError,
260                              "expected type_num %d (NPY_INT64) got %d",
261                              NPY_INT64, PyArray_TYPE((PyArrayObject*) py_V5));
262                 {
263         __failure = 6;
264         if (!PyErr_Occurred()) {
265             PyErr_SetString(PyExc_RuntimeError,
266                 "Unexpected error in an Op's C code. "
267                 "No Python exception was set.");
268             }
269         goto __label_6;}
270             }
271             
272         V5 = (PyArrayObject*)(py_V5);
273         Py_XINCREF(V5);
274         
275 {
276 // Op class GpuDnnConvDesc
277 
278 {
279   cudnnStatus_t err;
280 
281   if ((err = cudnnCreateConvolutionDescriptor(&V1)) != CUDNN_STATUS_SUCCESS) {
282     PyErr_Format(PyExc_MemoryError, "could not allocate convolution "
283                  "descriptor: %s", cudnnGetErrorString(err));
284     {
285         __failure = 7;
286         if (!PyErr_Occurred()) {
287             PyErr_SetString(PyExc_RuntimeError,
288                 "Unexpected error in an Op's C code. "
289                 "No Python exception was set.");
290             }
291         goto __label_7;}
292   }
293 
294 #if defined(CUDNN_VERSION) && CUDNN_VERSION >= 30
295 
296   int pad[2] = {0, 0};
297   int subsample[2] = {2, 2};
298   int upscale[2] = {1, 1};
299 
300   // Adjust padding values if using full convolution
301   if (1 == 0) {
302     pad[0] = *(npy_int64 *)PyArray_GETPTR1(V5, 2) - 1;
303     pad[1] = *(npy_int64 *)PyArray_GETPTR1(V5, 3) - 1;
304     if (2 >= 3) {
305         pad[2] = *(npy_int64 *)PyArray_GETPTR1(V5, 4) - 1;
306     }
307   }
308   // Adjust padding values if using half convolution
309   else if (1 == 2) {
310     pad[0] = *(npy_int64 *)PyArray_GETPTR1(V5, 2) / 2;
311     pad[1] = *(npy_int64 *)PyArray_GETPTR1(V5, 3) / 2;
312     if (2 >= 3) {
313         pad[2] = *(npy_int64 *)PyArray_GETPTR1(V5, 4) / 2;
314     }
315   }
316 
317   err = cudnnSetConvolutionNdDescriptor_v3(
318   V1,
319   2,
320   pad, subsample, upscale,
321   CUDNN_CONVOLUTION, CUDNN_DATA_FLOAT
322   );
323 #else
324   PyErr_Format(PyExc_RuntimeError, "could not set op descriptor: CUDNN_VERSION must be >= 30");
325 #endif
326   if (err != CUDNN_STATUS_SUCCESS) {
327     PyErr_Format(PyExc_RuntimeError, "could not set op descriptor: %s",
328                  cudnnGetErrorString(err));
329     {
330         __failure = 7;
331         if (!PyErr_Occurred()) {
332             PyErr_SetString(PyExc_RuntimeError,
333                 "Unexpected error in an Op's C code. "
334                 "No Python exception was set.");
335             }
336         goto __label_7;}
337   }
338 }
339 __label_7:
340 
341 double __DUMMY_7;
342 
343 }
344 __label_6:
345 
346         if (V5) {
347             Py_XDECREF(V5);
348         }
349         
350     {Py_XDECREF(py_V5);}
351     
352 double __DUMMY_6;
353 
354 }
355 __label_4:
356 
357         if (V3) {
358             Py_XDECREF(V3);
359         }
360         
361     {Py_XDECREF(py_V3);}
362     
363 double __DUMMY_4;
364 
365 }
366 __label_2:
367 
368     if (!__failure) {
369       
370 Py_XDECREF(py_V1);
371 if (V1 == NULL) {
372   py_V1 = Py_None;
373   Py_INCREF(py_V1);
374 } else {
375   py_V1 = PyCObject_FromVoidPtr((void *)V1,
376                                       (void (*)(void *))cudnnDestroyConvolutionDescriptor);
377 }
378 if (py_V1 == NULL) { cudnnDestroyConvolutionDescriptor(V1); }
379 
380       PyObject* old = PyList_GET_ITEM(storage_V1, 0);
381       {Py_XINCREF(py_V1);}
382       PyList_SET_ITEM(storage_V1, 0, py_V1);
383       {Py_XDECREF(old);}
384     }
385     
386     {Py_XDECREF(py_V1);}
387     
388 double __DUMMY_2;
389 
390 }
391 
392             
393         if (__failure) {
394             // When there is a failure, this code puts the exception
395             // in __ERROR.
396             PyObject* err_type = NULL;
397             PyObject* err_msg = NULL;
398             PyObject* err_traceback = NULL;
399             PyErr_Fetch(&err_type, &err_msg, &err_traceback);
400             if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}
401             if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}
402             if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}
403             PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);
404             PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);
405             PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);
406             PyList_SET_ITEM(__ERROR, 0, err_type);
407             PyList_SET_ITEM(__ERROR, 1, err_msg);
408             PyList_SET_ITEM(__ERROR, 2, err_traceback);
409             {Py_XDECREF(old_err_type);}
410             {Py_XDECREF(old_err_msg);}
411             {Py_XDECREF(old_err_traceback);}
412         }
413         // The failure code is returned to index what code block failed.
414         return __failure;
415         
416         }
417     };
418     }
419     
420 
421         static int __struct_compiled_op_3a87097b49a747ff917f4cb202458172_executor(__struct_compiled_op_3a87097b49a747ff917f4cb202458172* self) {
422             return self->run();
423         }
424 
425         static void __struct_compiled_op_3a87097b49a747ff917f4cb202458172_destructor(void* executor, void* self) {
426             delete ((__struct_compiled_op_3a87097b49a747ff917f4cb202458172*)self);
427         }
428         
429 //////////////////////
430 ////  Functions
431 //////////////////////
432 static PyObject * instantiate(PyObject * self, PyObject *argtuple) {
433   assert(PyTuple_Check(argtuple));
434   if (4 != PyTuple_Size(argtuple)){ 
435      PyErr_Format(PyExc_TypeError, "Wrong number of arguments, expected 4, got %i", (int)PyTuple_Size(argtuple));
436      return NULL;
437   }
438   __struct_compiled_op_3a87097b49a747ff917f4cb202458172* struct_ptr = new __struct_compiled_op_3a87097b49a747ff917f4cb202458172();
439   if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1),PyTuple_GET_ITEM(argtuple, 2),PyTuple_GET_ITEM(argtuple, 3) ) != 0) {
440     delete struct_ptr;
441     return NULL;
442   }
443   PyObject* thunk = PyCObject_FromVoidPtrAndDesc((void*)(&__struct_compiled_op_3a87097b49a747ff917f4cb202458172_executor), struct_ptr, __struct_compiled_op_3a87097b49a747ff917f4cb202458172_destructor);
444   return thunk; }
445 
446 //////////////////////
447 ////  Module init
448 //////////////////////
449 static PyMethodDef MyMethods[] = {
450 	{"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
451 	{NULL, NULL, 0, NULL}
452 };
453 PyMODINIT_FUNC init3a87097b49a747ff917f4cb202458172(void){
454    import_array();
455    (void) Py_InitModule("3a87097b49a747ff917f4cb202458172", MyMethods);
456 }
457 
===============================
In file included from /usr/include/python2.7/pyconfig.h:6:0,
                 from /usr/include/python2.7/Python.h:8,
                 from mod.cu:1:
/usr/include/python2.7/pyconfig-64.h:1182:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/local/cuda/include/host_config.h:173:0,
                 from /usr/local/cuda/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/features.h:168:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/python2.7/pyconfig.h:6:0,
                 from /usr/include/python2.7/Python.h:8,
                 from mod.cu:1:
/usr/include/python2.7/pyconfig-64.h:1204:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/local/cuda/include/host_config.h:173:0,
                 from /usr/local/cuda/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/features.h:170:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
mod.cu(305): warning: subscript out of range
mod.cu(313): warning: subscript out of range
mod.cu(317): error: identifier "cudnnSetConvolutionNdDescriptor_v3" is undefined
1 error detected in the compilation of "/tmp/tmpxft_00002399_00000000-9_mod.cpp1.ii".

['nvcc', '-shared', '-O3', '-arch=sm_37', '-m64', '-Xcompiler', '-fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/centos/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.2.1511-Core-x86_64-2.7.5-64/cuda_ndarray', '-I/usr/lib64/python2.7/site-packages/theano/sandbox/cuda', '-I/usr/local/cuda/include', '-I/usr/lib64/python2.7/site-packages/numpy/core/include', '-I/usr/include/python2.7', '-I/usr/lib64/python2.7/site-packages/theano/gof', '-o', '/home/centos/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.2.1511-Core-x86_64-2.7.5-64/tmpL_l9Du/3a87097b49a747ff917f4cb202458172.so', 'mod.cu', '-L/usr/lib64', '-lcudnn', '-lpython2.7', '-lcudart']
Traceback (most recent call last):
  File "train_val_mask.py", line 129, in <module>
    nb_val_samples=100)
  File "/usr/lib/python2.7/site-packages/keras/engine/training.py", line 1454, in fit_generator
    self._make_train_function()
  File "/usr/lib/python2.7/site-packages/keras/engine/training.py", line 767, in _make_train_function
    **self._function_kwargs)
  File "/usr/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 969, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 955, in __init__
    **kwargs)
  File "/usr/lib64/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/usr/lib64/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/usr/lib64/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/usr/lib64/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/lib64/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/lib64/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/usr/lib64/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/usr/lib64/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/usr/lib64/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/lib64/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/usr/lib64/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/usr/lib64/python2.7/site-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/lib64/python2.7/site-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/lib64/python2.7/site-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/usr/lib64/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py", line 399, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuDnnConvDesc{border_mode='valid', subsample=(2, 2), conv_mode='conv', precision='float32'}(MakeVector{dtype='int64'}.0, MakeVector{dtype='int64'}.0), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -arch=sm_37 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/centos/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.2.1511-Core-x86_64-2.7.5-64/cuda_ndarray -I/usr/lib64/python2.7/site-packages/theano/sandbox/cuda -I/usr/local/cuda/include -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/theano/gof -o /home/centos/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.2.1511-Core-x86_64-2.7.5-64/tmpL_l9Du/3a87097b49a747ff917f4cb202458172.so mod.cu -L/usr/lib64 -lcudnn -lpython2.7 -lcudart', "[GpuDnnConvDesc{border_mode='valid', subsample=(2, 2), conv_mode='conv', precision='float32'}(<TensorType(int64, vector)>, <TensorType(int64, vector)>)]")
```

**Comment by nouiz** [comment]
We don't support Theano 0.8.2 anymore. We are close to releasing Theano 0.9rc1 now.

Use Theano dev version, it very probably have a fix for this. The version you use only support cudnn v3 and v4. If you installed v5 or v5.1, use Theano dev version. It support that more recent cudnn version.
