### ISSUE TITLE
conflicts between torch and theano--a suggestion for improvement.

### ISSUE THREAD

**Issue by cjliux** [Theano/Theano#5581]
Currently, torch is using cudnn 5110 while theano 0.9.0b1 can only support 5005. Then the problem is when importing theano, it prompts:
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 66, in init_dev
    avail = dnn.dnn_available(name)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/dnn.py", line 174, in dnn_available
    if not dnn_present():
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/dnn.py", line 157, in dnn_present
    dnn_present.avail, dnn_present.msg = _dnn_check_version()
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/dnn.py", line 130, in _dnn_check_version
    v = version()
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/dnn.py", line 330, in version
    "while the library is version %s." % v)
RuntimeError: Mixed dnn version. The header is version 5005 while the library is version 5110.

So I suggest that an entry for setting the path of cudnn should be added to THEANO_FLAGS.

**Comment by nouiz** [comment]
Theano support cudnn 5.1. What make you think you need both version?

Make sure your environment only have cudnn 5.1 and all will work well.

**Comment by cjliux** [comment]
Eh...Sorry. I have tried it on windows and that didn't work for me. Anyway, thank you.
