### ISSUE TITLE
Test fail deterministically in DebugMode theano/scan_module/tests/test_scan_opt.py:TestGaussNewton.test_nobatch

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5586]
This test always fail in DebugMode.

THEANO_FLAGS=DebugMode.patience=1,mode=DebugMode theano-nose theano/scan_module/tests/test_scan_opt.py:TestGaussNewton.test_nobatch -s --pdb --pdb-failure

It is the scanOp_save_mem opt that seem to shift all result when it should not do so. Here is the error:
```
======================================================================
ERROR: test_nobatch (theano.scan_module.tests.test_scan_opt.TestGaussNewton)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/bastienf/repos/Theano/theano/scan_module/tests/test_scan_opt.py", line 119, in test_nobatch
    class GaussNewtonMatrix(object):
  File "/u/bastienf/repos/Theano/theano/scan_module/tests/test_scan_opt.py", line 106, in _run
    f()
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "/u/bastienf/repos/Theano/theano/compile/debugmode.py", line 2305, in deco
    return f()
  File "/u/bastienf/repos/Theano/theano/compile/debugmode.py", line 2230, in f
    r_vals)
  File "/u/bastienf/repos/Theano/theano/compile/debugmode.py", line 1078, in _find_bad_optimizations0
    new_graph=new_graph_str)
BadOptimization: BadOptimization Error 
  Variable: id 140677454264592 Subtensor{::int64}.0
  Op Subtensor{::int64}(Subtensor{int64:int64:int8}.0, Constant{1})
  Value Type: <type 'numpy.ndarray'>
  Old Value shape, dtype, strides: (10, 10) float64 (80, 8)

  Old Value:  [[ 0.45176911  0.436364    0.44078463  0.43683308  0.4447106   0.42295613
   0.50847826  0.47602453  0.45637602  0.47293546]
 [ 0.51382751  0.51165349  0.47543479  0.53047943  0.50142264  0.48407497
   0.51621107  0.51573665  0.50520342  0.53558663]
 [ 0.55589683  0.49987857  0.49289679  0.57590271  0.51975115  0.51570383
   0.55758665  0.54078606  0.54665063  0.54495092]
 [ 0.45316789  0.42250768  0.43212262  0.4732338   0.46341912  0.4823203
   0.47384448  0.49727241  0.4833003   0.48690126]
 [ 0.515654    0.486016    0.48040412  0.52063374  0.48240941  0.47240748
   0.53208756  0.52581719  0.50153071  0.4975123 ]
 [ 0.49802653  0.47392992  0.44635642  0.48402941  0.46828034  0.45190321
   0.47732847  0.48928166  0.48246821  0.48137742]
 [ 0.49570112  0.46813647  0.46155462  0.48750967   ...
  New Value shape, dtype, strides: (10, 10) float64 (80, 8)

  New Value:  [[ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.45176911  0.436364    0.44078463  0.43683308  0.4447106   0.42295613
   0.50847826  0.47602453  0.45637602  0.47293546]
 [ 0.51382751  0.51165349  0.47543479  0.53047943  0.50142264  0.48407497
   0.51621107  0.51573665  0.50520342  0.53558663]
 [ 0.55589683  0.49987857  0.49289679  0.57590271  0.51975115  0.51570383
   0.55758665  0.54078606  0.54665063  0.54495092]
 [ 0.45316789  0.42250768  0.43212262  0.4732338   0.46341912  0.4823203
   0.47384448  0.49727241  0.4833003   0.48690126]
 [ 0.515654    0.486016    0.48040412  0.52063374  0.48240941  0.47240748
   0.53208756  0.52581719  0.50153071  0.4975123 ]
 [ 0.49802653  0.47392992  0.44635642  0.48402941  0.468280 ...
  Max Abs Diff:  0.508478258386
  Mean Abs Diff:  0.0731873411236
  Median Abs Diff:  0.031827912461
  Std Abs Diff:  0.129511172417
  Value at Max Diff:  (0.0, 0.50847825838649241)
  Max Rel Diff:  1.0
  Mean Rel Diff:  0.128204322697
  Median Rel Diff:  0.0317529552746
  Std Rel Diff:  0.291558012091
  Value at Max Diff:  (0.0, 0.45176910549191918)

  Reason:  scanOp_save_mem
  Old Graph:
  Subtensor{int64:int64:int8} [id A] ''   
   |for{cpu,rop_of_scan_fn&scan_fn&scan_fn}.3 [id B] ''   
   | |Shape_i{0} [id C] ''   
   | | |<TensorType(float64, matrix)> [id D]
   | |Subtensor{int64:int64:int8} [id E] ''   
   | | |<TensorType(float64, matrix)> [id D]
   | | |ScalarFromTensor [id F] ''   
   | | | |Elemwise{switch,no_inplace} [id G] ''   
   | | |   |Elemwise{le,no_inplace} [id H] ''   
   | | |   |TensorConstant{0} [id I]
   | | |   |TensorConstant{0} [id J]
   | | |ScalarFromTensor [id K] ''   
   | | | |Shape_i{0} [id C] ''   
   | | |Constant{1} [id L]
   | |Alloc [id M] ''   
   | | |TensorConstant{(1, 1) of 0.0} [id N]
   | | |Elemwise{sub,no_inplace} [id O] ''   
   | | | |Elemwise{switch,no_inplace} [id P] ''   
   | | | | |Elemwise{lt,no_inplace} [id Q] ''   
   | | | | |TensorConstant{0} [id R]
   | | | | |Elemwise{switch,no_inplace} [id S] ''   
   | | | |Elemwise{switch,no_inplace} [id T] ''   
   | | |   |Elemwise{lt,no_inplace} [id U] ''   
   | | |   |Elemwise{switch,no_inplace} [id V] ''   
   | | |   |Elemwise{switch,no_inplace} [id P] ''   
   | | |Shape_i{1} [id W] ''   
   | |   |<TensorType(float64, matrix)> [id D]
   | |IncSubtensor{Set;:int64:} [id X] ''   
   | | |AllocEmpty{dtype='float64'} [id Y] ''   
   | | | |TensorConstant{1} [id Z]
   | | | |TensorConstant{10} [id BA]
   | | |TensorConstant{(1, 10) of 0.0} [id BB]
   | | |Constant{1} [id BC]
   | |Subtensor{:int64:} [id BD] ''   
   | | |Alloc [id BE] ''   
   | | | |TensorConstant{0.0} [id BF]
   | | | |Elemwise{add,no_inplace} [id BG] ''   
   | | | | |TensorConstant{1} [id BH]
   | | | | |Shape_i{0} [id C] ''   
   | | | |TensorConstant{10} [id BI]
   | | |ScalarFromTensor [id BJ] ''   
   | |   |Elemwise{maximum,no_inplace} [id BK] ''   
   | |     |Elemwise{maximum,no_inplace} [id BL] ''   
   | |     |TensorConstant{1} [id Z]
   | |IncSubtensor{Set;:int64:} [id BM] ''   
   | | |AllocEmpty{dtype='float64'} [id BN] ''   
   | | | |Elemwise{add,no_inplace} [id BO] ''   
   | | | | |Elemwise{switch,no_inplace} [id BP] ''   
   | | | | |TensorConstant{1} [id BQ]
   | | | |TensorConstant{10} [id BR]
   | | |TensorConstant{(1, 10) of 0.0} [id BB]
   | | |Constant{1} [id BS]
   | |IncSubtensor{Set;:int64:} [id BT] ''   
   | | |AllocEmpty{dtype='float64'} [id BU] ''   
   | | | |Elemwise{add,no_inplace} [id BV] ''   
   | | | | |Elemwise{switch,no_inplace} [id BW] ''   
   | | | | |TensorConstant{1} [id BQ]
   | | | |TensorConstant{10} [id BR]
   | | |TensorConstant{(1, 10) of 0.0} [id BB]
   | | |Constant{1} [id BS]
   | |<TensorType(float64, matrix)> [id BX]
   | |<TensorType(float64, matrix)> [id BY]
   | |<TensorType(float64, vector)> [id BZ]
   | |TensorConstant{(1,) of 1.0} [id CA]
   | |TensorConstant{(1,) of 1} [id CB]
   | |Elemwise{mul,no_inplace} [id CC] ''   
   | | |TensorConstant{(1, 1) of 2.0} [id CD]
   | | |<TensorType(float64, matrix)> [id BX]
   | |Elemwise{mul,no_inplace} [id CE] ''   
   | | |TensorConstant{(1, 1) of 2.0} [id CD]
   | | |<TensorType(float64, matrix)> [id BY]
   | |Elemwise{mul,no_inplace} [id CF] ''   
   |   |TensorConstant{(1,) of 2.0} [id CG]
   |   |<TensorType(float64, vector)> [id BZ]
   |ScalarFromTensor [id CH] ''   
   | |Elemwise{add,no_inplace} [id CI] ''   
   |   |Elemwise{sub,no_inplace} [id CJ] ''   
   |   | |Elemwise{sub,no_inplace} [id CK] ''   
   |   | | |Elemwise{switch,no_inplace} [id CL] ''   
   |   | | |Shape_i{0} [id C] ''   
   |   | |TensorConstant{1} [id CM]
   |   |Elemwise{maximum,no_inplace} [id CN] ''   
   |     |Elemwise{add,no_inplace} [id CO] ''   
   |     | |Elemwise{sub,no_inplace} [id CP] ''   
   |     | |TensorConstant{1} [id BQ]
   |     |TensorConstant{2} [id CQ]
   |ScalarFromTensor [id CR] ''   
   | |Elemwise{add,no_inplace} [id CS] ''   
   |   |Elemwise{sub,no_inplace} [id CT] ''   
   |   | |Elemwise{sub,no_inplace} [id CU] ''   
   |   | | |Elemwise{add,no_inplace} [id BG] ''   
   |   | | |Shape_i{0} [id C] ''   
   |   | |TensorConstant{1} [id CV]
   |   |Elemwise{maximum,no_inplace} [id CN] ''   
   |Constant{1} [id CW]

  New Graph:
  Subtensor{::int64} [id CX] ''   
   |Subtensor{int64:int64:int8} [id CY] ''   
   | |for{cpu,rop_of_scan_fn&scan_fn&scan_fn}.3 [id CZ] ''   
   | | |Elemwise{maximum,no_inplace} [id DA] ''   
   | | | |Elemwise{minimum,no_inplace} [id DB] ''   
   | | | | |Elemwise{maximum,no_inplace} [id DC] ''   
   | | | | |Shape_i{0} [id C] ''   
   | | | |InplaceDimShuffle{} [id DD] ''   
   | | |   |Elemwise{Cast{int64}} [id DE] ''   
   | | |Subtensor{int64:int64:int8} [id E] ''   
   | | |Alloc [id M] ''   
   | | |IncSubtensor{Set;:int64:} [id DF] ''   
   | | | |AllocEmpty{dtype='float64'} [id DG] ''   
   | | | | |TensorConstant{1} [id DH]
   | | | | |TensorConstant{10} [id DI]
   | | | |TensorConstant{(1, 10) of 0.0} [id BB]
   | | | |Constant{1} [id DJ]
   | | |Subtensor{:int64:} [id DK] ''   
   | | | |Subtensor{:int64:} [id BD] ''   
   | | | |ScalarFromTensor [id DL] ''   
   | | |   |Elemwise{maximum,no_inplace} [id DM] ''   
   | | |IncSubtensor{Set;:int64:} [id DN] ''   
   | | | |AllocEmpty{dtype='float64'} [id DO] ''   
   | | | | |Elemwise{add,no_inplace} [id DP] ''   
   | | | | |TensorConstant{10} [id DI]
   | | | |TensorConstant{(1, 10) of 0.0} [id BB]
   | | | |Constant{1} [id DJ]
   | | |IncSubtensor{Set;:int64:} [id DQ] ''   
   | | | |AllocEmpty{dtype='float64'} [id DR] ''   
   | | | | |Elemwise{add,no_inplace} [id DS] ''   
   | | | | |TensorConstant{10} [id DI]
   | | | |TensorConstant{(1, 10) of 0.0} [id BB]
   | | | |Constant{1} [id DJ]
   | | |<TensorType(float64, matrix)> [id BX]
   | | |<TensorType(float64, matrix)> [id BY]
   | | |<TensorType(float64, vector)> [id BZ]
   | | |TensorConstant{(1,) of 1.0} [id CA]
   | | |TensorConstant{(1,) of 1} [id CB]
   | | |Elemwise{mul,no_inplace} [id CC] ''   
   | | |Elemwise{mul,no_inplace} [id CE] ''   
   | | |Elemwise{mul,no_inplace} [id CF] ''   
   | |ScalarFromTensor [id DT] ''   
   | | |Elemwise{add,no_inplace} [id DU] ''   
   | |   |Elemwise{sub,no_inplace} [id DV] ''   
   | |   | |Elemwise{sub,no_inplace} [id DW] ''   
   | |   | |TensorConstant{1} [id DX]
   | |   |Elemwise{maximum,no_inplace} [id DY] ''   
   | |     |Elemwise{add,no_inplace} [id DZ] ''   
   | |     |TensorConstant{2} [id EA]
   | |ScalarFromTensor [id EB] ''   
   | | |Elemwise{add,no_inplace} [id EC] ''   
   | |   |Elemwise{sub,no_inplace} [id ED] ''   
   | |   | |Elemwise{sub,no_inplace} [id EE] ''   
   | |   | |TensorConstant{1} [id EF]
   | |   |Elemwise{maximum,no_inplace} [id DY] ''   
   | |ScalarFromTensor [id EG] ''   
   |   |TensorConstant{1} [id EH]
   |Constant{1} [id EI]


Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison

-------------------- >> begin captured logging << --------------------
theano.configdefaults: WARNING: install mkl with `conda install mkl-service`: No module named mkl
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 313.034s

FAILED (errors=1)
```

**Comment by nouiz** [comment]
dde50054c638604a1dd0de2c6a403cfc730ccdab is the first commit with the bug
