### ISSUE TITLE
no such instruction: vinserti128

### ISSUE THREAD

**Issue by mmelodea** [Theano/Theano#5604]
Dears,

I'm trying to use Keras on a cluster where I don't have admin permissions. So, I'm trying that by using a virtual environment. Everything goes fine during the installation and setup of Theano and Keras. Also when I insert the model for the DNN in the python command line. However, after the compile command, when I call the "Fit" method I'm getting the error below. Any suggestion on how to solve that? I appreciate any help, please.
(Note: I also have tried TensorFlow, but it returning an error about glibc_2.16)

Problem occurred during compilation with the command line below:
/cvmfs/sft.cern.ch/lcg/releases/LCG_85swan2/gcc/4.9.3/x86_64-slc6/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=4096 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/cvmfs/sft.cern.ch/lcg/releases/LCG_85swan2/numpy/1.11.0/x86_64-slc6-gcc49-opt/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/core/include -I/cvmfs/sft.cern.ch/lcg/releases/LCG_85swan2/Python/2.7.10/x86_64-slc6-gcc49-opt/include/python2.7 -I/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof -L/cvmfs/sft.cern.ch/lcg/releases/LCG_85swan2/Python/2.7.10/x86_64-slc6-gcc49-opt/lib -fvisibility=hidden -o /afs/cern.ch/user/m/mmelodea/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.8-Carbon-x86_64-2.7.10-64/tmp2k6F0s/75f4c6515305ea530af50178aa318ddb.so /afs/cern.ch/user/m/mmelodea/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.8-Carbon-x86_64-2.7.10-64/tmp2k6F0s/mod.cpp -lblas -lpython2.7
/tmp/mmelodea/ccjClQji.s: Assembler messages:
/tmp/mmelodea/ccjClQji.s:3207: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'

Traceback (most recent call last):
  File "higgs_keras_trainer.py", line 85, in <module>
    model.fit(X_train, Y_train, nb_epoch=nepochs, batch_size=37, verbose=2)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/keras/engine/training.py", line 1168, in fit
    self._make_train_function()
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/keras/engine/training.py", line 767, in _make_train_function
    **self._function_kwargs)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 969, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 955, in __init__
    **kwargs)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/vm.py", line 1063, in make_all
    impl=impl))
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "/afs/cern.ch/user/m/mmelodea/keras/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2309, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Dot22(dense_input_1, dense_1_W), '\n', "Compilation failed (return status=1): /tmp/mmelodea/ccjClQji.s: Assembler messages:. /tmp/mmelodea/ccjClQji.s:3207: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'. ", '[Dot22(dense_input_1, dense_1_W)]')

**Comment by lamblin** [comment]
Which version of Theano are you using?
Could you try with the latest release candidate, or master from GitHub?

**Comment by mmelodea** [comment]
Hi lamblin,

thanks for replying. I'm had installed the latest version through pip inside the virtualenv environment. I just tried now your suggestion. I downloaded the Theano from master branch on github and installed it. It's version "Theano==0.9.0rc1". The same error still arises. It also prints a lot of code before the error message. I've attached the full output in case it can helps.
[keras_error.txt](https://github.com/Theano/Theano/files/795369/keras_error.txt)

**Comment by nouiz** [comment]
See this work around that workmed many times. Most of the time this is a
bug in g++ or a problem with different linker/compiler version.

https://github.com/Theano/Theano/issues/3780#issuecomment-164843114

**Comment by mmelodea** [comment]
Hi nouiz,

thank you very much! That worked! I would like just to ask one thing more... I tested the first option for that Theano flag (theano.config.gcc.cxxflags = '-match=core2') and it worked but, I got the warning message below. That's normal? Also, is it possible to find out which option should I use on that flag, I mean the optimal?

"WARNING (theano.gof.cmodule): WARNING: your Theano flags `gcc.cxxflags` specify an `-march=X` flags.
It is better to let Theano/g++ find it automatically, but we don't do it now"

**Comment by nouiz** [comment]
There is no way to remove that warning. As it happen frequently that bug,
maybe we should remove it? Or at least, we should give a way to remove it.

@abergeron, @lamblin, what do you think?

**Comment by nouiz** [comment]
To know the -march value that will work for you, you will need to test them
yourself. I don't have a better suggestion.

**Comment by mmelodea** [comment]
Thank you so much!
That's enough for me! Theano is running now without problem.
So, I can close this issue, right.
