### ISSUE TITLE
Inconsistency of float64/float32 on cpu and gpu

### ISSUE THREAD

**Issue by botev** [Theano/Theano#5624]
I have in `.theanorc` the flag for warnings if `float64` are present. Running this on CPU makes no raises at all. Running this on gpu gives me consistently erros of the type:
```
ERROR (theano.gof.opt): Optimization failure due to: local_gpua_gemv
ERROR (theano.gof.opt): node: CGemv{no_inplace}(AllocEmpty{dtype='float32'}.0, TensorConstant{1.0}, InplaceDimShuffle{2,1}.0, InplaceDimShuffle{0}.0, TensorConstant{0.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gof/opt.py", line 1973, in process_node
    replacements = lopt.transform(node)
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gpuarray/opt.py", line 234, in local_opt
    new_op(*node.inputs, return_list=True)]
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gpuarray/blas.py", line 53, in make_node
    alpha = as_tensor_variable(alpha).astype('float64')
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/var.py", line 458, in astype
    return theano.tensor.cast(self, dtype)
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/basic.py", line 1179, in cast
    return _cast_mapping[dtype](x)
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/elemwise.py", line 581, in make_node
    out_broadcastables)]
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/elemwise.py", line 580, in <listcomp>
    for dtype, broadcastable in izip(out_dtypes,
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gof/type.py", line 405, in __call__
    return utils.add_tag_trace(self.make_variable(name))
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/type.py", line 353, in make_variable
    return self.Variable(self, name=name)
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/var.py", line 821, in __init__
    raise Exception(msg)
Exception: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
```
Running with `optimizaiton=None` also raises 0 exceptions. This more or less means there is a bugged optmizer that introduces this on the gpu. 

With pdb I get to here:
```
-> self.train_fn = th.function([x_index], cost, updates=updates)                                                                                                 [17/1928]
  /share/apps/barber/system/lib/python3.6/site-packages/theano/compile/function.py(326)function()
-> output_keys=output_keys)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/compile/pfunc.py(486)pfunc()
-> output_keys=output_keys)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/compile/function_module.py(1794)orig_function()
-> output_keys=output_keys).create(
  /share/apps/barber/system/lib/python3.6/site-packages/theano/compile/function_module.py(1474)__init__()
-> optimizer_profile = optimizer(fgraph)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/opt.py(98)__call__()
-> return self.optimize(fgraph)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/opt.py(87)optimize()
-> ret = self.apply(fgraph, *args, **kwargs)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/opt.py(235)apply()
-> sub_prof = optimizer.optimize(fgraph)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/opt.py(87)optimize()
-> ret = self.apply(fgraph, *args, **kwargs)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/opt.py(235)apply()
-> sub_prof = optimizer.optimize(fgraph)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/opt.py(87)optimize()
-> ret = self.apply(fgraph, *args, **kwargs)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gpuarray/opt.py(391)apply()
-> outputs = new_ops(*[mapping[i] for i in node.inputs], return_list=True)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/op.py(604)__call__()
-> node = self.make_node(*inputs, **kwargs)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gpuarray/blas.py(245)make_node()
-> alpha = as_tensor_variable(alpha).astype('float64')
  /share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/var.py(458)astype()
-> return theano.tensor.cast(self, dtype)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/basic.py(1179)cast()
-> return _cast_mapping[dtype](x)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/op.py(604)__call__()
-> node = self.make_node(*inputs, **kwargs)
  /share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/elemwise.py(581)make_node()
-> out_broadcastables)]
  /share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/elemwise.py(580)<listcomp>()
-> for dtype, broadcastable in izip(out_dtypes,
  /share/apps/barber/system/lib/python3.6/site-packages/theano/gof/type.py(405)__call__()
-> return utils.add_tag_trace(self.make_variable(name))
  /share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/type.py(353)make_variable()
-> return self.Variable(self, name=name)
> /share/apps/barber/system/lib/python3.6/site-packages/theano/tensor/var.py(824)__init__()->None
-> pdb.set_trace()
(Pdb) th.config.floatX                  
'float32'
```
Note that I'm using the bleeding edge theano wtih `libgpuarray` Cuda 8.0 and Cudnn 5.1

**Comment by nouiz** [comment]
This isn't a bugged optimizer. For complicated reason, we pass some scalar
to cudnn/cublas as double in the new back-end to allow supporting float32
and float64.


Anyway, this PR should remove that problem, can you try it?

https://github.com/Theano/Theano/pull/5625

thanks for the report.
