### ISSUE TITLE
Problem running theano with multiple  GPUs. 

### ISSUE THREAD

**Issue by hkhanal** [Theano/Theano#5630]
Hello, 
I am having hard time running theano in multiple  GPUs.  Following packages  are installed in Ubuntu 14.02

1.  Dev version Theano
2. GPU Array backend [libgpuarray](http://deeplearning.net/software/libgpuarray/installation.html)
3. cuDNN v5
4. Cuda 7.0

It works for single GPUs  without  "contexts" in  THEANO_FLAG .  Contexts for multiple GPUs still works for simple theano programming as given in  the [ link](http://deeplearning.net/software/theano/tutorial/using_multi_gpu.html#a-simple-graph-on-two-gpus). 

But the problem is , it does not works for deep learning  optimization and throws the following error.  Any suggestions and  help will be highly appricated . Thank you

hkhanal@dev-nvidia:~/deeplearning/supervised_learning/DBN$ THEANO_FLAGS="contexts=dev0->cuda0;dev1->cuda1;dev2->cuda2;dev3->cuda3,lib.cnmem=1" python train_model.py
Using cuDNN version 5005 on context dev0
Mapped name dev0 to device cuda0: GeForce GTX TITAN X (0000:0A:00.0)
Using cuDNN version 5005 on context dev1
Mapped name dev1 to device cuda1: GeForce GTX TITAN X (0000:09:00.0)
Using cuDNN version 5005 on context dev2
Mapped name dev2 to device cuda2: GeForce GTX TITAN X (0000:06:00.0)
Using cuDNN version 5005 on context dev3
Mapped name dev3 to device cuda3: GeForce GTX TITAN X (0000:05:00.0)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gpuarray.opt.GraphToGPU object at 0x7f57bfe43850>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/hkhanal/software/Theano-master/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/hkhanal/software/Theano-master/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/hkhanal/software/Theano-master/theano/gpuarray/opt.py", line 320, in apply
    target = infer_context_name(*fgraph.inputs)
  File "/home/hkhanal/software/Theano-master/theano/gpuarray/basic_ops.py", line 122, in infer_context_name
    raise ValueError("Could not infer context from inputs")
ValueError: Could not infer context from inputs

ERROR (theano.gof.opt): Optimization failure due to: local_gpua_mrg
ERROR (theano.gof.opt): node: mrg_uniform{TensorType(float32, matrix),no_inplace}(<TensorType(int32, matrix)>, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/hkhanal/software/Theano-master/theano/gof/opt.py", line 1973, in process_node
    replacements = lopt.transform(node)
  File "/home/hkhanal/software/Theano-master/theano/sandbox/rng_mrg.py", line 1630, in local_gpua_mrg
    context_name = infer_context_name(*node.inputs)
  File "/home/hkhanal/software/Theano-master/theano/gpuarray/basic_ops.py", line 122, in infer_context_name
    raise ValueError("Could not infer context from inputs")
ValueError: Could not infer context from inputs

ERROR (theano.gof.opt): Optimization failure due to: local_gpua_mrg
ERROR (theano.gof.opt): node: mrg_uniform{TensorType(float32, matrix),no_inplace}(<TensorType(int32, matrix)>, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/hkhanal/software/Theano-master/theano/gof/opt.py", line 1973, in process_node
    replacements = lopt.transform(node)
  File "/home/hkhanal/software/Theano-master/theano/sandbox/rng_mrg.py", line 1630, in local_gpua_mrg
    context_name = infer_context_name(*node.inputs)
  File "/home/hkhanal/software/Theano-master/theano/gpuarray/basic_ops.py", line 122, in infer_context_name
    raise ValueError("Could not infer context from inputs")
ValueError: Could not infer context from inputs

If you have any questions on Theano, please ask your questions in either [theano-user mailing list](https://groups.google.com/forum/#!forum/theano-users) or [stackoverflow](http://stackoverflow.com/) with the "theano" tag.

Use issue only to report bugs or to ask for new features in Theano.

Before reporting a bug, update to Theano development version. Maybe it
is already fixed. If not, tell us the Theano flags and Theano version
that generate the problem. If it is a regression, can do a "git
bisect" to idenfy when the problem appeard. This really help fix it
rapidly.

If you add a feature request, describe in which case it will be useful.

**Comment by Sentient07** [comment]
I think the context would be inferred correctly only if you set the device parameter. could you set `THEANO_FLAGS=device=cudaN` and try again ?

**Comment by jiangnanhugo** [comment]
it doesn't work on my setting:
1. Dev version Theano
2. GPU Array backend libgpuarray
3. cuDNN v5.103
4. Cuda 7.5
the same error. 

And `THEANO_FLAGS=device=cudaN` has been tried, the problem `raise ValueError("Could not infer context from inputs")` is fixed.

**Comment by lamblin** [comment]
You probably need to change your code to be more explicit about which operations you want to execute on which GPU.
When there is only one GPU (device=cudaN), then it's easy: Theano uses the default context.
If there are several contexts, then you have to use `.transfer('cudaX')` to explicitly add transfers to your graph.
