### ISSUE TITLE
Theano tries to import libraries (and fails) when running in CPU-mode

### ISSUE THREAD

**Issue by apacha** [Theano/Theano#5653]
I am using the following simple script to test open-blas when I encountered a strange behavior:

```
import numpy as np
import time
import theano

print('blas.ldflags=', theano.config.blas.ldflags)

A = np.random.rand(1000, 10000).astype(theano.config.floatX)
B = np.random.rand(10000, 1000).astype(theano.config.floatX)
np_start = time.time()
AB = A.dot(B)
np_end = time.time()
X, Y = theano.tensor.matrices('XY')
mf = theano.function([X, Y], X.dot(Y))
t_start = time.time()
tAB = mf(A, B)
t_end = time.time()
print("numpy time: %f[s], theano time: %f[s] (times should be close when run on CPU!)" % (
np_end - np_start, t_end - t_start))
print("Result difference: %f" % (np.abs(AB - tAB).max(), ))
```

When running with the following GPU-flags
`D:\Entwicklungen\DeepLearningForComputerVision\Assignment3\OtherScripts>echo %THEANO_FLAGS%
floatX=float32,device=gpu,dnn.enabled=False,lib.cnmem=0.8,blas.ldflags=-LC:\\Programming\\OpenBLAS-v0.2.19-Win64-int32\\bin -lopenblas`

The result is as expected 
`numpy time: 0.797226[s], theano time: 0.043567[s] (times should be close when run on CPU!)
Result difference: 0.019287`

But when running the CPU-flags, I get the DLL load failed exception:
```
D:\Entwicklungen\DeepLearningForComputerVision\Assignment3\OtherScripts>echo %THEANO_FLAGS%
floatX=float32,device=cpu,lib.cnmem=0.8,blas.ldflags=-LC:\\Programming\\OpenBLAS-v0.2.19-Win64-int32\\bin -lopenblas

D:\Entwicklungen\DeepLearningForComputerVision\Assignment3\OtherScripts>python openblas_test.py
blas.ldflags= -LC:\Programming\OpenBLAS-v0.2.19-Win64-int32\bin -lopenblas
Importing {0} tmp53h6ydg9.m13a84de18947238e6a7c2ce4f64f7854
Traceback (most recent call last):
  File "openblas_test.py", line 13, in <module>
    mf = theano.function([X, Y], X.dot(Y))
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\compile\function_module.py", line 1777, in orig_function
    defaults)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\compile\function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\vm.py", line 1003, in make_all
    no_recycling))
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\op.py", line 970, in make_thunk
    no_recycling)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\cmodule.py", line 1143, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\cmodule.py", line 2214, in compile_str
    return dlimport(lib_filename)
  File "C:\Programming\Anaconda3\lib\site-packages\theano-0.8.2-py3.5.egg\theano\gof\cmodule.py", line 300, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: The specified module could not be found.
```

Investigating this a little more, I tried different versions of Theano (0.8.2 and 0.9-rc2) and experienced the same issue with both versions. I am not sure, if it is directly caused by Theano, because I found out by modifying cmodule.py that the script tries to import the built libraries from the Theano-Cache (e.g. `Importing {0} tmp53h6ydg9.m13a84de18947238e6a7c2ce4f64f7854`). When running in GPU-mode, it correctly creates those libraries in the Theano-cache, but when running in the CPU-mode the libraries it tries to load, somehow are not created inside the theano-cache and can thus not be imported.

I've also tried adding `dnn.enabled=False` and removing `cnmem=0.8` but that did not change anything.

Interestingly enough is that the following script 
```
#from theano import function, config, shared, sandbox
from theano import *
import theano.tensor as T
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], T.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, T.Elemwise) for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')
```
runs though and even imports libraries from the theano-cache:

```
D:\Entwicklungen\DeepLearningForComputerVision\Assignment3\OtherScripts>python cpu_gpu_test.py
Importing {0} lazylinker_ext.lazylinker_ext
Importing {0} cutils_ext.cutils_ext
Importing {0} tmpbl1kzv46.m41cf678f6846ccb3ca16f8c5a808ad9f
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 13.299426 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu
```

I am running on the following environment:

- Windows 10
- Python 3.5 (with Anaconda 3)
- Theano (Version 0.8.2 or 0.9-rc2)
- Keras (Version 1.2.2)
- Cuda-8.0.61
- Cudnn-8.0-windows-10-x64-v5.1
- The rest as recommended by https://github.com/philferriere/dlwin

It seems that a lot of other users experience the same issue:

- https://stackoverflow.com/questions/34508431/installing-theano-on-windows-dll-load-failed
- https://stackoverflow.com/questions/41000780/error-running-theano-test-importerror-dll-load-failed-a-dynamic-link-libra?noredirect=1&lq=1 (my earlier question on SO)

Since I now have a little more time, I will gladly provide more information if needed and help debugging.

**Comment by lamblin** [comment]
Could you set `nocleanup=True` in the config flags? This should prevent the libraries in `tmpXXX...` from being deleted if the import fails.
Then, if you find one of these that failed, could you open it with the [dependency walker](http://www.dependencywalker.com/) and see if some missing dependency comes up?

**Comment by nouiz** [comment]
As no news and there have been many related fixes I'll close this issue. If someone still have problems, reopen and add information.
