### ISSUE TITLE
-- sporadic error: RuntimeError: Error in the elemwise call

### ISSUE THREAD

**Issue by jc-Rosichini** [Theano/Theano#5659]
Hi
I just want to report a **sporadic error** which happens from time to time during a running training cycle.
I'm really unable to reproduce it on a deterministic way since it may happen unexpectedly after 100+ , 300+ or more training epochs...

**my config:**
theano: 0.9.0rc2.dev-674f8d5148cb8dcea446e7243e629d8f83647da5
numpy: 1.11.0
pygpu: 0.6.1
lasagne: 0.2.dev1
Using cuDNN version 5105
GeForce GTX 980M
Windows 10 x64

**symptom**

Traceback (most recent call last):
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Error in the elemwise call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 610, in <module>
    initiate_training(cf)
  File "train.py", line 576, in initiate_training
    train(cf)
  File "train.py", line 445, in train
    history, nan_occured = batch_loop(train_iter, train_fn, epoch, 'train', history, limit_randomize)
  File "train.py", line 98, in batch_loop
    loss, I, U, acc = f(X, y) # f  train_function or val_function
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\link.py", line 141, in raise_with_op
    detailed_err_msg = "\nApply node that caused the error: " + str(node)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\graph.py", line 180, in __str__
    return op_as_string(self.inputs, self)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\graph.py", line 1233, in op_as_string
    strs = as_string(i, op.inputs, leaf_formatter, node_formatter)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\graph.py", line 1313, in as_string
    return [describe(output) for output in o]
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\graph.py", line 1313, in <listcomp>
    return [describe(output) for output in o]
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\graph.py", line 1311, in describe
    return leaf_formatter(r)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gpuarray\type.py", line 577, in __str__
    return "GpuArrayConstant{%s}" % np_data
  File "pygpu\gpuarray.pyx", line 2051, in pygpu.gpuarray.GpuArray.__str__ (pygpu/gpuarray.c:26220)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
  File "pygpu\gpuarray.pyx", line 1664, in pygpu.gpuarray.GpuArray.__array__ (pygpu/gpuarray.c:21420)
  File "pygpu\gpuarray.pyx", line 1371, in pygpu.gpuarray._pygpu_as_ndarray (pygpu/gpuarray.c:18126)
  File "pygpu\gpuarray.pyx", line 384, in pygpu.gpuarray.array_read (pygpu/gpuarray.c:6727)
pygpu.gpuarray.GpuArrayException: b'unspecified launch failure'

**Comment by jc-Rosichini** [comment]
Could this be tied to the following test failure???

E:\FC_DenseNet_mars>python -c "import pygpu;pygpu.test()"
pygpu is installed in C:\Users\PCGP1\AppData\Roaming\Python\Python35\site-packages\pygpu-0.6.1-py3.5-win-amd64.egg\pygpu
NumPy version 1.11.0
NumPy relaxed strides checking option: False
NumPy is installed in C:\Users\PCGP1\Anaconda3\lib\site-packages\numpy
Python version 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
*** Testing for GeForce GTX 980M
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: pygpu.tests.test_elemwise.test_infinity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\PCGP1\AppData\Roaming\Python\Python35\site-packages\pygpu-0.6.1-py3.5-win-amd64.egg\pygpu\tests\test_elemwise.py", line 324, in test_infinity
    preamble=preamble)
  File "pygpu\_elemwise.pyx", line 137, in pygpu._elemwise.GpuElemwise.__cinit__ (pygpu/_elemwise.c:3099)
pygpu.gpuarray.GpuArrayException: Could not initialize C GpuElemwise instance

----------------------------------------------------------------------
Ran 6895 tests in 241.148s

FAILED (errors=1)

**Comment by nouiz** [comment]
Hi,

As your GPU is shared for the monitor and the computation, this raise some concern. If an application need extra GPU memory for the screen (like firefox, chrome, ...) as they use OpenGL or other stuff like that, and there is no memory available on the GPU, this will steal the memory from the CUDA software and return strange error message.

If you don't use your laptop while it compute for hours, do you have the bug still happening? If you don't have this problem, then this could be the problem. Another way to test this it to make the model much smaller to be sure no memory is missing. If it don't happen anymore, then this could be the solution.

It could be also an hardware problem due to overheating...

Make sure to use Therano 0.9rc3 or the dev version, I forgot all the fix we did in the new back-end, maybe one could cover this.

**Comment by jc-Rosichini** [comment]
Thanks Frederic,

I've been thinking too about a possible memory issue with the GPU, although the reported message is not the 'regular' out of memory. Anyway I'll move to 0.9rc3 and see what happens.

Btw. Is 'ERROR: pygpu.tests.test_elemwise.test_infinity' an identified and potentially problematic issue? I'm still getting it.

Rgds - Jean-Claude

**Comment by abergeron** [comment]
The first error about unspecified launch failure is on windows 99.99% of the time because a kernel took too long and Windows killed it.

The other error about not being able to compile the GpuElemwise code for test_infinity is different, and is tracked in https://github.com/Theano/libgpuarray/issues/370.

**Comment by jc-Rosichini** [comment]
BTW. For first error, changing the default timeout value in Windows registry seems to fix it:
ie go under the windows registry editor and change TdrDelay from default 2 to 8 for instance:

TdrDelay - Specifies the number of seconds that the GPU can delay the preempt request from the GPU scheduler. This is effectively the timeout threshold. The default value is 2 seconds.
KeyPath   : HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDrivers
KeyValue  : TdrDelay
ValueType : REG_DWORD
ValueData : Number of seconds to delay; 2 seconds is the default

**Comment by lamblin** [comment]
OK, so we should document it, maybe in the FAQ.

**Comment by abergeron** [comment]
I'm not sure we should document registry editing in the FAQ.  It is sort of easy to break your machine if you don't know what you're doing.

We could provide a registry patch file to download and apply, but then again I would much rather that we encourage people not to train on windows machines as it is a bad idea.
