### ISSUE TITLE
Error when removing compilelock 

### ISSUE THREAD

**Issue by cshanbo** [Theano/Theano#5694]
Hi,
I'm recently trying to use [platoon](https://github.com/mila-udem/platoon) to build a `multi-node, multi-GPU`, `Theano`-based training system (I'm using the latest Theano version on Github).

I found that when running multiple tasks, there will be compile lock occurs. I'm guessing that `Theano` try to delete those `compile locks` when the actual work is done. This is a great design and won't be a problem in a `single-node` scenario, while there will be a `No such file or directory` in a `multi-node` scenario. I think `Theano` try to remove those `compile lock` on another node.

So, my question is: is there any chance for users to control whether to delete compile lock, or passing the necessary arguments to make the `removing` operation recognize different `nodes` since the `removing` operation is transparent to users right now.

Thank you 

### FYI, The error is like:

```
Traceback (most recent call last):
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cmodule.py", line 1481, in _on_atexit
    func(*targs, **kargs)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cmodule.py", line 1481, in _on_atexit
    self.clear_unversioned()
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cmodule.py", line 1442, in clear_unversioned
    self.clear_unversioned()
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cmodule.py", line 1442, in clear_unversioned
    False)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cmodule.py", line 340, in module_name_from_dir
    files = os.listdir(dirname)
    False)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cmodule.py", line 340, in module_name_from_dir
    files = os.listdir(dirname)
OSError: [Errno 2] No such file or directory: '/search/odin/chengshanbo/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.13-64/tmpuT3_lQ'
OSError: [Errno 2] No such file or directory: '/search/odin/chengshanbo/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.13-64/tmpuT3_lQ'
```

**Comment by lamblin** [comment]
These are not locks, these are directories containing C modules without a version number (so that they are not cached).
I think it would be OK to be resilient to the case where they have already been deleted by another process, and just pass.

**Comment by nouiz** [comment]
I have a fix, thanks for this report:

https://github.com/Theano/Theano/pull/5697

**Comment by nouiz** [comment]
The fix is now merged. Can you update Theano and if you see other problems, send us the stack trace again? This is stuff that is hard to test, so if it happen again, tell us.

**Comment by imk1** [comment]
This fix did not work for me.
