### ISSUE TITLE
Mismatch when copying CNN function

### ISSUE THREAD

**Issue by ASpeiser** [Theano/Theano#5695]
```
import numpy as np
import theano.tensor as T
import theano
from theano import config
import lasagne
import lasagne.nonlinearities as lnl
import lasagne.layers as ll

nn = ll.InputLayer((None, None))
nn = ll.DimshuffleLayer(nn, (0, 'x', 1))

nn = ll.Conv1DLayer(nn, num_filters = 5, filter_size = 7, stride =1, pad = 'same',nonlinearity=lnl.tanh)
nn = ll.Conv1DLayer(nn, num_filters = 5, filter_size = 7, stride =1, pad = 'same',nonlinearity=lnl.tanh)

nn = ll.DimshuffleLayer(nn,(0,2,1))
nn = ll.FlattenLayer(nn)

Input = T.matrix('X')
test = np.random.normal(size=[10,100]).astype(config.floatX)

func = theano.function([Input], ll.get_output(nn,inputs=Input))
copyfunc = func.copy()

print(np.max(func(test)-copyfunc(test)))

1.6629354
```

The bug seems to fairly specific. 

1: Results match when I exchange 'same' with 'valid'
2: Results match when I only use one convolutional layer. 
3: The mismatch only occurs for the GPU and only when I use the old cuda backend. 

I tried to come up with a simple vanilla theano script that reproduces the issue but failed.
i.e. this works fine:

```
rng = np.random.RandomState(23455)
from theano.tensor.nnet import conv2d
example = np.random.normal(size=[1, 3, 639, 516]).astype(config.floatX)

input = T.tensor4(name='input')

w_shp = (3, 3, 9, 9)
W = theano.shared( np.asarray(
            rng.uniform(low=-1.0, high=1.0, size=w_shp),dtype=input.dtype), name ='W')

conv_out = conv2d(input,W, border_mode='half')
conv_out = conv2d(conv_out, W, border_mode='half')
output = T.nnet.relu(conv_out)

f = theano.function([input], output)
f_copy = f.copy()
np.max(f(example)-f_copy(example))
0.0
```
So I guess the additional dimshuffles/brodcasts in the lasagne implementation are involved.
I already posted in the lasagne group: https://groups.google.com/forum/#!topic/lasagne-users/G-eez5pJPaM

**Comment by f0k** [comment]
I've been able to boil it down:
```python
#!/usr/bin/env python
import numpy as np
np.random.seed(0)
import theano.tensor as T
import theano

# input
x = T.tensor4('X')
y = x
# conv2d - must have border_mode != 'valid', and given filter_shape
w = theano.shared(np.random.randn(5, 1, 1, 7).astype(theano.config.floatX))
y = T.nnet.conv2d(y, w, filter_shape=(5, 1, 1, 7), border_mode='full')
# conv2d - must be present for the bug to appear
w = theano.shared(np.random.randn(5, 5, 1, 7).astype(theano.config.floatX))
y = T.nnet.conv2d(y, w)

# compile function and copy it
func = theano.function([x], y)
copyfunc = func.copy()

# run
test = np.random.normal(size=[10, 1, 1, 100]).astype(theano.config.floatX)
out1 = func(test)
out2 = copyfunc(test)
# first bug: out1 is np.ndarray, out2 is single-element list
print(type(out1))
print(type(out2))
print(type(out2[0]))
# second bug: results are not the same
print(out1.shape)
print(out2[0].shape)
print(np.max(out1 - out2[0]))
```

**Comment by lamblin** [comment]
Could you give us a debugprint of both functions (and also without the `filter_shape`)?
How big is the difference?

I can see how specifying the shape may select a different implementation of conv2d during the optimization phase. And if the selected implementation is a non-deterministic cuDNN backward pass, it could explain small differences.
The single-element list is a special case in `function`, I think it should be added in `.copy()` as well.

**Comment by f0k** [comment]
> Could you give us a debugprint of both functions

Tried that before, but you cannot debugprint a copied function. We could count that a third bug:
```
Traceback (most recent call last):
  File "copybug.py", line 34, in <module>
    theano.printing.debugprint(copyfunc)
  File "/raid/user/jan/install/Theano-git/theano/printing.py", line 177, in debugprint
    if any([p for p in profile_list if p is not None and p.fct_callcount > 0]):
AttributeError: 'bool' object has no attribute 'fct_callcount'
```
I can debugprint `func.maker.graph.outputs[0]`, they're identical:
```python
s1 = theano.printing.debugprint(func.maker.fgraph.outputs[0], file='str')
s2 = theano.printing.debugprint(copyfunc.maker.fgraph.outputs[0], file='str')
print(s1 == s2)  # prints True
```

> I can see how specifying the shape may select a different implementation of conv2d during the optimization phase. And if the selected implementation is a non-deterministic cuDNN backward pass, it could explain small differences.

The difference with the random seed I gave is 54.9456. It must be something more serious, like not setting up the copied GpuDnnConvDesc correctly, or not copying over all of its attributes. Note that this does not happen in the new backend or when using the CPU.

> The single-element list is a special case in function, I think it should be added in .copy() as well.

Yes, that's the easier of the problems! (This probably affects all backends.)

**Comment by f0k** [comment]
> Could you give us a debugprint of both functions

<details><summary>debugprint including filter_shape</summary>

```
HostFromGpu [id A] ''   
 |GpuDnnConv{algo='time_once', inplace=True} [id B] ''   
   |GpuContiguous [id C] ''   
   | |GpuDnnConv{algo='time_once', inplace=True} [id D] ''   
   |   |GpuContiguous [id E] ''   
   |   | |GpuFromHost [id F] ''   
   |   |   |X [id G]
   |   |GpuContiguous [id H] ''   
   |   | |Assert{msg='AbstractConv shape mismatch: shape of filters does not match given kshp.'} [id I] ''   
   |   |   |Assert{msg='AbstractConv shape mismatch: shape of filters does not match given kshp.'} [id J] ''   
   |   |   | |<CudaNdarrayType(float32, 4D)> [id K]
   |   |   | |Elemwise{eq,no_inplace} [id L] ''   
   |   |   | | |Shape_i{0} [id M] ''   
   |   |   | | | |<CudaNdarrayType(float32, 4D)> [id K]
   |   |   | | |TensorConstant{5} [id N]
   |   |   | |Elemwise{eq,no_inplace} [id O] ''   
   |   |   | | |Shape_i{1} [id P] ''   
   |   |   | | | |<CudaNdarrayType(float32, 4D)> [id K]
   |   |   | | |TensorConstant{1} [id Q]
   |   |   | |Elemwise{eq,no_inplace} [id R] ''   
   |   |   | | |Shape_i{2} [id S] ''   
   |   |   | | | |<CudaNdarrayType(float32, 4D)> [id K]
   |   |   | | |TensorConstant{1} [id Q]
   |   |   | |Elemwise{eq,no_inplace} [id T] ''   
   |   |   |   |Shape_i{3} [id U] ''   
   |   |   |   | |<CudaNdarrayType(float32, 4D)> [id K]
   |   |   |   |TensorConstant{7} [id V]
   |   |   |Elemwise{eq,no_inplace} [id L] ''   
   |   |   |Elemwise{eq,no_inplace} [id O] ''   
   |   |   |Elemwise{eq,no_inplace} [id R] ''   
   |   |   |Elemwise{eq,no_inplace} [id T] ''   
   |   |GpuAllocEmpty [id W] ''   
   |   | |Assert{msg='The convolution would produce an invalid shape (dim[0] < 0).'} [id X] ''   
   |   | | |Shape_i{0} [id Y] ''   
   |   | | | |X [id G]
   |   | | |Elemwise{ge,no_inplace} [id Z] ''   
   |   | |   |Shape_i{0} [id Y] ''   
   |   | |   |TensorConstant{0} [id BA]
   |   | |Assert{msg='The convolution would produce an invalid shape (dim[1] < 0).'} [id BB] ''   
   |   | | |Shape_i{0} [id M] ''   
   |   | | |Elemwise{ge,no_inplace} [id BC] ''   
   |   | |   |Shape_i{0} [id M] ''   
   |   | |   |TensorConstant{0} [id BA]
   |   | |Assert{msg='The convolution would produce an invalid shape (dim[2] <= 0).'} [id BD] ''   
   |   | | |Elemwise{Composite{(((i0 + (i1 * (Composite{(((i0 - i1) * i2) + i1)}(i2, i3, i4) - i3))) - Composite{(((i0 - i1) * i2) + i1)}(i2, i3, i4)) + i3)}}[(0, 2)] [id BE] ''   
   |   | | | |Shape_i{2} [id BF] ''   
   |   | | | | |X [id G]
   |   | | | |TensorConstant{2} [id BG]
   |   | | | |Shape_i{2} [id S] ''   
   |   | | | |TensorConstant{1} [id Q]
   |   | | | |TensorConstant{1} [id BH]
   |   | | |Elemwise{gt,no_inplace} [id BI] ''   
   |   | |   |Elemwise{Composite{(((i0 + (i1 * (Composite{(((i0 - i1) * i2) + i1)}(i2, i3, i4) - i3))) - Composite{(((i0 - i1) * i2) + i1)}(i2, i3, i4)) + i3)}}[(0, 2)] [id BE] ''   
   |   | |   |TensorConstant{0} [id BA]
   |   | |Assert{msg='The convolution would produce an invalid shape (dim[3] <= 0).'} [id BJ] ''   
   |   |   |Elemwise{Composite{(((i0 + (i1 * (Composite{(((i0 - i1) * i2) + i1)}(i2, i3, i4) - i3))) - Composite{(((i0 - i1) * i2) + i1)}(i2, i3, i4)) + i3)}}[(0, 2)] [id BK] ''   
   |   |   | |Shape_i{3} [id BL] ''   
   |   |   | | |X [id G]
   |   |   | |TensorConstant{2} [id BG]
   |   |   | |Shape_i{3} [id U] ''   
   |   |   | |TensorConstant{1} [id Q]
   |   |   | |TensorConstant{1} [id BH]
   |   |   |Elemwise{gt,no_inplace} [id BM] ''   
   |   |     |Elemwise{Composite{(((i0 + (i1 * (Composite{(((i0 - i1) * i2) + i1)}(i2, i3, i4) - i3))) - Composite{(((i0 - i1) * i2) + i1)}(i2, i3, i4)) + i3)}}[(0, 2)] [id BK] ''   
   |   |     |TensorConstant{0} [id BA]
   |   |GpuDnnConvDesc{border_mode='full', subsample=(1, 1), conv_mode='conv', precision='float32'} [id BN] ''   
   |   | |MakeVector{dtype='int64'} [id BO] ''   
   |   | | |Shape_i{0} [id Y] ''   
   |   | | |Shape_i{1} [id BP] ''   
   |   | | | |X [id G]
   |   | | |Shape_i{2} [id BF] ''   
   |   | | |Shape_i{3} [id BL] ''   
   |   | |MakeVector{dtype='int64'} [id BQ] ''   
   |   |   |Shape_i{0} [id M] ''   
   |   |   |Shape_i{1} [id P] ''   
   |   |   |Shape_i{2} [id S] ''   
   |   |   |Shape_i{3} [id U] ''   
   |   |Constant{1.0} [id BR]
   |   |Constant{0.0} [id BS]
   |GpuContiguous [id BT] ''   
   | |<CudaNdarrayType(float32, 4D)> [id BU]
   |GpuAllocEmpty [id BV] ''   
   | |Assert{msg='The convolution would produce an invalid shape (dim[0] < 0).'} [id X] ''   
   | |Assert{msg='The convolution would produce an invalid shape (dim[1] < 0).'} [id BW] ''   
   | | |Shape_i{0} [id BX] ''   
   | | | |<CudaNdarrayType(float32, 4D)> [id BU]
   | | |Elemwise{ge,no_inplace} [id BY] ''   
   | |   |Shape_i{0} [id BX] ''   
   | |   |TensorConstant{0} [id BA]
   | |Assert{msg='The convolution would produce an invalid shape (dim[2] <= 0).'} [id BZ] ''   
   | | |Elemwise{Composite{((i0 - (((i1 - i2) * i3) + i2)) + i2)}}[(0, 0)] [id CA] ''   
   | | | |Elemwise{Composite{((i0 - i1) + i1)}}[(0, 0)] [id CB] ''   
   | | | | |Shape_i{2} [id BF] ''   
   | | | | |TensorConstant{1} [id Q]
   | | | |Shape_i{2} [id CC] ''   
   | | | | |<CudaNdarrayType(float32, 4D)> [id BU]
   | | | |TensorConstant{1} [id Q]
   | | | |TensorConstant{1} [id BH]
   | | |Elemwise{gt,no_inplace} [id CD] ''   
   | |   |Elemwise{Composite{((i0 - (((i1 - i2) * i3) + i2)) + i2)}}[(0, 0)] [id CA] ''   
   | |   |TensorConstant{0} [id BA]
   | |Assert{msg='The convolution would produce an invalid shape (dim[3] <= 0).'} [id CE] ''   
   |   |Elemwise{Composite{((i0 - (((i1 - i2) * i3) + i2)) + i2)}}[(0, 0)] [id CF] ''   
   |   | |Elemwise{Composite{(((i0 + i1) - i2) + i3)}}[(0, 0)] [id CG] ''   
   |   | | |Shape_i{3} [id BL] ''   
   |   | | |TensorConstant{12} [id CH]
   |   | | |TensorConstant{7} [id V]
   |   | | |TensorConstant{1} [id Q]
   |   | |Shape_i{3} [id CI] ''   
   |   | | |<CudaNdarrayType(float32, 4D)> [id BU]
   |   | |TensorConstant{1} [id Q]
   |   | |TensorConstant{1} [id BH]
   |   |Elemwise{gt,no_inplace} [id CJ] ''   
   |     |Elemwise{Composite{((i0 - (((i1 - i2) * i3) + i2)) + i2)}}[(0, 0)] [id CF] ''   
   |     |TensorConstant{0} [id BA]
   |GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'} [id CK] ''   
   | |MakeVector{dtype='int64'} [id CL] ''   
   | | |Shape_i{0} [id Y] ''   
   | | |TensorConstant{5} [id CM]
   | | |Elemwise{Composite{((i0 - i1) + i1)}}[(0, 0)] [id CB] ''   
   | | |Elemwise{Composite{(((i0 + i1) - i2) + i3)}}[(0, 0)] [id CG] ''   
   | |MakeVector{dtype='int64'} [id CN] ''   
   |   |Shape_i{0} [id BX] ''   
   |   |Shape_i{1} [id CO] ''   
   |   | |<CudaNdarrayType(float32, 4D)> [id BU]
   |   |Shape_i{2} [id CC] ''   
   |   |Shape_i{3} [id CI] ''   
   |Constant{1.0} [id BR]
   |Constant{0.0} [id BS]
```
</details>

<details><summary>debugprint without filter_shape</summary>

```
HostFromGpu [id A] ''   
 |GpuDnnConv{algo='time_once', inplace=True} [id B] ''   
   |GpuContiguous [id C] ''   
   | |GpuDnnConv{algo='time_once', inplace=True} [id D] ''   
   |   |GpuContiguous [id E] ''   
   |   | |GpuFromHost [id F] ''   
   |   |   |X [id G]
   |   |GpuContiguous [id H] ''   
   |   | |<CudaNdarrayType(float32, 4D)> [id I]
   |   |GpuAllocEmpty [id J] ''   
   |   | |Assert{msg='The convolution would produce an invalid shape (dim[0] < 0).'} [id K] ''   
   |   | | |Shape_i{0} [id L] ''   
   |   | | | |X [id G]
   |   | | |Elemwise{ge,no_inplace} [id M] ''   
   |   | |   |Shape_i{0} [id L] ''   
   |   | |   |TensorConstant{0} [id N]
   |   | |Assert{msg='The convolution would produce an invalid shape (dim[1] < 0).'} [id O] ''   
   |   | | |Shape_i{0} [id P] ''   
   |   | | | |<CudaNdarrayType(float32, 4D)> [id I]
   |   | | |Elemwise{ge,no_inplace} [id Q] ''   
   |   | |   |Shape_i{0} [id P] ''   
   |   | |   |TensorConstant{0} [id N]
   |   | |Assert{msg='The convolution would produce an invalid shape (dim[2] <= 0).'} [id R] ''   
   |   | | |Elemwise{Composite{(((i0 + (i1 * (Composite{((i0 * i1) + i2)}(i2, i3, i4) - i4))) - Composite{((i0 * i1) + i2)}(i2, i3, i4)) + i4)}} [id S] ''   
   |   | | | |Shape_i{2} [id T] ''   
   |   | | | | |X [id G]
   |   | | | |TensorConstant{2} [id U]
   |   | | | |Elemwise{Sub}[(0, 0)] [id V] ''   
   |   | | | | |Shape_i{2} [id W] ''   
   |   | | | | | |<CudaNdarrayType(float32, 4D)> [id I]
   |   | | | | |TensorConstant{1} [id X]
   |   | | | |TensorConstant{1} [id Y]
   |   | | | |TensorConstant{1} [id X]
   |   | | |Elemwise{gt,no_inplace} [id Z] ''   
   |   | |   |Elemwise{Composite{(((i0 + (i1 * (Composite{((i0 * i1) + i2)}(i2, i3, i4) - i4))) - Composite{((i0 * i1) + i2)}(i2, i3, i4)) + i4)}} [id S] ''   
   |   | |   |TensorConstant{0} [id N]
   |   | |Assert{msg='The convolution would produce an invalid shape (dim[3] <= 0).'} [id BA] ''   
   |   |   |Elemwise{Composite{(((i0 + (i1 * (Composite{((i0 * i1) + i2)}(i2, i3, i4) - i4))) - Composite{((i0 * i1) + i2)}(i2, i3, i4)) + i4)}} [id BB] ''   
   |   |   | |Shape_i{3} [id BC] ''   
   |   |   | | |X [id G]
   |   |   | |TensorConstant{2} [id U]
   |   |   | |Elemwise{Sub}[(0, 0)] [id BD] ''   
   |   |   | | |Shape_i{3} [id BE] ''   
   |   |   | | | |<CudaNdarrayType(float32, 4D)> [id I]
   |   |   | | |TensorConstant{1} [id X]
   |   |   | |TensorConstant{1} [id Y]
   |   |   | |TensorConstant{1} [id X]
   |   |   |Elemwise{gt,no_inplace} [id BF] ''   
   |   |     |Elemwise{Composite{(((i0 + (i1 * (Composite{((i0 * i1) + i2)}(i2, i3, i4) - i4))) - Composite{((i0 * i1) + i2)}(i2, i3, i4)) + i4)}} [id BB] ''   
   |   |     |TensorConstant{0} [id N]
   |   |GpuDnnConvDesc{border_mode='full', subsample=(1, 1), conv_mode='conv', precision='float32'} [id BG] ''   
   |   | |MakeVector{dtype='int64'} [id BH] ''   
   |   | | |Shape_i{0} [id L] ''   
   |   | | |Shape_i{1} [id BI] ''   
   |   | | | |X [id G]
   |   | | |Shape_i{2} [id T] ''   
   |   | | |Shape_i{3} [id BC] ''   
   |   | |MakeVector{dtype='int64'} [id BJ] ''   
   |   |   |Shape_i{0} [id P] ''   
   |   |   |Shape_i{1} [id BK] ''   
   |   |   | |<CudaNdarrayType(float32, 4D)> [id I]
   |   |   |Shape_i{2} [id W] ''   
   |   |   |Shape_i{3} [id BE] ''   
   |   |Constant{1.0} [id BL]
   |   |Constant{0.0} [id BM]
   |GpuContiguous [id BN] ''   
   | |<CudaNdarrayType(float32, 4D)> [id BO]
   |GpuAllocEmpty [id BP] ''   
   | |Assert{msg='The convolution would produce an invalid shape (dim[0] < 0).'} [id K] ''   
   | |Assert{msg='The convolution would produce an invalid shape (dim[1] < 0).'} [id BQ] ''   
   | | |Shape_i{0} [id BR] ''   
   | | | |<CudaNdarrayType(float32, 4D)> [id BO]
   | | |Elemwise{ge,no_inplace} [id BS] ''   
   | |   |Shape_i{0} [id BR] ''   
   | |   |TensorConstant{0} [id N]
   | |Assert{msg='The convolution would produce an invalid shape (dim[2] <= 0).'} [id BT] ''   
   | | |Elemwise{Composite{((i0 - (((i1 - i2) * i3) + i2)) + i2)}}[(0, 0)] [id BU] ''   
   | | | |Elemwise{Composite{(((i0 + (i1 * (Composite{((i0 * i1) + i1)}(i2, i3) - i3))) - Composite{((i0 * i1) + i1)}(i2, i3)) + i3)}}[(0, 0)] [id BV] ''   
   | | | | |Shape_i{2} [id T] ''   
   | | | | |TensorConstant{2} [id U]
   | | | | |Elemwise{Sub}[(0, 0)] [id V] ''   
   | | | | |TensorConstant{1} [id X]
   | | | |Shape_i{2} [id BW] ''   
   | | | | |<CudaNdarrayType(float32, 4D)> [id BO]
   | | | |TensorConstant{1} [id X]
   | | | |TensorConstant{1} [id Y]
   | | |Elemwise{gt,no_inplace} [id BX] ''   
   | |   |Elemwise{Composite{((i0 - (((i1 - i2) * i3) + i2)) + i2)}}[(0, 0)] [id BU] ''   
   | |   |TensorConstant{0} [id N]
   | |Assert{msg='The convolution would produce an invalid shape (dim[3] <= 0).'} [id BY] ''   
   |   |Elemwise{Composite{((i0 - (((i1 - i2) * i3) + i2)) + i2)}}[(0, 0)] [id BZ] ''   
   |   | |Elemwise{Composite{(((i0 + (i1 * (Composite{((i0 * i1) + i1)}(i2, i3) - i3))) - Composite{((i0 * i1) + i1)}(i2, i3)) + i3)}}[(0, 0)] [id CA] ''   
   |   | | |Shape_i{3} [id BC] ''   
   |   | | |TensorConstant{2} [id U]
   |   | | |Elemwise{Sub}[(0, 0)] [id BD] ''   
   |   | | |TensorConstant{1} [id X]
   |   | |Shape_i{3} [id CB] ''   
   |   | | |<CudaNdarrayType(float32, 4D)> [id BO]
   |   | |TensorConstant{1} [id X]
   |   | |TensorConstant{1} [id Y]
   |   |Elemwise{gt,no_inplace} [id CC] ''   
   |     |Elemwise{Composite{((i0 - (((i1 - i2) * i3) + i2)) + i2)}}[(0, 0)] [id BZ] ''   
   |     |TensorConstant{0} [id N]
   |GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'} [id CD] ''   
   | |MakeVector{dtype='int64'} [id CE] ''   
   | | |Shape_i{0} [id L] ''   
   | | |Shape_i{0} [id P] ''   
   | | |Elemwise{Composite{(((i0 + (i1 * (Composite{((i0 * i1) + i1)}(i2, i3) - i3))) - Composite{((i0 * i1) + i1)}(i2, i3)) + i3)}}[(0, 0)] [id BV] ''   
   | | |Elemwise{Composite{(((i0 + (i1 * (Composite{((i0 * i1) + i1)}(i2, i3) - i3))) - Composite{((i0 * i1) + i1)}(i2, i3)) + i3)}}[(0, 0)] [id CA] ''   
   | |MakeVector{dtype='int64'} [id CF] ''   
   |   |Shape_i{0} [id BR] ''   
   |   |Shape_i{1} [id CG] ''   
   |   | |<CudaNdarrayType(float32, 4D)> [id BO]
   |   |Shape_i{2} [id BW] ''   
   |   |Shape_i{3} [id CB] ''   
   |Constant{1.0} [id BL]
   |Constant{0.0} [id BM]
```
</details>
<br/>

Ah, new insight: When running the copied function with border_mode="full" and no supplied filter shape, I get:
```
RuntimeError: could not set op descriptor: CUDNN_STATUS_BAD_PARAM
Apply node that caused the error: GpuDnnConvDesc{border_mode='full', subsample=(1, 1), conv_mode='conv', precision='float32'}(MakeVector{dtype='int64'}.0, MakeVector{dtype='int64'}.0)
Toposort index: 31
Inputs types: [TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(4,), (4,)]
Inputs strides: [(8,), (8,)]
Inputs values: [array([ 10,   1,   1, 100]), array([5, 1, 0, 6])]
Outputs clients: [[GpuDnnConv{algo='time_once', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='full', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})]]
```
For whatever reason, it thinks the filter shape should be `5, 1, 0, 6`.

**Comment by nouiz** [comment]
If this work well in the new basic back end, we won't spent time on this.
We will remove shortly the old backend. Is there something that prevent you
from using the new backend?

Fred

Le ven. 10 mars 2017 14:10, Jan Schlüter <notifications@github.com> a
écrit :

**Comment by f0k** [comment]
> If this work well in the new basic back end, we won't spent time on this.

Fair enough. It looks like a fairly specific problem.

> Is there something that prevent you from using the new backend?

Seems compilation took too long in the new backend: https://groups.google.com/d/msg/lasagne-users/G-eez5pJPaM/iuZNE2jUAgAJ
@ASpeiser, did you try again with an updated libgpuarray and Theano?

**Comment by ASpeiser** [comment]
I did a fresh installation of cuda/libgpuarray on a different system with a different GPU and got the same problem:

Compiling of a function involving scan op takes 14s vs 1.2s with the old backend. On the other system its something like 30s vs 1.5s. I guess its connected to this issue: https://github.com/Theano/Theano/issues/4817 ? 

Anyway it pretty much makes it impossible to run the new backend for me, I gave up on compiling my whole graph after half an hour or so.

**Comment by jan-matthis** [comment]
See also: https://github.com/Theano/Theano/issues/5583

**Comment by f0k** [comment]
> See also

But that's for a runtime overhead, not for increased compilation time.

**Comment by nouiz** [comment]
#5583 isn't related to compilation time. We didn't saw that one cause
problem in "real" jobs.

For #4817, @abergeron is working on this and have a PR and is not contining
work on it. Should be fixed next week (or the week after).

I don't get everything about your compilation time. Yes 14s vs 1.2s isn't
great, but should be fixed relatively rapidly. What is the link of this
case vs the 30m? What is the time of the 30m case in the old back-end?
Don't forget, the first time we compile a function, we compile c code that
is cached. If you compile in the new back-end for the first time, you pay
that first compilation cost.

We are working on this right now. There is 2 PR that make structural change
to Theano to make it easier to generate less code. The next step will be to
use that new structure:)

**Comment by ASpeiser** [comment]
Cool, looking forward to the next release then. 
I guess the issue can be closed.

**Comment by nouiz** [comment]
closing as what is left (slower compilation) have its own issue https://github.com/Theano/Theano/issues/5695)
