### ISSUE TITLE
GpuArrayException: invalid argument when calling compiled theano function

### ISSUE THREAD

**Issue by gyglim** [Theano/Theano#5737]
I have an issue with switching to the new backend (see below).
It occurs when calling the complied function (feat_fn) and happens, from what I understand, when returning the results. While this works when I test it, the same fails when called via on a gRPC server, that runs a single `concurrent.futures.ThreadPoolExecutor`, with the error below. 

__Note__:The code in question uses the new 3D convolution and pooling interface.

```scores = feat_fn(snip)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 141, in raise_with_op
    detailed_err_msg = "\nApply node that caused the error: " + str(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 180, in __str__
    return op_as_string(self.inputs, self)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 1233, in op_as_string
    strs = as_string(i, op.inputs, leaf_formatter, node_formatter)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 1313, in as_string
    return [describe(output) for output in o]
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 1311, in describe
    return leaf_formatter(r)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/type.py", line 577, in __str__
    return "GpuArrayConstant{%s}" % np_data
  File "pygpu/gpuarray.pyx", line 2148, in pygpu.gpuarray.GpuArray.__str__ (pygpu/gpuarray.c:28699)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "pygpu/gpuarray.pyx", line 1664, in pygpu.gpuarray.GpuArray.__array__ (pygpu/gpuarray.c:21612)
  File "pygpu/gpuarray.pyx", line 1371, in pygpu.gpuarray._pygpu_as_ndarray (pygpu/gpuarray.c:18318)
  File "pygpu/gpuarray.pyx", line 384, in pygpu.gpuarray.array_read (pygpu/gpuarray.c:6919)
GpuArrayException: invalid argument
```

I followed http://deeplearning.net/software/libgpuarray/installation.html to install libgpuarray and successfully run the tests.

**Comment by nouiz** [comment]
Are you use the GPU context is well created and the data is on the right context? Doing thing on the GPU over multiple thread/process isn't trivial, there is limitation on what can be done.

In the next few weeks, we will work on better error message to help debug cases like this.

**Comment by gyglim** [comment]
What do you mean with the right context? How can I verify this?
 I have context None for both cases (working & non-working). I know that using Threads is non-trivial and I had problems with multi-threading before. But gRPC requires running the service using a ThreadPoolExecutor, as far as I know. Thus I use it, but with a single thread. This worked for the old backend

**Comment by nouiz** [comment]
How do you init the GPU in that thread? Do you init the GPU in that thread?
This is the probably what need to be done.

**Comment by akraoui** [comment]
hi!
you can help me plz; i have the problem when i type command "import theano" on console ipython---spyder---- the error displayed :
import theano
Traceback (most recent call last):

  File "<ipython-input-1-3397704bd624>", line 1, in <module>
    import theano
File "C:\Users\numero tel\Anaconda3\lib\site-packages\theano\configdefaults.py", line 119, in <module>
    in_c_key=False)

  File "C:\Users\numero tel\Anaconda3\lib\site-packages\theano\configparser.py", line 285, in AddConfigVar
    configparam.__get__(root, type(root), delete_key=True)

  File "C:\Users\numero tel\Anaconda3\lib\site-packages\theano\configparser.py", line 333, in __get__
    self.__set__(cls, val_str)
'You are tring to use the GPU back-end. '

ValueError: You are tring to use the old GPU back-end. It was removed from Theano. Use device = cuda * now. See https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29
i need your help﻿

**Comment by lamblin** [comment]
@akraoui As the error message tells you, you are trying to use the old GPU back-end (`device=gpu`) instead of the new one (`device=cuda`). Please use the new syntax and follow the instructions on the link displayed.
Moreover, this ticket is about a different problem.

**Comment by lamblin** [comment]
@gyglim Do you have the same issue when forcing synchronous execution with `CUDA_LAUNCH_BLOCKING=1` in the environment?

**Comment by nouiz** [comment]
No news and no way to reproduce, so closing.
