### ISSUE TITLE
Error due to user folder name with spaces, while importing Theano

### ISSUE THREAD

**Issue by Ahsan-Anjum** [Theano/Theano#5767]
I'm using Windows 8.1 64-bit on a Dell Inspiron 15r 5521, core i5 3rd generation. I have installed Anaconda2 4.3.1 64-bit version and am trying to import theano after installing it.
The user folder name is "C:\Users\Muhammad Ahsan Anjum" without the quotes. Its giving error because it simply takes the path till it encounters the first space character(the path being somewhere in "C:\Users\Muhammad Ahsan Anjum\AppData\Local"). How do I make it take the full path including the spaces, so that Theano is compiled?
This is what I get after typing "import theano" in my Python environment:

Problem occurred during compilation with the command line below:
"C:\SciSoft\TDM-GCC-64\bin\g++.exe" -shared -g -march=ivybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mn
o-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr
 -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma
-mno-avx512vbmi -mno-clwb -mno-pcommit --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072 -mtune=ivybridge -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DM
S_WIN64 -I"C:\ProgramFiles\Anaconda2\lib\site-packages\numpy\core\include" -I"C:\ProgramFiles\Anaconda2\include" -I"C:\ProgramFiles\Anaconda2\lib\site-packages\theano\gof" -L"C:\ProgramFiles
\Anaconda2\libs" -L"C:\ProgramFiles\Anaconda2" -o C:\Users\Muhammad Ahsan Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-
64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Muhammad Ahsan Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker
_ext\mod.cpp -lpython27
g++.exe: error: Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker_ext\lazylinker_ext.pyd: No such file or dire
ctory
g++.exe: error: C:\Users\Muhammad: No such file or directory
g++.exe: error: Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp: No such file or directory

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\__init__.py", line 66, in <module>
    from theano.compile import (
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\compile\__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 21, in <module>
    import theano.compile.mode
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\compile\mode.py", line 10, in <module>
    import theano.gof.vm
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\gof\vm.py", line 662, in <module>
    from . import lazylinker_c
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): g++.exe: error: Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazyli
. g++.exe: error: Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp: No such file or directory

**Comment by nouiz** [comment]
Make sure to use Theano 0.9. There was recent conda packages for that:

conda install Theano

We fixed such problems since 0.8.2

**Comment by Ahsan-Anjum** [comment]
I already had Theano 0.9. But I uninstalled it, and reinstalled it using "conda install Theano", and this is what I got:

Problem occurred during compilation with the command line below:
"C:\ProgramFiles\Anaconda2\Library\mingw-w64\bin\g++.exe" -shared -g -march=ivybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul
 -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-
prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx
512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072 -mtune=ivybridge -DNPY_NO_DEPRECATE
D_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\ProgramFiles\Anaconda2\lib\site-packages\numpy\core\include" -I"C:\ProgramFiles\Anaconda2\include" -I"C:\ProgramFiles\Anaconda2\lib\site-packa
ges\theano\gof" -L"C:\ProgramFiles\Anaconda2\libs" -L"C:\ProgramFiles\Anaconda2" -o C:\Users\Muhammad Ahsan Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_
58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Muhammad Ahsan Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9
_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp -lpython27
g++.exe: error: Ahsan: No such file or directory
g++.exe: error: Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker_ext\lazylinker_ext.pyd: No such file or dire
ctory
g++.exe: error: C:\Users\Muhammad: No such file or directory
g++.exe: error: Ahsan: No such file or directory
g++.exe: error: Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp: No such file or directory

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\__init__.py", line 66, in <module>
    from theano.compile import (
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\compile\__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 21, in <module>
    import theano.compile.mode
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\compile\mode.py", line 10, in <module>
    import theano.gof.vm
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\gof\vm.py", line 662, in <module>
    from . import lazylinker_c
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
. g++.exe: error: Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker_ext\lazylinker_ext.pyd: No such file or di
. g++.exe: error: Anjum\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp: No such file or directory

**Comment by nthgol** [comment]
I have the same issue: 
Problem occurred during compilation with the command line below:
C:/TDM-GCC-64/bin/g++.exe -shared -g -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\numpy\core\include" -I"C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\include" -I"C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\gof" -L"C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\libs" -L"C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets" -o C:\Users\Goldstein Nathan\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.5.3-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Goldstein Nathan\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.5.3-64\lazylinker_ext\mod.cpp -lpython35
Traceback (most recent call last):
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\gof\lazylinker_c.py", line 75, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\gof\lazylinker_c.py", line 92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Goldstein Nathan/PycharmProjects/neural_networks/main_digit_recognition.py", line 4, in <module>
    import keras
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import activations
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\keras\activations.py", line 4, in <module>
    from . import backend as K
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\keras\backend\__init__.py", line 70, in <module>
    from .theano_backend import *
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\keras\backend\theano_backend.py", line 3, in <module>
    import theano
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\__init__.py", line 66, in <module>
    from theano.compile import (
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\compile\__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\compile\function_module.py", line 21, in <module>
    import theano.compile.mode
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\compile\mode.py", line 10, in <module>
    import theano.gof.vm
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\gof\vm.py", line 662, in <module>
    from . import lazylinker_c
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\Users\Goldstein Nathan\AppData\Local\Continuum\Anaconda3\envs\neuralnets\lib\site-packages\theano\gof\cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
. 

Process finished with exit code 1

**Comment by nouiz** [comment]
Uninstall Theano and install the dev version. Check the web site, I'm
offline.
The dev version have a fix for this

**Comment by nthgol** [comment]
this worked. thanks. to readers FYI its not avail on conda just through pip

**Comment by nouiz** [comment]
You can get it with this long pip  command:

pip install https://github.com/Theano/Theano.git

thanks for the update, I'm closing this issue as it work.

**Comment by ramakrse** [comment]
Experience problem in using used pip install https://github.com/Theano/Theano.git. Solved by pip install git+https://github.com/Theano/Theano.git
