### ISSUE TITLE
theano0.9.0 pyhton2.7-ImportError: cannot import name gof

### ISSUE THREAD

**Issue by dan0910** [Theano/Theano#5801]
Hello, I installed Anaconda2 and theano on Win10. ( I use `pip install theano` ) 
And I got following error when I tried to import theano in Spyder. Theano version: 0.9.0   Python version:2.7.13

import theano
Traceback (most recent call last):

 File "<ipython-input-7-3397704bd624>", line 1, in <module>
    import theano

  File "E:\Anaconda\lib\site-packages\theano\__init__.py", line 66, in <module>
    from theano.compile import (

  File "E:\Anaconda\lib\site-packages\theano\compile\__init__.py", line 10, in <module>
    from theano.compile.function_module import *

  File "E:\Anaconda\lib\site-packages\theano\compile\function_module.py", line 18, in <module>
    from theano import config, gof

ImportError: cannot import name gof

What can I do to solve the problem? THANK you so much.

**Comment by lamblin** [comment]
Spyder seems to change environment variables, which sometimes interferes with importing theano.
Make sure the current working directory is not inside the checkout of Theano.
You could also try installing theano from Conda.
In any case, theano-users and stackoverflow would be the places to ask for support.
