### ISSUE TITLE
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by cjliux** [Theano/Theano#5841]
I have installed theano on windows 10 pro with anaconda3 4.1.1 by just typing `conda install mingw libpython`  and `conda install theano pygpu`.However I can't import theano and the error it raised is as follow:

ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1797, in _try_compile_tmp
    os.remove(exe_path + ".exe")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Asus\\AppData\\Local\\Temp\\try_march_ey1e72jb.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 66, in init_dev
    avail = dnn.dnn_available(name)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 174, in dnn_available
    if not dnn_present():
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 155, in dnn_present
    dnn_present.avail, dnn_present.msg = _dnn_check_compile()
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 121, in _dnn_check_compile
    try_run=False, output=True)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2187, in try_flags
    theano.config.cxx, comp_args)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1842, in _try_flags
    comp_args=comp_args)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1762, in _try_compile_tmp
    args = cls.compile_args()
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2094, in compile_args
    default_compilation_result, default_execution_result = try_march_flag(GCC_compiler.march_flags)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1869, in try_march_flag
    flags=cflags, try_run=True)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2181, in try_compile_tmp
    comp_args)
  File "E:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1802, in _try_compile_tmp
    err += "\n" + str(e)
TypeError: can't concat bytes to str
  
Do anyone know how to solve that?

**Comment by cjliux** [comment]
some information about my settings:
nvidia driver 373.06
cuda toolkit  v8.0
cudnn v5.1 for win10
vs2015 pro

**Comment by cjliux** [comment]
I have found the solution.That's because `device=cuda` has not yet been supported in the version that I am using.

**Comment by aeloyq** [comment]
whose version not been supported,Theano's?

**Comment by nouiz** [comment]
0.8.2 don't have good device=cuda support. 0.9 should support it well as well as the dev version.
