### ISSUE TITLE
an issue with tensor.ifelse

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#5864]
I have the optimizer swearing on me that I give inputs of different types to `IfElse` op. But in fact they are the same: float32 scalars. Somehow during the optimization the optimizer moves one of the inputs to the gpu without moving the other, and after that, indeed, the types become different, as the error message below says. This only happens with `optimizer=fast_run`.

```
ERROR:theano.gof.opt:Traceback (most recent call last):
  File "/u/bahdanau/Dist/theano/theano/gof/opt.py", line 241, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/u/bahdanau/Dist/theano/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/u/bahdanau/Dist/theano/theano/gpuarray/opt.py", line 380, in apply
    node.outputs)
  File "/u/bahdanau/Dist/theano/theano/gpuarray/opt.py", line 939, in local_gpua_lazy_ifelse
    return IfElse(op.n_outs, gpu=True)(c, *inps, return_list=True)
  File "/u/bahdanau/Dist/theano/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/u/bahdanau/Dist/theano/theano/ifelse.py", line 188, in make_node
    'false return values'), t, f, t.type, f.type)
TypeError: ('IfElse requires same types for true and false return values', shared_mbcloss, TensorConstant{0.0}, GpuArrayType<None>(float32, scalar), TensorType(float32, scalar))
```

**Comment by rizar** [comment]
Correction: this also happens with `device=cuda00,optimizer=fast_compile`. Not on CPU though.

**Comment by nouiz** [comment]
Do you have code to reproduce this?

**Comment by nouiz** [comment]
```
import numpy
import theano
from theano import tensor

x = tensor.lscalar('x')
y = theano.shared(numpy.asarray(1, dtype='float32'), name='y')
z = tensor.constant(2.)

a = theano.ifelse.ifelse(x, y, z)
f = theano.function([x], [a])
```
@rizar give me that code to reproduce it.

**Comment by nouiz** [comment]
I have a fix here:
https://github.com/Theano/Theano/pull/5865

thanks
