### ISSUE TITLE
ImportError: ('The following error happened while compiling the node', InplaceDimShuffle{x}(TensorConstant{0.0})

### ISSUE THREAD

**Issue by tsohil** [Theano/Theano#5897]
Hi,

I am running theano within Anaconda on Ubuntu 16(32-bit) machine. Here is my machine state

```
sam@sam-Vostro-1014:~$ lscpu 
Architecture:          i686
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 23
Model name:            Intel(R) Core(TM)2 Duo CPU     T6670  @ 2.20GHz
Stepping:              10
CPU MHz:               1600.000
CPU max MHz:           2201.0000
CPU min MHz:           1200.0000
BogoMIPS:              4389.23
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              2048K
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm ida

```

I am trying to run some deep learning model and got below mentioned error.

```
Traceback (most recent call last):

  File "<ipython-input-1-3988e94aa62b>", line 1, in <module>
    runfile('/home/sam/Documents/max-margin/data_preprocess.py', wdir='/home/sam/Documents/max-margin')

  File "/home/sam/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/sam/Documents/max-margin/data_preprocess.py", line 27, in <module>
    max_margin_dtr.trainer(data_list, data_list)

  File "max_margin_dtr.py", line 317, in trainer
    f_cost = theano.function(inps, -cost, profile=False)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1795, in orig_function
    defaults)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py", line 1047, in make_all
    impl=impl))

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 935, in make_thunk
    no_recycling)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1489, in compile_cmodule
    preargs=preargs)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)

  File "/home/sam/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])

ImportError: ('The following error happened while compiling the node', InplaceDimShuffle{x}(TensorConstant{0.0}), '\n', '/home/sam/.theano/compiledir_Linux-4.8--generic-i686-with-debian-stretch-sid-i686-2.7.13-32/tmptIQl06/0abe19206004f55475830d020f9a6684.so: undefined symbol: _ZdlPvj', '[InplaceDimShuffle{x}(TensorConstant{0.0})]')
```

Please help me with this issue. 

Thanks.

**Comment by lamblin** [comment]
See #5845.
Your version of g++ is too recent for the version of libstdc++ shipped with Anaconda.
You can install and use explicitly an older version of g++, or try to preload the system libstdc++, as I mentioned in the other ticket.
Closing as a duplicate.
