### ISSUE TITLE
`pp` should not raise `AttributeError` if input has no 'owner`

### ISSUE THREAD

**Issue by kohr-h** [Theano/Theano#5925]
[This line](https://github.com/Theano/Theano/blob/7179282715fb04052e0f4e3c14f242eaac1cfe1e/theano/printing.py#L509) causes an `AttributeError` when the input has no `owner` attribute.
Given that the subsequent code already tries to handle the case when `owner is None`, a simple fix would be to use 
```python
node = getattr(output, 'owner', None)
```
instead. In that case, `pp` simply falls back to `print` (or rather `repr`), as one would probably expect when pretty-printing is not possible.
I'll propose a PR to fix this.

**Comment by lamblin** [comment]
I'm not against that fix, but how did you manage to create a Variable without an owner?

**Comment by nouiz** [comment]
I don't like this fix. I think it hide another problem. Do you have code that reproduce it? Pascal raised the good question, how did you got a Variable instance without an owner field? Maybe the object isn't a variable and so this method should not have been called on that object. So maybe the fix is upstream.

If you can't easily share code that reproduce it, can you share the full error message? Maybe the stack trace and help us find the cause of this problem.

thanks for the report.

**Comment by kohr-h** [comment]
For me it was triggered by using `pp` on a `Function` object. I guess a minimal example would look like this:
```python
>>> from theano import tensor as T
>>> from theano import function, pp
>>> x = T.scalar('x')
>>> f = function([x], x)
>>> pp(f)
Traceback (most recent call last):

  File "<ipython-input-2-3f435b5bf788>", line 1, in <module>
    pp(f)

  File "[...]/theano/printing.py", line 616, in __call__
    return self.process(*args)

  File "[...]/theano/printing.py", line 551, in process
    return printer.process(r, pstate)

  File "/[...]/theano/printing.py", line 509, in process
    node = getattr(output, 'owner')

AttributeError: 'Function' object has no attribute 'owner'
```
I have to guess what the exact intent of `pp` is because there is no docstring. But my first thought is "print pretty if you can, otherwise just print" for *any* input. So if that's what it's intended for, it should never crash.
I see in the source that there's a string
```python
"""
Print to the terminal a math-like expression.
"""
```
[just underneath](https://github.com/Theano/Theano/blob/7179282715fb04052e0f4e3c14f242eaac1cfe1e/theano/printing.py#L650-L653) the assignment of a `PPrinter` instance to the name `pp`. Maybe you want to do `pp.__doc__ = ...` with that string?

**Comment by lamblin** [comment]
- the docstring should be declared in `def __call__` inside the definition of `PPrinter`
- in order to support calling `pp` on a Function object, I think we would need to add some logic in `PPrinter.__call__`, to dispatch one Function argument to `self.process_graph(inputs, outputs, updates)` and get the right inputs, outputs, and updates from `args[0].maker.fgraph`.
- also, while we are at it, we could also accept a `FunctionGraph` object.

**Comment by nouiz** [comment]
pp was made to work on Theano variable, not Theano function. @lamblin explain how to make it work with functions. That would be the right "fix" (to add the new feature). Otherwise, the repr of a Function isn't the pp() printing, but something else.

Do you want to implement it?

**Comment by kohr-h** [comment]
I can give it a shot.
