### ISSUE TITLE
Thread safe shared updates on the GPU?

### ISSUE THREAD

**Issue by botev** [Theano/Theano#5929]
Currently, from a test it seems that the `set_value` method of shared variables is not thread safe and raises issues with cuda. However, I don't see any good reason why multi threading is not allowed on shared variables values, this can allow for some form of async work during theano function execution. The error I get is:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/share/apps/python-3.6.0-shared/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/share/apps/python-3.6.0-shared/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 16, in poll
    p1.set_value(copied_value)
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gpuarray/type.py", line 637, in set_value
    self.container.value = value
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gof/link.py", line 477, in __set__
    **kwargs)
  File "/share/apps/barber/system/lib/python3.6/site-packages/theano/gpuarray/type.py", line 296, in filter_inplace
    old_data.write(data)
  File "pygpu/gpuarray.pyx", line 1665, in pygpu.gpuarray.GpuArray.write (pygpu/gpuarray.c:21009)
  File "pygpu/gpuarray.pyx", line 387, in pygpu.gpuarray.array_write (pygpu/gpuarray.c:6810)
pygpu.gpuarray.GpuArrayException: (b'cuMemcpyHtoDAsync(dst->ptr + dstoff, src, sz, ctx->mem_s): CUDA_ERROR_INVALID_VALUE: invalid argument', 'Container name "p1"')
```

The code to reproduce:
```
import numpy as np
import theano
import theano.tensor as T
from theano.ifelse import ifelse
import time
import threading


def fill_in(p1, p2, value):
    lock = threading.Condition()

    def poll():
        copied_value = np.array(value, copy=True)
        lock.acquire()
        while True:
            p1.set_value(copied_value)
            # print("Setting 1")
            copied_value += 1
            lock.wait()
            p2.set_value(copied_value)
            # print("Setting 2")
            copied_value += 1
            lock.wait()

    t = threading.Thread(target=poll)
    t.daemon = True
    t.start()
    time.sleep(1)

    def gen():
        while True:
            lock.acquire()
            lock.notify()
            lock.release()
            yield
    return gen()


def main(M=10000, N=10000, iter=100):
    f1, f2, p1, p2 = make_function(M, N)
    np_in = np.random.randn(M, N).astype(theano.config.floatX)
    generator = fill_in(p1, p2, np_in)
    s1 = time.time()
    for i in range(iter):
        o1 = f1(np_in)
        np_in += 1
        print(np_in[0, 0], o1[0, 0])
    print("end 1 -", time.time() - s1)
    next(generator)
    s2 = time.time()
    for i, _ in zip(range(iter), generator):
        o2 = f2()
        print(np_in[0, 0], o2[0, 0])
    print("end 2 -", time.time() - s2)


def make_function(M, N):
    a = T.fmatrix()
    f1 = theano.function([a], a + T.constant(2))
    theano.printing.debugprint(f1.maker.fgraph.outputs[0])
    p1 = theano.shared(np.zeros((M, N), dtype=theano.config.floatX))
    p2 = theano.shared(np.zeros((M, N), dtype=theano.config.floatX))
    flag = theano.shared(np.asarray(True))
    p = ifelse(flag, p1, p2)
    f2 = theano.function([], p + T.constant(2), updates=((flag, T.bitwise_not(flag)), ))
    return f1, f2, p1, p2

if __name__ == '__main__':
    main()
```
Is there anyway around this issue or is it just dead?

**Comment by lamblin** [comment]
Sorry, but this is not in our plans for the moment.
Synchronization on the GPU is forced by using only 1 stream by default for now. We have only one way to get more stream for now by using the flag gpuarray.single_stream=False as discussed in gh-5986. 

To transfer the minibatch in parallel to computation. I think the direction I wrote in gh-5986 is the way to go and not this one.
