### ISSUE TITLE
pygpu.gpuarray.GpuArrayException: Unaligned array

### ISSUE THREAD

**Issue by jagiella** [Theano/Theano#5934]
Using keras/theano with the new gpuarray backend, the following error occured:

```python
Traceback (most recent call last):
  File "newBackend.py", line 38, in <module>
    model.fit( x, y)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 856, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1498, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1152, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1158, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9990)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7083)
pygpu.gpuarray.GpuArrayException: Unaligned array
Apply node that caused the error: GpuContiguous(InplaceGpuDimShuffle{3,2,0,1}.0)
Toposort index: 58
Inputs types: [GpuArrayType<None>(float32, (False, False, False, False))]
Inputs shapes: [(4, 1, 11, 11)]
Inputs strides: [(4, 9223372036854775807, 176, 16)]
Inputs values: ['not shown']
Outputs clients: [[Shape(GpuContiguous.0), Shape_i{3}(GpuContiguous.0), Shape_i{2}(GpuContiguous.0), Shape_i{0}(GpuContiguous.0), GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```
Code to reproduce the problem:
```python
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
import numpy as np
x = np.random.random( size=(100, 1, 200, 300)).astype('float32')
y = np.random.random( size=(100, 3)).astype('float32')
model = Sequential([
	Conv2D( 4, (11,11), activation='relu', padding='same', input_shape=x.shape[1:]),
	MaxPooling2D( (2,2)),
	Conv2D( 8, (7,7), activation='relu', padding='same'),
	MaxPooling2D( (2,2)),
	Conv2D( 16, (5,5), activation='relu', padding='same'),
	MaxPooling2D( (2,2)),
	Conv2D( 32, (3,3), activation='relu', padding='same'),
	MaxPooling2D( (2,2)),
	Conv2D( 64, (3,3), activation='relu', padding='same'),
	MaxPooling2D( (2,2)),
	#Conv2D( 128, (3,3), activation='relu', padding='same'),
	#MaxPooling2D( (2,2)),
	#Conv2D( 256, (3,3), activation='relu', padding='same'),
	#MaxPooling2D( (2,2)),
	Flatten(),
	Dropout(0.05),
	Dense(128, activation='relu'),
	Dropout(0.05),
	Dense(y.shape[1], activation='softmax')
])
#print( model.summary())
model.compile( loss='categorical_crossentropy', optimizer='adadelta', metrics=['accuracy'])
model.fit( x, y)
```

**Comment by nouiz** [comment]
Update Theano to the dev version of keras. Both have changes that would fix it.

**Comment by jagiella** [comment]
I updated to the latest versions on both repositories:
```shell
$ sudo -H python -m pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
[sudo] password for nickj: 
Collecting git+git://github.com/fchollet/keras.git
  Cloning git://github.com/fchollet/keras.git to /tmp/pip-cUsll2-build
Installing collected packages: Keras
  Found existing installation: Keras 2.0.4
    Uninstalling Keras-2.0.4:
      Successfully uninstalled Keras-2.0.4
  Running setup.py install for Keras ... done
Successfully installed Keras-2.0.4
```


```python
Using Theano backend.
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
In file included from /tmp/try_flags_Q3q20i.c:4:0:
/usr/include/cudnn.h:63:26: fatal error: driver_types.h: No such file or directory
compilation terminated.

Mapped name None to device cuda: GeForce GTX 1070 (0000:01:00.0)
Epoch 1/10
Traceback (most recent call last):
  File "newBackend.py", line 38, in <module>
    model.fit( x, y)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 868, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1503, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1155, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1196, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9990)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7083)
pygpu.gpuarray.GpuArrayException: 
Apply node that caused the error: GpuContiguous(GpuSubtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 72
Inputs types: [GpuArrayType<None>(float32, 4D)]
Inputs shapes: [(4, 1, 11, 11)]
Inputs strides: [(4, 9223372036854775807, -176, -16)]
Inputs values: ['not shown']
Outputs clients: [[GpuCorrMM{valid, (1, 1), (1, 1)}(GpuContiguous.0, GpuContiguous.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by nouiz** [comment]
This new error is the same as in https://github.com/Theano/Theano/issues/5945, so I'll let this issue closed and we should continue discussion on the new issue about the new error.
