### ISSUE TITLE
Linker errors on Windows (32-bit Python, 64-bit Windows 10)

### ISSUE THREAD

**Issue by benjaminalt** [Theano/Theano#5958]
I am using Theano version 0.9.0 with a 32-bit Anaconda2 installation (Python 2.7) on a 64-bit Windows 10 machine. When I try to create a neural network with Keras using Theano as a backend, everything works when I don't have the m2w64-toolchain Anaconda package installed and the default Python implementation is used. When I install m2w64-toolchain to speed things up, I get a lot of linker errors and "Compilation failed" exceptions. I attached the full error trace. 
[theano_error_trace.txt](https://github.com/Theano/Theano/files/1010341/theano_error_trace.txt)
What is going wrong here?

Part of the error trace (so people with similar problems can find this issue) (still see the attached document, there is more): 

```
00001	#include <Python.h>
00002	#include <iostream>
00003	#include "theano_mod_helper.h"
00004	#include <math.h>
00005	#include <numpy/arrayobject.h>
00006	#include <numpy/arrayscalars.h>
00007	//////////////////////
00008	////  Support Code
00009	//////////////////////
00010	
00011	    namespace {
00012	    struct __struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e {
00013	        PyObject* __ERROR;
00014	
00015	        PyObject* storage_V3;
00016	PyObject* storage_V1;
00017	        
00018	
00019	        __struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e() {
00020	            // This is only somewhat safe because we:
00021	            //  1) Are not a virtual class
00022	            //  2) Do not use any virtual classes in the members
00023	            //  3) Deal with mostly POD and pointers
00024	
00025	            // If this changes, we would have to revise this, but for
00026	            // now I am tired of chasing segfaults because
00027	            // initialization code had an error and some pointer has
00028	            // a junk value.
00029	            memset(this, 0, sizeof(*this));
00030	        }
00031	        ~__struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e(void) {
00032	            cleanup();
00033	        }
00034	
00035	        int init(PyObject* __ERROR, PyObject* storage_V3, PyObject* storage_V1) {
00036	            Py_XINCREF(storage_V3);
00037	Py_XINCREF(storage_V1);
00038	            this->storage_V3 = storage_V3;
00039	this->storage_V1 = storage_V1;
00040	            
00041	
00042	
00043	
00044	            this->__ERROR = __ERROR;
00045	            return 0;
00046	        }
00047	        void cleanup(void) {
00048	            __label_1:
00049	
00050	double __DUMMY_1;
00051	__label_3:
00052	
00053	double __DUMMY_3;
00054	__label_6:
00055	
00056	double __DUMMY_6;
00057	
00058	            Py_XDECREF(this->storage_V3);
00059	Py_XDECREF(this->storage_V1);
00060	        }
00061	        int run(void) {
00062	            int __failure = 0;
00063	            
00064	    PyObject* py_V1;
00065	    
00066	        PyArrayObject* V1;
00067	        
00068	    PyObject* py_V3;
00069	    
00070	        PyArrayObject* V3;
00071	        
00072	{
00073	
00074	    py_V1 = PyList_GET_ITEM(storage_V1, 0);
00075	    {Py_XINCREF(py_V1);}
00076	    
00077	        if (py_V1 == Py_None)
00078	        {
00079	            
00080	        V1 = NULL;
00081	        
00082	        }
00083	        else
00084	        {
00085	            
00086	        V1 = (PyArrayObject*)(py_V1);
00087	        Py_XINCREF(V1);
00088	        
00089	        }
00090	        
00091	{
00092	
00093	    py_V3 = PyList_GET_ITEM(storage_V3, 0);
00094	    {Py_XINCREF(py_V3);}
00095	    
00096	        V3 = (PyArrayObject*)(py_V3);
00097	        Py_XINCREF(V3);
00098	        
00099	{
00100	// Op class DimShuffle
00101	if (PyArray_NDIM(V3) != 0){PyErr_SetString(PyExc_NotImplementedError, "input nd"); {
00102	        __failure = 5;
00103	        if (!PyErr_Occurred()) {
00104	            PyErr_SetString(PyExc_RuntimeError,
00105	                "Unexpected error in an Op's C code. "
00106	                "No Python exception was set.");
00107	            }
00108	        goto __label_5;};};
00109	if (V1) {Py_XDECREF(V1);};
00110	{ PyArrayObject * V3__view_or_copy = V3;
00111	Py_INCREF((PyObject*)V3__view_or_copy);
00112	npy_intp dimensions[2];
00113	dimensions[0] = 1;
00114	dimensions[1] = 1;
00115	npy_intp strides[2];
00116	strides[0] = 0;
00117	strides[1] = 0;
00118	if (strides[2-1] == 0) strides[2-1] = PyArray_DESCR(V3__view_or_copy)->elsize;
00119	if (strides[0] == 0) strides[0] = strides[0+1] * dimensions[0+1];
00120	V1 = (PyArrayObject*)PyArray_New(&PyArray_Type, 2, dimensions, PyArray_TYPE(V3__view_or_copy), strides, PyArray_DATA(V3__view_or_copy), PyArray_ITEMSIZE(V3__view_or_copy), (NPY_ARRAY_WRITEABLE*PyArray_ISWRITEABLE(V3__view_or_copy)), NULL);
00121	if (V1 == NULL) {
00122	        __failure = 5;
00123	        if (!PyErr_Occurred()) {
00124	            PyErr_SetString(PyExc_RuntimeError,
00125	                "Unexpected error in an Op's C code. "
00126	                "No Python exception was set.");
00127	            }
00128	        goto __label_5;};;
00129	PyArray_UpdateFlags(V1, NPY_ARRAY_UPDATE_ALL);
00130	
00131	PyArray_SetBaseObject(V1, (PyObject*)V3__view_or_copy);
00132	};__label_5:
00133	
00134	double __DUMMY_5;
00135	
00136	}
00137	__label_4:
00138	
00139	        if (V3) {
00140	            Py_XDECREF(V3);
00141	        }
00142	        
00143	    {Py_XDECREF(py_V3);}
00144	    
00145	double __DUMMY_4;
00146	
00147	}
00148	__label_2:
00149	
00150	    if (!__failure) {
00151	      
00152	        {Py_XDECREF(py_V1);}
00153	        if (!V1) {
00154	            Py_INCREF(Py_None);
00155	            py_V1 = Py_None;
00156	        }
00157	        else if ((void*)py_V1 != (void*)V1) {
00158	            py_V1 = (PyObject*)V1;
00159	        }
00160	
00161	        {Py_XINCREF(py_V1);}
00162	
00163	        if (V1 && !PyArray_ISALIGNED((PyArrayObject*) py_V1)) {
00164	            PyErr_Format(PyExc_NotImplementedError,
00165	                         "c_sync: expected an aligned array, got non-aligned array of type %ld"
00166	                         " with %ld dimensions, with 3 last dims "
00167	                         "%ld, %ld, %ld"
00168	                         " and 3 last strides %ld %ld, %ld.",
00169	                         (long int) PyArray_TYPE((PyArrayObject*) py_V1),
00170	                         (long int) PyArray_NDIM(V1),
00171	                         (long int) (PyArray_NDIM(V1) >= 3 ?
00172	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-3] : -1),
00173	                         (long int) (PyArray_NDIM(V1) >= 2 ?
00174	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-2] : -1),
00175	                         (long int) (PyArray_NDIM(V1) >= 1 ?
00176	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-1] : -1),
00177	                         (long int) (PyArray_NDIM(V1) >= 3 ?
00178	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-3] : -1),
00179	                         (long int) (PyArray_NDIM(V1) >= 2 ?
00180	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-2] : -1),
00181	                         (long int) (PyArray_NDIM(V1) >= 1 ?
00182	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-1] : -1)
00183	        );
00184	            {
00185	        __failure = 2;
00186	        if (!PyErr_Occurred()) {
00187	            PyErr_SetString(PyExc_RuntimeError,
00188	                "Unexpected error in an Op's C code. "
00189	                "No Python exception was set.");
00190	            }
00191	        goto __label_2;}
00192	        }
00193	        
00194	      PyObject* old = PyList_GET_ITEM(storage_V1, 0);
00195	      {Py_XINCREF(py_V1);}
00196	      PyList_SET_ITEM(storage_V1, 0, py_V1);
00197	      {Py_XDECREF(old);}
00198	    }
00199	    
00200	        if (V1) {
00201	            Py_XDECREF(V1);
00202	        }
00203	        
00204	    {Py_XDECREF(py_V1);}
00205	    
00206	double __DUMMY_2;
00207	
00208	}
00209	
00210	            
00211	        if (__failure) {
00212	            // When there is a failure, this code puts the exception
00213	            // in __ERROR.
00214	            PyObject* err_type = NULL;
00215	            PyObject* err_msg = NULL;
00216	            PyObject* err_traceback = NULL;
00217	            PyErr_Fetch(&err_type, &err_msg, &err_traceback);
00218	            if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}
00219	            if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}
00220	            if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}
00221	            PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);
00222	            PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);
00223	            PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);
00224	            PyList_SET_ITEM(__ERROR, 0, err_type);
00225	            PyList_SET_ITEM(__ERROR, 1, err_msg);
00226	            PyList_SET_ITEM(__ERROR, 2, err_traceback);
00227	            {Py_XDECREF(old_err_type);}
00228	            {Py_XDECREF(old_err_msg);}
00229	            {Py_XDECREF(old_err_traceback);}
00230	        }
00231	        // The failure code is returned to index what code block failed.
00232	        return __failure;
00233	        
00234	        }
00235	    };
00236	    }
00237	    
00238	
00239	        static int __struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e_executor(__struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e* self) {
00240	            return self->run();
00241	        }
00242	
00243	        static void __struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e_destructor(void* executor, void* self) {
00244	            delete ((__struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e*)self);
00245	        }
00246	        
00247	//////////////////////
00248	////  Functions
00249	//////////////////////
00250	static PyObject * instantiate(PyObject * self, PyObject *argtuple) {
00251	  assert(PyTuple_Check(argtuple));
00252	  if (3 != PyTuple_Size(argtuple)){ 
00253	     PyErr_Format(PyExc_TypeError, "Wrong number of arguments, expected 3, got %i", (int)PyTuple_Size(argtuple));
00254	     return NULL;
00255	  }
00256	  __struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e* struct_ptr = new __struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e();
00257	  if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1),PyTuple_GET_ITEM(argtuple, 2) ) != 0) {
00258	    delete struct_ptr;
00259	    return NULL;
00260	  }
00261	  PyObject* thunk = PyCObject_FromVoidPtrAndDesc((void*)(&__struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e_executor), struct_ptr, __struct_compiled_op_d405e96d7f3c74ff048ea3c07349948e_destructor);
00262	  return thunk; }
00263	
00264	//////////////////////
00265	////  Module init
00266	//////////////////////
00267	static PyMethodDef MyMethods[] = {
00268		{"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
00269		{NULL, NULL, 0, NULL}
00270	};
00271	PyMODINIT_FUNC initd405e96d7f3c74ff048ea3c07349948e(void){
00272	   import_array();
00273	   (void) Py_InitModule("d405e96d7f3c74ff048ea3c07349948e", MyMethods);
00274	}
00275	
Problem occurred during compilation with the command line below:
"Q:\Anaconda2\Library\mingw-w64\bin\g++.exe" -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=broadwell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrtm -mhle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mclflushopt -mxsavec -mxsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=generic -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m32 -I"Q:\Anaconda2\lib\site-packages\numpy\core\include" -I"Q:\Anaconda2\include" -I"Q:\Anaconda2\lib\site-packages\theano\gof" -L"Q:\Anaconda2\libs" -L"Q:\Anaconda2" -o C:\Users\alt\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32\tmptb_tfl\d405e96d7f3c74ff048ea3c07349948e.pyd C:\Users\alt\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32\tmptb_tfl\mod.cpp -lpython27
===============================
C:\Users\alt\AppData\Local\Temp\ccN2MgJu.o: In function `run':
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:87: undefined reference to `_imp___Py_NoneStruct'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:183: undefined reference to `_imp__PyExc_NotImplementedError'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:154: undefined reference to `_imp___Py_NoneStruct'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:189: undefined reference to `_imp__PyExc_RuntimeError'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:101: undefined reference to `_imp__PyExc_NotImplementedError'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:106: undefined reference to `_imp__PyExc_RuntimeError'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:218: undefined reference to `_imp___Py_NoneStruct'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:220: undefined reference to `_imp___Py_NoneStruct'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:219: undefined reference to `_imp___Py_NoneStruct'
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:126: undefined reference to `_imp__PyExc_RuntimeError'
C:\Users\alt\AppData\Local\Temp\ccN2MgJu.o: In function `instantiate':
C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:253: undefined reference to `_imp__PyExc_TypeError'
C:\Users\alt\AppData\Local\Temp\ccN2MgJu.o: In function `import_array':
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1473: undefined reference to `_imp__PyCObject_Type'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1474: undefined reference to `_imp__PyExc_RuntimeError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1475: undefined reference to `_imp__PyExc_ImportError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1496: undefined reference to `_imp__PyExc_RuntimeError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1496: undefined reference to `_imp__PyExc_ImportError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1455: undefined reference to `_imp__PyExc_ImportError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1518: undefined reference to `_imp__PyExc_RuntimeError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1518: undefined reference to `_imp__PyExc_ImportError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1461: undefined reference to `_imp__PyExc_AttributeError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1482: undefined reference to `_imp__PyExc_ImportError'
Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1482: undefined reference to `_imp__PyExc_RuntimeError'
collect2.exe: error: ld returned 1 exit status

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x,x}(TensorConstant{-0.4472135955})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "Q:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "Q:\Anaconda2\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "Q:\Anaconda2\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "Q:\Anaconda2\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "Q:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "Q:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "Q:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "Q:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "Q:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "Q:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ("Compilation failed (return status=1): C:\\Users\\alt\\AppData\\Local\\Temp\\ccN2MgJu.o: In function `run':\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:87: undefined reference to `_imp___Py_NoneStruct'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:183: undefined reference to `_imp__PyExc_NotImplementedError'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:154: undefined reference to `_imp___Py_NoneStruct'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:189: undefined reference to `_imp__PyExc_RuntimeError'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:101: undefined reference to `_imp__PyExc_NotImplementedError'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:106: undefined reference to `_imp__PyExc_RuntimeError'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:218: undefined reference to `_imp___Py_NoneStruct'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:220: undefined reference to `_imp___Py_NoneStruct'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:219: undefined reference to `_imp___Py_NoneStruct'\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:126: undefined reference to `_imp__PyExc_RuntimeError'\r. C:\\Users\\alt\\AppData\\Local\\Temp\\ccN2MgJu.o: In function `instantiate':\r. C:/Users/alt/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-32/tmptb_tfl/mod.cpp:253: undefined reference to `_imp__PyExc_TypeError'\r. C:\\Users\\alt\\AppData\\Local\\Temp\\ccN2MgJu.o: In function `import_array':\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1473: undefined reference to `_imp__PyCObject_Type'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1474: undefined reference to `_imp__PyExc_RuntimeError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1475: undefined reference to `_imp__PyExc_ImportError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1496: undefined reference to `_imp__PyExc_RuntimeError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1496: undefined reference to `_imp__PyExc_ImportError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1455: undefined reference to `_imp__PyExc_ImportError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1518: undefined reference to `_imp__PyExc_RuntimeError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1518: undefined reference to `_imp__PyExc_ImportError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1461: undefined reference to `_imp__PyExc_AttributeError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1482: undefined reference to `_imp__PyExc_ImportError'\r. Q:/Anaconda2/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1482: undefined reference to `_imp__PyExc_RuntimeError'\r. collect2.exe: error: ld returned 1 exit status\r. ", '[InplaceDimShuffle{x,x}(TensorConstant{-0.4472135955})]')


```

**Comment by benjaminalt** [comment]
It turns out libpython was not installed; ` conda install -c anaconda libpython=2.0` solved the problem. For reference, see [this issue](https://github.com/Theano/Theano/issues/2087).
