### ISSUE TITLE
mac Sierra issue with pygpu

### ISSUE THREAD

**Issue by cralax** [Theano/Theano#5966]
Hi,

My system is mac OS Sierra 10.12.5
By checking with command: gcc --version:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

When I run the following command to install to install gpuarray: python setup.py build
It finishes with the following comment:
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
error: command 'gcc' failed with exit status 1

When I try with (as advised in the doc): python setup.py build -L /usr/local/lib -I /usr/local/include
I have the following command:error: option -L not recognized

When I try with python setup.py build -I /usr/local/lib -I /usr/local/include
I have error: option -I not recognized

Could you please help me?

Thanks

**Comment by cralax** [comment]
Moreover, I tried to install pygpu with onda but when I import the module I have the following message:

Traceback (most recent call last):

  File "<ipython-input-6-b22a183e5879>", line 1, in <module>
    import pygpu

  File "/Users/Clement/libgpuarray/pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction

  File "/Users/Clement/libgpuarray/pygpu/elemwise.py", line 3, in <module>
    from .dtypes import dtype_to_ctype, get_common_dtype

  File "/Users/Clement/libgpuarray/pygpu/dtypes.py", line 6, in <module>
    from . import gpuarray

ImportError: cannot import name 'gpuarray'

**Comment by lamblin** [comment]
What are those 20 errors that are reported? Can you paste the whole error message?

When you installed through conda, did it install the `libgpuarray` package as well?

**Comment by cralax** [comment]
Hello

When I install libgpuarray, I have the following message:

Install the project...
-- Install configuration: "Release"
-- Up-to-date: /Users/Clement/.local/include/gpuarray/array.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/blas.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/collectives.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/buffer.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/buffer_blas.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/buffer_collectives.h
-- Installing: /Users/Clement/.local/include/gpuarray/abi_version.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/config.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/elemwise.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/error.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/extension.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/ext_cuda.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/kernel.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/types.h
-- Up-to-date: /Users/Clement/.local/include/gpuarray/util.h
-- Installing: /Users/Clement/.local/lib/libgpuarray.2.1.dylib
-- Up-to-date: /Users/Clement/.local/lib/libgpuarray.2.dylib
-- Up-to-date: /Users/Clement/.local/lib/libgpuarray.dylib
-- Installing: /Users/Clement/.local/lib/libgpuarray-static.a

When I run python setup.py build:
running build_py
copying pygpu/version.py -> build/lib.macosx-10.9-x86_64-3.6/pygpu
running egg_info
writing pygpu.egg-info/PKG-INFO
writing dependency_links to pygpu.egg-info/dependency_links.txt
writing requirements to pygpu.egg-info/requires.txt
writing top-level names to pygpu.egg-info/top_level.txt
reading manifest file 'pygpu.egg-info/SOURCES.txt'
writing manifest file 'pygpu.egg-info/SOURCES.txt'
running build_ext
building 'pygpu.collectives' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Clement/anaconda/include -arch x86_64 -I/Users/Clement/anaconda/include -arch x86_64 -DGPUARRAY_SHARED -I/Users/Clement/anaconda/lib/python3.6/site-packages/numpy/core/include -I/Users/Clement/anaconda/include/python3.6m -c pygpu/collectives.c -o build/temp.macosx-10.9-x86_64-3.6/pygpu/collectives.o -Wno-unused-variable -Wno-unused-function
In file included from pygpu/collectives.c:464:
In file included from /Users/Clement/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/Clement/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /Users/Clement/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:
/Users/Clement/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: 
      "Using deprecated NumPy API, disable it by "          "#defining
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
pygpu/collectives.c:1807:79: warning: declaration of 'enum gpucomm_reduce_ops'
      will not be visible outside of this function [-Wvisibility]
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23191:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_SUM); if (unl...
                                                        ^~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23203:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_SUM); if (unl...
                                                        ^~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23215:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_SUM); if (unl...
                                                        ^~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23227:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_PROD); if (un...
                                                        ^~~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23239:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_PROD); if (un...
                                                        ^~~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23251:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_PROD); if (un...
                                                        ^~~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23263:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_PROD); if (un...
                                                        ^~~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23275:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_MAX); if (unl...
                                                        ^~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23287:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_MAX); if (unl...
                                                        ^~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23299:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_MIN); if (unl...
                                                        ^~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:23311:57: error: argument type 'enum gpucomm_reduce_ops' is
      incomplete
  __pyx_t_2 = __Pyx_PyInt_From_enum__gpucomm_reduce_ops(GA_MIN); if (unl...
                                                        ^~~~~~
pygpu/collectives.c:1807:79: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:26129:91: warning: declaration of 'enum gpucomm_reduce_ops'
      will not be visible outside of this function [-Wvisibility]
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:26129:44: error: conflicting types for
      '__Pyx_PyInt_From_enum__gpucomm_reduce_ops'
            static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__gpucom...
                                           ^
pygpu/collectives.c:1807:32: note: previous declaration is here
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops...
                               ^
pygpu/collectives.c:26129:110: error: variable has incomplete type
      'enum gpucomm_reduce_ops'
  ...__Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_ops value) {
                                                                       ^
pygpu/collectives.c:26129:91: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:26130:45: error: cast to incomplete type
      'enum gpucomm_reduce_ops'
    const enum gpucomm_reduce_ops neg_one = (enum gpucomm_reduce_ops) -1...
                                            ^
pygpu/collectives.c:26129:91: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:26130:35: error: variable has incomplete type 'const enum
      gpucomm_reduce_ops'
    const enum gpucomm_reduce_ops neg_one = (enum gpucomm_reduce_ops) -1...
                                  ^
pygpu/collectives.c:26129:91: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:26130:88: error: cast to incomplete type
      'enum gpucomm_reduce_ops'
  ...neg_one = (enum gpucomm_reduce_ops) -1, const_zero = (enum gpucomm_reduc...
                                                          ^
pygpu/collectives.c:26129:91: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:26130:75: error: variable has incomplete type 'const enum
      gpucomm_reduce_ops'
  ...enum gpucomm_reduce_ops neg_one = (enum gpucomm_reduce_ops) -1, const_ze...
                                                                     ^
pygpu/collectives.c:26129:91: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:26133:13: error: invalid application of 'sizeof' to an
      incomplete type 'enum gpucomm_reduce_ops'
        if (sizeof(enum gpucomm_reduce_ops) < sizeof(long)) {
            ^     ~~~~~~~~~~~~~~~~~~~~~~~~~
pygpu/collectives.c:26129:91: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
pygpu/collectives.c:26135:20: error: invalid application of 'sizeof' to an
      incomplete type 'enum gpucomm_reduce_ops'
        } else if (sizeof(enum gpucomm_reduce_ops) <= sizeof(unsigned long)) {
                   ^     ~~~~~~~~~~~~~~~~~~~~~~~~~
pygpu/collectives.c:26129:91: note: forward declaration of
      'enum gpucomm_reduce_ops'
  ...PyObject* __Pyx_PyInt_From_enum__gpucomm_reduce_ops(enum gpucomm_reduce_...
                                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
error: command 'gcc' failed with exit status 1

**Comment by Sentient07** [comment]
@cralax Hi, what is your cuda version? Could you check your cuda version once, whether it is in accordance with what is described in this thread (Last comment especially) https://devtalk.nvidia.com/default/topic/970835/cuda-8-on-sierra/ (the last comment especially). If you still have problems with using your gpu, let us know.

**Comment by cralax** [comment]
Please find below information about my setup:
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:46_CST_2017
Cuda compilation tools, release 8.0, V8.0.61


And my GPU works well with pytorch and tensorflow...

**Comment by lamblin** [comment]
I thought XCode 8 was not compatible with even recent versions of CUDA.
Can you try with XCode 7.3?

**Comment by Sentient07** [comment]
@lamblin It used to be the situation, when I opened the thread in Google Group, but they provided a patch by mid December that supports XCode 8.0 as well.
@cralax did you install libgpuarray systemwide or for a particular user? If you install it for a particular user and then try to install pygpu in a location that is owned by root, it might cause problem. If you don't have access to root directories, virtual environment would be a good option. In any case, it is much easier to install it using conda.

**Comment by cralax** [comment]
Hi,

Moreover chez works well with pytorch and my Xcode version.
I tried to install libgpuarray and pygpu with conda and no error. However, when I try to import them in spyder I have an error telling that the modules don't exist.
It sounds strange especially concerning pygpu.

**Comment by cralax** [comment]
Sorry it works well... (iPhone corrector...)

**Comment by lamblin** [comment]
Do you manage to import conda's pygpu from a regular Python prompt? Spyder has been known to mess with paths.

**Comment by cralax** [comment]
I manage to import libgpuarray with python using the terminal but not pygpu.
How can I import libgpuarray with spider? It can import all my other libraries
