### ISSUE TITLE
Mac: import theano in Python 3.6 gives error "AttributeError: module 'theano.gof' has no attribute 'Query'"

### ISSUE THREAD

**Issue by vishesh9494** [Theano/Theano#5992]
I am having a Macbook Pro running on MacOS Sierra. I installed Theano using pip3 for python 3.6. Now whenever i try to import theano in python3.6 it always gives me the following error:

Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/__init__.py", line 55, in <module>
    from theano.gof import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/gof/__init__.py", line 58, in <module>
    from theano.gof.opt import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/gof/opt.py", line 12, in <module>
    import pdb
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 76, in <module>
    import code
  File "/Users/vishesh/Documents/deep_learning/Spatial Transformer Network code/code.py", line 18, in <module>
    import SpatialTransformer
  File "/Users/vishesh/Documents/deep_learning/Spatial Transformer Network code/SpatialTransformer.py", line 1, in <module>
    import theano.tensor as T
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/tensor/__init__.py", line 8, in <module>
    from theano.tensor.basic import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/tensor/basic.py", line 20, in <module>
    from theano.tensor import elemwise
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/tensor/elemwise.py", line 14, in <module>
    from theano import scalar
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/scalar/__init__.py", line 3, in <module>
    from .basic import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/scalar/basic.py", line 26, in <module>
    from theano import gof, printing
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/printing.py", line 21, in <module>
    from theano.compile import Function, debugmode, SharedVariable
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/compile/__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/compile/function_module.py", line 21, in <module>
    import theano.compile.mode
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/compile/mode.py", line 46, in <module>
    OPT_NONE = gof.Query(include=[], exclude=exclude)
AttributeError: module 'theano.gof' has no attribute 'Query'

The installation was perfect and without any glitch and so I have no idea why is this not working. Please help me out on this one. Thank You.

**Comment by lamblin** [comment]
The problem has nothing to do with Theano in itself.
What happens is that you have a file name `code.py` in your PYTHONPATH, which shadows the built-in `code` module of Python. So when `pdb` tries to import the built-in `code`, it imports your `code.py` instead, which imports `theano`, so it is a circular import.
The relevant portion of the stack trace demonstrating this is:
```
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 76, in
import code
File "/Users/vishesh/Documents/deep_learning/Spatial Transformer Network code/code.py", line 18, in
import SpatialTransformer
File "/Users/vishesh/Documents/deep_learning/Spatial Transformer Network code/SpatialTransformer.py", line 1, in
import theano.tensor as T
```
If you remove `/Users/vishesh/Documents/deep_learning/Spatial Transformer Network code` from your `PYTHONPATH`, or rename your file `code.py` to something that is not a built-in Python module, it should fix the issue.
