### ISSUE TITLE
Pygpu errors + Cuda

### ISSUE THREAD

**Issue by BLCKPSTV** [Theano/Theano#6010]
I'm getting lot of errors to install and link my Cuda for usage in an AI writer...

I don't get what to to with following errors.. This is for a setup lasagna/theano.

```
Compile log:
NVRTC compile log::
nvrtc: error: failed to load builtins
Link info log::

Link error log::
error   : Binary format for key='0', ident='' is not recognized


======================================================================
ERROR: pygpu.tests.test_tools.test_check_contig_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/quintendewilde/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/pygpu/tests/test_tools.py", line 20, in test_check_contig_2
    bc, bg = gen_gpuarray((50, 1, 20), 'float32', ctx=context, sliced=2)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/pygpu/tests/support.py", line 160, in gen_gpuarray
    assert numpy.allclose(a, numpy.asarray(b)), (a, numpy.asarray(b))
  File "/Users/quintendewilde/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "pygpu/gpuarray.pyx", line 1664, in pygpu.gpuarray.GpuArray.__array__ (pygpu/gpuarray.c:21616)
  File "pygpu/gpuarray.pyx", line 1362, in pygpu.gpuarray._pygpu_as_ndarray (pygpu/gpuarray.c:18230)
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9994)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7087)
GpuArrayException: Undeterminate error

======================================================================
ERROR: pygpu.tests.test_tools.test_check_args_collapse_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/quintendewilde/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/pygpu/tests/test_tools.py", line 67, in test_check_args_collapse_2
    offseted_inner=True)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/pygpu/tests/support.py", line 160, in gen_gpuarray
    assert numpy.allclose(a, numpy.asarray(b)), (a, numpy.asarray(b))
  File "/Users/quintendewilde/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "pygpu/gpuarray.pyx", line 1664, in pygpu.gpuarray.GpuArray.__array__ (pygpu/gpuarray.c:21616)
  File "pygpu/gpuarray.pyx", line 1362, in pygpu.gpuarray._pygpu_as_ndarray (pygpu/gpuarray.c:18230)
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9994)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7087)
GpuArrayException: Undeterminate error

======================================================================
ERROR: pygpu.tests.test_tools.test_check_args_collapse_3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/quintendewilde/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/pygpu/tests/test_tools.py", line 79, in test_check_args_collapse_3
    offseted_outer=True)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/pygpu/tests/support.py", line 160, in gen_gpuarray
    assert numpy.allclose(a, numpy.asarray(b)), (a, numpy.asarray(b))
  File "/Users/quintendewilde/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "pygpu/gpuarray.pyx", line 1664, in pygpu.gpuarray.GpuArray.__array__ (pygpu/gpuarray.c:21616)
  File "pygpu/gpuarray.pyx", line 1362, in pygpu.gpuarray._pygpu_as_ndarray (pygpu/gpuarray.c:18230)
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9994)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7087)
GpuArrayException: Undeterminate error

======================================================================
ERROR: pygpu.tests.test_tools.test_check_args_broadcast_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/quintendewilde/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/pygpu/tests/test_tools.py", line 120, in test_check_args_broadcast_2
    offseted_inner=True)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/pygpu/tests/support.py", line 160, in gen_gpuarray
    assert numpy.allclose(a, numpy.asarray(b)), (a, numpy.asarray(b))
  File "/Users/quintendewilde/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "pygpu/gpuarray.pyx", line 1664, in pygpu.gpuarray.GpuArray.__array__ (pygpu/gpuarray.c:21616)
  File "pygpu/gpuarray.pyx", line 1362, in pygpu.gpuarray._pygpu_as_ndarray (pygpu/gpuarray.c:18230)
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9994)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7087)
GpuArrayException: Undeterminate error

----------------------------------------------------------------------

```

**Comment by abergeron** [comment]
There is a problem with your installation of cuda/nvrtc as indicated by this portion:

```
NVRTC compile log::
nvrtc: error: failed to load builtins
```

**Comment by BLCKPSTV** [comment]
Stackoverflow doesn't show anything to fix this.. :/

**Comment by deepali-c** [comment]
What is the version of OS and CUDA where you see this issue? Please verify if the path for the libnvrtc-builtins.so is added to LD_LIBRARY_PATH.

**Comment by dineshjoshi** [comment]
I ran into a similar issue on macOS Sierra (10.12.3) and was able to fix it by setting `LD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/lib64`

**Comment by madanh** [comment]
I think the docs [here](http://deeplearning.net/software/theano/install_ubuntu.html) ,section "fix lib path" have to be more specific about 'lib subdirectory'  in question. E.g lib subdirectory of cuda installation, `/usr/local/cuda/lib` if installed from nvidia-provided packages.

**Comment by olivernina** [comment]
@dineshjoshi Thanks for the solution. I tried it on my macOS Sierra 10.13.6 and it worked well. Cheers!
