### ISSUE TITLE
Compiling give Clang errors.

### ISSUE THREAD

**Issue by BLCKPSTV** [Theano/Theano#6017]
I'm trying to run/compile [https://github.com/ryankiros/neural-storyteller](url) project. 
When I go to Ipython and type import generate I get all sorts of clang errors.. 

```Exception: Compilation failed (return status=1): clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sse4a'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-tbm'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-fma4'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-prfchw'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-rdseed'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sha'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: no such file or directory: '+cx16'. clang: error: no such file or directory: '+xsave'. clang: error: no such file or directory: '+bmi2'. clang: error: language not recognized: 'savec'. clang: error: no such file or directory: '+fsgsbase'. clang: error: no such file or directory: '+avx'. clang: error: no such file or directory: '+rtm'. clang: error: no such file or directory: '+popcnt'. clang: error: no such file or directory: '+fma'. clang: error: no such file or directory: '+bmi'. clang: error: no such file or directory: '+aes'. clang: error: no such file or directory: '+rdrnd'. clang: error: language not recognized: 'saves'. clang: error: no such file or directory: '+sse4.1'. clang: error: no such file or directory: '+sse4.2'. clang: error: no such file or directory: '+avx2'. clang: error: no such file or directory: '+sse'. clang: error: no such file or directory: '+lzcnt'. clang: error: no such file or directory: '+pclmul'. clang: error: no such file or directory: '+f16c'. clang: error: no such file or directory: '+ssse3'. clang: error: no such file or directory: '+mmx'. clang: error: no such file or directory: '+cmov'. clang: error: language not recognized: 'op'. clang: error: no such file or directory: '+movbe'. clang: error: no such file or directory: '+hle'. clang: error: no such file or directory: '+xsaveopt'. clang: error: no such file or directory: '+sse2'. clang: error: no such file or directory: '+sse3'. ```

**I've already switched from xcode 8.0 to 7.3, tried to install clang via homebrew conda etc... 
Is there any way to reverse engineer this problem or explain how I can not bump up to this problem again (I've already install my os twice to retry this project)**

My specs are OSX 10.12.5 (16F73)
All installation happened with conda, python2.7, bleeding Theano and Lasagne.

Clang info : 
```
llvm-gcc --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

**Comment by lamblin** [comment]
I thought this had been fixed a long while ago. Which version of Theano are you using?
Ping @abergeron

**Comment by BLCKPSTV** [comment]
Conda info theano gives me 

multiple installations?? I only installed twice...
```
Fetching package metadata ...........

theano 0.8.2 py27_0
-------------------
file name   : theano-0.8.2-py27_0.tar.bz2
name        : theano
version     : 0.8.2
build string: py27_0
build number: 0
channel     : defaults
size        : 3.6 MB
arch        : x86_64
date        : 2016-10-15
license     : BSD 3-Clause
license_family: BSD
md5         : d357261f46d36148f0866f4ee3e71fd4
noarch      : None
platform    : darwin
url         : https://repo.continuum.io/pkgs/free/osx-64/theano-0.8.2-py27_0.tar.bz2
dependencies:
    numpy >=1.3.0
    python 2.7*
    scipy >=0.7.0
    six >=1.9.0

theano 0.8.2 py34_0
-------------------
file name   : theano-0.8.2-py34_0.tar.bz2
name        : theano
version     : 0.8.2
build string: py34_0
build number: 0
channel     : defaults
size        : 3.7 MB
arch        : x86_64
date        : 2016-10-15
license     : BSD 3-Clause
license_family: BSD
md5         : 1c690652b7f7bf2d4e7098b3d62b6227
noarch      : None
platform    : darwin
url         : https://repo.continuum.io/pkgs/free/osx-64/theano-0.8.2-py34_0.tar.bz2
dependencies:
    numpy >=1.3.0
    python 3.4*
    scipy >=0.7.0
    six >=1.9.0

theano 0.8.2 py35_0
-------------------
file name   : theano-0.8.2-py35_0.tar.bz2
name        : theano
version     : 0.8.2
build string: py35_0
build number: 0
channel     : defaults
size        : 3.7 MB
arch        : x86_64
date        : 2016-10-15
license     : BSD 3-Clause
license_family: BSD
md5         : 5c4a125c9fc6bf3cdc3c7bce936ceefd
noarch      : None
platform    : darwin
url         : https://repo.continuum.io/pkgs/free/osx-64/theano-0.8.2-py35_0.tar.bz2
dependencies:
    numpy >=1.3.0
    python 3.5*
    scipy >=0.7.0
    six >=1.9.0

theano 0.9.0 py27_0
-------------------
file name   : theano-0.9.0-py27_0.tar.bz2
name        : theano
version     : 0.9.0
build string: py27_0
build number: 0
channel     : defaults
size        : 3.8 MB
arch        : x86_64
date        : 2017-03-22
license     : BSD 3-Clause
license_family: BSD
md5         : 0d38c5f94424d7386f6670b41903ea68
noarch      : None
platform    : darwin
url         : https://repo.continuum.io/pkgs/free/osx-64/theano-0.9.0-py27_0.tar.bz2
dependencies:
    mkl-service
    numpy >=1.9.1
    pygpu >=0.6.2
    python 2.7*
    scipy >=0.14.0
    six >=1.9.0

theano 0.9.0 py35_0
-------------------
file name   : theano-0.9.0-py35_0.tar.bz2
name        : theano
version     : 0.9.0
build string: py35_0
build number: 0
channel     : defaults
size        : 4.0 MB
arch        : x86_64
date        : 2017-03-22
license     : BSD 3-Clause
license_family: BSD
md5         : 642bd234899d44139ccfa68d862a36bc
noarch      : None
platform    : darwin
url         : https://repo.continuum.io/pkgs/free/osx-64/theano-0.9.0-py35_0.tar.bz2
dependencies:
    mkl-service
    numpy >=1.9.1
    pygpu >=0.6.2
    python 3.5*
    scipy >=0.14.0
    six >=1.9.0

theano 0.9.0 py36_0
-------------------
file name   : theano-0.9.0-py36_0.tar.bz2
name        : theano
version     : 0.9.0
build string: py36_0
build number: 0
channel     : defaults
size        : 4.0 MB
arch        : x86_64
date        : 2017-03-22
license     : BSD 3-Clause
license_family: BSD
md5         : a8fb030bac61a5c3e3d2258dde40083f
noarch      : None
platform    : darwin
url         : https://repo.continuum.io/pkgs/free/osx-64/theano-0.9.0-py36_0.tar.bz2
dependencies:
    mkl-service
    numpy >=1.9.1
    pygpu >=0.6.2
    python 3.6*
    scipy >=0.14.0
    six >=1.9.0

```

**Comment by lamblin** [comment]
`conda info` will give you information on all the packages existing in conda, not the installed ones.
Use `conda list theano` to see the one currently installed, if it was indeed installed by conda.
Otherwise, from Python:
```python
>>> import theano
>>> theano.__version__
```

**Comment by BLCKPSTV** [comment]
I get to results when doing that: 

```
# packages in environment at /Users/quintendewilde/anaconda/envs/py27:
#
Theano                    0.10.0.dev1               <pip>
theano                    0.9.0                    py27_0  
```

**Comment by BLCKPSTV** [comment]
**Update**

Somehow I got past (well till now) the clang error. I'm getting this one instead.
**maybe the clang error happens after this??**

```
/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py in <module>()
    261 # We must do those import to be able to create the full doc when
    262 # nvcc is not available
--> 263 from theano.sandbox.cuda.var import (CudaNdarrayVariable,
    264                                      CudaNdarrayConstant,
    265                                      CudaNdarraySharedVariable,

/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/var.py in <module>()
     14     # is not available
     15     from theano.sandbox.cuda import filter as type_support_filter
---> 16     from theano.sandbox.cuda.basic_ops import HostFromGpu, GpuFromHost
     17 except ImportError:
     18     pass

/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py in <module>()
   4146 
   4147 
-> 4148 @theano.compile.profilemode.register_profiler_printer
   4149 def profile_printer(fct_name, compile_time, fct_call_time, fct_call,
   4150                     apply_time, apply_cimpl, message, outputs_size,

AttributeError: 'module' object has no attribute 'profilemode'

```

**Comment by Sentient07** [comment]
What are your environment variables? Seems like you're using the old backend which is removed from the current master. To change to new backend follow this [link](http://deeplearning.net/software/theano/tutorial/using_gpu.html) .

**Comment by BLCKPSTV** [comment]
This one I already did yesterday, the output for this when I do it again is. 
without flag = uses cpu...
```
 THEANO_FLAGS=device=cuda0 python /Users/quintendewilde/Desktop/gpu1.py 
Traceback (most recent call last):
  File "/Users/quintendewilde/Desktop/gpu1.py", line 1, in <module>
    from theano import function, config, shared, tensor
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/__init__.py", line 123, in <module>
    import theano.gpuarray
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, nerv, extra_ops, multinomial, reduction
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/gpuarray/multinomial.py", line 11, in <module>
    import theano.sandbox.multinomial
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/multinomial.py", line 12, in <module>
    from theano.sandbox.cuda import cuda_available, GpuOp, register_opt
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 263, in <module>
    from theano.sandbox.cuda.var import (CudaNdarrayVariable,
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/var.py", line 16, in <module>
    from theano.sandbox.cuda.basic_ops import HostFromGpu, GpuFromHost
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 4148, in <module>
    @theano.compile.profilemode.register_profiler_printer
AttributeError: 'module' object has no attribute 'profilemode'

```

**Comment by abergeron** [comment]
You have two Theano installs please remove one of them (preferably the pip one) and try again.

**Comment by BLCKPSTV** [comment]
Deleted pip version 10 and retried in ipython
Conda still lists 0.9 from conda install

I really don't get what is happening :/


```
In [1]: import generate
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e2356e8a9459> in <module>()
----> 1 import generate

/Users/quintendewilde/projects/AI_Writer/generate.py in <module>()
      8 import skimage.transform
      9 
---> 10 import skipthoughts
     11 import decoder
     12 import embedding

/Users/quintendewilde/projects/AI_Writer/skipthoughts.py in <module>()
      4 import os
      5 
----> 6 import theano
      7 import theano.tensor as tensor
      8 

ImportError: No module named theano


```

**Comment by abergeron** [comment]
Remove the other theano and reinstall it.

**Comment by BLCKPSTV** [comment]
Hmmmpff, I've seen it working on other macs...

Ok I reinstalled. And import theano works. 

but following and former error rises up again.

```
In [1]: import generate
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-e2356e8a9459> in <module>()
----> 1 import generate

/Users/quintendewilde/projects/AI_Writer/generate.py in <module>()
      9 
     10 import skipthoughts
---> 11 import decoder
     12 import embedding
     13 

/Users/quintendewilde/projects/AI_Writer/decoder.py in <module>()
      4 import theano
      5 import theano.tensor as tensor
----> 6 from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
      7 
      8 import cPickle as pkl

/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py in <module>()
     21 from theano.compile import optdb
     22 from theano.gof import local_optimizer
---> 23 from . import multinomial
     24 
     25 import theano.sandbox.cuda

/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/multinomial.py in <module>()
     10 import copy
     11 
---> 12 from theano.sandbox.cuda import cuda_available, GpuOp, register_opt
     13 if cuda_available:
     14     from theano.sandbox.cuda import CudaNdarrayType

/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py in <module>()
    261 # We must do those import to be able to create the full doc when
    262 # nvcc is not available
--> 263 from theano.sandbox.cuda.var import (CudaNdarrayVariable,
    264                                      CudaNdarrayConstant,
    265                                      CudaNdarraySharedVariable,

/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/var.py in <module>()
     14     # is not available
     15     from theano.sandbox.cuda import filter as type_support_filter
---> 16     from theano.sandbox.cuda.basic_ops import HostFromGpu, GpuFromHost
     17 except ImportError:
     18     pass

/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py in <module>()
   4146 
   4147 
-> 4148 @theano.compile.profilemode.register_profiler_printer
   4149 def profile_printer(fct_name, compile_time, fct_call_time, fct_call,
   4150                     apply_time, apply_cimpl, message, outputs_size,

AttributeError: 'module' object has no attribute 'profilemode'
```

**Comment by abergeron** [comment]
Is the code for AI_Writer available somewhere?  I'll have to try and reproduce your problem locally.

Also can you send me the output of `conda list`?

**Comment by lamblin** [comment]
Or maybe you have old `.pyc` files from an earlier installation.

**Comment by BLCKPSTV** [comment]
Hey,

This is the repo I started with but this one needs changes from the original which missis installation parts of lasange etc.. but has the libraries en dicts to train the 'AI'. **also the generate.py & config.py of the first repo needs to be changed according to the neural_storytelling. It's a duplicate.** 

Source AI_Writer = [https://github.com/llSourcell/AI_Writer](url)
Neural_Story = [https://github.com/ryankiros/neural-storyteller](url)

> @theano.compile.profilemode is commented 
I didn't commented it out or I believe not on purpose, I don't know really where that file is (I didn't have time to take a look will do tonight)
The .pyc file are still in my folder and I did not delete them, so I suspect these are still the old one.
Regular deleting of these is no problem?

**Comment by abergeron** [comment]
Yes, you can safely delete the .pyc files.

**Comment by abergeron** [comment]
Can you run `python -c 'import theano; print(theano.__file__); print(theano.__version__)'`

**Comment by BLCKPSTV** [comment]
This happens when running:

```
(py27) iMacvanQuinten:AI_Writer quintendewilde$ python -c 'import theano; print(theano.__file__); print(theano.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/__init__.py", line 123, in <module>
    import theano.gpuarray
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, nerv, extra_ops, multinomial, reduction
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/gpuarray/multinomial.py", line 11, in <module>
    import theano.sandbox.multinomial
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/multinomial.py", line 12, in <module>
    from theano.sandbox.cuda import cuda_available, GpuOp, register_opt
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 263, in <module>
    from theano.sandbox.cuda.var import (CudaNdarrayVariable,
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/var.py", line 16, in <module>
    from theano.sandbox.cuda.basic_ops import HostFromGpu, GpuFromHost
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 4148, in <module>
    @theano.compile.profilemode.register_profiler_printer
AttributeError: 'module' object has no attribute 'profilemode'
```

Conda list =
```
# packages in environment at /Users/quintendewilde/anaconda/envs/py27:
#
appdirs                   1.4.3                     <pip>
appnope                   0.1.0                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py27_0  
configparser              3.5.0                    py27_0  
cycler                    0.10.0                   py27_0  
Cython                    0.25.2                    <pip>
decorator                 4.0.11                   py27_0  
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_0  
freetype                  2.5.5                         2  
functools32               3.2.3.2                  py27_0  
get_terminal_size         1.0.0                    py27_0  
html5lib                  0.999                    py27_0  
icu                       54.1                          0  
ipykernel                 4.6.1                    py27_0  
ipython                   5.3.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
jbig                      2.1                           0  
jinja2                    2.9.6                    py27_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py27_0  
jupyter_client            5.0.1                    py27_0  
jupyter_core              4.3.0                    py27_0  
Lasagne                   0.2.dev1                  <pip>
libgfortran               3.0.0                         0    conda-forge
libgpuarray               0.6.4                         0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
mako                      1.0.6                    py27_0  
Mako                      1.0.6                     <pip>
markupsafe                0.23                     py27_2  
matplotlib                2.0.2               np112py27_0  
mistune                   0.7.4                    py27_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py27_3  
nbconvert                 5.2.1                    py27_0  
nbformat                  4.3.0                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.4                    py27_0    anaconda
nose                      1.3.7                    py27_1  
notebook                  5.0.0                    py27_0  
numpy                     1.12.1          py27_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.44                     py27_0  
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2l                        0  
pandocfilters             1.4.1                    py27_0  
path.py                   10.3.1                   py27_0  
pathlib2                  2.2.1                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    4.1.1                    py27_0  
pip                       9.0.1                    py27_1  
prompt_toolkit            1.0.14                   py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.34                    <pip>
pycuda                    2017.1                    <pip>
pydot-ng                  1.0.0.15                 py27_0    anaconda
pygments                  2.2.0                    py27_0  
pygpu                     0.6.4                    py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_2  
pytest                    3.1.1                     <pip>
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
pytools                   2017.3                    <pip>
pytz                      2017.2                   py27_0  
pywavelets                0.5.2               np112py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         2  
readline                  6.2                           2  
requests                  2.14.2                   py27_0    anaconda
scandir                   1.5                      py27_0  
scikit-cuda               0.5.1                     <pip>
scikit-image              0.13.0              np112py27_0  
scipy                     0.19.0          np112py27_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
subprocess32              3.2.7                    py27_0  
terminado                 0.6                      py27_0  
testpath                  0.3.1                    py27_0  
theano                    0.9.0                    py27_0  
tk                        8.5.18                        0  
tornado                   4.5.1                    py27_0  
traitlets                 4.3.2                    py27_0  
wcwidth                   0.1.7                    py27_0  
wheel                     0.29.0                   py27_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
```

**Comment by abergeron** [comment]
You have packages mixed from conda-forge and anaconda which is a bad idea in general.

But in any case this doesn't have an influence on the current problem that your Theano package is somehow a modified version of the original package that has some files that differ.

To see where the problem might have come from add the following line to your .condarc: `show_channel_urls: true`.  (Create it and put that line in, if it doesn't exist).

**Comment by BLCKPSTV** [comment]
Which should I keep? Forge or original conda. 

I'm trying the .condarc file (if I find . where this is)

**Comment by BLCKPSTV** [comment]
Did you manage to recreate this?

**Comment by abergeron** [comment]
No, I wasn't able to reproduce this.  I'm more and more convinced that you have a modified package or stray .pyc files somewhere.

You can try:
```
source activate py27
conda remove theano
conda install theano
```

Also, which set of packages to keep is your decision.  I don't know what are your requirements here.
