### ISSUE TITLE
Wrong number of dimensions: expected 1, got 2 with shape (1, 32) Error

### ISSUE THREAD

**Issue by dimeldo** [Theano/Theano#6090]
Hey guys, I'm using this code (from [here](https://github.com/julianser/hed-dlg-truncated/blob/master/search.py#L139)):

``` Python
ran_vector = self.model.rng.normal(size=(context.shape[0],n_samples,self.model.latent_gaussian_per_utterance_dim)).astype('float32')
zero_mask = numpy.zeros((context.shape[0], self.model.bs), dtype='float32')
ones_mask = numpy.zeros((context.shape[0], self.model.bs), dtype='float32')

# Computes new utterance decoder hidden states (including intermediate utterance encoder and dialogue encoder hidden states)
new_hd = self.compute_decoder_encoding(enlarged_context, enlarged_reversed_context, self.max_len, zero_mask, zero_mask, numpy.zeros((self.model.bs), dtype='float32'), ran_vector, ones_mask)
prev_hd[:] = new_hd[0][-1][0:context.shape[1], :]
```
And I'm getting this error:
```
2017-06-29 23:40:23,073 INFO - Traceback (most recent call last):
2017-06-29 23:40:23,074 INFO - File "train.py", line 531, in <module>
2017-06-29 23:40:23,085 INFO - main(args)
2017-06-29 23:40:23,086 INFO - File "train.py", line 249, in main
2017-06-29 23:40:23,093 INFO - samples, costs = random_sampler.sample([[]], n_samples=1, n_turns=3)
2017-06-29 23:40:23,094 INFO - File "/code/search.py", line 55, in sample_apply
2017-06-29 23:40:23,104 INFO - samples, costs = sample_logic(sampler, joined_context, **kwargs)
2017-06-29 23:40:23,105 INFO - File "/code/search.py", line 153, in sample
2017-06-29 23:40:23,111 INFO - new_hd = self.compute_decoder_encoding(enlarged_context, enlarged_reversed_context, self.max_len, zero_mask, zero_mask, numpy.zeros((self.model.bs), dtype='float32'), ran_vector, ones_mask)
2017-06-29 23:40:23,111 INFO - File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 786, in __call__
2017-06-29 23:40:23,128 INFO - allow_downcast=s.allow_downcast)
2017-06-29 23:40:23,129 INFO - File "/usr/local/lib/python2.7/site-packages/theano/tensor/type.py", line 177, in filter
2017-06-29 23:40:23,139 INFO - data.shape))
2017-06-29 23:40:23,140 INFO - TypeError: ('Bad input argument to theano function with name "decoder_encoding_fn"  at index 4(0-based)', 'Wrong number of dimensions: expected 1, got 2 with shape (1, 32).')
```
How can I fix this?

**Comment by lamblin** [comment]
As the error message says, the fifth argument passed to `self.compute_decoder_encoding`, in this case the second instance of `zeros`, is a matrix of (1, 32), but a 1D vector was expected.
The fix would be either to make sure the theano function accepts a matrix or a row, or to pass a vector.
In any case, this is not a bug in Theano. If you did not change the original code, maybe you should open an issue on https://github.com/julianser/hed-dlg-truncated instead.
