### ISSUE TITLE
cuDNN reduction is broken

### ISSUE THREAD

**Issue by khaotik** [Theano/Theano#6118]
```
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano as th
T = th.Using cuDNN version 6020 on context None
Preallocating 1200/2000 Mb (0.600000) on cuda
tMapped name None to device cuda: GeForce GTX 750 Ti (0000:01:00.0)
>>> T = th.tensor
>>> x = T.tensor3()
>>> y = T.sum(x.transpose(0,2,1), axis=0)
>>> fn = th.function([x],y)
>>> import numpy as np
>>> fn(np.random.rand(4,5,6).astype('float32'))
Traceback (most recent call last):
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: Only contiguous inputs are supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: Only contiguous inputs are supported.
Apply node that caused the error: GpuDnnReduction{red_op='add', axis=(0,), acc_dtype='float32', dtype='float32', return_indices=False}(InplaceGpuDimShuffle{0,2,1}.0)
Toposort index: 2
Inputs types: [GpuArrayType<None>(float32, 3D)]
Inputs shapes: [(4, 6, 5)]
Inputs strides: [(120, 4, 24)]
Inputs values: ['not shown']
Inputs type_num: [11]
Outputs clients: [[HostFromGpu(gpuarray)(GpuDnnReduction{red_op='add', axis=(0,), acc_dtype='float32', dtype='float32', return_indices=False}.0)]]

Debugprint of the apply node: 
GpuDnnReduction{red_op='add', axis=(0,), acc_dtype='float32', dtype='float32', return_indices=False} [id A] <GpuArrayType<None>(float32, matrix)> ''   
 |InplaceGpuDimShuffle{0,2,1} [id B] <GpuArrayType<None>(float32, 3D)> ''   
   |GpuFromHost<None> [id C] <GpuArrayType<None>(float32, 3D)> ''   
     |<TensorType(float32, 3D)> [id D] <TensorType(float32, 3D)>

Storage map footprint:
 - <TensorType(float32, 3D)>, Input, Shape: (4, 5, 6), ElemSize: 4 Byte(s), TotalSize: 480 Byte(s)
 - GpuFromHost<None>.0, Shape: (4, 5, 6), ElemSize: 4 Byte(s), TotalSize: 480 Byte(s)
 - InplaceGpuDimShuffle{0,2,1}.0, Shape: (4, 6, 5), ElemSize: 4 Byte(s), TotalSize: 480 Byte(s)
 TotalSize: 960 Byte(s) 0.000 GB
 TotalSize inputs: 480 Byte(s) 0.000 GB

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
```

**Comment by nouiz** [comment]
@abergeron

**Comment by abergeron** [comment]
There is a fix for this in #6116

**Comment by juancamilog** [comment]
while waiting for that PR to be merged, would downgrading to cudnn 5 temporarily fix it?

**Comment by abergeron** [comment]
Yes, as that would disable the reductions through cuDNN.
