### ISSUE TITLE
Bug of raw_random.permutation()

### ISSUE THREAD

**Issue by zzd1992** [Theano/Theano#6129]
I use theano with version '0.10.0dev1.dev-RELEASE'. I can't run the function T.raw_random.permutation in my computer. Here is the code and traceback:
```python
 import theano
 import theano.tensor as T
 x = T.raw_random.permutation(random_state=12345,n=10)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)
  File "/home/zhang/mylib/Mylasagne/Layers/Dense.py", line 106, in <module>
    x = T.raw_random.permutation(random_state=12345,n=10)
  File "/home/zhang/tool/Theano/theano/tensor/raw_random.py", line 756, in permutation
    return op(random_state, size, n)
  File "/home/zhang/tool/Theano/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/zhang/tool/Theano/theano/tensor/raw_random.py", line 204, in make_node
    if not isinstance(r.type, RandomStateType):
AttributeError: 'int' object has no attribute 'type'
```
How to fix it?

**Comment by notoraptor** [comment]
Value for arg `random_state` should be a Theano random state symbolic variable, not directly an integer (12345):
```python
import numpy as np
import theano
from theano.tensor import raw_random
# 1) The random state symbolic variable.
rstate = raw_random.random_state_type()
# 2) The permutation results
next_rstate, x = raw_random.permutation(random_state=rstate, n=10)
# 3) the theano function
f = theano.function([rstate], [next_rstate, x])
# 4) Now run theano function with a random state value
rstate_val = np.random.RandomState(seed=12345)
next_rstate_val, x_val = f(rstate_val)
print(x_val)
# 5) You can reuse `next_rstate_val` to generate the next permutation on x, and so on.
next_rstate_val, x_val_2 = f(next_rstate_val)
print(x_val_2)
```

**Comment by zzd1992** [comment]
Can I directly set rstate without pass it through theano.function?
Or is there any other function which can replace raw_random.permulation?
@notoraptor

**Comment by notoraptor** [comment]
At the end, you will necessarly use `theano.function()`, because theano works by first creating a symbolic graph, and then executing the graph with some given values.

There are some ways to encapsulate rstate by using theano shared variables. I give an example below, but consider checking the theano documentation: http://deeplearning.net/software/theano_versions/dev/tutorial/examples.html#using-shared-variables .
```python
import numpy as np
import theano
from theano.tensor import raw_random
# The random state value into a shared variable.
rstate = theano.shared(np.random.RandomState(seed=12345))
next_rstate, x = raw_random.permutation(random_state=rstate, n=10)
# Shared variable (rstate) will be internally updated with new rstate (next_rstate).
# But you still need to create a function.
f = theano.function([], x, updates=[(rstate, next_rstate)])
# Then, you can run f() many times, to get different generated permutations.
print(f())
print(f())
print(f())
print(f())
print(f())
print(f())
# ...
```
