### ISSUE TITLE
Compile Failure and Performance Issue w/#5881

### ISSUE THREAD

**Issue by HapeMask** [Theano/Theano#6144]
After #5881 was merged (https://github.com/Theano/Theano/commit/4f3a52a55a31ce82e737d44f3025a26da247958a), I noticed a significant (10x) performance decrease while training a particular CNN.

I narrowed things down to the following small example: https://gist.github.com/HapeMask/01c36d97ea7c9afd4c4383ff014a9a18
The key is that the loss comes from an adv. subtensor, otherwise the bug isn't present.

The code is running on the gpu (profile mode shows 99.9% GPU time), but nvidia-smi shows a GPU utilization of only 8%. A quick check suggests that the time is being spent here: https://github.com/Theano/Theano/blob/master/theano/gpuarray/subtensor.py#L691

As a separate note, if you take the code in the above gist and remove all use of ```valid``` in ```nll()```, the sample fails to compile with the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/Theano-0.10.0.dev1-py3.6.egg/theano/compile/function_module.py", line 883, in __call__
    self.fn() if output_subset is None else\
  File "/usr/lib/python3.6/site-packages/Theano-0.10.0.dev1-py3.6.egg/theano/gof/op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/lib/python3.6/site-packages/Theano-0.10.0.dev1-py3.6.egg/theano/gpuarray/subtensor.py", line 696, in perform
    x_flat.__setitem__(i, tmp)
  File "pygpu/gpuarray.pyx", line 2096, in pygpu.gpuarray.GpuArray.__setitem__ (pygpu/gpuarray.c:26904)
  File "pygpu/gpuarray.pyx", line 346, in pygpu.gpuarray.array_setarray (pygpu/gpuarray.c:6287)
ValueError: b'Dimension error. a->nd = 0, v->nd = 1'
```

This is not the case at https://github.com/Theano/Theano/commit/86c195d221ffdb3bc024cd99f073fd357481562e, where the code compiles and runs as expected.

**Comment by aam-at** [comment]
My code is using [multiclass_hinge_loss](https://github.com/Lasagne/Lasagne/blob/master/lasagne/objectives.py#L302). After merging #5881, the code is 40x times slower. Gpu utilization is less than 10 percent. At 86c195d221ffdb3bc024cd99f073fd357481562e, no performance degradation.

**Comment by lamblin** [comment]
@HapeMask Whad did you change exactly to remove `valid`?
I used
```
nll = (mx[:,0] - pre_sm[b_idx, Y, r_idx, c_idx] + tt.log(tt.exp(pre_sm - mx).sum(axis=1)))
return nll
```
But I now have an index error instead:
```
Traceback (most recent call last):
  File "test_6144.py", line 34, in <module>
    f(xx, yy)
  File "/u/lamblinp/code/Theano_git/theano/compile/function_module.py", line 897, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/u/lamblinp/code/Theano_git/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/u/lamblinp/code/Theano_git/theano/compile/function_module.py", line 883, in __call__
    self.fn() if output_subset is None else\
  File "/u/lamblinp/code/Theano_git/theano/gof/op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "/u/lamblinp/code/Theano_git/theano/gpuarray/subtensor.py", line 700, in perform
    val = y_flat[j]
  File "pygpu/gpuarray.pyx", line 1985, in pygpu.gpuarray.GpuArray.__getitem__ (pygpu/gpuarray.c:24842)
  File "pygpu/gpuarray.pyx", line 2051, in pygpu.gpuarray.GpuArray.__cgetitem__ (pygpu/gpuarray.c:25728)
  File "pygpu/gpuarray.pyx", line 1598, in pygpu.gpuarray.GpuArray.__index_helper (pygpu/gpuarray.c:20384)
IndexError: index 0 out of bounds
Apply node that caused the error: GpuAdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}(GpuElemwise{Composite{(i0 + (EQ(i1, i2) * i3))}}[(0, 0)]<gpuarray>.0, Assert{msg='`x[i]` and `y` do not have the same shape.'}.0, InplaceDimShuffle{0,x,x}.0, GpuFromHost<None>.0, InplaceDimShuffle{x,0,x}.0, InplaceDimShuffle{x,x,0}.0)
Toposort index: 138
Inputs types: [GpuArrayType<None>(float32, 4D), GpuArrayType<None>(float32, (True, True, True)), TensorType(int64, (False, True, True)), GpuArrayType<None>(int32, 3D), TensorType(int64, (True, False, True)), TensorType(int64, (True, True, False))]
Inputs shapes: [(256, 16, 64, 64), (1, 1, 1), (256, 1, 1), (256, 64, 64), (1, 64, 1), (1, 1, 64)]
Inputs strides: [(262144, 16384, 256, 4), (4, 4, 4), (8, 8, 8), (16384, 256, 4), (512, 8, 8), (512, 512, 8)]
Inputs values: ['not shown', gpuarray.array([[[ -9.53674316e-07]]], dtype=float32), 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Shape(GpuAdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0), GpuContiguous(GpuAdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0)]]
```

**Comment by HapeMask** [comment]
Yes, you made the correct change. The error I posted came from the current master branch when I made the issue. I updated to the latest and now I get the same error you posted. In either case, no error is generated with https://github.com/Theano/Theano/commit/86c195d221ffdb3bc024cd99f073fd357481562e (and I have been successfully using that bit of code for quite awhile with past Theano versions).

**Comment by lamblin** [comment]
OK, thanks.
There are definitely issues with GpuAdvancedIncSubtensor. For now, I would advise disabling the optimization inserting it (`optimizer_excluding=local_gpua_advanced_subtensor` should do it), until we either disable it globally, or fix it.

**Comment by nouiz** [comment]
For now we disabled it. We won't make a faster implementation for 0.10, so I bump it to 0.11.
