### ISSUE TITLE
error on compiling with new backend on windows

### ISSUE THREAD

**Issue by aeloyq** [Theano/Theano#6145]
Windows 10 with cuda 8.0  cudnn 5.1 driver 378.78
Anaconda python 2.7 and VS2013
installed theano by
conda install theano pygpu(also tried conda install pygpu=0.6.2)

theanoflags:

> [global]
device=cuda
floatX = float32
cxx=C:\Users\aeloyq\Anaconda2\Library\mingw-w64\bin\g++.exe
[dnn]
enabled=True
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64
[gpuarray]
preallocate=0.8

when runing lstm.py in DeepLearningTutorials

got error:

Could not load "nvrtc64_90.dll"（0.6.8）

> ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu\gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:9424)
  File "pygpu\gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9115)
  File "pygpu\gpuarray.pyx", line 1057, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13417)
GpuArrayException: Could not load "nvrtc64_90.dll": �Ҳ���ָ����ģ�顣

ImportError: ('The following error happened while compiling the node', GpuDot22(GpuReshape{2}.0, lstm_W), '\n', 'pygpu.blas does not export expected C function pygpu_blas_rgemmBatch_3d')（0.6.2）

> Using cuDNN version 5110 on context None
Preallocating 9011/11264 Mb (0.800000) on cuda
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:06:00.0)
model options {'encoder': 'lstm', 'optimizer': <function adadelta at 0x000000001C3AFD68>, 'validFreq': 370, 'lrate': 0.0001, 'batch_size': 16, 'decay_c': 0.0, 'patience': 10, 'reload_model': None, 'n_words': 10000, 'max_epochs': 100, 'dispFreq': 10, 'dataset': 'imdb', 'valid_batch_size': 64, 'use_dropout': True, 'dim_proj': 128, 'maxlen': 100, 'saveto': 'lstm_model.npz', 'noise_std': 0.0, 'test_size': 500, 'saveFreq': 1110}
Loading data
Building model
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '8712' (I am process '12316')
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydev_run_in_console.py", line 78, in <module>
    globals = run_file(file, None, None)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydev_run_in_console.py", line 35, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "F:/Machine Learning/DeepLearningTutorials-master/code/lstm.py", line 656, in <module>
    test_size=500,
  File "F:/Machine Learning/DeepLearningTutorials-master/code/lstm.py", line 511, in train_lstm
    y, f_pred_prob, f_pred, cost) = build_model(tparams, model_options)
  File "F:/Machine Learning/DeepLearningTutorials-master/code/lstm.py", line 394, in build_model
    f_pred_prob = theano.function([x, mask], pred, name='f_pred_prob')
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1795, in orig_function
    defaults)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\vm.py", line 1047, in make_all
    impl=impl))
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 1118, in module_from_key
    module = self._get_from_key(key)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 1017, in _get_from_key
    return self._get_module(name)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 691, in _get_module
    self.module_from_name[name] = dlimport(name)
  File "C:\Users\aeloyq\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: ('The following error happened while compiling the node', GpuDot22(GpuReshape{2}.0, lstm_W), '\n', 'pygpu.blas does not export expected C function pygpu_blas_rgemmBatch_3d')

**Comment by khaotik** [comment]
It says missing NVRTC component, which is required for gpuarray JIT compilation.

I don't know about windows side. On linux, it looks like:
```
khaotik@KKST:/usr/local/cuda/lib64$ ls | grep nvrtc
libnvrtc-builtins.so
libnvrtc-builtins.so.8.0
libnvrtc-builtins.so.8.0.61
libnvrtc.so
libnvrtc.so.8.0
libnvrtc.so.8.0.61
```
Can you find NVRTL DLL under `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64` ? If not, a CUDA toolkit reinstall would solve the problem.

**Comment by aeloyq** [comment]
just found nvrtc.dll
i think there is nothing wrong with cuda because i just installed it on a fresh operating system

**Comment by khaotik** [comment]
The error message says could not load `nvrtc64_90.dll`, which is weird, because CUDA 9.0 has not been released yet.

**Comment by notoraptor** [comment]
About `nvrtc64_90.dll`, the latest NVIDIA drivers may already expect to work with CUDA 9.0 and related DLLs. Have you recently updated your drivers ?

This have been recently fixed in gpuarray master branch ( https://github.com/Theano/libgpuarray/pull/476 ), but not yet ported to conda package. @abergeron can confirm.

**Comment by aeloyq** [comment]
yes, these error occurred after i upgrade my driver

**Comment by abergeron** [comment]
You can work around this by exporting `GPUARRAY_CUDA_VERSION=80` so that it loads the libraries from cuda 8.0.  As mentionned this is fixed in master and should arrive in the next release.

**Comment by aeloyq** [comment]
ok now theano can be import but it crashed when compiling the theano function with exit code -1073741819 (0xC0000005)

**Comment by notoraptor** [comment]
Does it crashes with any other message ?

Could you clear the theano cache (`theano-cache purge`) and then retry ?

**Comment by abergeron** [comment]
That something I've never seen before.

You are using the conda packages on windows?  Which versions exactly?

**Comment by aeloyq** [comment]
i faced same situation on both two computers and one of them was reinstalled system(Win 10) recently.
i downloaded anaconda cuda cudnn from official website anaconda' version is Anaconda2-4.4.0-Windows-x86_64
then:
conda install theano pygpu
conda upgrade numpy
finally
set GPUARRAY_CUDA_VERSION=80

**Comment by aeloyq** [comment]
After downgrade pygpu to 0.6.4 problem solved !

**Comment by aeloyq** [comment]
My msvc is not able to compile(make) the latest version of pygpu 0.6.8
May anyone help to test it or provides compiled files.

**Comment by abergeron** [comment]
There are conda packages that you should use instead of compiling it yourself if you have trouble.

**Comment by aeloyq** [comment]
Since @notoraptor  said

> This have been recently fixed in gpuarray master branch ( Theano/libgpuarray#476 ), but not yet ported to conda package.

So i think current conda package dosen't contain the patch and the latest release or dev one is needed instead.

How long will it take for releasing a newer version in common? 
Or where can i find version 0.6.7(only 0.6.2, 0.6.4, 0.6.8 can be found in conda)

BR

**Comment by abergeron** [comment]
Not all versions were compiled.  Also, to work with 0.6.8 you can export `GPUARRAY_CUDA_VERSION=80` and it will load cuda 8.0.

**Comment by afung01** [comment]
I am new to theano and I currently own a 1080TI and since installing the most recent drivers I too am getting the could not load nvrtc64_90.dll. The previous posts here mentions creating an environment variable GPUARRAY_CUDA_VERSION=80. Can someone explain what the Variable Name and Value would be?

I tried Name as GPUARRAY_CUDA_VERSION and Value as 80 and it does not work

**Comment by notoraptor** [comment]
Have you created the environment variable through Windows Control Panel ? If so, you must then close and reopen the command line (or any program/windows where you use Theano) so that changes are taken into account.
