### ISSUE TITLE
Install theano for my second version of python(3,6)

### ISSUE THREAD

**Issue by tswc** [Theano/Theano#6155]
I have just installed 2 versions of python-----2.7 and 3.6
But when I install theano for 3.6, I got this error.
Why does the package of python 3.6 still use the packages of 2.7?
Is that the problem with PATH environment variable?

NEED HELP!!!!!thanks!!!!

`Traceback (most recent call last):
  File "C:/Users/TSWC/Google Drive/FA/python_2c/test1.py", line 1, in <module>
    import theano
  File "C:\Users\TSWC\AppData\Local\conda\conda\envs\py3\lib\site-packages\theano\__init__.py", line 45, in <module>
    from theano.configdefaults import config
  File "C:\Users\TSWC\AppData\Local\conda\conda\envs\py3\lib\site-packages\theano\configdefaults.py", line 17, in <module>
    from theano.configparser import (AddConfigVar, BoolParam, ConfigParam, EnumStr,
  File "C:\Users\TSWC\AppData\Local\conda\conda\envs\py3\lib\site-packages\theano\configparser.py", line 16, in <module>
    from theano.compat import configparser as ConfigParser
  File "C:\Users\TSWC\AppData\Local\conda\conda\envs\py3\lib\site-packages\theano\compat\__init__.py", line 7, in <module>
    from six.moves import configparser
  File "C:\Users\TSWC\AppData\Local\conda\conda\envs\py3\lib\site-packages\six.py", line 92, in __get__
    result = self._resolve()
  File "C:\Users\TSWC\AppData\Local\conda\conda\envs\py3\lib\site-packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "C:\Users\TSWC\AppData\Local\conda\conda\envs\py3\lib\site-packages\six.py", line 82, in _import_module
    __import__(name)
  File "C:\ProgramData\Anaconda2\Lib\site-packages\theano\configparser.py", line 16, in <module>
    from theano.compat import configparser as ConfigParser
ImportError: cannot import name 'configparser'`

**Comment by tswc** [comment]
I was going to install configparser.
Then I got new problem.
`(py3) C:\Users\TSWC>conda install configparser                                                                                                                                                                                              Fetching package metadata .............                                                                                                                                                                                                     Solving package specifications: .                                                                                                                                                                                                                                                                                                                                                                                                                                                       UnsatisfiableError: The following specifications were found to be in conflict:                                                                                                                                                                - configparser -> python 2.7*                                                                                                                                                                                                               - python 3.6*                                                                                                                                                                                                                             Use "conda info <package>" to see the dependencies for each package.   `

**Comment by lamblin** [comment]
If you want to install multiple versions of Python at the same time, a good option is to use conda environments.
This is not the place to discuss this.
