### ISSUE TITLE
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by weiwancheng** [Theano/Theano#6191]
I use theano on windows and python3. get an error,please help me. 

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -I"C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\theano\\sandbox\\cuda" -I"C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\numpy\\core\\include" -I"C:\\Users\\Administrator\\Anaconda3\\include" -I"C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\theano\\gof" -L"C:\\Users\\Administrator\\Anaconda3\\libs" -L"C:\\Users\\Administrator\\Anaconda3" -o C:\\Users\\Administrator\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -lcublas -lpython35 -lcudart')
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH

['nvcc', '-shared', '-O3', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-I"C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\theano\\sandbox\\cuda"', '-I"C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\numpy\\core\\include"', '-I"C:\\Users\\Administrator\\Anaconda3\\include"', '-I"C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\theano\\gof"', '-L"C:\\Users\\Administrator\\Anaconda3\\libs"', '-L"C:\\Users\\Administrator\\Anaconda3"', '-o', 'C:\\Users\\Administrator\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\\cuda_ndarray\\cuda_ndarray.pyd', 'mod.cu', '-lcublas', '-lpython35', '-lcudart']
ERROR (theano.gof.opt): Optimization failure due to: local_subtensor_merge
ERROR (theano.gof.opt): node: Subtensor{:int64:}(Subtensor{int64::}.0, ScalarFromTensor.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 3033, in local_subtensor_merge
    ushape[pos_2]))
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 2981, in merge_two_slices
    start = pre_greedy_local_optimizer(list_opt, start)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2880, in pre_greedy_local_optimizer
    list_optimizations, out, {}, 0)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2852, in local_recursive_function
    depth + 1)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2852, in local_recursive_function
    depth + 1)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2864, in local_recursive_function
    ret = opt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: local_subtensor_merge
ERROR (theano.gof.opt): node: Subtensor{:int64:}(Subtensor{int64::}.0, ScalarFromTensor.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 3033, in local_subtensor_merge
    ushape[pos_2]))
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 2981, in merge_two_slices
    start = pre_greedy_local_optimizer(list_opt, start)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2880, in pre_greedy_local_optimizer
    list_optimizations, out, {}, 0)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2852, in local_recursive_function
    depth + 1)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2852, in local_recursive_function
    depth + 1)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2864, in local_recursive_function
    ret = opt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: local_subtensor_merge
ERROR (theano.gof.opt): node: Subtensor{:int64:}(x_mask[0:], ScalarFromTensor.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 3033, in local_subtensor_merge
    ushape[pos_2]))
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 2981, in merge_two_slices
    start = pre_greedy_local_optimizer(list_opt, start)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2880, in pre_greedy_local_optimizer
    list_optimizations, out, {}, 0)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2852, in local_recursive_function
    depth + 1)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2852, in local_recursive_function
    depth + 1)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 2864, in local_recursive_function
    ret = opt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: ScalarFromTensor(TensorConstant{0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x,x}(TensorConstant{1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x,x,x}(TensorConstant{1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: ScalarFromTensor(TensorConstant{1})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: ScalarFromTensor(TensorConstant{0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x,x}(TensorConstant{1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

INFO (theano.gof.compilelock): Refreshing lock C:\Users\Administrator\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\lock_dir\lock
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x,x,x}(TensorConstant{1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: ScalarFromTensor(TensorConstant{1})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: ScalarFromTensor(TensorConstant{0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\tensor\opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

**Comment by lamblin** [comment]
Please use StackOverflow or theano-users to request support. Please provide more information there regarding your set up, OS, versions, etc.
It looks like your `%PATH%` does not contain all the DLLs that the modules compiled by Theano are needing. You can use the Dependency Walker to check what the missing dependencies are.
It may be an issue with the set up of Anaconda, for instance.
