### ISSUE TITLE
ValueError: total size of new array must be unchanged with [optimizer = fast_run]

### ISSUE THREAD

**Issue by noskill** [Theano/Theano#6195]
I get this traceback with optimizer = fast_run, but not with fast_compile. Theano from master 048d0c472b42a86c9317df704c7f7cb66c0ecac1
my .theanorc:

```
[global]
floatX = float64
device = cpu
compute_test_value = warn 
optimizer = fast_run
#optimizer = fast_compile
exception_verbosity=high

[nvcc]
fastmath = True
```

traceback:
```
Traceback (most recent call last):
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4490)
ValueError: total size of new array must be unchanged

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "actorcritic_error1.py", line 207, in <module>
    n_steps=steps)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan.py", line 1076, in scan
    scan_outs = local_op(*scan_inputs)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gof/op.py", line 674, in __call__
    required = thunk()
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4606)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib/python3.4/site-packages/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4490)
ValueError: total size of new array must be unchanged
Apply node that caused the error: Reshape{2}(Elemwise{mul}.0, MakeVector{dtype='int64'}.0)
Toposort index: 67
Inputs types: [TensorType(float64, vector), TensorType(int64, vector)]
Inputs shapes: [(2,), (2,)]
Inputs strides: [(8,), (8,)]
Inputs values: [array([ 0.00067265,  0.00098442]), array([700,   1])]
Inputs type_num: [12, 7]
Outputs clients: [[Sum{axis=[0], acc_dtype=float64}(Reshape{2}.0), Dot22(Reshape{2}.0, W.T), Gemm{no_inplace}(<TensorType(float64, matrix)>, TensorConstant{1e-05}, InplaceDimShuffle{1,0}.0, Reshape{2}.0, TensorConstant{0.9})]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1162, in access_term_cache
    new_output_grads)

Debugprint of the apply node: 
Reshape{2} [id A] <TensorType(float64, matrix)> ''   
 |Elemwise{mul} [id B] <TensorType(float64, vector)> ''   
 | |TensorConstant{(1,) of 0...2857142857} [id C] <TensorType(float64, (True,))>
 | |Elemwise{Composite{((i0 - i1) - (i2 * i3))}}[(0, 0)] [id D] <TensorType(float64, vector)> ''   
 |   |Reshape{1} [id E] <TensorType(float64, vector)> ''   
 |   | |Elemwise{Add}[(0, 0)] [id F] <TensorType(float64, matrix)> ''   
 |   | | |Dot22 [id G] <TensorType(float64, matrix)> ''   
 |   | | | |Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)] [id H] <TensorType(float64, matrix)> ''   
 |   | | | | |Dot22 [id I] <TensorType(float64, matrix)> ''   
 |   | | | | | |Join [id J] <TensorType(float64, matrix)> 'concatenete_axis_1'   
 |   | | | | | |W_copy [id K] <TensorType(float64, matrix)>
 |   | | | | |InplaceDimShuffle{x,0} [id L] <TensorType(float64, row)> ''   
 |   | | | |   |b_copy [id M] <TensorType(float64, vector)>
 |   | | | |W_copy [id N] <TensorType(float64, matrix)>
 |   | | |InplaceDimShuffle{x,0} [id O] <TensorType(float64, row)> ''   
 |   | |   |b_copy [id P] <TensorType(float64, vector)>
 |   | |TensorConstant{(1,) of -1} [id Q] <TensorType(int64, (True,))>
 |   |FromFunctionOp{_call}.3 [id R] <TensorType(float64, vector)> 'rewards'   
 |   |TensorConstant{(1,) of 0.99} [id S] <TensorType(float64, (True,))>
 |   |Reshape{1} [id T] <TensorType(float64, vector)> ''   
 |     |Elemwise{Add}[(0, 0)] [id U] <TensorType(float64, matrix)> ''   
 |     | |Dot22 [id V] <TensorType(float64, matrix)> ''   
 |     | | |Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)] [id W] <TensorType(float64, matrix)> ''   
 |     | | | |Dot22 [id X] <TensorType(float64, matrix)> ''   
 |     | | | | |Join [id Y] <TensorType(float64, matrix)> 'concatenete_axis_1'   
 |     | | | | |W_copy [id K] <TensorType(float64, matrix)>
 |     | | | |InplaceDimShuffle{x,0} [id L] <TensorType(float64, row)> ''   
 |     | | |W_copy [id N] <TensorType(float64, matrix)>
 |     | |InplaceDimShuffle{x,0} [id O] <TensorType(float64, row)> ''   
 |     |TensorConstant{(1,) of -1} [id Q] <TensorType(int64, (True,))>
 |MakeVector{dtype='int64'} [id Z] <TensorType(int64, vector)> ''   
   |TensorConstant{700} [id BA] <TensorType(int64, scalar)>
   |Shape_i{1} [id BB] <TensorType(int64, scalar)> ''   
     |W_copy [id N] <TensorType(float64, matrix)>

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

```

**Comment by lamblin** [comment]
Scan has a limitation that the inputs and outputs of the step functions must have the same shape at each iteration.
Could it be possible that the step function produces results of varying shapes?

It is also possible that an optimization tries to move some computation outside of the loop, which would result in output variables of varying shape, instead of only intermediate variables, see #5249.
Can you adding `optimizer_excluding=scanOp_pushout_output` to `THEANO_FLAGS`?

**Comment by noskill** [comment]
> Could it be possible that the step function produces results of varying shapes?

When running with fast_compile outputs of theano.function have same shapes(except for first dimension), like expected.


I added optimizer_excluding=scanOp_pushout_output to .theanorc and got exactly the same error.

But when i assigned names for all variables debugprint is a little bit different:
```
Traceback (most recent call last):
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4490)
ValueError: total size of new array must be unchanged

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "actorcritic_error2.py", line 215, in <module>
    n_steps=steps)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan.py", line 1076, in scan
    scan_outs = local_op(*scan_inputs)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gof/op.py", line 674, in __call__
    required = thunk()
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4606)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib/python3.4/site-packages/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4490)
ValueError: total size of new array must be unchanged
Apply node that caused the error: Reshape{2}((dloss/dc_Qvalue), MakeVector{dtype='int64'}.0)
Toposort index: 67
Inputs types: [TensorType(float64, vector), TensorType(int64, vector)]
Inputs shapes: [(2,), (2,)]
Inputs strides: [(8,), (8,)]
Inputs values: [array([ -9.50308139e-06,   1.07883686e-04]), array([700,   1])]
Inputs type_num: [12, 7]
Outputs clients: [[Sum{axis=[0], acc_dtype=float64}(Reshape{2}.0), Dot22(Reshape{2}.0, W.T), Gemm{no_inplace}(<TensorType(float64, matrix)>, TensorConstant{1e-05}, InplaceDimShuffle{1,0}.0, Reshape{2}.0, TensorConstant{0.9})]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1162, in access_term_cache
    new_output_grads)

Debugprint of the apply node: 
Reshape{2} [id A] <TensorType(float64, matrix)> ''   
 |Elemwise{mul} [id B] <TensorType(float64, vector)> '(dloss/dc_Qvalue)'   
 |MakeVector{dtype='int64'} [id C] <TensorType(int64, vector)> ''   
   |TensorConstant{700} [id D] <TensorType(int64, scalar)>
   |Shape_i{1} [id E] <TensorType(int64, scalar)> ''   
     |W_copy [id F] <TensorType(float64, matrix)>

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by lamblin** [comment]
> Update: shape is varying for some variables which are not returned from scan.

Thanks. For me it confirms it would be possible that a "pushout" optimization pushes a node outside of the loop, even when its shape is not constant across the steps.

Can you try with:
- `optimizer_excluding=scan_pushout_dot1`
- `optimizer_excluding=scanOp_pushout_seqs_ops`
- `optimizer_excluding=scanOp_pushout_nonseqs_ops`

**Comment by noskill** [comment]
Same error with this parameters:

optimizer_excluding=scanOp_pushout_output:scan_pushout_dot1:scanOp_pushout_seqs_ops:scanOp_pushout_nonseqs_ops:scanOp_pushout_output:scan_pushout_dot1:scanOp_pushout_seqs_ops:scanOp_pushout_nonseqs_ops
