### ISSUE TITLE
ValueError: Split: the splits sums to 3, expected 4. with [optimizer = fast_run] 

### ISSUE THREAD

**Issue by noskill** [Theano/Theano#6196]
I get this traceback with optimizer = fast_run, but not with fast_compile. Theano from master 048d0c4
my .theanorc:

```
[global]
floatX = float64
device = cpu
compute_test_value = warn 
optimizer = fast_run
#optimizer = fast_compile
exception_verbosity=high

[nvcc]
fastmath = True
```

traceback:

```
Traceback (most recent call last):
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4490)
ValueError: Split: the splits sums to 3, expected 4.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "actorcritic_error0.py", line 161, in <module>
    n_steps=10000)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan.py", line 1076, in scan
    scan_outs = local_op(*scan_inputs)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gof/op.py", line 674, in __call__
    required = thunk()
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4606)
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib/python3.4/site-packages/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/leron/.theano/compiledir_Linux-4.1--default-x86_64-with-SuSE-42.1-x86_64-x86_64-3.4.5-64/scan_perform/mod.cpp:4490)
ValueError: Split: the splits sums to 3, expected 4.
Apply node that caused the error: Split{2}((dmean/dconcatenete_axis_1), TensorConstant{1}, MakeVector{dtype='int64'}.0)
Toposort index: 74
Inputs types: [TensorType(float64, matrix), TensorType(int8, scalar), TensorType(int64, vector)]
Inputs shapes: [(20, 4), (), (2,)]
Inputs strides: [(32, 8), (), (8,)]
Inputs values: ['not shown', array(1, dtype=int8), array([2, 1])]
Inputs type_num: [12, 1, 7]
Outputs clients: [[], [Elemwise{Mul}[(0, 1)](TensorConstant{(1, 1) of 2.0}, Split{2}.1, Elemwise{Composite{(i0 - sqr(i1))}}[(0, 1)].0), Elemwise{mul,no_inplace}(Split{2}.1, Elemwise{Composite{(i0 - sqr(i1))}}[(0, 1)].0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib/python3.4/site-packages/Theano-0.10.0.dev1-py3.4.egg/theano/gradient.py", line 1162, in access_term_cache
    new_output_grads)

Debugprint of the apply node: 
Split{2}.0 [id A] <TensorType(float64, matrix)> ''   
 |Dot22 [id B] <TensorType(float64, matrix)> '(dmean/dconcatenete_axis_1)'   
 |TensorConstant{1} [id C] <TensorType(int8, scalar)>
 |MakeVector{dtype='int64'} [id D] <TensorType(int64, vector)> ''   
   |TensorConstant{2} [id E] <TensorType(int64, scalar)>
   |Shape_i{1} [id F] <TensorType(int64, scalar)> ''   
     |W_copy [id G] <TensorType(float64, matrix)>
Split{2}.1 [id A] <TensorType(float64, matrix)> ''   

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

```

**Comment by lamblin** [comment]
That's quite strange.
The underlying cause could be the same as #6195. Could you try to see if the same suggestion helps?

**Comment by noskill** [comment]
I wasn't able to reproduce this problem in a small script, so my code, if this helps, is here: 

https://bitbucket.org/noSkill/fireml/src/94a84029f4754e9ea02264194deb79eba7395f37/example/reinforcement/actorcritic_error0.py
