### ISSUE TITLE
could not find cudnn library in developer install

### ISSUE THREAD

**Issue by sandeep-gh** [Theano/Theano#6258]
I am doing a developer install of theano. 
I was able to install and test libgpuarray successfully.
Theano installs correctly but fails to run. 
My LD_LIBRARY_PATH looks as follows:

```
/home/sandeep/NDSSL-Software/theano_from_source/cuda/lib64:
/cm/shared/apps/cuda70/toolkit/7.0.28/extras/CUPTI/lib64:
/cm/shared/apps/cuda70/toolkit/7.0.28/lib64:
/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/NVIDIA-Linux-x86_64-375.74-diagnostic:
/home/sandeep/NDSSL-Software/theano_from_source/libgpuarray/lib/:
/home/sandeep/NDSSL-Software/theano_from_source/lib/:
/cm/local/apps/cuda/libs/current/lib64:/usr/lpp/mmfs/lib
```

The .theanorc looks like this:
```
[global]
device = cuda

[dnn]
include_path=/home/sandeep/NDSSL-Software/theano_from_source/cuda/include/
library_path=/home/sandeep/NDSSL-Software/theano_from_source/cuda/lib64/
```

However I get following error:
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/__init__.py", line 179, in <module>
    use(config.device)
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/__init__.py", line 166, in use
    init_dev(device, preallocate=preallocate)
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/__init__.py", line 73, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/dnn.py", line 111, in _make_handle
    cudnn = _dnn_lib()
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/dnn.py", line 93, in _dnn_lib
    raise RuntimeError('Could not find cudnn library (looked for v5* or v6*)')
RuntimeError: Could not find cudnn library (looked for v5* or v6*)
```

**Comment by sandeep-gh** [comment]
Turns out it was LIBRARY_PATH not defined issue. Thanks.

**Comment by negargoli** [comment]
I faced the same problem can you explain what do you mean by "Turns out it was LIBRARY_PATH not defined issue"
thanks

**Comment by nouiz** [comment]
The environment variable LIBRARY_PATH was not defined (or did not contain the information needed.
