### ISSUE TITLE
theano on linux; dev install; error creating cudnn handle 

### ISSUE THREAD

**Issue by sandeep-gh** [Theano/Theano#6259]
I am doing a developer install of theano. 
I was able to install and test libgpuarray successfully.
Theano installs correctly but fails to run. 
My LD_LIBRARY_PATH looks as follows:

```
/home/sandeep/NDSSL-Software/theano_from_source/cuda/lib64:
/cm/shared/apps/cuda70/toolkit/7.0.28/extras/CUPTI/lib64:
/cm/shared/apps/cuda70/toolkit/7.0.28/lib64:
/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/NVIDIA-Linux-x86_64-375.74-diagnostic:
/home/sandeep/NDSSL-Software/theano_from_source/libgpuarray/lib/:
/home/sandeep/NDSSL-Software/theano_from_source/lib/:
/cm/local/apps/cuda/libs/current/lib64:/usr/lpp/mmfs/lib
```

The .theanorc looks like this:
```
[global]
device = cuda

[dnn]
include_path=/home/sandeep/NDSSL-Software/theano_from_source/cuda/include/
library_path=/home/sandeep/NDSSL-Software/theano_from_source/cuda/lib64/
```
Other env variables:
```
export CPATH=/home/sandeep/NDSSL-Software/theano_from_source/cuda/include 
export LIBRARY_PATH=/home/sandeep/NDSSL-Software/theano_from_source/cuda/lib64:$LD_LIBRARY_PATH
```
The cuda/include and cuda/lib64/ has all the include and lib files for cuda toolkit. 

However I get following error:
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/__init__.py", line 179, in <module>
    use(config.device)
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/__init__.py", line 166, in use
    init_dev(device, preallocate=preallocate)
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/__init__.py", line 73, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File "/home/sandeep/NDSSL-Software/theano_from_source/Theano/theano/gpuarray/dnn.py", line 116, in _make_handle
    raise RuntimeError("error creating cudnn handle")
RuntimeError: error creating cudnn handle
[Elemwise{exp,no_inplace}(<TensorType(float64, vector)>)]

```

**Comment by sandeep-gh** [comment]
The above error was with cudnn 8.0. When I use cudnn-7.5, I get following error:

```
In [1]: run -i test_theano_gpu.py
Using cuDNN version 5005 on context None
Mapped name None to device cuda0: Tesla K20m (0000:03:00.0)

You can find the C code in this temporary file: /tmp/theano_compilation_error_AJHMSB
library inux-x86_64.egg/pygpu/gpuarray_api.h:6, is not found.
library inux-x86_64.egg/pygpu/gpuarray.h:20: is not found.
library inux-x86_64.egg/pygpu/gpuarray.h:20: is not found.
library inux-x86_64.egg/pygpu/gpuarray.h:35: is not found.
library inux-x86_64.egg/pygpu/gpuarray.h:51: is not found.
library inux-x86_64.egg/pygpu/gpuarray_api.h:25: is not found.
library inux-x86_64.egg/pygpu/gpuarray_api.h:27: is not found.
```

Were in theano is above path specified?

**Comment by sandeep-gh** [comment]
I copied binaries/gpuarray from theano to cuda/include and that seems to fix it. 
I am not sure what step i missed in installation that mis-wired that header file.
