### ISSUE TITLE
GpuAdvancedIncSubtensor "fancy indexing not supported"

### ISSUE THREAD

**Issue by gvtulder** [Theano/Theano#6277]
PR #6220 has disabled the optimization that introduces `GpuAdvancedIncSubtensor`. I'd like to add another bug to the list. This might be related to the bug discussed in #6144, but my example gives me a different error message.

If you re-enable the `local_gpua_advanced_incsubtensor` optimization, this will give an error if you run it with `device=cuda` (it works on the CPU without problems):
```python
import numpy as np
import theano
import theano.tensor as T

x = T.matrix()
a = T.vector(dtype='bool')

x_v = np.arange(9).reshape(3, 3).astype(theano.config.floatX)
a_v = np.array([True, False, True])

f = theano.function([x, a], T.inc_subtensor(x[(0,) + a.nonzero()], 1))
theano.printing.debugprint(f)
print(f(x_v, a_v))
```

```
Using cuDNN version 5105 on context None
Mapped name None to device cuda: Quadro K1000M (0000:01:00.0)
HostFromGpu(gpuarray) [id A] ''   4
 |GpuAdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False} [id B] ''   3
   |GpuFromHost<None> [id C] ''   2
   | |<TensorType(float32, matrix)> [id D]
   |GpuArrayConstant{1} [id E]
   |TensorConstant{0} [id F]
   |Subtensor{int64} [id G] ''   1
     |Nonzero [id H] ''   0
     | |<TensorType(bool, vector)> [id I]
     |Constant{0} [id J]
Traceback (most recent call last):
  File "test_adv_index.py", line 13, in <module>
    print(f(x_v, a_v))
  File "/home/gijs/src/theano-git/theano/compile/function_module.py", line 897, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/gijs/src/theano-git/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/gijs/src/theano-git/theano/compile/function_module.py", line 883, in __call__
    self.fn() if output_subset is None else\
  File "/home/gijs/src/theano-git/theano/gof/op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/gijs/src/theano-git/theano/gpuarray/subtensor.py", line 714, in perform
    x_flat_sub = x_flat[i].__getitem__(index)
  File "pygpu/gpuarray.pyx", line 1950, in pygpu.gpuarray.GpuArray.__getitem__ (pygpu/gpuarray.c:24400)
NotImplementedError: fancy indexing not supported
Apply node that caused the error: GpuAdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}(GpuFromHost<None>.0, GpuArrayConstant{1}, TensorConstant{0}, Subtensor{int64}.0)
Toposort index: 3
Inputs types: [GpuArrayType<None>(float32, matrix), GpuArrayType<None>(int8, scalar), TensorType(int64, scalar), TensorType(int64, vector)]
Inputs shapes: [(3, 3), (), (), (2,)]
Inputs strides: [(12, 4), (), (), (8,)]
Inputs values: ['not shown', gpuarray.array(1, dtype=int8), array(0), array([0, 2])]
Outputs clients: [[HostFromGpu(gpuarray)(GpuAdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by nouiz** [comment]
It was disable voluntarily, as there sometimes it slow down the computation! (transfer to CPU + CPU indexing + transfer to GPU sometimes faster then the new implementation...) Until we fix that, we prefer to don't have speed regression.

I'm investigating about the error, people should be able to manually enable it.

**Comment by nouiz** [comment]
IRL discussion with @abergeron about this. This code need updates including the problem your found. It seem the tests didn't always ran the GPU version, so we didn't found all the problems. see also: https://github.com/Theano/Theano/pull/6221 (that PR need the dev version of libgpuarray)

We won't have the time to fix all this for Theano 0.10, so for now, we keep it deactivated. If you have case where is work, you can always use if for now, but we don't know if all the problems give crash, so maybe you could also get wrong shape or wrong value.

**Comment by gvtulder** [comment]
Thanks. Keeping it deactivated for now seems fine. I ran into this while trying to get the tests for the boolean indexing to work (#6207).

**Comment by nouiz** [comment]
So we probably should use nonzero for bool indexing on GPU or not move it
to the GPU. I'm fine with both option.

**Comment by gvtulder** [comment]
Well, the advanced indexing part does work on the GPU, it's only the increment/set subtensor that's affected by this problem. `nonzero()` wouldn't make a difference, because you'd get the same error, as you can see in the example here. It's the implementation of GpuAdvancedIncSubtensor that's the problem, not the translation from boolean mask to indices.

I've disabled the GPU optimization for AdvancedBooleanIncSubtensor for now, I think that's a workable solution.
