### ISSUE TITLE
numpy.int64 not valid as input value for building Neural Network layer

### ISSUE THREAD

**Issue by stawo** [Theano/Theano#6291]
When adding an LSTM layer to my network, if I specify the number of nodes using a numpy.int64 variable, I get an exception.
Is this the desired behaviour?

In my case, I extract this number from a csv trhough a pandas dataframe, so the values are automatically imported as numpy types.
I use Theano 0.9.0, but I don't have the time to check the beta code (I'm working on a company project).

Way to reproduce the exception:
```
import numpy
from keras.models import Sequential
from keras.layers import LSTM
from keras.optimizers import Adam

model = Sequential()
model.add(LSTM(numpy.int64(2), input_shape=(1,3)))
```

Exception:
```
Traceback (most recent call last):
  File "c:/Users/x/Downloads/test.py", line 7, in <module>
    model.add(LSTM(numpy.int64(2), input_shape=(1,3)))
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\models.py", line 436, in add
    layer(x)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 262, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\engine\topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 309, in call
    initial_state = self.get_initial_state(inputs)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 249, in get_initial_state
    initial_state = K.tile(initial_state, [1, self.units])  # (samples, output_dim)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\backend\theano_backend.py", line 928, in tile
    y = T.tile(x, n)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\tensor\basic.py", line 5281, in tile
    raise ValueError("elements of reps must be scalars of integer dtype. {reps} {formatReps}".format(reps=reps, formatReps=[type(r) for r in reps]))
ValueError: elements of reps must be scalars of integer dtype. [1, 2] [<class 'int'>, <class 'numpy.int64'>]
```

Note: I modified the code in the file tensor/basic.py to display what type of values where passed to Theano, nothing more.

**Comment by nouiz** [comment]
I have tested this with the master and it is fixed.

Note, we keep the master of Theano pretty stable. Normally I don't hesitate to recomand it to people, but today we merged many big PR. If you need a quick work around, just pass a python int instead of a numpy.int64() number.

We are working on a Theano 0.10 release, so the fix should be available shortly.
