### ISSUE TITLE
Better handing of rpath

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#6322]
In https://github.com/Theano/Theano/pull/6305, we fix some problems by using rpath. But we don't use the same rpath handing as for cudnn. This isn't great. We should find one way to handle all rpath and make this consistent.

we could also add a method c_rpath() to the op interface.

**Comment by notoraptor** [comment]
I am configuring a fresh installation of Ubuntu (linux) and I got the error related to shared object loading when testing `dnn.version()`. As for CTC related-errors, compilation succeeds but runtime loading fails because `ImportError: ('The following error happened while compiling the node', DnnVersion(), '\n', 'libcudnn.so.7: cannot open shared object file: No such file or directory', '[DnnVersion()]')`.

And as for CTC, when I remove quotes around rpath in `DnnVersion.c_compile_args()`, the test succeeds. So I will make a complete PR to fix it, and to introduce `c_rpath()` if possible.

Error report:

```
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/theano$ nosetests -xvs theano/gpuarray/tests/test_dnn.py:test_version
Failure: ImportError (('The following error happened while compiling the node', DnnVersion(), '\n', 'libcudnn.so.7: cannot open shared object file: No such file or directory', '[DnnVersion()]')) ... ERROR

======================================================================
ERROR: Failure: ImportError (('The following error happened while compiling the node', DnnVersion(), '\n', 'libcudnn.so.7: cannot open shared object file: No such file or directory', '[DnnVersion()]'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/notoraptor/Programmes/anaconda3/envs/python2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/notoraptor/Programmes/anaconda3/envs/python2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/notoraptor/Programmes/anaconda3/envs/python2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, extra_ops, multinomial, reduction, rng_mrg, ctc
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/opt.py", line 2744, in <module>
    from .dnn import (local_abstractconv_cudnn,
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/dnn.py", line 326, in <module>
    handle_type = CUDNNDataType('cudnnHandle_t', 'cudnnDestroy')
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/dnn.py", line 243, in CUDNNDataType
    version=version(raises=False))
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/dnn.py", line 306, in version
    if not dnn_present():
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/dnn.py", line 196, in dnn_present
    dnn_present.avail, dnn_present.msg = _dnn_check_version()
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/dnn.py", line 167, in _dnn_check_version
    v = version()
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gpuarray/dnn.py", line 317, in version
    profile=False)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/compile/function_module.py", line 1842, in orig_function
    fn = m.create(defaults)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/compile/function_module.py", line 1716, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/vm.py", line 1084, in make_all
    impl=impl))
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/cmodule.py", line 2362, in compile_str
    return dlimport(lib_filename)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/gof/cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', DnnVersion(), '\n', 'libcudnn.so.7: cannot open shared object file: No such file or directory', '[DnnVersion()]')

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

My `.theanorc`:
```
[cuda]
root=/usr/local/cuda
[dnn]
base_path=/home/notoraptor/.local/cudnn/cuda
```

My `PATH`:
```
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/theano$ echo $PATH | sed 's/\:/\n/g' | sort -u
/bin
/home/notoraptor/Programmes/anaconda3/bin
/home/notoraptor/Programmes/anaconda3/envs/python2/bin
/home/notoraptor/Programmes/bin
/sbin
/snap/bin
/usr/bin
/usr/games
/usr/local/bin
/usr/local/games
/usr/local/sbin
/usr/sbin
```
My `CPATH`:
```
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/theano$ echo $CPATH | sed 's/\:/\n/g' | sort -u

/home/notoraptor/.local/include
```
My `LIBRARY_PATH`:
```
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/theano$ echo $LIBRARY_PATH | sed 's/\:/\n/g' | sort -u

/home/notoraptor/.local/lib
```
My `LD_LIBRARY_PATH`:
```
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/theano$ echo $LD_LIBRARY_PATH | sed 's/\:/\n/g' | sort -u

/home/notoraptor/.local/lib
```
Content of `/home/notoraptor/.local/include` and `/home/notoraptor/.local/lib`:
```
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/theano$ ls /home/notoraptor/.local/include/
gpuarray
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/theano$ ls /home/notoraptor/.local/lib/
libgpuarray.so  libgpuarray.so.2  libgpuarray.so.2.1  libgpuarray-static.a  python2.7
```

@nouiz @abergeron

**Comment by abergeron** [comment]
So this means that we should remove the quotes and just delete the windows portion since that uses PATH manipulation now.
