### ISSUE TITLE
Cannot load DLL

### ISSUE THREAD

**Issue by finarb** [Theano/Theano#6327]
1. Installed theano, pygpu from conda
2. Installed cuda8
3. Put the cudnn 5.1 files in the cuda installation
4. Created following system variables

A. THEANO_FLAGS_CPU =
floatX=float32,device=cpu

B.THEANO_FLAGS_GPU = 
floatX=float32,device=cuda0,dnn.enabled=False,gpuarray.preallocate=0.8,blas.ldflags=-LC:/deeplearning/OpenBLAS-v0.2.14-Win64-int32/bin-LC:/deeplearning/OpenBLAS-v0.2.14-Win64-int32/lib-lopenblas

C.THEANO_FLAGS_GPU_DNN=
floatX=float32,device=cuda0,optimizer_including=cudnn,gpuarray.preallocate=0.8,dnn.conv.algo_bwd_filter=deterministic,dnn.conv.algo_bwd_data=deterministic,dnn.include_path=C:/deeplearning/CUDA/v8.0/include,dnn.library_path=C:/deeplearning/CUDA/v8.0/lib/x64,,blas.ldflags=-LC:/deeplearning/OpenBLAS-v0.2.14-Win64-int32/bin-LC:/deeplearning/OpenBLAS-v0.2.14-Win64-int32/lib-lopenblas

Before running code I switch the theano flag environment variable depending on what I want to use

Both A and B work fine on the mnist_cnn.py and the cpu/gpu test code

_```
from theano import function, config, shared, tensor
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')
```_

But when I switch to C i.e. GPU DNN
and I write import theano

I am getting the following error

```
> ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
> Traceback (most recent call last):
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
>     use(config.device)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
>     init_dev(device)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gpuarray\__init__.py", line 66, in init_dev
>     avail = dnn.dnn_available(name)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gpuarray\dnn.py", line 174, in dnn_available
>     if not dnn_present():
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gpuarray\dnn.py", line 157, in dnn_present
>     dnn_present.avail, dnn_present.msg = _dnn_check_version()
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gpuarray\dnn.py", line 130, in _dnn_check_version
>     v = version()
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gpuarray\dnn.py", line 338, in version
>     profile=False)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\compile\function.py", line 326, in function
>     output_keys=output_keys)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
>     output_keys=output_keys)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\compile\function_module.py", line 1795, in orig_function
>     defaults)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\compile\function_module.py", line 1661, in create
>     input_storage=input_storage_lists, storage_map=storage_map)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
>     storage_map=storage_map)[:3]
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\vm.py", line 1047, in make_all
>     impl=impl))
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
>     no_recycling)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
>     output_storage=node_output_storage)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
>     keep_lock=keep_lock)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
>     keep_lock=keep_lock)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
>     key=key, lnk=self, keep_lock=keep_lock)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
>     module = lnk.compile_cmodule(location)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
>     preargs=preargs)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
>     return dlimport(lib_filename)
>   File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
>     rval = __import__(module_name, {}, {}, [module_name])
> ImportError: ('The following error happened while compiling the node', DnnVersion(), '\n', 'DLL load failed: The specified module could not be found.', '[DnnVersion()]')
```

Please help

**Comment by finarb** [comment]
ALso this is in Window 10, if that makes a difference

**Comment by Dateios** [comment]
@notoraptor I have the same problem. I add the folder to windows path. But it didn't work.

cuda8.0 cudnn64_6

**Comment by abergeron** [comment]
Some questions to be able to diagnose the issue:
 * Which version of Theano do you use?
 * What is the exact error message (copy and paste, including previous output)?
 * What is the exact content of your PATH variable?
