### ISSUE TITLE
Cannot use Theano GPU with cuDNN

### ISSUE THREAD

**Issue by dineshgit** [Theano/Theano#6328]
I'm not able to use Theano in GPU mode with cuDNN. Please help.
Below is the error I got from Command Prompt. I have placed all the 
necessary libraries/headers at the right folders in CUDA path.

dlwin36 is the environment created under Anaconda.
I'm training MNIST data.

(dlwin36) C:\Users\dines\Desktop>set THEANO_FLAGS=%THEANO_FLAGS_GPU_DNN%
(dlwin36) C:\Users\dines\Desktop>python mnist_cnn.py
Using Theano backend.
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'C:\\Users\\dines\\AppData\\Local\\Temp\\try_flags_f7vkrtdy.c:4:19: fatal error: cudnn.h: No such file or directory\r\ncompilation terminated.\r\n'
Preallocating 3276/4096 Mb (0.800000) on cuda0
Mapped name None to device cuda0: GeForce GTX 1050 (0000:01:00.0)
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Traceback (most recent call last):
  File "mnist_cnn.py", line 49, in <module>
    input_shape=input_shape))
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\keras\models.py", line 443, in add
    layer(x)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\keras\engine\topology.py", line 569, in __call__
    self.build(input_shapes[0])
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\keras\layers\convolutional.py", line 134, in build
    constraint=self.kernel_constraint)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\keras\legacy\interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\keras\engine\topology.py", line 391, in add_weight
    weight = K.variable(initializer(shape), dtype=dtype, name=name)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\keras\initializers.py", line 208, in __call__
    dtype=dtype, seed=self.seed)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\keras\backend\theano_backend.py", line 2123, in random_uniform
    return rng.uniform(shape, low=minval, high=maxval, dtype=dtype)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\sandbox\rng_mrg.py", line 1354, in uniform
    rstates = self.get_substream_rstates(nstreams, dtype)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\configparser.py", line 117, in res
    return f(*args, **kwargs)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\sandbox\rng_mrg.py", line 1256, in get_substream_rstates
    multMatVect(rval[0], A1p72, M1, A2p72, M2)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\sandbox\rng_mrg.py", line 66, in multMatVect
    [A_sym, s_sym, m_sym, A2_sym, s2_sym, m2_sym], o, profile=False)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\compile\function_module.py", line 1794, in orig_function
    output_keys=output_keys).create(
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\compile\function_module.py", line 1474, in __init__
    optimizer_profile = optimizer(fgraph)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\gof\opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Toolkits\Anaconda3-4.4.0\envs\dlwin36\lib\site-packages\theano\gpuarray\dnn.py", line 3081, in apply
    dnn_available.msg)
AssertionError: cuDNN optimization was enabled, but Theano was not able to use it for context None. We got this error:
cannot compile with cuDNN. We got this error:
b'C:\\Users\\dines\\AppData\\Local\\Temp\\try_flags_f7vkrtdy.c:4:19: fatal error: cudnn.h: No such file or directory\r\ncompilation terminated.\r\n'

**Comment by notoraptor** [comment]
@dineshgit What is the content of `THEANO_FLAGS_GPU_DNN` on your computer ?

> I have placed all the necessary libraries/headers at the right folders in CUDA path.

Where are cuDNN folders exactly ? Especially, where is `cudnn.h` file on your computer ?

**Comment by dineshgit** [comment]
@notoraptor I would like to close this issue because I solved the problem by reinstalling all the packages from scratch.
