### ISSUE TITLE
No ldflags and no fallback for [sd]gemv_ on Windows

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6365]
I have a compilation error on Theano when trying to test tensor corr operations on Windows 10 64 bits:

```

(python2) C:\Users\notoraptor\mila\dev\git\theano>nosetests -xvs theano\tensor\nnet\tests\test_corr.py
test_fwd (theano.tensor.nnet.tests.test_corr.Grouped_conv_noOptim) ...
You can find the C code in this temporary file: c:\users\notora~1\appdata\local\temp\theano_compilation_error_fkklco
ERROR

======================================================================
ERROR: test_fwd (theano.tensor.nnet.tests.test_corr.Grouped_conv_noOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\tensor\nnet\tests\test_abstract_conv.py", line 1491, in test_fwd
    mode=self.ref_mode)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\compile\function_module.py", line 1842, in orig_function
    fn = m.create(defaults)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\compile\function_module.py", line 1716, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\vm.py", line 1084, in make_all
    impl=impl))
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gof\cmodule.py", line 2353, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(img, Subtensor{::, ::, ::int64, ::int64}.0), '\n', "Compilation failed (return status=1): C:\\Users\\NOTORA~1\\AppData\\Local\\Temp\\ccxCBz0C.o: In function `corrMM(tagPyArrayObject*, tagPyArrayObject*, tagPyArrayObject*, int, int, int, int, int, int, int, int, int)':\r. C:/Users/notoraptor/AppData/Local/Theano/compiledir_Windows-10-10.0.15063-Intel64_Family_6_Model_158_Stepping_9_GenuineIntel-2.7.13-64/tmpzoeqsr/mod.cpp:1199: undefined reference to `dgemv_'\r. collect2.exe: error: ld returned 1 exit status\r. ", '[CorrMM{valid, (1, 1), (1, 1), 1 False}(img, <TensorType(float64, 4D)>)]')

----------------------------------------------------------------------
Ran 1 test in 1.956s

FAILED (errors=1)
```

Error message says:
```
undefined reference to `dgemv_'\r. collect2.exe: error: ld returned 1 exit status
```

When checking theano.config.blas.ldflags, this flag appeared to be empty:
```

(python2) C:\Users\notoraptor\mila\dev\git\theano>python
Python 2.7.13 |Continuum Analytics, Inc.| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import theano
>>> theano.config.blas.ldflags
''
```

Even if conda packages mkl, mkl-service and m2w64-openblas were installed.
```

(python2) C:\Users\notoraptor\mila\dev\git\theano>conda list
# packages in environment at C:\Users\notoraptor\data\programs\Anaconda3\envs\python2:
#
m2w64-openblas            0.2.19                        1

mkl                       2017.0.3                      0
mkl-service               1.1.2                    py27_3
```

So, it seems Theano cannot set ldflags on Windows even when BLAS libraries are installed. Other useful remarks:
- MKL packages seems to contains only DLL files, no `.lib` files. So, it seems quite impossible to link against MKL files.
- Theano currently provides a fallback for `[sd]gemm` when ldflags is empty, but not for `[sd]gemv_` as it was not used. But the new feature about unshared convolutions needs `[sd]gemv_` functions. So, maybe should we implement a fallback for these functions too.

@abergeron @nouiz @lamblin

**Comment by abergeron** [comment]
This is because MKL linking fails on windows.

I think we should add sgemv and dgemv to the fallback code, but I don't think there is anything we can do for mkl linking.

**Comment by nouiz** [comment]
The MKL linking problem was fixed by ContinuonIO some time ago when they did the 0.9 packages.

**Comment by nouiz** [comment]
See gh-5290 for when it was fixed in my memory.

**Comment by notoraptor** [comment]
@nouiz I assume the fix introduced by #5290 is here: https://github.com/Theano/Theano/blob/master/theano/configdefaults.py#L1361 . It checks if MKL can be imported, and if so, it adds MKL library path (which is python distribution lib path) to PATH system variable.

But this library path contains only DLLs (neither `.lib` nor `.a`), and we currently don't know how to link a DLL alone to a compiled file (using `-LPATH -llib` does not work; in fact, on Windows, we don't reach to this point: https://github.com/Theano/Theano/blob/master/theano/configdefaults.py#L1379 ).

This code:
```python
from __future__ import print_function, absolute_import, division
import mkl
import os
import sys
mkl_path = os.path.join(sys.prefix, 'Library', 'bin')
for sub_path in os.listdir(mkl_path):
	print(sub_path)
```
produces this output:
```
1033
cilkrts20.dll
ifdlg100.dll
libchkp.dll
libicaf.dll
libifcoremd.dll
libifcoremdd.dll
libifcorert.dll
libifcorertd.dll
libifportmd.dll
libimalloc.dll
libiomp5md.dll
libiompstubs5md.dll
libmmd.dll
libmmdd.dll
libmpx.dll
liboffload.dll
mkl_avx.dll
mkl_avx2.dll
mkl_avx512.dll
mkl_avx512_mic.dll
mkl_core.dll
mkl_def.dll
mkl_intel_thread.dll
mkl_mc.dll
mkl_mc3.dll
mkl_rt.dll
mkl_sequential.dll
mkl_tbb_thread.dll
mkl_vml_avx.dll
mkl_vml_avx2.dll
mkl_vml_avx512.dll
mkl_vml_avx512_mic.dll
mkl_vml_cmpt.dll
mkl_vml_def.dll
mkl_vml_mc.dll
mkl_vml_mc2.dll
mkl_vml_mc3.dll
msvcm90.dll
msvcp90.dll
msvcr90.dll
vcomp90.dll
```
Only DLL files.

**Comment by nouiz** [comment]
This comment seem to indicate it that it was working:

https://github.com/Theano/Theano/pull/5290#issuecomment-263367655

Or it mean it didn't crash, but maybe it wasn't using mkl?

**Comment by notoraptor** [comment]
It still works (`python -m theano.misc.check_blas > log-python2.log 2>&1`), but `blas.ldflags` is empty (I guess it means that it uses fallback [sd]gemm):
File `log-python2.log`:
```

        Some results that you can compare against. They were 10 executions
        of gemm in float64 with matrices of shape 2000x2000 (M=N=K=2000).
        All memory layout was in C order.

        CPU tested: Xeon E5345(2.33Ghz, 8M L2 cache, 1333Mhz FSB),
                    Xeon E5430(2.66Ghz, 12M L2 cache, 1333Mhz FSB),
                    Xeon E5450(3Ghz, 12M L2 cache, 1333Mhz FSB),
                    Xeon X5560(2.8Ghz, 12M L2 cache, hyper-threads?)
                    Core 2 E8500, Core i7 930(2.8Ghz, hyper-threads enabled),
                    Core i7 950(3.07GHz, hyper-threads enabled)
                    Xeon X5550(2.67GHz, 8M l2 cache?, hyper-threads enabled)


        Libraries tested:
            * numpy with ATLAS from distribution (FC9) package (1 thread)
            * manually compiled numpy and ATLAS with 2 threads
            * goto 1.26 with 1, 2, 4 and 8 threads
            * goto2 1.13 compiled with multiple threads enabled

                          Xeon   Xeon   Xeon  Core2 i7    i7     Xeon   Xeon
        lib/nb threads    E5345  E5430  E5450 E8500 930   950    X5560  X5550

        numpy 1.3.0 blas                                                775.92s
        numpy_FC9_atlas/1 39.2s  35.0s  30.7s 29.6s 21.5s 19.60s
        goto/1            18.7s  16.1s  14.2s 13.7s 16.1s 14.67s
        numpy_MAN_atlas/2 12.0s  11.6s  10.2s  9.2s  9.0s
        goto/2             9.5s   8.1s   7.1s  7.3s  8.1s  7.4s
        goto/4             4.9s   4.4s   3.7s  -     4.1s  3.8s
        goto/8             2.7s   2.4s   2.0s  -     4.1s  3.8s
        openblas/1                                        14.04s
        openblas/2                                         7.16s
        openblas/4                                         3.71s
        openblas/8                                         3.70s
        mkl 11.0.083/1            7.97s
        mkl 10.2.2.025/1                                         13.7s
        mkl 10.2.2.025/2                                          7.6s
        mkl 10.2.2.025/4                                          4.0s
        mkl 10.2.2.025/8                                          2.0s
        goto2 1.13/1                                                     14.37s
        goto2 1.13/2                                                      7.26s
        goto2 1.13/4                                                      3.70s
        goto2 1.13/8                                                      1.94s
        goto2 1.13/16                                                     3.16s

        Test time in float32. There were 10 executions of gemm in
        float32 with matrices of shape 5000x5000 (M=N=K=5000)
        All memory layout was in C order.


        cuda version      8.0    7.5    7.0
        gpu
        M40               0.45s  0.47s
        k80               0.92s  0.96s
        K6000/NOECC       0.71s         0.69s
        P6000/NOECC       0.25s

        Titan X (Pascal)  0.28s
        GTX Titan X       0.45s  0.45s  0.47s
        GTX Titan Black   0.66s  0.64s  0.64s
        GTX 1080          0.35s
        GTX 980 Ti               0.41s
        GTX 970                  0.66s
        GTX 680                         1.57s
        GTX 750 Ti               2.01s  2.01s
        GTX 750                  2.46s  2.37s
        GTX 660                  2.32s  2.32s
        GTX 580                  2.42s
        GTX 480                  2.87s
        TX1                             7.6s (float32 storage and computation)
        GT 610                          33.5s
        
Some Theano flags:
checked?
no...
    blas.ldflags= 
    compiledir= C:\Users\notoraptor\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-Intel64_Family_6_Model_158_Stepping_9_GenuineIntel-2.7.13-64
    floatX= float64
    device= cpu
Some OS information:
    sys.platform= win32
    sys.version= 2.7.13 |Continuum Analytics, Inc.| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)]
    sys.prefix= C:\Users\notoraptor\data\programs\Anaconda3\envs\python2
Some environment variables:
    MKL_NUM_THREADS= None
    OMP_NUM_THREADS= None
    GOTO_NUM_THREADS= None

Numpy config: (used when the Theano flag "blas.ldflags" is empty)
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/notoraptor/data/programs/Anaconda3/envs/python2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/notoraptor/data/programs/Anaconda3/envs/python2\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/notoraptor/data/programs/Anaconda3/envs/python2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/notoraptor/data/programs/Anaconda3/envs/python2\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/notoraptor/data/programs/Anaconda3/envs/python2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/notoraptor/data/programs/Anaconda3/envs/python2\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/notoraptor/data/programs/Anaconda3/envs/python2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/notoraptor/data/programs/Anaconda3/envs/python2\\Library\\include']
Numpy dot module: numpy.core.multiarray
Numpy location: C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\lib\site-packages\numpy\__init__.pyc
Numpy version: 1.13.1

We executed 10 calls to gemm with a and b matrices of shapes (5000, 5000) and (5000, 5000).

Total execution time: 20.22s on CPU (with direct Theano binding to blas).

Try to run this script a few times. Experience shows that the first time is not as fast as followings calls. The difference is not big, but consistent.
```

**Comment by nouiz** [comment]
ok, so your PR is the good short term fix. Ideally, if we can make Theano link directly to MKL on windows, it would be great. We should bring this to ContinuumIO when we tell them about the new release.

**Comment by notoraptor** [comment]
It seems we can link against DLL on Windows. It is told to be possible: https://cygwin.com/cygwin-ug-net/dll.html

And I think I have fixed it: https://github.com/Theano/Theano/pull/6367/commits/f086ca178345bd89f61c26293d7a572ef9b04d39 (in PR #6367 )

@abergeron @nouiz
