### ISSUE TITLE
Failed attempt at making an Op

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6378]
So I was trying to make some custom Ops and in order to understand it better I've decided to try to make an Op for automatic gradient of parameters of discrete distribution using the score function. Here is my attempt for bernoulli:
```
class StochasticBernoulli(theano.Op):
    __props__ = ('pass_gradient', 'stream')

    def __init__(self, pass_gradient=True, stream=None):
        self.pass_gradient = pass_gradient
        self.stream = stream if stream is not None else MRG_RandomStreams(213)
        assert isinstance(self.stream, (MRG_RandomStreams, RandomStreams))

    def make_node(self, p_logits, n=1):
        p_logits = T.as_tensor_variable(p_logits)
        n = T.as_tensor_variable(n)
        assert n.ndim == 0
        if isinstance(n, T.Constant) and n.value == 1:
            broadcast = p_logits.broadcastable
        else:
            broadcast = (False, ) + p_logits.broadcastable
        sample_type = T.TensorType(dtype=theano.config.floatX, broadcastable=broadcast)
        out_type = T.TensorType(dtype="int8", broadcastable=broadcast)
        return T.Apply(self, [p_logits, n], [sample_type(), out_type()])

    def perform(self, node, inputs, output_storage, params=None):
        p_logits, n = inputs
        p = T.nnet.sigmoid(p_logits)
        sample = output_storage[0]
        z = output_storage[1]
        if n.item() == 1:
            shape = tuple(p_logits.shape[i] for i in range(p_logits.ndim))
        else:
            shape = (n, ) + tuple(p_logits.shape[i] for i in range(p_logits.ndim))
            pattern = ('x', ) + tuple(range(p_logits.ndim))
            p = p.dimshuffle(*pattern)
        sample[0] = self.stream.uniform(size=shape)
        z[0] = T.gt(p, sample[0])

    def L_op(self, inputs, outputs, output_grads):
        p_logits, n = inputs
        samples = outputs[0]
        p = T.nnet.sigmoid(p_logits)
        if samples.ndim > p_logits.ndim:
            pattern = ('x',) + tuple(range(p_logits.ndim))
            p = p.dimshuffle(*pattern)
        if self.pass_gradient:
            grad = - T.Lop(T.nnet.binary_crossentropy(p, samples),
                           p_logits, output_grads[0], consider_constant=[samples])
            return [grad, T.DisconnectedType()()]
        else:
            return [T.DisconnectedType()(), T.DisconnectedType()()]


if __name__ == '__main__':
    a = theano.shared(np.random.rand(5, 3).astype(theano.config.floatX))
    b = StochasticBernoulli()(a)
    s = T.sum(b)
    c = T.grad(s, a)
    print(c.eval())
```
The code however gives some quite strange error, which I do not understand where it is comming from:
```
/usr/local/lib/python3.4/dist-packages/theano/gradient.py:1254: UserWarning: StochasticBernoulli{pass_gradient=True, stream=<theano.sandbox.rng_mrg.MRG_RandomStreams object at 0x7f021ae75dd8>}.grad returned DisconnectedType for input 1. You may want to implement a connection_pattern method for it.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
TypeError: Number of dimensions lower than expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/work/python/Lasagne/examples/sotc.py", line 76, in <module>
    print(c.eval())
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/graph.py", line 519, in eval
    rval = self._fn_cache[inputs](*args)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/link.py", line 156, in raise_with_op
    if getattr(ipt[0], "size", -1) <= 5:
  File "/usr/local/lib/python3.4/dist-packages/theano/tensor/var.py", line 91, in __bool__
    "Variables do not support boolean operations."
TypeError: Variables do not support boolean operations.
```
Any ideas on what I'm doing wrong?

**Comment by gvtulder** [comment]
The main problem is probably that you're using Theano functions and variables in your `perform` function. The `inputs` given to `perform` are NumPy arrays, and the outputs it writes to `output_storage` should be NumPy arrays as well. Your `perform` is creating Theano variables (with `T.nnet.sigmoid`, `stream.uniform`, `dimshuffle` etc.) and stores those as the output, but that won't work. You'll have to convert `perform` to a pure NumPy implementation that does what you want.

For example:
```python
import numpy as np
import theano
import theano.tensor as T
from theano.tensor.shared_randomstreams import RandomStreams
from theano.sandbox.rng_mrg import MRG_RandomStreams

class StochasticBernoulli(theano.Op):
    __props__ = ('pass_gradient', 'stream')

    def __init__(self, pass_gradient=True, stream=None):
        self.pass_gradient = pass_gradient
        self.stream = stream if stream is not None else MRG_RandomStreams(213)
        assert isinstance(self.stream, (MRG_RandomStreams, RandomStreams))
    
    def make_node(self, p_logits, n=1):
        p_logits = T.as_tensor_variable(p_logits)
        if n == 1:
            broadcast = p_logits.broadcastable
            shape = p_logits.shape
        else:
            broadcast = (False, ) + p_logits.broadcastable
            shape = (n, ) + tuple(p_logits.shape[i] for i in range(p_logits.ndim))
        sample = self.stream.uniform(size=shape) 
        out_type = T.TensorType(dtype="int8", broadcastable=broadcast)
        return T.Apply(self, [p_logits, sample], [sample.type(), out_type()])

    def perform(self, node, inputs, output_storage, params=None):
        p_logits, sample = inputs
        p = 1 / (1 + np.exp(p_logits))
        if p_logits.ndim < sample.ndim:
            p = p[np.newaxis, ...]
        output_storage[0][0] = sample
        output_storage[1][0] = p > sample


if __name__ == '__main__':
    a = theano.shared(np.random.rand(5, 3).astype(theano.config.floatX))
    b = StochasticBernoulli()(a)
    f = theano.function([], b)
    print(f())
    print(f())
```

**Comment by botev** [comment]
Hmm, however, I wanted basically to make an Op that has a different gradient, however, its computation is still Theano optimized. Maybe I should use `OpFromGraph` instead then. Does the computation of `OpFromGraph` get optimized as well?

**Comment by gvtulder** [comment]
You could remove the `perform` and add an optimisation that replaces the `StochasticBernoulli` op with the Theano implementation. (Have a look at the [optimisations for the abstract batchnorm ops](https://github.com/Theano/Theano/blob/47ac5f998af8b51ca7ad328c20c91beb03c5c6f2/theano/tensor/nnet/bn.py#L679) for example.) You would basically do in the optimisation what you now tried to do in `perform`.

I've never used `OpFromGraph`, but the documentation seems to suggest that its main purpose is to keep the subset-graph separate from the main graph. That's probably not what you want here. Doing  it in an optimisation would add your implementation to the main graph, so that it can be optimised together with everything else.

**Comment by nouiz** [comment]
OpFromGraph is the right tool for this case. There is the use case you describe, but there is a new one that is the one needed here.

Mostly, with the parameter inline=True, the OpFromGraph will get flattened in the orignal graph. This combined with override_grad() would do the equivalent of the abstract op + opt to inline it without the need for an optimization.

Closing, as I'm pretty sure of my answer, but if that don't work, don't hesitate to reopen it and add more information.

**Comment by botev** [comment]
@nouiz The last question on this is there any equivalent to `OpFromGraph` where we override the Lop rather than `grad` or smth like that (I just want to use the outputs of the op rather than recalculate them)?

**Comment by nouiz** [comment]
This is in a PR: https://github.com/Theano/Theano/pull/5641

No time to review/finish it for the 0.10 release, but you can probably use
it directly or rebase it and use it.
