### ISSUE TITLE
CTC failes with omp_get_num_threads’ was not declared in this scope.

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6399]
The following code:
```
import theano
import theano.tensor as T
from theano.tensor.nnet.ctc import ctc
a = T.ftensor3()
b = T.imatrix()
c = T.ivector()
s = ctc(a,b,c)
f = theano.function([a,b,c], s)
```
Fails with the following error:
```
You can find the C code in this temporary file: /tmp/theano_compilation_error_nfqys_ne
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/hdd/work/python/Theano/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/media/hdd/work/python/Theano/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/media/hdd/work/python/Theano/theano/compile/function_module.py", line 1842, in orig_function
    fn = m.create(defaults)
  File "/media/hdd/work/python/Theano/theano/compile/function_module.py", line 1716, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/media/hdd/work/python/Theano/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/media/hdd/work/python/Theano/theano/gof/vm.py", line 1084, in make_all
    impl=impl))
  File "/media/hdd/work/python/Theano/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/media/hdd/work/python/Theano/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/media/hdd/work/python/Theano/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/media/hdd/work/python/Theano/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/media/hdd/work/python/Theano/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/media/hdd/work/python/Theano/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/media/hdd/work/python/Theano/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/media/hdd/work/python/Theano/theano/gof/cmodule.py", line 2353, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', ConnectionistTemporalClassification{compute_grad=False}(CpuContiguous.0, <TensorType(int32, matrix)>, <TensorType(int32, vector)>), '\n', 'Compilation failed (return status=1): /home/alex/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-3.6.1-64/tmpks6lrpro/mod.cpp: In function ‘void ctc_context_init(ctc_context_t*)’:. /home/alex/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-3.6.1-64/tmpks6lrpro/mod.cpp:27:48: error: ‘omp_get_num_threads’ was not declared in this scope.      options->num_threads = omp_get_num_threads();.                                                 ^. ', '[ConnectionistTemporalClassification{compute_grad=False}(<TensorType(float32, 3D)>, <TensorType(int32, matrix)>, <TensorType(int32, vector)>)]')
```
The cloned `warp-ctc` directory contains a single build folder where the build of the library is done. In `.theanorc` I have:
```
[ctc]
root = /home/alex/work/python/warp-ctc
```
e.g. the library is `/home/alex/work/python/warp-ctc/build/libwarpctc.so`.
Also running the `test_cpu` of `wrap-ctc` passes all the tests (I'm currently trying to run this on a CPU in Theano as well).

**Comment by botev** [comment]
@joaovictortr Would you have any idea by any chance?

**Comment by nouiz** [comment]
I think your c++ compiler that Theano use don't support openmp. I suppose this case wasn't tested.
Which compiler do you have?

**Comment by nouiz** [comment]
Closed, the problem was his Theano flag. To enable openmp, you should not put it in the cxx.flags, but use Theano flag openmp=True
