### ISSUE TITLE
Incorrect MissingArgument error

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6402]
So in Lasagne I did the following:
```
adv_samples = theano.shared(mnist.data[partition][0][adv_index], name="adv_samples")
output = L.get_output(dense_layers[-1],
                          batch_norm_use_averages=True,
                          batch_norm_update_averages=False)
theano.printing.debugprint(output)
output = L.get_output(dense_layers[-1], inputs=adv_samples,
                          batch_norm_use_averages=True,
                          batch_norm_update_averages=False)
theano.printing.debugprint(output)
# output = theano.clone(output, replace={in_l.input_var: adv_samples})
s = theano.function([], output)
```
The thing is I still get an error:
```
Traceback (most recent call last):
  File "/home/alex/work/python/LaplaceNets/scripts/res_net_sfgs.py", line 225, in <module>
    main(**vars(parser.parse_args()))
  File "/home/alex/work/python/LaplaceNets/scripts/res_net_sfgs.py", line 138, in main
    s = theano.function([], output)
  File "/home/alex/work/python/Theano/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/alex/work/python/Theano/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/alex/work/python/Theano/theano/compile/function_module.py", line 1840, in orig_function
    name=name)
  File "/home/alex/work/python/Theano/theano/compile/function_module.py", line 1488, in __init__
    accept_inplace)
  File "/home/alex/work/python/Theano/theano/compile/function_module.py", line 181, in std_fgraph
    update_mapping=update_mapping)
  File "/home/alex/work/python/Theano/theano/gof/fg.py", line 175, in __init__
    self.__import_r__(output, reason="init")
  File "/home/alex/work/python/Theano/theano/gof/fg.py", line 346, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/home/alex/work/python/Theano/theano/gof/fg.py", line 391, in __import__
    raise MissingInputError(error_msg, variable=r)
theano.gof.fg.MissingInputError: Input 0 of the graph (indices start from 0), used to compute Reshape{4}(x.input, TensorConstant{[-1  3 32 32]}), was not provided and not given a value. Use the Theano flag exception_verbosity='high', for more information on this error.
 
Backtrace when that variable is created:

  File "/home/alex/work/python/LaplaceNets/scripts/res_net_sfgs.py", line 225, in <module>
    main(**vars(parser.parse_args()))
  File "/home/alex/work/python/LaplaceNets/scripts/res_net_sfgs.py", line 65, in main
    invars, loss_layer, dense_layers = laplace_nets.util.load_model(paramfile, flattened_input=True, **model_args)
  File "/home/alex/work/python/LaplaceNets/laplace_nets/util.py", line 17, in load_model
    iv, ll, dl = model_zoo.build_model(**kwargs)
  File "/home/alex/work/python/LaplaceNets/laplace_nets/model_zoo.py", line 21, in build_model
    return build_wide_resnet(**kwargs)
  File "/home/alex/work/python/LaplaceNets/laplace_nets/model_zoo.py", line 150, in build_wide_resnet
    il = L.InputLayer((None, h*w*c), name="x")
  File "/home/alex/work/python/Lasagne/lasagne/layers/input.py", line 61, in __init__
    input_var = input_var_type(var_name)
```
Which obviously is totally wrong as in the second case I'm replacing the variable. I've also printed the graphs and the name of the variable is `x.input` and it does not appear anywhere in the second graph.

**Comment by nouiz** [comment]
Can you give me code that allow me to reproduce this? The code snipet isn't enough.

**Comment by botev** [comment]
So there is some issue with the default updates I think. The layer is:
```
class BatchNormTheanoLayer(L.Layer):
    def __init__(self, incoming, axes='auto', epsilon=1e-4, alpha=0.1,
                 beta=init.Constant(0), gamma=init.Constant(1),
                 mean=init.Constant(0), inv_std=init.Constant(1), **kwargs):
        super(BatchNormTheanoLayer, self).__init__(incoming, **kwargs)
        ndim = len(self.input_shape)
        if axes in ('auto', 'spatial'):
            axes = (0,) + tuple(range(2, ndim))
        elif axes == 'per-activation':
            axes = (0,)
        elif isinstance(axes, (tuple, list, np.ndarray)):
            axes = tuple(int(a) for a in axes)
        else:
            raise ValueError('invalid axes: %s', str(axes))
        axes = tuple(sorted(axes))
        if len(axes) == 0:
            raise ValueError('there should be at least one normalization axis')
        if min(axes) < 0 or max(axes) >= ndim:
            raise ValueError('axes should be less than ndim (<%d), but %s given' % (ndim, str(axes)))
        self.axes = axes
        self.epsilon = epsilon
        self.alpha = alpha

        # create parameters, ignoring all dimensions in axes
        shape = utils.get_shape_except_axes(self.input_shape, axes)
        if beta is None:
            self.beta = None
        else:
            self.beta = self.add_param(beta, shape, 'beta',
                                       trainable=True, regularizable=False)
        if gamma is None:
            self.gamma = None
        else:
            self.gamma = self.add_param(gamma, shape, 'gamma',
                                        trainable=True, regularizable=True)
        self.mean = self.add_param(mean, shape, 'mean',
                                   trainable=False, regularizable=False)
        self.var = self.add_param(inv_std, shape, 'var',
                                  trainable=False, regularizable=False)

    def get_outputs_for(self, inputs, deterministic=False,
                        batch_norm_use_averages=None,
                        batch_norm_update_averages=None, **kwargs):
        x = inputs[0]

        # Decide whether to use the stored averages or mini-batch statistics
        if batch_norm_use_averages is None:
            batch_norm_use_averages = deterministic
        use_averages = batch_norm_use_averages

        # Decide whether to update the stored averages
        if batch_norm_update_averages is None:
            batch_norm_update_averages = not deterministic
        update_averages = batch_norm_update_averages

        gamma = 1 if self.gamma is None else self.gamma
        beta = 0 if self.beta is None else self.beta
        if use_averages:
            bn = T.nnet.bn.batch_normalization_test
            out = bn(x, gamma, beta,
                     self.mean, self.var,
                     self.axes, self.epsilon)
        elif update_averages:
            bn = T.nnet.bn.batch_normalization_train
            # Trick: To update the stored statistics, we create memory-aliased
            # clones of the stored statistics:
            out, _, _, new_mean, new_var = bn(x, gamma, beta, self.axes,
                                              self.epsilon, self.alpha,
                                              self.mean, self.var)
            # set a default update for them:
            self.mean.default_update = new_mean
            self.var.default_update = new_var
            # and make sure they end up in the graph without participating in
            # the computation (this way their default_update will be collected
            # and applied, but the computation will be optimized away):
            pattern = ['x' for _ in range(out.ndim)]
            c = 0
            for i in range(out.ndim):
                if i not in self.axes:
                    pattern[i] = c
                    c += 1
            out += 0 * self.mean.dimshuffle(*pattern)
            out += 0 * self.var.dimshuffle(*pattern)
        else:
            bn = T.nnet.bn.batch_normalization_train
            out, _, _, _, _ = bn(x, gamma, beta, self.axes,
                                 self.epsilon, self.alpha)

        return out
```
The code than is:
```
def build_wide_resnet(h, w, c, n_classes, n=3, k=2, dropout=True, flattened_input=False, **kwargs):
    if flattened_input:
        il = L.InputLayer((None, h*w*c), name="x")
        layer = L.ReshapeLayer(il, (-1, c, h, w))
    else:
        il = L.InputLayer((None, c, h, w), name="x")
        layer = il
    
    layer = L.Conv2DLayer(il, 128, (3, 3), stride=(1, 1), pad="same", name="conv")
    layer = BatchNormTheanoLayer(layer, name="bn")
    layer = L.DenseLayer(layer, num_units=100, name="last")
    return il.input_var, layer

# CIFAR 100
x_in, layer = build_wide_resnet(32, 32, 3, 100, n=3, k=8)

adv_samples = theano.shared(np.random.rand(79, 3, 32, 32).astype(theano.config.floatX), 
                            name="adv_samples")
```
Then the final code (note the comment):
```
# If this lines is commented it works
output1 = L.get_output(layer)
output2 = L.get_output(layer, inputs=adv_samples, 
                       batch_norm_use_averages=True, 
                      batch_norm_update_averages=False)
s = theano.function([], output2)
```
Gvies you back the error.

**Comment by Sentient07** [comment]
I think the missing input error is because you're asking Lasagne to create the input variable to the `InputLayer`. In the toy example that I created (without your `BatchNorm` Layer), I was able to rectify with the following correction 
```s = theano.function([il.input_var], output2)```

Also, in the Layer that you're creating, it is `get_output_for` and not `get_outputs_for`. Hope it helps

**Comment by botev** [comment]
@Sentient07 If you only uncommnet the first line the code works. Also, the `output2` should not depend on the input given that you have `inputs=adv_samples`. The point is that the first line creates something that requires the input while it shouldn't.

**Comment by Sentient07** [comment]
Oh! I thought you meant that uncommenting that line is the problem (with the issue being getting output1 as the output). If I understand correctly, you mean, the code that follows gives error and the one that follows it doesn't ?

```
output1 = L.get_output(layer)
output2 = L.get_output(layer, inputs=adv_samples, 
                       batch_norm_use_averages=True, 
                      batch_norm_update_averages=False)
s = theano.function([], output2)
```

```
output2 = L.get_output(layer, inputs=adv_samples, 
                       batch_norm_use_averages=True, 
                      batch_norm_update_averages=False)
s = theano.function([], output2)
```

**Comment by botev** [comment]
Yes, to clear it up, from your two code snippets, I get the first one to break and the second one to work.
This to me suggests that the error is coming from the `default_update`. 

PS: Consequently, I've just found out the issue - it is the default updates which are made in the first call. As such calling `s = theano.function([], output2, no_default_updates=True)` solves the problem

**Comment by lamblin** [comment]
This seems to be yet another issue with clone / replace, I've updated #5483 to keep track of it.
