### ISSUE TITLE
pygpu is valid and new, but get "pygpu was configured but could not be imported or is too old"

### ISSUE THREAD

**Issue by csaftoiu** [Theano/Theano#6420]
See the following:
```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)
NoneType
>>> theano
<module 'theano' from '/usr/local/lib/python3.5/dist-packages/theano/__init__.py'>
>>> import pygpu
>>> pygpu.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pygpu' has no attribute 'version'
>>> pygpu.__version__
'0.7.2+12.g51b5e8a'
```

As you can see, pygpu can be imported and is not too old. This is on latest Theano development version.

Additional info: pygpu passes all but a few tests:
```
======================================================================
ERROR: test_create_from_previous (pygpu.tests.test_collectives.TestGpuCommCliqueId)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pygpu-0.7.2+12.g51b5e8a-py3.5-linux-x86_64.egg/pygpu/tests/test_collectives.py", line 40, in setUp
    self.cid = GpuCommCliqueId(context=ctx)
  File "pygpu/collectives.pyx", line 35, in pygpu.collectives.GpuCommCliqueId.__cinit__
  File "pygpu/collectives.pyx", line 303, in pygpu.collectives.comm_generate_id
pygpu.gpuarray.GpuArrayException: b'Could not load "libnccl.so": libnccl.so: cannot open shared object file: No such file or directory'

======================================================================
ERROR: test_create_from_string_id (pygpu.tests.test_collectives.TestGpuCommCliqueId)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pygpu-0.7.2+12.g51b5e8a-py3.5-linux-x86_64.egg/pygpu/tests/test_collectives.py", line 40, in setUp
    self.cid = GpuCommCliqueId(context=ctx)
  File "pygpu/collectives.pyx", line 35, in pygpu.collectives.GpuCommCliqueId.__cinit__
  File "pygpu/collectives.pyx", line 303, in pygpu.collectives.comm_generate_id
pygpu.gpuarray.GpuArrayException: b'Could not load "libnccl.so": libnccl.so: cannot open shared object file: No such file or directory'

======================================================================
ERROR: test_pickle (pygpu.tests.test_collectives.TestGpuCommCliqueId)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pygpu-0.7.2+12.g51b5e8a-py3.5-linux-x86_64.egg/pygpu/tests/test_collectives.py", line 40, in setUp
    self.cid = GpuCommCliqueId(context=ctx)
  File "pygpu/collectives.pyx", line 35, in pygpu.collectives.GpuCommCliqueId.__cinit__
  File "pygpu/collectives.pyx", line 303, in pygpu.collectives.comm_generate_id
pygpu.gpuarray.GpuArrayException: b'Could not load "libnccl.so": libnccl.so: cannot open shared object file: No such file or directory'

======================================================================
ERROR: test_richcmp (pygpu.tests.test_collectives.TestGpuCommCliqueId)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pygpu-0.7.2+12.g51b5e8a-py3.5-linux-x86_64.egg/pygpu/tests/test_collectives.py", line 40, in setUp
    self.cid = GpuCommCliqueId(context=ctx)
  File "pygpu/collectives.pyx", line 35, in pygpu.collectives.GpuCommCliqueId.__cinit__
  File "pygpu/collectives.pyx", line 303, in pygpu.collectives.comm_generate_id
pygpu.gpuarray.GpuArrayException: b'Could not load "libnccl.so": libnccl.so: cannot open shared object file: No such file or directory'

----------------------------------------------------------------------
Ran 7253 tests in 151.900s

FAILED (SKIP=7, errors=4)
csaftoiu@numberchomper:~$ 
```

**Comment by nouiz** [comment]
You can ignore the test_collectives error if you don't plan to do multi-GPU for data parallism. If you want that, you will need to install NCCL2 that is needed for that.

Your Theano is too old for your libgpuarray version. Update it to the dev version.

**Comment by csaftoiu** [comment]
Actually it was the latest Theano, but apparently it's a known bug. I installed stable version of Theano & the required version of libgpuarray and all good forn ow
