### ISSUE TITLE
WrongValue error after 2 consecutives cudnn conv gradinput on same data with TRUE_HALF_CONFIG

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6435]
While debugging errors related to #5932 , I think I get a strange behaviour with cudnn conv gradinput, algo deterministic and float16 precision. When I compute gradinput with same arrays twice, I get expected results twice (compared to CPU) with float32 and float64, but I get a WrongValue error in the second call with float16.

This is a script to reproduce the problem (it contains code extracted from #5932 to ease tests). Script can receive the dtype as argument (float16, float32 and float64). To quick check used arrays, it also prints a hash of tensors involved in computation.

Script: https://gist.github.com/notoraptor/f6f8cd0471c66a9de227ba85a1c47d21

Parameters used:
- inputs shape (2, 3, 300, 5)
- filters shape (2, 3, 40, 4)
- borders (1, 1)
- alpha 2
- beta -3

Output with float64:
```
$ python ../test_dnn_float16.py float64
Using cuDNN version 7002 on context None
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
deterministic float64 float64 ((2, 3, 300, 5), (2, 3, 40, 4), (1, 1), (1, 1), (1, 1), 'conv', 2, -3)
Hash inputs_val            : eec5f0862f89822d1cbc830a89d49c72a318e98d5d4deedf6837dcd6864b674a
Hash filters_val           : 73ebccff5f4a23da52130e436000461c7f90929532557d6f14560c9b469ad89e
Hash topgrad_val           : b6ea724a38cdf6e2e80fb7617c7d7e6140a1d30a14c67cba47a3bbd420dee375
Hash CPU res before scaling: 6724456cb9ddc84e5696d25225a60f24ddb30589b532b3b17b970566c5d1f5c3
Hash     res before scaling: a3a871976ac9df9d5be88d62232637b0b1d3b86b857653769ee8006e3fc8dab5
Hash CPU res after  scaling: c7b3b0aa1108102193a059477647088c17c96e0e26cd8fa2271673e368394c1b
Hash     res after  scaling: 2295eda58b24fbbfcf23fc58a5ded70aba22861e70e4d0ed98d48a2fb7d81233
CPU
[-0.007 -0.003  0.001 -0.003 -0.007] [-0.007 -0.003  0.001 -0.003 -0.007]
res
[-0.007 -0.003  0.001 -0.003 -0.007] [-0.007 -0.003  0.001 -0.003 -0.007]
Hash inputs_val            : eec5f0862f89822d1cbc830a89d49c72a318e98d5d4deedf6837dcd6864b674a
Hash filters_val           : 73ebccff5f4a23da52130e436000461c7f90929532557d6f14560c9b469ad89e
Hash topgrad_val           : b6ea724a38cdf6e2e80fb7617c7d7e6140a1d30a14c67cba47a3bbd420dee375
Hash CPU res before scaling: 6724456cb9ddc84e5696d25225a60f24ddb30589b532b3b17b970566c5d1f5c3
Hash     res before scaling: a3a871976ac9df9d5be88d62232637b0b1d3b86b857653769ee8006e3fc8dab5
Hash CPU res after  scaling: c7b3b0aa1108102193a059477647088c17c96e0e26cd8fa2271673e368394c1b
Hash     res after  scaling: 2295eda58b24fbbfcf23fc58a5ded70aba22861e70e4d0ed98d48a2fb7d81233
CPU
[-0.007 -0.003  0.001 -0.003 -0.007] [-0.007 -0.003  0.001 -0.003 -0.007]
res
[-0.007 -0.003  0.001 -0.003 -0.007] [-0.007 -0.003  0.001 -0.003 -0.007]
```
All involved arrays seems to produce the same hash in two consecutive calls, including the final compared arrays. Same with float32:
```
$ python ../test_dnn_float16.py float32
Using cuDNN version 7002 on context None
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
deterministic float32 float32 ((2, 3, 300, 5), (2, 3, 40, 4), (1, 1), (1, 1), (1, 1), 'conv', 2, -3)
Hash inputs_val            : a518f7a0714a3dbae64098dd20bffafe7e05930656f1af8c87f88890f6a38e6c
Hash filters_val           : 5b303e92bdf796b695727c933761789f03ebfde0d8f4dc483dcda9f67786430c
Hash topgrad_val           : 1638ed31f4b2a48af185ea85c1015f48100adaaba23a7b54415c24b1bfef9ec4
Hash CPU res before scaling: 98a8c169a9f6043797d091bf0e76ae9ba7c0826d0870f042d0da264637995fd5
Hash     res before scaling: 400ddfb76857e18460ad651e53de22feaea405af074eba61ea27f709ba3146b9
Hash CPU res after  scaling: 552f41fb940330ebbaafd9465424e17355bdb3c1cf3374adfe0591ca0d277cf3
Hash     res after  scaling: 660a8c3bec561eaee37a31317fab4937c2f3827a4a6a0953b568fd746483c900
CPU
[-0.007 -0.003  0.001 -0.003 -0.007] [-0.007 -0.003  0.001 -0.003 -0.007]
res
[-0.007 -0.003  0.001 -0.003 -0.007] [-0.007 -0.003  0.001 -0.003 -0.007]
Hash inputs_val            : a518f7a0714a3dbae64098dd20bffafe7e05930656f1af8c87f88890f6a38e6c
Hash filters_val           : 5b303e92bdf796b695727c933761789f03ebfde0d8f4dc483dcda9f67786430c
Hash topgrad_val           : 1638ed31f4b2a48af185ea85c1015f48100adaaba23a7b54415c24b1bfef9ec4
Hash CPU res before scaling: 98a8c169a9f6043797d091bf0e76ae9ba7c0826d0870f042d0da264637995fd5
Hash     res before scaling: 400ddfb76857e18460ad651e53de22feaea405af074eba61ea27f709ba3146b9
Hash CPU res after  scaling: 552f41fb940330ebbaafd9465424e17355bdb3c1cf3374adfe0591ca0d277cf3
Hash     res after  scaling: 660a8c3bec561eaee37a31317fab4937c2f3827a4a6a0953b568fd746483c900
CPU
[-0.007 -0.003  0.001 -0.003 -0.007] [-0.007 -0.003  0.001 -0.003 -0.007]
res
[-0.007 -0.003  0.001 -0.003 -0.007] [-0.007 -0.003  0.001 -0.003 -0.007]
```
But with **``float16``**, output array computed on GPU changes in the second call (while CPU reference array stays the same):
```
$ python ../test_dnn_float16.py float16
Using cuDNN version 7002 on context None
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
deterministic float16 float16 ((2, 3, 300, 5), (2, 3, 40, 4), (1, 1), (1, 1), (1, 1), 'conv', 2, -3)
Hash inputs_val            : 2d3275bf1be3df5e27db19356f00dc87b8819a2f1cafe1b7419062398c163aa9
Hash filters_val           : 6782d9a2294dab8874c3cbbb1eafca69e7cb38e5d036de527f954047a8b1ad1b
Hash topgrad_val           : 182655443c9f857d5a350d9bb06a0b279ef20c9584c1b8e1de01e8e80c20566a
Hash CPU res before scaling: f8b0e94958a7ef7e9216fc161dfc40a216c0506b0bf535627fead3f6c8020fa4
Hash     res before scaling: b3de5f947fe0bcdf3f597a2ab0291338d11958113f1c96f2e1b715db9d730436
Hash CPU res after  scaling: 18301966109c4cc2b3213098ebdf9f6d2ea69873c6b70bd4b3474d7841f78133
Hash     res after  scaling: 582e1ec74e7aa6b75566013c74e7b58e2fabdf591f1207bebbe4480413305bdc
CPU
[-0.00699414 -0.00299609  0.00100195 -0.00299609 -0.00699414] [-0.00699414 -0.00299609  0.00100195 -0.00299609 -0.00699414]
res
[-0.00699615 -0.00299072  0.0010128  -0.00299072 -0.00699615] [-0.00699615 -0.00299072  0.0010128  -0.00299072 -0.00699615]
Hash inputs_val            : 2d3275bf1be3df5e27db19356f00dc87b8819a2f1cafe1b7419062398c163aa9
Hash filters_val           : 6782d9a2294dab8874c3cbbb1eafca69e7cb38e5d036de527f954047a8b1ad1b
Hash topgrad_val           : 182655443c9f857d5a350d9bb06a0b279ef20c9584c1b8e1de01e8e80c20566a
Hash CPU res before scaling: f8b0e94958a7ef7e9216fc161dfc40a216c0506b0bf535627fead3f6c8020fa4
Hash     res before scaling: e1a8c025456b8a2e0814c2dba20329c6f1654b72544905318fe6acf8a20d2d99
Hash CPU res after  scaling: 18301966109c4cc2b3213098ebdf9f6d2ea69873c6b70bd4b3474d7841f78133
Hash     res after  scaling: 837c67680554b33bb92cfe4ff0670f299d568bf01571142b4cd5e98ad9b243c1
Traceback (most recent call last):
  File "../test_dnn_float16.py", line 153, in <module>
    run_conv_gradinput(algo, dtype, precision, parameters, allocator=np.ones)
  File "../test_dnn_float16.py", line 131, in run_conv_gradinput
    utt.assert_allclose(cpu_res, res, rtol=rtol, atol=atol)
  File "/mnt/00447B2C447B2396/Users/notoraptor/mila/dev/git/theano/theano/tests/unittest_tools.py", line 358, in assert_allclose
    raise WrongValue(expected, value, rtol, atol)
theano.tests.unittest_tools.WrongValue: WrongValue
           : shape, dtype, strides, min, max, n_inf, n_nan:
  Expected : (2, 3, 300, 5) float32 (18000, 6000, 20, 4) -0.00699414 0.304853 0 0 
  Value    : (2, 3, 300, 5) float16 (9000, 3000, 10, 2) -0.0069962 0.30371 0 0

...

  Max Abs Diff:  0.0972115
  Mean Abs Diff:  0.00536192
  Median Abs Diff:  0.000527099
  Std Abs Diff:  0.0137345
  Max Rel Diff:  0.415143
  Mean Rel Diff:  0.0326335
  Median Rel Diff:  0.00288658
  Std Rel Diff:  0.0830883

  rtol, atol: 0.05 0.05
```
Ran on Ubuntu 17.04 64 bits with cuDNN 7.0.2 and theano master branch.

Can anyone confirm the problem on another computer ?

@abergeron @nouiz @lamblin

**Comment by nouiz** [comment]
We did a bug report to NVIDIA.
