### ISSUE TITLE
import error: no attribute 'sgemv'

### ISSUE THREAD

**Issue by zzd1992** [Theano/Theano#6451]
I work on Ubuntu 14.04. I install theano via
```
sudo pip install theano
```
Everything looks well. 
```
  Downloading Theano-0.9.0.tar.gz (3.1MB)
    100% |████████████████████████████████| 3.1MB 477kB/s 
Requirement already satisfied: numpy>=1.9.1 in /usr/local/lib/python2.7/dist-packages (from theano)
Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python2.7/dist-packages (from theano)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from theano)
Installing collected packages: theano
  Running setup.py install for theano ... done
Successfully installed theano-0.9.0
```
However, when I run the following command
```
python -c "import theano"
```
Some error appears. Here is the traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 80, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/__init__.py", line 17, in <module>
    from theano.tensor import blas
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/blas.py", line 169, in <module>
    _blas_gemv_fns = {numpy.dtype('float32'): fblas.sgemv,
AttributeError: 'module' object has no attribute 'sgemv'
```
How to fix it?

**Comment by zzd1992** [comment]
@nouiz

**Comment by notoraptor** [comment]
Hi @zzd1992 , which version of scipy do you have ? Can you run the following commands ?
```bash
python -c "import scipy; print(scipy.__version__)"
python -c "import scipy.linalg.blas.fblas"
python -c "import scipy.linalg.blas; print(dir(scipy.linalg.blas))"
```

**Comment by zzd1992** [comment]
```
python -c "import scipy; print(scipy.__version__)"
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
```
```
python -c "import scipy.linalg.blas.fblas"
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named fblas
```

```
python -c "import scipy.linalg.blas; print(dir(scipy.linalg.blas))"
```
```
['__builtins__', '__doc__', '__file__', '__name__', '__package__']
```
The first two command are not OK. But I am sure the version of scipy>=0.14 because I install theano successfully.
 @notoraptor

**Comment by zzd1992** [comment]
Before installing theano, I install the latest version of keras. And scipy is installed automatically. Is the version of scipy too new for theano 0.9.0?

**Comment by notoraptor** [comment]
It's weird scipy can not print `__version__`.

I have scipy 0.19.1 too (with `__version__` correctly printed), and I have not that bug.

Could you try the following commands ?

```
python -c "import theano; print(theano.__path__)"
python -c "import scipy; print(scipy.__path__)"
```

**Comment by zzd1992** [comment]
I reinstall scipy via
```
sudo -H pip install scipy
```
And all bugs are fixed ( I can import theano successfully). Before I reinstall scipy, it was installed automatically when I install keras via pip. I don't know the difference, but anyway, the bugs are fixed now.
