### ISSUE TITLE
PYGPU(0.6.9) is too old - Could not initialize pygpu

### ISSUE THREAD

**Issue by wkolasa** [Theano/Theano#6497]
Hi,

I followed these instruction to install Theano: https://ankivil.com/installing-keras-theano-and-dependencies-on-windows-10/.  Everything was working great until I switch .theanorc config value to device = cuda.  At this point, when I ran the test .py, I received an error stting the pygpu 0.6.0 is too old.  How can I upgrade to 0.7.0?  Or instead, is there another way to go?  I've also tried version 0.6.8 and 0.6.2.    I'm running on Windows 10.   Thanks for any help.  Here is the run / error:

PS C:\program files\anaconda3> python cifar10_cnn.py
Using Theano backend.
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gpuarray\__init__.py", line 220, in <module>
    use(config.device)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gpuarray\__init__.py", line 207, in use
    init_dev(device, preallocate=preallocate)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gpuarray\__init__.py", line 68, in init_dev
    pygpu_version.fullversion)
ValueError: Your installed version of pygpu(0.6.9) is too old, please upgrade to 0.7.0 or later (but below 0.8.0)
x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples
Using real-time data augmentation.
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 966, in compile_args
    ret += x.c_compile_args(c_compiler)
TypeError: c_compile_args() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\tensor\blas.py", line 444, in _ldflags
    assert t0 == '-'
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cifar10_cnn.py", line 106, in <module>
    workers=4)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\models.py", line 1121, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\training.py", line 1926, in fit_generator
    self._make_train_function()
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\training.py", line 967, in _make_train_function
    **self._function_kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\backend\theano_backend.py", line 1231, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\backend\theano_backend.py", line 1217, in __init__
    **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\compile\function_module.py", line 1841, in orig_funct
ion
    fn = m.create(defaults)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\vm.py", line 1084, in make_all
    impl=impl))
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 1297, in cmodule_key
    compile_args=self.compile_args(),
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 968, in compile_args
    ret += x.c_compile_args()
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\tensor\nnet\corr.py", line 181, in c_compile_args
    compile_args = ldflags(libs=False, flags=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\tensor\blas.py", line 389, in ldflags
    include_dir=include_dir)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\gof\utils.py", line 257, in rval
    val = f(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\theano\tensor\blas.py", line 447, in _ldflags
    % (t, ldflags_str))
ValueError: ('The following error happened while compiling the node', CorrMM{half, (1, 1), (1, 1), 1 False}(InplaceDimSh
uffle{0,3,1,2}.0, Subtensor{::, ::, ::int64, ::int64}.0), '\n', 'invalid token "Files\\Anaconda3\\Library\\bin"" in ldfl
ags_str: "-L"C:\\Program Files\\Anaconda3\\Library\\bin" -lmkl_core -lmkl_intel_thread -lmkl_rt"')
PS C:\program files\anaconda3>

**Comment by nouiz** [comment]
Those are old instruction. You should try the current versoin here:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray
)

This will tell you how to clean up your OS and install the new version. I
would recommant that you install the dev/beta version like this:

conda install -c mila-udem -c mila-udem/label/pre theano pygpu

**Comment by wkolasa** [comment]
Hello Frédéric,

Thank you.  I’ve uninstalled everything and I’m installing the current version now.  I’ll let you know how it works.

Best Regards,
William

**Comment by wkolasa** [comment]
Hi,

When following the instructions to install for windows, I noticed the instructions are from 2014:  https://github.com/Theano/Theano/wiki/Windowsinstallation  Is there a newer version?

Thank you.
William

**Comment by nouiz** [comment]
Don't use that page. Use this page:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)

MOstly, uninstall most stuff, then install conda and do:

conda instal ... as wrote on the page I link to.

**Comment by wkolasa** [comment]
Do you recommend Python 3.5 or 3.6?

**Comment by nouiz** [comment]
I didn'T try 3.6, 3.5 is safer. But maybe it work and I just don't know.

**Comment by wkolasa** [comment]
I used 3.5 for safety.  Everything install. I tested Theano and received this error:

WARNING (theano.configdefaults):  g++ not available, if using conda:  ‘conda install m2w64-toolchain’
WARNING (theano.configdefaults):  g++ not detect ! Theano will be unable to execute optimized C-implementations…
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

I have the C:mingw64\bin in environment path before any tests.  I did follow the initial error message and I did install conda (m2w64-toolchain), which updated many things.  However, the issue is still present… the exact same error message.  I rebooted.  New powershell window.

**Comment by nouiz** [comment]
You followed very old instruction for Theano. Remove the mingw that those instruction asked to install. It probably cause conflict and follow those instruction:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)

**Comment by wkolasa** [comment]
Thank you very much, Frédéric.  I was able to get Theano working (it’s much faster than TensorFlow), but I still have mingw64 installed.  I’m going to take a look at the configuration and see if I can update.

Best Regards,
William

**Comment by nouiz** [comment]
If your configuration is working, you can keep it like that. We just don't support it. As it work, I'll close this issue.

**Comment by AnisIdowu1** [comment]
Please , In line with all the comments above, I want to ask if unstalling the softwares specified in the link only means removing from anaconda prompt or removing from the system? What have done so far is restalling anaconda python (3.5) and followed the instruction in the link but when I imported theano, it  cannot recognise cuDNN and to bye pass it , I have to use dnn.disabled. I will appreciate any help to fix this and ready to provide further information if needed. Thanks.
