### ISSUE TITLE
Volta, CUDA 9 and Cudnn 7

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6503]
What are the steps for trying to make Theano work with these (priority is just the Volta). We are specifically interested in this as AWS has launched its P3 instances. Currently, I'm not aware what is the glue code for this. Trying out of the box a Volta with cuda-8 and cudnn 7 (as Theano fails with cudnn 6 on Volta) pygpu fails with:
```
pygpu.gpuarray.GpuArrayException: (b'nvrtcCompileProgram: NVRTC_ERROR_INVALID_OPTION', 3)
``
The question is what is the work that needs to be done for integrating this?

**Comment by nouiz** [comment]
We have this working here.

Use Theano 1.0rc1 (some of the betas should work, but in the rc1, we speed
up a case). Use the latest version of libgpuarray.

You need to use at least cudnn 7.0.2. 7.0.1 will be super slow. You will
absolutly need cuda 9. I use 9.0.176. I don't know which version started to
work. If you use multi-gpu, you will need nccl 2.0.

If that don't work, compile libgpuarray from scratch manually but use
 "-DCMAKE_BUILD_TYPE=Debug" instead of "-DCMAKE_BUILD_TYPE=Release" as one
of cmake parameter. It will give more information about the error.

**Comment by botev** [comment]
Is there any specific nvidia driver that is needed?

**Comment by nouiz** [comment]
I use 384.81 on a server. I don't know all driver that support it. Look on
nvidia web site if the current driver support V100, if so, I suppose it
should work.

**Comment by botev** [comment]
So with the previous driver, it did not work on the Volta. I can also confirm that with driver 375.66 on P100 with CUDA 9.0 and cudnn 7.0.3  I get the same issue with gpuarray.

**Comment by nouiz** [comment]
libgpuarray 0.7.4 should work fine. The only change in the master is related to opencl.
Can you delete all your installed libgpuarray version and pygpu. Then recompile it with
 "-DCMAKE_BUILD_TYPE=Debug" instead of "-DCMAKE_BUILD_TYPE=Release" as one
of cmake parameter. It should give more information about the error.

**Comment by botev** [comment]
Some of the errors:
```
======================================================================
ERROR: pygpu.tests.test_basic.test_tril
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/tests/test_basic.py", line 15, in test_tril
    result = tril(ag, inplace=inplace)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/basic.py", line 63, in tril
    k = _generate_kernel(A.context, cols, upper)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/basic.py", line 26, in _generate_kernel
    k = GpuKernel(src, "extract_tri", spec, context=ctx)
  File "pygpu/gpuarray.pyx", line 2404, in pygpu.gpuarray.GpuKernel.__cinit__
  File "pygpu/gpuarray.pyx", line 446, in pygpu.gpuarray.kernel_init
pygpu.gpuarray.GpuArrayException: CUDA kernel compile failure ::
0001	
0002	    #include "cluda.h"
0003	    KERNEL void extract_tri(GLOBAL_MEM ga_float *a, ga_size a_off, ga_uint N) {
0004	        a = (GLOBAL_MEM ga_float *)(((GLOBAL_MEM char *)a) + a_off);
0005	        unsigned int idx = GID_1 * LDIM_0 * GDIM_0 +
0006	                           GID_0 * LDIM_0 + LID_0;
0007	        unsigned int ix = idx/5;
0008	        unsigned int iy = idx%5;
0009	        if (idx < N) {
0010	            if (ix < iy)
0011	                a[idx] = 0.0;
0012	        }
0013	    }
0014	    

Compile log:
NVRTC compile log::

Link info log::

Link error log::
ptxas application ptx input, line 9; fatal   : Unsupported .version 6.0; current version is '5.0'
ptxas fatal   : Ptx assembly aborted due to errors


======================================================================
ERROR: pygpu.tests.test_basic.test_triu
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/tests/test_basic.py", line 29, in test_triu
    result = triu(ag, inplace=inplace)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/basic.py", line 44, in triu
    k = _generate_kernel(A.context, cols, upper)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/basic.py", line 26, in _generate_kernel
    k = GpuKernel(src, "extract_tri", spec, context=ctx)
  File "pygpu/gpuarray.pyx", line 2404, in pygpu.gpuarray.GpuKernel.__cinit__
  File "pygpu/gpuarray.pyx", line 446, in pygpu.gpuarray.kernel_init
pygpu.gpuarray.GpuArrayException: CUDA kernel compile failure ::
0001	
0002	    #include "cluda.h"
0003	    KERNEL void extract_tri(GLOBAL_MEM ga_float *a, ga_size a_off, ga_uint N) {
0004	        a = (GLOBAL_MEM ga_float *)(((GLOBAL_MEM char *)a) + a_off);
0005	        unsigned int idx = GID_1 * LDIM_0 * GDIM_0 +
0006	                           GID_0 * LDIM_0 + LID_0;
0007	        unsigned int ix = idx/5;
0008	        unsigned int iy = idx%5;
0009	        if (idx < N) {
0010	            if (ix > iy)
0011	                a[idx] = 0.0;
0012	        }
0013	    }
0014	    

Compile log:
NVRTC compile log::

Link info log::

Link error log::
ptxas application ptx input, line 9; fatal   : Unsupported .version 6.0; current version is '5.0'
ptxas fatal   : Ptx assembly aborted due to errors
```
```
ERROR: pygpu.tests.test_blas.test_dot(1, 'float64', False, False, True, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/tests/support.py", line 44, in f
    func(*args, **kwargs)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/tests/test_blas.py", line 44, in dot
    gr = gblas.dot(gX, gY, gZ, overwrite_z=overwrite)
  File "pygpu/blas.pyx", line 79, in pygpu.blas.dot
  File "pygpu/blas.pyx", line 29, in pygpu.blas.pygpu_blas_rdot
pygpu.gpuarray.GpuArrayException: (b'cublasCreate: (cublas) Library not initialized.', 11)

======================================================================
ERROR: pygpu.tests.test_blas.test_dot(256, 'float32', True, True, True, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/tests/support.py", line 44, in f
    func(*args, **kwargs)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/tests/test_blas.py", line 31, in dot
    sliced=sliced, ctx=context)
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/.local/lib/python3.6/site-packages/pygpu-0.7.4+2.g6710220-py3.6-linux-x86_64.egg/pygpu/tests/support.py", line 166, in gen_gpuarray
    assert numpy.allclose(a, numpy.asarray(b)), (a, numpy.asarray(b))
  File "/jmain01/home/JAD002/dxt02/aab09-dxt02/miniconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "pygpu/gpuarray.pyx", line 1728, in pygpu.gpuarray.GpuArray.__array__
  File "pygpu/gpuarray.pyx", line 1389, in pygpu.gpuarray._pygpu_as_ndarray
  File "pygpu/gpuarray.pyx", line 711, in pygpu.gpuarray.pygpu_copy
  File "pygpu/gpuarray.pyx", line 406, in pygpu.gpuarray.array_copy
pygpu.gpuarray.GpuArrayException: b'cuLinkAddData: CUDA_ERROR_NO_BINARY_FOR_GPU: no kernel image is available for execution on the device'
```

**Comment by nouiz** [comment]
For Volta you absolutly need cuda 9 + a recent enough driver. With this error, I have the impression your environment is bad. Did you make sure the driver was reloaded(did you reboot) after installing the new driver? Does your environment mix cuda 8 and cuda 9? This is the part of the error that make me think that:

"
ptxas application ptx input, line 9; fatal   : Unsupported .version 6.0; current version is '5.0'
"

**Comment by botev** [comment]
So this on the P100 with the old driver 375.66 and cuda 9. On the Volta where I have the 384.41 it works fine.

**Comment by lamblin** [comment]
Maybe the driver is too old for cuda 9?

**Comment by botev** [comment]
That's what I also thought initially :D If that is the case feel free to close this.

**Comment by nouiz** [comment]
Can you update the driver to the newer that work with the V100? That driver should also work with P100 I think.

**Comment by lamblin** [comment]
According to various answers on the internet (https://askubuntu.com/questions/967332/how-can-i-install-cuda-9-on-ubuntu-17-10), and even an error message that seems to be in the CUDA installer (https://devtalk.nvidia.com/default/topic/1024915/install-cuda-9-on-ubuntu-16-04-with-the-runfile-and-pre-installed-drivers/):
> A driver of version at least 384.00 is required for CUDA 9.0 functionality to work.

So I'm going to close, please reopen if you still have the issue with 384.*.
