### ISSUE TITLE
Scan memory leak(?)

### ISSUE THREAD

**Issue by AlexeySorokin** [Theano/Theano#6516]
Using: Windows10+Miniconda Python 3.6+Theano 0.9.0

I am developing a neural network for text sequences using Theano as backend using as one of the layers the function transforming an array X of the shape (batch_size, T, d) to an array B of shape (batch_size, T, h, d) with B[s,i,j] = X[s,i-(h-1-j)], so B[s,i] = [B[s,i-h+1], ..., B[s,i]] which means B[s,i] stores the left context of length h for the i+1-th element of X.

I implement the transformation using **scan** filling each row of B[s] by a slice of X[s] (in this case there are T iterations) or filling each column by a shifted copy of X[s] (in this case there are h iterations). It happens that first approach goes out of memory even on small array of size 2*500*2 while the second works fine for much larger arrays. I suppose Theano to consume memory storing intermediate values of B for all T iterations though the documentation says it is clear enough to avoid it.

**Below is my code:**

```
    def make_history(X, h, pad):
    """
    A theano func transforming a 3D array X of shape r*m*d to a 4D array B of shape r*m*h*d,
    where B[s,i,j] = A[s,i-(h-1-j)] if j >= h-1-i abd  and B[s,i,j] = pad otherwise

    pad is either a 1D array (a single pad value)
    or a 2D matrix (a separate pad value for each element)
    """
    B = tT.repeat(kb.zeros_like(X)[:,:,None,:], h, axis=2)
    pad = pad[...,None,:] # adding timestep axis to pad
    m = X.shape[1]
    def _shifted_fill(b, i, a, h):
        start, row_start = tT.largest(i-(h-1), 0), tT.largest((h-1)-i, 0)
        r1 = tT.set_subtensor(b[:,i,:row_start], pad)
        b_new = tT.set_subtensor(r1[:,i,row_start:], a[:,start:i+1])
        return [b_new, i+1]
    results, updates = theano.scan(
        _shifted_fill, non_sequences=[X, h], outputs_info=[tT.zeros_like(B), 0], n_steps=m)
    return results[0][-1]


def make_history_1(X, h, pad):
    """
    A theano func transforming a 3D array X of shape r*m*d to a 4D array B of shape r*m*h*d,
    where B[s,i,j] = A[s,i-(h-1-j)] if j >= h-1-i abd  and B[s,i,j] = pad otherwise

    """
    B = tT.repeat(kb.zeros_like(X)[:,:,None,:], h, axis=2)
    pad = pad[...,None,:]
    m = X.shape[1]
    def _shifted_fill_vertical(b, d, a, h):
        r1 = tT.set_subtensor(b[:,:d,h-1-d], pad)
        b_new = tT.set_subtensor(r1[:,d:,h-1-d],a[:,:m-d])
        return [b_new, d-1]
    results, updates = theano.scan(
        _shifted_fill_vertical, non_sequences=[X, h], outputs_info=[B, h-1], n_steps=h)
    return results[0][-1]

def test_memory():
    a = tT.dtensor3()
    pad, right_pad = tT.dvector(), tT.dvector()
    # theano.config.scan.debug = True
    # print(theano.config.scan)
    b = make_history(a, 3, pad)
    c = make_history_1(a, 3, pad)
    f = theano.function([a, pad], [b], on_unused_input="ignore")
    g = theano.function([a, pad], [c], on_unused_input="ignore")
    T, d = 500, 2
    A = np.random.rand(2, T, d)
    B, C = np.ones(shape=(d,), dtype=float), np.zeros(shape=(d,), dtype=float)
    answer = f(A, B)[0]
    other = g(A, B)[0]
    print(np.max(np.fabs(answer-other)))`
```

**It produces:**

```
C:\Miniconda3\python.exe C:/Programming/packages/neural_LM/common.py
WARNING (theano.gof.cmodule): OPTIMIZATION WARNING: Theano was not able to find the g++ parameters that tune the compilation to your  specific CPU. This can slow down the execution of Theano functions. Please submit the following lines to Theano's mailing list so that we can fix this problem:

Using cuDNN version 5005 on context None
Mapped name None to device cuda: GeForce 940M (0000:04:00.0)
Using Theano backend.
Traceback (most recent call last):
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (C:\Users\\ufffd\ufffd\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.6.3-64\scan_perform\mod.cpp:4490)
RuntimeError: setarray failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "C:\Miniconda3\lib\site-packages\theano\scan_module\scan_op.py", line 989, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\Miniconda3\lib\site-packages\theano\scan_module\scan_op.py", line 978, in p
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform (C:\Users\\ufffd\ufffd\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.6.3-64\scan_perform\mod.cpp:4606)
  File "C:\Miniconda3\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Miniconda3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (C:\Users\\ufffd\ufffd\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.6.3-64\scan_perform\mod.cpp:4490)
RuntimeError: setarray failed
Apply node that caused the error: GpuIncSubtensor{Set;::, int8, int8::}(GpuIncSubtensor{Set;::, int8, :int8:}.0, GpuSubtensor{::, int8:int8:}.0, ScalarFromTensor.0, ScalarFromTensor.0)
Toposort index: 13
Inputs types: [GpuArrayType<None>(float64, (False, False, False, False)), GpuArrayType<None>(float64, (False, False, False)), Scalar(int8), Scalar(int8)]
Inputs shapes: [(2, 500, 3, 2), (2, 247, 2), (), ()]
Inputs strides: [(24000, 48, 16, 8), (8000, 16, 8), (), ()]
Inputs values: ['not shown', 'not shown', 127, 0]
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Programming/packages/neural_LM/common.py", line 183, in <module>
    test_memory()
  File "C:/Programming/packages/neural_LM/common.py", line 176, in test_memory
    answer = f(A, B)[0]
  File "C:\Miniconda3\lib\site-packages\theano\compile\function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Miniconda3\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Miniconda3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Miniconda3\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "C:\Miniconda3\lib\site-packages\theano\scan_module\scan_op.py", line 989, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\Miniconda3\lib\site-packages\theano\scan_module\scan_op.py", line 978, in p
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform (C:\Users\\ufffd\ufffd\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.6.3-64\scan_perform\mod.cpp:4606)
  File "C:\Miniconda3\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Miniconda3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (C:\Users\\ufffd\ufffd\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.6.3-64\scan_perform\mod.cpp:4490)
RuntimeError: setarray failed
Apply node that caused the error: GpuIncSubtensor{Set;::, int8, int8::}(GpuIncSubtensor{Set;::, int8, :int8:}.0, GpuSubtensor{::, int8:int8:}.0, ScalarFromTensor.0, ScalarFromTensor.0)
Toposort index: 13
Inputs types: [GpuArrayType<None>(float64, (False, False, False, False)), GpuArrayType<None>(float64, (False, False, False)), Scalar(int8), Scalar(int8)]
Inputs shapes: [(2, 500, 3, 2), (2, 247, 2), (), ()]
Inputs strides: [(24000, 48, 16, 8), (8000, 16, 8), (), ()]
Inputs values: ['not shown', 'not shown', 127, 0]
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: forall_inplace,cpu,scan_fn}(Elemwise{Maximum}[(0, 0)].0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuFromHost<None>.0, GpuFromHost<None>.0)
Toposort index: 20
Inputs types: [TensorType(int64, scalar), GpuArrayType<None>(float64, (False, False, False, False, False)), GpuArrayType<None>(int8, (True,)), GpuArrayType<None>(float64, (False, False, False)), GpuArrayType<None>(float64, (False,))]
Inputs shapes: [(), (2, 2, 500, 3, 2), (1,), (2, 500, 2), (2,)]
Inputs strides: [(), (48000, 24000, 48, 16, 8), (1,), (8000, 16, 8), (8,)]
Inputs values: [array(500, dtype=int64), 'not shown', gpuarray.array([127], dtype=int8), 'not shown', gpuarray.array([ 1.,  1.])]
Outputs clients: [[GpuSubtensor{int64}(forall_inplace,cpu,scan_fn}.0, ScalarFromTensor.0)], []]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

Process finished with exit code 1
```

**Comment by lamblin** [comment]
We have stopped maintaining the 0.9 version.
Can you please try with 1.0 and libgpuarray 0.7.5?
