### ISSUE TITLE
DLL Load failed

### ISSUE THREAD

**Issue by mustafasaaed** [Theano/Theano#6527]
whenever i try to run this code :

from theano import function, config, shared, tensor
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')

i get the following error

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "h.py", line 10, in <module>
    f = function([], tensor.exp(x))
  File "c:\Python34\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "c:\Python34\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "c:\Python34\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "c:\Python34\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "c:\Python34\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "c:\Python34\lib\site-packages\theano\gof\vm.py", line 1084, in make_all
    impl=impl))
  File "c:\Python34\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "c:\Python34\lib\site-packages\theano\gof\op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "c:\Python34\lib\site-packages\theano\gof\cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "c:\Python34\lib\site-packages\theano\gof\cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "c:\Python34\lib\site-packages\theano\gof\cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "c:\Python34\lib\site-packages\theano\gof\cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "c:\Python34\lib\site-packages\theano\gof\cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "c:\Python34\lib\site-packages\theano\gof\cmodule.py", line 2368, in compile_str
    return dlimport(lib_filename)
  File "c:\Python34\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: The specified module could not be found.

**Comment by notoraptor** [comment]
Hi ! Could you re-run your code with theano flag `cmodule.compilation_warning` set to `True` and post the entire output message ?
```
set THEANO_FLAGS=device=cuda,cmodule.compilation_warning=True
python your_script.py
```

Also, do you use any other theano flag ?

**Comment by mustafasaaed** [comment]
@notoraptor i am using AMD GPU not nvidia cards.

**Comment by notoraptor** [comment]
Ok, so could you use `opencl0:0` instead ?

```
set THEANO_FLAGS=device=opencl0:0,cmodule.compilation_warning=True
python your_script.py
```

**Comment by mustafasaaed** [comment]
here what i got : 
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
--- Logging error ---
Traceback (most recent call last):
  File "c:\Python34\lib\logging\__init__.py", line 978, in emit
    msg = self.format(record)
  File "c:\Python34\lib\logging\__init__.py", line 828, in format
    return fmt.format(record)
  File "c:\Python34\lib\logging\__init__.py", line 573, in format
    record.exc_text = self.formatException(record.exc_info)
  File "c:\Python34\lib\logging\__init__.py", line 523, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "c:\Python34\lib\traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "c:\Python34\lib\traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "c:\Python34\lib\traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
Call stack:
  File "h.py", line 1, in <module>
    from theano import function, config, shared, tensor
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "c:\Python34\lib\site-packages\theano\__init__.py", line 156, in <module>
    import theano.gpuarray
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "c:\Python34\lib\site-packages\theano\gpuarray\__init__.py", line 255, in <module>
    exc_info=True)
Message: 'pygpu was configured but could not be imported or is too old (version 0.7 or higher required)'
Arguments: ()
Traceback (most recent call last):
  File "h.py", line 10, in <module>
    f = function([], tensor.exp(x))
  File "c:\Python34\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "c:\Python34\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "c:\Python34\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "c:\Python34\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "c:\Python34\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "c:\Python34\lib\site-packages\theano\gof\vm.py", line 1084, in make_all
    impl=impl))
  File "c:\Python34\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "c:\Python34\lib\site-packages\theano\gof\op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "c:\Python34\lib\site-packages\theano\gof\cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "c:\Python34\lib\site-packages\theano\gof\cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "c:\Python34\lib\site-packages\theano\gof\cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "c:\Python34\lib\site-packages\theano\gof\cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "c:\Python34\lib\site-packages\theano\gof\cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "c:\Python34\lib\site-packages\theano\gof\cmodule.py", line 2368, in compile_str
    return dlimport(lib_filename)
  File "c:\Python34\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: The specified module could not be found.

**Comment by notoraptor** [comment]
Do you use the latest theano and pygpu versions ? Latest theano version is 1.0, latest pygpu version is 0.7.5 .

**Comment by nouiz** [comment]
OpenCL backend isn't in a usable state. As we stop developing Theano, we
won't finish it.
