### ISSUE TITLE
Optimization failure due to: local_reshape_dimshuffle

### ISSUE THREAD

**Issue by armaos** [Theano/Theano#6534]
hi all, I am encountering the error below.
I am using the pre-made Docker form [here](http://lasagne.readthedocs.io/en/latest/user/installation.html#docker). So i suspect that I have the latest bleeding-edge builds of Theano and Lasagne.

````
ERROR (theano.gof.opt): Optimization failure due to: local_reshape_dimshuffle
ERROR (theano.gof.opt): node: Reshape{2}(InplaceDimShuffle{0,x}.0, <TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2035, in process_node
    remove=remove)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/toolbox.py", line 569, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/toolbox.py", line 518, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 486, in replace
    ". The type of the replacement must be the same.", old, new)
BadOptimization: BadOptimization Error 
  Variable: id 140648242408208 Reshape{2}.0
  Op Reshape{2}(CGemv{no_inplace}.0, <TensorType(int64, vector)>)
  Value Type: <type 'NoneType'>
  Old Value:  None
  New Value:  None
  Reason:  local_reshape_dimshuffle. The type of the replacement must be the same.
  Old Graph:
  Reshape{2} [id A] <TensorType(float32, col)> ''   
   |InplaceDimShuffle{0,x} [id B] <TensorType(float32, col)> ''   
   | |CGemv{no_inplace} [id C] <TensorType(float32, vector)> ''   
   |   |AllocEmpty{dtype='float32'} [id D] <TensorType(float32, vector)> ''   
   |   | |Shape_i{1} [id E] <TensorType(int64, scalar)> ''   
   |   |   |LSTMAttention.AlignSeqOutputLayer: (aln) W_a_copy0 [id F] <TensorType(float32, matrix)>
   |   |TensorConstant{1.0} [id G] <TensorType(float32, scalar)>
   |   |Elemwise{tanh,no_inplace} [id H] <TensorType(float32, matrix)> ''   
   |   | |InplaceDimShuffle{1,0} [id I] <TensorType(float32, matrix)> ''   
   |   |   |Reshape{2} [id J] <TensorType(float32, matrix)> ''   
   |   |Reshape{1} [id K] <TensorType(float32, vector)> ''   
   |   | |Rebroadcast{?,?,0} [id L] <TensorType(float32, 3D)> ''   
   |   | | |InplaceDimShuffle{0,1,x} [id M] <TensorType(float32, (False, False, True))> ''   
   |   | |MakeVector{dtype='int64'} [id N] <TensorType(int64, vector)> ''   
   |   |   |Elemwise{switch,no_inplace} [id O] <TensorType(int64, scalar)> ''   
   |   |TensorConstant{0.0} [id P] <TensorType(float32, scalar)>
   |<TensorType(int64, vector)> [id Q] <TensorType(int64, vector)>

  New Graph:
  Reshape{2} [id R] <TensorType(float32, matrix)> ''   
   |CGemv{no_inplace} [id C] <TensorType(float32, vector)> ''   
   |<TensorType(int64, vector)> [id Q] <TensorType(int64, vector)>


Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
````

I already have : 
`tensor.cmp_sloppy=2`

and is the function dump that generates the error:
https://www.dropbox.com/s/vcgiicmwhtw8ei1/train_fun.pkl?dl=0

**Comment by nouiz** [comment]
There is two docker. The CPU one is 4 mounts old. If it is this one, I
think we fixed that in the master of Theano.

You don't need docker. You can use anaconda and it install easily Theano:
http://deeplearning.net/software/theano/install_ubuntu.html#requirements-installation-through-conda-recommended

This work for Mac, Linux and Windows.

**Comment by armaos** [comment]
Hi nuiz,
thanks for replying and helping. I am really struggling make that work without bugs. 
1) I was using the docker because I was running the network in multiple machines (and it was for me the easier solution) Anyway the docker version of theano is `'0.10.0dev1.dev-2c6adcccaefb3aa466be76f403bcc4981d023a6a'` so its newer than the 0.9 that comes with the conda, right? 

2)Then in tried in a clean enviroment, with dependencies and theano installed through conda:
`conda create --name envCondaExcl  numpy scipy mkl nose sphinx pydot-ng theano pygpu IPython`

theano version in this case:
`'0.9.0.dev-425cb8effc7958e8ca376b023d8344b7620a9622'`

and lasagne Bleeding-edge

and the error changed to 

```

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{2}.0, Reshape{2}.0, TensorType(float32, col), TensorType(float32, matrix), 'local_reshape_dimshuffle') local_reshape_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_reshape_dimshuffle
ERROR (theano.gof.opt): node: Reshape{2}(InplaceDimShuffle{0,x}.0, <TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/root/miniconda2/envs/envCondaExcl/lib/python2.7/site-packages/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/root/miniconda2/envs/envCondaExcl/lib/python2.7/site-packages/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/root/miniconda2/envs/envCondaExcl/lib/python2.7/site-packages/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/miniconda2/envs/envCondaExcl/lib/python2.7/site-packages/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{2}.0, Reshape{2}.0, TensorType(float32, col), TensorType(float32, matrix), 'local_reshape_dimshuffle')
```

**Comment by nouiz** [comment]
Install Theano from our conda channel

conda install -c mila-udem theano pygpu

it will be the last release 1.0.1 that is very new and should help.
