### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by niraknitsew** [Theano/Theano#6550]
When trying to compile example "logistic regression" from the tutorial, I get following error: 

Traceback (most recent call last):
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\cc.py", line 966, in compile_args
    ret += x.c_compile_args(c_compiler)
TypeError: c_compile_args() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\tensor\blas.py", line 444, in _ldflags
    assert t0 == '-'
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Karin\Miniconda3\Lib\idlelib\condaKARIN\testKARIN.py", line 53, in <module>
    updates=((w, w - 0.1 * gw), (b, b - 0.1 * gb)))
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\vm.py", line 1084, in make_all
    impl=impl))
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\cc.py", line 1297, in cmodule_key
    compile_args=self.compile_args(),
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\cc.py", line 968, in compile_args
    ret += x.c_compile_args()
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\tensor\blas_c.py", line 19, in c_compile_args
    return ldflags(libs=False, flags=True)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\tensor\blas.py", line 389, in ldflags
    include_dir=include_dir)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\utils.py", line 257, in rval
    val = f(*args, **kwargs)
  File "C:\Users\Karin\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\tensor\blas.py", line 447, in _ldflags
    % (t, ldflags_str))
ValueError: ('The following error happened while compiling the node', CGemv{inplace}(AllocEmpty{dtype='float64'}.0, TensorConstant{1.0}, x, w, TensorConstant{0.0}), '\n', 'invalid token "XXX" in ldflags_str: "XXX"')

**Comment by nouiz** [comment]
What Theano flags do you set? In addition, can you give us the result of:

python -c "import theano; print(theano.config.blas.ldflags)"

Which version of Theano do you use and how it was installed?
What is your OS?

**Comment by niraknitsew** [comment]
Hi!
print(theano.config.blas.ldlflags) returns 
AttributeError: 'SubObj' object has no attribute 'ldlflags'.  
I use Theano 1.0.1 installed with conda on Windows 7 
I haven't set any theano flags.

**Comment by niraknitsew** [comment]
Theano_flags is set to blas.ldflags=XXX

**Comment by nouiz** [comment]
Remove that config. It don't make sense as a flag to g++.

Le sam. 13 janv. 2018 08:51, niraknitsew <notifications@github.com> a
écrit :

**Comment by EzeCyviz** [comment]
Please could assist me with find the root of this error

AttributeError: ('The following error happened while compiling the node', Elemwise{mul,no_inplace}(TensorConstant{20}, <TensorType(int64, scalar)>), '\n', "'module' object has no attribute '_get_ndarray_c_version'")
