### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by imransalam** [Theano/Theano#6552]
Using cuDNN version 6021 on context None
Mapped name None to device cuda0: Tesla K80 (0000:00:04.0)
/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
warn("The default mode, 'constant', will be changed to 'reflect' in "
/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/tensor/nnet/conv.py:98: UserWarning: theano.tensor.nnet.conv.conv2d is deprecated. Use theano.tensor.nnet.conv2d instead.
warnings.warn("theano.tensor.nnet.conv.conv2d is deprecated."
/mnt/disks/ext/3D-R2N2/lib/layers.py:354: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
padding=self._padding)
/mnt/disks/ext/3D-R2N2/lib/layers.py:354: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
padding=self._padding)
Traceback (most recent call last):
File "demo.py", line 89, in 
main()
File "demo.py", line 71, in main
voxel_prediction, _ = solver.test_output(demo_imgs)
File "/mnt/disks/ext/3D-R2N2/lib/solver.py", line 220, in test_output
*self.net.activations])
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/compile/function.py", line 317, in function
output_keys=output_keys)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/compile/pfunc.py", line 486, in pfunc
output_keys=output_keys)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/compile/function_module.py", line 1841, in orig_function
fn = m.create(defaults)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/compile/function_module.py", line 1715, in create
input_storage=input_storage_lists, storage_map=storage_map)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gof/link.py", line 699, in make_thunk
storage_map=storage_map)[:3]
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gof/vm.py", line 1084, in make_all
impl=impl))
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 866, in make_thunk
on_unused_input='ignore')
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/compile/function.py", line 317, in function
output_keys=output_keys)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/compile/pfunc.py", line 486, in pfunc
output_keys=output_keys)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/compile/function_module.py", line 1839, in orig_function
name=name)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/compile/function_module.py", line 1519, in init
optimizer_profile = optimizer(fgraph)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gof/opt.py", line 99, in call
return self.optimize(fgraph)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gof/opt.py", line 88, in optimize
ret = self.apply(fgraph, *args, **kwargs)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gof/opt.py", line 242, in apply
sub_prof = optimizer.optimize(fgraph)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gof/opt.py", line 88, in optimize
ret = self.apply(fgraph, *args, **kwargs)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gof/opt.py", line 242, in apply
sub_prof = optimizer.optimize(fgraph)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gof/opt.py", line 88, in optimize
ret = self.apply(fgraph, *args, **kwargs)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gpuarray/opt.py", line 417, in apply
node.outputs)
File "/home/imran_salam_24/anaconda3/envs/my_env/lib/python3.6/site-packages/theano/gpuarray/opt.py", line 1496, in local_gpua_error_convop
"""

AssertionError: ('The following error happened while compiling the node', forall_inplace,gpu,scan_fn}(Shape_i{0}.0, GpuSubtensor{int64:int64:int8}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, 4D)>, <GpuArrayType(float32, matrix)>, <GpuArrayType(float32, matrix)>, <GpuArrayType(float32, matrix)>, <GpuArrayType(float32, matrix)>, InplaceGpuDimShuffle{x,x,0,x,x}.0, InplaceGpuDimShuffle{x,0}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, GpuFromHost.0, InplaceGpuDimShuffle{x,x,0,x,x}.0, GpuFromHost.0, GpuFromHost.0, GpuFromHost.0, GpuFromHost.0, GpuFromHost.0, GpuReshape{4}.0, GpuFromHost.0, GpuFromHost.0, GpuFromHost.0, GpuFromHost.0, GpuReshape{4}.0, InplaceGpuDimShuffle{x,x,0,x,x}.0, GpuFromHost.0, GpuFromHost.0, GpuFromHost.0, GpuFromHost.0, GpuFromHost.0, GpuReshape{4}.0), '\n', '\nConvOp does not work with
the gpuarray backend.\n\nUse the new convolution interface to have GPU convolution working:\ntheano.tensor.nnet.conv2d()\n')

My theanorc file is ;
[global]
floatX = float32
device = cuda0

**Comment by nouiz** [comment]
When building your graph, call "theano.tensor.nnet.conv2d" instead of the old interface "theano.tensor.nnet.conv.conv2d"

**Comment by stalin59** [comment]
Al construir su gráfico, llame a "theano.tensor.nnet.conv2d" en lugar de la interfaz anterior "theano.tensor.nnet.conv.conv2d, como lo reemplazas
