### ISSUE TITLE
error("pygpu was configured but could not be imported", exc_info=True)

### ISSUE THREAD

**Issue by ashleshsortee** [Theano/Theano#6553]
Please help
getting this error
Thanks in advanced

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\logging\__init__.py", line 978, in emit
    msg = self.format(record)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\logging\__init__.py", line 828, in format
    return fmt.format(record)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\logging\__init__.py", line 573, in format
    record.exc_text = self.formatException(record.exc_info)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\logging\__init__.py", line 523, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
Call stack:
  File "test.py", line 2, in <module>
    from theano import function, config, shared, sandbox
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\site-packages\theano\__init__.py", line 118, in <module>
    import theano.sandbox.gpuarray
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Users\ashlesh\Anaconda3\envs\env_name34\lib\site-packages\theano\sandbox\gpuarray\__init__.py", line 131, in <module>
    error("pygpu was configured but could not be imported", exc_info=True)
Message: 'pygpu was configured but could not be imported'

**Comment by nouiz** [comment]
How do you try to install it? I think the anaconda team compiled Theano only for python 3.5 and 3.6 (see the output of "conda search theano"). We provide our own conda packages for python 3.5 and 3.6 too.

Can you update Python? You can just create a new conda env:

```
conda create -n my_new_env python=3.6
source activate my_new_env
conda install theano pygpu
```

Otherwise, check pygpu manuall installation: http://deeplearning.net/software/libgpuarray/installation.html
