### ISSUE TITLE
Theano with CUDA 9.0, cuDNN 7.0.3

### ISSUE THREAD

**Issue by rasto2211** [Theano/Theano#6556]
I'm trying to run theano 1.0.1 from conda with CUDA 9.0 and cuDNN 7.0.3. When I run
```
python3 -c "import theano"
```
I get this message:
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/rasto/.local/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/home/rasto/.local/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/home/rasto/.local/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 117, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File "/home/rasto/.local/lib/python3.5/site-packages/theano/gpuarray/dnn.py", line 132, in _make_handle
    "This can be a sign of a too old driver.", err)
RuntimeError: ('Error creating cudnn handle. This can be a sign of a too old driver.', 4)
```

pygpu seems to be working when I do:
```
DEVICE="cuda0" python3 -c "import pygpu; pygpu.test()"
```

My theanorc:
```
[global]
floatX = float32
device = cuda0

[lib]
cnmem = 1

[nvcc]
flags=-D_FORCE_INLINES
fastmath = True

[blas]
ldflags = -lopenblas

[cuda]
root = /usr/local/cuda-9.0/bin

[dnn]
include_path = /usr/lib/cuda/include
library_path = /usr/lib/cuda/lib64
```

Any idea how to fix this problem?

Btw. I can successfully run tensorflow on this machine.

Thank you for your help in advance.

**Comment by nouiz** [comment]
Maybe deleting your Theano cache will help. On the command line:
theano-cache purge

Otherwise, which version of Tensorflow? Could it be using CUDA 8? If so, this would give weight to the suggested fix. Updating your driver could help.

**Comment by abergeron** [comment]
Make sure the cudnn package that is installed was built for the same version cuda as the one that Theano uses.  Otherwise you can get this error because there is a mixup in cuda versions.

**Comment by rasto2211** [comment]
@nouiz I used tensorflow wheel from [this repository](https://github.com/mind/wheels/releases). I took the wheel compiled with cuda 9.0.

@nouiz the fix with purging theano history did not help.

@abergeron As as far as I understand it correctly tensorflow uses CUDA toolkit and cuDNN so I think that I have cuDNN which is compatible with CUDA 9.0.

**Comment by mese79** [comment]
Hi
I have the very same problem except i'm using `cuda 9.1.85` and `cudnn 7.0.5` .
As @rasto2211 said running `DEVICE="cuda0" python -c "import pygpu; pygpu.test()"` works.
Also i've checked this code before importing theano:
```
from theano import gpuarray as gpu
print('gpu.pygpu_activated:', gpu.pygpu_activated)   # False
gpu.use(device='cuda0')
print('gpu.pygpu_activated:', gpu.pygpu_activated)   # True
```
I guess somehow theano.gpuarray module can not find the device and inititialize it.

**Comment by abergeron** [comment]
What error message do you get?  Can you please post it?

**Comment by mese79** [comment]
I'm trying to run this:
```
from theano import gpuarray as gpu
print('gpu.pygpu_activated:', gpu.pygpu_activated)
gpu.use(device='cuda0')
print('gpu.pygpu_activated:', gpu.pygpu_activated)

from theano import function, config, shared, sandbox
import theano.tensor as T
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], T.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, T.Elemwise) for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')
```
And i get this error:
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/mehdi/Programming/Python/virtual_envs/theano/lib/python3.6/site-packages/Theano-1.0.1+36.g91f71fc2f-py3.6.egg/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/home/mehdi/Programming/Python/virtual_envs/theano/lib/python3.6/site-packages/Theano-1.0.1+36.g91f71fc2f-py3.6.egg/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/home/mehdi/Programming/Python/virtual_envs/theano/lib/python3.6/site-packages/Theano-1.0.1+36.g91f71fc2f-py3.6.egg/theano/gpuarray/__init__.py", line 117, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File "/home/mehdi/Programming/Python/virtual_envs/theano/lib/python3.6/site-packages/Theano-1.0.1+36.g91f71fc2f-py3.6.egg/theano/gpuarray/dnn.py", line 130, in _make_handle
    "This can be a sign of a too old driver.", err)
RuntimeError: ('Error creating cudnn handle. This can be a sign of a too old driver.', 1)
gpu.pygpu_activated: False
Mapped name None to device cuda0: GeForce 920MX (0000:01:00.0)
gpu.pygpu_activated: True

```

**Comment by abergeron** [comment]
The fact that it succeeds the second time might be a red herring.  There might be some state that is not properly cleaned up on error.  But it also doesn't use cudnn the second time.

Can you try to run your script with `LD_DEBUG=libs`, like this:

```
LD_DEBUG=libs python script.py
```

**Comment by mese79** [comment]
here is the log: 
[theano.log](https://github.com/Theano/Theano/files/1696357/theano.log)

**Comment by abergeron** [comment]
I see several potential problems:

 - You are using bumblebee.  This is known to cause problems with cuda.
 - cuda 9.1 *strongly* recommends driver 390+ and you have 384.111 installed.
 - You are most likely using distribution-provided packages.  They very often break compute in subtle ways, enough that we stopped supporting that.

My recommendation would be to try without optirun and, if that doesn't work, try upgrading the driver and finally reinstall cuda with the official runfile.

**Comment by abergeron** [comment]
Also, https://wiki.archlinux.org/index.php/bumblebee#CUDA_without_Bumblebee

**Comment by mese79** [comment]
after updating my nvidia driver to 390.25, test script works fine.
Thanks.

**Comment by nouiz** [comment]
@rasto2211 is your problem also fixed?

**Comment by abergeron** [comment]
@rasto2211 If you still have problems, please try to run with `LD_DEBUG=libs`

**Comment by rasto2211** [comment]
[Here's](https://drive.google.com/file/d/1tRMaqaGgI2HROHofCSfpCdInQJIgQEL7/view?usp=sharing) the debugging log. It's quite long and I did not know where to put it so I put it on google drive.

**Comment by lamblin** [comment]
The debugging log seems to indicate you are using driver 384.111.
As the error message indicates that your driver could be too old, could you try 390.*?

**Comment by abergeron** [comment]
384.111 should be ok for cuda 9.0 (but don't let that discourage you from upgrading).

What is the output of `nvidia-smi`?

**Comment by rasto2211** [comment]
@abergeron Output from nvidia-smi:
```
NVIDIA-SMI 384.111                Driver Version: 384.111
```

**Comment by abergeron** [comment]
That is clearly not the full output.

**Comment by rasto2211** [comment]
Ok, here's the full output. I just did not think that the rest of the output is any useful:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:05:00.0 Off |                  N/A |
| 56%   68C    P2   103W / 200W |   7917MiB /  8112MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      6523      C   python3                                     7907MiB |
+-----------------------------------------------------------------------------+

```

**Comment by abergeron** [comment]
I just realized, but you probably aren't linking with the same cudnn at runtime and at compile time,  because it would look in `/usr/lib/cuda/lib64` when compiling,  but at runtime it finds `/usr/lib/x86_64-linux-gnu/libcudnn.so.7`

This is probably because of your `[dnn]` section.  Can you change it to
```
[dnn]
base_path = /usr/lib/cuda
```
This should set all the paths correctly, including runtime.

**Comment by rasto2211** [comment]
You probably meant:
```
[dnn]
base_path = /usr/local/cuda
```
I've tried it and it did not help.

**Comment by abergeron** [comment]
I meant `/usr/lib/cuda` because of this in you config file:

```
[dnn]
include_path = /usr/lib/cuda/include
library_path = /usr/lib/cuda/lib64
```

But how did you install cudnn?  What was the package/archive name?

**Comment by rasto2211** [comment]
Ups... Then it seems that theano is not using the variables in the section `dnn` at all because `/usr/lib/cuda` does not exists. Cuda is installed in `/usr/local/cuda`.

I did not install the cuda package because I don't have `sudo` on the machine with GPU.

**Comment by wqp89324** [comment]
I'm trying to setup theano 1.0.1 with CUDA 7.5 and cuDNN 6.0 (Windows7). 
I created a new virtual environment with conda and installed required libraries like this:
```
conda install numpy scipy mkl-service libpython m2w64-toolchain
conda install theano pygpu
```
Here are versions of major relavant libraries:
```
theano 1.0.1
python 3.5.5
numpy 1.14.2
scipy 1.0.0
m2w64-toolchain 5.3.0
mkl-service 1.1.2
pygpu 0.7.5
libgpuarray 0.7.5
libpython 2.1
mkl 2018.0.2
```
The way I installed cuDNN is to copy files into corresponding folders inside CUDA folder. Originally I installed CUDA at C:\Program Files\NVIDIA GPU Computing Toolkit, then I copied the CUDA folder to C root.

When I run:
`python -c "import theano"`

I get this message:
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\te\lib\site-packages\theano\gpuarray\__init__.py", line 227, in <module>
    use(config.device)
  File "C:\Program Files\Anaconda3\envs\te\lib\site-packages\theano\gpuarray\__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "C:\Program Files\Anaconda3\envs\te\lib\site-packages\theano\gpuarray\__init__.py", line 121, in init_dev
    dnn.dnn_available.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
b'C:/Program Files/Anaconda3/envs/te/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:/Program: No such file or directory
C:/Program Files/Anaconda3/envs/te/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find Files/Anaconda3/envs/te/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/lib/../lib/default-manifest.o: No such file or directory
collect2.exe: error: ld returned 1 exit status'
```

My theanoc file:
```
[global]
floatX = float32
device = cuda

[dnn]
enabled = True
include_path=C:/CUDA/v7.5/include
library_path=C:/CUDA/v7.5/lib/x64

[blas]
ldflags = C:/Program Files/Anaconda3/envs/t/Library/bin mkl_rt
```

Can somebody help please?

**Comment by lamblin** [comment]
Please stop spamming on unrelated tickets.

**Comment by bilalghanem** [comment]
I have the same issue, I am not able to configure it with cuda: https://stackoverflow.com/questions/57053163/error-theano-gpuarray-pygpu-was-configured-but-could-not-be-imported-or-is-to
