### ISSUE TITLE
problem with  \xe2\x80\x98gpucontext_props\xe2\x80\x99 

### ISSUE THREAD

**Issue by 0x000FF4** [Theano/Theano#6562]
When i try to run my program I get this(notice that I have placed pygpu manually inside dist-packages)

`Using Theano backend.
Using cuDNN version 7005 on context None
Preallocating 4464/8116 Mb (0.550000) on cuda0
Mapped name None to device cuda0: GeForce GTX 1080 (0000:03:00.0)

You can find the C code in this temporary file: /tmp/theano_compilation_error_rtqrYu
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{(1, 1, 1, ...038254604})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2019, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6507, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): In file included from /home/x000ff4/.theano/compiledir_Linux-4.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmpsx8geN/mod.cpp:10:0:. /usr/local/lib/python2.7/dist-packages/pygpu/gpuarray_api.h:23:90: error: \xe2\x80\x98gpucontext_props\xe2\x80\x99 has not been declared.  static struct PyGpuContextObject *(*__pyx_api_f_5pygpu_8gpuarray_pygpu_init)(PyObject *, gpucontext_props *) = 0;.                                                                                           ^. ', '[GpuFromHost<None>(TensorConstant{(1, 1, 1, ...038254604})]')

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{(1, 1, 1, ...019127302})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2019, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6507, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): In file included from /home/x000ff4/.theano/compiledir_Linux-4.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmpqSFSNt/mod.cpp:10:0:. /usr/local/lib/python2.7/dist-packages/pygpu/gpuarray_api.h:23:90: error: \xe2\x80\x98gpucontext_props\xe2\x80\x99 has not been declared.  static struct PyGpuContextObject *(*__pyx_api_f_5pygpu_8gpuarray_pygpu_init)(PyObject *, gpucontext_props *) = 0;.                                                                                           ^. ', '[GpuFromHost<None>(TensorConstant{(1, 1, 1, ...019127302})]')

You can find the C code in this temporary file: /tmp/theano_compilation_error_lU0o_n

You can find the C code in this temporary file: /tmp/theano_compilation_error_I2uXee
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{(1, 1, 1, ...038254604})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2019, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6507, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): In file included from /home/x000ff4/.theano/compiledir_Linux-4.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmppHPURm/mod.cpp:10:0:. /usr/local/lib/python2.7/dist-packages/pygpu/gpuarray_api.h:23:90: error: \xe2\x80\x98gpucontext_props\xe2\x80\x99 has not been declared.  static struct PyGpuContextObject *(*__pyx_api_f_5pygpu_8gpuarray_pygpu_init)(PyObject *, gpucontext_props *) = 0;.                                                                                           ^. ', '[GpuFromHost<None>(TensorConstant{(1, 1, 1, ...038254604})]')

ERROR (theano.gof.opt): Optimization failure due to: constant_folding

You can find the C code in this temporary file: /tmp/theano_compilation_error_dcldKJ
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{(1, 1, 1, ...019127302})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2019, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6507, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): In file included from /home/x000ff4/.theano/compiledir_Linux-4.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmp1FhLuX/mod.cpp:10:0:. /usr/local/lib/python2.7/dist-packages/pygpu/gpuarray_api.h:23:90: error: \xe2\x80\x98gpucontext_props\xe2\x80\x99 has not been declared.  static struct PyGpuContextObject *(*__pyx_api_f_5pygpu_8gpuarray_pygpu_init)(PyObject *, gpucontext_props *) = 0;.                                                                                           ^. ', '[GpuFromHost<None>(TensorConstant{(1, 1, 1, ...019127302})]')

You can find the C code in this temporary file: /tmp/theano_compilation_error_51I40V
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{(1, 1, 1, ...038254604})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2019, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6507, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): In file included from /home/x000ff4/.theano/compiledir_Linux-4.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmpgyrXuP/mod.cpp:10:0:. /usr/local/lib/python2.7/dist-packages/pygpu/gpuarray_api.h:23:90: error: \xe2\x80\x98gpucontext_props\xe2\x80\x99 has not been declared.  static struct PyGpuContextObject *(*__pyx_api_f_5pygpu_8gpuarray_pygpu_init)(PyObject *, gpucontext_props *) = 0;.                                                                                           ^. ', '[GpuFromHost<None>(TensorConstant{(1, 1, 1, ...038254604})]')

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{(1, 1, 1, ...019127302})
You can find the C code in this temporary file: /tmp/theano_compilation_error_NodZ0k
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2019, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6507, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): In file included from /home/x000ff4/.theano/compiledir_Linux-4.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmpoWGc2F/mod.cpp:10:0:. /usr/local/lib/python2.7/dist-packages/pygpu/gpuarray_api.h:23:90: error: \xe2\x80\x98gpucontext_props\xe2\x80\x99 has not been declared.  static struct PyGpuContextObject *(*__pyx_api_f_5pygpu_8gpuarray_pygpu_init)(PyObject *, gpucontext_props *) = 0;.                                                                                           ^. ', '[GpuFromHost<None>(TensorConstant{(1, 1, 1, ...019127302})]')

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{(1, 1, 1, ...038254604})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2019, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6507, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): In file included from /home/x000ff4/.theano/compiledir_Linux-4.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmp8M4HOC/mod.cpp:10:0:. /usr/local/lib/python2.7/dist-packages/pygpu/gpuarray_api.h:23:90: error: \xe2\x80\x98gpucontext_props\xe2\x80\x99 has not been declared.  static struct PyGpuContextObject *(*__pyx_api_f_5pygpu_8gpuarray_pygpu_init)(PyObject *, gpucontext_props *) = 0;.                                                                                           ^. ', '[GpuFromHost<None>(TensorConstant{(1, 1, 1, ...038254604})]')

You can find the C code in this temporary file: /tmp/theano_compilation_error__e3nVu

You can find the C code in this temporary file: /tmp/theano_compilation_error_WkBQw7
Traceback (most recent call last):
  File "/media/x000ff4/aa3f70b2-2e86-4051-8ad1-11098a957956/root/PycharmProjects/forexServer/newModel.py", line 96, in <module>
    padding='same', return_sequences=True))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 467, in add
    layer(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/layers.py", line 968, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 590, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional_recurrent.py", line 379, in build
    constraint=self.kernel_constraint)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 414, in add_weight
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 150, in variable
    value = value.eval()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 522, in eval
    self._fn_cache[inputs] = theano.function(inputs, self)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/vm.py", line 1084, in make_all
    impl=impl))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', GPUA_mrg_uniform{GpuArrayType<None>(float32, 4D),inplace}(<GpuArrayType<None>(int32, matrix)>, TensorConstant{[ 10  10   4 160]}), '\n', 'Compilation failed (return status=1): In file included from /home/x000ff4/.theano/compiledir_Linux-4.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmpkZD_xw/mod.cpp:10:0:. /usr/local/lib/python2.7/dist-packages/pygpu/gpuarray_api.h:23:90: error: \xe2\x80\x98gpucontext_props\xe2\x80\x99 has not been declared.  static struct PyGpuContextObject *(*__pyx_api_f_5pygpu_8gpuarray_pygpu_init)(PyObject *, gpucontext_props *) = 0;.                                                                                           ^. ', '[*1 -> GPUA_mrg_uniform{GpuArrayType<None>(float32, 4D),inplace}(<GpuArrayType<None>(int32, matrix)>, TensorConstant{[ 10  10   4 160]}), *1::1]')

Process finished with exit code 1
`

**Comment by nouiz** [comment]
Can you try the dev version of Theano? The was related change and I think
they are not in the last release

**Comment by nouiz** [comment]
no news, so closing.
