### ISSUE TITLE
ubuntu FileNotFoundError compiledir_Linux-4.13--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.4-64

### ISSUE THREAD

**Issue by edwinlimlx** [Theano/Theano#6577]
tried running ```theano-cache purge``` but met with the above error

checked the dir ```~/.theano/``` is empty.

theano: 1.0.1
Ubuntu: 16
cuda: 9.0
cudnn: 7.0.5.15

```
~/.theanorc

[cuda]
root=/usr/local/cuda/bin

[global]
floatX=float32
device=cuda
OMP_NUM_THREADS=8
openmp=True
#optimizer=fast_run
LD_DEBUG=libs

[blas]
ldflags=-LC:\openblas -lopenblas

[dnn]
include_path=/usr/local/cuda/include
library_path=/usr/local/cuda/lib64
enabled=True

[nvcc]
#optimizer_including=cudnn
fastmath=True
```

Error
```
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:17:00.0)
WARNING (theano.gof.cmodule): A module that was loaded by this ModuleCache can no longer be read from file /home/<USER>/.theano/compiledir_Linux-4.13--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.4-64/tmpbxwvwjjd/mb723a79e77767d1dbdefdd68a32a62b84558aa21c10528d0101d296d860cddc8.so... this could lead to problems.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/<USER>/anaconda3/envs/merlin/lib/python3.6/site-packages/theano/gof/cmodule.py", line 1507, in _on_atexit
    self.clear_unversioned()
  File "/home/<USER>/anaconda3/envs/merlin/lib/python3.6/site-packages/theano/gof/cmodule.py", line 1448, in clear_unversioned
    for filename in os.listdir(self.dirname):
FileNotFoundError: [Errno 2] No such file or directory: '/home/<USER>/.theano/compiledir_Linux-4.13--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.4-64'
```

**Comment by edwinlimlx** [comment]
not having issues with demo in this. please ignore
