### ISSUE TITLE
Can't create function on cygwin with python3.6

### ISSUE THREAD

**Issue by JonnoFTW** [Theano/Theano#6586]
I've compiled theano and libgpuarray on cygwin, but when I run this simple example and set `DEVICE=opencl1:0`:

```python
from theano import function, tensor as T
x = T.dscalar('x')
f = function([x], x+5)
```
I get the output (I've added a line to cmodule.py to show compile cmd): 
```
 f = function([x],x+5)
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -shared -DMS_WIN64 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/usr/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/c_code -L/usr/lib -fvisibility=hidden -o /home/Jonathan/.theano/compiledir_CYGWIN_NT-10.0-2.10.0-0.325-5-3-x86_64-64bit-WindowsPE--3.6.4-64/tmp7mkh3oi1/m03cc3cdee46c6787a94521175277126c8d483d4e6ac5026e943ac127eec8e49a.pyd /home/Jonathan/.theano/compiledir_CYGWIN_NT-10.0-2.10.0-0.325-5-3-x86_64-64bit-WindowsPE--3.6.4-64/tmp7mkh3oi1/mod.cpp -lpython3.6m.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/vm.py", line 1084, in make_all
    impl=impl))
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cmodule.py", line 2368, in compile_str
    return dlimport(lib_filename)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ModuleNotFoundError: No module named 'tmp7mkh3oi1.m03cc3cdee46c6787a94521175277126c8d483d4e6ac5026e943ac127eec8e49a'
```

My ~/.theanorc has:

```
[gcc]
cxxflags = -DMS_WIN64
```

Also, when I run this my compiledir has a tmp folder with the same name as the missing module which then is deleted automatically a short time later.

**Comment by lamblin** [comment]
Unfortunately, Cygwin is not a supported platform, and we stopped active development.
From what I remember, the extension for the compiled module file was not the expected one, maybe you can try to apply #2990 manually.
Also, OpenCL support in libgpuarray is highly experimental.

**Comment by JonnoFTW** [comment]
That fix worked for me, although it still only uses the CPU.

**Comment by lamblin** [comment]
I just accepted the PR, let's consider this solved!

**Comment by lamblin** [comment]
Btw, to make Theano use `opencl1:0` as a device from the command line, that would be `THEANO_FLAGS=device=opencl1:0`, setting `DEVICE` just lets `libgpuarray` know what the default GPU should be, but Theano still attempts to use the CPU first.
