### ISSUE TITLE
unable to remap dll to same address as parent on cygwin

### ISSUE THREAD

**Issue by JonnoFTW** [Theano/Theano#6590]
I'm running:

* cygwin 64 bit,
* python3.6.4 64 bits
* Windows 10
* gcc 6.4.0

I'm trying to run a simple script:

```python
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

model = Sequential([
    Dense(16, input_dim=1, activation='relu'),
    Dense(1, activation='relu')
])
model.compile(optimizer='sgd', loss='mse')
x = np.arange((10,1), dtype=np.int64)
y = np.arange(10, dtype=np.int64)
model.fit(x=x, y=y, epochs=10)
```
It works fine on CPU, but running on GPU I get this error:

```
Using Theano backend.
Mapped name None to device opencl1:0: Tonga
WARNING (theano.gof.cmodule): ModuleCache.refresh() Found key without dll in cache, deleting it. /home/Jonathan/.theano/compiledir_CYGWIN_NT-10.0-2.10.0-0.325-5-3-x86_64-64bit-WindowsPE--3.6.4-64/tmp4nbsbshf/key.pkl
      0 [main] python3.6m 872 child_info_fork::abort: unable to remap mb6e9dce19188bca4cdce3447935db9bc87fa3fd060b1339da3f63535a3d8cd4d.dll to same address as parent (0xC450000) - try running rebaseall
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -DMS_WIN64 -L/usr/x86_64-w64-mingw32/sys-root/mingw/lib/ -L /usr/local/atlas/lib -L /usr/local/lib -llapack -lgfortran -lblas -I /usr/local/unclude -lgpuarray -m64 -march=sandybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-mwaitx -mno-clzero -mno-pku --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=sandybridge -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/usr/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/c_code -L/usr/lib -fvisibility=hidden -o /home/Jonathan/.theano/compiledir_CYGWIN_NT-10.0-2.10.0-0.325-5-3-x86_64-64bit-WindowsPE--3.6.4-64/tmpj4efo9si/m1f456284222bf25c12eeaf92d8a7531647d5b23901273177e0e8e3b445d15dd9.dll /home/Jonathan/.theano/compiledir_CYGWIN_NT-10.0-2.10.0-0.325-5-3-x86_64-64bit-WindowsPE--3.6.4-64/tmpj4efo9si/mod.cpp -lpython3.6m.dll
ERROR (theano.gof.cmodule): [Errno 11] Resource temporarily unavailable
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: Elemwise{sub,no_inplace}(TensorConstant{(1, 1) of 0.59408855}, TensorConstant{(1, 1) of ..0.59408855})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/opt.py", line 2019, in process_node
    replacements = lopt.transform(node)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/tensor/opt.py", line 6507, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/gof/cmodule.py", line 2316, in compile_str
    p_out = output_subprocess_Popen(cmd)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/misc/windows.py", line 77, in output_subprocess_Popen
    p = subprocess_Popen(command, **params)
  File "/usr/lib/python3.6/site-packages/Theano-1.0.1-py3.6.egg/theano/misc/windows.py", line 43, in subprocess_Popen
    proc = subprocess.Popen(command, startupinfo=startupinfo, **params)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

I suspect it's a problem that theano is making a dll that cannot be mapped properly using the python3.6m.dll library. Running rebaseall (as suggested by others having similar problems: https://superuser.com/questions/194529/cygwin-fatal-error-unable-to-remap-what-does-it-mean) does nothing because every time a new temporary .dll is generated in the theano cache (might have something to do with `ModuleCache.refresh()` being run every time.

My `.theanorc` looks like this:
```
[global]
device = opencl1:0
floatX = float32
exception_verbosity = high
[gcc]
cxxflags =  -DMS_WIN64 -L/usr/x86_64-w64-mingw32/sys-root/mingw/lib/ -L /usr/local/atlas/lib -L /usr/local/lib -llapack -lgfortran -lblas -I /usr/local/unclude -lgpuarray -m64
[blas]
ldflags = -lblas -lgfortran
```

Running the examples from the theano ["using the gpu" tutorial](http://deeplearning.net/software/theano/tutorial/using_gpu.html) works fine with this output:

```
Jonathan@p ~
$ ./test_theano.py
Mapped name None to device opencl1:0: Tonga
WARNING (theano.gof.cmodule): ModuleCache.refresh() Found key without dll in cache, deleting it. /home/Jonathan/.theano/compiledir_CYGWIN_NT-10.0-2.10.0-0.325-5-3-x86_64-64bit-WindowsPE--3.6.4-64/tmp6y_66obz/key.pkl
[GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float32, vector)>), HostFromGpu(gpuarray)(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 0.998310 seconds
Result is [1.2317803 1.6187935 1.5227805 ... 2.207718  2.2996776 1.6232328]
Used the gpu

Jonathan@p ~
$ ./test_theano2.py
Mapped name None to device opencl1:0: Tonga
WARNING (theano.gof.cmodule): ModuleCache.refresh() Found key without dll in cache, deleting it. /home/Jonathan/.theano/compiledir_CYGWIN_NT-10.0-2.10.0-0.325-5-3-x86_64-64bit-WindowsPE--3.6.4-64/tmpcavuj10w/key.pkl
[GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float32, vector)>)]
Looping 1000 times took 0.140595 seconds
Result is [1.2317803 1.6187935 1.5227805 ... 2.207718  2.2996776 1.6232328]
Used the gpu
```

**Comment by abergeron** [comment]
Additionally, we do not support cygwin, so if you manage to get it working, great, but we don't have the time to look into why it doesn't work.

The only supported configuration on windows is installing through conda packages.
