### ISSUE TITLE
LSTM Fails to run on OpenCL with TypeError: This is for CUDA arrays.

### ISSUE THREAD

**Issue by JonnoFTW** [Theano/Theano#6591]
I'm trying to run a simple LSTM from the keras sequential guide:
```
#!/usr/bin/env python3
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

data_dim = 16
timesteps = 8
num_classes = 10

# expected input data shape: (batch_size, timesteps, data_dim)
model = Sequential()
model.add(LSTM(32, return_sequences=True,
               input_shape=(timesteps, data_dim)))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32))  # return a single vector of dimension 32
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

# Generate dummy training data
x_train = np.random.random((10000, timesteps, data_dim))
y_train = np.random.random((10000, num_classes))

# Generate dummy validation data
x_val = np.random.random((100, timesteps, data_dim))
y_val = np.random.random((100, num_classes))

model.fit(x_train, y_train,
          batch_size=64, epochs=5,
          validation_data=(x_val, y_val))
```

 It compiles fine, but when it gets to `fit`, I get this error:

```python
Using Theano backend.
Mapped name None to device opencl0:0: Tonga 
Train on 10000 samples, validate on 100 samples
Epoch 1/5
Traceback (most recent call last):
  File "/home/jonno/.pyenv/versions/3.6.4/lib/python3.6/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/home/jonno/.pyenv/versions/3.6.4/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/jonno/.pyenv/versions/3.6.4/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 374, in theano.scan_module.scan_perform.perform (/home/jonno/.theano/compiledir_Linux-4.13--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.4-64/scan_perform/mod.cpp:4293)
  File "pygpu/gpuarray.pyx", line 2252, in pygpu.gpuarray.GpuArray.gpudata.__get__
TypeError: This is for CUDA arrays.
Apply node that caused the error: for{gpu,scan_fn}(Subtensor{int64}.0, GpuSubtensor{:int64:}.0, GpuIncSubtensor{Set;:int64:}.0, GpuIncSubtensor{Set;:int64:}.0, Subtensor{int64}.0, lstm_1/kernel, lstm_1/bias, lstm_1/recurrent_kernel)
Toposort index: 39
Inputs types: [TensorType(int64, scalar), GpuArrayType<None>(float32, 3D), GpuArrayType<None>(float32, 3D), GpuArrayType<None>(float32, 3D), TensorType(int64, scalar), GpuArrayType<None>(float32, matrix), GpuArrayType<None>(float32, vector), GpuArrayType<None>(float32, matrix)]
Inputs shapes: [(), (8, 64, 16), (9, 64, 32), (9, 64, 32), (), (16, 128), (128,), (32, 128)]
Inputs strides: [(), (64, 512, 4), (8192, 128, 4), (8192, 128, 4), (), (512, 4), (4,), (512, 4)]
Inputs values: [array(8), 'not shown', 'not shown', 'not shown', array(8), 'not shown', 'not shown', 'not shown']
Outputs clients: [[Shape(for{gpu,scan_fn}.0), GpuSubtensor{::int64}(for{gpu,scan_fn}.0, Constant{-1}), GpuSubtensor{:int64:}(for{gpu,scan_fn}.0, Constant{-1})], [Shape(for{gpu,scan_fn}.1), GpuSubtensor{::int64}(for{gpu,scan_fn}.1, Constant{-1}), GpuSubtensor{:int64:}(for{gpu,scan_fn}.1, Constant{-1})], [InplaceGpuDimShuffle{0,1,2}(for{gpu,scan_fn}.2), Shape(for{gpu,scan_fn}.2), GpuSubtensor{::int64}(for{gpu,scan_fn}.2, Constant{-1})]]

```

Perhaps theano is generating code that uses gpudata  (used by CUDA) instead  of data or base_data for opencl in pygpu.

The same thing happens when I run with `optimizer=fast_compile`. My .theanorc is:
```
[global]
device = opencl0:0
floatX = float32
optimizer = fast_compile
[blas]
ldflags = -lopenblas
```

**Comment by JonnoFTW** [comment]
@nouiz  this is a separate problem with opencl on ubuntu when calling fit on the model, I should have clarified that.  The other issue is on windows and  happens when you compile a model

**Comment by nouiz** [comment]
We only have a prototype support for OpenCL in Theano. It is not in a usable state. So unless you plan to finish it, it won't help you. We won't finish it due to 

https://groups.google.com/d/msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ

**Comment by JonnoFTW** [comment]
Alright thanks for letting me know. If I have time I'd love to work on it.
