### ISSUE TITLE
 Could not initialize pygpu error with CUDA 9.0 and latest Theano

### ISSUE THREAD

**Issue by michaelklachko** [Theano/Theano#6602]
I have CUDA 9.0 and CuDNN 7.5 on my Ubuntu 16.04, and Tensorflow works fine. In order to install theano, I first installed miniconda, then ran "`conda install theano pygpu`" and it seemed to have installed fine. 

However, here's what I get:
```

$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Using cuDNN version 7005 on context None
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/michael/miniconda2/envs/las/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/home/michael/miniconda2/envs/las/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/home/michael/miniconda2/envs/las/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 159, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 149, in pygpu.blas.gemm
  File "pygpu/blas.pyx", line 47, in pygpu.blas.pygpu_blas_rgemm
pygpu.gpuarray.GpuArrayException: (b'cuLinkAddData: CUDA_ERROR_UNKNOWN: unknown error', 3)
```

Here's the packages I have installed in this environment:

```
$ conda list
# packages in environment at /home/michael/miniconda2/envs/las:
#
# Name                    Version                   Build  Channel
binutils_impl_linux-64    2.28.1               had2808c_3
binutils_linux-64         7.2.0                        26
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py36_0
gcc_impl_linux-64         7.2.0                habb00fd_3
gcc_linux-64              7.2.0                        26
gxx_impl_linux-64         7.2.0                hdf63c60_3
gxx_linux-64              7.2.0                        26
intel-openmp              2018.0.0                      8
libedit                   3.1                  heed3624_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 7.2.0                hdf63c60_3
libgfortran-ng            7.2.0                hdf63c60_3
libgpuarray               0.7.5                h14c3975_0
libstdcxx-ng              7.2.0                hdf63c60_3
mako                      1.0.7            py36h0727276_0
markupsafe                1.0              py36hd9260cd_1
mkl                       2018.0.2                      1
mkl-service               1.1.2            py36h17a0993_4
mkl_fft                   1.0.1            py36h3010b51_0
mkl_random                1.0.1            py36h629b387_0
ncurses                   6.0                  h9df7e31_2
nose                      1.3.7            py36hcdf7029_2
numpy                     1.14.2           py36hdbf6ddf_1
openssl                   1.0.2o               h20670df_0
pip                       10.0.1                   py36_0
pygpu                     0.7.5            py36h14c3975_0
python                    3.6.5                hc3d631a_2
readline                  7.0                  ha6073c6_4
scipy                     1.0.1            py36hfc37229_0
setuptools                39.1.0                   py36_0
six                       1.11.0           py36h372c433_1
sqlite                    3.23.1               he433501_0
theano                    1.0.1            py36h6bb024c_0
tk                        8.6.7                hc745277_3
wheel                     0.31.0                   py36_0
xz                        5.2.3                h5e939de_4
zlib                      1.2.11               ha838bed_2
```

Here's my .theanorc file:
```
[global]
device = cuda0
optimizer_including = cudnn
floatX = float32

[dnn]
include_path = /usr/local/cuda/include
library_path = /usr/local/cuda/lib64

[lib]
cnmem = 0.7

[nvcc]
fastmath = True

[blas]
# Only used for device = cpu
ldflags = -lopenblas

[cuda]
root = /usr/local/cuda/bin
```

Nvidia driver: Driver Version: 384.81

**Comment by lamblin** [comment]
Please use stackoverflow or theano-users for help on how to make Theano work.

Something strange is that you say you have cuDNN 7.5, but Theano seems to find the files for 7.0 (version 7005 corresponds to one of the 7.0 releases).

**Comment by michaelklachko** [comment]
Thanks, I opened a topic on theano-users. CuDNN is 7.0.5
