### ISSUE TITLE
pkl_ultis tries to import from theano.gpuarray.type import _name_for_ctx, when running on CPU

### ISSUE THREAD

**Issue by juancamilog** [Theano/Theano#6608]
I have a couple scripts that crash on a machine that does not have a GPU when trying to save graphs and shared variables with theano.misc.pkl_utils.dump. The exception trace I get is the following

    /home/juancamilog/miniconda2/lib/python2.7/site-packages/skcuda/cublas.py:282: UserWarning: creating CUBLAS context to get version number
    warnings.warn('creating CUBLAS context to get version number')
    Traceback (most recent call last):
    File "/home/juancamilog/ros/aqua_ws/src/robot_learning/scripts/episodic_mbrl_client.py", line 372, in <module>
        exp.save()
    File "/home/juancamilog/workspace/kusanagi/kusanagi/base/Loadable.py", line 141, in save
        t_dump(self.get_instance_state(), f, 2)
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/misc/pkl_utils.py", line 364, in dump
        zipadd(func, zip_file, 'pkl')
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/misc/pkl_utils.py", line 401, in zipadd
        func(temp_file)
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/misc/pkl_utils.py", line 363, in func
        p.dump(obj)
    File "/home/juancamilog/miniconda2/lib/python2.7/pickle.py", line 224, in dump
        self.save(obj)
    File "/home/juancamilog/miniconda2/lib/python2.7/pickle.py", line 271, in save
        pid = self.persistent_id(obj)
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/misc/pkl_utils.py", line 272, in __call__
        return super(PersistentSharedVariableID, self).__call__(obj)
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/misc/pkl_utils.py", line 202, in __call__
        from theano.gpuarray.type import _name_for_ctx
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 33, in <module>
        from . import fft, dnn, opt, extra_ops, multinomial, reduction, sort, rng_mrg, ctc
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/gpuarray/fft.py", line 14, in <module>
        from .opt import register_opt, op_lifter, register_opt2
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/gpuarray/opt.py", line 85, in <module>
        from .linalg import (GpuCusolverSolve, MATRIX_STRUCTURES_SOLVE, GpuCholesky,
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/theano/gpuarray/linalg.py", line 29, in <module>
        from skcuda import cusolver
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/skcuda/cusolver.py", line 22, in <module>
        from . import cublas
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/skcuda/cublas.py", line 290, in <module>
        _cublas_version = int(_get_cublas_version())
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/skcuda/cublas.py", line 283, in _get_cublas_version
        h = cublasCreate()
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/skcuda/cublas.py", line 201, in cublasCreate
        cublasCheckStatus(status)
    File "/home/juancamilog/miniconda2/lib/python2.7/site-packages/skcuda/cublas.py", line 175, in cublasCheckStatus
        raise cublasExceptions[status]
    skcuda.cublas.cublasNotInitialized

I think the problem is this line: https://github.com/Theano/Theano/blob/master/theano/misc/pkl_utils.py#L202 , which should be inside the try/catch statement.

**Comment by abergeron** [comment]
That line is supposed to be safe even on a machine with no GPU/CUDA/pygpu.

However in your case it doesn't work because you have all that installed and yet along with skcuda and yet you can't use any of it.  A short-term solution would be to uninstall skcuda which will stop it from crashing (Theano will realize it's not there and adjust accordingly).

**Comment by nouiz** [comment]
As no news, closing. If you tried the solution, knowing the results would be great.
