### ISSUE TITLE
Optimizer fails on boolean type

### ISSUE THREAD

**Issue by nlgranger** [Theano/Theano#6609]
this line: https://github.com/Theano/Theano/blob/master/theano/tensor/opt.py#L6328
causes the optimizer to fail when the dtype is bool because numpy does not support minus operation on booleans:
`TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead`

The debugger doesn't give me much information, but I suspect the bit of my code that cause it be:
```
        mask = T.ge(t, seq_sizes_)[:, None] \
            + T.ge(T.arange(label_size)[None, :],
                   2 * label_sizes_[:, None] + 1)

        a_t = T.switch(
            isneginf(a_t) + mask, -2e9,
            a_t + y_t[T.arange(batch_sz)[:, None], blanked_labels_])
```

I don't feel confident modifying the code here so I'd like to have an external opinion before hacking into it. Do you need a more complete example?

**Comment by nouiz** [comment]
Which version of Python and NumPy do you use? Older version where supporting this.

**Comment by nouiz** [comment]
Also, can you give the full error message?

**Comment by nlgranger** [comment]
Thanks for looing into it.

* numpy==1.14.3
* Theano == git, 3b51141a46affe9505f0e3f283020820b2c0251e

The error message reads like so:

```
ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(InplaceDimShuffle{0,1,x}.0, InplaceDimShuffle{x,0,1}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/granger/dev/Theano/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4989, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum), out.type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4833, in simplify
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4919, in simplify_constants
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 6328, in add_calculate
    v = reduce(np.add, num, zero) - reduce(np.add, denum, zero)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{ge,no_inplace}.0, Elemwise{ge,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/granger/dev/Theano/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4989, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum), out.type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4833, in simplify
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4919, in simplify_constants
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 6328, in add_calculate
    v = reduce(np.add, num, zero) - reduce(np.add, denum, zero)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{ge,no_inplace}.0, Elemwise{ge,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/granger/dev/Theano/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4989, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum), out.type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4833, in simplify
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4919, in simplify_constants
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 6328, in add_calculate
    v = reduce(np.add, num, zero) - reduce(np.add, denum, zero)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{ge,no_inplace}.0, Elemwise{ge,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/granger/dev/Theano/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4989, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum), out.type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4833, in simplify
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4919, in simplify_constants
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 6328, in add_calculate
    v = reduce(np.add, num, zero) - reduce(np.add, denum, zero)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{ge,no_inplace}.0, Elemwise{ge,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/granger/dev/Theano/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4989, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum), out.type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4833, in simplify
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4919, in simplify_constants
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 6328, in add_calculate
    v = reduce(np.add, num, zero) - reduce(np.add, denum, zero)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{ge,no_inplace}.0, Elemwise{ge,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/granger/dev/Theano/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4989, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum), out.type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4833, in simplify
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4919, in simplify_constants
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 6328, in add_calculate
    v = reduce(np.add, num, zero) - reduce(np.add, denum, zero)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{lt,no_inplace}.0, <TensorType(bool, matrix)>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/granger/dev/Theano/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4989, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum), out.type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4833, in simplify
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4919, in simplify_constants
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 6328, in add_calculate
    v = reduce(np.add, num, zero) - reduce(np.add, denum, zero)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

ERROR (theano.gof.opt): Optimization failure due to: local_add_canonizer
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(Elemwise{lt,no_inplace}.0, <TensorType(bool, matrix)>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/granger/dev/Theano/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4989, in transform
    num, denum = self.simplify(list(orig_num), list(orig_denum), out.type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4833, in simplify
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 4919, in simplify_constants
    out_type=out_type)
  File "/home/granger/dev/Theano/theano/tensor/opt.py", line 6328, in add_calculate
    v = reduce(np.add, num, zero) - reduce(np.add, denum, zero)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Comment by nlgranger** [comment]
The graph is produced by an OpFromGragh with inline=True, probably from a theano.scan inside that...
I can try to isolate the problem more precisely by ablation in the code but if you have suggestions to avoid working blindly they are welcome.

**Comment by nouiz** [comment]
Does your graph run? I think this is just "warning". If it run, you can use it. It just mean you are loosing some optimization.

**Comment by nouiz** [comment]
I'm able to reproduce this error like this:
```
import theano
c0 = theano.tensor.constant([True])
c1 = theano.tensor.constant([True])
theano.function([], c0 + c1)
```

**Comment by nouiz** [comment]
NumPy changed its API. Now "bool - bool" is not working anymore.

I did a PR to fix this: https://github.com/Theano/Theano/pull/6615

Can you test it?

**Comment by abergeron** [comment]
The fix was merged
