### ISSUE TITLE
Theano 1.0.2: Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by bilymufac** [Theano/Theano#6638]
I just installed the latest theano. It works well without configuration to use gpu. I use anaconda operated in windows 10 with nvidia geforce 980.

To use gpu, I create the .theanorc file as follows:
```
[global]
floatx = float32
device = cuda0
mode = FAST_RUN
optimizer_including=cudnn

[blas]
ldflags = -LC:\Anaconda3\Library\bin -lcublas64_80

[nvcc]
fastmath = True

[dnn]
enabled = True
include_path = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include
library_path = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\lib\x64

[lib]
cnmem=0
```
Then, I got the error as follows:
```
(base) C:\Users\cerdas>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\cerdas\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 227, in <module>
    use(config.device)
  File "C:\Users\cerdas\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "C:\Users\cerdas\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 121, in init_dev
    dnn.dnn_available.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
b'C:\\Users\\cerdas\\AppData\\Local\\Temp\\try_flags_bowiuepk.c:4:19: fatal error: cudnn.h: No such file or directory\r\ncompilation terminated.\r\n'
```

**Comment by abergeron** [comment]
Where did you install cuDNN?

**Comment by bilymufac** [comment]
Thanks for notice me about cuDNN, i haven't installing cudnn before, so I download and place the file into the proper directory, so it can be solve my problem.

**Comment by VaibhavManojTiwari** [comment]
Where did u place it man?

**Comment by stephanefschwarz** [comment]
> Thanks for notice me about cuDNN, i haven't installing cudnn before, so I download and place the file into the proper directory, so it can be solve my problem.

Can you describe what did you do exactly?
