### ISSUE TITLE
Error import theano in SUSE

### ISSUE THREAD

**Issue by L619** [Theano/Theano#6666]
I install theano without error(only use naked python,without conda),  but when I use the command "import theano", there is an error as following.  Could you please fix it? Thank you.
My linux system is:
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"

The python version is 3.6.7

>>> import theano
You can find the C code in this temporary file: /tmp/theano_compilation_error_w72urbne
library inux/7/include-fixed/limits.h:194, is not found.
library inux/7/include-fixed/syslimits.h:7, is not found.
library inux/7/include-fixed/limits.h:34, is not found.
library inux/7/include-fixed/limits.h:194, is not found.
library inux/7/include-fixed/syslimits.h:7, is not found.
library inux/7/include-fixed/limits.h:34, is not found.
Traceback (most recent call last):
  File "/opt/python3/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python3/lib/python3.6/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/opt/python3/lib/python3.6/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "/opt/python3/lib/python3.6/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/opt/python3/lib/python3.6/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "/opt/python3/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "/opt/python3/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2388, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): In file included from /opt/python3/include/python3.6m/pyport.h:194:0,.                  from /opt/python3/include/python3.6m/Python.h:53,.                  from /root/.theano/compiledir_Linux-4.4--default-x86_64-with-SuSE-12-x86_64-x86_64-3.6.7-64/lazylinker_ext/mod.cpp:1:. /usr/include/c++/7/math.h:65:12: error: ‘constexpr bool std::isinf(double)’ conflicts with a previous declaration.  using std::isinf;.             ^~~~~. In file included from /usr/include/features.h:347:0,.                  from /usr/include/limits.h:27,.                  from /usr/lib64/gcc/x86_64-suse-linux/7/include-fixed/limits.h:194,.                  from /usr/lib64/gcc/x86_64-suse-linux/7/include-fixed/syslimits.h:7,.                  from /usr/lib64/gcc/x86_64-suse-linux/7/include-fixed/limits.h:34,.                  from /opt/python3/include/python3.6m/Python.h:11,.                  from /root/.theano/compiledir_Linux-4.4--default-x86_64-with-SuSE-12-x86_64-x86_64-3.6.7-64/lazylinker_ext/mod.cpp:1:. /usr/include/bits/mathcalls.h:202:1: note: previous declaration ‘int isinf(double)’.  __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));.  ^. In file included from /opt/python3/include/python3.6m/pyport.h:194:0,.                  from /opt/python3/include/python3.6m/Python.h:53,.                  from /root/.theano/compiledir_Linux-4.4--default-x86_64-with-SuSE-12-x86_64-x86_64-3.6.7-64/lazylinker_ext/mod.cpp:1:. /usr/include/c++/7/math.h:66:12: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration.  using std::isnan;.             ^~~~~. In file included from /usr/include/features.h:347:0,.                  from /usr/include/limits.h:27,.                  from /usr/lib64/gcc/x86_64-suse-linux/7/include-fixed/limits.h:194,.                  from /usr/lib64/gcc/x86_64-suse-linux/7/include-fixed/syslimits.h:7,.                  from /usr/lib64/gcc/x86_64-suse-linux/7/include-fixed/limits.h:34,.                  from /opt/python3/include/python3.6m/Python.h:11,.                  from /root/.theano/compiledir_Linux-4.4--default-x86_64-with-SuSE-12-x86_64-x86_64-3.6.7-64/lazylinker_ext/mod.cpp:1:. /usr/include/bits/mathcalls.h:235:1: note: previous declaration ‘int isnan(double)’.  __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));.  ^.

**Comment by L619** [comment]
@abergeron , sorry, I can't see the program.  What is the program ? Thank you.        "Can you test if you are able to compile this program"
