### ISSUE TITLE
ERROR: Failure: pygpu.gpuarray.GpuArrayException

### ISSUE THREAD

**Issue by cedoard** [Theano/Theano#6668]
Hi to everyone,
I had the [same issue](https://github.com/Theano/Theano/issues/6006) when I tried to run keras/theano on gpu, I followed instructions and set that environment variables. 
Right now I get a new error when I run `pygpu.test()`:

```
Traceback (most recent call last):
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/secarbone/miniconda3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/secarbone/miniconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/pygpu/tests/test_operations.py", line 4, in <module>
    from .support import (gen_gpuarray, context, SkipTest)
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "/Library/Frameworks/CUDA.framework/CUDA": dlopen(/Library/Frameworks/CUDA.framework/CUDA, 5): image not found'
```

    ```ERROR: Failure: GpuArrayException (b'Could not load "/Library/Frameworks/CUDA.framework/CUDA": dlopen(/Library/Frameworks/CUDA.framework/CUDA, 5): image not found')```

My system is Mac Os High Sierra 10.13 with NVIDIA GeForce GT 330M. I installed _cuda 10.0.130_ and _cudnn 10.0_.
This is my _.theanorc_ file:

    [global]
    floatX = float32
    device = gpu
    force_device = True
    optimizer_including=cudnn
    
    [nvcc]
    fastmath = True
    
    [cuda]
    root=Users/secarbone/cuda 
------------------------------------------------------------------------------------------------------
**_EDIT_**: I re-installed Cuda (using .dmg file, not from terminal), I followed [Invidia installation guide](https://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html) and applied this tips:

> 1. Uncheck System Preferences > Energy Saver > Automatic Graphic Switch
> 2. Drag the Computer sleep bar to Never in System Preferences > Energy Saver
 
Now i get this new error: `Segmentation fault: 11`

```
 >>> import pygpu
>>> pygpu.test()
pygpu is installed in /Users/secarbone/miniconda3/lib/python3.6/site-packages/pygpu
NumPy version 1.15.4
NumPy relaxed strides checking option: True
NumPy is installed in /Users/secarbone/miniconda3/lib/python3.6/site-packages/numpy
Python version 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
nose version 1.3.7
Segmentation fault: 11
```

**Comment by justanhduc** [comment]
@hubner27 I believe the latest CUDA and cuDNN supported by Theano is 9.0 and 7.1 respectively. https://github.com/Theano/Theano/blob/master/HISTORY.txt
