### ISSUE TITLE
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by kajitkiller** [Theano/Theano#6682]
I have looked extensively through the other issues listed and have not been able to resolve this. I am using Windows 10 with Cuda 10 and Anaconda Navigator 2.7. 

ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\liamf\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 227, in <module>
    use(config.device)
  File "C:\Users\liamf\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "C:\Users\liamf\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 99, in init_dev
    **args)
  File "pygpu\gpuarray.pyx", line 658, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
GpuArrayException: Could not load "nvrtc64_70.dll": The specified module could not be found.

**Comment by londere** [comment]
You should compile libgpuarray and then install it to python if you use conda you could apply:
`conda install pygpu`
you should read the following info available:
http://deeplearning.net/software/libgpuarray/installation.html
