### ISSUE TITLE
Can't install theano 1.0.4 with pip 19.0.1

### ISSUE THREAD

**Issue by vineus** [Theano/Theano#6687]
Install fails with python 2.7 and pip 19:

```bash
# python --version
Python 2.7.15
# pip --version
pip 19.0.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
# pip install theano==1.0.4                                                                                                                                      
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting theano==1.0.4
  Using cached https://files.pythonhosted.org/packages/7d/c4/6341148ad458b6cd8361b774d7ee6895c38eab88f05331f22304c484ed5d/Theano-1.0.4.tar.gz                                                               
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-GeHbhQ/theano/setup.py", line 17, in <module>
        import versioneer
      File "versioneer.py", line 281, in <module>
        import configparser
      File "/usr/local/lib/python2.7/site-packages/configparser.py", line 12, in <module>
        from backports.configparser import (
      File "/usr/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 139, in <module>                                                                                               
        from backports.configparser.helpers import OrderedDict as _default_dict
      File "/usr/local/lib/python2.7/site-packages/backports/configparser/helpers.py", line 193, in <module>                                                                                                
        dict(__metaclass__=abc.ABCMeta),
      File "/usr/local/lib/python2.7/abc.py", line 87, in __new__
        cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
    TypeError: type() argument 1 must be string, not newstr

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-GeHbhQ/theano/
```

**Comment by vineus** [comment]
Sorry, mea culpa. It was an issue with configparser (upgrading from 3.5.1 to 3.7.0 broke the install), nothing to do with theano.
