### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by jtrakk** [Theano/Theano#6728]
Hello I am having trouble importing theano on python 3.6.1.

```
lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.10 (Final)
Release:	6.10
Codename:	Final
```

```
user@login2:tmp$ venv/bin/python -m pip install --upgrade git+https://github.com/Theano/Theano.git
Collecting git+https://github.com/Theano/Theano.git
  Cloning https://github.com/Theano/Theano.git to /work/tmp/pip-req-build-z1vi0eae
  Running command git clone -q https://github.com/Theano/Theano.git /work/tmp/pip-req-build-z1vi0eae
Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in ./venv/lib/python3.6/site-packages (from Theano==1.0.4+21.g8f510a1) (1.17.3)
Requirement already satisfied, skipping upgrade: scipy>=0.14 in ./venv/lib/python3.6/site-packages (from Theano==1.0.4+21.g8f510a1) (1.3.1)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in ./venv/lib/python3.6/site-packages (from Theano==1.0.4+21.g8f510a1) (1.12.0)
Building wheels for collected packages: Theano
  Building wheel for Theano (setup.py) ... done
  Created wheel for Theano: filename=Theano-1.0.4+21.g8f510a1-cp36-none-any.whl size=2667467 sha256=211933a51b27a1167a1f875763a1848e93e5b0dfa6bb526f0549d6e48895de83
  Stored in directory: /work/tmp/pip-ephem-wheel-cache-lkx7q629/wheels/14/72/17/35fc1366380e8e05fc8ed5d44e24a2da28ef975aa4be6aaa17
Successfully built Theano
Installing collected packages: Theano
  Found existing installation: Theano 1.0.4
    Uninstalling Theano-1.0.4:
      Successfully uninstalled Theano-1.0.4
Successfully installed Theano-1.0.4+21.g8f510a1
user@login2:tmp$ venv/bin/python -c 'import theano'

You can find the C code in this temporary file: /tmp/theano_compilation_error_ufgau8cl
Traceback (most recent call last):
  File "/u/home/a/user/tmp/venv/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/home/a/user/tmp/venv/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/u/home/a/user/tmp/venv/lib/python3.6/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/u/home/a/user/tmp/venv/lib/python3.6/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "/u/home/a/user/tmp/venv/lib/python3.6/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/u/home/a/user/tmp/venv/lib/python3.6/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "/u/home/a/user/tmp/venv/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "/u/home/a/user/tmp/venv/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2396, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against symbol `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(boolobject.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(bytearrayobject.o): relocation R_X86_64_32 against symbol `_PyByteArray_empty_string' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(bytesobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(exceptions.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(floatobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(funcobject.o): relocation R_X86_64_32S against symbol `PyCode_Type' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(iterobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(listobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(longobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(dictobject.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(memoryobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(methodobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(moduleobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(object.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(obmalloc.o): relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(capsule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(rangeobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(setobject.o): relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(sliceobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(structseq.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(tupleobject.o): relocation R_X86_64_32 against symbol `_PyEval_SliceIndex' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(typeobject.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(unicodeobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(unicodectype.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(weakrefobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_warnings.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(bltinmodule.o): relocation R_X86_64_32S against symbol `PyFilter_Type' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(ceval.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(compile.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(codecs.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(errors.o): relocation R_X86_64_32S against symbol `PyTraceBack_Type' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(future.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(getargs.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(import.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(importdl.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(marshal.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(modsupport.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(peephole.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(pyhash.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(pylifecycle.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(pystate.o): relocation R_X86_64_32S against symbol `_PyEval_EvalFrameDefault' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(pythonrun.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(pytime.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(random.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(symtable.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(sysmodule.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(traceback.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(pystrtod.o): relocation R_X86_64_32S against symbol `_Py_ctype_tolower' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(dtoa.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(formatter_unicode.o): relocation R_X86_64_32S against symbol `_Py_ctype_table' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(fileutils.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(dynload_shlib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(thread.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(getpath.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(gcmodule.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_threadmodule.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(posixmodule.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(errnomodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(pwdmodule.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_sre.o): relocation R_X86_64_32S against symbol `_Py_ctype_tolower' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_codecsmodule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_weakref.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_functoolsmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_operator.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_collectionsmodule.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(itertoolsmodule.o): relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(atexitmodule.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(signalmodule.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_stat.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(timemodule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_localemodule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_iomodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(iobase.o): relocation R_X86_64_32 against symbol `_Py_FalseStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(fileio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(bytesio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(bufferedio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(textio.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(stringio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(zipimport.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(faulthandler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(_tracemalloc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(hashtable.o): relocation R_X86_64_32 against symbol `PyMem_RawFree' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(symtablemodule.o): relocation R_X86_64_32 against symbol `PyUnicode_FSDecoder' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(xxsubtype.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(getbuildinfo.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(acceler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(grammar1.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(myreadline.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(parsetok.o): relocation R_X86_64_32S against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(tokenizer.o): relocation R_X86_64_32S against symbol `PyUnicode_Type' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(accu.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(bytes_methods.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(cellobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(classobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(codeobject.o): relocation R_X86_64_32S against symbol `PyUnicode_Type' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(complexobject.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(descrobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(enumobject.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(genobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(fileobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(frameobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(odictobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(namespaceobject.o): relocation R_X86_64_32S against symbol `_PyNamespace_Type' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(Python-ast.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(ast.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(getcopyright.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(getplatform.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(getversion.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(mystrtoul.o): relocation R_X86_64_32S against symbol `_Py_ctype_table' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(structmember.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(parser.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: /u/local/apps/python/3.6.1/lib/libpython3.6m.a(getcompiler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /u/local/compilers/gcc/4.9.3/bin/ld: final link failed: nonrepresentable section on output. collect2: error: ld returned 1 exit status. 

```

**Comment by IveJ** [comment]
Hi Issuer,

U can try cleae Theano cache and rebase git following doc/update.txt to
troubleshooting.

**Comment by IveJ** [comment]
Hi Issuer,

Ofcourse you did attemp to do through install_centos6.txt instruction.

**Comment by nouiz** [comment]
I think you need to install a package python-dev or python-devel or similar.
See the install_centos6 installation instruction for the exact missing package name

**Comment by jtrakk** [comment]
I have switched to conda, which worked out of the box.
