### ISSUE TITLE
theano.gpuarray.type.ContextNotDefined

### ISSUE THREAD

**Issue by jeongmeani** [Theano/Theano#6740]
Hi, 
i'm new user of Theano.
currently, i loaded pickle i got from other site.
but it gave me error message like below.

Traceback (most recent call last):

  File "cnn.py", line 18, in <module>
    classifier  = cPickle.load(gzip.open(modelFile))
  File "/home/jmkim/.local/lib/python2.7/site-packages/theano/gpuarray/type.py", line 899, in GpuArray_unpickler
    ctx = get_context(ctx_name)
  File "/home/jmkim/.local/lib/python2.7/site-packages/theano/gpuarray/type.py", line 104, in get_context
    raise ContextNotDefined("context name %s not defined" % (name,))
**theano.gpuarray.type.ContextNotDefined: context name None not defined**

is the pickle file wrong? or should i correct this using other option or library?

Thanks

**Comment by danny305** [comment]
I am having the same problem.

**Comment by outside-BUPT** [comment]
Me too ..

**Comment by Kym1410** [comment]
me too...

**Comment by li2nan** [comment]
me too..........

**Comment by narein97** [comment]
Solved this issue by configuring theano to use the gpu as so

` import os
data_type = 'float32'
os.environ["JAX_PLATFORM_NAME"] = "gpu"
os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"]="platform"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"]="false"
os.environ["THEANO_FLAGS"] = 'device=cuda1,floatX=float32,dnn.base_path=/usr/bin/nvcc,openmp=True,force_device=True'
import theano`

This gives a message as so

`Mapped name None to device cuda1: NVIDIA GeForce GTX 1080 Ti (0000:09:00.0)`

After this, you should be able to load the pickle file
