### ISSUE TITLE
 error: /usr/local/cuda-10.1/lib64/libcudnn.so: ELF section name out of range\ncollect2: error: ld returned 1 exit status\n'

### ISSUE THREAD

**Issue by Light--** [Theano/Theano#6742]
# my code
```
$ python3.6
Python 3.6.9 (default, Jul  3 2019, 15:36:16) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Theano-1.0.4-py3.6.egg/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/usr/local/lib/python3.6/dist-packages/Theano-1.0.4-py3.6.egg/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/usr/local/lib/python3.6/dist-packages/Theano-1.0.4-py3.6.egg/theano/gpuarray/__init__.py", line 121, in init_dev
    dnn.dnn_available.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
b'/usr/bin/ld: error: /usr/local/cuda-10.1/lib64/libcudnn.so: ELF section name out of range\ncollect2: error: ld returned 1 exit status\n'
>>> 

```

# my theano configuration
```
[global]
device = cuda
floatX = float32
[dnn]
enabled = True
include_path=/usr/local/cuda-10.1/include
library_path=/usr/local/cuda-10.1/lib64

```

# my theano package
```
$ pip3.6 show theano
Name: Theano
Version: 1.0.4
Summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
Home-page: http://deeplearning.net/software/theano/
Author: LISA laboratory, University of Montreal
Author-email: theano-dev@googlegroups.com
License: BSD
Location: /usr/local/lib/python3.6/dist-packages/Theano-1.0.4-py3.6.egg
Requires: numpy, scipy, six
Required-by: 

```

**Comment by nouiz** [comment]
Maybe this page will help you:

http://www.deeplearning.net/software/theano/library/gpuarray/dnn.html

You must install cudnn separately of Theano. Also make sure to install a version supported by Theano.
Theano isn’t maintained and probably doesn’t support the most recent version of cudnn.
