### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rlloretb** [Theano/Theano#6756]
Python 3.7
MacOS Mojave
theano: 1.0.4
pymc3: 3.8

**While running this code in pymc3:**
import pymc3 as pm
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as ss

from matplotlib import animation, get_backend

meanX = 1.5
stdX = 1.2
X = np.random.normal(meanX, stdX, size = 1000)
plt.hist(X, bins = 50)

with pm.Model() as model:
    **mean = pm.Normal("mean", mu = 1, sigma = 2)**
    std = pm.Normal("std", mu = 1, sigma = 2)
    x = pm.Normal("X", mu = mean, sigma = std, observed = X)
    step = pm.Metropolis()
    trace = pm.sample(5000, step = step)

**I encounter the following compilation error:**

You can find the C code in this temporary file: /var/folders/d7/s84vcfs95q50khg3886tk52r0000gp/T/theano_compilation_error_bpzwglnx
Traceback (most recent call last):

  File "/Users/lloretroger/Documents/GS_CL_OPT/bayesian_test.py", line 25, in <module>
    mean = pm.Normal("mean", mu = 1, sigma = 2)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 46, in __new__
    dist = cls.dist(*args, **kwargs)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 57, in dist
    dist.__init__(*args, **kwargs)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/pymc3/distributions/continuous.py", line 470, in __init__
    self.variance = 1. / self.tau

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/tensor/var.py", line 203, in __rtruediv__
    return theano.tensor.basic.true_div(other, self)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/op.py", line 670, in __call__
    no_recycling=[])

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/cc.py", line 1624, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/cc.py", line 1527, in compile_cmodule
    preargs=preargs)

  File "/Users/lloretroger/opt/miniconda3/envs/py37/lib/python3.7/site-packages/theano/gof/cmodule.py", line 2396, in compile_str
    (status, compile_stderr.replace('\n', '. ')))

**Exception: ('Compilation failed (return status=1): ld: unknown option: -platform_version. clang-10: error: linker command failed with exit code 1 (use -v to see invocation). ', '[Elemwise{true_div,no_inplace}(TensorConstant{1.0}, TensorConstant{0.25})]')**

**Comment by rlloretb** [comment]
Solved by installing on fresh environment:
Install first spyder (if you need it). Then,
conda install numpy scipy mkl
conda install theano pygpu
conda install pymc3
