### ISSUE TITLE
ImportError: ('The following error happened while compiling the node', BatchedDot(InplaceDimShuffle{0,x,x}.0, InplaceDimShuffle{0,x,x}.0), '\n', '/home/ubuntu/.theano/compiledir_Linux-5.4--aws-x86_64-with-Ubuntu-18.04-bionic-x86_64-2.7.17-64/tmpzf5vI0/72293d6e71ebd97c85893a86d22f2f4e642e5161c3a1571912fe0467ee2def6b.so: undefined symbol: dgemm_', '[BatchedDot(<TensorType(float64, (False, True, True))>, <TensorType(float64, (False, True, True))>)]')

### ISSUE THREAD

**Issue by Siaan** [Theano/Theano#6766]
Using python 2.7.17 on Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1029-aws x86_64)
backports.functools-lru-cache==1.6.1
cycler==0.10.0
dill==0.3.2
kiwisolver==1.1.0
Lasagne @ https://github.com/Lasagne/Lasagne/archive/master.zip
matplotlib==2.2.5
numpy==1.16.6
pandas==0.24.2
pkg-resources==0.0.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
scipy==1.2.3
six==1.15.0
subprocess32==3.5.4
Theano==1.0.5

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
-2420.562687085329
Traceback (most recent call last):
  File "script.py", line 209, in <module>
    pM, wgt, sgvb = train_recmodel(y_data, x_data)
  File "script.py", line 108, in train_recmodel
    givens={sgvb.Y: batch_y},
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1624, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1527, in compile_cmodule
    preargs=preargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2420, in compile_str
    return dlimport(lib_filename)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 317, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', BatchedDot(InplaceDimShuffle{0,x,x}.0, InplaceDimShuffle{0,x,x}.0), '\n', '/home/ubuntu/.theano/compiledir_Linux-5.4--aws-x86_64-with-Ubuntu-18.04-bionic-x86_64-2.7.17-64/tmpzf5vI0/72293d6e71ebd97c85893a86d22f2f4e642e5161c3a1571912fe0467ee2def6b.so: undefined symbol: dgemm_', '[BatchedDot(<TensorType(float64, (False, True, True))>, <TensorType(float64, (False, True, True))>)]')

**Comment by Siaan** [comment]
Forgot to install BLAS dependency
