### ISSUE TITLE
windows errors for “ImportError: DLL load failed while importing m885ff006a95d626dac547a7bdfdb471bbf058622ece2b4435e42316c4012ea56: 找不到指定的模块”

### ISSUE THREAD

**Issue by v-yunbin** [Theano/Theano#6778]
its normal in linux，but met errors in windows：
```
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Loading model parameters...
Building model...
ERROR (theano.gof.opt): Optimization failure due to: local_subtensor_merge
ERROR (theano.gof.opt): node: Subtensor{:int64:}(Subtensor{int64::}.0, ScalarFromTensor.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\tensor\opt.py", line 3088, in local_subtensor_merge
    merge_two_slices(slice1,
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\tensor\opt.py", line 3039, in merge_two_slices
    start = pre_greedy_local_optimizer(list_opt, start)
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\opt.py", line 2922, in pre_greedy_local_optimizer
    final_outs, optimized_nodes = local_recursive_function(
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\opt.py", line 2891, in local_recursive_function
    outs, optimized_vars = local_recursive_function(
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\opt.py", line 2891, in local_recursive_function
    outs, optimized_vars = local_recursive_function(
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\opt.py", line 2907, in local_recursive_function
    ret = opt.transform(node)
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\tensor\opt.py", line 6515, in constant_folding
    thunk = node.op.make_thunk(node, storage_map, compute_map,
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\op.py", line 954, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map,
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\op.py", line 857, in make_c_thunk
    outputs = cl.make_thunk(input_storage=node_input_storage,
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py", line 1215, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py", line 1153, in __compile__
    thunk, module = self.cthunk_factory(error_storage,
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py", line 1623, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py", line 1520, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py", line 2420, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py", line 317, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed while importing m885ff006a95d626dac547a7bdfdb471bbf058622ece2b4435e42316c4012ea56: 找不到指定的模块。

ERROR (theano.gof.opt): Optimization failure due to: local_subtensor_merge
ERROR (theano.gof.opt): node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
````

**Comment by linqitong** [comment]
你好，我也遇到了一样的问题。能问一下你当时是如何解决的呢
