### ISSUE TITLE
max recusion limit

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#689]
Theano can have a max recursion limit error from Python. The current work around is to use this code:

`import sys
sys.setrecursionlimit(50000)`

Here is code that reproduce the problem:

```
from numpy import *
from theano import *
import theano.tensor as t
from __builtin__ import map

factors = []

sd = t.dscalar()

means = t.dvector()

for i in range(85):
    factors.append( -0.5 * sd ** -2  * (ones(10)-means[i]) ** 2 + 0.5 * t.log(0.5 * (sd ** -2) / pi))

factors = map(t.sum, factors)
logp = t.add(*factors)

vars =[sd, means]
dlogp = function(vars, [grad(logp, v) for v in vars])
```

The stack trace tell that it is in a call to cPickle.dump when we try to create the key for the code cache. Here is the stack trace:

``````
Traceback (most recent call last):
  File "test_max_recursion.py", line 19, in <module>
    dlogp = function(vars, [grad(logp, v) for v in vars])
  File "/u/bastienf/repos/Theano/theano/compile/function.py", line 123, in function
    profile=profile)
  File "/u/bastienf/repos/Theano/theano/compile/pfunc.py", line 474, in pfunc
    on_unused_input=on_unused_input)
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1378, in orig_function
    defaults)
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1208, in create
    _fn, _i, _o = self.linker.make_thunk(input_storage = input_storage_lists)
  File "/u/bastienf/repos/Theano/theano/gof/link.py", line 380, in make_thunk
    output_storage = output_storage)[:3]
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 1453, in make_all
    no_recycling)]
  File "/u/bastienf/repos/Theano/theano/gof/op.py", line 576, in make_thunk
    output_storage=node_output_storage)
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 909, in make_thunk
    keep_lock=keep_lock)
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 852, in __compile__
    keep_lock=keep_lock)
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 1276, in cthunk_factory
    key=key, fn=self.compile_cmodule_by_step, keep_lock=keep_lock)
  File "/u/bastienf/repos/Theano/theano/gof/cmodule.py", line 962, in module_from_key
    key_data.save_pkl()
  File "/u/bastienf/repos/Theano/theano/gof/cmodule.py", line 432, in save_pkl
    protocol=cPickle.HIGHEST_PROTOCOL)
RuntimeError: maximum recursion depth exceeded in cmp```
``````

**Comment by aaamourao** [comment]
Hi I got exactly this when running the following project [dblN/stochastic_depth_keras](https://github.com/dblN/stochastic_depth_keras)
I'm running it on a virtual environment with the following libraries installed
```
Keras==1.0.0
numpy==1.11.0
PyYAML==3.11
scipy==0.17.0
six==1.10.0
Theano==0.8.1
```

**Comment by aaamourao** [comment]
My recursion limit:
```python
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getrecursionlimit()
1000
```

**Comment by nouiz** [comment]
Just to be sure, when you use the proposed work around, it fix for you too?

```
import sys;
sys.setrecursionlimit(40000)
```

**Comment by aaamourao** [comment]
@nouiz Yep, I think it was kind of a pilot error. I thought it could be a related bug, but it was just a matter of increasing the recursion limit to `2800`.
